DECLARE
	TYPE t_tabs IS TABLE OF VARCHAR2(30); --table names
	v_list t_tabs := t_tabs(
		'BSCI_COMPANY_STAGING',
		'CHILD_CMS_COMPANY_STAGING',
		'CHILD_CMS_COMPANY_STAGING_1',
		'CHILD_CMS_COMPANY_STAGING_4',
		'CMS_COMPANY_STAGING',
		'CMS_COMPANY_STAGING_2',
		'CMS_COMPANY_STAGING_3',
		'CMS_COMPANY_STAGING_4',
		'CMS_STAGING',
		'CMS_STAGING',
		'COMPANY_DATA',
		'COMPANY_DATA_2',
		'COMPANY_DATA_4',
		'COMPANY_EXTRA',
		'COMPANY_EXTRA',
		'COMPANY_PRODUCT',
		'COMPANY_PRODUCT',
		'COMPANY_PURCHASER_STAGING',
		'COMPANY_SALES_ORG',
		'COMPANY_STAGING',
		'COMPANY_TURNOVER',
		'MERCH_CAT',
		'PRODUCT',
		'SALES_ORG',
		'SAP_COMPANY_STAGING',
		'SCORE_BAND',
		'SCORE_BAND',
		'SCORE_BAND',
		'SCORE_BAND_MAP',
		'TURNOVER_STAGING',
		'TERTIARY_COMPANY_STAGING',
		'USER_STAGING'
	); 
BEGIN
	FOR i IN 1 .. v_list.COUNT 
	LOOP
		FOR r IN (
			SELECT table_name 
			  FROM all_tables 
			 WHERE owner = 'RAG' 
			   AND table_name = v_list(i))
		LOOP
			EXECUTE IMMEDIATE 'DROP TABLE rag.'||r.table_name||' PURGE';
		END LOOP;
	END LOOP;
END;
/

