
exec dbms_output.put_line('create_chain_dedupe_staging on '||:bv_site_name);

BEGIN
	security.user_pkg.logonadmin(:bv_site_name);
	
	-- Unregister table if there is one
	FOR r IN (
		SELECT oracle_table
		  FROM cms.tab 
		 WHERE oracle_schema = 'RAG' 
		   AND oracle_table IN ('SAP_COMPANY_STAGING', 'BSCI_COMPANY_STAGING', 'TERTIARY_COMPANY_STAGING')
	)
	LOOP
		cms.tab_pkg.UnregisterTable(
			in_oracle_schema => 'RAG',
			in_oracle_table	 => r.oracle_table
		);
	END LOOP;

	-- Drop table if there is one
	FOR r IN (SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'RAG' AND TABLE_NAME IN ('SAP_COMPANY_STAGING', 'BSCI_COMPANY_STAGING', 'TERTIARY_COMPANY_STAGING'))
	LOOP
		EXECUTE IMMEDIATE 'DROP TABLE rag.'||r.TABLE_NAME;
	END LOOP;
END;
/

CREATE TABLE rag.SAP_COMPANY_STAGING (
	SAP_COMPANY_STAGING_ID	NUMBER(10, 0)	NOT NULL,
	VENDOR_NUM				VARCHAR2(255)	NOT NULL,
	VENDOR_NAME				VARCHAR2(255)	NOT NULL,
	CITY	 			 	VARCHAR2(255),
	POSTAL_CODE				VARCHAR2(255),
	STREET					VARCHAR2(255),
	COMPANY_TYPE			VARCHAR2(255),
	COUNTRY					VARCHAR2(255),
	ACTIVATED_DTM			DATE,
	STATE					VARCHAR2(255),
	WEBSITE					VARCHAR2(255),
	SECTOR					VARCHAR2(255),
	FACILITY_TYPE			VARCHAR2(255),
	OWNERSHIP_TYPE			VARCHAR2(255),
	PARENT_COMPANY			VARCHAR2(255),
	COMPANY_SECONDARY_REF	VARCHAR2(255),
	ACTIVE					NUMBER(1),
	EMAIL					VARCHAR(255),
	DEACTIVATED_DTM			DATE,
	CONSTRAINT PK_SAP_COMPANY_STAGING PRIMARY KEY (SAP_COMPANY_STAGING_ID),
	CONSTRAINT UC_SAP_COMPANY_STAGING UNIQUE(VENDOR_NUM)
);

CREATE TABLE rag.BSCI_COMPANY_STAGING (
	BSCI_COMPANY_STAGING_ID	NUMBER(10, 0)	NOT NULL,
	BSCI_VENDOR_NUM			VARCHAR2(255)	NOT NULL,
	VENDOR_NAME				VARCHAR2(255)	NOT NULL,
	COMPANY_TYPE			VARCHAR2(255),
	COUNTRY					VARCHAR2(255),
	POSTCODE				VARCHAR2(255),
	WEBSITE					VARCHAR2(255),
	SECTOR					VARCHAR2(255),
	FACILITY_TYPE			VARCHAR2(255),
	OWNERSHIP_TYPE			VARCHAR2(255),
	IS_ACTIVE				NUMBER(1),
	ADDRESS					VARCHAR2(255),
	CONSTRAINT PK_BSCI_COMPANY_STAGING PRIMARY KEY (BSCI_COMPANY_STAGING_ID),
	CONSTRAINT UC_BSCI_COMPANY_STAGING UNIQUE(BSCI_VENDOR_NUM)
);

CREATE TABLE rag.TERTIARY_COMPANY_STAGING (
	TRY_COMPANY_STAGING_ID	NUMBER(10, 0)	NOT NULL,
	TERTIARY_VENDOR_NUM		VARCHAR2(255)	NOT NULL,
	VENDOR_NAME				VARCHAR2(255)	NOT NULL,
	COMPANY_TYPE			VARCHAR2(255),
	COUNTRY					VARCHAR2(255),
	POSTCODE				VARCHAR2(255),
	WEBSITE					VARCHAR2(255),
	SECTOR					VARCHAR2(255),
	FACILITY_TYPE			VARCHAR2(255),
	OWNERSHIP_TYPE			VARCHAR2(255),
	IS_ACTIVE				NUMBER(1),
	ADDRESS					VARCHAR2(255),
	CONSTRAINT PK_TRY_COMPANY_STAGING PRIMARY KEY (TRY_COMPANY_STAGING_ID),
	CONSTRAINT UC_TRY_COMPANY_STAGING UNIQUE(TERTIARY_VENDOR_NUM)
);

BEGIN
	security.user_pkg.logonadmin(:bv_site_name);
	
	cms.tab_pkg.RegisterTable(
		in_oracle_schema => 'RAG',
		in_oracle_table => 'SAP_COMPANY_STAGING,BSCI_COMPANY_STAGING,TERTIARY_COMPANY_STAGING',
		in_managed => FALSE
	);
END;
/
