define version=118
@update_header

connect aspen2/aspen2@&_CONNECT_IDENTIFIER
grant select on aspen2.lang to chain;
connect chain/chain@&_CONNECT_IDENTIFIER

CREATE SEQUENCE chain.FILE_GROUP_FILE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

ALTER TABLE chain.FILE_GROUP ADD DEFAULT_FILE_GROUP_FILE_ID    NUMBER(10, 0);

ALTER TABLE chain.FILE_GROUP_FILE ADD FILE_GROUP_FILE_ID    NUMBER(10, 0);

ALTER TABLE chain.FILE_GROUP_FILE DROP CONSTRAINT PK352 drop index;

UPDATE chain.file_group_file SET file_group_file_id = ROWNUM;

DECLARE
	v_count NUMBER(10);
BEGIN
	SELECT COUNT(*)+1 -- For some reason you need to increment by 1 more than you'd think
	  INTO v_count
	  FROM chain.file_group_file;
	EXECUTE IMMEDIATE 'ALTER SEQUENCE file_group_file_id_seq INCREMENT BY '||v_count;
END;
/

ALTER TABLE chain.FILE_GROUP_FILE MODIFY FILE_GROUP_FILE_ID    NUMBER(10, 0) NOT NULL;

ALTER TABLE chain.FILE_GROUP_FILE ADD CONSTRAINT PK352 PRIMARY KEY (APP_SID, FILE_GROUP_FILE_ID);

CREATE UNIQUE INDEX chain.UNIQUE_FG_FILE ON chain.FILE_GROUP_FILE(APP_SID, FILE_GROUP_ID, FILE_UPLOAD_SID);

ALTER TABLE chain.FILE_GROUP_FILE ADD CONSTRAINT RefCUSTOMER_OPTIONS908 
    FOREIGN KEY (APP_SID)
    REFERENCES chain.CUSTOMER_OPTIONS(APP_SID);

@..\upload_pkg
@..\upload_body
@..\company_user_body

@update_tail