define version=66
@update_header

create index chain.ix_action_related_user_ on chain.action (app_sid, related_user_sid);
create index chain.ix_action_for_user_sid on chain.action (app_sid, for_user_sid);
create index chain.ix_action_related_compa on chain.action (app_sid, related_company_sid);
create index chain.ix_action_for_company_s on chain.action (app_sid, for_company_sid);
create index chain.ix_action_related_quest on chain.action (app_sid, related_questionnaire_id);
create index chain.ix_action_reason_for_ac on chain.action (reason_for_action_id, app_sid);
create index chain.ix_action_user_s_user_sid on chain.action_user_status (app_sid, user_sid);
create index chain.ix_alert_entry_alert_entry_p on chain.alert_entry (alert_entry_param_type_id);
create index chain.ix_alert_entry_alert_entry_t on chain.alert_entry (app_sid, alert_entry_type_id, template_name);
create index chain.ix_alert_entry_alrt_en_type on chain.alert_entry (alert_entry_type_id);
create index chain.ix_alert_entry_user_sid on chain.alert_entry (app_sid, user_sid);
create index chain.ix_alert_entry_company_sid on chain.alert_entry (app_sid, company_sid);
create index chain.ix_alert_entry_company_sid_u on chain.alert_entry (app_sid, company_sid, user_sid, owner_scheduled_alert_id);
create index chain.ix_alert_entry_a_action_id on chain.alert_entry_action (app_sid, action_id);
create index chain.ix_alert_entry_a_alert_entry_i on chain.alert_entry_action (app_sid, alert_entry_id);
create index chain.ix_alert_entry_a_user_sid on chain.alert_entry_action (app_sid, user_sid);
create index chain.ix_alert_entry_e_alert_entry_i on chain.alert_entry_event (app_sid, alert_entry_id);
create index chain.ix_alert_entry_e_user_sid on chain.alert_entry_event (app_sid, user_sid);
create index chain.ix_alert_entry_t_alert_entry_t on chain.alert_entry_template (alert_entry_type_id);
create index chain.ix_alert_entry_t_app_sid on chain.alert_entry_type (app_sid);
create index chain.ix_applied_compa_group_capabil on chain.applied_company_capability (group_capability_id);
create index chain.ix_capability_app_sid on chain.capability (app_sid);
create index chain.ix_card_group_ca_required_capa on chain.card_group_card (required_capability_id);
create index chain.ix_card_group_ca_card_id on chain.card_group_card (card_id);
create index chain.ix_card_group_ca_card_group_id on chain.card_group_card (card_group_id);
create index chain.ix_card_group_pr_card_group_id on chain.card_group_progression (app_sid, card_group_id, to_card_id);
create index chain.ix_card_group_pr_from_card_id_ on chain.card_group_progression (from_card_id, from_card_action);
create index chain.ix_chain_user_default_compa on chain.chain_user (app_sid, default_company_sid);
create index chain.ix_chain_user_merged_to_use on chain.chain_user (app_sid, merged_to_user_sid);
create index chain.ix_chain_user_registration_ on chain.chain_user (registration_status_id);
create index chain.ix_chain_user_visibility_id on chain.chain_user (visibility_id);
create index chain.ix_cmpnt_cmpnt_r_parent_compon on chain.cmpnt_cmpnt_relationship (parent_component_id, app_sid);
create index chain.ix_cmpnt_cmpnt_r_component_id_ on chain.cmpnt_cmpnt_relationship (component_id, app_sid);
create index chain.ix_cmpnt_prod_re_purchaser_com on chain.cmpnt_prod_relationship (purchaser_component_id, app_sid);
create index chain.ix_cmpnt_prod_re_supplier_prod on chain.cmpnt_prod_relationship (supplier_product_id, app_sid);
create index chain.ix_cmpnt_prod_re_prchser_cmpny on chain.cmpnt_prod_relationship (app_sid, purchaser_company_sid);
create index chain.ix_cmpnt_prod_re_supplr_cmpny on chain.cmpnt_prod_relationship (app_sid, supplier_company_sid);
create index chain.ix_cmp_prd_re_pe_prchser_cmpnt on chain.cmpnt_prod_rel_pending (purchaser_component_id, app_sid);
create index chain.ix_cmp_prd_re_pe_supplr_prodct on chain.cmpnt_prod_rel_pending (supplier_product_id, app_sid);
create index chain.ix_cmp_prd_re_pe_prchsr_compny on chain.cmpnt_prod_rel_pending (app_sid, purchaser_company_sid);
create index chain.ix_cmp_prd_re_pe_supplr_compny on chain.cmpnt_prod_rel_pending (app_sid, supplier_company_sid);
create index chain.ix_company_country_code on chain.company (country_code);
create index chain.ix_company_metri_company_sid on chain.company_metric (app_sid, company_sid);
create index chain.ix_component_created_by_si on chain.component (app_sid, created_by_sid);
create index chain.ix_component_company_sid on chain.component (app_sid, company_sid);
create index chain.ix_component_component_typ on chain.component (component_type_id, app_sid);
create index chain.ix_component_app_sid on chain.component (app_sid);
create index chain.ix_component_sou_card_group_id on chain.component_source (card_group_id);
create index chain.ix_component_sou_component_typ on chain.component_source (component_type_id, app_sid);
create index chain.ix_component_typ_editor_card_g on chain.component_type (editor_card_group_id);
create index chain.ix_component_typ_app_sid on chain.component_type (app_sid);
create index chain.ix_component_typ_child_compone on chain.component_type_containment (child_component_type_id, app_sid);
create index chain.ix_component_typ_container_com on chain.component_type_containment (container_component_type_id, app_sid);
create index chain.ix_event_related_actio on chain.event (app_sid, related_action_id);
create index chain.ix_event_for_user_sid on chain.event (app_sid, for_user_sid);
create index chain.ix_event_related_user_ on chain.event (app_sid, related_user_sid);
create index chain.ix_event_related_compa on chain.event (app_sid, related_company_sid);
create index chain.ix_event_for_company_s on chain.event (app_sid, for_company_sid);
create index chain.ix_event_event_type_id on chain.event (app_sid, event_type_id);
create index chain.ix_event_related_quest on chain.event (app_sid, related_questionnaire_id);
create index chain.ix_event_user_st_user_sid on chain.event_user_status (app_sid, user_sid);
create index chain.ix_event_user_st_event_id_app_ on chain.event_user_status (event_id, app_sid);
create index chain.ix_group_capabil_capability_id on chain.group_capability (capability_id);
create index chain.ix_group_capabil_group_capabil on chain.group_capability_override (group_capability_id);
create index chain.ix_invitation_from_user_sid on chain.invitation (app_sid, from_user_sid);
create index chain.ix_invitation_to_user_sid on chain.invitation (app_sid, to_user_sid);
create index chain.ix_invitation_cancelled_by_ on chain.invitation (app_sid, cancelled_by_user_sid);
create index chain.ix_invitation_from_company_ on chain.invitation (app_sid, from_company_sid);
create index chain.ix_invitation_to_company_si on chain.invitation (app_sid, to_company_sid);
create index chain.ix_invitation_reinvitation_ on chain.invitation (app_sid, reinvitation_of_invitation_id);
create index chain.ix_invitation_invitation_st on chain.invitation (invitation_status_id);
create index chain.ix_invitation_invitation_ty on chain.invitation (invitation_type_id);
create index chain.ix_invitation_qn_added_by_user on chain.invitation_qnr_type (app_sid, added_by_user_sid);
create index chain.ix_invitation_qn_questionnaire on chain.invitation_qnr_type (app_sid, questionnaire_type_id);
create index chain.ix_newsflash_com_company_sid on chain.newsflash_company (app_sid, company_sid);
create index chain.ix_newsflash_use_user_sid on chain.newsflash_user_settings (app_sid, user_sid);
create index chain.ix_product_root_componen on chain.product (root_component_id, app_sid);
create index chain.ix_product_created_by_si on chain.product (app_sid, created_by_sid);
create index chain.ix_product_company_sid on chain.product (app_sid, company_sid);
create index chain.ix_product_product_build on chain.product (product_builder_component_id, app_sid);
create index chain.ix_product_app_sid on chain.product (app_sid);
create index chain.ix_product_metri_product_metri on chain.product_metric (product_metric_type_id, app_sid);
create index chain.ix_product_metri_app_sid on chain.product_metric_type (app_sid);
create index chain.ix_qnr_share_log_user_sid on chain.qnr_share_log_entry (app_sid, user_sid);
create index chain.ix_qnr_share_log_company_sid on chain.qnr_share_log_entry (app_sid, company_sid);
create index chain.ix_qnr_share_log_share_status_ on chain.qnr_share_log_entry (share_status_id);
create index chain.ix_qnr_status_lo_user_sid on chain.qnr_status_log_entry (app_sid, user_sid);
create index chain.ix_qnr_status_lo_questionnaire on chain.qnr_status_log_entry (questionnaire_status_id);
create index chain.ix_questionnaire_questionnaire on chain.questionnaire (app_sid, questionnaire_type_id);
create index chain.ix_questionnaire_quest_metric on chain.questionnaire_metric (app_sid, questionnaire_metric_type_id);
create index chain.ix_questionnaire_quest_metrict on chain.questionnaire_metric_type (app_sid, questionnaire_type_id);
create index chain.ix_questionnaire_quest_share on chain.questionnaire_share (app_sid, questionnaire_id);
create index chain.ix_questionnaire_group_name on chain.questionnaire_type (app_sid, group_name);
create index chain.ix_reason_for_ac_action_repeat on chain.reason_for_action (action_repeat_type_id);
create index chain.ix_reason_for_ac_action_type_i on chain.reason_for_action (app_sid, action_type_id);
create index chain.ix_reset_passwor_user_sid on chain.reset_password (app_sid, user_sid);
create index chain.ix_reset_passwor_accept_invita on chain.reset_password (app_sid, accept_invitation_on_reset);
create index chain.ix_scheduled_ale_user_sid on chain.scheduled_alert (app_sid, user_sid);
create index chain.ix_supplier_rela_supplier_comp on chain.supplier_relationship (app_sid, supplier_company_sid);
create index chain.ix_task_action_id on chain.task (app_sid, action_id);
create index chain.ix_task_created_by_si on chain.task (app_sid, created_by_sid);
create index chain.ix_task_last_updated_ on chain.task (app_sid, last_updated_by_sid);
create index chain.ix_task_company_sid on chain.task (app_sid, company_sid);
create index chain.ix_task_app_sid on chain.task (app_sid);
create index chain.ix_task_questionnaire on chain.task (app_sid, questionnaire_id);
create index chain.ix_task_task_node_id_ on chain.task (task_node_id, app_sid);
create index chain.ix_task_task_status_i on chain.task (task_status_id);
create index chain.ix_task_task_type_id_ on chain.task (task_type_id, app_sid);
create index chain.ix_task_doc_doc_id_versio on chain.task_doc (app_sid, doc_id, version);
create index chain.ix_task_entry_created_by_si on chain.task_entry (app_sid, created_by_sid);
create index chain.ix_task_entry_app_sid on chain.task_entry (app_sid);
create index chain.ix_task_entry_task_id_app_s on chain.task_entry (task_id, app_sid);
create index chain.ix_task_entry_task_entry_ty on chain.task_entry (task_entry_type_id);
create index chain.ix_task_node_company_sid on chain.task_node (app_sid, company_sid);
create index chain.ix_task_node_app_sid on chain.task_node (app_sid);
create index chain.ix_task_node_parent_task_n on chain.task_node (parent_task_node_id, app_sid);
create index chain.ix_task_node_task_node_typ on chain.task_node (task_node_type_id, app_sid);
create index chain.ix_task_node_typ_app_sid on chain.task_node_type (app_sid);
create index chain.ix_task_type_app_sid on chain.task_type (app_sid);
create index chain.ix_task_type_parent_task_t on chain.task_type (parent_task_type_id, app_sid);
create index chain.ix_task_user_res_user_sid on chain.task_user_responsible (app_sid, user_sid);
create index chain.ix_task_user_res_task_id_app_s on chain.task_user_responsible (task_id, app_sid);

@update_tail