define version=99
@update_header

connect aspen2/aspen2@&_CONNECT_IDENTIFIER
grant REFERENCES on aspen2.translation_set to chain;

connect chain/chain@&_CONNECT_IDENTIFIER

CREATE SEQUENCE chain.FILE_GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE TABLE chain.FILE_GROUP(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    FILE_GROUP_ID             NUMBER(10, 0)     NOT NULL,
    GUID                      VARCHAR2(38)      NOT NULL,
    COMPANY_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY', 'CHAIN_COMPANY') NOT NULL,
    FILE_GROUP_MODEL_ID       NUMBER(10, 0)     NOT NULL,
    DOWNLOAD_PERMISSION_ID    NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    TITLE                     VARCHAR2(255)     NOT NULL,
    DESCRIPTION               VARCHAR2(4000),
    CONSTRAINT PK350 PRIMARY KEY (APP_SID, FILE_GROUP_ID)
)
;


CREATE TABLE chain.FILE_GROUP_MODEL(
    FILE_GROUP_MODEL_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION            VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK358 PRIMARY KEY (FILE_GROUP_MODEL_ID)
)
;

CREATE TABLE chain.FILE_GROUP_FILE(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    FILE_GROUP_ID      NUMBER(10, 0)    NOT NULL,
    FILE_UPLOAD_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK352 PRIMARY KEY (APP_SID, FILE_GROUP_ID, FILE_UPLOAD_SID)
)
;


CREATE TABLE chain.DOWNLOAD_PERMISSION(
    DOWNLOAD_PERMISSION_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION               VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK349 PRIMARY KEY (DOWNLOAD_PERMISSION_ID)
)
;

ALTER TABLE chain.FILE_UPLOAD ADD (
    DOWNLOAD_PERMISSION_ID     NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    LANG                       VARCHAR2(10)
)
;

-- 
-- INDEX: UNIQUE_FG_GUID
--

CREATE UNIQUE INDEX chain.UNIQUE_FG_GUID ON chain.FILE_GROUP(APP_SID, GUID)
;



BEGIN
	INSERT INTO chain.DOWNLOAD_PERMISSION (DOWNLOAD_PERMISSION_ID, DESCRIPTION)
	VALUES (0, 'Standard capability based permissions');
	
	INSERT INTO chain.DOWNLOAD_PERMISSION (DOWNLOAD_PERMISSION_ID, DESCRIPTION)
	VALUES (1, 'Everyone can downloadaccess this file');
	
	INSERT INTO chain.DOWNLOAD_PERMISSION (DOWNLOAD_PERMISSION_ID, DESCRIPTION)
	VALUES (2, 'My company and my suppliers can download this file');
	
	

	INSERT INTO chain.FILE_GROUP_MODEL (FILE_GROUP_MODEL_ID, DESCRIPTION)
	VALUES (0, 'Groups files by thier language and provides the user with the best file when downloading based on their language settings.');
	
END;
/

-- 
-- TABLE: FILE_GROUP 
--

ALTER TABLE chain.FILE_GROUP ADD CONSTRAINT RefCOMPANY881 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES chain.COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE chain.FILE_GROUP ADD CONSTRAINT RefCUSTOMER_OPTIONS882 
    FOREIGN KEY (APP_SID)
    REFERENCES chain.CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE chain.FILE_GROUP ADD CONSTRAINT RefFILE_GROUP_MODEL891 
    FOREIGN KEY (FILE_GROUP_MODEL_ID)
    REFERENCES chain.FILE_GROUP_MODEL(FILE_GROUP_MODEL_ID)
;

ALTER TABLE chain.FILE_GROUP ADD CONSTRAINT RefDOWNLOAD_PERMISSION892 
    FOREIGN KEY (DOWNLOAD_PERMISSION_ID)
    REFERENCES chain.DOWNLOAD_PERMISSION(DOWNLOAD_PERMISSION_ID)
;


-- 
-- TABLE: FILE_GROUP_FILE 
--

ALTER TABLE chain.FILE_GROUP_FILE ADD CONSTRAINT RefFILE_UPLOAD883 
    FOREIGN KEY (APP_SID, FILE_UPLOAD_SID)
    REFERENCES chain.FILE_UPLOAD(APP_SID, FILE_UPLOAD_SID)
;

ALTER TABLE chain.FILE_GROUP_FILE ADD CONSTRAINT RefFILE_GROUP884 
    FOREIGN KEY (APP_SID, FILE_GROUP_ID)
    REFERENCES chain.FILE_GROUP(APP_SID, FILE_GROUP_ID)
;

-- 
-- TABLE: FILE_UPLOAD 
--

ALTER TABLE chain.FILE_UPLOAD ADD CONSTRAINT RefTRANSLATION_SET886 
    FOREIGN KEY (APP_SID, LANG)
    REFERENCES ASPEN2.TRANSLATION_SET(APPLICATION_SID, LANG)
;

ALTER TABLE chain.FILE_UPLOAD ADD CONSTRAINT RefDOWNLOAD_PERMISSION893 
    FOREIGN KEY (DOWNLOAD_PERMISSION_ID)
    REFERENCES chain.DOWNLOAD_PERMISSION(DOWNLOAD_PERMISSION_ID)
;



DECLARE
	v_card_id		CHAIN.card.card_id%TYPE;
BEGIN
	SELECT card_id
	  INTO v_card_id
	  FROM CHAIN.card
	 WHERE js_class_type = 'Chain.Cards.RejectRegisterLogin';
	
	DELETE 
	  FROM CHAIN.card_group_progression
	 WHERE from_card_id = v_card_id
		OR to_card_id = v_card_id;

	DELETE
	  FROM CHAIN.card_progression_action
	 WHERE card_id = v_card_id;

	DELETE 
	  FROM CHAIN.card_group_card
	 WHERE card_id = v_card_id;

	DELETE 
	  FROM CHAIN.card
	 WHERE card_id = v_card_id;	
END;
/


@..\chain_pkg
@..\upload_pkg
@..\upload_body

@..\rls

@update_tail
