define version=81
@update_header

connect csr/csr@&_CONNECT_IDENTIFIER

grant select, references on csr.alert_type to chain;
grant select, references on csr.alert_type_param to chain;

connect chain/chain@&_CONNECT_IDENTIFIER

CREATE TABLE chain.ALERT_PARTIAL_TEMPLATE
(
	APP_SID						NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	ALERT_TYPE_ID				NUMBER(10,0) NOT NULL,
	PARTIAL_TEMPLATE_TYPE_ID	NUMBER(10,0) NOT NULL,
	LANG						VARCHAR2(10 BYTE) NOT NULL,
	PARTIAL_HTML				CLOB NOT NULL,
	CONSTRAINT PK_ALERT_PARTIAL_TEMPLATE PRIMARY KEY (APP_SID, ALERT_TYPE_ID, PARTIAL_TEMPLATE_TYPE_ID, LANG),
	CONSTRAINT FK_PARTIAL_TEMPALTE_ALTRT_TYPE FOREIGN KEY (ALERT_TYPE_ID) REFERENCES CSR.ALERT_TYPE(ALERT_TYPE_ID),
	CONSTRAINT FK_ALRT_PARTIAL_TPL_APP FOREIGN KEY (APP_SID) REFERENCES CSR.CUSTOMER(APP_SID)
);

CREATE TABLE chain.ALERT_PARTIAL_TEMPLATE_PARAM
(
	APP_SID						NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	ALERT_TYPE_ID				NUMBER(10,0) NOT NULL,
	PARTIAL_TEMPLATE_TYPE_ID	NUMBER(10,0) NOT NULL,
	FIELD_NAME					VARCHAR2(50),
	CONSTRAINT PK_ALERT_PARTIAL_TPL_PARAM PRIMARY KEY (APP_SID, ALERT_TYPE_ID, PARTIAL_TEMPLATE_TYPE_ID, FIELD_NAME),
	CONSTRAINT FK_PARTIAL_TPL_P_ALTRT_TYPE_P FOREIGN KEY (ALERT_TYPE_ID, FIELD_NAME) REFERENCES CSR.ALERT_TYPE_PARAM(ALERT_TYPE_ID, FIELD_NAME)
);


@../alert_helper_pkg
@../alert_helper_body

grant execute on chain.alert_helper_pkg to web_user;


@update_tail