define version=106
@update_header

-- these may not all exist on some systems (apparently)
CREATE TABLE chain.TMP_DROP_TABLES (POSITION NUMBER(10) NOT NULL, TABLE_NAME VARCHAR2(30) NOT NULL);

BEGIN
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (1, 'OLD_CMPNT_PROD_REL_PENDING');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (2, 'OLD_CMPNT_PROD_RELATIONSHIP');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (3, 'OLD_CMPNT_CMPNT_RELATIONSHIP');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (4, 'OLD_COMPONENT_SOURCE');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (5, 'OLD_COMPONENT_TYPE_CONTAINMENT');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (6, 'OLD_PRODUCT_CODE_TYPE');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (7, 'OLD_PRODUCT_ANSWER');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (8, 'OLD_PRODUCT');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (9, 'OLD_COMPONENT');
	INSERT INTO chain.TMP_DROP_TABLES (POSITION, TABLE_NAME) VALUES (10, 'OLD_COMPONENT_TYPE');
END;
/

BEGIN
	FOR r IN (
		SELECT table_name
		  FROM chain.tmp_drop_tables
		 WHERE table_name IN (SELECT table_name FROM all_tables WHERE owner='CHAIN' AND NVL(dropped, 'NO') = 'NO')
		 ORDER BY position
 	)
 	LOOP
 		EXECUTE IMMEDIATE 'DROP TABLE chain.'||r.table_name;
 	END LOOP;
END;
/

DROP TABLE chain.TMP_DROP_TABLES;

@..\chain_pkg

@..\company_user_body
@..\uninvited_body
@..\company_body

@update_tail