define version=98
@update_header


CREATE GLOBAL TEMPORARY TABLE CHAIN.TT_USER_TASKS
(
	SUPPLIER_NAME				VARCHAR2(255)	NOT NULL,
	SUPPLIER_SID				NUMBER(10,0)	NOT NULL,
	TASK_TYPE_DESCRIPTION		VARCHAR2(255)	NOT NULL,
	PARENT_TASK_TYPE_DESCRIPTION VARCHAR2(255)	NOT NULL,
	DUE_DATE					DATE,
	RN 							NUMBER,
	MESSAGE_TEMPLATE			VARCHAR2(4000),
	RE_QUESTIONNAIRE			VARCHAR2(255),
	RE_USER 					VARCHAR2(256)
) ON COMMIT DELETE ROWS;


@..\chain_pkg
@..\company_pkg
@..\helper_pkg
@..\task_pkg

@..\company_body
@..\helper_body
@..\task_body


@update_tail