define version=4
@update_header

CREATE TABLE QUESTIONNAIRE_GROUP(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    GROUP_NAME     VARCHAR2(30)     NOT NULL,
    DESCRIPTION    VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK166 PRIMARY KEY (APP_SID, GROUP_NAME)
)
;


ALTER TABLE QUESTIONNAIRE_TYPE ADD (GROUP_NAME VARCHAR2(30));
ALTER TABLE QUESTIONNAIRE_TYPE ADD (POSITION NUMBER(10));

ALTER TABLE QUESTIONNAIRE_TYPE ADD CONSTRAINT RefQUESTIONNIARE_GROUP375 
    FOREIGN KEY (APP_SID, GROUP_NAME)
    REFERENCES QUESTIONNAIRE_GROUP(APP_SID, GROUP_NAME)
;

ALTER TABLE CUSTOMER_OPTIONS ADD (QUESTIONNAIRE_FILTER_CLASS VARCHAR2(100));


@..\questionnaire_pkg
@..\questionnaire_body

@update_tail