define version=30
@update_header

PROMPT >> New Sequences

CREATE SEQUENCE COMPONENT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE SEQUENCE PRODUCT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

PROMPT >> New Tables

CREATE TABLE ALL_COMPONENT(
    COMPONENT_ID         NUMBER(10, 0)     NOT NULL,
    APP_SID              NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    COMPANY_SID          NUMBER(10, 0)     NOT NULL,
    CREATED_BY_SID       NUMBER(10, 0)     NOT NULL,
    CREATED_DTM          DATE              DEFAULT SYSDATE NOT NULL,
    DESCRIPTION          VARCHAR2(4000),
    COMPONENT_TYPE_ID    NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK195 PRIMARY KEY (COMPONENT_ID, APP_SID)
)
;

CREATE TABLE ALL_PRODUCT(
    PRODUCT_ID           NUMBER(10, 0)    NOT NULL,
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    COMPANY_SID          NUMBER(10, 0)    NOT NULL,
    CREATED_BY_SID       NUMBER(10, 0)    NOT NULL,
    CREATED_DTM          DATE             DEFAULT SYSDATE NOT NULL,
    DESCRIPTION          VARCHAR2(500)    NOT NULL,
    ACTIVE               NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CODE1                VARCHAR2(100)    NOT NULL,
    CODE2                VARCHAR2(100),
    CODE3                VARCHAR2(100),
    NEED_REVIEW          NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    DELETED              NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    ROOT_COMPONENT_ID    NUMBER(10, 0)    NOT NULL,
    CHECK (ACTIVE IN (1,0)),
    CHECK (NEED_REVIEW IN (1,0)),
    CHECK (DELETED IN (1,0)),
    CONSTRAINT PK170 PRIMARY KEY (PRODUCT_ID, APP_SID)
)
;

CREATE TABLE CMPNT_PROD_REL_PENDING(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    PURCHASER_COMPANY_SID     NUMBER(10, 0)     NOT NULL,
    PURCHASER_COMPONENT_ID    NUMBER(10, 0),
    SUPPLIER_COMPANY_SID      NUMBER(10, 0)     NOT NULL,
    SUPPLIER_PRODUCT_ID       NUMBER(10, 0),
    BUYING_CODE               VARCHAR2(100),
    BUYING_DESCRIPTION        VARCHAR2(4000),
    SELLING_CODE              VARCHAR2(100),
    SELLING_DESCRIPTION       VARCHAR2(4000)
)
;

CREATE TABLE CMPNT_PROD_RELATIONSHIP(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    PURCHASER_COMPONENT_ID    NUMBER(10, 0)     NOT NULL,
    SUPPLIER_PRODUCT_ID       NUMBER(10, 0)     NOT NULL,
    PURCHASER_COMPANY_SID     NUMBER(10, 0)     NOT NULL,
    SUPPLIER_COMPANY_SID      NUMBER(10, 0)     NOT NULL,
    BUYING_CODE               VARCHAR2(100),
    BUYING_DESCRIPTION        VARCHAR2(4000),
    SELLING_CODE              VARCHAR2(100),
    SELLING_DESCRIPTION       VARCHAR2(4000),
    CONSTRAINT PK174_1 PRIMARY KEY (APP_SID, PURCHASER_COMPONENT_ID, SUPPLIER_PRODUCT_ID)
)
;

CREATE TABLE COMPONENT_TYPE(
    COMPONENT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    DESCRIPTION          VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK202 PRIMARY KEY (COMPONENT_TYPE_ID, APP_SID)
)
;

CREATE TABLE DEFAULT_PRODUCT_CODE_TYPE(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    CODE_LABEL1    VARCHAR2(100)    NOT NULL,
    CODE_LABEL2    VARCHAR2(100),
    CODE_LABEL3    VARCHAR2(100),
    CONSTRAINT PK198 PRIMARY KEY (APP_SID)
)
;

CREATE TABLE PRODUCT_CODE_TYPE(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    COMPANY_SID        NUMBER(10, 0)    NOT NULL,
    CODE_LABEL1        VARCHAR2(100)    DEFAULT 'SKU' NOT NULL,
    CODE_LABEL2        VARCHAR2(100),
    CODE2_MANDATORY    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CODE_LABEL3        VARCHAR2(100),
    CODE3_MANDATORY    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CHECK (CODE2_MANDATORY IN (1,0)),
    CHECK (CODE3_MANDATORY IN (1,0)),
    CONSTRAINT PK176 PRIMARY KEY (APP_SID, COMPANY_SID)
)
;

CREATE TABLE PRODUCT_METRIC(
    PRODUCT_ID                NUMBER(10, 0)    NOT NULL,
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    PRODUCT_METRIC_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    METRIC_VALUE              NUMBER(10, 3),
    NORMALISED_VALUE          NUMBER(10, 3),
    CONSTRAINT PK182 PRIMARY KEY (PRODUCT_ID, APP_SID, PRODUCT_METRIC_TYPE_ID)
)
;

CREATE TABLE PRODUCT_METRIC_TYPE(
    PRODUCT_METRIC_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    DESCRIPTION               VARCHAR2(200)    NOT NULL,
    CLASS                     VARCHAR2(64),
    MAX_SCORE                 NUMBER(10, 3),
    CONSTRAINT PK181 PRIMARY KEY (PRODUCT_METRIC_TYPE_ID, APP_SID)
)
;


PROMPT >> References

ALTER TABLE ALL_COMPONENT ADD CONSTRAINT RefCUSTOMER_OPTIONS416 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE ALL_COMPONENT ADD CONSTRAINT RefCOMPANY417 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE ALL_COMPONENT ADD CONSTRAINT RefCHAIN_USER456 
    FOREIGN KEY (APP_SID, CREATED_BY_SID)
    REFERENCES CHAIN_USER(APP_SID, USER_SID)
;

ALTER TABLE ALL_COMPONENT ADD CONSTRAINT RefCOMPONENT_TYPE419 
    FOREIGN KEY (COMPONENT_TYPE_ID, APP_SID)
    REFERENCES COMPONENT_TYPE(COMPONENT_TYPE_ID, APP_SID)
;

ALTER TABLE ALL_PRODUCT ADD CONSTRAINT RefCUSTOMER_OPTIONS420 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE ALL_PRODUCT ADD CONSTRAINT RefCOMPANY421 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE ALL_PRODUCT ADD CONSTRAINT RefCHAIN_USER457 
    FOREIGN KEY (APP_SID, CREATED_BY_SID)
    REFERENCES CHAIN_USER(APP_SID, USER_SID)
;

ALTER TABLE ALL_PRODUCT ADD CONSTRAINT RefALL_COMPONENT423 
    FOREIGN KEY (ROOT_COMPONENT_ID, APP_SID)
    REFERENCES ALL_COMPONENT(COMPONENT_ID, APP_SID)
;

ALTER TABLE CMPNT_PROD_REL_PENDING ADD CONSTRAINT RefALL_COMPONENT424 
    FOREIGN KEY (PURCHASER_COMPONENT_ID, APP_SID)
    REFERENCES ALL_COMPONENT(COMPONENT_ID, APP_SID)
;

ALTER TABLE CMPNT_PROD_REL_PENDING ADD CONSTRAINT RefCOMPANY425 
    FOREIGN KEY (APP_SID, PURCHASER_COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE CMPNT_PROD_REL_PENDING ADD CONSTRAINT RefCOMPANY426 
    FOREIGN KEY (APP_SID, SUPPLIER_COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE CMPNT_PROD_REL_PENDING ADD CONSTRAINT RefALL_PRODUCT428 
    FOREIGN KEY (SUPPLIER_PRODUCT_ID, APP_SID)
    REFERENCES ALL_PRODUCT(PRODUCT_ID, APP_SID)
;

ALTER TABLE CMPNT_PROD_RELATIONSHIP ADD CONSTRAINT RefALL_COMPONENT429 
    FOREIGN KEY (PURCHASER_COMPONENT_ID, APP_SID)
    REFERENCES ALL_COMPONENT(COMPONENT_ID, APP_SID)
;

ALTER TABLE CMPNT_PROD_RELATIONSHIP ADD CONSTRAINT RefCOMPANY430 
    FOREIGN KEY (APP_SID, PURCHASER_COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE CMPNT_PROD_RELATIONSHIP ADD CONSTRAINT RefCOMPANY431 
    FOREIGN KEY (APP_SID, SUPPLIER_COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE CMPNT_PROD_RELATIONSHIP ADD CONSTRAINT RefALL_PRODUCT432 
    FOREIGN KEY (SUPPLIER_PRODUCT_ID, APP_SID)
    REFERENCES ALL_PRODUCT(PRODUCT_ID, APP_SID)
;

ALTER TABLE COMPONENT_TYPE ADD CONSTRAINT RefCUSTOMER_OPTIONS433 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE DEFAULT_PRODUCT_CODE_TYPE ADD CONSTRAINT RefCUSTOMER_OPTIONS434 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE PRODUCT_CODE_TYPE ADD CONSTRAINT RefCOMPANY435 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE PRODUCT_METRIC ADD CONSTRAINT RefPRODUCT_METRIC_TYPE436 
    FOREIGN KEY (PRODUCT_METRIC_TYPE_ID, APP_SID)
    REFERENCES PRODUCT_METRIC_TYPE(PRODUCT_METRIC_TYPE_ID, APP_SID)
;

ALTER TABLE PRODUCT_METRIC ADD CONSTRAINT RefALL_PRODUCT437 
    FOREIGN KEY (PRODUCT_ID, APP_SID)
    REFERENCES ALL_PRODUCT(PRODUCT_ID, APP_SID)
;

ALTER TABLE PRODUCT_METRIC_TYPE ADD CONSTRAINT RefCUSTOMER_OPTIONS438 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

@update_tail
