define version=45
@update_header

DROP INDEX PROD_CODE1_UNIQUE_IDX;

CREATE UNIQUE INDEX PROD_CODE1_UNIQUE_IDX ON ALL_PRODUCT(CASE WHEN DELETED = 0 THEN COMPANY_SID END, CASE WHEN DELETED = 0 THEN APP_SID END, CASE WHEN DELETED = 0 THEN LOWER(CODE1) END)
;

@update_tail

