define version=126
@update_header

DROP TABLE chain.TT_USER_TASKS;

CREATE GLOBAL TEMPORARY TABLE chain.TT_USER_TASKS
(
	SUPPLIER_NAME				VARCHAR2(255)	NOT NULL,
	SUPPLIER_SID				NUMBER(10,0)	NOT NULL,
	TASK_TYPE_DESCRIPTION		VARCHAR2(255)	NOT NULL,
	PARENT_TASK_TYPE_DESCRIPTION VARCHAR2(255)	NOT NULL,
	DUE_DATE					DATE,
	RN 							NUMBER,
	MESSAGE_TEMPLATE			VARCHAR2(4000),
	RE_QUESTIONNAIRE			VARCHAR2(255),
	RE_USER 					VARCHAR2(256),
	MESSAGE_DEFINITION_ID		NUMBER(10,0)
) ON COMMIT DELETE ROWS;

@..\task_body


@update_tail
