-- Please update version.sql too -- this keeps clean builds in sync
define version=69
@update_header


CREATE TABLE GT_TARGET_SCORES_LOG(
    APP_SID                NUMBER(10, 0)     NOT NULL,
    GT_PRODUCT_TYPE_ID     NUMBER(10, 0)     NOT NULL,
    GT_PRODUCT_RANGE_ID    NUMBER(10, 0)     NOT NULL,
    USER_SID               NUMBER(10, 0)     NOT NULL,
    DESCRIPTION            VARCHAR2(2048)    NOT NULL,
    AUDIT_DATE             DATE              NOT NULL
)
;

ALTER TABLE GT_TARGET_SCORES_LOG ADD CONSTRAINT RefGT_PRODUCT_RANGE481 
    FOREIGN KEY (GT_PRODUCT_RANGE_ID)
    REFERENCES GT_PRODUCT_RANGE(GT_PRODUCT_RANGE_ID)
;

ALTER TABLE GT_TARGET_SCORES_LOG ADD CONSTRAINT RefCUSTOMER_OPTIONS482 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE GT_TARGET_SCORES_LOG ADD CONSTRAINT RefGT_PRODUCT_TYPE483 
    FOREIGN KEY (GT_PRODUCT_TYPE_ID)
    REFERENCES GT_PRODUCT_TYPE(GT_PRODUCT_TYPE_ID)
;





@update_tail
