-- Please update version.sql too -- this keeps clean builds in sync
define version=53
@update_header

set define $;

UPDATE gt_product_answers SET gt_product_range_id = null;

DELETE FROM gt_product_range;

INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (2,'24 Hour');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (3,'Act');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (4,'Adv Totalcare');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (5,'Advanced+');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (6,'Anti Dandruff');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (7,'Antibac');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (8,'Aqua');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (9,'Aromatherapy');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (10,'Aromatics');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (11,'Aromatics Men');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (12,'Asilone');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (13,'Basics');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (14,'Boots');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (15,'Boots For Men');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (16,'Botanics');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (17,'Bow Wow Beauty');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (18,'Brecon Carreg');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (19,'Calmurid');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (20,'Camomile');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (21,'Classics');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (22,'Cocois');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (23,'Colour Burst');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (24,'Colour Whouse');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (25,'Cranberry');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (26,'Delicious');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (27,'Diabetic');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (28,'Dial');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (29,'Domestic Delight');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (30,'Eastern Spa');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (31,'Ellactiva');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (32,'Embrace');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (33,'Essentials');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (34,'Essntl Aromathrapy');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (35,'Etp');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (36,'Everydayindulgence');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (37,'Expert');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (38,'Exterol');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (39,'Extracts');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (40,'Flower Therapy');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (41,'Forceval');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (42,'Fragrant');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (43,'Fresh');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (44,'Garden Collection');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (45,'Get Crafty');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (46,'Get Playing');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (47,'Get Scientific');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (48,'Girard');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (49,'Gishiki');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (50,'Glamour Kit');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (51,'Green Cross');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (52,'Hallmark');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (53,'Healthy Start');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (54,'Home Therapys');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (55,'Hydro Therapy');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (56,'Immulia');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (57,'Ingredients');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (58,'Jewellery');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (59,'Ketopine');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (60,'Kim');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (61,'Ladies Inv');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (62,'Leather');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (63,'Lifestyle');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (64,'Ltp');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (65,'Luki Panda');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (66,'Lutsine');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (67,'Malvern');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (68,'Mediterranean');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (69,'Mens Spa');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (70,'Menu');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (71,'Miko Cat');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (72,'Mile High');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (73,'Milko');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (74,'Monogram');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (75,'Natural Balance');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (76,'Natural Collection');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (77,'Naturals');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (78,'No7');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (79,'Ocean Spa');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (80,'Oep');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (81,'Omron');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (82,'Organic');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (83,'Oriental Floral');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (84,'Oriental Flower');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (85,'Original Beauty Fo');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (86,'Paul Trend');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (87,'Pb');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (88,'Performance');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (89,'Pet Me!');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (90,'Pick N Stick');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (91,'Premium Ingredient');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (92,'Premium Soaps');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (93,'Pure Moisture');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (94,'Pure Protection');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (95,'Retro Id');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (96,'Rosewater');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (97,'Rowarolan');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (98,'Royal Jelly');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (99,'Ruby Wax');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (100,'Salon Performance');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (101,'Sanctuaryclassic');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (102,'Shapers');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (103,'Simply Natural');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (104,'Skin Kindly');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (105,'Skin Therapy');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (106,'Smartcard');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (107,'Smile');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (108,'Softsense');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (109,'Soltan');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (110,'Spa');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (111,'Specialist');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (112,'Stork Club');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (113,'Studio Basics');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (114,'Summer Brights');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (115,'Sun Swim & Gym');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (116,'Teddy Range');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (117,'The Collection');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (118,'Therapy');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (119,'Time Delay');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (120,'Tt & Wh');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (121,'Ultra Dry');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (122,'Value');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (123,'Venetian Antiques');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (124,'Venus');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (125,'Wellbeing');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (126,'White Collection');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (127,'Winnie The Pooh');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (128,'Winter');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (129,'Xeramance');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (130,'Zoo Crew');
INSERT INTO SUPPLIER.GT_PRODUCT_RANGE (
   GT_PRODUCT_RANGE_ID, DESCRIPTION) 
VALUES (1,'Unknown / No Range Allocated');


UPDATE gt_product_answers SET gt_product_range_id = 1;

set define &;

@update_tail
