-- Please update version.sql too -- this keeps clean builds in sync
define version=65
@update_header



-- 
-- TABLE: GT_TARGET_SCORES 
--

CREATE TABLE GT_TARGET_SCORES(
    APP_SID                      NUMBER(10, 0)    NOT NULL,
    GT_PRODUCT_TYPE_ID           NUMBER(10, 0)    NOT NULL,
    GT_PRODUCT_RANGE_ID          NUMBER(10, 0),
    MIN_SCORE_NAT_DERIVED        NUMBER(10, 2),
    MAX_SCORE_NAT_DERIVED        NUMBER(10, 2),
    MIN_SCORE_CHEMICALS          NUMBER(10, 2),
    MAX_SCORE_CHEMICALS          NUMBER(10, 2),
    MIN_SCORE_SOURCE_BIOD        NUMBER(10, 2),
    MAX_SCORE_SOURCE_BIOD        NUMBER(10, 2),
    MIN_SCORE_ACCRED_BIOD        NUMBER(10, 2),
    MAX_SCORE_ACCRED_BIOD        NUMBER(10, 2),
    MIN_SCORE_FAIR_TRADE         NUMBER(10, 2),
    MAX_SCORE_FAIR_TRADE         NUMBER(10, 2),
    MIN_SCORE_RENEW_PACK         NUMBER(10, 2),
    MAX_SCORE_RENEW_PACK         NUMBER(10, 2),
    MIN_SCORE_WHATS_IN_PROD      NUMBER(10, 2),
    MAX_SCORE_WHATS_IN_PROD      NUMBER(10, 2),
    MIN_SCORE_WATER_IN_PROD      NUMBER(10, 2),
    MAX_SCORE_WATER_IN_PROD      NUMBER(10, 2),
    MIN_SCORE_ENERGY_IN_PROD     NUMBER(10, 2),
    MAX_SCORE_ENERGY_IN_PROD     NUMBER(10, 2),
    MIN_SCORE_PACK_IMPACT        NUMBER(10, 2),
    MAX_SCORE_PACK_IMPACT        NUMBER(10, 2),
    MIN_SCORE_PACK_OPT           NUMBER(10, 2),
    MAX_SCORE_PACK_OPT           NUMBER(10, 2),
    MIN_SCORE_RECYCLED_PACK      NUMBER(10, 2),
    MAX_SCORE_RECYCLED_PACK      NUMBER(10, 2),
    MIN_SCORE_SUPP_MANAGEMENT    NUMBER(10, 2),
    MAX_SCORE_SUPP_MANAGEMENT    NUMBER(10, 2),
    MIN_SCORE_TRANS_RAW_MAT      NUMBER(10, 2),
    MAX_SCORE_TRANS_RAW_MAT      NUMBER(10, 2),
    MIN_SCORE_TRANS_TO_BOOTS     NUMBER(10, 2),
    MAX_SCORE_TRANS_TO_BOOTS     NUMBER(10, 2),
    MIN_SCORE_TRANS_PACKAGING    NUMBER(10, 2),
    MAX_SCORE_TRANS_PACKAGING    NUMBER(10, 2),
    MIN_SCORE_TRANS_OPT          NUMBER(10, 2),
    MAX_SCORE_TRANS_OPT          NUMBER(10, 2),
    MIN_SCORE_WATER_USE          NUMBER(10, 2),
    MAX_SCORE_WATER_USE          NUMBER(10, 2),
    MIN_SCORE_ENERGY_USE         NUMBER(10, 2),
    MAX_SCORE_ENERGY_USE         NUMBER(10, 2),
    MIN_SCORE_ANCILLARY_REQ      NUMBER(10, 2),
    MAX_SCORE_ANCILLARY_REQ      NUMBER(10, 2),
    MIN_SCORE_PROD_WASTE         NUMBER(10, 2),
    MAX_SCORE_PROD_WASTE         NUMBER(10, 2),
    MIN_SCORE_RECYCLABLE_PACK    NUMBER(10, 2),
    MAX_SCORE_RECYCLABLE_PACK    NUMBER(10, 2),
    MIN_SCORE_RECOV_PACK         NUMBER(10, 2),
    MAX_SCORE_RECOV_PACK         NUMBER(10, 2)
)
;

ALTER TABLE SUPPLIER.GT_TARGET_SCORES ADD 
CONSTRAINT GT_TARGET_SCORES_UK
 UNIQUE (APP_SID, GT_PRODUCT_RANGE_ID, GT_PRODUCT_TYPE_ID)
 ENABLE
 VALIDATE;
 
-- 
-- TABLE: GT_TARGET_SCORES 
--

ALTER TABLE GT_TARGET_SCORES ADD CONSTRAINT RefGT_PRODUCT_TYPE487 
    FOREIGN KEY (GT_PRODUCT_TYPE_ID)
    REFERENCES GT_PRODUCT_TYPE(GT_PRODUCT_TYPE_ID)
;

ALTER TABLE GT_TARGET_SCORES ADD CONSTRAINT RefGT_PRODUCT_RANGE488 
    FOREIGN KEY (GT_PRODUCT_RANGE_ID)
    REFERENCES GT_PRODUCT_RANGE(GT_PRODUCT_RANGE_ID)
;

-- add col to questionnaire table
ALTER TABLE SUPPLIER.QUESTIONNAIRE
ADD (PACKAGE_NAME VARCHAR2(256 BYTE));


UPDATE QUESTIONNAIRE SET PACKAGE_NAME='product_wood_pkg' WHERE QUESTIONNAIRE_ID = 1;
UPDATE QUESTIONNAIRE SET PACKAGE_NAME='natural_product_pkg' WHERE QUESTIONNAIRE_ID = 2;
UPDATE QUESTIONNAIRE SET PACKAGE_NAME='product_info_pkg' WHERE QUESTIONNAIRE_ID = 8;
UPDATE QUESTIONNAIRE SET PACKAGE_NAME='gt_packaging_pkg' WHERE QUESTIONNAIRE_ID = 9;
UPDATE QUESTIONNAIRE SET PACKAGE_NAME='gt_formulation_pkg' WHERE QUESTIONNAIRE_ID = 10;
UPDATE QUESTIONNAIRE SET PACKAGE_NAME='gt_transport_pkg' WHERE QUESTIONNAIRE_ID = 11;
UPDATE QUESTIONNAIRE SET PACKAGE_NAME='gt_supplier_pkg' WHERE QUESTIONNAIRE_ID = 12;



@update_tail
