-- Please update version.sql too -- this keeps clean builds in sync
define version=48
@update_header

-- insert into the questionnaire table as shows titles properly on q page then
INSERT INTO SUPPLIER.QUESTIONNAIRE (QUESTIONNAIRE_ID, CLASS_NAME, FRIENDLY_NAME, DESCRIPTION, ACTIVE) VALUES (8, 'gtProductInfo', 'GT ProductInfo', '', 1);
INSERT INTO SUPPLIER.QUESTIONNAIRE (QUESTIONNAIRE_ID, CLASS_NAME, FRIENDLY_NAME, DESCRIPTION, ACTIVE) VALUES (9, 'gtPackaging', 'GT Packaging', '', 1);
INSERT INTO SUPPLIER.QUESTIONNAIRE (QUESTIONNAIRE_ID, CLASS_NAME, FRIENDLY_NAME, DESCRIPTION, ACTIVE) VALUES (10, 'gtFormulation', 'GT Formulation', '', 1);
INSERT INTO SUPPLIER.QUESTIONNAIRE (QUESTIONNAIRE_ID, CLASS_NAME, FRIENDLY_NAME, DESCRIPTION, ACTIVE) VALUES (11, 'gtTransport', 'GT Transport', '', 1);
INSERT INTO SUPPLIER.QUESTIONNAIRE (QUESTIONNAIRE_ID, CLASS_NAME, FRIENDLY_NAME, DESCRIPTION, ACTIVE) VALUES (12, 'gtSupplier', 'GT Supplier', '', 1);

@update_tail
