VARIABLE version NUMBER
BEGIN :version := 11; END; -- CHANGE THIS TO MATCH VERSION NUMBER
/

WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
	v_version	version.db_version%TYPE;
BEGIN
	SELECT db_version INTO v_version FROM supplier.version;
	IF v_version >= :version THEN
		RAISE_APPLICATION_ERROR(-20001, '========= UPDATE '||:version||' HAS ALREADY BEEN APPLIED =======');
	END IF;
	IF v_version + 1 <> :version THEN
		RAISE_APPLICATION_ERROR(-20001, '========= UPDATE '||:version||' CANNOT BE APPLIED TO A DATABASE OF VERSION '||v_version||' =======');
	END IF;
END;
/

INSERT INTO SUPPLIER.NP_KINGDOM (NP_KINGDOM_ID, NAME, DESCRIPTION) VALUES ( 1, 'Flora', 'Flora');
INSERT INTO SUPPLIER.NP_KINGDOM (NP_KINGDOM_ID, NAME, DESCRIPTION) VALUES ( 2, 'Fauna', 'Fauna');
INSERT INTO SUPPLIER.NP_KINGDOM (NP_KINGDOM_ID, NAME, DESCRIPTION) VALUES ( 3, 'Fungi', 'Fungi');

INSERT INTO SUPPLIER.NP_EVIDENCE_TYPE (NP_EVIDENCE_TYPE_ID, NAME, DESCRIPTION) VALUES (1 , 'Certification Scheme', 'Certification Scheme');
INSERT INTO SUPPLIER.NP_EVIDENCE_TYPE (NP_EVIDENCE_TYPE_ID, NAME, DESCRIPTION) VALUES (2 , 'Export Certificate', 'Export Certificate');
INSERT INTO SUPPLIER.NP_EVIDENCE_TYPE (NP_EVIDENCE_TYPE_ID, NAME, DESCRIPTION) VALUES (3 , 'Other', 'Other');
INSERT INTO SUPPLIER.NP_EVIDENCE_TYPE (NP_EVIDENCE_TYPE_ID, NAME, DESCRIPTION) VALUES (4 , 'None', 'None');

INSERT INTO SUPPLIER.NP_EVIDENCE_CLASS (NP_EVIDENCE_CLASS_ID, NAME, DESCRIPTION) VALUES (1 , 'Species', 'Species');
INSERT INTO SUPPLIER.NP_EVIDENCE_CLASS (NP_EVIDENCE_CLASS_ID, NAME, DESCRIPTION) VALUES (2 , 'Growing / Harvesting', 'Growing / Harvesting');
INSERT INTO SUPPLIER.NP_EVIDENCE_CLASS (NP_EVIDENCE_CLASS_ID, NAME, DESCRIPTION) VALUES (3 , 'Processing', 'Processing');
INSERT INTO SUPPLIER.NP_EVIDENCE_CLASS (NP_EVIDENCE_CLASS_ID, NAME, DESCRIPTION) VALUES (4 , 'Final Product Production', 'Final Product Production');

INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (1,'Anion exchange','Anion exchange');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (2,'Bleaching - with chemical addition','Bleaching - with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (3,'Cation exchange','Cation exchange');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (4,'Conversion - with chemical addition or synthesis','Conversion - with chemical addition or synthesis');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (5,'Curing - with chemical addition','Curing - with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (6,'Decaffeination - with chemical addition','Decaffeination - with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (7,'Enzymolysis','Enzymolysis');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (8,'Esterification','Esterification');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (9,'Hormonal action','Hormonal action');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (10,'Hydrogenation','Hydrogenation');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (11,'Hydrolysis - with chemical addition','Hydrolysis - with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (12,'Interesterification','Interesterification');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (13,'Oxidation - with chemical addition','Oxidation - with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (14,'Reduction -  with chemical addition','Reduction -  with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (15,'Smoking -  with chemical addition','Smoking -  with chemical addition');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (16,'Synthesis - chemical','Synthesis - chemical');
INSERT INTO NP_PRODUCTION_PROCESS (NP_PRODUCTION_PROCESS_ID, NAME, DESCRIPTION)  VALUES (17,'Tenderising -  with chemical addition','Tenderising -  with chemical addition');


UPDATE supplier.version SET db_version = :version;
COMMIT;

PROMPT
PROMPT ================== UPDATED OK ========================
EXIT
