-- Please update version.sql too -- this keeps clean builds in sync
define version=59
@update_header


-- 
-- TABLE: GT_SCORES_GIFT 
--

CREATE TABLE GT_SCORES_GIFT(
    PRODUCT_ID               NUMBER(10, 0)    NOT NULL,
    REVISION_ID              NUMBER(10, 0)    NOT NULL,
    SCORE_NAT_DERIVED        NUMBER(10, 2),
    SCORE_CHEMICALS          NUMBER(10, 2),
    SCORE_SOURCE_BIOD        NUMBER(10, 2),
    SCORE_ACCRED_BIOD        NUMBER(10, 2),
    SCORE_FAIR_TRADE         NUMBER(10, 2),
    SCORE_RENEW_PACK         NUMBER(10, 2),
    SCORE_WHATS_IN_PROD      NUMBER(10, 2),
    SCORE_WATER_IN_PROD      NUMBER(10, 2),
    SCORE_ENERGY_IN_PROD     NUMBER(10, 2),
    SCORE_PACK_IMPACT        NUMBER(10, 2),
    SCORE_PACK_OPT           NUMBER(10, 2),
    SCORE_RECYCLED_PACK      NUMBER(10, 2),
    SCORE_SUPP_MANAGEMENT    NUMBER(10, 2),
    SCORE_TRANS_RAW_MAT      NUMBER(10, 2),
    SCORE_TRANS_TO_BOOTS     NUMBER(10, 2),
    SCORE_TRANS_PACKAGING    NUMBER(10, 2),
    SCORE_TRANS_OPT          NUMBER(10, 2),
    SCORE_WATER_USE          NUMBER(10, 2),
    SCORE_ENERGY_USE         NUMBER(10, 2),
    SCORE_ANCILLARY_REQ      NUMBER(10, 2),
    SCORE_PROD_WASTE         NUMBER(10, 2),
    SCORE_RECYCLABLE_PACK    NUMBER(10, 2),
    SCORE_RECOV_PACK         NUMBER(10, 2),
    CONSTRAINT PK258_1 PRIMARY KEY (PRODUCT_ID, REVISION_ID)
)
;

-- 
-- TABLE: GT_SCORES_GIFT 
--

ALTER TABLE GT_SCORES_GIFT ADD CONSTRAINT RefPRODUCT_REVISION476 
    FOREIGN KEY (PRODUCT_ID, REVISION_ID)
    REFERENCES PRODUCT_REVISION(PRODUCT_ID, REVISION_ID)
;

ALTER TABLE GT_SCORES_GIFT ADD CONSTRAINT RefALL_PRODUCT477 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES ALL_PRODUCT(PRODUCT_ID)
;



@update_tail
