-- Please update version.sql too -- this keeps clean builds in sync
define version=42
@update_header

PROMPT set score tables to default -1 

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_NAT_DERIVED  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_CHEMICALS  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_SOURCE_BIOD  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_ACCRED_BIOD  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_FAIR_TRADE  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_RENEW_PACK  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_WHATS_IN_PROD  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_WATER_IN_PROD  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_ENERGY_IN_PROD  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_PACK_IMPACT  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_PACK_OPT  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_RECYCLED_PACK  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_SUPP_MANAGEMENT  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_TRANS_RAW_MAT  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_TRANS_TO_BOOTS  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_TRANS_PACKAGING  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_TRANS_OPT  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_WATER_USE  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_ENERGY_USE  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_ANCILLARY_REQ  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_PROD_WASTE  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_RECYCLABLE_PACK  DEFAULT -1);

ALTER TABLE SUPPLIER.GT_SCORES
MODIFY(SCORE_RECOV_PACK  DEFAULT -1);


PROMPT set profile table to be fully nullable
ALTER TABLE SUPPLIER.GT_PROFILE
MODIFY(BIOPOLYMER_USED  NULL);

ALTER TABLE SUPPLIER.GT_PROFILE
MODIFY(BIOPOLYMER_USED  DEFAULT NULL);

ALTER TABLE SUPPLIER.GT_PROFILE
MODIFY(ORIGIN_TYPE  NULL);

-- put boots supplier stuff onsite scores into score table 
INSERT INTO SUPPLIER.GT_TRANS_REGION_SCORING (GT_REGION_ID, GT_TRANSPORT_TYPE_ID, GT_SCORE) VALUES (1, 0, 1);
INSERT INTO SUPPLIER.GT_TRANS_REGION_SCORING (GT_REGION_ID, GT_TRANSPORT_TYPE_ID, GT_SCORE) VALUES (2, 0, 1);

@update_tail
