--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      NPSL Ltd
-- Project :      donations.dm1
-- Author :       Richard Kirby
--
-- Date Created : Wednesday, June 05, 2013 10:28:04
-- Target DBMS : Oracle 10g
--

-- 
-- SEQUENCE: BUDGET_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.BUDGET_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: CONSTANT_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.CONSTANT_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: DONATION_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.DONATION_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: FILTER_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.FILTER_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: LETTER_BODY_TEXT_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.LETTER_BODY_TEXT_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: LETTER_TEMPLATE_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.LETTER_TEMPLATE_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TAG_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.TAG_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_FIELDSET_ID_SEQ 
--

CREATE SEQUENCE DONATIONS.USER_FIELDSET_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: DONATIONS.BUDGET 
--

CREATE TABLE DONATIONS.BUDGET(
    APP_SID              NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    BUDGET_ID            NUMBER(10, 0)     NOT NULL,
    DESCRIPTION          VARCHAR2(255)     NOT NULL,
    SCHEME_SID           NUMBER(10, 0)     NOT NULL,
    START_DTM            DATE              NOT NULL,
    END_DTM              DATE              NOT NULL,
    MANAGEMENT_COST      NUMBER(16, 2),
    BUDGET_AMOUNT        NUMBER(16, 2),
    REGION_GROUP_SID     NUMBER(10, 0)     NOT NULL,
    CURRENCY_CODE        VARCHAR2(4)       NOT NULL,
    EXCHANGE_RATE        NUMBER(24, 10)    NOT NULL,
    COMPARE_FIELD_NUM    NUMBER(2, 0),
    IS_ACTIVE            NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    CONSTRAINT PK_BUDGET PRIMARY KEY (APP_SID, BUDGET_ID)
)
;



-- 
-- TABLE: DONATIONS.BUDGET_CONSTANT 
--

CREATE TABLE DONATIONS.BUDGET_CONSTANT(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    BUDGET_ID      NUMBER(10, 0)    NOT NULL,
    CONSTANT_ID    NUMBER(10, 0)    NOT NULL,
    VAL            NUMBER(18, 4)    NOT NULL,
    CONSTRAINT PK_BUDGET_CONSTANT PRIMARY KEY (APP_SID, BUDGET_ID, CONSTANT_ID)
)
;



-- 
-- TABLE: DONATIONS.CONSTANT 
--

CREATE TABLE DONATIONS.CONSTANT(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CONSTANT_ID    NUMBER(10, 0)    NOT NULL,
    LOOKUP_KEY     VARCHAR2(255),
    CONSTRAINT PK_CONSTANT PRIMARY KEY (APP_SID, CONSTANT_ID)
)
;



-- 
-- TABLE: DONATIONS.CURRENCY 
--

CREATE TABLE DONATIONS.CURRENCY(
    CURRENCY_CODE    VARCHAR2(4)     NOT NULL,
    SYMBOL           VARCHAR2(4),
    LABEL            VARCHAR2(64)    NOT NULL,
    CONSTRAINT PK_CURRENCY PRIMARY KEY (CURRENCY_CODE)
)
;



-- 
-- TABLE: DONATIONS.CUSTOM_FIELD 
--

CREATE TABLE DONATIONS.CUSTOM_FIELD(
    APP_SID          NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FIELD_NUM        NUMBER(2, 0)      NOT NULL,
    LABEL            VARCHAR2(255)     NOT NULL,
    EXPR             VARCHAR2(1024),
    IS_MANDATORY     NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    NOTE             VARCHAR2(1024),
    LOOKUP_KEY       VARCHAR2(255)     NOT NULL,
    IS_CURRENCY      NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    DETAILED_NOTE    CLOB,
    SECTION          VARCHAR2(64),
    POS              NUMBER(4, 0)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CUSTOM_FIELD PRIMARY KEY (APP_SID, FIELD_NUM),
    CONSTRAINT UK_CUSTOM_FIELD_LOOKUP_KEY  UNIQUE (APP_SID, LOOKUP_KEY)
)
;



-- 
-- TABLE: DONATIONS.CUSTOM_FIELD_DEPENDENCY 
--

CREATE TABLE DONATIONS.CUSTOM_FIELD_DEPENDENCY(
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FIELD_NUM              NUMBER(2, 0)     NOT NULL,
    DEPENDENT_FIELD_NUM    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK109 PRIMARY KEY (APP_SID, FIELD_NUM, DEPENDENT_FIELD_NUM)
)
;



-- 
-- TABLE: DONATIONS.CUSTOMER_DEFAULT_EXRATE 
--

CREATE TABLE DONATIONS.CUSTOMER_DEFAULT_EXRATE(
    APP_SID          NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CURRENCY_CODE    VARCHAR2(4)       NOT NULL,
    EXCHANGE_RATE    NUMBER(24, 10)    NOT NULL,
    CONSTRAINT PK_CUSTOMER_DEFAULT_EXRATE PRIMARY KEY (APP_SID, CURRENCY_CODE)
)
;



-- 
-- TABLE: DONATIONS.CUSTOMER_FILTER_FLAG 
--

CREATE TABLE DONATIONS.CUSTOMER_FILTER_FLAG(
    APP_SID                       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RECIPIENT_REGION_GROUP        NUMBER(1, 0)     NOT NULL,
    BROWSE_REGION_GROUP           NUMBER(1, 0)     NOT NULL,
    REPORT_REGION_GROUP           NUMBER(1, 0)     NOT NULL,
    AUTO_GEN_STATUS_TRANSITION    NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    IS_VERSION_2_ENABLED          NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CUSTOMER_FILTER_FLAG PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: DONATIONS.CUSTOMER_OPTIONS 
--

CREATE TABLE DONATIONS.CUSTOMER_OPTIONS(
    APP_SID                           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DEFAULT_COUNTRY                   VARCHAR2(2),
    DEFAULT_CURRENCY                  VARCHAR2(4),
    DEFAULT_FIELD                     VARCHAR2(255),
    DOCUMENT_DESCRIPTION_ENABLED      NUMBER(1, 0),
    IS_RECIPIENT_TAX_ID_MANDATORY     NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    IS_RECIPIENT_ADDRESS_MANDATORY    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    SHOW_ALL_YEARS_BY_DEFAULT         NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    FC_TAG_ID                         NUMBER(10, 0),
    FC_AMOUNT_FIELD_LOOKUP_KEY        VARCHAR2(255),
    FC_STATUS_TAG_GROUP_SID           NUMBER(10, 0),
    FC_PAID_TAG_ID                    NUMBER(10, 0),
    FC_RECONCILED_TAG_ID              NUMBER(10, 0),
    CONSTRAINT PK104 PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: DONATIONS.CUSTOMER_RECALC 
--

CREATE TABLE DONATIONS.CUSTOMER_RECALC(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROCESSING    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK107 PRIMARY KEY (APP_SID, PROCESSING)
)
;



-- 
-- TABLE: DONATIONS.DONATION 
--

CREATE TABLE DONATIONS.DONATION(
    APP_SID                       NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DONATION_ID                   NUMBER(10, 0)     NOT NULL,
    SCHEME_SID                    NUMBER(10, 0)     NOT NULL,
    RECIPIENT_SID                 NUMBER(10, 0)     NOT NULL,
    BUDGET_ID                     NUMBER(10, 0)     NOT NULL,
    DONATION_STATUS_SID           NUMBER(10, 0)     NOT NULL,
    REGION_SID                    NUMBER(10, 0)     NOT NULL,
    ACTIVITY                      VARCHAR2(1024),
    ENTERED_DTM                   DATE              DEFAULT SYSDATE NOT NULL,
    ENTERED_BY_SID                NUMBER(10, 0)     NOT NULL,
    LAST_STATUS_CHANGED_BY        NUMBER(10, 0)     NOT NULL,
    DONATED_DTM                   DATE,
    PAID_DTM                      DATE,
    PAYMENT_REF                   VARCHAR2(255),
    NOTES                         CLOB              DEFAULT EMPTY_CLOB() NOT NULL,
    DOCUMENT_SID                  NUMBER(10, 0),
    ALLOCATED_FROM_DONATION_ID    NUMBER(10, 0),
    EXTRA_VALUES_XML              CLOB              DEFAULT EMPTY_CLOB() NOT NULL,
    LETTER_BODY_TEXT              CLOB,
    CONTACT_NAME                  VARCHAR2(255),
    LAST_STATUS_CHANGED_DTM       DATE              NOT NULL,
    CUSTOM_1                      NUMBER(16, 2),
    CUSTOM_2                      NUMBER(16, 2),
    CUSTOM_3                      NUMBER(16, 2),
    CUSTOM_4                      NUMBER(16, 2),
    CUSTOM_5                      NUMBER(16, 2),
    CUSTOM_6                      NUMBER(16, 2),
    CUSTOM_7                      NUMBER(16, 2),
    CUSTOM_8                      NUMBER(16, 2),
    CUSTOM_9                      NUMBER(16, 2),
    CUSTOM_10                     NUMBER(16, 2),
    CUSTOM_11                     NUMBER(16, 2),
    CUSTOM_12                     NUMBER(16, 2),
    CUSTOM_13                     NUMBER(16, 2),
    CUSTOM_14                     NUMBER(16, 2),
    CUSTOM_15                     NUMBER(16, 2),
    CUSTOM_16                     NUMBER(16, 2),
    CUSTOM_17                     NUMBER(16, 2),
    CUSTOM_18                     NUMBER(16, 2),
    CUSTOM_19                     NUMBER(16, 2),
    CUSTOM_20                     NUMBER(16, 2),
    CUSTOM_21                     NUMBER(16, 2),
    CUSTOM_22                     NUMBER(16, 2),
    CUSTOM_23                     NUMBER(16, 2),
    CUSTOM_24                     NUMBER(16, 2),
    CUSTOM_25                     NUMBER(16, 2),
    CUSTOM_26                     NUMBER(16, 2),
    CUSTOM_27                     NUMBER(16, 2),
    CUSTOM_28                     NUMBER(16, 2),
    CUSTOM_29                     NUMBER(16, 2),
    CUSTOM_30                     NUMBER(16, 2),
    CUSTOM_31                     NUMBER(16, 2),
    CUSTOM_32                     NUMBER(16, 2),
    CUSTOM_33                     NUMBER(16, 2),
    CUSTOM_34                     NUMBER(16, 2),
    CUSTOM_35                     NUMBER(16, 2),
    CUSTOM_36                     NUMBER(16, 2),
    CUSTOM_37                     NUMBER(16, 2),
    CUSTOM_38                     NUMBER(16, 2),
    CUSTOM_39                     NUMBER(16, 2),
    CUSTOM_40                     NUMBER(16, 2),
    CUSTOM_41                     NUMBER(16, 2),
    CUSTOM_42                     NUMBER(16, 2),
    CUSTOM_43                     NUMBER(16, 2),
    CUSTOM_44                     NUMBER(16, 2),
    CUSTOM_45                     NUMBER(16, 2),
    CUSTOM_46                     NUMBER(16, 2),
    CUSTOM_47                     NUMBER(16, 2),
    CUSTOM_48                     NUMBER(16, 2),
    CUSTOM_49                     NUMBER(16, 2),
    CUSTOM_50                     NUMBER(16, 2),
    CUSTOM_51                     NUMBER(16, 2),
    CUSTOM_52                     NUMBER(16, 2),
    CUSTOM_53                     NUMBER(16, 2),
    CUSTOM_54                     NUMBER(16, 2),
    CUSTOM_55                     NUMBER(16, 2),
    CUSTOM_56                     NUMBER(16, 2),
    CUSTOM_57                     NUMBER(16, 2),
    CUSTOM_58                     NUMBER(16, 2),
    CUSTOM_59                     NUMBER(16, 2),
    CUSTOM_60                     NUMBER(16, 2),
    CUSTOM_61                     NUMBER(16, 2),
    CUSTOM_62                     NUMBER(16, 2),
    CUSTOM_63                     NUMBER(16, 2),
    CUSTOM_64                     NUMBER(16, 2),
    CUSTOM_65                     NUMBER(16, 2),
    CUSTOM_66                     NUMBER(16, 2),
    CUSTOM_67                     NUMBER(16, 2),
    CUSTOM_68                     NUMBER(16, 2),
    CUSTOM_69                     NUMBER(16, 2),
    CUSTOM_70                     NUMBER(16, 2),
    CUSTOM_71                     NUMBER(16, 2),
    CUSTOM_72                     NUMBER(16, 2),
    CUSTOM_73                     NUMBER(16, 2),
    CUSTOM_74                     NUMBER(16, 2),
    CUSTOM_75                     NUMBER(16, 2),
    CUSTOM_76                     NUMBER(16, 2),
    CUSTOM_77                     NUMBER(16, 2),
    CUSTOM_78                     NUMBER(16, 2),
    CUSTOM_79                     NUMBER(16, 2),
    CUSTOM_80                     NUMBER(16, 2),
    CUSTOM_81                     NUMBER(16, 2),
    CUSTOM_82                     NUMBER(16, 2),
    CUSTOM_83                     NUMBER(16, 2),
    CUSTOM_84                     NUMBER(16, 2),
    CUSTOM_85                     NUMBER(16, 2),
    CUSTOM_86                     NUMBER(16, 2),
    CUSTOM_87                     NUMBER(16, 2),
    CUSTOM_88                     NUMBER(16, 2),
    CUSTOM_89                     NUMBER(16, 2),
    CUSTOM_90                     NUMBER(16, 2),
    CUSTOM_91                     NUMBER(16, 2),
    CUSTOM_92                     NUMBER(16, 2),
    CUSTOM_93                     NUMBER(16, 2),
    CUSTOM_94                     NUMBER(16, 2),
    CUSTOM_95                     NUMBER(16, 2),
    CUSTOM_96                     NUMBER(16, 2),
    CUSTOM_97                     NUMBER(16, 2),
    CUSTOM_98                     NUMBER(16, 2),
    CUSTOM_99                     NUMBER(16, 2),
    CUSTOM_100                    NUMBER(16, 2),
    CUSTOM_101                    NUMBER(16, 2),
    CUSTOM_102                    NUMBER(16, 2),
    CUSTOM_103                    NUMBER(16, 2),
    CUSTOM_104                    NUMBER(16, 2),
    CUSTOM_105                    NUMBER(16, 2),
    CUSTOM_106                    NUMBER(16, 2),
    CUSTOM_107                    NUMBER(16, 2),
    CUSTOM_108                    NUMBER(16, 2),
    CUSTOM_109                    NUMBER(16, 2),
    CUSTOM_110                    NUMBER(16, 2),
    CUSTOM_111                    NUMBER(16, 2),
    CUSTOM_112                    NUMBER(16, 2),
    CUSTOM_113                    NUMBER(16, 2),
    CUSTOM_114                    NUMBER(16, 2),
    CUSTOM_115                    NUMBER(16, 2),
    CUSTOM_116                    NUMBER(16, 2),
    CUSTOM_117                    NUMBER(16, 2),
    CUSTOM_118                    NUMBER(16, 2),
    CUSTOM_119                    NUMBER(16, 2),
    CUSTOM_120                    NUMBER(16, 2),
    END_DTM                       DATE,
    CONSTRAINT PK_DONATION PRIMARY KEY (APP_SID, DONATION_ID)
)
;



-- 
-- TABLE: DONATIONS.DONATION_DOC 
--

CREATE TABLE DONATIONS.DONATION_DOC(
    APP_SID         NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DONATION_ID     NUMBER(10, 0)     NOT NULL,
    DOCUMENT_SID    NUMBER(10, 0)     NOT NULL,
    DESCRIPTION     VARCHAR2(2048),
    CONSTRAINT PK_DONATION_DOC PRIMARY KEY (APP_SID, DONATION_ID, DOCUMENT_SID)
)
;



-- 
-- TABLE: DONATIONS.DONATION_STATUS 
--

CREATE TABLE DONATIONS.DONATION_STATUS(
    APP_SID                     NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DONATION_STATUS_SID         NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                 VARCHAR2(255)     NOT NULL,
    INCLUDE_VALUE_IN_REPORTS    NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    POS                         NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    MEANS_PAID                  NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    MEANS_DONATED               NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    COLOUR                      NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    LETTER_ACTIVE               NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    WARNING_MSG                 VARCHAR2(2000),
    SHOW_FOR_NEW_DONATION       NUMBER(1, 0)      DEFAULT 1 NOT NULL
                                CONSTRAINT CK_SHOW_STATUS_FOR_NEW_DON CHECK (SHOW_FOR_NEW_DONATION IN (0,1)),
    CONSTRAINT PK_DONATION_STATUS PRIMARY KEY (APP_SID, DONATION_STATUS_SID)
)
;



-- 
-- TABLE: DONATIONS.DONATION_TAG 
--

CREATE TABLE DONATIONS.DONATION_TAG(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DONATION_ID     NUMBER(10, 0)    NOT NULL,
    TAG_ID          NUMBER(10, 0)    NOT NULL,
    PCT_OF_VALUE    NUMBER(10, 2)    DEFAULT 1 NOT NULL,
    CONSTRAINT PK_DONATION_TAG PRIMARY KEY (APP_SID, DONATION_ID, TAG_ID)
)
;



-- 
-- TABLE: DONATIONS.EXCLUDE_TAG 
--

CREATE TABLE DONATIONS.EXCLUDE_TAG(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SCHEME_SID    NUMBER(10, 0)    NOT NULL,
    TAG_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK111 PRIMARY KEY (APP_SID, SCHEME_SID, TAG_ID)
)
;



-- 
-- TABLE: DONATIONS.FC_BUDGET 
--

CREATE TABLE DONATIONS.FC_BUDGET(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    BUDGET_ID                 NUMBER(10, 0)     NOT NULL,
    FUNDING_COMMITMENT_SID    NUMBER(10, 0)     NOT NULL,
    AMOUNT                    NUMBER(24, 10),
    CONSTRAINT PK129 PRIMARY KEY (APP_SID, BUDGET_ID, FUNDING_COMMITMENT_SID)
)
;



-- 
-- TABLE: DONATIONS.FC_DEFAULT_TAG 
--

CREATE TABLE DONATIONS.FC_DEFAULT_TAG(
    APP_SID    NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK146 PRIMARY KEY (TAG_ID, APP_SID)
)
;



-- 
-- TABLE: DONATIONS.FC_DONATION 
--

CREATE TABLE DONATIONS.FC_DONATION(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FUNDING_COMMITMENT_SID    NUMBER(10, 0)    NOT NULL,
    DONATION_ID               NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK139 PRIMARY KEY (APP_SID, FUNDING_COMMITMENT_SID, DONATION_ID)
)
;



-- 
-- TABLE: DONATIONS.FC_TAG 
--

CREATE TABLE DONATIONS.FC_TAG(
    TAG_ID                    NUMBER(10, 0)    NOT NULL,
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FUNDING_COMMITMENT_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK137 PRIMARY KEY (TAG_ID, APP_SID, FUNDING_COMMITMENT_SID)
)
;



-- 
-- TABLE: DONATIONS.FC_UPLOAD 
--

CREATE TABLE DONATIONS.FC_UPLOAD(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FC_UPLOAD_SID             NUMBER(10, 0)    NOT NULL,
    FUNDING_COMMITMENT_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK124 PRIMARY KEY (APP_SID, FC_UPLOAD_SID, FUNDING_COMMITMENT_SID)
)
;



-- 
-- TABLE: DONATIONS.FILTER 
--

CREATE TABLE DONATIONS.FILTER(
    APP_SID          NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FILTER_ID        NUMBER(10, 0)     NOT NULL,
    CSR_USER_SID     NUMBER(10, 0)     NOT NULL,
    IS_SHARED        NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    NAME             VARCHAR2(255)     NOT NULL,
    DESCRIPTION      VARCHAR2(2048),
    LAST_USED_DTM    DATE              DEFAULT SYSDATE NOT NULL,
    FILTER_XML       SYS.XMLType,
    COLUMN_XML       SYS.XMLType,
    FILTER_TYPE      NUMBER(1, 0)      NOT NULL,
    CONSTRAINT PK_FILTER PRIMARY KEY (APP_SID, FILTER_ID)
)
;



-- 
-- TABLE: DONATIONS.FUNDING_COMMITMENT 
--

CREATE TABLE DONATIONS.FUNDING_COMMITMENT(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FUNDING_COMMITMENT_SID    NUMBER(10, 0)     NOT NULL,
    SCHEME_SID                NUMBER(10, 0)     NOT NULL,
    RECIPIENT_SID             NUMBER(10, 0)     NOT NULL,
    REGION_GROUP_SID          NUMBER(10, 0)     NOT NULL,
    REGION_SID                NUMBER(10, 0)     NOT NULL,
    DONATION_STATUS_SID       NUMBER(10, 0)     NOT NULL,
    CSR_USER_SID              NUMBER(10, 0)     NOT NULL,
    CHARITY_BUDGET_TAG_ID     NUMBER(10, 0),
    NAME                      VARCHAR2(255)     NOT NULL,
    DESCRIPTION               VARCHAR2(1023),
    PAYMENT_DTM               DATE,
    REMINDER_DTM              DATE,
    NOTES                     CLOB,
    REVIEW_ON_EXPIRY          NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    LAST_REVIEW_DTM           DATE,
    REMINDER_SENT_DTM         DATE,
    CONSTRAINT PK119 PRIMARY KEY (APP_SID, FUNDING_COMMITMENT_SID)
)
;



-- 
-- TABLE: DONATIONS.LETTER_BODY_REGION_GROUP 
--

CREATE TABLE DONATIONS.LETTER_BODY_REGION_GROUP(
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_GROUP_SID       NUMBER(10, 0)    NOT NULL,
    LETTER_BODY_TEXT_ID    NUMBER(10, 0)    NOT NULL,
    DONATION_STATUS_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_LETTER_BODY_REGION_GROUP PRIMARY KEY (APP_SID, REGION_GROUP_SID, LETTER_BODY_TEXT_ID, DONATION_STATUS_SID)
)
;



-- 
-- TABLE: DONATIONS.LETTER_BODY_TEXT 
--

CREATE TABLE DONATIONS.LETTER_BODY_TEXT(
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    LETTER_BODY_TEXT_ID    NUMBER(10, 0)    NOT NULL,
    DONATION_STATUS_SID    NUMBER(10, 0)    NOT NULL,
    BODY_TEXT              CLOB,
    ACTIVE                 NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_LETTER_BODY_TEXT PRIMARY KEY (APP_SID, LETTER_BODY_TEXT_ID, DONATION_STATUS_SID)
)
;



-- 
-- TABLE: DONATIONS.LETTER_TEMPLATE 
--

CREATE TABLE DONATIONS.LETTER_TEMPLATE(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    LETTER_TEMPLATE_ID    NUMBER(10, 0)    NOT NULL,
    NAME                  VARCHAR2(512)    NOT NULL,
    DATA                  BLOB,
    CONSTRAINT PK_LETTER_TEMPLATE PRIMARY KEY (APP_SID, LETTER_TEMPLATE_ID)
)
;



-- 
-- TABLE: DONATIONS.RECIPIENT 
--

CREATE TABLE DONATIONS.RECIPIENT(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RECIPIENT_SID       NUMBER(10, 0)    NOT NULL,
    PARENT_SID          NUMBER(10, 0),
    ORG_NAME            VARCHAR2(255)    NOT NULL,
    ORG_NAME_SOUNDEX    VARCHAR2(255)    NOT NULL,
    CONTACT_NAME        VARCHAR2(255),
    ADDRESS_1           VARCHAR2(255),
    ADDRESS_2           VARCHAR2(255),
    ADDRESS_3           VARCHAR2(255),
    ADDRESS_4           VARCHAR2(255),
    TOWN                VARCHAR2(255),
    STATE               VARCHAR2(255),
    POSTCODE            VARCHAR2(255),
    PHONE               VARCHAR2(255),
    PHONE_ALT           VARCHAR2(255),
    FAX                 VARCHAR2(255),
    COUNTRY_CODE        VARCHAR2(2)      NOT NULL,
    EMAIL               VARCHAR2(255),
    REF                 VARCHAR2(255),
    ACCOUNT_NUM         VARCHAR2(255),
    SORT_CODE           VARCHAR2(64),
    TAX_ID              VARCHAR2(128),
    BANK_NAME           VARCHAR2(255),
    LAST_USED_DTM       DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RECIPIENT PRIMARY KEY (APP_SID, RECIPIENT_SID)
)
;



-- 
-- TABLE: DONATIONS.RECIPIENT_POSTIT 
--

CREATE TABLE DONATIONS.RECIPIENT_POSTIT(
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RECIPIENT_SID    NUMBER(10, 0)    NOT NULL,
    POSTIT_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RECIPIENT_POSTIT PRIMARY KEY (APP_SID, RECIPIENT_SID, POSTIT_ID)
)
;



-- 
-- TABLE: DONATIONS.RECIPIENT_TAG 
--

CREATE TABLE DONATIONS.RECIPIENT_TAG(
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RECIPIENT_SID    NUMBER(10, 0)    NOT NULL,
    TAG_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RECIPIENT_TAG PRIMARY KEY (APP_SID, RECIPIENT_SID, TAG_ID)
)
;



-- 
-- TABLE: DONATIONS.RECIPIENT_TAG_GROUP 
--

CREATE TABLE DONATIONS.RECIPIENT_TAG_GROUP(
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    POS              NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK131 PRIMARY KEY (APP_SID, TAG_GROUP_SID)
)
;



-- 
-- TABLE: DONATIONS.REGION_FILTER_TAG_GROUP 
--

CREATE TABLE DONATIONS.REGION_FILTER_TAG_GROUP(
    REGION_TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CONSTRAINT PK141 PRIMARY KEY (REGION_TAG_GROUP_ID, APP_SID)
)
;



-- 
-- TABLE: DONATIONS.REGION_GROUP 
--

CREATE TABLE DONATIONS.REGION_GROUP(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_GROUP_SID      NUMBER(10, 0)    NOT NULL,
    DESCRIPTION           VARCHAR2(255)    NOT NULL,
    LETTER_TEMPLATE_ID    NUMBER(10, 0),
    CONSTRAINT PK_REGION_GROUP PRIMARY KEY (APP_SID, REGION_GROUP_SID)
)
;



-- 
-- TABLE: DONATIONS.REGION_GROUP_MEMBER 
--

CREATE TABLE DONATIONS.REGION_GROUP_MEMBER(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SID          NUMBER(10, 0)    NOT NULL,
    REGION_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_REGION_GROUP_MEMBER PRIMARY KEY (APP_SID, REGION_SID, REGION_GROUP_SID)
)
;



-- 
-- TABLE: DONATIONS.REGION_GROUP_RECIPIENT 
--

CREATE TABLE DONATIONS.REGION_GROUP_RECIPIENT(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    RECIPIENT_SID       NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_REGION_GROUP_RECIPIENT PRIMARY KEY (APP_SID, REGION_GROUP_SID, RECIPIENT_SID)
)
;



-- 
-- TABLE: DONATIONS.SCHEME 
--

CREATE TABLE DONATIONS.SCHEME(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SCHEME_SID                NUMBER(10, 0)     NOT NULL,
    NAME                      VARCHAR2(256)     NOT NULL,
    DESCRIPTION               VARCHAR2(2048),
    ACTIVE                    NUMBER(10, 0)     DEFAULT 1 NOT NULL,
    EXTRA_FIELDS_XML          CLOB              DEFAULT EMPTY_CLOB() NOT NULL,
    NOTE_HACK                 CLOB,
    TRACK_PAYMENTS            NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    TRACK_COMPANY_GIVING      NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    TRACK_CHARITY_BUDGET      NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    TRACK_DONATION_END_DTM    NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    HELPER_PKG                VARCHAR2(255),
    CONSTRAINT PK_SCHEME PRIMARY KEY (APP_SID, SCHEME_SID)
)
;



-- 
-- TABLE: DONATIONS.SCHEME_DONATION_STATUS 
--

CREATE TABLE DONATIONS.SCHEME_DONATION_STATUS(
    SCHEME_SID             NUMBER(10, 0)    NOT NULL,
    DONATION_STATUS_SID    NUMBER(10, 0)    NOT NULL,
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CONSTRAINT PK102 PRIMARY KEY (SCHEME_SID, DONATION_STATUS_SID, APP_SID)
)
;



-- 
-- TABLE: DONATIONS.SCHEME_FIELD 
--

CREATE TABLE DONATIONS.SCHEME_FIELD(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FIELD_NUM         NUMBER(2, 0)     NOT NULL,
    SCHEME_SID        NUMBER(10, 0)    NOT NULL,
    SHOW_IN_BROWSE    NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SCHEME_FIELD PRIMARY KEY (APP_SID, FIELD_NUM, SCHEME_SID)
)
;



-- 
-- TABLE: DONATIONS.SCHEME_TAG_GROUP 
--

CREATE TABLE DONATIONS.SCHEME_TAG_GROUP(
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SCHEME_SID       NUMBER(10, 0)    NOT NULL,
    TAG_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    POS              NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SCHEME_TAG_GROUP PRIMARY KEY (APP_SID, SCHEME_SID, TAG_GROUP_SID)
)
;



-- 
-- TABLE: DONATIONS.TAG 
--

CREATE TABLE DONATIONS.TAG(
    APP_SID        NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_ID         NUMBER(10, 0)     NOT NULL,
    TAG            VARCHAR2(255)     NOT NULL,
    EXPLANATION    VARCHAR2(1024),
    CONSTRAINT PK_TAG PRIMARY KEY (APP_SID, TAG_ID)
)
;



-- 
-- TABLE: DONATIONS.TAG_GROUP 
--

CREATE TABLE DONATIONS.TAG_GROUP(
    APP_SID           NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_GROUP_SID     NUMBER(10, 0)     NOT NULL,
    NAME              VARCHAR2(255)     NOT NULL,
    MULTI_SELECT      NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    MANDATORY         NUMBER(10, 0)     DEFAULT 1 NOT NULL,
    RENDER_AS         CHAR(1)           DEFAULT 'X' NOT NULL,
    RENDER_IN         CHAR(1)           DEFAULT 'V' NOT NULL,
    NOTE              VARCHAR2(1024),
    DETAILED_NOTE     CLOB,
    SHOW_IN_FILTER    NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TAG_GROUP PRIMARY KEY (APP_SID, TAG_GROUP_SID)
)
;



-- 
-- TABLE: DONATIONS.TAG_GROUP_MEMBER 
--

CREATE TABLE DONATIONS.TAG_GROUP_MEMBER(
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    TAG_ID           NUMBER(10, 0)    NOT NULL,
    POS              NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    IS_VISIBLE       NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TAG_GROUP_MEMBER PRIMARY KEY (APP_SID, TAG_GROUP_SID, TAG_ID)
)
;



-- 
-- TABLE: DONATIONS.TRANSITION 
--

CREATE TABLE DONATIONS.TRANSITION(
    APP_SID                     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TRANSITION_SID              NUMBER(10, 0)    NOT NULL,
    FROM_DONATION_STATUS_SID    NUMBER(10, 0)    NOT NULL,
    TO_DONATION_STATUS_SID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TRANSITION PRIMARY KEY (APP_SID, TRANSITION_SID)
)
;



-- 
-- TABLE: DONATIONS.UK_CHARITY 
--

CREATE TABLE DONATIONS.UK_CHARITY(
    CHARITY_NUMBER           VARCHAR2(40)      NOT NULL,
    TITLE                    VARCHAR2(255),
    ACTIVITIES               VARCHAR2(4000),
    CONTACT_NAME             VARCHAR2(255),
    ADDRESS                  VARCHAR2(255),
    WEBSITE                  VARCHAR2(255),
    TELEPHONE                VARCHAR2(255),
    DATE_REGISTERED          DATE,
    DATE_REMOVED             DATE,
    ACCOUNTS_DATE            DATE,
    SPENDING                 NUMBER(10, 0),
    INCOME                   NUMBER(10, 0),
    COMPANY_NUMBER           VARCHAR2(255),
    OPENLYLOCAL_URL          VARCHAR2(255),
    TWITTER_ACCOUNT_NAME     VARCHAR2(255),
    FACEBOOK_ACCOUNT_NAME    VARCHAR2(255),
    YOUTUBE_ACCOUNT_NAME     VARCHAR2(255),
    CREATED_AT               DATE              NOT NULL,
    UPDATED_AT               DATE              NOT NULL,
    CONSTRAINT PK_UK_CHARITY PRIMARY KEY (CHARITY_NUMBER)
)
;



-- 
-- TABLE: DONATIONS.USER_FIELDSET 
--

CREATE TABLE DONATIONS.USER_FIELDSET(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    USER_FIELDSET_ID    NUMBER(10, 0)    NOT NULL,
    CSR_USER_SID        NUMBER(10, 0)    NOT NULL,
    NAME                VARCHAR2(512),
    CONSTRAINT PK_USER_FIELDSET PRIMARY KEY (APP_SID, USER_FIELDSET_ID)
)
;



-- 
-- TABLE: DONATIONS.USER_FIELDSET_FIELD 
--

CREATE TABLE DONATIONS.USER_FIELDSET_FIELD(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FIELD_NAME          VARCHAR2(512)    NOT NULL,
    USER_FIELDSET_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_USER_FIELDSET_FIELD PRIMARY KEY (APP_SID, FIELD_NAME, USER_FIELDSET_ID)
)
;



-- 
-- INDEX: DONATIONS.UK_CONSTANT_KEY 
--

CREATE UNIQUE INDEX DONATIONS.UK_CONSTANT_KEY ON DONATIONS.CONSTANT(APP_SID, LOOKUP_KEY)
;
-- 
-- TABLE: DONATIONS.BUDGET 
--

ALTER TABLE DONATIONS.BUDGET ADD CONSTRAINT RefSCHEME48 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;

ALTER TABLE DONATIONS.BUDGET ADD CONSTRAINT RefREGION_GROUP67 
    FOREIGN KEY (APP_SID, REGION_GROUP_SID)
    REFERENCES DONATIONS.REGION_GROUP(APP_SID, REGION_GROUP_SID)
;

ALTER TABLE DONATIONS.BUDGET ADD CONSTRAINT RefCURRENCY103 
    FOREIGN KEY (CURRENCY_CODE)
    REFERENCES DONATIONS.CURRENCY(CURRENCY_CODE)
;


-- 
-- TABLE: DONATIONS.BUDGET_CONSTANT 
--

ALTER TABLE DONATIONS.BUDGET_CONSTANT ADD CONSTRAINT RefCONSTANT111 
    FOREIGN KEY (APP_SID, CONSTANT_ID)
    REFERENCES DONATIONS.CONSTANT(APP_SID, CONSTANT_ID)
;

ALTER TABLE DONATIONS.BUDGET_CONSTANT ADD CONSTRAINT RefBUDGET112 
    FOREIGN KEY (APP_SID, BUDGET_ID)
    REFERENCES DONATIONS.BUDGET(APP_SID, BUDGET_ID)
;


-- 
-- TABLE: DONATIONS.CUSTOM_FIELD_DEPENDENCY 
--

ALTER TABLE DONATIONS.CUSTOM_FIELD_DEPENDENCY ADD CONSTRAINT RefCUSTOM_FIELD168 
    FOREIGN KEY (APP_SID, DEPENDENT_FIELD_NUM)
    REFERENCES DONATIONS.CUSTOM_FIELD(APP_SID, FIELD_NUM)
;

ALTER TABLE DONATIONS.CUSTOM_FIELD_DEPENDENCY ADD CONSTRAINT RefCUSTOM_FIELD169 
    FOREIGN KEY (APP_SID, FIELD_NUM)
    REFERENCES DONATIONS.CUSTOM_FIELD(APP_SID, FIELD_NUM)
;


-- 
-- TABLE: DONATIONS.CUSTOMER_DEFAULT_EXRATE 
--

ALTER TABLE DONATIONS.CUSTOMER_DEFAULT_EXRATE ADD CONSTRAINT RefCURRENCY105 
    FOREIGN KEY (CURRENCY_CODE)
    REFERENCES DONATIONS.CURRENCY(CURRENCY_CODE)
;


-- 
-- TABLE: DONATIONS.CUSTOMER_OPTIONS 
--

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOM_FIELD176 
    FOREIGN KEY (APP_SID, FC_AMOUNT_FIELD_LOOKUP_KEY)
    REFERENCES DONATIONS.CUSTOM_FIELD(APP_SID, LOOKUP_KEY)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefTAG241 
    FOREIGN KEY (APP_SID, FC_TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOM_FIELD248 
    FOREIGN KEY (APP_SID, DEFAULT_FIELD)
    REFERENCES DONATIONS.CUSTOM_FIELD(APP_SID, LOOKUP_KEY)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefTAG_GROUP258 
    FOREIGN KEY (APP_SID, FC_STATUS_TAG_GROUP_SID)
    REFERENCES DONATIONS.TAG_GROUP(APP_SID, TAG_GROUP_SID)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefCURRENCY162 
    FOREIGN KEY (DEFAULT_CURRENCY)
    REFERENCES DONATIONS.CURRENCY(CURRENCY_CODE)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT FK_FC_PAID_TAG_ID 
    FOREIGN KEY (APP_SID, FC_PAID_TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT FK_FC_RECONCILED_TAG_ID 
    FOREIGN KEY (APP_SID, FC_RECONCILED_TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;


-- 
-- TABLE: DONATIONS.DONATION 
--

ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefBUDGET50 
    FOREIGN KEY (APP_SID, BUDGET_ID)
    REFERENCES DONATIONS.BUDGET(APP_SID, BUDGET_ID)
;

ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefDONATION51 
    FOREIGN KEY (APP_SID, ALLOCATED_FROM_DONATION_ID)
    REFERENCES DONATIONS.DONATION(APP_SID, DONATION_ID)
;

ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefDONATION_STATUS52 
    FOREIGN KEY (APP_SID, DONATION_STATUS_SID)
    REFERENCES DONATIONS.DONATION_STATUS(APP_SID, DONATION_STATUS_SID)
;

ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefSCHEME53 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;

ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefRECIPIENT54 
    FOREIGN KEY (APP_SID, RECIPIENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID)
;

-- 
-- TABLE: DONATIONS.DONATION_DOC 
--

ALTER TABLE DONATIONS.DONATION_DOC ADD CONSTRAINT RefDONATION124 
    FOREIGN KEY (APP_SID, DONATION_ID)
    REFERENCES DONATIONS.DONATION(APP_SID, DONATION_ID)
;

-- 
-- TABLE: DONATIONS.DONATION_TAG 
--

ALTER TABLE DONATIONS.DONATION_TAG ADD CONSTRAINT RefTAG55 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE DONATIONS.DONATION_TAG ADD CONSTRAINT RefDONATION56 
    FOREIGN KEY (APP_SID, DONATION_ID)
    REFERENCES DONATIONS.DONATION(APP_SID, DONATION_ID)
;


-- 
-- TABLE: DONATIONS.EXCLUDE_TAG 
--

ALTER TABLE DONATIONS.EXCLUDE_TAG ADD CONSTRAINT RefTAG172 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE DONATIONS.EXCLUDE_TAG ADD CONSTRAINT RefSCHEME173 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;


-- 
-- TABLE: DONATIONS.FC_BUDGET 
--

ALTER TABLE DONATIONS.FC_BUDGET ADD CONSTRAINT RefBUDGET218 
    FOREIGN KEY (APP_SID, BUDGET_ID)
    REFERENCES DONATIONS.BUDGET(APP_SID, BUDGET_ID)
;

ALTER TABLE DONATIONS.FC_BUDGET ADD CONSTRAINT RefFUNDING_COMMITMENT219 
    FOREIGN KEY (APP_SID, FUNDING_COMMITMENT_SID)
    REFERENCES DONATIONS.FUNDING_COMMITMENT(APP_SID, FUNDING_COMMITMENT_SID)
;


-- 
-- TABLE: DONATIONS.FC_DEFAULT_TAG 
--

ALTER TABLE DONATIONS.FC_DEFAULT_TAG ADD CONSTRAINT RefTAG256 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;


-- 
-- TABLE: DONATIONS.FC_DONATION 
--

ALTER TABLE DONATIONS.FC_DONATION ADD CONSTRAINT RefDONATION245 
    FOREIGN KEY (APP_SID, DONATION_ID)
    REFERENCES DONATIONS.DONATION(APP_SID, DONATION_ID)
;

ALTER TABLE DONATIONS.FC_DONATION ADD CONSTRAINT RefFUNDING_COMMITMENT246 
    FOREIGN KEY (APP_SID, FUNDING_COMMITMENT_SID)
    REFERENCES DONATIONS.FUNDING_COMMITMENT(APP_SID, FUNDING_COMMITMENT_SID)
;


-- 
-- TABLE: DONATIONS.FC_TAG 
--

ALTER TABLE DONATIONS.FC_TAG ADD CONSTRAINT RefTAG238 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE DONATIONS.FC_TAG ADD CONSTRAINT RefFUNDING_COMMITMENT239 
    FOREIGN KEY (APP_SID, FUNDING_COMMITMENT_SID)
    REFERENCES DONATIONS.FUNDING_COMMITMENT(APP_SID, FUNDING_COMMITMENT_SID)
;


-- 
-- TABLE: DONATIONS.FC_UPLOAD 
--

ALTER TABLE DONATIONS.FC_UPLOAD ADD CONSTRAINT RefFUNDING_COMMITMENT223 
    FOREIGN KEY (APP_SID, FUNDING_COMMITMENT_SID)
    REFERENCES DONATIONS.FUNDING_COMMITMENT(APP_SID, FUNDING_COMMITMENT_SID)
;


-- 
-- TABLE: DONATIONS.FUNDING_COMMITMENT 
--

ALTER TABLE DONATIONS.FUNDING_COMMITMENT ADD CONSTRAINT RefRECIPIENT199 
    FOREIGN KEY (APP_SID, RECIPIENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID)
;

ALTER TABLE DONATIONS.FUNDING_COMMITMENT ADD CONSTRAINT RefTAG200 
    FOREIGN KEY (APP_SID, CHARITY_BUDGET_TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE DONATIONS.FUNDING_COMMITMENT ADD CONSTRAINT RefDONATION_STATUS221 
    FOREIGN KEY (APP_SID, DONATION_STATUS_SID)
    REFERENCES DONATIONS.DONATION_STATUS(APP_SID, DONATION_STATUS_SID)
;

ALTER TABLE DONATIONS.FUNDING_COMMITMENT ADD CONSTRAINT RefSCHEME225 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;

ALTER TABLE DONATIONS.FUNDING_COMMITMENT ADD CONSTRAINT RefREGION_GROUP227 
    FOREIGN KEY (APP_SID, REGION_GROUP_SID)
    REFERENCES DONATIONS.REGION_GROUP(APP_SID, REGION_GROUP_SID)
;


-- 
-- TABLE: DONATIONS.LETTER_BODY_REGION_GROUP 
--

ALTER TABLE DONATIONS.LETTER_BODY_REGION_GROUP ADD CONSTRAINT RefLETTER_BODY_TEXT93 
    FOREIGN KEY (APP_SID, LETTER_BODY_TEXT_ID, DONATION_STATUS_SID)
    REFERENCES DONATIONS.LETTER_BODY_TEXT(APP_SID, LETTER_BODY_TEXT_ID, DONATION_STATUS_SID)
;

ALTER TABLE DONATIONS.LETTER_BODY_REGION_GROUP ADD CONSTRAINT RefREGION_GROUP94 
    FOREIGN KEY (APP_SID, REGION_GROUP_SID)
    REFERENCES DONATIONS.REGION_GROUP(APP_SID, REGION_GROUP_SID)
;


-- 
-- TABLE: DONATIONS.LETTER_BODY_TEXT 
--

ALTER TABLE DONATIONS.LETTER_BODY_TEXT ADD CONSTRAINT RefDONATION_STATUS95 
    FOREIGN KEY (APP_SID, DONATION_STATUS_SID)
    REFERENCES DONATIONS.DONATION_STATUS(APP_SID, DONATION_STATUS_SID)
;


-- 
-- TABLE: DONATIONS.RECIPIENT 
--

ALTER TABLE DONATIONS.RECIPIENT ADD CONSTRAINT RefRECIPIENT70 
    FOREIGN KEY (APP_SID, PARENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID)
;


-- 
-- TABLE: DONATIONS.RECIPIENT_POSTIT 
--

ALTER TABLE DONATIONS.RECIPIENT_POSTIT ADD CONSTRAINT FK_RCP_RCP_POSTIT 
    FOREIGN KEY (APP_SID, RECIPIENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID)
;


-- 
-- TABLE: DONATIONS.RECIPIENT_TAG 
--

ALTER TABLE DONATIONS.RECIPIENT_TAG ADD CONSTRAINT RefRECIPIENT233 
    FOREIGN KEY (APP_SID, RECIPIENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID)
;

ALTER TABLE DONATIONS.RECIPIENT_TAG ADD CONSTRAINT RefTAG234 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;


-- 
-- TABLE: DONATIONS.RECIPIENT_TAG_GROUP 
--

ALTER TABLE DONATIONS.RECIPIENT_TAG_GROUP ADD CONSTRAINT RefTAG_GROUP235 
    FOREIGN KEY (APP_SID, TAG_GROUP_SID)
    REFERENCES DONATIONS.TAG_GROUP(APP_SID, TAG_GROUP_SID)
;


-- 
-- TABLE: DONATIONS.REGION_GROUP 
--

ALTER TABLE DONATIONS.REGION_GROUP ADD CONSTRAINT RefLETTER_TEMPLATE96 
    FOREIGN KEY (APP_SID, LETTER_TEMPLATE_ID)
    REFERENCES DONATIONS.LETTER_TEMPLATE(APP_SID, LETTER_TEMPLATE_ID)
;


-- 
-- TABLE: DONATIONS.REGION_GROUP_MEMBER 
--

ALTER TABLE DONATIONS.REGION_GROUP_MEMBER ADD CONSTRAINT RefREGION_GROUP59 
    FOREIGN KEY (APP_SID, REGION_GROUP_SID)
    REFERENCES DONATIONS.REGION_GROUP(APP_SID, REGION_GROUP_SID)
;

-- 
-- TABLE: DONATIONS.REGION_GROUP_RECIPIENT 
--

ALTER TABLE DONATIONS.REGION_GROUP_RECIPIENT ADD CONSTRAINT RefRECIPIENT79 
    FOREIGN KEY (APP_SID, RECIPIENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID)
;

ALTER TABLE DONATIONS.REGION_GROUP_RECIPIENT ADD CONSTRAINT RefREGION_GROUP80 
    FOREIGN KEY (APP_SID, REGION_GROUP_SID)
    REFERENCES DONATIONS.REGION_GROUP(APP_SID, REGION_GROUP_SID)
;


-- 
-- TABLE: DONATIONS.SCHEME_DONATION_STATUS 
--

ALTER TABLE DONATIONS.SCHEME_DONATION_STATUS ADD CONSTRAINT RefDONATION_STATUS156 
    FOREIGN KEY (APP_SID, DONATION_STATUS_SID)
    REFERENCES DONATIONS.DONATION_STATUS(APP_SID, DONATION_STATUS_SID)
;

ALTER TABLE DONATIONS.SCHEME_DONATION_STATUS ADD CONSTRAINT RefSCHEME157 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;


-- 
-- TABLE: DONATIONS.SCHEME_FIELD 
--

ALTER TABLE DONATIONS.SCHEME_FIELD ADD CONSTRAINT RefSCHEME125 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;

ALTER TABLE DONATIONS.SCHEME_FIELD ADD CONSTRAINT RefCUSTOM_FIELD126 
    FOREIGN KEY (APP_SID, FIELD_NUM)
    REFERENCES DONATIONS.CUSTOM_FIELD(APP_SID, FIELD_NUM)
;


-- 
-- TABLE: DONATIONS.SCHEME_TAG_GROUP 
--

ALTER TABLE DONATIONS.SCHEME_TAG_GROUP ADD CONSTRAINT RefSCHEME60 
    FOREIGN KEY (APP_SID, SCHEME_SID)
    REFERENCES DONATIONS.SCHEME(APP_SID, SCHEME_SID)
;

ALTER TABLE DONATIONS.SCHEME_TAG_GROUP ADD CONSTRAINT RefTAG_GROUP61 
    FOREIGN KEY (APP_SID, TAG_GROUP_SID)
    REFERENCES DONATIONS.TAG_GROUP(APP_SID, TAG_GROUP_SID)
;


-- 
-- TABLE: DONATIONS.TAG_GROUP_MEMBER 
--

ALTER TABLE DONATIONS.TAG_GROUP_MEMBER ADD CONSTRAINT RefTAG_GROUP62 
    FOREIGN KEY (APP_SID, TAG_GROUP_SID)
    REFERENCES DONATIONS.TAG_GROUP(APP_SID, TAG_GROUP_SID)
;

ALTER TABLE DONATIONS.TAG_GROUP_MEMBER ADD CONSTRAINT RefTAG63 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES DONATIONS.TAG(APP_SID, TAG_ID)
;


-- 
-- TABLE: DONATIONS.TRANSITION 
--

ALTER TABLE DONATIONS.TRANSITION ADD CONSTRAINT RefDONATION_STATUS129 
    FOREIGN KEY (APP_SID, FROM_DONATION_STATUS_SID)
    REFERENCES DONATIONS.DONATION_STATUS(APP_SID, DONATION_STATUS_SID)
;

ALTER TABLE DONATIONS.TRANSITION ADD CONSTRAINT RefDONATION_STATUS130 
    FOREIGN KEY (APP_SID, TO_DONATION_STATUS_SID)
    REFERENCES DONATIONS.DONATION_STATUS(APP_SID, DONATION_STATUS_SID)
;


-- 
-- TABLE: DONATIONS.USER_FIELDSET_FIELD 
--

ALTER TABLE DONATIONS.USER_FIELDSET_FIELD ADD CONSTRAINT RefUSER_FIELDSET101 
    FOREIGN KEY (APP_SID, USER_FIELDSET_ID)
    REFERENCES DONATIONS.USER_FIELDSET(APP_SID, USER_FIELDSET_ID)
;


