
ALTER TABLE DONATIONS.CONSTANT ADD CONSTRAINT RefCUSTOMER150 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE DONATIONS.CUSTOM_FIELD ADD CONSTRAINT RefCUSTOMER123 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE DONATIONS.CUSTOMER_FILTER_FLAG ADD CONSTRAINT RefCUSTOMER143 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefCOUNTRY161 
    FOREIGN KEY (DEFAULT_COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE DONATIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOMER163 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE DONATIONS.CUSTOMER_RECALC ADD CONSTRAINT RefCUSTOMER165 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefCSR_USER134 
    FOREIGN KEY (APP_SID, LAST_STATUS_CHANGED_BY)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE DONATIONS.DONATION ADD CONSTRAINT RefCSR_USER135 
    FOREIGN KEY (APP_SID, ENTERED_BY_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE DONATIONS.DONATION_DOC ADD CONSTRAINT RefFILE_UPLOAD153 
    FOREIGN KEY (DOCUMENT_SID, APP_SID)
    REFERENCES CSR.FILE_UPLOAD(FILE_UPLOAD_SID, APP_SID)
;



ALTER TABLE DONATIONS.DONATION_STATUS ADD CONSTRAINT RefCUSTOMER144 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE DONATIONS.FILTER ADD CONSTRAINT RefCSR_USER116 
    FOREIGN KEY (APP_SID, CSR_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE DONATIONS.FILTER ADD CONSTRAINT RefCUSTOMER118 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE DONATIONS.LETTER_TEMPLATE ADD CONSTRAINT RefCUSTOMER145 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE DONATIONS.RECIPIENT ADD CONSTRAINT RefCOUNTRY65 
    FOREIGN KEY (COUNTRY_CODE)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE DONATIONS.REGION_GROUP_MEMBER ADD CONSTRAINT RefREGION146 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;


ALTER TABLE DONATIONS.TAG ADD CONSTRAINT RefCUSTOMER147 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE DONATIONS.TAG_GROUP ADD CONSTRAINT RefCUSTOMER148 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE DONATIONS.USER_FIELDSET ADD CONSTRAINT RefCSR_USER136 
    FOREIGN KEY (APP_SID, CSR_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;



ALTER TABLE DONATIONS.REGION_FILTER_TAG_GROUP ADD CONSTRAINT RefTAG_GROUP253 
    FOREIGN KEY (APP_SID,REGION_TAG_GROUP_ID)
    REFERENCES CSR.TAG_GROUP(APP_SID, TAG_GROUP_ID)
;
