 ALTER TABLE CSR.ALERT_FRAME_BODY ADD CONSTRAINT FK_ALERT_FRM_BDY_TRAN_SET 
    FOREIGN KEY (APP_SID, LANG)
    REFERENCES ASPEN2.TRANSLATION_SET(APPLICATION_SID, LANG)
;

ALTER TABLE CSR.ALERT_TEMPLATE_BODY ADD CONSTRAINT FK_ALT_TPL_BDY_BDY_TRAN_SET 
    FOREIGN KEY (APP_SID, LANG)
    REFERENCES ASPEN2.TRANSLATION_SET(APPLICATION_SID, LANG)
;

ALTER TABLE CSR.CHAIN_TPL_DELEGATION ADD CONSTRAINT REFCH_TPL_DELEG_QUE_TYPE 
    FOREIGN KEY (APP_SID, TPL_DELEGATION_SID)
    REFERENCES CHAIN.QUESTIONNAIRE_TYPE(APP_SID, QUESTIONNAIRE_TYPE_ID)  DEFERRABLE INITIALLY DEFERRED
;
 
ALTER TABLE csr.compliance_item_rollout ADD CONSTRAINT fk_cir_pcr
	FOREIGN KEY (country, region)
	REFERENCES postcode.region (country, region)
;

ALTER TABLE csr.compliance_item_rollout ADD CONSTRAINT fk_cir_pcc
	FOREIGN KEY (country)
	REFERENCES postcode.country (country)
;

ALTER TABLE CSR.COMPLIANCE_REGION_MAP ADD CONSTRAINT FK_COM_REG_MAP_P_REG
	FOREIGN KEY (COUNTRY, REGION)
	REFERENCES POSTCODE.REGION(COUNTRY, REGION)
;
	
ALTER TABLE csr.country_group_country ADD CONSTRAINT fk_cgc_pc
	FOREIGN KEY (country_id)
	REFERENCES postcode.country (country)
;
 
ALTER TABLE CSR.CUSTOM_LOCATION ADD CONSTRAINT RefCOUNTRY2087 
    FOREIGN KEY (COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE CSR.DOC_FOLDER ADD CONSTRAINT FK_DOC_FOLDER_COMPANY 
	FOREIGN KEY (APP_SID, COMPANY_SID) 
	REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE CSR.DELEGATION_REGION_DESCRIPTION ADD CONSTRAINT FK_DELEG_REG_DESC_ASPEN2_TS
    FOREIGN KEY (APP_SID, LANG)
    REFERENCES ASPEN2.TRANSLATION_SET (APPLICATION_SID, LANG)
;

ALTER TABLE CSR.FACTOR ADD CONSTRAINT RefCOUNTRY1718 
    FOREIGN KEY (GEO_COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE CSR.FACTOR ADD CONSTRAINT RefREGION1719 
    FOREIGN KEY (GEO_COUNTRY, GEO_REGION)
    REFERENCES POSTCODE.REGION(COUNTRY, REGION)
;

 
ALTER TABLE CSR.ISSUE_ACTION ADD CONSTRAINT RefTASK1698 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

  
ALTER TABLE CSR.LOCATION ADD CONSTRAINT RefCOUNTRY2095 
    FOREIGN KEY (COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

 
ALTER TABLE CSR.MAP_SHPFILE ADD CONSTRAINT RefCOUNTRY1675 
    FOREIGN KEY (GEO_COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

 
ALTER TABLE CSR.REGION ADD CONSTRAINT RefREGION1206 
    FOREIGN KEY (GEO_COUNTRY, GEO_REGION)
    REFERENCES POSTCODE.REGION(COUNTRY, REGION)
;

ALTER TABLE CSR.REGION ADD CONSTRAINT RefCOUNTRY1207 
    FOREIGN KEY (GEO_COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE CSR.REGION ADD CONSTRAINT RefCITY1208 
    FOREIGN KEY (GEO_CITY_ID)
    REFERENCES POSTCODE.CITY(CITY_ID)
;


ALTER TABLE CSR.REGION_GROUP_REGION ADD CONSTRAINT FK_REG_GRP_REG_P_REG
	FOREIGN KEY (COUNTRY, REGION)
	REFERENCES POSTCODE.REGION(COUNTRY, REGION)
;

 
ALTER TABLE CSR.STD_FACTOR ADD CONSTRAINT RefREGION1221 
    FOREIGN KEY (GEO_COUNTRY, GEO_REGION)
    REFERENCES POSTCODE.REGION(COUNTRY, REGION)
;

ALTER TABLE CSR.POSTCODE_EGRID ADD CONSTRAINT FK_POSTCODE_POSTCODE_EGRID
    FOREIGN KEY (COUNTRY,POSTCODE)
    REFERENCES POSTCODE.POSTCODE(COUNTRY,POSTCODE);
 
ALTER TABLE CSR.SUPPLIER ADD CONSTRAINT REFSUP_CHAIN_COMPANY 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE CSR.ALL_PROPERTY ADD CONSTRAINT FK_PROP_COMPANY
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID);

ALTER TABLE CSR.QS_FILTER_CONDITION ADD CONSTRAINT FK_QS_FIL_COND_CHAIN_FIL
    FOREIGN KEY (APP_SID, FILTER_ID)
    REFERENCES CHAIN.FILTER(APP_SID, FILTER_ID);

ALTER TABLE CSR.SUPPLIER ADD CONSTRAINT FK_SUPPLIER_RECIPIENT
    FOREIGN KEY (APP_SID, RECIPIENT_SID)
    REFERENCES DONATIONS.RECIPIENT(APP_SID, RECIPIENT_SID);

ALTER TABLE CSR.CMS_TAB_ALERT_TYPE ADD CONSTRAINT FK_CMS_TAB_TAB_ALERT_TYPE
    FOREIGN KEY (APP_SID, TAB_SID)
    REFERENCES CMS.TAB(APP_SID, TAB_SID) ON DELETE CASCADE;

ALTER TABLE CSR.LOGISTICS_TAB_MODE ADD CONSTRAINT FK_TAB_LOG_TAB_MODE 
    FOREIGN KEY (APP_SID, TAB_SID)
    REFERENCES CMS.TAB(APP_SID, TAB_SID) ON DELETE CASCADE;


ALTER TABLE CSR.IND_DESCRIPTION ADD CONSTRAINT FK_IND_DESCRIPTION_ASPEN2_TS
	FOREIGN KEY (APP_SID, LANG)
	REFERENCES ASPEN2.TRANSLATION_SET (APPLICATION_SID, LANG)
;
	
ALTER TABLE CSR.REGION_DESCRIPTION ADD CONSTRAINT FK_REGION_DESC_ASPEN2_TS
	FOREIGN KEY (APP_SID, LANG)
	REFERENCES ASPEN2.TRANSLATION_SET (APPLICATION_SID, LANG)
;

ALTER TABLE CSR.DATAVIEW_IND_DESCRIPTION ADD CONSTRAINT FK_DV_IND_DESC_ASPEN2_TS
	FOREIGN KEY (APP_SID, LANG)
	REFERENCES ASPEN2.TRANSLATION_SET (APPLICATION_SID, LANG)
;

ALTER TABLE CSR.DELEGATION_IND_DESCRIPTION ADD CONSTRAINT FK_DELEG_IND_DESC_ASPEN2_TS
	FOREIGN KEY (APP_SID, LANG)
	REFERENCES ASPEN2.TRANSLATION_SET (APPLICATION_SID, LANG)
;

ALTER TABLE CSR.IND_SEL_GROUP_MEMBER_DESC ADD CONSTRAINT FK_IND_SEL_GRP_MEM_ASPEN2_TS
	FOREIGN KEY (APP_SID, LANG)
	REFERENCES ASPEN2.TRANSLATION_SET (APPLICATION_SID, LANG)
;


ALTER TABLE csr.deleg_meta_role_ind_selection ADD CONSTRAINT FK_DELEG_META_ROLE_IND_ASPN2TS
	FOREIGN KEY (app_sid, lang)
	REFERENCES aspen2.translation_set
;

alter table csr.cms_alert_helper add constraint fk_cms_alert_helper_cms_tab
foreign key (app_sid, tab_sid) references cms.tab (app_sid, tab_sid);

alter table csr.cms_alert_type add constraint fk_cms_alert_type_cms_tab
foreign key (app_sid, tab_sid) references cms.tab (app_sid, tab_sid);

ALTER TABLE CSR.INBOUND_ISSUE_ACCOUNT ADD CONSTRAINT FK_ACCOUNT_INB_ISS_ACC
	FOREIGN KEY (ACCOUNT_SID)
    REFERENCES MAIL.ACCOUNT(ACCOUNT_SID) ON DELETE CASCADE;

ALTER TABLE CSR.INBOUND_CMS_ACCOUNT ADD CONSTRAINT FK_ACCOUNT_INBOUND_CMS_ACCOUNT
	FOREIGN KEY (ACCOUNT_SID)
    REFERENCES MAIL.ACCOUNT(ACCOUNT_SID) ON DELETE CASCADE;

ALTER TABLE CSR.INBOUND_CMS_ACCOUNT ADD CONSTRAINT FK_TAB_INBOUND_CMS_ACCOUNT
    FOREIGN KEY (APP_SID, TAB_SID)
    REFERENCES CMS.TAB(APP_SID, TAB_SID) ON DELETE CASCADE;

ALTER TABLE CSR.INCIDENT_TYPE ADD CONSTRAINT FK_INC_TYPE_CMS_TAB
    FOREIGN KEY (APP_SID, TAB_SID)
    REFERENCES CMS.TAB(APP_SID, TAB_SID) ON DELETE CASCADE;
	
ALTER TABLE CSR.INCIDENT_TYPE ADD CONSTRAINT FK_INC_TYPE_CMS_FORM
	FOREIGN KEY (APP_SID, MOBILE_FORM_SID) 
	REFERENCES CMS.FORM (APP_SID, FORM_SID);

ALTER TABLE CSR.FLOW_TRANSITION_ALERT_CMS_COL ADD
CONSTRAINT FK_FLOW_CMS_COL FOREIGN KEY (APP_SID, COLUMN_SID) REFERENCES CMS.TAB_COLUMN (APP_SID, COLUMN_SID);

ALTER TABLE CSR.FLOW_STATE_CMS_COL ADD
CONSTRAINT FK_FLOW_STATE_CMS_COL FOREIGN KEY (APP_SID, COLUMN_SID) REFERENCES CMS.TAB_COLUMN (APP_SID, COLUMN_SID);

ALTER TABLE CSR.FLOW_STATE_TRANSITION_CMS_COL ADD
CONSTRAINT FK_FLOW_STATE_TRANS_CMS_COL FOREIGN KEY (APP_SID, COLUMN_SID) REFERENCES CMS.TAB_COLUMN (APP_SID, COLUMN_SID);

ALTER TABLE csr.flow_item_generated_alert
ADD CONSTRAINT FK_FL_ITM_GN_ALRT_TO_COL_SID FOREIGN KEY (app_sid, to_column_sid) REFERENCES cms.tab_column(app_sid, column_sid);

ALTER TABLE CSR.EXPORT_FEED_CMS_FORM ADD CONSTRAINT FK_EXP_CMS_FORM_TAB
    FOREIGN KEY (APP_SID, FORM_SID) REFERENCES CMS.FORM (APP_SID, FORM_SID);
	
ALTER TABLE csr.teamroom_type ADD CONSTRAINT FK_TEAMROOM_TYPE_USER_GROUP 
	 FOREIGN KEY (DEFAULT_NEW_USER_GROUP_SID)
	 REFERENCES SECURITY.GROUP_TABLE(SID_ID);

ALTER TABLE CSR.QS_FILTER_CONDITION_GENERAL ADD CONSTRAINT FK_QS_FIL_COND_GEN_CHAIN_FIL 
	FOREIGN KEY (APP_SID, FILTER_ID) 
	REFERENCES CHAIN.FILTER(APP_SID, FILTER_ID);

ALTER TABLE csr.PROPERTY_OPTIONS ADD 
  (CONSTRAINT fk_fund_company_type_id FOREIGN KEY (app_sid, fund_company_type_id) REFERENCES chain.company_type(app_sid, company_type_id));
	
ALTER TABLE CSR.SUPPLIER_SURVEY_RESPONSE ADD CONSTRAINT FK_SUPPL_SURV_RESP_COMPONENT
	FOREIGN KEY (APP_SID, COMPONENT_ID)
	REFERENCES CHAIN.COMPONENT(APP_SID, COMPONENT_ID);

ALTER TABLE CSR.PLUGIN ADD CONSTRAINT fk_plugin_cms_tab 
	FOREIGN KEY (app_sid, tab_sid) 
	REFERENCES cms.tab (app_sid, tab_sid) ON DELETE CASCADE;

ALTER TABLE CSR.PLUGIN ADD CONSTRAINT fk_plugin_cms_form
	FOREIGN KEY (app_sid, form_sid) 
	REFERENCES cms.form (app_sid, form_sid) ON DELETE CASCADE;

ALTER TABLE CSR.PLUGIN ADD CONSTRAINT FK_PLUGIN_CHAIN_CARD_GROUP 
	FOREIGN KEY (CARD_GROUP_ID) 
	REFERENCES CHAIN.CARD_GROUP (CARD_GROUP_ID);
	
ALTER TABLE csr.internal_audit_type ADD CONSTRAINT fk_int_audit_type_cms_tab 
	FOREIGN KEY (app_sid, tab_sid) 
	REFERENCES cms.tab (app_sid, tab_sid);
	
ALTER TABLE csr.internal_audit_type ADD CONSTRAINT fk_int_audit_type_cms_form
	FOREIGN KEY (app_sid, form_sid) 
	REFERENCES cms.form (app_sid, form_sid);
	
ALTER TABLE csr.delegation_grid ADD CONSTRAINT fk_dele_grid_cms_form
	FOREIGN KEY (app_sid, form_sid) 
	REFERENCES cms.form (app_sid, form_sid);

ALTER TABLE csr.issue_involvement ADD CONSTRAINT fk_issue_involvement_company
	FOREIGN KEY (app_sid, company_sid)
	REFERENCES csr.supplier (app_sid, company_sid);
	
ALTER TABLE csr.tpl_report_tag_dataview ADD CONSTRAINT fk_tpl_rprt_tag_dv_saved_fltr 
	FOREIGN KEY (app_sid, saved_filter_sid)
	REFERENCES chain.saved_filter (app_sid, saved_filter_sid);

ALTER TABLE csr.tpl_report_tag_logging_form ADD CONSTRAINT fk_tpl_rprt_tag_lf_saved_fltr 
	FOREIGN KEY (app_sid, saved_filter_sid)
	REFERENCES chain.saved_filter (app_sid, saved_filter_sid);

ALTER TABLE csr.tpl_report_tag_qchart ADD CONSTRAINT fk_tpl_rprt_tag_qc_saved_fltr 
	FOREIGN KEY (app_sid, saved_filter_sid)
	REFERENCES chain.saved_filter (app_sid, saved_filter_sid);

ALTER TABLE CSR.FLOW_STATE_ALERT_ROLE ADD CONSTRAINT FK_FSAR_GROUP FOREIGN KEY (GROUP_SID) REFERENCES SECURITY.GROUP_TABLE(SID_ID);
ALTER TABLE CSR.FLOW_STATE_ROLE ADD CONSTRAINT FK_FSR_GROUP FOREIGN KEY (GROUP_SID) REFERENCES SECURITY.GROUP_TABLE(SID_ID);
ALTER TABLE CSR.FLOW_STATE_ROLE_CAPABILITY ADD CONSTRAINT FK_FSRC_GROUP FOREIGN KEY (GROUP_SID) REFERENCES SECURITY.GROUP_TABLE(SID_ID);
ALTER TABLE CSR.FLOW_STATE_TRANSITION_ROLE ADD CONSTRAINT FK_FSTR_GROUP FOREIGN KEY (GROUP_SID) REFERENCES SECURITY.GROUP_TABLE(SID_ID);
ALTER TABLE CSR.FLOW_TRANSITION_ALERT_ROLE ADD CONSTRAINT FK_FTAR_GROUP FOREIGN KEY (GROUP_SID) REFERENCES SECURITY.GROUP_TABLE(SID_ID);

ALTER TABLE CSR.FLOW_STATE_TRANSITION ADD CONSTRAINT FK_FST_GROUP FOREIGN KEY (GROUP_SID_CAN_SET) REFERENCES SECURITY.GROUP_TABLE(SID_ID);

ALTER TABLE csr.plugin 
ADD CONSTRAINT fk_plugin_saved_filter 
FOREIGN KEY (app_sid, saved_filter_sid) 
REFERENCES chain.saved_filter(app_sid, saved_filter_sid);

ALTER TABLE csr.plugin 
ADD CONSTRAINT fk_plugin_pre_filter 
FOREIGN KEY (app_sid, pre_filter_sid) 
REFERENCES chain.saved_filter(app_sid, saved_filter_sid);

ALTER TABLE CSR.AUTO_IMP_MAILBOX ADD CONSTRAINT FK_AUTO_IMP_MAILBOX_BOX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_MAIL_SENDER_FILTER ADD CONSTRAINT FK_AUTO_IMP_MAIL_SNDR_FLTR_BX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_MAIL_SUBJECT_FILTER ADD CONSTRAINT FK_AUTO_IMP_MAIL_SBJCT_FLTR_BX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_MAIL_ATTACH_FILTER ADD CONSTRAINT FK_AUTO_IMP_MAIL_ATCH_FLTR_BOX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_MAIL ADD CONSTRAINT FK_AUTO_IMP_MAIL_BOX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_MAIL_FILE ADD CONSTRAINT FK_AUTO_IMP_MAIL_FILE_BOX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_MAIL_MSG ADD CONSTRAINT FK_AUTO_IMP_MAIL_MSG_BOX
	FOREIGN KEY (MAILBOX_SID)
	REFERENCES MAIL.MAILBOX (MAILBOX_SID)
;

ALTER TABLE CSR.AUTO_IMP_PRODUCT_SETTINGS ADD CONSTRAINT FK_AUTO_IMP_PROD_CMS_TAB
	FOREIGN KEY (APP_SID, TAB_SID)
	REFERENCES CMS.TAB(APP_SID, TAB_SID);

ALTER TABLE csr.tpl_report_variant ADD CONSTRAINT fk_tpl_rep_variant_lang
	FOREIGN KEY (language_code)
	REFERENCES aspen2.lang(lang)
;

ALTER TABLE csr.issue_custom_field ADD CONSTRAINT fk_iss_cus_field_group
	FOREIGN KEY (restrict_to_group_sid)
	REFERENCES security.group_table (sid_id)
;