CREATE OR REPLACE PACKAGE CSR.null_pkg AS

-- Note that RESTRICT_REFERENCES seems to operate on the last defined 
-- overload of a function, and you do need it to appear once per overload
FUNCTION eq(
	in_a	IN 	VARCHAR2,
	in_b	IN	VARCHAR2
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(eq, RNDS, WNDS, RNPS, WNPS);

FUNCTION eq(
	in_a	IN 	CLOB,
	in_b	IN	CLOB
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(eq, RNDS, WNDS, RNPS, WNPS);

FUNCTION eq(
	in_a	IN	DATE,
	in_b	IN	DATE
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(eq, RNDS, WNDS, RNPS, WNPS);

FUNCTION eq(
	in_a	IN	NUMBER,
	in_b	IN	NUMBER
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(eq, RNDS, WNDS, RNPS, WNPS);

FUNCTION ne(
	in_a	IN	VARCHAR2,
	in_b	IN	VARCHAR2
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(ne, RNDS, WNDS, RNPS, WNPS);

FUNCTION ne(
	in_a	IN	CLOB,
	in_b	IN	CLOB
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(ne, RNDS, WNDS, RNPS, WNPS);

FUNCTION ne(
	in_a	IN	DATE,
	in_b	IN	DATE
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(ne, RNDS, WNDS, RNPS, WNPS);

FUNCTION ne(
	in_a	IN	NUMBER,
	in_b	IN	NUMBER
) RETURN BOOLEAN DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(ne, RNDS, WNDS, RNPS, WNPS);

FUNCTION btn(
	in_v	IN	BOOLEAN
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(btn, RNDS, WNDS, RNPS, WNPS);

FUNCTION seq(
	in_a	IN	VARCHAR2,
	in_b	IN	VARCHAR2
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(seq, RNDS, WNDS, RNPS, WNPS);

FUNCTION seq(
	in_a	IN	CLOB,
	in_b	IN	CLOB
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(seq, RNDS, WNDS, RNPS, WNPS);

FUNCTION seq(
	in_a	IN	DATE,
	in_b	IN	DATE
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(seq, RNDS, WNDS, RNPS, WNPS);

FUNCTION seq(
	in_a	IN	NUMBER,
	in_b	IN	NUMBER
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(seq, RNDS, WNDS, RNPS, WNPS);

FUNCTION sne(
	in_a	IN	VARCHAR2,
	in_b	IN	VARCHAR2
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(sne, RNDS, WNDS, RNPS, WNPS);

FUNCTION sne(
	in_a	IN	CLOB,
	in_b	IN	CLOB
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(sne, RNDS, WNDS, RNPS, WNPS);

FUNCTION sne(
	in_a	IN	DATE,
	in_b	IN	DATE
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(sne, RNDS, WNDS, RNPS, WNPS);

FUNCTION sne(
	in_a	IN	NUMBER,
	in_b	IN	NUMBER
) RETURN BINARY_INTEGER DETERMINISTIC;
PRAGMA RESTRICT_REFERENCES(sne, RNDS, WNDS, RNPS, WNPS);

END;
/
