

-- 
-- TABLE: PRODUCT_IMPORT_DATA 
--

CREATE TABLE PRODUCT_IMPORT_DATA(
    PRODUCT_ID           NUMBER(10, 0)     NOT NULL,
    ITEM_CODE            VARCHAR2(256)     NOT NULL,
    PRODUCT              VARCHAR2(1024)    NOT NULL,
    BUSINESS_CENTRE      VARCHAR2(256),
    BUSINESS_CENTRE_2    VARCHAR2(256),
    SUPPLIER             VARCHAR2(256)     NOT NULL,
    PRODUCT_TYPE         VARCHAR2(256),
    BRAND                VARCHAR2(256),
    WRME                 NUMBER(10, 2),
    SPLIT_WRME           NUMBER(10, 2),
    CONSTRAINT PRODUCT_IMPORT_DATA_PK PRIMARY KEY (PRODUCT_ID)
    USING INDEX
TABLESPACE INDX
)
;



-- 
-- TABLE: PRODUCT_IMPORT_MAPPING 
--

CREATE TABLE PRODUCT_IMPORT_MAPPING(
    IMPORT_PRODUCT_ID    NUMBER(10, 0)    NOT NULL,
    NEW_PRODUCT_ID       NUMBER(10, 0)    NOT NULL,
    DTM                  DATE             NOT NULL
)
;





-- 
-- TABLE: WOOD_IMPORT_DATA 
--

CREATE TABLE WOOD_IMPORT_DATA(
    PRODUCT_ID           NUMBER(10, 0)     NOT NULL,
    WOOD_NUMBER          NUMBER(10, 0)     NOT NULL,
    PART_NAME            VARCHAR2(1024)    NOT NULL,
    QTY                  NUMBER(10, 2)     NOT NULL,
    WEIGHT               NUMBER(10, 2)     NOT NULL,
    WOOD_TYPE            VARCHAR2(256)     NOT NULL,
    COUNTRY_OF_ORIGIN    VARCHAR2(256)     NOT NULL,
    CERT_TYPE            VARCHAR2(3)       NOT NULL,
    CERT_SCHEME          VARCHAR2(256)     NOT NULL
)
;



-- 
-- TABLE: PRODUCT_IMPORT_DATA 
--

ALTER TABLE PRODUCT_IMPORT_DATA ADD CONSTRAINT RefALL_PRODUCT464 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES ALL_PRODUCT(PRODUCT_ID)
;




-- 
-- TABLE: WOOD_IMPORT_DATA 
--

ALTER TABLE WOOD_IMPORT_DATA ADD CONSTRAINT RefALL_PRODUCT341 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES ALL_PRODUCT(PRODUCT_ID)
;


