-- csr tables
grant select,insert on csr.accuracy_type to csrimp;
grant insert on csr.accuracy_type_option to csrimp;
grant insert,update on csr.aggregate_ind_group to csrimp;
grant insert on csr.aggregate_ind_group_member to csrimp;
grant insert on csr.aggregate_ind_group_audit_log to csrimp;
grant insert on csr.alert to csrimp;
grant insert on csr.alert_bounce to csrimp;
grant insert on csr.alert_frame to csrimp;
grant insert on csr.alert_frame_body to csrimp;
grant insert on csr.alert_template to csrimp;
grant insert on csr.alert_template_body to csrimp;
grant insert on csr.all_meter to csrimp;
grant insert on csr.app_lock to csrimp;
grant insert on csr.approval_dashboard to csrimp;
grant insert on csr.approval_dashboard_alert_type to csrimp;
grant insert on csr.approval_dashboard_ind to csrimp;
grant insert on csr.approval_dashboard_instance to csrimp;
grant insert on csr.approval_dashboard_region to csrimp;
grant insert on csr.approval_dashboard_tab to csrimp;
grant insert on csr.approval_dashboard_tpl_tag to csrimp;
grant insert on csr.approval_dashboard_val to csrimp;
grant insert on csr.approval_note_portlet_note to csrimp;
grant select,insert,update on csr.approval_step to csrimp;
grant insert on csr.approval_step_ind to csrimp;
grant insert on csr.approval_step_region to csrimp;
grant select,insert on csr.approval_step_sheet to csrimp;
grant insert on csr.approval_step_role to csrimp;
grant insert on csr.approval_step_sheet_log to csrimp;
grant insert on csr.approval_step_user to csrimp;
grant select,insert,update on csr.attachment to csrimp;
grant select,insert on csr.attachment_history to csrimp;
grant insert on csr.audit_alert to csrimp;
grant insert on csr.audit_closure_type to csrimp;
grant insert on csr.audit_type_closure_type to csrimp;
grant insert on csr.audit_log to csrimp;
grant insert on csr.audit_non_compliance to csrimp;
grant insert on csr.audit_type_non_comp_default to csrimp;
grant insert on csr.audit_user_cover to csrimp;
grant insert on csr.audit_type_expiry_alert_role to csrimp;
grant insert on csr.audit_type_tab to csrimp;
grant insert on csr.audit_type_header to csrimp;
grant insert on csr.audit_type_flow_inv_type to csrimp;
grant insert on csr.autocreate_user to csrimp;
grant insert on csr.batch_job_approval_dash_vals to csrimp;
grant select,insert on csr.calc_dependency to csrimp;
grant insert on csr.calc_tag_dependency to csrimp;
grant insert on csr.calc_baseline_config_dependency to csrimp;
grant insert on csr.cms_alert_type to csrimp;
grant insert on csr.cms_alert_helper to csrimp;
grant insert on csr.cms_tab_alert_type to csrimp;
grant insert on csr.correspondent to csrimp;
grant insert on csr.current_supplier_score to csrimp;
grant select,insert,update on csr.csr_user to csrimp;
grant select, insert, update on csr.cookie_policy_consent to csrimp;
grant select on csr.cookie_policy_consent_id_seq to csrimp;
grant select,insert,update on csr.customer to csrimp;
grant select,insert on csr.customer_alert_type to csrimp;
grant insert on csr.customer_alert_type_param to csrimp;
grant insert on csr.customer_portlet to csrimp;
grant insert on csr.customer_help_lang to csrimp;
grant insert on csr.customer_region_type to csrimp;
grant insert on csr.dashboard to csrimp;
grant insert on csr.dashboard_item to csrimp;
grant insert on csr.data_bucket to csrimp;
grant select, insert, update on csr.dataview to csrimp;
grant insert on csr.dataview_arbitrary_period TO csrimp;
grant insert on csr.dataview_arbitrary_period_hist TO csrimp;
grant select,insert,delete on csr.dataview_ind_member to csrimp;
grant select,insert,delete on csr.dataview_ind_description to csrimp;
grant select,insert,delete on csr.dataview_region_description to csrimp;
grant select,insert,delete on csr.dataview_region_member to csrimp;
grant insert on csr.dataview_scenario_run to csrimp;
grant insert on csr.dataview_zone to csrimp;
grant insert on csr.dataview_trend to csrimp;
grant insert on csr.dataview_history to csrimp;
grant insert on csr.deleg_grid_variance to csrimp;
grant update,select on csr.deleg_plan to csrimp;
grant insert on csr.deleg_plan to csrimp;
grant insert,delete,select on csr.deleg_plan_applied to csrimp;
grant insert,delete,select on csr.deleg_plan_col to csrimp;
grant insert,delete,select on csr.deleg_plan_col_deleg to csrimp;
grant insert,delete,select on csr.deleg_plan_col_survey to csrimp;
grant insert on csr.deleg_plan_date_schedule to csrimp;
grant insert,delete,select on csr.deleg_plan_deleg_region to csrimp;
grant insert,delete,select on csr.deleg_plan_deleg_region_deleg to csrimp;
grant insert,delete,select on csr.deleg_plan_region to csrimp;
grant insert,delete,select on csr.deleg_plan_role to csrimp;
grant insert on csr.deleg_plan_survey_region to csrimp;
grant select,insert,update on csr.delegation to csrimp;
grant select,insert,update on csr.delegation_description to csrimp;
grant insert on csr.delegation_comment to csrimp;
grant insert on csr.delegation_date_schedule to csrimp;
grant select,insert,update on csr.delegation_grid to csrimp;
grant select,update,insert on csr.delegation_ind to csrimp;
grant select,insert,update,delete on csr.delegation_ind_description to csrimp;
grant insert,select on csr.delegation_grid_aggregate_ind to csrimp;
grant insert,select on csr.delegation_ind_cond to csrimp;
grant insert,select on csr.delegation_ind_cond_action to csrimp;
grant select,insert,update,delete on csr.deleg_ind_form_expr to csrimp;
grant select,insert on csr.deleg_ind_group to csrimp;
grant select,insert on csr.deleg_ind_group_member to csrimp;
grant insert,select on csr.delegation_ind_tag to csrimp;
grant insert,select on csr.delegation_ind_tag_list to csrimp;
grant insert on csr.deleg_meta_role_ind_selection to csrimp;
grant insert on csr.delegation_plugin to csrimp;
grant select, insert, update, delete on csr.delegation_region to csrimp;
grant select, insert, update, delete on csr.delegation_region_description to csrimp;
grant insert on csr.delegation_tag to csrimp;
grant insert,select on csr.delegation_role to csrimp;
grant select,insert on csr.delegation_user to csrimp;
grant insert on csr.delegation_user_cover to csrimp;
grant insert on csr.doc to csrimp;
grant insert on csr.doc_current to csrimp;
grant insert on csr.doc_data to csrimp;
grant insert on csr.doc_download to csrimp;
grant select, insert, update on csr.doc_folder to csrimp;
grant insert on csr.doc_folder_subscription to csrimp;
grant insert on csr.doc_library to csrimp;
grant insert on csr.doc_notification to csrimp;
grant insert on csr.doc_subscription to csrimp;
grant insert on csr.doc_version to csrimp;
grant insert, update on csr.doc_folder_name_translation to csrimp;
grant insert on csr.event to csrimp;
grant insert on csr.excel_export_options to csrimp;
grant insert on csr.excel_export_options_tag_group to csrimp;
grant select,insert on csr.factor to csrimp;
grant insert on csr.factor_history to csrimp;
grant insert on csr.file_upload to csrimp;
grant insert, update, select on csr.flow to csrimp;
grant insert on csr.flow_alert_type to csrimp;
grant insert, update, select on csr.flow_item to csrimp;
grant insert, update, select on csr.flow_item_region to csrimp;
grant insert on csr.flow_item_involvement to csrimp;
grant select on csr.flow_capability to csrimp;
grant select on csr.flow_item_gen_alert_id_seq to csrimp;
grant insert on csr.flow_item_generated_alert to csrimp;
grant insert on csr.flow_involvement_cover to csrimp;
grant insert on csr.flow_involvement_type to csrimp;
grant insert on csr.flow_inv_type_alert_class to csrimp;
grant insert on csr.flow_state to csrimp;
grant insert on csr.flow_state_log to csrimp;
grant insert on csr.flow_state_log_file to csrimp;
grant insert on csr.flow_state_role to csrimp;
grant insert on csr.flow_state_cms_col to csrimp;
grant insert on csr.flow_state_group to csrimp;
grant insert on csr.flow_state_group_member to csrimp;
grant insert on csr.flow_state_involvement to csrimp;
grant insert on csr.flow_state_role_capability to csrimp;
grant insert on csr.flow_state_survey_tag to csrimp;
grant insert on csr.flow_state_trans_helper to csrimp;
grant insert on csr.flow_state_transition to csrimp;
grant insert on csr.flow_state_transition_role to csrimp;
grant insert on csr.flow_state_transition_cms_col to csrimp;
grant insert on csr.flow_state_transition_inv to csrimp;
grant insert on csr.flow_transition_alert to csrimp;
grant insert on csr.flow_transition_alert_cms_col to csrimp;
grant insert on csr.flow_transition_alert_role to csrimp;
grant insert on csr.flow_transition_alert_cc_role to csrimp;
grant insert on csr.flow_transition_alert_user to csrimp;
grant insert on csr.flow_transition_alert_cc_user to csrimp;
grant insert on csr.flow_transition_alert_inv to csrimp;
grant insert on csr.customer_flow_alert_class to csrimp;
grant insert on csr.form to csrimp;
grant insert on csr.form_allocation to csrimp;
grant insert on csr.form_allocation_item to csrimp;
grant insert on csr.form_allocation_user to csrimp;
grant insert on csr.form_comment to csrimp;
grant insert on csr.form_ind_member to csrimp;
grant insert on csr.form_region_member to csrimp;
grant select,insert on csr.file_upload to csrimp;
grant select,insert,update,delete on csr.form_expr to csrimp;
grant select on csr.form to csrimp;
grant select on csr.form_allocation to csrimp;
grant insert on csr.group_user_cover to csrimp;
grant select on csr.help_lang to csrimp;
grant insert on csr.hide_portlet to csrimp;
grant insert on csr.img_chart to csrimp;
grant insert,delete,select on csr.img_chart_ind to csrimp;
grant select,insert on csr.imp_conflict to csrimp;
grant select,insert on csr.imp_conflict_val to csrimp;
grant select,insert on csr.imp_ind to csrimp;
grant select,insert on csr.imp_measure to csrimp;
grant select,insert on csr.imp_region to csrimp;
grant select,insert on csr.imp_session to csrimp;
grant select,insert,update on csr.imp_val to csrimp;
grant insert on csr.imp_vocab to csrimp;
grant insert on csr.incident_type to csrimp;
grant select,insert,delete on csr.ind_start_point to csrimp;
grant select,insert,update on csr.ind to csrimp;
grant select,insert,update,delete on csr.ind_description to csrimp;
grant select,insert on csr.ind_flag to csrimp;
grant select on csr.ind_selection_group to csrimp;
grant select on csr.ind_selection_group_member to csrimp;
grant insert on csr.ind_sel_group_member_desc to csrimp;
grant insert on csr.ind_selection_group to csrimp;
grant insert on csr.ind_selection_group_member to csrimp;
grant insert,delete on csr.ind_tag to csrimp;
grant insert,select,update on csr.ind_validation_rule to csrimp;
grant insert,update on csr.internal_audit to csrimp;
grant insert on csr.internal_audit_file to csrimp;
grant insert on csr.internal_audit_file_data to csrimp;
grant insert on csr.internal_audit_postit to csrimp;
grant insert on csr.internal_audit_type to csrimp;
grant insert on csr.internal_audit_type_report to csrimp;
grant insert on csr.ia_type_report_group to csrimp;
grant insert on csr.internal_audit_type_carry_fwd to csrimp;
grant insert on csr.internal_audit_type_tag_group to csrimp;
grant insert on csr.internal_audit_tag to csrimp;
grant insert on csr.flow_state_audit_ind to csrimp;
grant insert on csr.internal_audit_type_group to csrimp;
grant insert, update on csr.issue to csrimp;
grant insert on csr.issue_action to csrimp;
grant insert on csr.issue_action_log to csrimp;
grant insert on csr.issue_compliance_region to csrimp;
grant insert on csr.issue_custom_field to csrimp;
grant insert on csr.issue_custom_field_opt_sel to csrimp;
grant insert on csr.issue_custom_field_option to csrimp;
grant insert on csr.issue_custom_field_str_val to csrimp;
grant insert on csr.issue_due_source to csrimp;
grant insert on csr.issue_log to csrimp;
grant insert on csr.issue_log_file to csrimp;
grant insert on csr.issue_log_read to csrimp;
grant insert on csr.issue_meter to csrimp;
grant insert on csr.issue_meter_alarm to csrimp;
grant insert on csr.issue_meter_data_source to csrimp;
grant insert on csr.issue_meter_raw_data to csrimp;
grant insert on csr.issue_non_compliance to csrimp;
grant insert on csr.issue_pending_val to csrimp;
grant insert on csr.issue_priority to csrimp;
grant insert on csr.issue_scheduled_task to csrimp;
grant insert on csr.issue_sheet_value to csrimp;
grant insert on csr.issue_supplier to csrimp;
grant insert on csr.issue_survey_answer to csrimp;
grant insert on csr.issue_type to csrimp;
grant insert on csr.issue_type_aggregate_ind_grp to csrimp;
grant insert on csr.issue_type_rag_status to csrimp;
grant insert on csr.rag_status to csrimp;
grant select,insert on csr.region_start_point to csrimp;
grant insert on csr.issue_involvement to csrimp;
grant insert on csr.issue_user_cover to csrimp;
grant insert on csr.user_measure_conversion to csrimp;
grant insert on csr.linked_meter to csrimp;
grant insert on csr.lookup_table to csrimp;
grant insert on csr.lookup_table_entry to csrimp;
grant insert on csr.meter_bucket to csrimp;
grant insert,select on csr.master_deleg to csrimp;
grant select,insert on csr.measure to csrimp;
grant select,insert on csr.measure_conversion to csrimp;
grant insert on csr.measure_conversion_period to csrimp;
grant select, delete on csr.measure_conversion_period to csrimp;
grant select, insert, update on csr.meter_aggregate_type to csrimp;
grant insert on csr.meter_alarm to csrimp;
grant insert on csr.meter_alarm_comparison to csrimp;
grant insert on csr.meter_alarm_event to csrimp;
grant insert on csr.meter_alarm_issue_period to csrimp;
grant insert on csr.meter_alarm_stat_run to csrimp;
grant insert on csr.meter_alarm_statistic to csrimp;
grant insert on csr.meter_alarm_statistic_job to csrimp;
grant insert on csr.meter_alarm_statistic_period to csrimp;
grant insert on csr.meter_alarm_test_time to csrimp;
grant insert on csr.meter_document to csrimp;
grant select,insert,update on csr.meter_data_source_hi_res_input to csrimp;
grant insert on csr.meter_element_layout to csrimp;
grant insert on csr.meter_excel_mapping to csrimp;
grant insert on csr.meter_excel_option to csrimp;
grant insert on csr.meter_header_element to csrimp;
grant insert on csr.meter_list_cache to csrimp;
grant insert on csr.meter_live_data to csrimp;
grant insert on csr.meter_meter_alarm_statistic to csrimp;
grant insert on csr.meter_orphan_data to csrimp;
grant insert on csr.meter_photo to csrimp;
grant insert on csr.meter_raw_data to csrimp;
grant insert on csr.meter_raw_data_log to csrimp;
grant insert on csr.meter_raw_data_error to csrimp;
grant insert on csr.meter_raw_data_source to csrimp;
grant insert on csr.meter_raw_data_status to csrimp;
grant select,insert on csr.meter_reading to csrimp;
grant insert on csr.meter_source_data to csrimp;
grant insert on csr.meter_source_type to csrimp;
grant insert on csr.meter_tab to csrimp;
grant insert on csr.meter_tab_group to csrimp;
grant insert on csr.meter_utility_contract to csrimp;
grant insert on csr.meter_xml_option to csrimp;
grant select, insert, update on csr.metering_options to csrimp;
grant insert on csr.model to csrimp;
grant insert on csr.model_instance to csrimp;
grant insert on csr.model_instance_chart to csrimp;
grant insert on csr.model_instance_map to csrimp;
grant insert on csr.model_instance_region to csrimp;
grant insert on csr.model_instance_sheet to csrimp;
grant insert on csr.model_map to csrimp;
grant insert on csr.model_range to csrimp;
grant insert on csr.model_range_cell to csrimp;
grant insert on csr.model_region_range to csrimp;
grant insert on csr.model_sheet to csrimp;
grant insert on csr.model_validation to csrimp;
grant insert on csr.non_comp_default to csrimp;
grant insert on csr.non_comp_default_issue to csrimp;
grant insert on csr.non_comp_default_folder to csrimp;
grant insert on csr.non_comp_default_tag to csrimp;
grant insert on csr.non_compliance to csrimp;
grant insert on csr.non_compliance_expr_action to csrimp;
grant insert on csr.non_compliance_tag to csrimp;
grant insert on csr.non_compliance_type to csrimp;
grant insert on csr.non_comp_type_audit_type to csrimp;
grant insert on csr.non_comp_type_rpt_audit_type to csrimp;
grant insert on csr.non_compliance_type_tag_group to csrimp;
grant select,insert on csr.non_compliance_type_flow_cap to csrimp;
grant insert,delete on csr.pct_ownership to csrimp;
grant select,insert on csr.pending_dataset to csrimp;
grant select,insert,update on csr.pending_ind to csrimp;
grant select,insert on csr.pending_period to csrimp;
grant select,insert on csr.pending_region to csrimp;
grant select,insert on csr.pending_val to csrimp;
grant select,insert on csr.pending_val_log to csrimp;
grant select,insert on csr.pending_val_variance to csrimp;
grant insert on csr.pending_val_accuracy_type_opt to csrimp;
grant insert on csr.pending_ind_accuracy_type to csrimp;
grant insert on csr.period to csrimp;
grant insert on csr.period_set to csrimp;
grant insert on csr.period_interval to csrimp;
grant insert on csr.period_interval_member to csrimp;
grant insert on csr.period_dates to csrimp;
grant select, insert on csr.portal_dashboard to csrimp;
grant insert on csr.postit to csrimp;
grant insert on csr.postit_file to csrimp;
grant insert on csr.qs_response_file to csrimp;
grant insert on csr.qs_answer_file to csrimp;
grant insert on csr.qs_answer_log to csrimp;
grant insert on csr.qs_custom_question_type to csrimp;
grant insert on csr.qs_expr_msg_action to csrimp;
grant insert on csr.qs_expr_nc_action_involve_role to csrimp;
grant insert on csr.qs_expr_non_compl_action to csrimp;
grant insert on csr.qs_filter_condition to csrimp;
GRANT INSERT ON csr.qs_filter_condition_general TO csrimp;
GRANT INSERT ON csr.qs_filter_cond_gen_type TO csrimp;
grant insert on csr.qs_question_option to csrimp;
grant insert on csr.qs_question_option_nc_tag to csrimp;
grant insert on csr.qs_response_postit to csrimp;
grant insert on csr.qs_submission_file to csrimp;
grant select,insert,update on csr.question to csrimp;
grant select,insert,update on csr.question_version to csrimp;
grant select,insert,update on csr.question_option to csrimp;
grant select,insert,update on csr.question_option_nc_tag to csrimp;
grant select,insert,update on csr.question_tag to csrimp;
grant select,insert,update on csr.quick_survey to csrimp;
grant insert on csr.quick_survey_answer to csrimp;
grant insert on csr.quick_survey_expr to csrimp;
grant insert on csr.quick_survey_expr_action to csrimp;
grant insert on csr.quick_survey_lang to csrimp;
grant insert on csr.quick_survey_question to csrimp;
grant insert on csr.quick_survey_question_tag to csrimp;
grant insert,update,select on csr.quick_survey_response to csrimp;
grant insert on csr.quick_survey_submission to csrimp;
grant insert on csr.quick_survey_type to csrimp;
grant select,insert,update,delete on csr.quick_survey_version to csrimp;
grant select,update,insert on csr.region to csrimp;
grant select, insert, update, delete on csr.region_description to csrimp;
grant insert on csr.region_event to csrimp;
grant insert on csr.region_internal_audit to csrimp;
grant insert on csr.region_meter_alarm to csrimp;
grant insert on csr.region_owner to csrimp;
grant insert on csr.region_proc_doc to csrimp;
grant insert on csr.region_proc_file to csrimp;
grant insert,select on csr.region_role_member to csrimp;
grant insert on csr.region_set to csrimp;
grant insert on csr.region_set_region to csrimp;
grant insert on csr.region_survey_response to csrimp;
grant insert on csr.region_score to csrimp;
grant insert on csr.region_score_log to csrimp;
grant insert,delete on csr.region_tag to csrimp;
grant select, insert on csr.region_tree to csrimp;
grant insert on csr.reporting_period to csrimp;
grant insert,select,update on csr.role to csrimp;
grant insert,select,delete on csr.role_grant to csrimp;
grant insert on csr.role_user_cover to csrimp;
grant insert,select on csr.route to csrimp;
grant insert,select on csr.route_step to csrimp;
grant insert,select on csr.route_step_user to csrimp;
grant insert,select on csr.rss_cache to csrimp;
grant insert,update,select on csr.scenario to csrimp;
grant insert on csr.scenario_ind to csrimp;
grant insert on csr.scenario_options to csrimp;
grant insert on csr.scenario_region to csrimp;
grant insert on csr.scenario_rule to csrimp;
grant insert on csr.scenario_rule_ind to csrimp;
grant insert on csr.scenario_rule_like_contig_ind to csrimp;
grant insert on csr.scenario_rule_region to csrimp;
grant insert on csr.scenario_run to csrimp;
grant insert on csr.scenario_run_val to csrimp;
grant insert,select on csr.scenario_run_version to csrimp;
grant insert,select on csr.scenario_run_version_file to csrimp;
grant insert on csr.score_threshold to csrimp;
grant insert on csr.score_type to csrimp;
grant insert on csr.score_type_agg_type to csrimp;
grant select on csr.score_type_agg_type_id_seq to csrimp;
grant insert on csr.scragpp_audit_log to csrimp;
grant insert on csr.scragpp_status to csrimp;
grant select,insert,update on csr.section to csrimp;
grant select,insert on csr.section_alert to csrimp;
grant insert,select on csr.section_cart_folder to csrimp;
grant insert,select on csr.section_cart to csrimp;
grant insert,select on csr.section_cart_member to csrimp;
grant select,insert,update on csr.section_comment to csrimp;
grant select,insert,update on csr.section_trans_comment to csrimp;
grant insert,select on csr.section_flow to csrimp;
grant select,insert on csr.section_module to csrimp;
grant insert,select on csr.section_tag to csrimp;
grant insert,select on csr.section_tag_member to csrimp;
grant insert,select on csr.section_routed_flow_state to csrimp;
grant insert on csr.section_version to csrimp;
grant insert on csr.section_status to csrimp;
grant insert on csr.section_transition to csrimp;
grant select,insert,update on csr.sheet to csrimp;
grant select,insert on csr.sheet_alert to csrimp;
grant insert on csr.sheet_date_schedule to csrimp;
grant select,insert on csr.sheet_history to csrimp;
grant select,insert on csr.sheet_inherited_value to csrimp;
grant select,insert,update on csr.sheet_value to csrimp;
grant select,insert on csr.sheet_value_accuracy to csrimp;
grant select,insert on csr.sheet_value_change to csrimp;
grant insert on csr.sheet_value_file to csrimp;
grant insert on csr.sheet_value_file_hidden_cache to csrimp;
grant select, insert on csr.sheet_value_var_expl to csrimp;
grant insert on csr.sheet_value_hidden_cache to csrimp;
grant select on csr.superadmin to csrimp;
grant insert on csr.supplier_score_log to csrimp;
grant insert on csr.tab to csrimp;
grant insert on csr.tab_description to csrimp;
grant insert on csr.tab_group to csrimp;
grant select,insert,update on csr.tab_portlet to csrimp;
grant insert on csr.tab_portlet_rss_feed to csrimp;
grant insert on csr.tab_portlet_user_region to csrimp;
grant insert on csr.tab_user to csrimp;
grant insert, update on csr.tag to csrimp;
grant insert on csr.tag_description to csrimp;
grant insert on csr.tag_group to csrimp;
grant insert on csr.tag_group_description to csrimp;
grant insert on csr.tag_group_member to csrimp;
grant insert on csr.target_dashboard to csrimp;
grant insert on csr.target_dashboard_ind_member to csrimp;
grant insert on csr.target_dashboard_reg_member to csrimp;
grant insert on csr.target_dashboard_value to csrimp;
grant insert on csr.template to csrimp;
grant insert on csr.tpl_img to csrimp;
grant insert on csr.tpl_rep_cust_tag_type to csrimp;
grant insert on csr.tpl_report to csrimp;
grant insert on csr.tpl_report_non_compl to csrimp;
grant insert on csr.tpl_report_tag to csrimp;
grant insert on csr.tpl_report_tag_dataview to csrimp;
grant insert on csr.tpl_report_tag_dv_region to csrimp;
grant insert on csr.tpl_report_tag_eval to csrimp;
grant insert on csr.tpl_report_tag_eval_cond to csrimp;
grant insert on csr.tpl_report_tag_ind to csrimp;
grant insert on csr.tpl_report_tag_logging_form to csrimp;
grant insert on csr.tpl_report_tag_text to csrimp;
grant insert on csr.tpl_report_tag_approval_note to csrimp;
grant insert on csr.tpl_report_tag_approval_matrix to csrimp;
grant insert on csr.tpl_report_tag_reg_data to csrimp;
grant insert on csr.tpl_report_tag_qchart to csrimp;
grant insert on csr.tpl_report_variant to csrimp;
grant insert on csr.tpl_report_variant_tag to csrimp;
grant insert on csr.trash to csrimp;
grant insert on csr.user_cover to csrimp;
grant insert, select on csr.user_setting to csrimp;
grant insert on csr.user_setting_entry to csrimp;
grant insert on csr.utility_contract to csrimp;
grant insert on csr.utility_invoice to csrimp;
grant insert on csr.utility_supplier to csrimp;
grant select, insert on csr.var_expl to csrimp;
grant select, insert on csr.var_expl_group to csrimp;
grant select,insert,delete on csr.val to csrimp;
grant select,insert,delete on csr.val_change to csrimp;
grant select,delete on csr.val_file to csrimp;
grant select,insert on csr.meter_reading_data to csrimp;
grant select,insert on csr.non_compliance_file to csrimp;
grant select,insert,update on csr.CURRENCY to csrimp;
grant select,insert,update on csr.FUND to csrimp;
grant select,insert,update on csr.FUND_FORM_PLUGIN to csrimp;
grant select,insert,update on csr.FUND_TYPE to csrimp;
grant select,insert,update on csr.LEASE to csrimp;
grant select,insert,update on csr.LEASE_POSTIT to csrimp;
grant select,insert,update on csr.LEASE_PROPERTY to csrimp;
grant select,insert,update on csr.LEASE_SPACE to csrimp;
grant select,insert,update on csr.LEASE_TYPE to csrimp;
grant select,insert,update on csr.METER_TYPE to csrimp;
grant select,insert,update on csr.MGMT_COMPANY to csrimp;
grant select,insert,update on csr.MGMT_COMPANY_CONTACT to csrimp;
grant select,insert,update on csr.MGMT_COMPANY_FUND_CONTACT to csrimp;
grant select,insert,update on csr.PLUGIN to csrimp;
grant select,insert,update on csr.PLUGIN_INDICATOR to csrimp;
grant select,insert,update on csr.ALL_PROPERTY to csrimp;
grant select,insert,update on csr.PROPERTY_ADDRESS_OPTIONS to csrimp;
grant select,insert,update on csr.PROPERTY_ELEMENT_LAYOUT to csrimp;
grant select,insert,update on csr.PROPERTY_CHARACTER_LAYOUT to csrimp;
grant select,insert,update on csr.PROPERTY_OPTIONS to csrimp;
grant select,insert,update on csr.PROPERTY_PHOTO to csrimp;
grant select,insert,update on csr.PROPERTY_SUB_TYPE to csrimp;
grant select,insert,update on csr.PROPERTY_TAB to csrimp;
grant select,insert,update on csr.PROP_TYPE_PROP_TAB to csrimp;
grant select,insert,update on csr.PROPERTY_TAB_GROUP to csrimp;
grant select,insert,update on csr.PROPERTY_TYPE to csrimp;
grant select, insert, update on csr.like_for_like_slot to csrimp;
grant select, insert, update on csr.like_for_like_email_sub to csrimp;

-- property dashboards
grant insert on csr.BENCHMARK_DASHBOARD to csrimp;
grant insert on csr.BENCHMARK_DASHBOARD_CHAR to csrimp;
grant insert on csr.BENCHMARK_DASHBOARD_IND to csrimp;
grant insert on csr.BENCHMARK_DASHBOARD_PLUGIN to csrimp;
grant insert on csr.METRIC_DASHBOARD to csrimp;
grant insert on csr.METRIC_DASHBOARD_IND to csrimp;
grant insert on csr.METRIC_DASHBOARD_PLUGIN to csrimp;

grant select,insert,update on csr.REGION_METRIC to csrimp;
grant select,insert,update on csr.REGION_METRIC_VAL to csrimp;
grant select,insert,update on csr.REGION_TYPE_METRIC to csrimp;
grant select,insert,update on csr.REGION_TYPE_TAG_GROUP to csrimp;
grant select,insert,update on csr.ALL_SPACE to csrimp;
grant select,insert,update on csr.SPACE_TYPE to csrimp;
grant select,insert,update on csr.SPACE_TYPE_REGION_METRIC to csrimp;
grant select,insert,update on csr.TENANT to csrimp;
grant select,insert,update on csr.plugin_type to csrimp;
grant select,insert,update on csr.plugin to csrimp;
grant select,insert,update on csr.property_type_space_type to csrimp;
grant select,insert,update on csr.supplier to csrimp;
grant select,insert,update on csr.delegation_layout to csrimp;

grant select, insert, update on csr.worksheet to csrimp;
grant select, insert, update on csr.worksheet_column to csrimp;
grant select, insert, update on csr.worksheet_column_value_map to csrimp;
grant select, insert, update on csr.worksheet_row to csrimp;
grant select, insert, update on csr.worksheet_value_map to csrimp;
grant select, insert, update on csr.worksheet_value_map_value to csrimp;
grant select, insert, update on csr.delegation_policy to csrimp;
grant select, insert, update on csr.scheduled_stored_proc to csrimp;
grant select, insert, update on csr.scheduled_stored_proc_log to csrimp;
grant select, insert, update on csr.customer_flow_capability to csrimp;
grant select, insert, update on csr.ia_type_survey_group to csrimp;
grant select, insert, update on csr.internal_audit_type_survey to csrimp;
grant select, insert, update on csr.internal_audit_survey to csrimp;
grant select, insert, update on csr.custom_factor_history to csrimp;
grant select, insert, update on csr.internal_audit_locked_tag to csrimp;

-- csr sequences
grant select on csr.alert_bounce_id_seq to csrimp;	  
grant select on csr.alert_frame_id_seq to csrimp;	  
grant select on csr.accuracy_type_id_seq to csrimp;
grant select on csr.accuracy_type_option_id_seq to csrimp;
grant select on csr.aggregate_ind_group_id_seq to csrimp;
grant select on csr.approval_dashboard_val_id_seq to csrimp;
grant select on csr.attachment_id_seq to csrimp;
grant select on csr.audit_closure_type_id_seq to csrimp;
grant select on csr.audit_non_compliance_id_seq to csrimp;
grant select on csr.audit_type_flw_inv_type_id_seq TO csrimp;
grant select on csr.application_pause_id_seq TO csrimp;
grant select on csr.baseline_config_id_seq to csrimp;
grant select on csr.baseline_config_period_id_seq to csrimp;
grant select on csr.correspondent_id_seq to csrimp;
grant select on csr.customer_alert_type_id_seq to csrimp;
grant select on csr.custom_question_type_id_seq to csrimp;
grant select on csr.custom_factor_history_seq to csrimp;
grant select on csr.dashboard_instance_id_seq to csrimp;
grant select on csr.dashboard_item_id_seq to csrimp;
grant select on csr.deleg_ind_group_id_seq to csrimp;
grant select on csr.deleg_plan_col_deleg_id_seq to csrimp;
grant select on csr.deleg_plan_col_id_seq to csrimp;
grant select on csr.deleg_plan_col_survey_id_seq to csrimp;
grant select on csr.delegation_date_schedule_seq to csrimp;
grant select on csr.delegation_ind_cond_id_seq to csrimp;
grant select on csr.doc_id_seq to csrimp;
grant select on csr.doc_data_id_seq to csrimp;
grant select on csr.doc_notification_id_seq to csrimp;
grant select on csr.event_id_seq to csrimp;
grant select on csr.expr_id_seq to csrimp;
grant select on csr.factor_id_seq to csrimp;
grant select on csr.flow_involvement_type_id_seq to csrimp;
grant select on csr.flow_item_id_seq to csrimp;
grant select on csr.flow_item_alert_id_seq to csrimp;
grant select on csr.flow_state_group_id_seq to csrimp;
grant select on csr.flow_state_transition_id_seq to csrimp;
grant select on csr.flow_transition_alert_id_seq to csrimp;
grant select on csr.flow_state_log_id_seq to csrimp;
grant select on csr.flow_state_log_file_id_seq to csrimp;
grant select on csr.flow_state_id_seq to csrimp;
grant select on csr.flow_state_rl_cap_id_seq to csrimp;
grant select on csr.flow_transition_alert_id_seq to csrimp;
grant select on csr.form_allocation_id_seq to csrimp;
grant select on csr.form_expr_id_seq to csrimp;
grant select on csr.imp_conflict_id_seq to csrimp;
grant select on csr.imp_ind_id_seq to csrimp;
grant select on csr.imp_measure_id_seq to csrimp;
grant select on csr.imp_region_id_seq to csrimp;
grant select on csr.imp_val_id_seq to csrimp;
grant select on csr.ind_validation_rule_id_seq to csrimp;
grant select on csr.internal_audit_type_id_seq to csrimp;
grant select on csr.internal_audit_type_group_seq to csrimp;
grant select on csr.internal_audit_type_report_seq to csrimp;
grant select on csr.ia_type_report_group_id_seq to csrimp;
grant select on csr.internal_audit_file_id_seq to csrimp;
grant select on csr.issue_id_seq to csrimp;
grant select on csr.issue_action_id_seq to csrimp;
grant select on csr.issue_action_log_id_seq to csrimp;
grant select on csr.issue_compliance_region_id_seq to csrimp;
grant select on csr.issue_custom_field_id_seq to csrimp;
grant select on csr.issue_id_seq to csrimp;
grant select on csr.issue_log_file_id_seq to csrimp;
grant select on csr.issue_log_id_seq to csrimp;
grant select on csr.issue_meter_alarm_id_seq to csrimp;
grant select on csr.issue_meter_data_source_id_seq to csrimp;
grant select on csr.issue_meter_id_seq to csrimp;
grant select on csr.issue_meter_raw_data_id_seq to csrimp;
grant select on csr.issue_non_compliance_id_seq to csrimp;
grant select on csr.issue_pending_val_id_seq to csrimp;
grant select on csr.issue_priority_id_seq to csrimp;
grant select on csr.issue_scheduled_task_id_seq to csrimp;
grant select on csr.issue_sheet_value_id_seq to csrimp;
grant select on csr.issue_supplier_id_seq to csrimp;
grant select on csr.issue_survey_answer_id_seq to csrimp;
grant select on csr.rag_status_id_seq to csrimp;
grant select on csr.meter_bucket_id_seq to csrimp;
grant select on csr.measure_conversion_id_seq to csrimp;
grant select on csr.meter_aggregate_type_id_seq to csrimp;
grant select on csr.meter_alarm_id_seq to csrimp;
grant select on csr.meter_data_id_seq to csrimp;
grant select on csr.meter_alarm_event_id_seq to csrimp;
grant select on csr.meter_comparison_id_seq to csrimp;
grant select on csr.meter_document_id_seq to csrimp;
grant select on csr.meter_issue_period_id_seq to csrimp;
grant select on csr.meter_header_element_id_seq to csrimp;
grant select on csr.meter_photo_id_seq to csrimp;
grant select on csr.meter_test_time_id_seq to csrimp;
grant select on csr.meter_raw_data_id_seq to csrimp;
grant select on csr.meter_raw_data_error_id_seq to csrimp;
grant select on csr.meter_statistic_id_seq to csrimp;
grant select on csr.meter_raw_data_id_seq to csrimp;
grant select on csr.meter_raw_data_error_id_seq to csrimp;
grant select on csr.meter_reading_id_seq to csrimp;
grant select on csr.model_range_id_seq to csrimp;
grant select on csr.non_comp_default_id_seq to csrimp;
grant select on csr.non_comp_default_folder_id_seq to csrimp;
grant select on csr.non_comp_default_issue_id_seq to csrimp;
grant select on csr.non_compliance_id_seq to csrimp;
grant select on csr.non_compliance_type_id_seq to csrimp;
grant select on csr.pending_ind_id_seq to csrimp;
grant select on csr.pending_region_id_seq to csrimp;
grant select on csr.pending_period_id_seq to csrimp;
grant select on csr.pending_val_id_seq to csrimp;
grant select on csr.pending_val_log_id_seq to csrimp;
grant select on csr.postit_id_seq to csrimp;
grant select on csr.postit_file_id_seq to csrimp;
grant select on csr.qs_answer_file_id_seq to csrimp;
grant select on csr.qs_answer_log_id_seq to csrimp;
grant select on csr.qs_expr_action_id_seq to csrimp;
grant select on csr.qs_expr_nc_action_id_seq to csrimp;
grant select on csr.qs_filter_condition_id_seq to csrimp;
grant select on csr.qs_filter_condition_gen_id_seq to csrimp;
grant select on csr.qs_question_option_id_seq to csrimp;
grant select on csr.qs_submission_id_seq to csrimp;
grant select on csr.question_id_seq to csrimp;
grant select on csr.quick_survey_type_id_seq to csrimp;
grant select on csr.raw_data_source_id_seq to csrimp;
grant select on csr.region_set_id_seq to csrimp;
grant select on csr.route_id_seq to csrimp;
grant select on csr.route_step_id_seq to csrimp;
grant select on csr.section_alert_id_seq to csrimp;
grant select on csr.section_cart_folder_id_seq to csrimp;
grant select on csr.section_cart_id_seq to csrimp;
grant select on csr.section_tag_id_seq to csrimp;
grant select on csr.score_threshold_id_seq to csrimp;
grant select on csr.score_type_id_seq to csrimp;
grant select on csr.section_comment_id_seq to csrimp;
grant select on csr.section_trans_comment_id_seq to csrimp;
grant select on csr.survey_response_id_seq to csrimp;
grant select on csr.sheet_history_id_seq to csrimp;
grant select on csr.sheet_id_seq to csrimp;
grant select on csr.sheet_value_change_id_seq to csrimp;
grant select on csr.sheet_value_id_seq to csrimp;
grant select on csr.tab_id_seq to csrimp;
grant select on csr.tab_portlet_id_seq to csrimp;
grant select on csr.tag_id_seq to csrimp;
grant select on csr.tag_group_id_seq to csrimp;
GRANT INSERT ON csr.term_cond_doc TO csrimp;
GRANT INSERT ON csr.term_cond_doc_log TO csrimp;
grant select on csr.tpl_report_non_compl_id_seq to csrimp;
grant select on csr.tpl_report_tag_app_note_id_seq to csrimp;
grant select on csr.tpl_rep_tag_app_matrix_id_seq to csrimp;
grant select on csr.tpl_report_tag_dataview_id_seq to csrimp;
grant select on csr.tpl_report_tag_eval_id_seq to csrimp;
grant select on csr.tpl_report_tag_ind_id_seq to csrimp;
grant select on csr.tpl_report_tag_logging_frm_seq to csrimp;
grant select on csr.tpl_report_tag_text_id_seq to csrimp;
grant select on csr.tpl_report_tag_reg_data_id_seq to csrimp;
grant select on csr.tpl_report_tag_qc_id_seq to csrimp;
grant select on csr.user_cover_id_seq to csrimp;
grant select on csr.var_expl_id_seq to csrimp;
grant select on csr.var_expl_group_id_seq to csrimp;
grant select on csr.val_change_id_seq to csrimp;
grant select on csr.val_id_seq to csrimp;
grant insert on csr.export_feed to csrimp;
grant insert on csr.export_feed_cms_form to csrimp;
grant insert on csr.export_feed_dataview to csrimp;
grant insert on csr.export_feed_stored_proc to csrimp;
grant select on csr.non_compliance_file_id_seq to csrimp;
grant select on csr.tenant_id_seq to csrimp;
grant select on csr.space_type_id_seq to csrimp;
grant select on csr.property_photo_id_seq to csrimp;
grant select on csr.property_type_id_seq to csrimp;
grant select on csr.property_sub_type_id_seq to csrimp;
grant select on csr.region_score_log_id_seq to csrimp;
grant select on csr.benchmark_dashb_char_id_seq to csrimp;
grant select on csr.lease_id_seq to csrimp;
grant select on csr.plugin_Id_seq to csrimp;
grant select on csr.plugin_ind_id_seq to csrimp;
grant select on csr.mgmt_company_id_seq to csrimp;
grant select on csr.fund_id_seq to csrimp;
grant select on csr.mgmt_company_contact_id_seq to csrimp;
grant select on csr.meter_type_Id_seq to csrimp;
grant select on csr.meter_input_id_seq to csrimp;
grant select on csr.meter_element_layout_id_seq to csrimp;
grant select on csr.lease_type_id_seq to csrimp;
grant select on csr.fund_type_id_seq to csrimp;
grant select on csr.region_metric_val_id_seq to csrimp;
grant select on csr.supplier_score_id_seq to csrimp;
grant select on csr.qs_expr_msg_action_id_seq to csrimp;
grant select on csr.delegation_layout_id_seq to csrimp;
grant select on csr.postit_id_seq to csrimp;
grant select on csr.non_compliance_file_id_seq to csrimp;
grant select on csr.ssp_id_seq to csrimp;
grant select on csr.sspl_id_seq to csrimp;

grant select on csr.worksheet_id_seq to csrimp;
grant select on csr.value_map_id_seq to csrimp;
grant select on csr.customer_flow_cap_id_seq to csrimp;
grant select on csr.ia_type_survey_group_id_seq to csrimp;
grant select on csr.ia_type_survey_id_seq to csrimp;

-- chain tables
grant select, insert, update on chain.capability to csrimp;
grant select, insert, update on chain.capability_flow_capability to csrimp;
grant select, insert, update on chain.customer_options to csrimp;
grant select, insert, update on chain.company_type to csrimp;
grant select, insert, update on chain.company to csrimp;
grant select, insert, update on chain.applied_company_capability to csrimp;
grant select, insert, update on chain.chain_user to csrimp;
grant select, insert, update on chain.company_group to csrimp;
grant select, insert, update on chain.company_type_relationship to csrimp;
grant select, insert, update on chain.company_type_capability to csrimp;
grant select, insert, update on chain.group_capability_override to csrimp;
grant select, insert, update on chain.implementation to csrimp;
grant select, insert, update on chain.sector to csrimp;
grant select, insert, update on chain.tertiary_relationships to csrimp;
grant select, insert, update on chain.company_type_role to csrimp;
grant select, insert, update on chain.supplier_relationship to csrimp;
grant select, insert, update on chain.supplier_relationship_source to csrimp;
grant select, insert, update on chain.supplier_follower to csrimp;
grant select, insert, update on chain.card_group_progression to csrimp;
grant select, insert, update on chain.card_group_card to csrimp;
grant select, insert, update on chain.card_init_param to csrimp;
grant select on chain.card to csrimp;

grant select, insert, update on chain.project to csrimp;
grant select, insert, update on chain.activity_type to csrimp;
grant select, insert, update on chain.outcome_type to csrimp;
grant select, insert, update on chain.activity_outcome_type to csrimp;
grant select, insert, update on chain.activity to csrimp;
grant select, insert, update on chain.activity_log to csrimp;
grant select, insert, update on chain.activity_log_file to csrimp;
grant select, insert, update on chain.activity_type_tag_group to csrimp;
grant select, insert, update on chain.activity_involvement to csrimp;
grant select, insert, update on chain.activity_tag to csrimp;
grant select, insert, update on chain.activity_type_action to csrimp;
grant select, insert, update on chain.activity_outcome_type_action to csrimp;
grant select, insert, update on chain.activity_type_alert to csrimp;
grant select, insert, update on chain.activity_type_alert_role to csrimp;
grant select, insert, update on chain.activity_type_default_user to csrimp;
grant select, insert, update on chain.product_type to csrimp;
grant select, insert, update on chain.product_type_tr to csrimp;
grant select, insert, update on chain.product_type_tag to csrimp;
grant select, insert, update on chain.company_product_type to csrimp;

grant select, insert, update on chain.alert_partial_template to csrimp;
grant select, insert, update on chain.alert_partial_template_param to csrimp;
grant select, insert, update on chain.amount_unit to csrimp;
grant select, insert, update on chain.applied_company_capability to csrimp;
grant select, insert, update on chain.audit_request to csrimp;
grant select, insert, update on chain.audit_request_alert to csrimp;
grant select, insert, update on chain.business_unit to csrimp;
grant select, insert, update on chain.business_unit_member to csrimp;
grant select, insert, update on chain.business_unit_supplier to csrimp;
grant select, insert, update on chain.card to csrimp;
grant select, insert, update on chain.chain_user_email_address_log to csrimp;
grant select, insert, update on chain.company_cc_email to csrimp;
grant select, insert, update on chain.company_header to csrimp;
grant select, insert, update on chain.company_metric_type to csrimp;
grant select, insert, update on chain.company_metric to csrimp;
grant select, insert, update on chain.company_reference to csrimp;
grant select, insert, update on chain.company_tab to csrimp;
grant select, insert, update on chain.company_tab_related_co_type to csrimp;
grant select, insert, update on chain.company_tab_company_type_role to csrimp;
grant select, insert, update on chain.company_tag_group to csrimp;
grant select, insert, update on chain.component_type to csrimp;
grant select, insert, update on chain.component_type_containment to csrimp;
grant select, insert, update on chain.company_type_tag_group to csrimp;
grant select, insert, update on chain.component to csrimp;
grant select, insert, update on chain.file_upload to csrimp;
grant select, insert, update on chain.component_document to csrimp;
grant select, insert, update on chain.component_source to csrimp;
grant select, insert, update on chain.component_tag to csrimp;
grant select, insert, update on chain.compound_filter to csrimp;
grant select, insert, update on chain.customer_alert_entry_template to csrimp;
grant select, insert, update on chain.customer_alert_entry_type to csrimp;
grant select, insert, update on chain.customer_aggregate_type to csrimp;
grant select, insert, update on chain.default_product_code_type to csrimp;
grant select, insert, update on chain.default_supp_rel_code_label to csrimp;
grant select, insert, update on chain.email_stub to csrimp;
grant select, insert, update on chain.file_group to csrimp;
grant select, insert, update on chain.file_group_file to csrimp;
grant select, insert, update on chain.filter to csrimp;
grant select, insert, update on chain.filter_field to csrimp;
grant select, insert, update on chain.filter_value to csrimp;
grant select, insert, update on chain.filter_page_column to csrimp;
grant select, insert, update on chain.filter_item_config to csrimp;
grant select, insert, update on chain.filter_page_cms_table to csrimp;
grant select, insert, update on chain.filter_page_ind to csrimp;
grant select, insert, update on chain.filter_page_ind_interval to csrimp;
grant select, insert, update on chain.filtersupplierreportlinks to csrimp;
grant select, insert, update on chain.flow_filter to csrimp;
grant select, insert, update on chain.invitation to csrimp;
grant select, insert, update on chain.invitation_user_tpl to csrimp;
grant select, insert, update on chain.message_definition to csrimp;
grant select, insert, update on chain.message_param to csrimp;
grant select, insert, update on chain.questionnaire_group to csrimp;
grant select, insert, update on chain.questionnaire_type to csrimp;
grant select, insert, update on chain.flow_questionnaire_type to csrimp;
grant select, insert, update on chain.invitation_qnr_type_component to csrimp;
grant select, insert, update on chain.message to csrimp;
grant select, insert, update on chain.alert_entry to csrimp;
grant select, insert, update on chain.alert_entry_param to csrimp;
grant select, insert, update on chain.invitation_qnr_type to csrimp;
grant select, insert, update on chain.message_recipient to csrimp;
grant select, insert, update on chain.message_refresh_log to csrimp;
grant select, insert, update on chain.newsflash to csrimp;
grant select, insert, update on chain.newsflash_company to csrimp;
grant select, insert, update on chain.newsflash_user_settings to csrimp;
grant select, insert, update on chain.product to csrimp;
grant select, insert, update on chain.product_code_type to csrimp;
grant select, insert, update on chain.product_metric_type to csrimp;
grant select, insert, update on chain.product_metric to csrimp;
grant select, insert, update on chain.product_metric_product_type to csrimp;
grant select, insert, update on chain.product_revision to csrimp;
grant select, insert, update on chain.purchase_channel to csrimp;
grant select, insert, update on chain.purchased_component to csrimp;
grant select, insert, update on chain.purchase to csrimp;
grant select, insert, update on chain.purchase_tag to csrimp;
grant select, insert, update on chain.purchaser_follower to csrimp;
grant select, insert, update on chain.qnnaire_share_alert_log to csrimp;
grant select, insert, update on chain.qnr_action_security_mask to csrimp;
grant select, insert, update on chain.questionnaire to csrimp;
grant select, insert, update on chain.qnr_share_log_entry to csrimp;
grant select, insert, update on chain.qnr_status_log_entry to csrimp;
grant select, insert, update on chain.questionnaire_expiry_alert to csrimp;
grant select, insert, update on chain.questionnaire_invitation to csrimp;
grant select, insert, update on chain.questionnaire_metric_type to csrimp;
grant select, insert, update on chain.questionnaire_metric to csrimp;
grant select, insert, update on chain.questionnaire_share to csrimp;
grant select, insert, update on chain.questionnaire_user to csrimp;
grant select, insert, update on chain.questionnaire_user_action to csrimp;
grant select, insert, update on chain.recipient to csrimp;
grant select, insert, update on chain.reference to csrimp;
grant insert on chain.reference_company_type to csrimp;
grant select, insert, update on chain.reference_capability to csrimp;
grant select, insert, update on chain.review_alert to csrimp;
grant select, insert, update on chain.saved_filter to csrimp;
grant select, insert, update on chain.saved_filter_aggregation_type to csrimp;
grant select, insert, update on chain.saved_filter_column to csrimp;
GRANT SELECT, INSERT, UPDATE ON chain.saved_filter_region TO csrimp;
grant select, insert, update on chain.saved_filter_alert to csrimp;
grant select, insert, update on chain.saved_filter_alert_subscriptn to csrimp;
grant select, insert, update on chain.saved_filter_sent_alert to csrimp;
grant select, insert, update on chain.scheduled_alert to csrimp;
grant select, insert, update on chain.supplier_audit to csrimp;
grant select, insert, update on chain.task to csrimp;
grant select, insert, update on chain.task_action_trigger to csrimp;
grant select, insert, update on chain.task_entry to csrimp;
grant select, insert, update on chain.task_entry_date to csrimp;
grant select, insert, update on chain.task_entry_file to csrimp;
grant select, insert, update on chain.task_entry_note to csrimp;
grant select, insert, update on chain.task_scheme to csrimp;
grant select, insert, update on chain.task_type to csrimp;
grant select, insert, update on chain.task_invitation_qnr_type to csrimp;
grant select, insert, update on chain.ucd_logon to csrimp;
grant select, insert, update on chain.uninvited_supplier to csrimp;
grant select, insert, update on chain.url_overrides to csrimp;
grant select, insert, update on chain.user_alert_entry_type to csrimp;
grant select, insert, update on chain.user_message_log to csrimp;
grant select, insert, update on chain.validated_purchased_component to csrimp;
grant select, insert, update on chain.worksheet_file_upload to csrimp;
grant select, insert, update on chain.default_message_definition to csrimp;
grant select, insert, update on chain.message_definition_lookup to csrimp;
grant select, insert, update on chain.filter_type to csrimp;
grant select, insert, update on chain.group_capability to csrimp;
grant select, insert, update on chain.card_progression_action to csrimp;
grant select, insert, update on chain.business_relationship_type to csrimp;
grant select, insert, update on chain.business_relationship_tier to csrimp;
grant select, insert, update on chain.business_rel_tier_company_type to csrimp;
grant select, insert, update on chain.business_relationship to csrimp;
grant select, insert, update on chain.business_relationship_company to csrimp;
grant select, insert, update on chain.business_relationship_period to csrimp;
grant select, insert, update on chain.risk_level to csrimp;
grant select, insert, update on chain.country_risk_level to csrimp;
grant select, insert, update on chain.import_source to csrimp;
grant insert on chain.import_source_lock to csrimp;
grant select, insert, update on chain.dedupe_staging_link to csrimp;
grant select, insert, update on chain.dedupe_mapping to csrimp;
grant select, insert, update on chain.dedupe_rule to csrimp;
grant select, insert, update on chain.dedupe_rule_set to csrimp;
grant select, insert, update on chain.dedupe_merge_log to csrimp;
grant select, insert, update on chain.dedupe_preproc_comp to csrimp;
grant select, insert, update on chain.dedupe_preproc_rule to csrimp;
grant select, insert, update on chain.dedupe_pp_field_cntry to csrimp;
grant select, insert, update on chain.dedupe_sub to csrimp;
grant select, insert, update on chain.dedupe_pp_alt_comp_name to csrimp;
grant select, insert, update on chain.dd_customer_blcklst_email to csrimp;
grant insert on chain.aggregate_type_config to csrimp;
grant select, insert, update on chain.higg to csrimp;
grant select, insert, update on chain.higg_config to csrimp;
grant select, insert, update on chain.higg_module_tag_group to csrimp;
grant select, insert, update on chain.higg_config_module to csrimp;
grant select, insert, update on chain.higg_response to csrimp;
grant select, insert, update on chain.higg_section_score to csrimp;
grant select, insert, update on chain.higg_sub_section_score to csrimp;
grant select, insert, update on chain.higg_question_response to csrimp;
grant select, insert, update on chain.higg_profile to csrimp;
grant select, insert, update on chain.higg_question_survey to csrimp;
grant select, insert, update on chain.higg_question_option_survey to csrimp;
grant select, insert, update on chain.higg_config_profile to csrimp;
grant select, insert, update on chain.higg_question_opt_conversion to csrimp;
grant select, insert, update on chain.product_header to csrimp;
grant select, insert, update on chain.product_header_product_type to csrimp;
grant select, insert, update on chain.product_tab to csrimp;
grant select, insert, update on chain.product_tab_product_type to csrimp;
grant select, insert, update on chain.product_supplier_tab to csrimp;
grant select, insert, update on chain.prod_supp_tab_product_type to csrimp;
grant select, insert, update on chain.product_company_alert to csrimp;
GRANT SELECT, INSERT, UPDATE ON chain.supplier_relationship_score TO csrimp;
grant select, insert, update on chain.supplier_involvement_type to csrimp;

grant select on chain.import_source_id_seq to csrimp;
grant select on chain.dedupe_mapping_id_seq to csrimp;
grant select on chain.dedupe_rule_id_seq to csrimp;
grant select on chain.dedupe_rule_set_id_seq to csrimp;
grant select on chain.dedupe_merge_log_id_seq to csrimp;
grant select on chain.dedupe_staging_link_id_seq to csrimp;
grant select on chain.dedupe_preproc_rule_id_seq to csrimp;
grant select, insert, update on chain.customer_grid_extension to csrimp;

grant select, insert, update on chain.company_type_score_calc to csrimp;
grant select, insert, update on chain.comp_type_score_calc_comp_type to csrimp;

grant select on chain.certification_type_id_seq to csrimp;
grant select, insert, update on chain.certification_type to csrimp;
grant select, insert, update on chain.cert_type_audit_type to csrimp;
grant select on chain.alt_company_name_id_seq to csrimp;
grant select, insert, update on chain.alt_company_name to csrimp;
grant select on chain.alt_company_name to csr;
grant select, insert, update on chain.pending_company_tag to csrimp;
grant select, insert, update on chain.pend_company_suggested_match to csrimp;
grant select, insert, update on chain.company_request_action to csrimp;

-- chain sequences
grant select on chain.capability_id_seq to csrimp;
grant select on chain.group_capability_id_seq to csrimp;
grant select on chain.company_type_id_seq to csrimp;

grant select on chain.project_id_seq to csrimp;
grant select on chain.activity_id_seq to csrimp;
grant select on chain.activity_type_id_seq to csrimp;
grant select on chain.outcome_type_id_seq to csrimp;
grant select on chain.activity_log_id_seq to csrimp;
grant select on chain.activity_log_file_id_seq to csrimp;
grant select on chain.activity_type_action_id_seq to csrimp;
grant select on chain.activity_outcm_typ_actn_id_seq to csrimp;
grant select on chain.product_type_id_seq to csrimp;

grant select on chain.alert_entry_id_seq to csrimp;
grant select on chain.card_id_seq to csrimp;
grant select on chain.message_id_seq to csrimp;
grant select on chain.scheduled_alert_id_seq to csrimp;
grant select on chain.audit_request_id_seq to csrimp;
grant select on chain.company_header_id_seq to csrimp;
grant select on chain.company_tab_id_seq to csrimp;
grant select on chain.component_id_seq to csrimp;
grant select on chain.compound_filter_id_seq to csrimp;
grant select on chain.file_group_id_seq to csrimp;
grant select on chain.file_group_file_id_seq to csrimp;
grant select on chain.filter_id_seq to csrimp;
grant select on chain.filter_type_id_seq to csrimp;
grant select on chain.filter_field_id_seq to csrimp;
grant select on chain.filter_value_id_seq to csrimp;
grant select on chain.filter_page_cms_table_id_seq to csrimp;
grant select on chain.questionnaire_type_id_seq to csrimp;
grant select on chain.invitation_id_seq to csrimp;
grant select on chain.message_definition_id_seq to csrimp;
grant select on chain.questionnaire_id_seq to csrimp;
grant select on chain.recipient_id_seq to csrimp;
grant select on chain.newsflash_id_seq to csrimp;
grant select on chain.product_id_seq to csrimp;
grant select on chain.purchase_id_seq to csrimp;
grant select on chain.questionnaire_share_id_seq to csrimp;
grant select on chain.task_id_seq to csrimp;
grant select on chain.task_type_id_seq to csrimp;
grant select on chain.task_entry_id_seq to csrimp;
grant select on chain.business_rel_type_id_seq to csrimp;
grant select on chain.business_rel_tier_id_seq to csrimp;
grant select on chain.business_relationship_id_seq to csrimp;
grant select on chain.business_rel_period_id_seq to csrimp;
grant select on chain.filter_page_ind_id_seq to csrimp;
grant select on chain.filter_page_ind_intrval_id_seq to csrimp;
grant select on chain.customer_aggregate_type_id_seq to csrimp;
grant select on chain.risk_level_id_seq to csrimp;
grant select on chain.reference_id_seq to csrimp;
grant select on chain.company_reference_id_seq to csrimp;
grant select on chain.higg_config_id_seq to csrimp;
grant select on chain.product_header_id_seq to csrimp;
grant select on chain.product_tab_id_seq to csrimp;
grant select on chain.product_supplier_tab_id_seq to csrimp;
grant select on chain.customer_filter_column_id_seq to csrimp;
grant select on chain.customer_filter_item_id_seq to csrimp;
grant select on chain.cust_filt_item_agg_type_id_seq to csrimp;
grant select, insert, update on chain.customer_filter_column to csrimp;
grant select, insert, update on chain.customer_filter_item to csrimp;
grant select, insert, update on chain.cust_filt_item_agg_type to csrimp;
grant select on chain.supplier_rel_score_id_seq to csrimp;
grant select on chain.company_type_role_id_seq to csrimp;
grant select on chain.comp_tab_comp_type_role_id_seq to csrimp;


grant select on chain.bsci_log_id_seq to csrimp;
grant select on chain.bsci_integration_report_id_seq to csrimp;
grant select on chain.bsci_supplier_id_seq to csrimp;
grant select on chain.bsci_audit_id_seq to csrimp;
grant select on chain.bsci_2009_audit_id_seq to csrimp;
grant select on chain.bsci_2009_a_finding_id_seq to csrimp;
grant select on chain.bsci_2009_a_associate_id_seq to csrimp;
grant select on chain.bsci_2014_audit_id_seq to csrimp;
grant select on chain.bsci_2014_a_finding_id_seq to csrimp;
grant select on chain.bsci_2014_a_associate_id_seq to csrimp;
grant select on chain.bsci_ext_audit_id_seq to csrimp;

-- security tables
grant select, insert on security.acl to csrimp;
grant insert on security.account_policy to csrimp;
grant insert on security.acc_policy_pwd_regexp to csrimp;
grant insert on security.application to csrimp;
grant select, insert on security.attributes to csrimp;
grant insert on security.group_members to csrimp;
grant insert on security.group_table to csrimp;
grant insert on security.home_page to csrimp;
grant insert on security.ip_rule to csrimp;
grant insert on security.ip_rule_entry to csrimp;
grant insert, update on security.menu to csrimp;
grant select on security.password_regexp to csrimp;
grant select on security.password_regexp_id_seq to csrimp;
grant select, insert on security.permission_name to csrimp;
grant select, insert on security.permission_mapping to csrimp;
grant select, insert, update on security.securable_object to csrimp;
grant insert, update, select on security.securable_object_attributes to csrimp;
grant select, insert, update on security.securable_object_class to csrimp;
grant insert on security.securable_object_keyed_acl to csrimp;
grant insert on security.user_certificates to csrimp;
grant insert on security.user_password_history to csrimp;
grant insert on security.user_table to csrimp;
grant insert on security.web_resource to csrimp;
grant insert, select on security.website to csrimp;

-- security sequences
grant select on security.acl_id_seq to csrimp;
grant select on security.attribute_id_seq to csrimp;
grant select on security.ip_rule_id_seq to csrimp;
grant select on security.sid_id_seq to csrimp;

-- mail tables
grant insert on mail.account to csrimp;
grant insert on mail.account_alias to csrimp;
grant select,insert,update on mail.mailbox to csrimp;
grant insert on mail.mailbox_message to csrimp;
grant insert on mail.message to csrimp;
grant insert on mail.message_header to csrimp;
grant insert on mail.message_address_field to csrimp;
grant select on mail.message_id_seq to csrimp;

-- aspen2 tables
grant select, insert, update, delete on aspen2.application to csrimp;
grant insert on aspen2.translated to csrimp;
grant insert on aspen2.translation to csrimp;
grant insert on aspen2.translation_application to csrimp;
grant insert on aspen2.translation_set to csrimp;
grant insert on aspen2.translation_set_include to csrimp;
grant select on aspen2.translated_id_seq to csrimp;
grant select on aspen2.lang to csrimp;
GRANT EXECUTE ON aspen2.t_split_table TO csrimp;

-- cms tables
grant insert on cms.app_schema to csrimp;
grant insert on cms.app_schema_table to csrimp;
grant insert on cms.cms_aggregate_type to csrimp;
grant insert on cms.context to csrimp;
grant insert on cms.data_helper to csrimp;
grant insert on cms.fast_context to csrimp;
grant insert on cms.flow_tab_column_cons to csrimp;
grant insert on cms.image to csrimp;
grant insert on cms.securable_object_whitelist to csrimp;
grant insert on cms.ck_cons to csrimp;
grant insert on cms.ck_cons_col to csrimp;
grant insert on cms.display_template to csrimp;
grant insert on cms.doc_template to csrimp;
grant insert on cms.doc_template_file to csrimp;
grant insert on cms.doc_template_version to csrimp;
grant insert on cms.filter to csrimp;
grant insert on cms.fk_cons to csrimp;
grant insert on cms.fk_cons_col to csrimp;
grant insert on cms.form to csrimp;
grant select, insert, update on cms.form_version to csrimp;
grant insert on cms.image_tag to csrimp;
grant insert on cms.link_track to csrimp;
grant select, insert on cms.oracle_tab to csrimp;
grant select, insert, update on cms.tab to csrimp;
grant select on cms.sys_schema to csrimp;
grant select, insert, update on cms.tab_column to csrimp;
grant insert on cms.tab_column_link to csrimp;
grant insert on cms.tab_column_link_type to csrimp;
grant insert on cms.tab_column_measure to csrimp;
grant insert on cms.tag to csrimp;
grant insert on cms.uk_cons to csrimp;
grant insert on cms.uk_cons_col to csrimp;
grant insert on cms.web_publication to csrimp;
grant insert on cms.tab_column_role_permission to csrimp;
grant insert on cms.tab_aggregate_ind to csrimp;
grant insert on cms.tab_issue_aggregate_ind to csrimp;
grant insert on cms.enum_group_tab to csrimp;
grant insert on cms.enum_group to csrimp;
grant insert on cms.enum_group_member to csrimp;

-- cms sequences
grant select on cms.cms_aggregate_type_id_seq to csrimp;
grant select on cms.column_id_seq to csrimp;
grant select on cms.web_publication_id_seq to csrimp;
grant select on cms.display_template_id_seq to csrimp;
grant select on cms.doc_template_id_seq to csrimp;
grant select on cms.doc_template_file_id_seq to csrimp;
grant select on cms.item_id_seq to csrimp;
grant select on cms.temp_upload_id_seq to csrimp;
grant select on cms.uk_cons_id_seq to csrimp;
grant select on cms.fk_cons_id_seq to csrimp;
grant select on cms.ck_cons_id_seq to csrimp;
grant select on cms.tag_id_seq to csrimp;
grant select on cms.tab_column_link_seq to csrimp;
grant select on cms.tab_aggregate_ind_id_seq to csrimp;
grant select on cms.enum_group_id_seq to csrimp;

--chem

grant select, insert, update on chem.chem_options to csrimp;
grant select, insert, update on chem.cas to csrimp;
grant select, insert, update on chem.cas_group to csrimp;
grant select, insert, update on chem.cas_group_member to csrimp;
grant select, insert, update on chem.cas_restricted to csrimp;
grant select, insert, update on chem.classification to csrimp;
grant select, insert, update on chem.manufacturer to csrimp;
grant select, insert, update on chem.substance to csrimp;
grant select, insert, update on chem.substance_cas to csrimp;
grant select, insert, update on chem.usage to csrimp;
grant select, insert, update on chem.substance_region to csrimp;
grant select, insert, update on chem.substance_region_process to csrimp;
grant select, insert, update on chem.process_cas_default to csrimp;
grant select, insert, update on chem.substance_process_use_change to csrimp;
grant select, insert, update on chem.subst_process_cas_dest_change to csrimp;
grant select, insert, update on chem.substance_audit_log to csrimp;
grant select, insert, update on chem.substance_file to csrimp;
grant select, insert, update on chem.substance_process_use to csrimp;
grant select, insert, update on chem.substance_process_cas_dest to csrimp;
grant select, insert, update on chem.substance_process_use_file to csrimp;
grant select, insert, update on chem.usage_audit_log to csrimp;

grant select on chem.cas_group_id_seq to csrimp;
grant select on chem.classification_id_seq to csrimp;
grant select on chem.manufacturer_id_seq to csrimp;
grant select on chem.substance_id_seq to csrimp;
grant select on chem.subst_rgn_proc_process_id_seq to csrimp;
grant select on chem.usage_id_seq to csrimp;
grant select on chem.subst_proc_use_change_id_seq to csrimp;
grant select on chem.subst_proc_cas_dest_chg_id_seq to csrimp;
grant select on chem.sub_audit_log_id_seq to csrimp;
grant select on chem.substance_file_id_seq to csrimp;
grant select on chem.substance_process_use_id_seq to csrimp;
grant select on chem.subst_proc_use_file_id_seq to csrimp;
grant select on chem.usage_audit_log_id_seq to csrimp;

--FB63025 - Carbon Module
-- grants for csrimp
grant select, insert, update on ct.customer_options to csrimp;
grant select, insert, update on ct.company to csrimp;
grant select, insert, update on ct.breakdown_type to csrimp;
grant select, insert, update on ct.breakdown to csrimp;
grant select, insert, update on ct.breakdown_group to csrimp;
grant select, insert, update on ct.breakdown_region to csrimp;
grant select, insert, update on ct.breakdown_region_eio to csrimp;
grant select, insert, update on ct.breakdown_region_group to csrimp;
grant select, insert, update on ct.bt_air_trip to csrimp;
grant select, insert, update on ct.bt_bus_trip to csrimp;
grant select, insert, update on ct.bt_cab_trip to csrimp;
grant select, insert, update on ct.bt_car_trip to csrimp;
grant select, insert, update on ct.bt_emissions to csrimp;
grant select, insert, update on ct.bt_motorbike_trip to csrimp;
grant select, insert, update on ct.bt_options to csrimp;
grant select, insert, update on ct.bt_profile to csrimp;
grant select, insert, update on ct.bt_train_trip to csrimp;
grant select, insert, update on ct.company_consumption_type to csrimp;
grant select, insert, update on ct.ec_bus_entry to csrimp;
grant select, insert, update on ct.ec_car_entry to csrimp;
grant select, insert, update on ct.ec_emissions_all to csrimp;
grant select, insert, update on ct.ec_motorbike_entry to csrimp;
grant select, insert, update on ct.ec_options to csrimp;
grant select, insert, update on ct.ec_profile to csrimp;
grant select, insert, update on ct.ec_questionnaire to csrimp;
grant select, insert, update on ct.ec_questionnaire_answers to csrimp;
grant select, insert, update on ct.ec_train_entry to csrimp;
grant select, insert, update on ct.hotspot_result to csrimp;
grant select, insert, update on ct.ht_consumption to csrimp;
grant select, insert, update on ct.ht_consumption_region to csrimp;
grant select, insert, update on ct.ht_cons_source_breakdown to csrimp;
grant select, insert, update on ct.ps_emissions_all to csrimp;
grant select, insert, update on ct.supplier to csrimp;
grant select, insert, update on ct.ps_item to csrimp;
grant select, insert, update on ct.ps_item_eio to csrimp;
grant select, insert, update on ct.ps_options to csrimp;
grant select, insert, update on ct.ps_spend_breakdown to csrimp;
grant select, insert, update on ct.ps_supplier_eio_freq to csrimp;
grant select, insert, update on ct.supplier_contact to csrimp;
grant select, insert, update on ct.up_options to csrimp;
grant select, insert, update on ct.worksheet_value_map_breakdown to csrimp;
grant select, insert, update on ct.worksheet_value_map_currency to csrimp;
grant select, insert, update on ct.worksheet_value_map_distance to csrimp;
grant select, insert, update on ct.worksheet_value_map_region to csrimp;
grant select, insert, update on ct.worksheet_value_map_supplier to csrimp;

grant select on ct.breakdown_id_seq to csrimp;
grant select on ct.breakdown_id_seq to CSR;
grant select on ct.breakdown_type_id_seq to csrimp;
grant select on ct.breakdown_type_id_seq to CSR;
grant select on ct.breakdown_group_id_seq to csrimp;
grant select on ct.breakdown_group_id_seq to CSR;
grant select on ct.bt_trip_entry_id_seq to csrimp;
grant select on ct.bt_trip_entry_id_seq to CSR;
grant select on ct.ec_questionnaire_id_seq to csrimp;
grant select on ct.ec_questionnaire_id_seq to CSR;
grant select on ct.ec_questionnaire_ans_id_seq to csrimp;
grant select on ct.ec_questionnaire_ans_id_seq to CSR;
grant select on ct.ps_item_id_seq to csrimp;
grant select on ct.ps_item_id_seq to CSR;
grant select on ct.supplier_id_seq to csrimp;
grant select on ct.supplier_id_seq to CSR;
grant select on ct.supplier_contact_id_seq to csrimp;
grant select on ct.supplier_contact_id_seq to CSR;

-- non csrimp grants
grant select, insert, update on ct.customer_options to CSR;
grant select, insert, update on ct.company to CSR;
grant select, insert, update on ct.breakdown_type to CSR;
grant select, insert, update on ct.breakdown to CSR;
grant select, insert, update on ct.breakdown_group to CSR;
grant select, insert, update on ct.breakdown_region to CSR;
grant select, insert, update on ct.breakdown_region_eio to CSR;
grant select, insert, update on ct.breakdown_region_group to CSR;
grant select, insert, update on ct.bt_air_trip to CSR;
grant select, insert, update on ct.bt_bus_trip to CSR;
grant select, insert, update on ct.bt_cab_trip to CSR;
grant select, insert, update on ct.bt_car_trip to CSR;
grant select, insert, update on ct.bt_emissions to CSR;
grant select, insert, update on ct.bt_motorbike_trip to CSR;
grant select, insert, update on ct.bt_options to CSR;
grant select, insert, update on ct.bt_profile to CSR;
grant select, insert, update on ct.bt_train_trip to CSR;
grant select, insert, update on ct.company_consumption_type to CSR;
grant select, insert, update on ct.ec_bus_entry to CSR;
grant select, insert, update on ct.ec_car_entry to CSR;
grant select, insert, update on ct.ec_emissions_all to CSR;
grant select, insert, update on ct.ec_motorbike_entry to CSR;
grant select, insert, update on ct.ec_options to CSR;
grant select, insert, update on ct.ec_profile to CSR;
grant select, insert, update on ct.ec_questionnaire to CSR;
grant select, insert, update on ct.ec_questionnaire_answers to CSR;
grant select, insert, update on ct.ec_train_entry to CSR;
grant select, insert, update on ct.hotspot_result to CSR;
grant select, insert, update on ct.ht_consumption to CSR;
grant select, insert, update on ct.ht_consumption_region to CSR;
grant select, insert, update on ct.ht_cons_source_breakdown to CSR;
grant select, insert, update on ct.ps_emissions_all to CSR;
grant select, insert, update on ct.supplier to CSR;
grant select, insert, update on ct.ps_item to CSR;
grant select, insert, update on ct.ps_item_eio to CSR;
grant select, insert, update on ct.ps_options to CSR;
grant select, insert, update on ct.ps_spend_breakdown to CSR;
grant select, insert, update on ct.ps_supplier_eio_freq to CSR;
grant select, insert, update on ct.supplier_contact to CSR;
grant select, insert, update on ct.up_options to CSR;
grant select, insert, update on ct.worksheet_value_map_breakdown to CSR;
grant select, insert, update on ct.worksheet_value_map_currency to CSR;
grant select, insert, update on ct.worksheet_value_map_distance to CSR;
grant select, insert, update on ct.worksheet_value_map_region to CSR;
grant select, insert, update on ct.worksheet_value_map_supplier to CSR;

grant select on ct.breakdown_id_seq to CSR;
grant select on ct.breakdown_type_id_seq to CSR;
grant select on ct.breakdown_group_id_seq to CSR;
grant select on ct.bt_trip_entry_id_seq to CSR;
grant select on ct.ec_questionnaire_id_seq to CSR;
grant select on ct.ec_questionnaire_ans_id_seq to CSR;
grant select on ct.ps_item_id_seq to CSR;
grant select on ct.supplier_id_seq to CSR;
grant select on ct.supplier_contact_id_seq to CSR;

grant select on csr.meter_bucket_id_seq to csrimp;
grant select,insert,update on csr.meter_data_priority to csrimp;
grant select,insert,update on csr.meter_patch_data to csrimp;
grant select,insert,update on csr.meter_input to csrimp;
grant select,insert,update on csr.meter_input_aggr_ind to csrimp;
grant select,insert,update on csr.meter_input_aggregator to csrimp;
grant select,insert,update on csr.meter_patch_job to csrimp;
grant select,insert,update on csr.meter_patch_batch_job to csrimp;
grant select,insert,update on csr.meter_data_coverage_ind to csrimp;

grant select, insert, update on csr.customer_file_upload_type_opt to csrimp;
grant select, insert, update on csr.customer_file_upload_mime_opt to csrimp;

grant select, insert, update on csr.meter_type_input to csrimp;

grant insert on csr.flow_alert_helper to csrimp;
grant insert on csr.issue_custom_field_date_val to csrimp;
grant insert on csr.quick_survey_score_threshold to csrimp;
grant insert on csr.quick_survey_css to csrimp;
grant insert on csr.supplier_survey_response to csrimp;

grant select, insert, update on csr.image_upload_portlet to csrimp;

grant select on csr.image_upload_portlet_seq to csrimp;


grant select, insert, update on csr.r_report_type to csrimp;
grant select, insert, update on csr.r_report to csrimp;
grant select, insert, update on csr.r_report_file to csrimp;
grant select on csr.r_report_type_id_seq to csrimp;
grant select on csr.r_report_file_id_seq to csrimp;


grant select, insert, update on csr.gresb_indicator_mapping to csrimp;
grant select, insert, update on csr.gresb_submission_log to csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.property_gresb TO csrimp;
grant select, insert, update on csr.property_fund to csrimp;
grant select, insert, update on csr.property_fund_ownership to csrimp;
grant select on csr.gresb_submission_seq to csrimp;
grant select, insert, update on csr.mgt_company_tree_sync_job to csrimp;

grant select, insert, update on csr.aggregation_period to csrimp;
grant select, insert, update on chain.dedupe_processed_record to csrimp;
grant select, insert, update on chain.dedupe_match to csrimp;


grant select on chain.dedupe_processed_record_id_seq to csrimp;
grant select on chain.dedupe_match_id_seq to csrimp;
GRANT SELECT ON chain.dedupe_sub TO csrimp;

grant select, insert, update on csr.geo_map to csrimp;
grant select, insert, update on csr.geo_map_region to csrimp;
grant select, insert, update on csr.degreeday_settings to csrimp;
grant select, insert, update on csr.degreeday_region to csrimp;

grant select, insert, update on csr.initiative to csrimp;
grant select, insert, update on csr.initiative_metric to csrimp;
grant select, insert, update on csr.initiative_project to csrimp;
grant select, insert, update on csr.initiative_project_rag_status to csrimp;
grant select, insert, update on csr.customer_init_saving_type to csrimp;
grant select, insert, update on csr.initiative_metric_group to csrimp;
grant select, insert, update on csr.project_initiative_metric to csrimp;
grant select, insert, update on csr.initiative_metric_assoc to csrimp;
grant select, insert, update on csr.project_init_metric_flow_state to csrimp;
grant select, insert, update on csr.initiative_metric_state_ind to csrimp;
grant select, insert, update on csr.aggr_tag_group to csrimp;
grant select, insert, update on csr.initiative_metric_tag_ind to csrimp;
grant select, insert, update on csr.aggr_tag_group_member to csrimp;
grant select, insert, update on csr.flow_state_group to csrimp;
grant select, insert, update on csr.flow_state_group_member to csrimp;
grant select, insert, update on csr.initiative_comment to csrimp;
grant select, insert, update on csr.initiative_event to csrimp;
grant select, insert, update on csr.initiative_group to csrimp;
grant select, insert, update on csr.initiative_group_flow_state to csrimp;
grant select, insert, update on csr.initiative_group_member to csrimp;
grant select, insert, update on csr.initiative_group_user to csrimp;
grant select, insert, update on csr.initiative_import_map_mru to csrimp;
grant select, insert, update on csr.initiative_import_template to csrimp;
grant select, insert, update on csr.initiative_import_template_map to csrimp;
grant select, insert, update on csr.initiative_metric_val to csrimp;
grant select, insert, update on csr.initiative_period_status to csrimp;
grant select, insert, update on csr.initiative_period to csrimp;
grant select, insert, update on csr.initiative_project_tab to csrimp;
grant select, insert, update on csr.initiative_project_tab_group to csrimp;
grant select, insert, update on csr.initiative_project_team to csrimp;
grant select, insert, update on csr.initiative_region to csrimp;
grant select, insert, update on csr.initiative_sponsor to csrimp;
grant select, insert, update on csr.initiative_tag to csrimp;
grant select, insert, update on csr.initiative_user_group to csrimp;
grant select, insert, update on csr.initiative_project_user_group to csrimp;
grant select, insert, update on csr.initiative_user to csrimp;
grant select, insert, update on csr.initiative_user_msg to csrimp;
grant select, insert, update on csr.initiatives_options to csrimp;
grant select, insert, update on csr.user_msg to csrimp;
grant select, insert, update on csr.project_initiative_period_stat to csrimp;
grant select, insert, update on csr.default_initiative_user_state to csrimp;
grant select, insert, update on csr.issue_initiative to csrimp;
grant select, insert, update on csr.aggr_region to csrimp;
grant select, insert, update on csr.alert_batch_run to csrimp;
grant select, insert, update on csr.customer_flow_alert_class to csrimp;
grant select, insert, update on csr.project_doc_folder to csrimp;
grant select, insert, update on csr.project_tag_group to csrimp;
grant select, insert, update on csr.project_tag_filter to csrimp;
grant select, insert, update on csr.init_tab_element_layout to csrimp;
grant select, insert, update on csr.init_create_page_el_layout to csrimp;
grant select, insert, update on csr.initiative_header_element to csrimp;

grant select on csr.initiative_metric_id_seq to csrimp;
grant select on csr.aggr_tag_group_id_seq to csrimp;
grant select on csr.flow_state_group_id_seq to csrimp;
grant select on csr.initiative_group_id_seq to csrimp;
grant select on csr.initiative_user_group_id_seq to csrimp;
grant select on csr.init_import_template_id_seq to csrimp;
grant select on csr.initiativ_period_status_id_seq to csrimp;
grant select on csr.initiative_comment_id_seq to csrimp;
grant select on csr.user_msg_id_seq to csrimp;
grant select on csr.issue_initiative_id_seq to csrimp;
grant select on csr.initiative_event_id_seq to csrimp;
grant select on csr.initiative_tab_element_id_seq to csrimp;
grant select on csr.init_create_page_el_id_seq to csrimp;
grant select on csr.init_header_element_id_seq to csrimp;

GRANT SELECT, INSERT, UPDATE ON csr.custom_factor_set TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.custom_factor TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.emission_factor_profile TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.emission_factor_profile_factor TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.std_factor_set_active TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_options TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_language TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_item_region TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.flow_item_audit_log TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_req_reg TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_regulation TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_requirement TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_item_tag TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_item TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_region_tag TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_root_regions TO csrimp;
grant select, insert, update on csr.compliance_activity_type to csrimp;
grant select, insert, update on csr.compliance_activity_sub_type to csrimp;
grant select, insert, update on csr.compliance_application_type to csrimp;
grant select, insert, update on csr.compliance_condition_sub_type to csrimp;
grant select, insert, update on csr.compliance_condition_type to csrimp;
grant select, insert, update on csr.compliance_item_rollout to csrimp;
grant select, insert, update on csr.compliance_permit to csrimp;
grant select, insert, update on csr.compliance_permit_application to csrimp;
grant select, insert, update on csr.compl_permit_application_pause to csrimp;
grant select, insert, update on csr.compliance_permit_condition to csrimp;
grant select, insert, update on csr.compliance_permit_sub_type to csrimp;
grant select, insert, update on csr.compliance_permit_type to csrimp;
grant select, insert, update on csr.compliance_permit_tab to csrimp;
grant select, insert, update on csr.compliance_permit_tab_group to csrimp;
grant select, insert, update on csr.compliance_permit_history to csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_item_description TO csrimp;
grant select on csr.compliance_activity_type_seq to csrimp;
grant select on csr.compliance_application_tp_seq to csrimp;
grant select on csr.compliance_cond_sub_type_seq to csrimp;
grant select on csr.compliance_condition_type_seq to csrimp;
grant select on csr.compliance_permit_appl_seq to csrimp;
grant select on csr.compliance_permit_seq to csrimp;
grant select on csr.compliance_permit_sub_type_seq to csrimp;
grant select on csr.compliance_permit_type_seq to csrimp;
GRANT SELECT ON csr.compliance_activ_sub_type_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.enhesa_options TO csrimp;
GRANT SELECT ON csr.enhesa_error_log_id_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.enhesa_error_log TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.enhesa_site_type TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.enhesa_site_type_heading TO csrimp;
GRANT SELECT ON csr.enhesa_site_type_id_seq TO csrimp;
GRANT SELECT ON csr.enhesa_site_typ_heading_id_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.comp_item_region_sched_issue TO csrimp;
GRANT SELECT ON csr.compliance_lang_id_seq to csrimp;
GRANT SELECT ON csr.compliance_item_seq TO csrimp;
GRANT SELECT ON csr.compliance_item_rollout_id_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_item_version_log TO csrimp;
GRANT SELECT ON csr.comp_item_version_log_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_audit_log TO csrimp;
GRANT SELECT ON csr.compliance_audit_log_id_seq TO csrimp;
GRANT SELECT ON csr.flow_item_audit_log_id_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.compliance_item_desc_hist TO csrimp;
GRANT SELECT ON csr.compliance_item_desc_hist_seq TO csrimp;

GRANT SELECT, INSERT, UPDATE ON csr.doc_type TO csrimp;
GRANT SELECT ON csr.doc_type_id_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.property_mandatory_roles TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.forecasting_rule TO csrimp;

grant select, insert, update on csr.aggregate_ind_val_detail to csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.duff_meter_region TO csrimp;
grant select, insert, update on csr.chain_tpl_delegation to csrimp;
grant select, insert, update on csr.customer_flow_alert_class to csrimp;
grant select, insert, update on csr.customer_geo_map_tab_type to csrimp;
grant select, insert, update on csr.customer_help_lang to csrimp;
grant select, insert, update on csr.img_chart_region to csrimp;
grant select, insert, update on csr.ind_set to csrimp;
grant select, insert, update on csr.ind_set_ind to csrimp;
grant select, insert, update on csr.ind_window to csrimp;
grant select, insert, update on csr.issue_alert to csrimp;
grant select, insert, update on csr.issue_meter_missing_data to csrimp;
grant select, insert, update on csr.route_log to csrimp;
grant select, insert, update on csr.route_step_vote to csrimp;
grant select, insert, update on csr.sheet_change_req to csrimp;
grant select, insert, update on csr.sheet_change_req_alert to csrimp;
grant select, insert, update on csr.sheet_value_change_file to csrimp;
grant select, insert, update on csr.supplier_delegation to csrimp;
grant select, insert, update on csr.user_msg_file to csrimp;
grant select, insert, update on csr.val_file to csrimp;
grant select, insert, update on csr.val_note to csrimp;

grant select on csr.ind_set_id_seq to csrimp;
grant select on csr.issue_meter_missing_data_seq to csrimp;
grant select on csr.route_log_id_seq to csrimp;
grant select on csr.sheet_change_req_id_seq to csrimp;
grant select on csr.sheet_change_req_alert_id_seq to csrimp;
grant select on csr.user_msg_file_id_seq to csrimp;
grant select on csr.val_note_id_seq to csrimp;

grant select, insert, update on csr.calendar to csrimp;
grant select, insert, update on csr.calendar_event to csrimp;
grant select, insert, update on csr.calendar_event_invite to csrimp;
grant select, insert, update on csr.calendar_event_owner to csrimp;
grant select, insert, update on csr.client_util_script to csrimp;
grant select, insert, update on csr.client_util_script_param to csrimp;
grant select, insert, update on csr.util_script_run_log to csrimp;

grant select on csr.calendar_event_id_seq to csrimp;
grant select on csr.client_util_script_id_seq to csrimp;

grant select, insert, update on csr.scenario_email_sub TO csrimp;
grant select, insert, update on csr.internal_audit_score to csrimp;
GRANT SELECT ON csr.schema_column TO csrimp;
GRANT SELECT ON csr.schema_table TO csrimp;
grant select, insert, update on csr.score_type_audit_type to csrimp;
GRANT INSERT ON csr.compliance_rollout_regions TO csrimp;

GRANT SELECT, INSERT, UPDATE ON csr.compliance_permit_score TO csrimp;
GRANT SELECT ON CSR.COMPLIANCE_PERMIT_SCORE_ID_SEQ TO csrimp;
grant select, insert, update on csr.compliance_permit_header to csrimp;
grant select, insert, update on csr.compliance_permit_header_group to csrimp;

GRANT SELECT, INSERT, UPDATE ON csr.intapi_company_user_group TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.secondary_region_tree_ctrl TO csrimp;
GRANT INSERT ON csr.secondary_region_tree_log TO csrimp;

grant select, insert, update on csr.issue_template to csrimp;
grant select, insert, update on csr.issue_template_custom_field to csrimp;
grant select, insert, update on csr.issue_template_cust_field_opt to csrimp;

grant select on csr.issue_template_id_seq to csrimp;

grant select on csr.core_working_hours_id_seq to csrimp;
grant select, insert, update on csr.core_working_hours to csrimp;
grant select, insert, update on csr.core_working_hours_day to csrimp;
grant select, insert, update on csr.core_working_hours_region to csrimp;

grant select,insert, update on csr.osha_mapping to csrimp;
grant select,insert, update on csr.osha_config to csrimp;
GRANT SELECT ON csr.scndry_region_tree_log_id_seq TO csrimp;

grant select on csr.sys_trans_audit_log_seq to csrimp;
grant select,insert, update on csr.sys_translations_audit_log to csrimp;
grant select,insert, update on csr.sys_translations_audit_data to csrimp;

grant insert on campaigns.campaign to csrimp;
grant insert on campaigns.campaign_region to csrimp;
grant insert on campaigns.campaign_region_response to csrimp;

grant select,insert, update on csr.internal_audit_listener_last_update to csrimp;

grant select,insert, update on csr.credential_management to csrimp;
grant select,insert, update on csr.integration_question_answer to csrimp;
grant select,insert, update on csr.region_certificate to csrimp;
grant select on csr.region_certificate_id_seq to csrimp;
grant select,insert, update on csr.region_energy_rating to csrimp;
grant select,insert, update on csr.module_history to csrimp;

grant select,insert,update,delete on csr.baseline_config to csrimp;
grant select,insert,update,delete on csr.baseline_config_period to csrimp;
grant select,insert,update,delete on csr.calc_baseline_config_dependency to csrimp;
