grant execute on csrimp.imp_pkg to tool_user;

-- select 'grant insert,select,update,delete on csrimp.'||lower(table_name)||' to tool_user;' 
-- from all_tables where owner='CSRIMP' and table_name not like 'MAP_%' and table_name!='version' and temporary='Y' order by lower(table_name);

-- temporary tables
grant insert,select,update,delete on csrimp.account_policy to tool_user;
grant insert,select,update,delete on csrimp.acc_policy_pwd_regexp to tool_user;
grant insert,select,update,delete on csrimp.accuracy_type to tool_user;
grant insert,select,update,delete on csrimp.accuracy_type_option to tool_user;
grant insert,select,update,delete on csrimp.acl to tool_user;
grant select,insert,update,delete on csrimp.aggregate_ind_group to tool_user;
grant select,insert,update,delete on csrimp.aggregate_ind_group_member to tool_user;
grant select,insert,update,delete on csrimp.aggregate_ind_group_audit_log to tool_user;
grant select,insert,update,delete on csrimp.aggregation_period TO tool_user;
grant insert,select,update,delete on csrimp.application to tool_user;
grant insert,select,update,delete on csrimp.alert to tool_user;
grant insert,select,update,delete on csrimp.alert_bounce to tool_user;
grant insert,select,update,delete on csrimp.alert_frame to tool_user;
grant insert,select,update,delete on csrimp.alert_frame_body to tool_user;
grant insert,select,update,delete on csrimp.alert_template to tool_user;
grant insert,select,update,delete on csrimp.alert_template_body to tool_user;
grant select,insert,update,delete on csrimp.all_meter to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_alert_type to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_ind to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_instance to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_region to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_tab to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_tpl_tag to tool_user;
grant select,insert,update,delete on csrimp.approval_dashboard_val to tool_user;
grant select,insert,update,delete on csrimp.approval_note_portlet_note to tool_user;
grant insert,select,update,delete on csrimp.approval_step to tool_user;
grant insert,select,update,delete on csrimp.approval_step_ind to tool_user;
grant insert,select,update,delete on csrimp.approval_step_region to tool_user;
grant insert,select,update,delete on csrimp.approval_step_role to tool_user;
grant insert,select,update,delete on csrimp.approval_step_sheet to tool_user;
grant insert,select,update,delete on csrimp.approval_step_sheet_log to tool_user;
grant insert,select,update,delete on csrimp.approval_step_user to tool_user;
grant insert,select,update,delete on csrimp.aspen2_application to tool_user;
grant insert,select,update,delete on csrimp.aspen2_translated to tool_user;
grant insert,select,update,delete on csrimp.aspen2_translation to tool_user;
grant insert,select,update,delete on csrimp.aspen2_translation_app to tool_user;
grant insert,select,update,delete on csrimp.aspen2_translation_set to tool_user;
grant insert,select,update,delete on csrimp.aspen2_translation_set_incl to tool_user;
grant insert,select,update,delete on csrimp.attachment to tool_user;
grant insert,select,update,delete on csrimp.attachment_history to tool_user;
grant insert,select,update,delete on csrimp.attributes to tool_user;
grant select,insert,update,delete on csrimp.autocreate_user to tool_user;
grant select,insert,update,delete on csrimp.audit_alert to tool_user;
grant select,insert,update,delete on csrimp.audit_closure_type to tool_user;
grant select,insert,update,delete on csrimp.audit_type_closure_type to tool_user;
grant select,insert,update,delete on csrimp.audit_log to tool_user;
grant select,insert,update,delete on csrimp.audit_non_compliance to tool_user;
grant select,insert,update,delete on csrimp.audit_type_non_comp_default to tool_user;
grant select,insert,update,delete on csrimp.audit_user_cover to tool_user;
grant select,insert,update,delete on csrimp.audit_type_expiry_alert_role to tool_user;
grant select,insert,update,delete on csrimp.audit_type_tab to tool_user;
grant select,insert,update,delete on csrimp.audit_type_header to tool_user;
grant select,insert,update,delete on csrimp.audit_type_flow_inv_type to tool_user;
grant select,insert,update,delete on csrimp.batch_job_approval_dash_vals to tool_user;
grant insert,select,update,delete on csrimp.calc_dependency to tool_user;
grant select,insert,update,delete on csrimp.calc_tag_dependency to tool_user;
grant select,insert,update,delete on csrimp.calc_baseline_config_dependency to tool_user;
grant select,insert,update,delete on csrimp.correspondent to tool_user;
grant select,insert,update,delete on csrimp.cms_aggregate_type to tool_user;
grant select,insert,update,delete on csrimp.cms_alert_helper to tool_user;
grant select,insert,update,delete on csrimp.cms_alert_type to tool_user;
grant select,insert,update,delete on csrimp.cms_app_schema to tool_user;
grant select,insert,update,delete on csrimp.cms_app_schema_table to tool_user;
--grant select,insert,update,delete on csrimp.cms_context to tool_user;
--grant select,insert,update,delete on csrimp.cms_fast_context to tool_user;
grant select,insert,update,delete on csrimp.cms_image to tool_user;
--grant select,insert,update,delete on csrimp.cms_securable_object_whitelist to tool_user;
grant select,insert,update,delete on csrimp.cms_ck_cons to tool_user;
grant select,insert,update,delete on csrimp.cms_ck_cons_col to tool_user;
grant select,insert,update,delete on csrimp.cms_data_helper to tool_user;
grant select,insert,update,delete on csrimp.cms_display_template  to tool_user;
grant select,insert,update,delete on csrimp.cms_doc_template  to tool_user;
grant select,insert,update,delete on csrimp.cms_doc_template_file  to tool_user;
grant select,insert,update,delete on csrimp.cms_doc_template_version  to tool_user;
grant select,insert,update,delete on csrimp.cms_filter to tool_user;
grant select,insert,update,delete on csrimp.cms_fk_cons to tool_user;
grant select,insert,update,delete on csrimp.cms_fk_cons_col to tool_user;
grant select,insert,update,delete on csrimp.cms_flow_tab_column_cons to tool_user;
grant select,insert,update,delete on csrimp.cms_form to tool_user;
grant select,insert,update,delete on csrimp.cms_form_version to tool_user;
grant select,insert,update,delete on csrimp.cms_image_tag to tool_user;
grant select,insert,update,delete on csrimp.cms_link_track to tool_user;
grant select,insert,update,delete on csrimp.cms_tab to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_column to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_column_link to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_column_link_type to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_column_measure to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_aggregate_ind to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_issue_aggregate_ind to tool_user;
grant select,insert,update,delete on csrimp.cms_tag to tool_user;
grant select,insert,update,delete on csrimp.cms_uk_cons to tool_user;
grant select,insert,update,delete on csrimp.cms_uk_cons_col to tool_user;
grant select,insert,update,delete on csrimp.cms_web_publication to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_column_role_permission to tool_user;
grant select,insert,update,delete on csrimp.cms_tab_alert_type to tool_user;
grant select,insert,update,delete on csrimp.cms_enum_group to tool_user;
grant select,insert,update,delete on csrimp.cms_enum_group_member to tool_user;
grant select,insert,update,delete on csrimp.cms_enum_group_tab to tool_user;
grant insert,select,update,delete on csrimp.csr_user to tool_user;
grant select,insert,update,delete on csrimp.current_supplier_score to tool_user;
grant select,insert,update,delete on csrimp.supplier_score_log to tool_user;
grant insert,select,update,delete on csrimp.customer to tool_user;
grant insert,select,update,delete on csrimp.customer_alert_type to tool_user;
grant select,insert,update,delete on csrimp.customer_alert_type_param to tool_user;
grant select,insert,update,delete on csrimp.customer_portlet to tool_user;
grant insert,select,update,delete on csrimp.customer_region_type to tool_user;
grant select,insert,update,delete on csrimp.dashboard to tool_user;
grant select,insert,update,delete on csrimp.dashboard_item to tool_user;
grant select,insert,update,delete on csrimp.data_bucket to tool_user;
grant insert,select,update,delete on csrimp.dataview to tool_user;
grant insert,select,update,delete on csrimp.dataview_arbitrary_period to tool_user;
grant insert,select,update,delete on csrimp.dataview_arbitrary_period_hist to tool_user;
grant insert,select,update,delete on csrimp.dataview_ind_description to tool_user;
grant insert,select,update,delete on csrimp.dataview_ind_member to tool_user;
grant insert,select,update,delete on csrimp.dataview_region_member to tool_user;
grant insert,select,update,delete on csrimp.dataview_region_description to tool_user;
grant select,insert,update,delete on csrimp.dataview_scenario_run to tool_user;
grant insert,select,update,delete on csrimp.dataview_trend to tool_user;
grant select,insert,update,delete on csrimp.dataview_zone to tool_user;
grant select,insert,update,delete on csrimp.dataview_history to tool_user;
grant select,insert,update,delete on csrimp.deleg_grid_variance to tool_user;
grant insert,select,update,delete on csrimp.deleg_ind_group_member to tool_user;
grant insert,select,update,delete on csrimp.deleg_ind_form_expr to tool_user;
grant insert,select,update,delete on csrimp.deleg_ind_group to tool_user;
grant select,insert,update,delete on csrimp.deleg_meta_role_ind_selection to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_applied to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_col to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_col_deleg to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_col_survey to tool_user;
grant select,insert,update,delete on csrimp.deleg_plan_date_schedule to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_deleg_region to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_deleg_region_deleg to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_region to tool_user;
grant insert,select,update,delete on csrimp.deleg_plan_role to tool_user;
grant insert,select,update,delete on csrimp.delegation to tool_user;
grant select,insert,update,delete on csrimp.delegation_comment to tool_user;
grant insert,select,update,delete on csrimp.delegation_description to tool_user;
grant select,insert,update,delete on csrimp.delegation_date_schedule to tool_user;
grant insert,select,update,delete on csrimp.delegation_grid to tool_user;
grant insert,select,update,delete on csrimp.delegation_grid_aggregate_ind to tool_user;
grant insert,select,update,delete on csrimp.delegation_ind to tool_user;
grant insert,select,update,delete on csrimp.delegation_ind_cond to tool_user;
grant insert,select,update,delete on csrimp.delegation_ind_cond_action to tool_user;
grant insert,select,update,delete on csrimp.delegation_ind_description to tool_user;
grant insert,select,update,delete on csrimp.delegation_ind_tag to tool_user;
grant insert,select,update,delete on csrimp.delegation_ind_tag_list to tool_user;
grant insert,select,update,delete on csrimp.delegation_region to tool_user;
grant insert,select,update,delete on csrimp.delegation_region_description to tool_user;
grant insert,select,update,delete on csrimp.delegation_role to tool_user;
grant insert,select,update,delete on csrimp.delegation_user to tool_user;
grant select,insert,update,delete on csrimp.delegation_plugin to tool_user;
grant select,insert,update,delete on csrimp.delegation_tag to tool_user;
grant select,insert,update,delete on csrimp.delegation_user_cover to tool_user;
grant select,insert,update,delete on csrimp.delegation_policy to tool_user;
grant select,insert,update,delete on csrimp.doc to tool_user;
grant select,insert,update,delete on csrimp.doc_current to tool_user;
grant select,insert,update,delete on csrimp.doc_data to tool_user;
grant select,insert,update,delete on csrimp.doc_download to tool_user;
grant select,insert,update,delete on csrimp.doc_folder to tool_user;
grant select,insert,update,delete on csrimp.doc_folder_subscription to tool_user;
grant select,insert,update,delete on csrimp.doc_library to tool_user;
grant select,insert,update,delete on csrimp.doc_notification to tool_user;
grant select,insert,update,delete on csrimp.doc_subscription to tool_user;
grant select,insert,update,delete on csrimp.doc_version to tool_user;
grant select,insert,update,delete on csrimp.doc_folder_name_translation to tool_user;
grant select,insert,update,delete on csrimp.event to tool_user;
grant select,insert,update,delete on csrimp.excel_export_options to tool_user;
grant select,insert,update,delete on csrimp.excel_export_options_tag_group to tool_user;
grant insert,select,update,delete on csrimp.factor to tool_user;
grant select,insert,update,delete on csrimp.factor_history to tool_user;
grant select,insert,update,delete on csrimp.forecasting_rule to tool_user;
grant insert,select,update,delete on csrimp.file_upload to tool_user;
grant select,insert,update,delete on csrimp.flow to tool_user;
grant select,insert,update,delete on csrimp.flow_alert_type to tool_user;
grant select,insert,update,delete on csrimp.flow_alert_helper to tool_user;
grant select,insert,update,delete on csrimp.flow_item to tool_user;
grant select,insert,update,delete on csrimp.flow_item_region to tool_user;
grant select,insert,update,delete on csrimp.flow_item_involvement to tool_user;
grant select,insert,update,delete on csrimp.flow_item_generated_alert to tool_user;
grant select,insert,update,delete on csrimp.flow_involvement_cover to tool_user;
grant select,insert,update,delete on csrimp.flow_involvement_type to tool_user;
grant select,insert,update,delete on csrimp.flow_inv_type_alert_class to tool_user;
grant select,insert,update,delete on csrimp.flow_state to tool_user;
grant select,insert,update,delete on csrimp.flow_state_log to tool_user;
grant select,insert,update,delete on csrimp.flow_state_log_file to tool_user;
grant select,insert,update,delete on csrimp.flow_state_role to tool_user;
grant select,insert,update,delete on csrimp.flow_state_cms_col to tool_user;
grant select,insert,update,delete on csrimp.flow_state_involvement to tool_user;
grant select,insert,update,delete on csrimp.flow_state_role_capability to tool_user;
grant select,insert,update,delete on csrimp.flow_state_survey_tag to tool_user;
grant select,insert,update,delete on csrimp.flow_state_trans_helper to tool_user;
grant select,insert,update,delete on csrimp.flow_state_transition to tool_user;
grant select,insert,update,delete on csrimp.flow_state_transition_role to tool_user;
grant select,insert,update,delete on csrimp.flow_state_transition_cms_col to tool_user;
grant select,insert,update,delete on csrimp.flow_state_transition_inv to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert_cms_col to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert_role to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert_cc_role to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert_inv to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert_user to tool_user;
grant select,insert,update,delete on csrimp.flow_transition_alert_cc_user to tool_user;
grant insert,select,update,delete on csrimp.form to tool_user;
grant insert,select,update,delete on csrimp.form_allocation to tool_user;
grant insert,select,update,delete on csrimp.form_allocation_item to tool_user;
grant insert,select,update,delete on csrimp.form_allocation_user to tool_user;
grant insert,select,update,delete on csrimp.form_comment to tool_user;
grant insert,select,update,delete on csrimp.form_expr to tool_user;
grant insert,select,update,delete on csrimp.form_ind_member to tool_user;
grant insert,select,update,delete on csrimp.form_region_member to tool_user;
grant insert,select,update,delete on csrimp.group_members to tool_user;
grant insert,select,update,delete on csrimp.group_table to tool_user;
grant select,insert,update,delete on csrimp.group_user_cover to tool_user;
grant insert,select,update,delete on csrimp.home_page to tool_user;
grant insert,select,update,delete on csrimp.img_chart to tool_user;
grant insert,select,update,delete on csrimp.img_chart_ind to tool_user;
grant insert,select,update,delete on csrimp.imp_conflict to tool_user;
grant insert,select,update,delete on csrimp.imp_conflict_val to tool_user;
grant insert,select,update,delete on csrimp.imp_ind to tool_user;
grant insert,select,update,delete on csrimp.imp_measure to tool_user;
grant insert,select,update,delete on csrimp.imp_region to tool_user;
grant insert,select,update,delete on csrimp.imp_session to tool_user;
grant insert,select,update,delete on csrimp.imp_val to tool_user;
grant select,insert,update,delete on csrimp.imp_vocab to tool_user;
grant select,insert,update,delete on csrimp.incident_type to tool_user;
grant insert,select,update,delete on csrimp.ind to tool_user;
grant insert,select,update,delete on csrimp.ind_description to tool_user;
grant insert,select,update,delete on csrimp.ind_accuracy_type to tool_user;
grant insert,select,update,delete on csrimp.ind_flag to tool_user;
grant insert,select,update,delete on csrimp.ind_start_point to tool_user;
grant select,insert,update,delete on csrimp.ind_sel_group_member_desc to tool_user;
grant select,insert,update,delete on csrimp.ind_selection_group to tool_user;
grant select,insert,update,delete on csrimp.ind_selection_group_member to tool_user;
grant insert,select,update,delete on csrimp.ind_tag to tool_user;
grant insert,select,update,delete on csrimp.ind_validation_rule to tool_user;
grant select,insert,update,delete on csrimp.internal_audit to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_file to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_file_data to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_postit to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_type_report to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_type to tool_user;
grant select,insert,update,delete on csrimp.flow_state_audit_ind to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_type_group to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_type_carry_fwd to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_type_report to tool_user;
grant select,insert,update,delete on csrimp.ia_type_report_group to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_locked_tag to tool_user;
grant select,insert,update,delete on csrimp.internal_audit_listener_last_update to tool_user;
grant insert,select,update,delete on csrimp.ip_rule to tool_user;
grant insert,select,update,delete on csrimp.ip_rule_entry to tool_user;
grant select,insert,update,delete on csrimp.issue to tool_user;
grant select,insert,update,delete on csrimp.issue_action to tool_user;
grant select,insert,update,delete on csrimp.issue_action_log to tool_user;
grant select,insert,update,delete on csrimp.issue_compliance_region to tool_user;
grant select,insert,update,delete on csrimp.issue_custom_field to tool_user;
grant select,insert,update,delete on csrimp.issue_custom_field_opt_sel to tool_user;
grant select,insert,update,delete on csrimp.issue_custom_field_option to tool_user;
grant select,insert,update,delete on csrimp.issue_custom_field_str_val to tool_user;
grant select,insert,update,delete on csrimp.issue_due_source to tool_user;
grant select,insert,update,delete on csrimp.issue_log to tool_user;
grant select,insert,update,delete on csrimp.issue_log_file to tool_user;
grant select,insert,update,delete on csrimp.issue_log_read to tool_user;
grant select,insert,update,delete on csrimp.issue_meter to tool_user;
grant select,insert,update,delete on csrimp.issue_meter_alarm to tool_user;
grant select,insert,update,delete on csrimp.issue_meter_data_source to tool_user;
grant select,insert,update,delete on csrimp.issue_meter_raw_data to tool_user;
grant select,insert,update,delete on csrimp.issue_non_compliance to tool_user;
grant select,insert,update,delete on csrimp.issue_pending_val to tool_user;
grant select,insert,update,delete on csrimp.issue_priority to tool_user;
grant select,insert,update,delete on csrimp.issue_scheduled_task to tool_user;
grant select,insert,update,delete on csrimp.issue_sheet_value to tool_user;
grant select,insert,update,delete on csrimp.issue_supplier to tool_user;
grant select,insert,update,delete on csrimp.issue_survey_answer to tool_user;
grant select,insert,update,delete on csrimp.issue_type to tool_user;
grant select,insert,update,delete on csrimp.issue_type_aggregate_ind_grp to tool_user;
grant select,insert,update,delete on csrimp.issue_involvement to tool_user;
grant select,insert,update,delete on csrimp.issue_user_cover to tool_user;
grant insert,select,update,delete on csrimp.known_so to tool_user;
grant select,insert,update,delete on csrimp.user_measure_conversion to tool_user;
grant select,insert,update,delete on csrimp.lookup_table to tool_user;
grant select,insert,update,delete on csrimp.lookup_table_entry to tool_user;
grant select,insert,update,delete on csrimp.meter_bucket to tool_user;
grant insert,select,update,delete on csrimp.mail_account to tool_user;
grant insert,select,update,delete on csrimp.mail_mailbox to tool_user;
grant insert,select,update,delete on csrimp.mail_mailbox_message to tool_user;
grant insert,select,update,delete on csrimp.mail_message to tool_user;
grant insert,select,update,delete on csrimp.mail_message_address_field to tool_user;
grant insert,select,update,delete on csrimp.mail_message_header to tool_user;
grant insert,select,update,delete on csrimp.master_deleg to tool_user;
grant insert,select,update,delete on csrimp.measure to tool_user;
grant insert,select,update,delete on csrimp.measure_conversion to tool_user;
grant insert,select,update,delete on csrimp.measure_conversion_period to tool_user;
grant insert,select,update,delete on csrimp.menu to tool_user;
grant select,insert,update,delete on csrimp.meter_aggregate_type to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_comparison to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_event to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_issue_period to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_stat_run to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_statistic to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_statistic_job to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_statistic_period to tool_user;
grant select,insert,update,delete on csrimp.meter_alarm_test_time to tool_user;
grant select,insert,update,delete on csrimp.meter_document to tool_user;
grant select,insert,update,delete on csrimp.meter_element_layout to tool_user;
grant select,insert,update,delete on csrimp.meter_excel_mapping to tool_user;
grant select,insert,update,delete on csrimp.meter_excel_option to tool_user;
grant select,insert,update,delete on csrimp.meter_header_element to tool_user;
grant select,insert,update,delete on csrimp.meter_list_cache to tool_user;
grant select,insert,update,delete on csrimp.meter_live_data to tool_user;
grant select,insert,update,delete on csrimp.meter_meter_alarm_statistic to tool_user;
grant select,insert,update,delete on csrimp.meter_orphan_data to tool_user;
grant select,insert,update,delete on csrimp.meter_photo to tool_user;
grant select,insert,update,delete on csrimp.meter_raw_data to tool_user;
grant select,insert,update,delete on csrimp.meter_raw_data_error to tool_user;
grant select,insert,update,delete on csrimp.meter_raw_data_source to tool_user;
grant select,insert,update,delete on csrimp.meter_raw_data_status to tool_user;
grant select,insert,update,delete on csrimp.meter_reading to tool_user;
grant select,insert,update,delete on csrimp.meter_source_data to tool_user;
grant select,insert,update,delete on csrimp.meter_reading_data to tool_user;
grant select,insert,update,delete on csrimp.meter_source_type to tool_user;
grant select,insert,update,delete on csrimp.meter_tab to tool_user;
grant select,insert,update,delete on csrimp.meter_tab_group to tool_user;
grant select,insert,update,delete on csrimp.meter_utility_contract to tool_user;
grant select,insert,update,delete on csrimp.metering_options to tool_user;
grant select,insert,update,delete on csrimp.meter_xml_option to tool_user;
grant select,insert,update,delete on csrimp.model to tool_user;
grant select,insert,update,delete on csrimp.model_instance to tool_user;
grant select,insert,update,delete on csrimp.model_instance_chart to tool_user;
grant select,insert,update,delete on csrimp.model_instance_map to tool_user;
grant select,insert,update,delete on csrimp.model_instance_region to tool_user;
grant select,insert,update,delete on csrimp.model_instance_sheet to tool_user;
grant select,insert,update,delete on csrimp.model_map to tool_user;
grant select,insert,update,delete on csrimp.model_range to tool_user;
grant select,insert,update,delete on csrimp.model_range_cell to tool_user;
grant select,insert,update,delete on csrimp.model_region_range to tool_user;
grant select,insert,update,delete on csrimp.model_sheet to tool_user;
grant select,insert,update,delete on csrimp.model_validation to tool_user;
grant select,insert,update,delete on csrimp.non_comp_default to tool_user;
grant select,insert,update,delete on csrimp.non_comp_default_issue to tool_user;
grant select,insert,update,delete on csrimp.non_comp_default_tag to tool_user;
grant select,insert,update,delete on csrimp.non_comp_default_folder to tool_user;
grant select,insert,update,delete on csrimp.non_compliance to tool_user;
grant select,insert,update,delete on csrimp.non_compliance_expr_action to tool_user;
grant select,insert,update,delete on csrimp.non_compliance_file_upload to tool_user;
grant select,insert,update,delete on csrimp.non_compliance_tag to tool_user;
grant select,insert,update,delete on csrimp.non_compliance_type to tool_user;
grant select,insert,update,delete on csrimp.non_compliance_type_flow_cap to tool_user;
grant select,insert,update,delete on csrimp.non_comp_type_audit_type to tool_user;
grant select,insert,update,delete on csrimp.non_comp_type_rpt_audit_type to tool_user;
grant select,insert,update,delete on csrimp.postit to tool_user;
grant select,insert,update,delete on csrimp.postit_file to tool_user;
grant insert,select,update,delete on csrimp.pct_ownership to tool_user;
grant insert,select,update,delete on csrimp.pending_dataset to tool_user;
grant insert,select,update,delete on csrimp.pending_ind to tool_user;
grant insert,select,update,delete on csrimp.pending_ind_accuracy_type to tool_user;
grant insert,select,update,delete on csrimp.pending_period to tool_user;
grant insert,select,update,delete on csrimp.pending_region to tool_user;
grant insert,select,update,delete on csrimp.pending_val to tool_user;
grant insert,select,update,delete on csrimp.pending_val_accuracy_type_opt to tool_user;
grant insert,select,update,delete on csrimp.pending_val_log to tool_user;
grant insert,select,update,delete on csrimp.pending_val_variance to tool_user;
grant insert,select,update,delete on csrimp.permission_mapping to tool_user;
grant insert,select,update,delete on csrimp.permission_name to tool_user;
grant insert,select,update,delete on csrimp.period to tool_user;
grant insert,select,update,delete on csrimp.period_set to tool_user;
grant insert,select,update,delete on csrimp.period_interval to tool_user;
grant insert,select,update,delete on csrimp.period_interval_member to tool_user;
grant insert,select,update,delete on csrimp.period_dates to tool_user;
grant insert,select,update,delete on csrimp.portal_dashboard to tool_user;
grant select,insert,update,delete on csrimp.qs_response_file to tool_user;
grant select,insert,update,delete on csrimp.qs_answer_file to tool_user;
grant select,insert,update,delete on csrimp.qs_answer_log to tool_user;
grant select,insert,update,delete on csrimp.qs_custom_question_type to tool_user;
grant select,insert,update,delete on csrimp.qs_expr_msg_action to tool_user;
grant select,insert,update,delete on csrimp.qs_expr_nc_action_involve_role to tool_user;
grant select,insert,update,delete on csrimp.qs_expr_non_compl_action to tool_user;
grant select,insert,update,delete on csrimp.qs_filter_condition to tool_user;
grant select,insert,update,delete on csrimp.qs_filter_cond_gen_type to tool_user;
grant select,insert,update,delete on csrimp.qs_filter_condition_general to tool_user;
grant select,insert,update,delete on csrimp.qs_question_option to tool_user;
grant select,insert,update,delete on csrimp.qs_question_option_nc_tag to tool_user;
grant select,insert,update,delete on csrimp.qs_response_postit to tool_user;
grant select,insert,update,delete on csrimp.qs_submission_file to tool_user;
grant select,insert,update,delete on csrimp.question to tool_user;
grant select,insert,update,delete on csrimp.question_version to tool_user;
grant select,insert,update,delete on csrimp.question_option to tool_user;
grant select,insert,update,delete on csrimp.question_option_nc_tag to tool_user;
grant select,insert,update,delete on csrimp.question_tag to tool_user;
grant select,insert,update,delete on csrimp.quick_survey to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_answer to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_expr to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_expr_action to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_lang to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_question to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_question_tag to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_response to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_submission to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_type to tool_user;
grant select,insert,update,delete on csrimp.quick_survey_version to tool_user;
grant select,insert,update,delete on csrimp.r_report_type to tool_user;
grant select,insert,update,delete on csrimp.r_report to tool_user;
grant select,insert,update,delete on csrimp.r_report_file to tool_user;
grant select,insert,update,delete on csrimp.rag_status to tool_user;
grant insert,select,update,delete on csrimp.region to tool_user;
grant insert,select,update,delete on csrimp.region_description to tool_user;
grant select,insert,update,delete on csrimp.region_event to tool_user;
grant select,insert,update,delete on csrimp.region_internal_audit to tool_user;
grant select,insert,update,delete on csrimp.region_meter_alarm to tool_user;
grant select,insert,update,delete on csrimp.region_proc_doc to tool_user;
grant select,insert,update,delete on csrimp.region_proc_file to tool_user;
grant insert,select,update,delete on csrimp.region_role_member to tool_user;
grant select,insert,update,delete on csrimp.region_owner to tool_user;
grant select,insert,update,delete on csrimp.region_set to tool_user;
grant select,insert,update,delete on csrimp.region_set_region to tool_user;
grant insert,select,update,delete on csrimp.region_start_point to tool_user;
grant select,insert,update,delete on csrimp.region_survey_response to tool_user;
grant select,insert,update,delete on csrimp.region_score to tool_user;
grant select,insert,update,delete on csrimp.region_score_log to tool_user;
grant insert,select,update,delete on csrimp.region_tag to tool_user;
grant insert,select,update,delete on csrimp.region_tree to tool_user;
grant insert,select,update,delete on csrimp.reporting_period to tool_user;
grant insert,select,update,delete on csrimp.role to tool_user;
grant insert,select,update,delete on csrimp.role_grant to tool_user;
grant select,insert,update,delete on csrimp.role_user_cover to tool_user;
grant insert,select,update,delete on csrimp.route to tool_user;
grant insert,select,update,delete on csrimp.route_step to tool_user;
grant insert,select,update,delete on csrimp.route_step_user to tool_user;
grant insert,select,update,delete on csrimp.rss_cache to tool_user;
grant select,insert,update,delete on csrimp.scenario to tool_user;
grant select,insert,update,delete on csrimp.scenario_email_sub to tool_user;
grant select,insert,update,delete on csrimp.scenario_ind to tool_user;
grant select,insert,update,delete on csrimp.scenario_options to tool_user;
grant select,insert,update,delete on csrimp.scenario_region to tool_user;
grant select,insert,update,delete on csrimp.scenario_rule to tool_user;
grant select,insert,update,delete on csrimp.scenario_rule_ind to tool_user;
grant select,insert,update,delete on csrimp.scenario_rule_like_contig_ind to tool_user;
grant select,insert,update,delete on csrimp.scenario_rule_region to tool_user;
grant select,insert,update,delete on csrimp.scenario_run to tool_user;
grant select,insert,update,delete on csrimp.scenario_run_val to tool_user;
grant select,insert,update,delete on csrimp.scenario_run_version to tool_user;
grant select,insert,update,delete on csrimp.scenario_run_version_file to tool_user;
grant select,insert,update,delete on csrimp.scheduled_stored_proc to tool_user;
grant select,insert,update,delete on csrimp.scheduled_stored_proc_log to tool_user;
grant select,insert,update,delete on csrimp.score_threshold to tool_user;
grant select,insert,update,delete on csrimp.score_type to tool_user;
grant select,insert,update,delete on csrimp.score_type_agg_type to tool_user;
grant select,insert,update,delete on csrimp.scragpp_status to tool_user;
grant select,insert,update,delete on csrimp.scragpp_audit_log to tool_user;
grant insert,select,update,delete on csrimp.section to tool_user;
grant insert,select,update,delete on csrimp.section_alert to tool_user;
grant insert,select,update,delete on csrimp.section_cart_folder to tool_user;
grant insert,select,update,delete on csrimp.section_cart to tool_user;
grant insert,select,update,delete on csrimp.section_cart_member to tool_user;
grant insert,select,update,delete on csrimp.section_comment to tool_user;
grant insert,select,update,delete on csrimp.section_trans_comment to tool_user;
grant insert,select,update,delete on csrimp.section_flow to tool_user;
grant insert,select,update,delete on csrimp.section_module to tool_user;
grant insert,select,update,delete on csrimp.section_routed_flow_state to tool_user;
grant insert,select,update,delete on csrimp.section_tag to tool_user;
grant insert,select,update,delete on csrimp.section_tag_member to tool_user;
grant insert,select,update,delete on csrimp.section_status to tool_user;
grant insert,select,update,delete on csrimp.section_transition to tool_user;
grant insert,select,update,delete on csrimp.section_version to tool_user;
grant insert,select,update,delete on csrimp.securable_object to tool_user;
grant insert,select,update,delete on csrimp.securable_object_attributes to tool_user;
grant insert,select,update,delete on csrimp.securable_object_class to tool_user;
grant insert,select,update,delete on csrimp.securable_object_keyed_acl to tool_user;
grant insert,select,update,delete on csrimp.sheet to tool_user;
grant insert,select,update,delete on csrimp.sheet_alert to tool_user;
grant select,insert,update,delete on csrimp.sheet_date_schedule to tool_user;
grant insert,select,update,delete on csrimp.sheet_history to tool_user;
grant insert,select,update,delete on csrimp.sheet_inherited_value to tool_user;
grant insert,select,update,delete on csrimp.sheet_value to tool_user;
grant insert,select,update,delete on csrimp.sheet_value_accuracy to tool_user;
grant insert,select,update,delete on csrimp.sheet_value_change to tool_user;
grant insert,select,update,delete on csrimp.sheet_value_file to tool_user;
grant insert,select,update,delete on csrimp.sheet_value_file_hidden_cache to tool_user;
grant insert,select,update,delete on csrimp.sheet_value_var_expl to tool_user;
grant insert,select,update,delete on csrimp.sheet_value_hidden_cache to tool_user;
grant insert,select,update,delete on csrimp.superadmin to tool_user;
grant insert,select,update,delete on csrimp.superadmin_folder to tool_user;
grant select,insert,update,delete on csrimp.tab to tool_user;
grant select,insert,update,delete on csrimp.tab_description to tool_user;
grant select,insert,update,delete on csrimp.tab_group to tool_user;
grant select,insert,update,delete on csrimp.tab_portlet to tool_user;
grant select,insert,update,delete on csrimp.tab_portlet_rss_feed to tool_user;
grant select,insert,update,delete on csrimp.tab_portlet_user_region to tool_user;
grant select,insert,update,delete on csrimp.tab_user to tool_user;
grant insert,select,update,delete on csrimp.tag to tool_user;
grant insert,select,update,delete on csrimp.tag_description to tool_user;
grant insert,select,update,delete on csrimp.tag_group to tool_user;
grant insert,select,update,delete on csrimp.tag_group_description to tool_user;
grant insert,select,update,delete on csrimp.tag_group_member to tool_user;
grant select,insert,update,delete on csrimp.target_dashboard to tool_user;
grant select,insert,update,delete on csrimp.target_dashboard_ind_member to tool_user;
grant select,insert,update,delete on csrimp.target_dashboard_reg_member to tool_user;
grant select,insert,update,delete on csrimp.target_dashboard_value to tool_user;
grant select,insert,update,delete on csrimp.template to tool_user;
grant select,insert,update,delete on csrimp.term_cond_doc to tool_user;
grant select,insert,update,delete on csrimp.term_cond_doc_log to tool_user;
grant select,insert,update,delete on csrimp.tpl_img to tool_user;
grant select,insert,update,delete on csrimp.tpl_rep_cust_tag_type to tool_user;
grant select,insert,update,delete on csrimp.tpl_report to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_non_compl to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_approval_note to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_approval_matrix to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_dataview to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_dv_region to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_eval to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_eval_cond to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_ind to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_logging_form to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_text to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_reg_data to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_tag_qchart to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_variant to tool_user;
grant select,insert,update,delete on csrimp.tpl_report_variant_tag to tool_user;
grant select,insert,update,delete on csrimp.trash to tool_user;
grant insert,select,update,delete on csrimp.user_certificates to tool_user;
grant insert,select,update,delete on csrimp.user_password_history to tool_user;
grant insert,select,update,delete on csrimp.user_table to tool_user;
grant select,insert,update,delete on csrimp.utility_contract to tool_user;
grant select,insert,update,delete on csrimp.utility_invoice to tool_user;
grant select,insert,update,delete on csrimp.utility_supplier to tool_user;
grant select,insert,update,delete on csrimp.user_cover to tool_user;
grant select,insert,update,delete on csrimp.user_setting_entry to tool_user;
grant select,insert,update,delete on csrimp.user_setting to tool_user;
grant insert,select,update,delete on csrimp.var_expl to tool_user;
grant insert,select,update,delete on csrimp.var_expl_group to tool_user;
grant insert,select,update,delete on csrimp.val to tool_user;
grant insert,select,update,delete on csrimp.val_change to tool_user;
grant insert,select,update,delete on csrimp.web_resource to tool_user;
grant insert,select,update,delete on csrimp.website to tool_user;
grant insert,select,update,delete on csrimp.non_compliance_file to tool_user;
grant select,insert,update,delete on csrimp.currency to tool_user;
grant select,insert,update,delete on csrimp.fund to tool_user;
grant select,insert,update,delete on csrimp.fund_form_plugin to tool_user;
grant select,insert,update,delete on csrimp.fund_type to tool_user;
grant select,insert,update,delete on csrimp.lease to tool_user;
grant select,insert,update,delete on csrimp.lease_postit to tool_user;
grant select,insert,update,delete on csrimp.lease_property to tool_user;
grant select,insert,update,delete on csrimp.lease_space to tool_user;
grant select,insert,update,delete on csrimp.lease_type to tool_user;
grant select,insert,update,delete on csrimp.meter_type to tool_user;
grant select,insert,update,delete on csrimp.mgmt_company to tool_user;
grant select,insert,update,delete on csrimp.mgmt_company_contact to tool_user;
grant select,insert,update,delete on csrimp.mgmt_company_fund_contact to tool_user;
grant select,insert,update,delete on csrimp.plugin to tool_user;
grant select,insert,update,delete on csrimp.plugin_indicator to tool_user;
grant select,insert,update,delete on csrimp.property to tool_user;
grant select,insert,update,delete on csrimp.property_address_options to tool_user;
grant select,insert,update,delete on csrimp.property_element_layout to tool_user;
grant select,insert,update,delete on csrimp.property_character_layout to tool_user;
grant select,insert,update,delete on csrimp.property_options to tool_user;
grant select,insert,update,delete on csrimp.property_photo to tool_user;
grant select,insert,update,delete on csrimp.property_sub_type to tool_user;
grant select,insert,update,delete on csrimp.property_tab to tool_user;
grant select,insert,update,delete on csrimp.property_tab_group to tool_user;
grant select,insert,update,delete on csrimp.property_type to tool_user;
grant select,insert,update,delete on csrimp.prop_type_prop_tab to tool_user;

-- property dashboards
grant select,insert,update,delete on csrimp.benchmark_dashboard to tool_user;
grant select,insert,update,delete on csrimp.benchmark_dashboard_char to tool_user;
grant select,insert,update,delete on csrimp.benchmark_dashboard_ind to tool_user;
grant select,insert,update,delete on csrimp.benchmark_dashboard_plugin to tool_user;
grant select,insert,update,delete on csrimp.metric_dashboard to tool_user;
grant select,insert,update,delete on csrimp.metric_dashboard_ind to tool_user;
grant select,insert,update,delete on csrimp.metric_dashboard_plugin to tool_user;

grant select,insert,update,delete on csrimp.region_metric to tool_user;
grant select,insert,update,delete on csrimp.region_metric_val to tool_user;
grant select,insert,update,delete on csrimp.region_type_metric to tool_user;
grant select,insert,update,delete on csrimp.region_type_tag_group to tool_user;
grant select,insert,update,delete on csrimp.space to tool_user;
grant select,insert,update,delete on csrimp.space_type to tool_user;
grant select,insert,update,delete on csrimp.space_type_region_metric to tool_user;
grant select,insert,update,delete on csrimp.tenant to tool_user;
grant select,insert,update,delete on csrimp.plugin_type to tool_user;
grant select,insert,update,delete on csrimp.plugin to tool_user;
grant select,insert,update,delete on csrimp.property_type_space_type to tool_user;
grant select,insert,update,delete on csrimp.chain_capability to tool_user;
grant select,insert,update,delete on csrimp.chain_capability_flow_cap to tool_user;
grant select,insert,update,delete on csrimp.chain_customer_options to tool_user;
grant select,insert,update,delete on csrimp.chain_company_type to tool_user;
grant select,insert,update,delete on csrimp.chain_company to tool_user;
grant select,insert,update,delete on csrimp.supplier to tool_user;
grant select,insert,update,delete on csrimp.chain_appli_compa_capabi to tool_user;
grant select,insert,update,delete on csrimp.chain_chain_user to tool_user;
grant select,insert,update,delete on csrimp.chain_company_group to tool_user;
grant select,insert,update,delete on csrimp.chain_compan_type_relati to tool_user;
grant select,insert,update,delete on csrimp.chain_compan_type_capabi to tool_user;
grant select,insert,update,delete on csrimp.chain_group_capab_overri to tool_user;
grant select,insert,update,delete on csrimp.chain_implementation to tool_user;
grant select,insert,update,delete on csrimp.chain_sector to tool_user;
grant select,insert,update,delete on csrimp.chain_tertiary_relations to tool_user;
grant select,insert,update,delete on csrimp.chain_company_type_role to tool_user;
grant select,insert,update,delete on csrimp.chain_supplier_relationship to tool_user;
grant select,insert,update,delete on csrimp.chain_supp_rel_source to tool_user;
grant select,insert,update,delete on csrimp.chain_supplier_follower to tool_user;
grant select,insert,update,delete on csrimp.chain_card to tool_user;
grant select,insert,update,delete on csrimp.chain_card_group_card to tool_user;
grant select,insert,update,delete on csrimp.chain_card_group_progression to tool_user;
grant select,insert,update,delete on csrimp.chain_card_init_param to tool_user;

grant select, insert, update, delete on csrimp.chain_activity_type to tool_user;
grant select, insert, update, delete on csrimp.chain_outcome_type to tool_user;
grant select, insert, update, delete on csrimp.chain_activi_outcom_type to tool_user;
grant select, insert, update, delete on csrimp.chain_activity to tool_user;
grant select, insert, update, delete on csrimp.chain_activity_log to tool_user;
grant select, insert, update, delete on csrimp.chain_activity_log_file to tool_user;
grant select, insert, update, delete on csrimp.chain_acti_type_tag_grou to tool_user;
grant select, insert, update, delete on csrimp.chain_activity_involvement to tool_user;
grant select, insert, update, delete on csrimp.chain_activity_tag to tool_user;
grant select, insert, update, delete on csrimp.chain_activi_type_action to tool_user;
grant select, insert, update, delete on csrimp.chain_act_outc_type_act to tool_user;
grant select, insert, update, delete on csrimp.chain_activit_type_alert to tool_user;
grant select, insert, update, delete on csrimp.chain_act_type_aler_role to tool_user;
grant select, insert, update, delete on csrimp.chain_act_type_defa_user to tool_user;

grant select, insert, update, delete on csrimp.chain_alert_parti_templa to tool_user;
grant select, insert, update, delete on csrimp.chain_ale_part_temp_para to tool_user;
grant select, insert, update, delete on csrimp.chain_amount_unit to tool_user;
grant select, insert, update, delete on csrimp.chain_audit_request to tool_user;
grant select, insert, update, delete on csrimp.chain_audit_reques_alert to tool_user;
grant select, insert, update, delete on csrimp.chain_business_unit to tool_user;
grant select, insert, update, delete on csrimp.chain_busine_unit_member to tool_user;
grant select, insert, update, delete on csrimp.chain_busine_unit_suppli to tool_user;
grant select, insert, update, delete on csrimp.chain_ch_use_ema_add_log to tool_user;
grant select, insert, update, delete on csrimp.chain_company_cc_email to tool_user;
grant select, insert, update, delete on csrimp.chain_company_header to tool_user;
grant select, insert, update, delete on csrimp.chain_compan_metric_type to tool_user;
grant select, insert, update, delete on csrimp.chain_company_metric to tool_user;
grant select, insert, update, delete on csrimp.chain_company_reference to tool_user;
grant select, insert, update, delete on csrimp.chain_company_tab to tool_user;
grant select, insert, update, delete on csrimp.chain_comp_tab_comp_type_role to tool_user;
grant select, insert, update, delete on csrimp.chain_company_tag_group to tool_user;
grant select, insert, update, delete on csrimp.chain_component_type to tool_user;
grant select, insert, update, delete on csrimp.chain_compon_type_contai to tool_user;
grant select, insert, update, delete on csrimp.chain_component to tool_user;
grant select, insert, update, delete on csrimp.chain_file_upload to tool_user;
grant select, insert, update, delete on csrimp.chain_component_document to tool_user;
grant select, insert, update, delete on csrimp.chain_component_source to tool_user;
grant select, insert, update, delete on csrimp.chain_component_tag to tool_user;
grant select, insert, update, delete on csrimp.chain_compound_filter to tool_user;
grant select, insert, update, delete on csrimp.chain_cus_aler_entr_temp to tool_user;
grant select, insert, update, delete on csrimp.chain_cus_aler_entr_type to tool_user;
grant select, insert, update, delete on csrimp.chain_customer_aggregate_type to tool_user;
grant select, insert, update, delete on csrimp.chain_def_prod_code_type to tool_user;
grant select, insert, update, delete on csrimp.chain_de_sup_rel_cod_lab to tool_user;
grant select, insert, update, delete on csrimp.chain_email_stub to tool_user;
grant select, insert, update, delete on csrimp.chain_file_group to tool_user;
grant select, insert, update, delete on csrimp.chain_file_group_file to tool_user;
grant select, insert, update, delete on csrimp.chain_filter to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_field to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_value to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_page_column to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_item_config to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_page_cms_table to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_page_ind to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_page_ind_interval to tool_user;
grant select, insert, update, delete on csrimp.chain_filtersupplierrepo to tool_user;
grant select, insert, update, delete on csrimp.chain_flow_filter to tool_user;
grant select, insert, update, delete on csrimp.chain_invitation to tool_user;
grant select, insert, update, delete on csrimp.chain_invitatio_user_tpl to tool_user;
grant select, insert, update, delete on csrimp.chain_message_definition to tool_user;
grant select, insert, update, delete on csrimp.chain_message_param to tool_user;
grant select, insert, update, delete on csrimp.chain_questionnair_group to tool_user;
grant select, insert, update, delete on csrimp.chain_questionnaire_type to tool_user;
grant select, insert, update, delete on csrimp.chain_flow_question_type to tool_user;
grant select, insert, update, delete on csrimp.chain_invi_qnr_type_comp to tool_user;
grant select, insert, update, delete on csrimp.chain_message to tool_user;
grant select, insert, update, delete on csrimp.chain_alert_entry to tool_user;
grant select, insert, update, delete on csrimp.chain_alert_entry_param to tool_user;
grant select, insert, update, delete on csrimp.chain_invitatio_qnr_type to tool_user;
grant select, insert, update, delete on csrimp.chain_message_recipient to tool_user;
grant select, insert, update, delete on csrimp.chain_messag_refresh_log to tool_user;
grant select, insert, update, delete on csrimp.chain_newsflash to tool_user;
grant select, insert, update, delete on csrimp.chain_newsflash_company to tool_user;
grant select, insert, update, delete on csrimp.chain_newsfl_user_settin to tool_user;
grant select, insert, update, delete on csrimp.chain_product to tool_user;
grant select, insert, update, delete on csrimp.chain_product_code_type to tool_user;
grant select, insert, update, delete on csrimp.chain_produc_metric_type to tool_user;
grant select, insert, update, delete on csrimp.chain_product_revision to tool_user;
grant select, insert, update, delete on csrimp.chain_product_metric to tool_user;
grant select, insert, update, delete on csrimp.chain_prd_mtrc_prd_type to tool_user;
grant select, insert, update, delete on csrimp.chain_purchase_channel to tool_user;
grant select, insert, update, delete on csrimp.chain_purchase_component to tool_user;
grant select, insert, update, delete on csrimp.chain_purchase to tool_user;
grant select, insert, update, delete on csrimp.chain_purchase_tag to tool_user;
grant select, insert, update, delete on csrimp.chain_purchaser_follower to tool_user;
grant select, insert, update, delete on csrimp.chain_qnna_shar_aler_log to tool_user;
grant select, insert, update, delete on csrimp.chain_qnr_acti_secu_mask to tool_user;
grant select, insert, update, delete on csrimp.chain_questionnaire to tool_user;
grant select, insert, update, delete on csrimp.chain_qnr_shar_log_entry to tool_user;
grant select, insert, update, delete on csrimp.chain_qnr_stat_log_entry to tool_user;
grant select, insert, update, delete on csrimp.chain_quest_expiry_alert to tool_user;
grant select, insert, update, delete on csrimp.chain_question_invitatio to tool_user;
grant select, insert, update, delete on csrimp.chain_questi_metric_type to tool_user;
grant select, insert, update, delete on csrimp.chain_questionnai_metric to tool_user;
grant select, insert, update, delete on csrimp.chain_questionnair_share to tool_user;
grant select, insert, update, delete on csrimp.chain_questionnaire_user to tool_user;
grant select, insert, update, delete on csrimp.chain_questi_user_action to tool_user;
grant select, insert, update, delete on csrimp.chain_recipient to tool_user;
grant select, insert, update, delete on csrimp.chain_reference to tool_user;
grant select, insert, update, delete on csrimp.chain_reference_company_type to tool_user;
grant select, insert, update, delete on csrimp.chain_reference_capability to tool_user;
grant select, insert, update, delete on csrimp.chain_review_alert to tool_user;
grant select, insert, update, delete on csrimp.chain_saved_filter to tool_user;
grant select, insert, update, delete on csrimp.chain_saved_filter_agg_type to tool_user;
grant select, insert, update, delete on csrimp.chain_saved_filter_column to tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.chain_saved_filter_region TO tool_user;
grant select, insert, update, delete on csrimp.chain_saved_filter_alert to tool_user;
grant select, insert, update, delete on csrimp.chain_saved_fltr_alrt_sbscrptn to tool_user;
grant select, insert, update, delete on csrimp.chain_supplier_audit to tool_user;
grant select, insert, update, delete on csrimp.chain_task to tool_user;
grant select, insert, update, delete on csrimp.chain_task_action_trigge to tool_user;
grant select, insert, update, delete on csrimp.chain_task_entry to tool_user;
grant select, insert, update, delete on csrimp.chain_task_entry_date to tool_user;
grant select, insert, update, delete on csrimp.chain_task_entry_file to tool_user;
grant select, insert, update, delete on csrimp.chain_task_entry_note to tool_user;
grant select, insert, update, delete on csrimp.chain_task_scheme to tool_user;
grant select, insert, update, delete on csrimp.chain_task_type to tool_user;
grant select, insert, update, delete on csrimp.chain_task_invi_qnr_type to tool_user;
grant select, insert, update, delete on csrimp.chain_ucd_logon to tool_user;
grant select, insert, update, delete on csrimp.chain_uninvited_supplier to tool_user;
grant select, insert, update, delete on csrimp.chain_url_overrides to tool_user;
grant select, insert, update, delete on csrimp.chain_use_aler_entr_type to tool_user;
grant select, insert, update, delete on csrimp.chain_user_message_log to tool_user;
grant select, insert, update, delete on csrimp.chain_valid_purch_compon to tool_user;
grant select, insert, update, delete on csrimp.chain_worksh_file_upload to tool_user;
grant select, insert, update, delete on csrimp.chain_defau_messa_defini to tool_user;
grant select, insert, update, delete on csrimp.chain_messa_defin_lookup to tool_user;
grant select, insert, update, delete on csrimp.chain_filter_type to tool_user;
grant select, insert, update, delete on csrimp.chain_group_capability to tool_user;
grant select, insert, update, delete on csrimp.chain_card_progre_action to tool_user;
grant select, insert, update, delete on csrimp.chain_product_type to tool_user;
grant select, insert, update, delete on csrimp.chain_product_type_tr to tool_user;
grant select, insert, update, delete on csrimp.chain_company_product_type to tool_user;
grant select, insert, update, delete on csrimp.chain_product_type_tag to tool_user;
grant select, insert, update, delete on csrimp.chain_busine_relati_type to tool_user;
grant select, insert, update, delete on csrimp.chain_busine_relati_tier to tool_user;
grant select, insert, update, delete on csrimp.chain_bu_rel_tie_com_typ to tool_user;
grant select, insert, update, delete on csrimp.chain_business_relations to tool_user;
grant select, insert, update, delete on csrimp.chain_busin_relat_compan to tool_user;
grant select, insert, update, delete on csrimp.chain_busin_relat_period to tool_user;
grant select, insert, update, delete on csrimp.chain_risk_level to tool_user;
grant select, insert, update, delete on csrimp.chain_country_risk_level to tool_user;
grant select, insert, update, delete on csrimp.chain_import_source to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_mapping to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_stagin_link to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_rule to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_rule_set to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_prepro_comp to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_prepro_rule to tool_user;
grant select, insert, update, delete on csrimp.chain_dedu_pp_fiel_cntry to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_sub to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_pp_alt_comp_name to tool_user;
grant select, insert, update, delete on csrimp.chain_dd_cust_blcklst_email to tool_user;
grant select, insert, update, delete on csrimp.chain_aggregate_type_config to tool_user;
grant select, insert, update, delete on csrimp.chain_higg to tool_user;
grant select, insert, update, delete on csrimp.higg_module_tag_group to tool_user;
grant select, insert, update, delete on csrimp.higg_config to tool_user;
grant select, insert, update, delete on csrimp.higg_config_module to tool_user;
grant select, insert, update, delete on csrimp.higg_response to tool_user;
grant select, insert, update, delete on csrimp.higg_section_score to tool_user;
grant select, insert, update, delete on csrimp.higg_sub_section_score to tool_user;
grant select, insert, update, delete on csrimp.higg_question_response to tool_user;
grant select, insert, update, delete on csrimp.higg_profile to tool_user;
grant select, insert, update, delete on csrimp.higg_question_survey to tool_user;
grant select, insert, update, delete on csrimp.higg_question_option_survey to tool_user;
grant select, insert, update, delete on csrimp.higg_config_profile to tool_user;
grant select, insert, update, delete on csrimp.higg_question_opt_conversion to tool_user;
grant select, insert, update, delete on csrimp.chain_product_header to tool_user;
grant select, insert, update, delete on csrimp.chain_pro_head_pro_type to tool_user;
grant select, insert, update, delete on csrimp.chain_product_tab to tool_user;
grant select, insert, update, delete on csrimp.chain_prod_tab_prod_type to tool_user;
grant select, insert, update, delete on csrimp.chain_produc_supplie_tab to tool_user;
grant select, insert, update, delete on csrimp.chain_pr_sup_tab_pr_typ to tool_user;
grant select, insert, update, delete on csrimp.chain_pend_cmpny_suggstd_match to tool_user;
grant select, insert, update, delete on csrimp.chain_pending_company_tag to tool_user;
grant select, insert, update, delete on csrimp.chain_company_request_action to tool_user;
grant select, insert, update, delete on csrimp.chain_product_company_alert to tool_user;

grant select, insert, update, delete on csrimp.worksheet to tool_user;
grant select, insert, update, delete on csrimp.worksheet_column to tool_user;
grant select, insert, update, delete on csrimp.worksheet_column_value_map to tool_user;
grant select, insert, update, delete on csrimp.worksheet_row to tool_user;
grant select, insert, update, delete on csrimp.worksheet_value_map to tool_user;
grant select, insert, update, delete on csrimp.worksheet_value_map_value to tool_user;

grant select, insert, update, delete on csrimp.chem_chem_options to tool_user;
grant select, insert, update, delete on csrimp.chem_cas to tool_user;
grant select, insert, update, delete on csrimp.chem_cas_group to tool_user;
grant select, insert, update, delete on csrimp.chem_cas_group_member to tool_user;
grant select, insert, update, delete on csrimp.chem_cas_restricted to tool_user;
grant select, insert, update, delete on csrimp.chem_classification to tool_user;
grant select, insert, update, delete on csrimp.chem_manufacturer to tool_user;
grant select, insert, update, delete on csrimp.chem_substance to tool_user;
grant select, insert, update, delete on csrimp.chem_substance_cas to tool_user;
grant select, insert, update, delete on csrimp.chem_usage to tool_user;
grant select, insert, update, delete on csrimp.chem_substance_region to tool_user;
grant select, insert, update, delete on csrimp.chem_subst_region_proces to tool_user;
grant select, insert, update, delete on csrimp.chem_process_cas_default to tool_user;
grant select, insert, update, delete on csrimp.chem_subs_proc_use_chang to tool_user;
grant select, insert, update, delete on csrimp.chem_sub_pro_cas_des_cha to tool_user;
grant select, insert, update, delete on csrimp.chem_substance_audit_log to tool_user;
grant select, insert, update, delete on csrimp.chem_substance_file to tool_user;
grant select, insert, update, delete on csrimp.chem_substan_process_use to tool_user;
grant select, insert, update, delete on csrimp.chem_subs_proce_cas_dest to tool_user;
grant select, insert, update, delete on csrimp.chem_subs_proce_use_file to tool_user;
grant select, insert, update, delete on csrimp.chem_usage_audit_log to tool_user;

--FB63025 - Carbon module
grant select, insert, update, delete on csrimp.customer_flow_capability to tool_user;
grant select, insert, update, delete on csrimp.ia_type_survey_group to tool_user;
grant select, insert, update, delete on csrimp.internal_audit_type_survey to tool_user;
grant select, insert, update, delete on csrimp.internal_audit_survey to tool_user;
grant select, insert, update, delete on csrimp.internal_audit_score to tool_user;

grant select, insert, update, delete on csrimp.meter_data_priority to tool_user;
grant select, insert, update, delete on csrimp.meter_patch_data to tool_user;
grant select, insert, update, delete on csrimp.meter_input to tool_user;
grant select, insert, update, delete on csrimp.meter_input_aggr_ind to tool_user;
grant select, insert, update, delete on csrimp.meter_input_aggregator to tool_user;
grant select, insert, update, delete on csrimp.meter_patch_job to tool_user;
grant select, insert, update, delete on csrimp.meter_patch_batch_job to tool_user;
grant select, insert, update, delete on csrimp.meter_data_coverage_ind to tool_user;
grant select, insert, update, delete on csrimp.meter_type_input to tool_user;
grant select, insert, update, delete on csrimp.meter_data_source_hi_res_input to tool_user;
grant select, insert, update, delete on csrimp.duff_meter_region to tool_user;

grant select, insert, update, delete on csrimp.customer_file_upload_type_opt to tool_user;
grant select, insert, update, delete on csrimp.customer_file_upload_mime_opt to tool_user;

grant select, insert, update, delete on csrimp.image_upload_portlet to tool_user;
	
grant select, insert, update, delete on csrimp.quick_survey_score_threshold to tool_user;
grant select, insert, update, delete on csrimp.supplier_survey_response to tool_user;

grant select, insert, update, delete on csrimp.non_compliance_type_tag_group to tool_user;
grant select, insert, update, delete on csrimp.internal_audit_type_tag_group to tool_user;
grant select, insert, update, delete on csrimp.internal_audit_tag to tool_user;
grant select, insert, update, delete on csrimp.chain_company_type_tag_group to tool_user;
grant select, insert, update, delete on csrimp.gresb_indicator_mapping to tool_user;
grant select, insert, update, delete on csrimp.gresb_submission_log to tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.property_gresb TO tool_user;
grant select, insert, update, delete on csrimp.property_fund to tool_user;
grant select, insert, update, delete on csrimp.property_fund_ownership to tool_user;
grant select, insert, update, delete on csrimp.mgt_company_tree_sync_job to tool_user;

grant select, insert, update, delete on csrimp.issue_custom_field_date_val to tool_user;
grant select, insert, update, delete on csrimp.quick_survey_css to tool_user;
grant select, insert, update, delete on csrimp.chain_dedup_proce_record to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_match to tool_user;
grant select, insert, update, delete on csrimp.chain_dedupe_merge_log to tool_user;


grant select, insert, update, delete on csrimp.geo_map to tool_user;
grant select, insert, update, delete on csrimp.geo_map_region to tool_user;
grant select, insert, update, delete on csrimp.degreeday_settings to tool_user;
grant select, insert, update, delete on csrimp.degreeday_region to tool_user;

grant select, insert, update, delete on csrimp.initiative to tool_user;
grant select, insert, update, delete on csrimp.initiative_metric to tool_user;
grant select, insert, update, delete on csrimp.initiative_project to tool_user;
grant select, insert, update, delete on csrimp.initia_projec_rag_status to tool_user;
grant select, insert, update, delete on csrimp.customer_init_saving_type to tool_user;
grant select, insert, update, delete on csrimp.initiative_metric_group to tool_user;
grant select, insert, update, delete on csrimp.project_initiative_metric to tool_user;
grant select, insert, update, delete on csrimp.initiative_metric_assoc to tool_user;
grant select, insert, update, delete on csrimp.project_init_metric_flow_state to tool_user;
grant select, insert, update, delete on csrimp.initiat_metric_state_ind to tool_user;
grant select, insert, update, delete on csrimp.aggr_tag_group to tool_user;
grant select, insert, update, delete on csrimp.initiativ_metric_tag_ind to tool_user;
grant select, insert, update, delete on csrimp.aggr_tag_group_member to tool_user;
grant select, insert, update, delete on csrimp.flow_state_group to tool_user;
grant select, insert, update, delete on csrimp.flow_state_group_member to tool_user;
grant select, insert, update, delete on csrimp.initiative_comment to tool_user;
grant select, insert, update, delete on csrimp.initiative_event to tool_user;
grant select, insert, update, delete on csrimp.initiative_group to tool_user;
grant select, insert, update, delete on csrimp.initiat_group_flow_state to tool_user;
grant select, insert, update, delete on csrimp.initiative_group_member to tool_user;
grant select, insert, update, delete on csrimp.initiative_group_user to tool_user;
grant select, insert, update, delete on csrimp.initiative_import_map_mru to tool_user;
grant select, insert, update, delete on csrimp.initiati_import_template to tool_user;
grant select, insert, update, delete on csrimp.initia_import_templa_map to tool_user;
grant select, insert, update, delete on csrimp.initiative_metric_val to tool_user;
grant select, insert, update, delete on csrimp.initiative_period_status to tool_user;
grant select, insert, update, delete on csrimp.initiative_period to tool_user;
grant select, insert, update, delete on csrimp.initiative_project_tab to tool_user;
grant select, insert, update, delete on csrimp.initia_project_tab_group to tool_user;
grant select, insert, update, delete on csrimp.initiative_project_team to tool_user;
grant select, insert, update, delete on csrimp.initiative_region to tool_user;
grant select, insert, update, delete on csrimp.initiative_sponsor to tool_user;
grant select, insert, update, delete on csrimp.initiative_tag to tool_user;
grant select, insert, update, delete on csrimp.initiative_user_group to tool_user;
grant select, insert, update, delete on csrimp.initia_projec_user_group to tool_user;
grant select, insert, update, delete on csrimp.initiative_user to tool_user;
grant select, insert, update, delete on csrimp.initiative_user_msg to tool_user;
grant select, insert, update, delete on csrimp.initiatives_options to tool_user;
grant select, insert, update, delete on csrimp.user_msg to tool_user;
grant select, insert, update, delete on csrimp.project_initiative_period_stat to tool_user;
grant select, insert, update, delete on csrimp.default_initiative_user_state to tool_user;
grant select, insert, update, delete on csrimp.issue_initiative to tool_user;
grant select, insert, update, delete on csrimp.aggr_region to tool_user;
grant select, insert, update, delete on csrimp.alert_batch_run to tool_user;
grant select, insert, update, delete on csrimp.project_doc_folder to tool_user;
grant select, insert, update, delete on csrimp.project_tag_group to tool_user;
grant select, insert, update, delete on csrimp.project_tag_filter to tool_user;
grant select, insert, update, delete on csrimp.init_tab_element_layout to tool_user;
grant select, insert, update, delete on csrimp.init_create_page_el_layout to tool_user;
grant select, insert, update, delete on csrimp.initiative_header_element to tool_user;

GRANT SELECT, INSERT, UPDATE ON csrimp.custom_factor_set TO tool_user;
GRANT SELECT, INSERT, UPDATE ON csrimp.custom_factor TO tool_user;
GRANT SELECT, INSERT, UPDATE ON csrimp.custom_factor_history TO tool_user;
GRANT SELECT, INSERT, UPDATE ON csrimp.emission_factor_profile TO tool_user;
GRANT SELECT, INSERT, UPDATE ON csrimp.emission_factor_profile_factor TO tool_user;
GRANT SELECT, INSERT, UPDATE ON csrimp.std_factor_set_active TO tool_user;

grant select, insert, update, delete on csrimp.chain_customer_grid_ext to tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_options TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_item_region TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.flow_item_audit_log TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_req_reg TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_regulation TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_requirement TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_item_tag TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_language TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_item TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_item_version_log TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_audit_log TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_root_regions TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_region_tag TO tool_user;
grant select, insert, update, delete on csrimp.compliance_activity_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_activity_sub_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_application_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_condition_sub_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_condition_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_item_rollout to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_application to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_condition to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_sub_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_tab to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_tab_group to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_history to tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_permit_score TO tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_header to tool_user;
grant select, insert, update, delete on csrimp.compliance_permit_header_group to tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.comp_item_region_sched_issue TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_item_description TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.compliance_item_desc_hist TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_options TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.map_enhesa_error_log TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_error_log TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_site_type TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_site_type_heading TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.map_compliance_item TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.doc_type TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.map_doc_type TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.property_mandatory_roles TO tool_user;

grant select, insert, update, delete on csrimp.aggregate_ind_val_detail to tool_user;
grant select, insert, update, delete on csrimp.chain_tpl_delegation to tool_user;
grant select, insert, update, delete on csrimp.customer_flow_alert_class to tool_user;
grant select, insert, update, delete on csrimp.customer_geo_map_tab_type to tool_user;
grant select, insert, update, delete on csrimp.customer_help_lang to tool_user;
grant select, insert, update, delete on csrimp.img_chart_region to tool_user;
grant select, insert, update, delete on csrimp.ind_set to tool_user;
grant select, insert, update, delete on csrimp.ind_set_ind to tool_user;
grant select, insert, update, delete on csrimp.ind_window to tool_user;
grant select, insert, update, delete on csrimp.issue_alert to tool_user;
grant select, insert, update, delete on csrimp.issue_meter_missing_data to tool_user;
grant select, insert, update, delete on csrimp.route_log to tool_user;
grant select, insert, update, delete on csrimp.route_step_vote to tool_user;
grant select, insert, update, delete on csrimp.sheet_change_req to tool_user;
grant select, insert, update, delete on csrimp.sheet_change_req_alert to tool_user;
grant select, insert, update, delete on csrimp.sheet_value_change_file to tool_user;
grant select, insert, update, delete on csrimp.supplier_delegation to tool_user;
grant select, insert, update, delete on csrimp.user_msg_file to tool_user;
grant select, insert, update, delete on csrimp.val_file to tool_user;
grant select, insert, update, delete on csrimp.val_note to tool_user;

grant select, insert, update, delete on csrimp.chain_higg to tool_user;
grant select, insert, update, delete on csrimp.chain_project to tool_user;
grant select, insert, update, delete on csrimp.chain_scheduled_alert to tool_user;
grant select, insert, update, delete on csrimp.chain_com_type_scor_calc to tool_user;
grant select, insert, update, delete on csrimp.chain_co_ty_sc_cal_co_ty to tool_user;
grant select, insert, update, delete on csrimp.cms_tidy_ddl to tool_user;
grant select, insert, update, delete on csrimp.delegation_layout to tool_user;
grant select, insert, update, delete on csrimp.export_feed to tool_user;
grant select, insert, update, delete on csrimp.export_feed_cms_form to tool_user;
grant select, insert, update, delete on csrimp.export_feed_dataview to tool_user;
grant select, insert, update, delete on csrimp.export_feed_stored_proc to tool_user;
grant select, insert, update, delete on csrimp.forecasting_rule to tool_user;
grant select, insert, update, delete on csrimp.hide_portlet to tool_user;
grant select, insert, update, delete on csrimp.internal_audit_type_report to tool_user;
grant select, insert, update, delete on csrimp.issue_type_rag_status to tool_user;
grant select, insert, update, delete on csrimp.like_for_like_email_sub to tool_user;
grant select, insert, update, delete on csrimp.like_for_like_slot to tool_user;
grant select, insert, update, delete on csrimp.linked_meter to tool_user;
grant select, insert, update, delete on csrimp.meter_patch_batch_data to tool_user;
grant select, insert, update, delete on csrimp.meter_raw_data_log to tool_user;
grant select, insert, update, delete on csrimp.non_comp_type_rpt_audit_type to tool_user;

grant select, insert, update, delete on csrimp.calendar to tool_user;
grant select, insert, update, delete on csrimp.calendar_event to tool_user;
grant select, insert, update, delete on csrimp.calendar_event_invite to tool_user;
grant select, insert, update, delete on csrimp.calendar_event_owner to tool_user;

grant select, insert, update, delete on csrimp.client_util_script to tool_user;
grant select, insert, update, delete on csrimp.client_util_script_param to tool_user;
grant select, insert, update, delete on csrimp.util_script_run_log to tool_user;

grant select, insert, update, delete on csrimp.chain_certification_type to tool_user;
grant select, insert, update, delete on csrimp.chain_cert_type_audit_type to tool_user;
grant select, insert, update, delete on csrimp.chain_alt_company_name to tool_user;
grant select, insert, update, delete on csrimp.chain_suppl_relati_score to tool_user;
grant select, insert, update, delete on csrimp.chain_cust_filter_column to tool_user;
grant select, insert, update, delete on csrimp.chain_custom_filter_item to tool_user;
grant select, insert, update, delete on csrimp.chain_cu_fil_ite_agg_typ to tool_user;
grant select, insert, update, delete on csrimp.chain_supplier_inv_type to tool_user;
grant select, insert, update, delete on csrimp.chain_co_tab_related_co_type to tool_user;
grant select, insert, update, delete on csrimp.score_type_audit_type to tool_user;
grant select, insert, update, delete on csrimp.compliance_rollout_regions to tool_user;
grant select, insert, update, delete on csrimp.cookie_policy_consent to tool_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.intapi_company_user_group TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.secondary_region_tree_ctrl TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.secondary_region_tree_log TO tool_user;

grant select, insert, update, delete on csrimp.issue_template to tool_user;
grant select, insert, update, delete on csrimp.issue_template_custom_field to tool_user;
grant select, insert, update, delete on csrimp.issue_template_cust_field_opt to tool_user;

grant select, insert, update on csrimp.core_working_hours to tool_user;
grant select, insert, update on csrimp.core_working_hours_day to tool_user;
grant select, insert, update on csrimp.core_working_hours_region to tool_user;

grant select, insert, update, delete on csrimp.osha_mapping to tool_user;

grant select, insert, update, delete on csrimp.sys_translations_audit_log to tool_user;
grant select, insert, update, delete on csrimp.sys_translations_audit_data to tool_user;

grant execute on chain.helper_pkg to csrimp;

grant select,insert,update,delete on csrimp.campaign to tool_user;
grant select,insert,update,delete on csrimp.campaign_region to tool_user;
grant select,insert,update,delete on csrimp.campaign_region_response to tool_user;

grant select,insert,update,delete on csrimp.credential_management to tool_user;
grant select,insert,update,delete on csrimp.integration_question_answer to tool_user;
grant select,insert,update,delete on csrimp.region_certificate to tool_user;
grant select,insert,update,delete on csrimp.region_energy_rating to tool_user;
grant select,insert,update,delete on csrimp.module_history to tool_user;

grant select,insert,update,delete on csrimp.baseline_config to tool_user;
grant select,insert,update,delete on csrimp.baseline_config_period to tool_user;
grant select,insert,update,delete on csrimp.calc_baseline_config_dependency to tool_user;