

-- 
-- TABLE: VERSION 
--

CREATE TABLE VERSION(
    DB_VERSION    NUMBER(10, 0)    NOT NULL
)
;

INSERT INTO VERSION VALUES (12);


CREATE TABLE CUSTOM_VALUE(
    SCHEME_SID      NUMBER(10, 0)     NOT NULL,
    FIELD_NUM       NUMBER(2, 0)      NOT NULL,
    LABEL           VARCHAR2(255)     NOT NULL,
    EXPR            VARCHAR2(1024),
    IS_MANDATORY    NUMBER(1, 0)       DEFAULT 0 NOT NULL,
    NOTE            VARCHAR2(1024),
    LOOKUP_KEY		VARCHAR2(255) NOT NULL,
    IS_CURRENCY		NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK76 PRIMARY KEY (SCHEME_SID, FIELD_NUM)
)
;

CREATE UNIQUE INDEX AK_CUSTOM_VALUE ON CUSTOM_VALUE(SCHEME_SID, LOOKUP_KEY)
;


-- TABLE: CUSTOM_FIELD 
--

ALTER TABLE CUSTOM_VALUE ADD CONSTRAINT RefSCHEME107 
    FOREIGN KEY (SCHEME_SID)
    REFERENCES SCHEME(SCHEME_SID)
;

ALTER TABLE DONATION ADD (
    CUSTOM_1                      NUMBER(16, 2),
    CUSTOM_2                      NUMBER(16, 2),
    CUSTOM_3                      NUMBER(16, 2),
    CUSTOM_4                      NUMBER(16, 2),
    CUSTOM_5                      NUMBER(16, 2)
);


COMMIT;

PROMPT
PROMPT ================== UPDATED OK ========================
EXIT


