
CREATE SEQUENCE USER_FIELDSET_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE TABLE USER_FIELDSET(
    USER_FIELDSET_ID    NUMBER(10, 0)    NOT NULL,
    APP_SID             NUMBER(10, 0)    NOT NULL,
    CSR_USER_SID        NUMBER(10, 0)    NOT NULL,
    NAME                VARCHAR2(512),
    CONSTRAINT PK69 PRIMARY KEY (USER_FIELDSET_ID)
);

CREATE TABLE USER_FIELDSET_FIELD(
    FIELD_NAME          VARCHAR2(512)    NOT NULL,
    USER_FIELDSET_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK67 PRIMARY KEY (FIELD_NAME, USER_FIELDSET_ID)
);


ALTER TABLE USER_FIELDSET_FIELD ADD CONSTRAINT RefUSER_FIELDSET101 
    FOREIGN KEY (USER_FIELDSET_ID)
    REFERENCES USER_FIELDSET(USER_FIELDSET_ID)
;

COMMIT;
