
ALTER TABLE REGION_GROUP
	DROP CONSTRAINT RefCURRENCY74;

ALTER TABLE REGION_GROUP
	DROP COLUMN CURRENCY_CODE;

ALTER TABLE BUDGET ADD (
	CURRENCY_CODE       VARCHAR2(4)      NULL
);

UPDATE BUDGET SET CURRENCY_CODE = 'GBP';
COMMIT;

ALTER TABLE BUDGET MODIFY (
	CURRENCY_CODE       VARCHAR2(4)      NOT NULL
);

ALTER TABLE BUDGET ADD CONSTRAINT RefCURRENCY103 
    FOREIGN KEY (CURRENCY_CODE)
    REFERENCES CURRENCY(CURRENCY_CODE);
