set serveroutput on
set echo off

@@test_core_access_pkg
@@test_core_access_body



BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'CREATE USER TESTCOREACCESS IDENTIFIED BY TESTCOREACCESS TEMPORARY TABLESPACE TEMP DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
		--EXECUTE IMMEDIATE 'CREATE TABLE TESTCOREACCESS.C$TESTCOREACCESSTABLE03(TEST VARCHAR2(255))';
		--EXECUTE IMMEDIATE 'grant ALL ON TESTCOREACCESS.C$TESTCOREACCESSTABLE03 to cms';
		--EXECUTE IMMEDIATE 'grant ALL ON TESTCOREACCESS.C$TESTCOREACCESSTABLE03 to csr';
	EXCEPTION
		WHEN OTHERS THEN NULL;
	END;
	
	-- Run all tests in package
	csr.unit_test_pkg.RunTests('csr.test_core_access_pkg', :bv_site_name);

	BEGIN
	null;
		--EXECUTE IMMEDIATE 'DROP TABLE TESTCOREACCESS.C$TESTCOREACCESSTABLE03';
		EXECUTE IMMEDIATE 'DROP USER TESTCOREACCESS CASCADE';
	EXCEPTION
		WHEN OTHERS THEN NULL;
	END;
END;
/

-- No need to keep the test fixture package after tests have ran
DROP PACKAGE csr.test_core_access_pkg;

set echo on
