DECLARE
	TYPE t_tabs IS TABLE OF VARCHAR2(30); --table names
	v_list t_tabs := t_tabs(
		'CMP_FLOW_SIMPLE_STAGING',
		'CMP_FLOW_MULTIPLE_STAGING',
		'CMP_FLOW_PK_COMPANY'
	);
BEGIN
	security.user_pkg.logonadmin(:bv_site_name);
	
	-- Unregister table if there is one
	FOR i IN 1 .. v_list.COUNT 
	LOOP
		FOR r IN (
			SELECT oracle_table
			  FROM cms.tab 
			 WHERE oracle_schema = 'RAG' 
			   AND oracle_table = v_list(i)
		)
		LOOP
			cms.tab_pkg.UnregisterTable(
				in_oracle_schema => 'RAG',
				in_oracle_table	 => r.oracle_table
			);
		END LOOP;
	END LOOP;

	FOR i IN 1 .. v_list.COUNT 
	LOOP
		cms.tab_pkg.DropTable('RAG', v_list(i), true);
	END LOOP;
END;
/

CREATE TABLE rag.CMP_FLOW_SIMPLE_STAGING (
	FLOW_COMPANY_SIMPLE_ID			NUMBER(10),
	FLOW_ITEM_ID					NUMBER(10),
	FLOW_ITEM_DESCRIPTION			VARCHAR2(40),
    FLOW_COMPANY_SID				NUMBER(10),
	CONSTRAINT PK_FLOW_CMP_TEST_REGION_SIMPLE PRIMARY KEY (FLOW_COMPANY_SIMPLE_ID)
);

COMMENT ON TABLE rag.CMP_FLOW_SIMPLE_STAGING IS 'desc="Flow Test Simple"';
COMMENT ON COLUMN rag.CMP_FLOW_SIMPLE_STAGING.FLOW_COMPANY_SIMPLE_ID IS 'desc="Flow Simple ID",auto';
COMMENT ON COLUMN rag.CMP_FLOW_SIMPLE_STAGING.FLOW_ITEM_ID IS 'desc="Flow Item ID",flow_item';
COMMENT ON COLUMN rag.CMP_FLOW_SIMPLE_STAGING.FLOW_ITEM_DESCRIPTION IS 'desc="Flow Item Label"'; 
COMMENT ON COLUMN rag.CMP_FLOW_SIMPLE_STAGING.FLOW_COMPANY_SID IS 'desc="Flow Company",flow_company';

CREATE TABLE rag.CMP_FLOW_MULTIPLE_STAGING (
	FLOW_COMPANY_MULTI_ID			NUMBER(10),
	FLOW_ITEM_ID					NUMBER(10),
	FLOW_ITEM_DESCRIPTION			VARCHAR2(40),
    FLOW_COMPANY_SID				NUMBER(10),
    FLOW_COMPANY_2_SID				NUMBER(10),
	CONSTRAINT PK_CMP_FLOW_MLT_ST PRIMARY KEY (FLOW_COMPANY_MULTI_ID)
);

COMMENT ON TABLE rag.CMP_FLOW_MULTIPLE_STAGING IS 'desc="Flow Company Test"';
COMMENT ON COLUMN rag.CMP_FLOW_MULTIPLE_STAGING.FLOW_COMPANY_MULTI_ID IS 'desc="Flow Company Multi ID",auto';
COMMENT ON COLUMN rag.CMP_FLOW_MULTIPLE_STAGING.FLOW_ITEM_ID IS 'desc="Flow Item ID",flow_item';
COMMENT ON COLUMN rag.CMP_FLOW_MULTIPLE_STAGING.FLOW_ITEM_DESCRIPTION IS 'desc="Flow Item Label"'; 
COMMENT ON COLUMN rag.CMP_FLOW_MULTIPLE_STAGING.FLOW_COMPANY_SID IS 'desc="Flow Company",flow_company';
COMMENT ON COLUMN rag.CMP_FLOW_MULTIPLE_STAGING.FLOW_COMPANY_2_SID IS 'desc="Flow Company 2",flow_company';

CREATE TABLE rag.CMP_FLOW_PK_COMPANY (
	FLOW_COMPANY_CMP_SID			NUMBER(10),
	SOME_INFORMATION				VARCHAR2(40),
	FLOW_ITEM_DESCRIPTION			VARCHAR2(40),
	CONSTRAINT PK_CMP_FLOW_PK_CMP PRIMARY KEY (FLOW_COMPANY_CMP_SID)
);

COMMENT ON TABLE rag.CMP_FLOW_PK_COMPANY IS 'desc="Flow Company Test"';
COMMENT ON COLUMN rag.CMP_FLOW_PK_COMPANY.FLOW_COMPANY_CMP_SID IS 'desc="Flow Company Multi ID",company,auto';
COMMENT ON COLUMN rag.CMP_FLOW_PK_COMPANY.SOME_INFORMATION IS 'desc="Some Information"';
COMMENT ON COLUMN rag.CMP_FLOW_PK_COMPANY.FLOW_ITEM_DESCRIPTION IS 'desc="Item Description"'; 

GRANT SELECT, INSERT, UPDATE, DELETE ON RAG.CMP_FLOW_SIMPLE_STAGING TO csr;
GRANT SELECT, INSERT, UPDATE, DELETE ON RAG.CMP_FLOW_MULTIPLE_STAGING TO csr;
GRANT SELECT, INSERT, UPDATE, DELETE ON RAG.CMP_FLOW_PK_COMPANY TO csr;

DECLARE
	v_tabs VARCHAR2(4000);
BEGIN
	security.user_pkg.logonadmin(:bv_site_name);
	
	v_tabs := 'CMP_FLOW_SIMPLE_STAGING,CMP_FLOW_MULTIPLE_STAGING,CMP_FLOW_PK_COMPANY';
	
	cms.tab_pkg.RegisterTable(
		in_oracle_schema => 'RAG',
		in_oracle_table => v_tabs,
		in_managed => FALSE
	);
END;
/