CREATE OR REPLACE PACKAGE csr.test_period_pkg AS

CHECK_CONSTRAINT_VIOLATED EXCEPTION;
PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);

PROCEDURE TestGetPeriodNumberMonthly;
PROCEDURE TestGetPeriodNumber;
PROCEDURE TestGetPeriodDate;
PROCEDURE TestPeriodDatesCannotBeInvalid;
PROCEDURE SetUpFixture(in_site_name VARCHAR2);
PROCEDURE SetUp;
PROCEDURE TearDown;
PROCEDURE TearDownFixture;

END;
/
