CREATE OR REPLACE PACKAGE csr.test_energy_star_pkg AS

PROCEDURE SetUpFixture;
PROCEDURE SetUp;

PROCEDURE TearDown;
PROCEDURE TearDownFixture;

-- Tests
PROCEDURE TestPrepConsumptionDataWithDataAfterLockShouldSucceed;
PROCEDURE TestPrepConsumptionDataWithDataBeforeLockShouldThrowLockPeriodException;
PROCEDURE TestPrepConsumptionDataWithDataPartiallyPastLockShouldThrowLockPeriodException;
PROCEDURE TestPrepConsumptionDataWhenLockIgnoredWithDataAfterLockShouldSucceed;
PROCEDURE TestPrepConsumptionDataWhenLockIgnoredWithDataBeforeLockShouldSucceed;
PROCEDURE TestPrepConsumptionDataWhenLockIgnoredWithDataPartiallyPastLockShouldSucceed;

PROCEDURE TestOnRegionChange;

END test_energy_star_pkg;
/
