CREATE OR REPLACE PACKAGE csr.test_issue_custom_field_pkg AS

PROCEDURE GetIssueDetails_UserHasAccessToCustomFieldsWithSharedGroup;

PROCEDURE GetIssueDetails_UserHasNoAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetIssueDetails_UserWithIssueManagementCapabilityHasAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetIssueType_UserHasAccessToCustomFieldsWithSharedGroup;

PROCEDURE GetIssueType_UserHasNoAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetIssueType_UserWithIssueManagementCapabilityHasAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetCustomFieldsForIssues_UserHasAccessToCustomFieldsWithSharedGroup;

PROCEDURE GetCustomFieldsForIssues_UserHasNoAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetCustomFieldsForIssues_UserWithIssueManagementCapabilityHasAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetList_UserHasAccessToCustomFieldsWithSharedGroup;

PROCEDURE GetList_UserHasNoAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetList_UserWithIssueManagementCapabilityHasAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetCustomFields_UserHasAccessToCustomFieldsWithSharedGroup;

PROCEDURE GetCustomFields_UserHasNoAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE GetCustomFields_UserWithIssueManagementCapabilityHasAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE ExportFindingsAndActions_UserHasAccessToCustomFieldsWithSharedGroup;

PROCEDURE ExportFindingsAndActions_UserHasNoAccessToCustomFieldsWithNoSharedGroup;

PROCEDURE ExportFindingsAndActions_UserWithIssueManagementCapabilityHasAccessToCustomFieldsWithNoSharedGroup;

-- Called before each test
PROCEDURE SetUp;

-- Called after each PASSED test
PROCEDURE TearDown;

-- Called once before starting a test fixture
PROCEDURE SetUpFixture;

-- Called once after all tests have PASSED
PROCEDURE TearDownFixture;

END;
/
