/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases V7.3.6                     */
/* Target DBMS:           Oracle 10g                                      */
/* Project file:          chem.dez                                        */
/* Project name:                                                          */
/* Author:                                                                */
/* Script type:           Database creation script                        */
/* Created on:            2014-10-30 14:28                                */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Add sequences                                                          */
/* ---------------------------------------------------------------------- */

CREATE SEQUENCE CHEM.SUBSTANCE_USE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.PROCESS_DEST_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.MANUFACTURER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.USAGE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBSTANCE_FILE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.CLASSIFICATION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBSTANCE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.CAS_GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.USAGE_AUDIT_LOG_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUB_AUDIT_LOG_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBSTANCE_PROCESS_USE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBST_PROC_CAS_DEST_CHG_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBST_PROC_USE_CHANGE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBST_PROC_USE_FILE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

CREATE SEQUENCE CHEM.SUBST_RGN_PROC_PROCESS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    CACHE 5
    noorder;

/* ---------------------------------------------------------------------- */
/* Add tables                                                             */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.CHEM_OPTIONS (
    APP_SID                 NUMBER(10, 0)       DEFAULT sys_context('SECURITY', 'APP') NOT NULL,
    CHEM_HELPER_PKG         VARCHAR(255),
    CONSTRAINT PK_CHEM_OPTIONS PRIMARY KEY (APP_SID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.CAS"                                                   */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.CAS (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(4000) NOT NULL,
    UNCONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    IS_VOC NUMBER(1) DEFAULT 0 NOT NULL,
    CATEGORY VARCHAR2(20),
    CONSTRAINT PK_CAS PRIMARY KEY (APP_SID, CAS_CODE)
);

ALTER TABLE CHEM.CAS ADD CONSTRAINT CHK_CAS_IS_VOC 
    CHECK (is_voc IN (0,1));

ALTER TABLE CHEM.CAS ADD CONSTRAINT CHK_CAS_UNCONFIRMED 
    CHECK (UNCONFIRMED IN (0,1));

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.CAS_RESTRICTED"                                        */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.CAS_RESTRICTED (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    ROOT_REGION_SID NUMBER(10) NOT NULL,
    START_DTM DATE,
    END_DTM DATE,
    REMARKS VARCHAR2(2048),
    SOURCE VARCHAR2(200),
    CLP_TABLE_3_1 VARCHAR2(1024),
    CLP_TABLE_3_2 VARCHAR2(1024),
    CONSTRAINT PK_CAS_RESTRICTED PRIMARY KEY (APP_SID, CAS_CODE, ROOT_REGION_SID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.CLASSIFICATION"                                        */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.CLASSIFICATION (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CLASSIFICATION_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    CONSTRAINT PK_CLASSIFICATION PRIMARY KEY (APP_SID, CLASSIFICATION_ID)
);

CREATE UNIQUE INDEX CHEM.UK_CLASSIFICATION ON CHEM.CLASSIFICATION (APP_SID,UPPER(DESCRIPTION));

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.MANUFACTURER"                                          */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.MANUFACTURER (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    MANUFACTURER_ID NUMBER(10) NOT NULL,
    CODE VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_MANUFACTURER PRIMARY KEY (APP_SID, MANUFACTURER_ID)
);

CREATE UNIQUE INDEX CHEM.UK_MANUFACTURER ON CHEM.MANUFACTURER (APP_SID,NAME);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE"                                             */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REF VARCHAR2(20),
    DESCRIPTION VARCHAR2(500),
    CLASSIFICATION_ID NUMBER(10) NOT NULL,
    MANUFACTURER_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10),
    IS_CENTRAL NUMBER(1),
    CONSTRAINT PK_SUBSTANCE PRIMARY KEY (APP_SID, SUBSTANCE_ID),
    CONSTRAINT UK_SUBSTANCE UNIQUE (APP_SID, REF)
);

ALTER TABLE CHEM.SUBSTANCE ADD
    CHECK (is_central IN (0,1));

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_CAS"                                         */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_CAS (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    PCT_COMPOSITION NUMBER(5,4),
    CONSTRAINT PK_SUBSTANCE_CAS PRIMARY KEY (APP_SID, SUBSTANCE_ID, CAS_CODE)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_FILE"                                        */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_FILE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_FILE_ID NUMBER(10) NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    DATA BLOB,
    UPLOADED_DTM DATE DEFAULT SYSDATE,
    UPLOADED_USER_SID NUMBER(10),
    MIME_TYPE VARCHAR2(256) NOT NULL,
    URL VARCHAR2(2048),
    FILENAME VARCHAR2(2048),
    CONSTRAINT PK_SUBSTANCE_FILE PRIMARY KEY (APP_SID, SUBSTANCE_FILE_ID, SUBSTANCE_ID),
    CONSTRAINT CHK_SUBSTANCE_FILE CHECK (((FILENAME IS NULL AND MIME_TYPE IS NULL) AND URL IS NOT NULL) OR ((FILENAME IS NOT NULL AND MIME_TYPE IS NOT NULL) AND URL IS NULL))
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.USAGE"                                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.USAGE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    USAGE_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    CONSTRAINT PK_USAGE PRIMARY KEY (APP_SID, USAGE_ID)
);

CREATE UNIQUE INDEX CHEM.UK_USAGE ON CHEM.USAGE (APP_SID,UPPER(DESCRIPTION));

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.WAIVER_STATUS"                                         */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.WAIVER_STATUS (
    WAIVER_STATUS_ID NUMBER(1) NOT NULL,
    DESCRIPTION VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_WAIVER_STATUS PRIMARY KEY (WAIVER_STATUS_ID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.USAGE_AUDIT_LOG"                                       */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.USAGE_AUDIT_LOG (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    USAGE_AUDIT_LOG_ID NUMBER(10) NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10),
    ROOT_DELEGATION_SID NUMBER(10),
    START_DTM DATE,
    END_DTM DATE,
    DESCRIPTION VARCHAR2(1024) NOT NULL,
    PARAM_1 VARCHAR2(1024),
    PARAM_2 VARCHAR2(1024),
    CHANGED_BY NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'SID') NOT NULL,
    CHANGED_DTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USAGE_AUDIT_LOG PRIMARY KEY (APP_SID, USAGE_AUDIT_LOG_ID, SUBSTANCE_ID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_AUDIT_LOG"                                   */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_AUDIT_LOG (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_AUDIT_LOG_ID NUMBER(10) NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(1024) NOT NULL,
    PARAM_1 VARCHAR2(1024),
    PARAM_2 VARCHAR2(1024),
    CHANGED_BY NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'SID') NOT NULL,
    CHANGED_DTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_SUBSTANCE_AUDIT_LOG PRIMARY KEY (APP_SID, SUBSTANCE_AUDIT_LOG_ID, SUBSTANCE_ID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_REGION"                                      */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_REGION (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10) NOT NULL,
    WAIVER_STATUS_ID NUMBER(1),
    FIRST_USED_DTM DATE,
    LOCAL_REF VARCHAR2(40),
    FLOW_ITEM_ID NUMBER(10),
    CONSTRAINT PK_SUBSTANCE_REGION PRIMARY KEY (APP_SID, SUBSTANCE_ID, REGION_SID),
	CONSTRAINT UC_SUBSTANCE_FLOW_ITEM UNIQUE (FLOW_ITEM_ID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_REGION_PROCESS"                              */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_REGION_PROCESS (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10) NOT NULL,
    PROCESS_ID NUMBER(10) NOT NULL,
    LABEL VARCHAR2(255) DEFAULT 'Default' NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    USAGE_ID NUMBER(10) NOT NULL,
    FIRST_USED_DTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_SUBSTANCE_REGION_PROCESS PRIMARY KEY (APP_SID, SUBSTANCE_ID, REGION_SID, PROCESS_ID)
);

CREATE UNIQUE INDEX CHEM.IDX_SUBSTANCE_REGION_PROCESS ON CHEM.SUBSTANCE_REGION_PROCESS (APP_SID,SUBSTANCE_ID,REGION_SID,CASE WHEN ACTIVE = 0 THEN PROCESS_ID WHEN ACTIVE = 1 THEN -1 END,UPPER(LABEL));

ALTER TABLE CHEM.SUBSTANCE_REGION_PROCESS ADD CONSTRAINT CHK_SUBSTANCE_REGN_PROC_ACTIVE 
    CHECK (ACTIVE IN (0,1));

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_PROCESS_USE_CHANGE"                          */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_PROCESS_USE_CHANGE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBST_PROC_USE_CHANGE_ID NUMBER(10) NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10) NOT NULL,
    PROCESS_ID NUMBER(10) NOT NULL,
    ROOT_DELEGATION_SID NUMBER(10),
    START_DTM DATE,
    END_DTM DATE,
    MASS_VALUE NUMBER(24,10),
    NOTE CLOB,
    ENTRY_STD_MEASURE_CONV_ID NUMBER(10),
    ENTRY_MASS_VALUE NUMBER(24,10),
    CHANGED_BY NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'SID') NOT NULL,
    CHANGED_DTM TIMESTAMP DEFAULT sys_extract_utc(systimestamp) NOT NULL,
    RETIRED_DTM TIMESTAMP,
    CONSTRAINT PK_SUBST_PROC_USE_CHANGE PRIMARY KEY (APP_SID, SUBST_PROC_USE_CHANGE_ID)
);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE_CHANGE ADD CONSTRAINT CK_SUBST_PROC_USE_CH_END_DTM 
    CHECK (TRUNC(END_DTM,'MON')=END_DTM);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE_CHANGE ADD CONSTRAINT CK_SUBST_PROC_USE_CH_START_DTM 
    CHECK (TRUNC(START_DTM,'MON') = START_DTM);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.PROCESS_CAS_DEFAULT"                                   */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.PROCESS_CAS_DEFAULT (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10) NOT NULL,
    PROCESS_ID NUMBER(10) NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    TO_AIR_PCT NUMBER(5,4) NOT NULL,
    TO_PRODUCT_PCT NUMBER(5,4) NOT NULL,
    TO_WASTE_PCT NUMBER(5,4) NOT NULL,
    TO_WATER_PCT NUMBER(5,4) NOT NULL,
    REMAINING_PCT NUMBER(5,4) NOT NULL,
    REMAINING_DEST VARCHAR2(100),
    CONSTRAINT PK_PROCESS_CAS_DEFAULT PRIMARY KEY (APP_SID, SUBSTANCE_ID, REGION_SID, PROCESS_ID, CAS_CODE),
    CONSTRAINT CHK_PROCESS_CAS_DEFAULT CHECK (TO_AIR_PCT >= 0 AND TO_PRODUCT_PCT >= 0 AND TO_WASTE_PCT >= 0 AND TO_WATER_PCT >= 0 AND REMAINING_PCT >= 0 AND (TO_AIR_PCT + TO_PRODUCT_PCT + TO_WASTE_PCT + TO_WATER_PCT + REMAINING_PCT) <= 1)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_PROCESS_USE"                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_PROCESS_USE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_PROCESS_USE_ID NUMBER(10) NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    REGION_SID NUMBER(10) NOT NULL,
    PROCESS_ID NUMBER(10) NOT NULL,
    ROOT_DELEGATION_SID NUMBER(10) NOT NULL,
    MASS_VALUE NUMBER(24,10),
    NOTE CLOB,
    START_DTM DATE,
    END_DTM DATE,
    ENTRY_STD_MEASURE_CONV_ID NUMBER(10),
    ENTRY_MASS_VALUE NUMBER(24,10),
    CHANGED_SINCE_PREV_PERIOD NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SUBSTANCE_PROCESS_USE PRIMARY KEY (APP_SID, SUBSTANCE_PROCESS_USE_ID),
    CONSTRAINT UC_SUBSTANCE_PROCESS_USE UNIQUE (APP_SID, SUBSTANCE_ID, REGION_SID, PROCESS_ID, ROOT_DELEGATION_SID, START_DTM, END_DTM),
    CONSTRAINT UC_SUBSTANCE_PROCESS_USE_2 UNIQUE (APP_SID, SUBSTANCE_PROCESS_USE_ID, SUBSTANCE_ID)
);

CREATE INDEX CHEM.IDX_SUBSTANCE_PROCESS_USE ON CHEM.SUBSTANCE_PROCESS_USE (APP_SID,START_DTM,END_DTM);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE ADD CONSTRAINT CHK_SUBS_PR_USE_CH_PP 
    CHECK (CHANGED_SINCE_PREV_PERIOD IN (0,1));

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE ADD CONSTRAINT CK_SUBST_PROC_USE_END_DTM 
    CHECK (TRUNC(END_DTM,'MON')=END_DTM);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE ADD CONSTRAINT CK_SUBST_PROC_USE_START_DTM 
    CHECK (TRUNC(START_DTM,'MON') = START_DTM);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_PROCESS_USE_FILE"                            */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_PROCESS_USE_FILE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_PROCESS_USE_FILE_ID NUMBER(10) NOT NULL,
    SUBSTANCE_PROCESS_USE_ID NUMBER(10) NOT NULL,
    DATA BLOB,
    UPLOADED_DTM DATE DEFAULT SYSDATE,
    UPLOADED_USER_SID NUMBER(10),
    MIME_TYPE VARCHAR2(255),
    FILENAME VARCHAR2(2048),
    CONSTRAINT PK_SUBSTANCE_PROCESS_USE_FILE PRIMARY KEY (APP_SID, SUBSTANCE_PROCESS_USE_FILE_ID),
    CONSTRAINT UK_SUBSTANCE_PROCESS_USE_FILE UNIQUE (APP_SID, SUBSTANCE_PROCESS_USE_ID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBSTANCE_PROCESS_CAS_DEST"                            */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBSTANCE_PROCESS_CAS_DEST (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBSTANCE_PROCESS_USE_ID NUMBER(10) NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    SUBSTANCE_ID NUMBER(10) NOT NULL,
    TO_AIR_PCT NUMBER(5,4) NOT NULL,
    TO_PRODUCT_PCT NUMBER(5,4) NOT NULL,
    TO_WASTE_PCT NUMBER(5,4) NOT NULL,
    TO_WATER_PCT NUMBER(5,4) NOT NULL,
    REMAINING_PCT NUMBER(5,4) NOT NULL,
    REMAINING_DEST VARCHAR2(100),
    CONSTRAINT PK_SUBSTANCE_PROCESS_CAS_DEST PRIMARY KEY (APP_SID, SUBSTANCE_PROCESS_USE_ID, CAS_CODE),
    CONSTRAINT CHK_SUBSTANCE_PROCESS_CAS_DEST CHECK (TO_AIR_PCT >= 0 AND TO_PRODUCT_PCT >= 0 AND TO_WASTE_PCT >= 0 AND TO_WATER_PCT >= 0 AND REMAINING_PCT >= 0 AND (TO_AIR_PCT + TO_PRODUCT_PCT + TO_WASTE_PCT + TO_WATER_PCT + REMAINING_PCT) <= 1)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.SUBST_PROCESS_CAS_DEST_CHANGE"                         */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.SUBST_PROCESS_CAS_DEST_CHANGE (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SUBST_PROC_CAS_DEST_CHANGE_ID NUMBER(10) NOT NULL,
    SUBST_PROC_USE_CHANGE_ID NUMBER(10) NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    TO_AIR_PCT NUMBER(5,4) NOT NULL,
    TO_PRODUCT_PCT NUMBER(5,4) NOT NULL,
    TO_WASTE_PCT NUMBER(5,4) NOT NULL,
    TO_WATER_PCT NUMBER(5,4) NOT NULL,
    REMAINING_PCT NUMBER(5,4) NOT NULL,
    REMAINING_DEST VARCHAR2(100),
    CHANGED_BY NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'SID') NOT NULL,
    CHANGED_DTM TIMESTAMP DEFAULT sys_extract_utc(systimestamp) NOT NULL,
    RETIRED_DTM DATE,
    CONSTRAINT PK_SUBST_PROC_CAS_DEST_CHANGE PRIMARY KEY (APP_SID, SUBST_PROC_CAS_DEST_CHANGE_ID)
);

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.CAS_GROUP"                                             */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.CAS_GROUP (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CAS_GROUP_ID NUMBER(10) NOT NULL,
    PARENT_GROUP_ID NUMBER(10),
    LABEL VARCHAR2(255),
    LOOKUP_KEY VARCHAR2(64),
    CONSTRAINT PK_CAS_GROUP PRIMARY KEY (APP_SID, CAS_GROUP_ID)
);

CREATE UNIQUE INDEX CHEM.IDX_CAS_GROUP_1 ON CHEM.CAS_GROUP (APP_SID,NVL(UPPER(LOOKUP_KEY),'CGID'||CAS_GROUP_ID));

/* ---------------------------------------------------------------------- */
/* Add table "CHEM.CAS_GROUP_MEMBER"                                      */
/* ---------------------------------------------------------------------- */

CREATE TABLE CHEM.CAS_GROUP_MEMBER (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CAS_GROUP_ID NUMBER(10) NOT NULL,
    CAS_CODE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CAS_GROUP_MEMBER PRIMARY KEY (APP_SID, CAS_GROUP_ID, CAS_CODE)
);

CREATE UNIQUE INDEX CHEM.IDX_CAS_GROUP_MEMBER_1 ON CHEM.CAS_GROUP_MEMBER (APP_SID,CAS_CODE);

/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

ALTER TABLE CHEM.CAS_RESTRICTED ADD CONSTRAINT FK_CAS_CAS_RESTR 
    FOREIGN KEY (APP_SID, CAS_CODE) REFERENCES CHEM.CAS (APP_SID, CAS_CODE);

ALTER TABLE CHEM.SUBSTANCE ADD CONSTRAINT FK_MFR_SUBST 
    FOREIGN KEY (APP_SID, MANUFACTURER_ID) REFERENCES CHEM.MANUFACTURER (APP_SID,MANUFACTURER_ID);

ALTER TABLE CHEM.SUBSTANCE ADD CONSTRAINT FK_CLASSIF_SUBST 
    FOREIGN KEY (APP_SID, CLASSIFICATION_ID) REFERENCES CHEM.CLASSIFICATION (APP_SID,CLASSIFICATION_ID);

ALTER TABLE CHEM.SUBSTANCE_CAS ADD CONSTRAINT FK_CAS_SUBST_CAS 
    FOREIGN KEY (APP_SID, CAS_CODE) REFERENCES CHEM.CAS (APP_SID, CAS_CODE);

ALTER TABLE CHEM.SUBSTANCE_CAS ADD CONSTRAINT FK_SUBST_SUBST_CAS 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE (APP_SID,SUBSTANCE_ID);

ALTER TABLE CHEM.PROCESS_CAS_DEFAULT ADD CONSTRAINT FK_SUBST_RGN_PROC_PROC_CAS 
    FOREIGN KEY (APP_SID, PROCESS_ID, SUBSTANCE_ID, REGION_SID) REFERENCES CHEM.SUBSTANCE_REGION_PROCESS (APP_SID,PROCESS_ID,SUBSTANCE_ID,REGION_SID);

ALTER TABLE CHEM.PROCESS_CAS_DEFAULT ADD CONSTRAINT FK_SUBST_CAS_PROC_CAS 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID, CAS_CODE) REFERENCES CHEM.SUBSTANCE_CAS (APP_SID,SUBSTANCE_ID,CAS_CODE);

ALTER TABLE CHEM.SUBSTANCE_FILE ADD CONSTRAINT FK_SUBST_SUBST_FILE 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE (APP_SID,SUBSTANCE_ID);

ALTER TABLE CHEM.SUBSTANCE_REGION ADD CONSTRAINT FK_SUBST_SUBST_RGN 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE (APP_SID,SUBSTANCE_ID);

ALTER TABLE CHEM.SUBSTANCE_REGION ADD CONSTRAINT FK_WAIVR_STAT_SUBST_RGN 
    FOREIGN KEY (WAIVER_STATUS_ID) REFERENCES CHEM.WAIVER_STATUS (WAIVER_STATUS_ID);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE ADD CONSTRAINT FK_SUBST_RGN_PROC_SUBST_PROC_U 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID, REGION_SID, PROCESS_ID) REFERENCES CHEM.SUBSTANCE_REGION_PROCESS (APP_SID,SUBSTANCE_ID,REGION_SID,PROCESS_ID);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE_FILE ADD CONSTRAINT FK_SUBST_PROC_USE_SUBST_USE_F 
    FOREIGN KEY (APP_SID, SUBSTANCE_PROCESS_USE_ID) REFERENCES CHEM.SUBSTANCE_PROCESS_USE (APP_SID,SUBSTANCE_PROCESS_USE_ID);

ALTER TABLE CHEM.SUBSTANCE_REGION_PROCESS ADD CONSTRAINT FK_USAGE_SUBST_RGN_PROC 
    FOREIGN KEY (APP_SID, USAGE_ID) REFERENCES CHEM.USAGE (APP_SID,USAGE_ID);

ALTER TABLE CHEM.SUBSTANCE_REGION_PROCESS ADD CONSTRAINT FK_SUBST_RGN_SUBST_RGN_PROC 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID, REGION_SID) REFERENCES CHEM.SUBSTANCE_REGION (APP_SID,SUBSTANCE_ID,REGION_SID);

ALTER TABLE CHEM.CAS_GROUP ADD CONSTRAINT FK_CAS_GRP_CAS_GRP 
    FOREIGN KEY (APP_SID, PARENT_GROUP_ID) REFERENCES CHEM.CAS_GROUP (APP_SID,CAS_GROUP_ID);

ALTER TABLE CHEM.CAS_GROUP_MEMBER ADD CONSTRAINT FK_CAS_CAS_GRP_MBR 
    FOREIGN KEY (APP_SID, CAS_CODE) REFERENCES CHEM.CAS (APP_SID, CAS_CODE);

ALTER TABLE CHEM.CAS_GROUP_MEMBER ADD CONSTRAINT FK_CAS_GRP_CAS_GRP_MBR 
    FOREIGN KEY (APP_SID, CAS_GROUP_ID) REFERENCES CHEM.CAS_GROUP (APP_SID,CAS_GROUP_ID);

ALTER TABLE CHEM.USAGE_AUDIT_LOG ADD CONSTRAINT FK_SUBST_ 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE (APP_SID,SUBSTANCE_ID);

ALTER TABLE CHEM.SUBSTANCE_AUDIT_LOG ADD CONSTRAINT FK_SUBST_SUBST_AUDIT_LOG 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE (APP_SID,SUBSTANCE_ID);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_CAS_DEST ADD CONSTRAINT FK_SUBST_CAS_SUBST_UPCD 
    FOREIGN KEY (APP_SID, CAS_CODE, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE_CAS (APP_SID,CAS_CODE,SUBSTANCE_ID) ON DELETE CASCADE;

ALTER TABLE CHEM.SUBSTANCE_PROCESS_CAS_DEST ADD CONSTRAINT FK_SUBST_PROC_USE_SUBST_UPCD 
    FOREIGN KEY (APP_SID, SUBSTANCE_PROCESS_USE_ID, SUBSTANCE_ID) REFERENCES CHEM.SUBSTANCE_PROCESS_USE (APP_SID,SUBSTANCE_PROCESS_USE_ID,SUBSTANCE_ID);

ALTER TABLE CHEM.SUBST_PROCESS_CAS_DEST_CHANGE ADD CONSTRAINT FK_SUBST_PROC_USE_CAS_DEST_C 
    FOREIGN KEY (APP_SID, SUBST_PROC_USE_CHANGE_ID) REFERENCES CHEM.SUBSTANCE_PROCESS_USE_CHANGE (APP_SID,SUBST_PROC_USE_CHANGE_ID);

ALTER TABLE CHEM.SUBSTANCE_PROCESS_USE_CHANGE ADD CONSTRAINT FK_SBST_REG_PR_SBST_PR_USE_CH 
    FOREIGN KEY (APP_SID, SUBSTANCE_ID, REGION_SID, PROCESS_ID) REFERENCES CHEM.SUBSTANCE_REGION_PROCESS (APP_SID,SUBSTANCE_ID,REGION_SID,PROCESS_ID);
