CREATE OR REPLACE PACKAGE CHEM.SUBSTANCE_HELPER_PKG AS

/* NOTE THAT RECOMPILING THIS AGAINST LIVE MAY RESULT IN SESSIONS HANGING AS CSR.SHEET_PKG HAS
   A DEPENDENCY ON THIS CODE, SO RECOMPILE CAREFULLY!
*/

PROCEDURE UNSEC_CopyForward(
	in_sheet_Id			IN		security_pkg.T_SID_ID,
	out_cnt				OUT	NUMBER	
);


END;
/