create index supplier.ix_alert_batch_app_sid on supplier.alert_batch (app_sid);
create index supplier.ix_all_company_country_code on supplier.all_company (country_code);
create index supplier.ix_all_company_app_sid on supplier.all_company (app_sid);
create index supplier.ix_all_procurer__supplier_comp on supplier.all_procurer_supplier (supplier_company_sid);
create index supplier.ix_all_procurer__currency_code on supplier.all_procurer_supplier (currency_code);
create index supplier.ix_all_procurer__app_sid on supplier.all_procurer_supplier (app_sid);
create index supplier.ix_all_product_supplier_comp on supplier.all_product (supplier_company_sid);
create index supplier.ix_all_product_q_questionnrid on supplier.all_product_questionnaire (questionnaire_id);
create index supplier.ix_all_product_q_questionnst on supplier.all_product_questionnaire (questionnaire_status_id);
create index supplier.ix_chain_questio_quick_survey_ on supplier.chain_questionnaire (app_sid, quick_survey_sid);
create index supplier.ix_chain_questio_app_sid on supplier.chain_questionnaire (app_sid);
create index supplier.ix_company_part_company_sid on supplier.company_part (company_sid);
create index supplier.ix_company_part_parent_id on supplier.company_part (parent_id);
create index supplier.ix_company_part_part_type_id on supplier.company_part (part_type_id);
create index supplier.ix_company_quest_chain_questio on supplier.company_questionnaire_response (chain_questionnaire_id);
create index supplier.ix_company_quest_app_sid on supplier.company_questionnaire_response (app_sid);
create index supplier.ix_company_quest_response_stat on supplier.company_questionnaire_response (response_status_id);
create index supplier.ix_company_tag_company_sid on supplier.company_tag (company_sid);

--create index supplier.ix_company_user_csr_user_sid on supplier.company_user (app_sid, csr_user_sid);
create unique index supplier.uk_csr_user_sid on supplier.company_user (app_sid, csr_user_sid);

create index supplier.ix_company_user_user_profile_ on supplier.company_user (user_profile_visibility_id);
create index supplier.ix_contact_owner_company on supplier.contact (owner_company_sid);
create index supplier.ix_contact_existing_comp on supplier.contact (existing_company_sid);
create index supplier.ix_contact_existing_comp_usr on supplier.contact (existing_company_sid, existing_user_sid, app_sid);
create index supplier.ix_contact_registered_to on supplier.contact (registered_to_company_sid, registered_as_user_sid, app_sid);
create index supplier.ix_contact_contact_state on supplier.contact (contact_state_id);
create index supplier.ix_contact_country_code on supplier.contact (country_code);
create index supplier.ix_contact_currency_code on supplier.contact (currency_code);
create index supplier.ix_contact_app_sid on supplier.contact (app_sid);
create index supplier.ix_customer_peri_period_id on supplier.customer_period (period_id);
create index supplier.ix_document_grou_document_grou on supplier.document_group_member (document_group_id);
create index supplier.ix_invite_sent_by_compa on supplier.invite (sent_by_company_sid, sent_by_user_sid, app_sid);
create index supplier.ix_invite_sent_to_conta on supplier.invite (sent_to_contact_id, sent_by_company_sid, app_sid);
create index supplier.ix_invite_invite_status on supplier.invite (invite_status_id);
create index supplier.ix_invite_questi_chain_questio on supplier.invite_questionnaire (chain_questionnaire_id);
create index supplier.ix_invite_questi_last_msg_from on supplier.invite_questionnaire (last_msg_from_company_sid, last_msg_from_user_sid, app_sid);
create index supplier.ix_message_company_sid on supplier.message (company_sid);
create index supplier.ix_message_user_sid on supplier.message (app_sid, user_sid);
create index supplier.ix_message_group_sid on supplier.message (group_sid);
create index supplier.ix_message_message_templ on supplier.message (message_template_id);
create index supplier.ix_message_conta_contact_id_ow on supplier.message_contact (contact_id, owner_company_sid, app_sid);
create index supplier.ix_message_procu_procurer_comp on supplier.message_procurer_supplier (procurer_company_sid, supplier_company_sid, app_sid);
create index supplier.ix_message_quest_chain_questio on supplier.message_questionnaire (chain_questionnaire_id);
create index supplier.ix_message_templ_message_templ on supplier.message_template (message_template_format_id);
create index supplier.ix_message_user_user_sid on supplier.message_user (app_sid, user_sid);
create index supplier.ix_product_part_product_id on supplier.product_part (product_id);
create index supplier.ix_product_part_part_type_id on supplier.product_part (part_type_id);
create index supplier.ix_product_part_parent_id on supplier.product_part (parent_id);
create index supplier.ix_product_quest_group_status_ on supplier.product_questionnaire_group (group_status_id);
create index supplier.ix_product_quest_group_id on supplier.product_questionnaire_group (group_id);
create index supplier.ix_product_revis_group_id on supplier.product_revision_tag (group_id);
create index supplier.ix_product_revis_tag_id on supplier.product_revision_tag (tag_id);
create index supplier.ix_product_sales_period_id on supplier.product_sales_volume (period_id);
create index supplier.ix_product_tag_tag_id on supplier.product_tag (tag_id);
create index supplier.ix_questionnaire_workflow_type on supplier.questionnaire_group (workflow_type_id);
create index supplier.ix_questionnaire_group_id on supplier.questionnaire_group_membership (group_id);
create index supplier.ix_quest_procurer_supplier on supplier.questionnaire_request (procurer_company_sid, supplier_company_sid, app_sid);
create index supplier.ix_quest_supplier_chain_q on supplier.questionnaire_request (supplier_company_sid, chain_questionnaire_id);
create index supplier.ix_quest_supplier_user on supplier.questionnaire_request (supplier_company_sid, supplier_user_sid, app_sid);
create index supplier.ix_quest_procurer_user on supplier.questionnaire_request (procurer_company_sid, procurer_user_sid, app_sid);
create index supplier.ix_quest_supplier_rel_by on supplier.questionnaire_request (supplier_company_sid, released_by_user_sid, app_sid);
create index supplier.ix_questionnaire_request_statu on supplier.questionnaire_request (request_status_id);
create index supplier.ix_questionnaire_questionnaire on supplier.questionnaire_tag (questionnaire_id);
create index supplier.ix_tag_group_mem_tag_id on supplier.tag_group_member (tag_id);
create index supplier.ix_tag_tag_attri_tag_attribute on supplier.tag_tag_attribute (tag_attribute_id);
create index supplier.ix_unit_unit_type_id on supplier.unit (unit_type_id);
create index supplier.ix_user_report_s_tag_id on supplier.user_report_sales_types (tag_id);
create index supplier.ix_user_report_s_period_id on supplier.user_report_settings (period_id);
