create index supplier.ix_cert_scheme_s_cert_scheme_i on supplier.cert_scheme_source_cat_mapping (cert_scheme_id);
create index supplier.ix_gt_access_pac_gt_access_vis on supplier.gt_access_pack_mapping (gt_access_visc_type_id);
create index supplier.ix_gt_battery_gt_battery_ch on supplier.gt_battery (gt_battery_chem_id);
create index supplier.ix_gt_battery_ba_gt_battery_ty on supplier.gt_battery_battery_type (gt_battery_type_id);
create index supplier.ix_gt_country_ma_country_code on supplier.gt_country_made_in (country_code);
create index supplier.ix_gt_country_ma_product_id_re on supplier.gt_country_made_in (product_id, revision_id);
create index supplier.ix_gt_country_ma_gt_transport_ on supplier.gt_country_made_in (gt_transport_type_id);
create index supplier.ix_gt_country_re_gt_region_id on supplier.gt_country_region (gt_region_id);
create index supplier.ix_gt_country_so_country_code on supplier.gt_country_sold_in (country_code);
create index supplier.ix_gt_country_so_product_id_re on supplier.gt_country_sold_in (product_id, revision_id);
create index supplier.ix_gt_endangered_gt_endangered on supplier.gt_endangered_prod_class_map (gt_endangered_species_id);
create index supplier.ix_gt_fa_anc_mat_product_id_re on supplier.gt_fa_anc_mat (product_id, revision_id);
create index supplier.ix_gt_fa_endange_gt_endangered on supplier.gt_fa_endangered_sp (gt_endangered_species_id);
create index supplier.ix_gt_fa_haz_che_product_id_re on supplier.gt_fa_haz_chem (product_id, revision_id);
create index supplier.ix_gt_fa_palm_in_product_id_re on supplier.gt_fa_palm_ind (product_id, revision_id);
create index supplier.ix_gt_fa_wsr_gt_water_stre on supplier.gt_fa_wsr (gt_water_stress_region_id);
create index supplier.ix_gt_fd_answer__gt_fd_scheme_ on supplier.gt_fd_answer_scheme (gt_fd_scheme_id);
create index supplier.ix_gt_fd_answer__product_id_re on supplier.gt_fd_answer_scheme (product_id, revision_id);
create index supplier.ix_gt_fd_endange_gt_endangered on supplier.gt_fd_endangered_sp (gt_endangered_species_id);
create index supplier.ix_gt_fd_ingredi_gt_fd_ingred_ on supplier.gt_fd_ingredient (gt_fd_ingred_prov_type_id);
create index supplier.ix_gt_fd_ingredi_gt_fd_ingred_ on supplier.gt_fd_ingredient (gt_fd_ingred_type_id);
create index supplier.ix_gt_fd_ingredi_gt_water_stre on supplier.gt_fd_ingredient (gt_water_stress_region_id);
create index supplier.ix_gt_fd_ingred__gt_fd_ingred_ on supplier.gt_fd_ingred_type (gt_fd_ingred_group_id);
create index supplier.ix_gt_fd_palm_in_gt_palm_ingre on supplier.gt_fd_palm_ind (gt_palm_ingred_id);
create index supplier.ix_gt_food_anc_m_product_id_re on supplier.gt_food_anc_mat (product_id, revision_id);
create index supplier.ix_gt_food_answe_data_quality_ on supplier.gt_food_answers (data_quality_type_id);
create index supplier.ix_gt_food_answe_gt_fd_portion on supplier.gt_food_answers (gt_fd_portion_type_id);
create index supplier.ix_gt_food_answe_gt_water_stre on supplier.gt_food_answers (gt_water_stress_region_id);
create index supplier.ix_gt_food_sa_q_gt_sa_questio on supplier.gt_food_sa_q (gt_sa_question_id);
create index supplier.ix_gt_formulatio_data_quality_ on supplier.gt_formulation_answers (data_quality_type_id);
create index supplier.ix_gt_formulatio_bs_document_g on supplier.gt_formulation_answers (bs_document_group);
create index supplier.ix_gt_link_produ_link_product_ on supplier.gt_link_product (link_product_id);
create index supplier.ix_gt_link_produ_product_id_re on supplier.gt_link_product (product_id, revision_id);
create index supplier.ix_gt_material_gt_material_g on supplier.gt_material (gt_material_group_id);
create index supplier.ix_gt_mat_man_ma_gt_manufac_ty on supplier.gt_mat_man_mappiing (gt_manufac_type_id);
create index supplier.ix_gt_packaging__data_quality_ on supplier.gt_packaging_answers (data_quality_type_id);
create index supplier.ix_gt_packaging__pack_style_ty on supplier.gt_packaging_answers (pack_style_type);
create index supplier.ix_gt_packaging__gt_access_pac on supplier.gt_packaging_answers (gt_access_pack_type_id);
create index supplier.ix_gt_packaging__gt_gift_cont_ on supplier.gt_packaging_answers (gt_gift_cont_type_id);
create index supplier.ix_gt_packaging__gt_pack_layer on supplier.gt_packaging_answers (gt_pack_layers_type_id);
create index supplier.ix_gt_packaging__gt_trans_pack on supplier.gt_packaging_answers (gt_trans_pack_type_id);
create index supplier.ix_gt_pack_item_product_id_re on supplier.gt_pack_item (product_id, revision_id);
create index supplier.ix_gt_pack_item_gt_pack_mater on supplier.gt_pack_item (gt_pack_material_type_id);
create index supplier.ix_gt_pack_item_gt_pack_shape on supplier.gt_pack_item (gt_pack_shape_type_id);
create index supplier.ix_gt_pack_item_product_id_re on supplier.gt_pack_item (product_id, revision_id);
create index supplier.ix_gt_pda_anc_ma_product_id_re on supplier.gt_pda_anc_mat (product_id, revision_id);
create index supplier.ix_gt_pda_batter_gt_battery_co on supplier.gt_pda_battery (gt_battery_code_id);
create index supplier.ix_gt_pda_batter_gt_battery_us on supplier.gt_pda_battery (gt_battery_use_id);
create index supplier.ix_gt_pda_batter_product_id_re on supplier.gt_pda_battery (product_id, revision_id);
create index supplier.ix_gt_pda_endang_gt_endangered on supplier.gt_pda_endangered_sp (gt_endangered_species_id);
create index supplier.ix_gt_pda_hc_ite_gt_pda_haz_ch on supplier.gt_pda_hc_item (gt_pda_haz_chem_id);
create index supplier.ix_gt_pda_hc_ite_gt_pda_materi on supplier.gt_pda_hc_item (gt_pda_material_item_id, product_id, revision_id);
create index supplier.ix_gt_pda_hc_mat_gt_pda_haz_ch on supplier.gt_pda_hc_mat_map (gt_pda_haz_chem_id);
create index supplier.ix_gt_pda_main_p_product_id_re on supplier.gt_pda_main_power (product_id, revision_id);
create index supplier.ix_gt_pda_materi_gt_manufac_ty on supplier.gt_pda_material_item (gt_manufac_type_id);
create index supplier.ix_gt_pda_materi_gt_material_i on supplier.gt_pda_material_item (gt_material_id);
create index supplier.ix_gt_pda_materi_gt_pda_accred on supplier.gt_pda_material_item (gt_pda_accred_type_id);
create index supplier.ix_gt_pda_materi_gt_pda_proven on supplier.gt_pda_material_item (gt_pda_provenance_type_id);
create index supplier.ix_gt_pda_materi_product_id_re on supplier.gt_pda_material_item (product_id, revision_id);
create index supplier.ix_gt_pda_materi_gt_water_stre on supplier.gt_pda_material_item (gt_water_stress_region_id);
create index supplier.ix_gt_pda_mat_pr_gt_pda_proven on supplier.gt_pda_mat_prov_mapping (gt_pda_provenance_type_id);
create index supplier.ix_gt_pda_palm_i_gt_palm_ingre on supplier.gt_pda_palm_ind (gt_palm_ingred_id);
create index supplier.ix_gt_pda_prov_a_gt_pda_accred on supplier.gt_pda_prov_acc_mapping (gt_pda_accred_type_id);
create index supplier.ix_gt_pdesign_an_data_quality_ on supplier.gt_pdesign_answers (data_quality_type_id);
create index supplier.ix_gt_pdesign_an_gt_pda_durabi on supplier.gt_pdesign_answers (gt_pda_durability_type_id);
create index supplier.ix_gt_product_an_data_quality_ on supplier.gt_product_answers (data_quality_type_id);
create index supplier.ix_gt_product_an_ct_doc_group_ on supplier.gt_product_answers (ct_doc_group_id);
create index supplier.ix_gt_product_an_consumer_advi on supplier.gt_product_answers (consumer_advice_3_dg);
create index supplier.ix_gt_product_an_consumer_advi on supplier.gt_product_answers (consumer_advice_4_dg);
create index supplier.ix_gt_product_an_sustain_asses on supplier.gt_product_answers (sustain_assess_1_dg);
create index supplier.ix_gt_product_an_sustain_asses on supplier.gt_product_answers (sustain_assess_2_dg);
create index supplier.ix_gt_product_an_sustain_asses on supplier.gt_product_answers (sustain_assess_3_dg);
create index supplier.ix_gt_product_an_sustain_asses on supplier.gt_product_answers (sustain_assess_4_dg);
create index supplier.ix_gt_product_an_gt_product_ra on supplier.gt_product_answers (gt_product_range_id);
create index supplier.ix_gt_product_ty_gt_access_vis on supplier.gt_product_type (gt_access_visc_type_id);
create index supplier.ix_gt_product_ty_gt_product_cl on supplier.gt_product_type (gt_product_class_id);
create index supplier.ix_gt_product_ty_gt_product_ty on supplier.gt_product_type (gt_product_type_group_id);
create index supplier.ix_gt_product_ty_gt_water_use_ on supplier.gt_product_type (gt_water_use_type_id);
create index supplier.ix_gt_product_us_company_sid on supplier.gt_product_user (company_sid);
create index supplier.ix_gt_product_us_user_sid on supplier.gt_product_user (app_sid, user_sid);
create index supplier.ix_gt_sa_ingred__gt_fd_ingred_ on supplier.gt_sa_ingred_prod_type (gt_fd_ingred_type_id);
create index supplier.ix_gt_sa_questio_gt_sa_issue_i on supplier.gt_sa_question (gt_sa_issue_id);
create index supplier.ix_gt_sa_q_prod__gt_product_ty on supplier.gt_sa_q_prod_type (gt_product_type_id);
create index supplier.ix_gt_score_log_product_id on supplier.gt_score_log (product_id);
create index supplier.ix_gt_score_log_gt_score_type on supplier.gt_score_log (gt_score_type_id);
create index supplier.ix_gt_shape_mate_gt_pack_mater on supplier.gt_shape_material_mapping (gt_pack_material_type_id);
create index supplier.ix_gt_supplier_a_data_quality_ on supplier.gt_supplier_answers (data_quality_type_id);
create index supplier.ix_gt_supplier_a_sust_doc_grou on supplier.gt_supplier_answers (sust_doc_group_id);
create index supplier.ix_gt_supplier_a_gt_sus_relati on supplier.gt_supplier_answers (gt_sus_relation_type_id);
create index supplier.ix_gt_tag_produc_tag_id on supplier.gt_tag_product_type (tag_id);
create index supplier.ix_gt_target_sco_gt_product_ra on supplier.gt_target_scores (gt_product_range_id);
create index supplier.ix_gt_target_sco_gt_product_ty on supplier.gt_target_scores (gt_product_type_id);
create index supplier.ix_gt_target_sco_app_sid on supplier.gt_target_scores_log (app_sid);
create index supplier.ix_gt_target_sco_gt_product_ra on supplier.gt_target_scores_log (gt_product_range_id);
create index supplier.ix_gt_target_sco_gt_product_ty on supplier.gt_target_scores_log (gt_product_type_id);
create index supplier.ix_gt_transport__data_quality_ on supplier.gt_transport_answers (data_quality_type_id);
create index supplier.ix_gt_trans_item_gt_trans_mate on supplier.gt_trans_item (gt_trans_material_type_id);
create index supplier.ix_gt_trans_item_product_id_re on supplier.gt_trans_item (product_id, revision_id);
create index supplier.ix_gt_trans_regi_gt_transport_ on supplier.gt_trans_region_scoring (gt_transport_type_id);
create index supplier.ix_gt_user_repor_csr_user_sid on supplier.gt_user_report_product_ranges (csr_user_sid);
create index supplier.ix_gt_user_repor_csr_user_sid on supplier.gt_user_report_product_types (csr_user_sid);
create index supplier.ix_tag_group_fil_gt_product_gr on supplier.tag_group_filter (gt_product_group_id);
create index supplier.ix_gt_anc_mat_pr_gt_ancillary_ on supplier.gt_anc_mat_prod_class_map (gt_ancillary_material_id);
create index supplier.ix_gt_anc_mat_pr_gt_product_cl on supplier.gt_anc_mat_prod_class_map (gt_product_class_id);
