--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      TEST
-- Project :      newSchema.dm1
-- Author :       TEST
--
-- Date Created : Saturday, September 05, 2009 18:46:22
-- Target DBMS : Oracle 10g
--

-- 
-- TABLE: SUPPLIER.NN_COMPANY_RISK 
--

CREATE TABLE SUPPLIER.NN_COMPANY_RISK(
    COMPANY_SID             NUMBER(10, 0)    NOT NULL,
    COMPANY_RISK_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK184 PRIMARY KEY (COMPANY_SID)
    USING INDEX
TABLESPACE INDX
)
;



-- 
-- TABLE: SUPPLIER.NN_COMPANY_RISK_TYPE 
--

CREATE TABLE SUPPLIER.NN_COMPANY_RISK_TYPE(
    COMPANY_RISK_TYPE_ID    NUMBER(10, 0)     NOT NULL,
    DESCRIPTION             VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK185 PRIMARY KEY (COMPANY_RISK_TYPE_ID)
    USING INDEX
TABLESPACE INDX
)
;



-- 
-- TABLE: SUPPLIER.NN_COUNTRY 
--

CREATE TABLE SUPPLIER.NN_COUNTRY(
    COUNTRY_CODE    VARCHAR2(8)      NOT NULL,
    COUNTRY         VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK54_1 PRIMARY KEY (COUNTRY_CODE)
    USING INDEX
TABLESPACE INDX
)
;



-- 
-- TABLE: SUPPLIER.NN_MANUFACTURING_SITE 
--

CREATE TABLE SUPPLIER.NN_MANUFACTURING_SITE(
    COMPANY_PART_ID        NUMBER(10, 0)     NOT NULL,
    MANUFACTURER_NAME      VARCHAR2(1024)    NOT NULL,
    SITE_ADDRESS           CLOB              NOT NULL,
    SITE_CONTACT_NAME      VARCHAR2(1024),
    SITE_CONTACT_NUMBER    VARCHAR2(256),
    EMPLOYEES_AT_SITE      NUMBER(10, 0),
    PROCESSES_AT_SITE      CLOB,
    COUNTRY_CODE           VARCHAR2(8)       NOT NULL,
    CONSTRAINT PK177 PRIMARY KEY (COMPANY_PART_ID)
    USING INDEX
TABLESPACE INDX
)
;



-- 
-- TABLE: SUPPLIER.NN_SUPPLIER_ANSWERS 
--

CREATE TABLE SUPPLIER.NN_SUPPLIER_ANSWERS(
    COMPANY_SID           NUMBER(10, 0)    NOT NULL,
    MANUFACTURING_CATS    CLOB,
    NOTES                 CLOB,
    DOCUMENT_GROUP_ID     NUMBER(10, 0),
    OTHER_PRODUCT_INFO    CLOB,
    CONSTRAINT PK142_1 PRIMARY KEY (COMPANY_SID)
    USING INDEX
TABLESPACE INDX
)
;



-- 
-- TABLE: SUPPLIER.NN_COMPANY_RISK 
--

ALTER TABLE SUPPLIER.NN_COMPANY_RISK ADD CONSTRAINT REFNN_COMPANY_RISK_TYPE287 
    FOREIGN KEY (COMPANY_RISK_TYPE_ID)
    REFERENCES SUPPLIER.NN_COMPANY_RISK_TYPE(COMPANY_RISK_TYPE_ID)
;


-- 
-- TABLE: SUPPLIER.NN_MANUFACTURING_SITE 
--

ALTER TABLE SUPPLIER.NN_MANUFACTURING_SITE ADD CONSTRAINT RefNN_COUNTRY86 
    FOREIGN KEY (COUNTRY_CODE)
    REFERENCES SUPPLIER.NN_COUNTRY(COUNTRY_CODE)
;

