CREATE TABLE CHAIN.ALERT_PARTIAL_TEMPLATE
(
	APP_SID						NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	ALERT_TYPE_ID				NUMBER(10,0) NOT NULL,
	PARTIAL_TEMPLATE_TYPE_ID	NUMBER(10,0) NOT NULL,
	LANG						VARCHAR2(10 BYTE) NOT NULL,
	PARTIAL_HTML				CLOB NOT NULL,
	CONSTRAINT PK_ALERT_PARTIAL_TEMPLATE PRIMARY KEY (APP_SID, ALERT_TYPE_ID, PARTIAL_TEMPLATE_TYPE_ID, LANG)
);

CREATE TABLE CHAIN.ALERT_PARTIAL_TEMPLATE_PARAM
(
	APP_SID						NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	ALERT_TYPE_ID				NUMBER(10,0) NOT NULL,
	PARTIAL_TEMPLATE_TYPE_ID	NUMBER(10,0) NOT NULL,
	FIELD_NAME					VARCHAR2(50),
	CONSTRAINT PK_ALERT_PARTIAL_TPL_PARAM PRIMARY KEY (APP_SID, ALERT_TYPE_ID, PARTIAL_TEMPLATE_TYPE_ID, FIELD_NAME)
);
