-- Please update version.sql too -- this keeps clean builds in sync
define version=27
@update_header

	-- Phase 3 - new pack types
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (14,'Cartons',14);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (15,'Sleeve / Backing card',15);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (16,'Overwrap',16);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (17,'Label / swing ticket',17);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (18,'Blister Packs',18);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (19,'Godet',19);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (20,'Compact',20);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (21,'Mascara',21);
	INSERT INTO GT_ACCESS_PACK_TYPE (GT_ACCESS_PACK_TYPE_ID, DESCRIPTION, POS) VALUES (22,'Stick Mechanism',22);
	
	-- Phase 3 - new pack type / visc type mappings
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (1, 4, 1);
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (2, 4, 2);	
	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (14, 4, 1);
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (15, 4, 1);	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (16, 4, 1);
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (17, 4, 1);	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (18, 4, 1);
	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (19, 3, 2);	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (19, 4, 2);	
	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (20, 2, 2);		
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (20, 3, 3);		
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (20, 4, 1);		
	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (21, 2, 2);		
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (21, 3, 3);		
	
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (22, 3, 4);		
	INSERT INTO GT_ACCESS_PACK_MAPPING (GT_ACCESS_PACK_TYPE_ID, GT_ACCESS_VISC_TYPE_ID, GT_ACCESS_SCORE) VALUES (22, 4, 5);		
	
@update_tail