-- Please update version.sql too -- this keeps clean builds in sync
define version=56
@update_header

-- not uses - based on battery type now
ALTER TABLE SUPPLIER.GT_BATTERY DROP COLUMN CHEM_SCORE;
ALTER TABLE SUPPLIER.GT_BATTERY DROP COLUMN WASTE_SCORE;


-- 
ALTER TABLE SUPPLIER.GT_BATTERY
 DROP CONSTRAINT REFGT_BATTERY_TYPE878;

ALTER TABLE SUPPLIER.GT_BATTERY DROP COLUMN GT_BATTERY_TYPE_ID;
 
--multiple battery types per battery are possible
-- 
-- TABLE: GT_BATTTERY_BATTERY_TYPE 
--

CREATE TABLE GT_BATTERY_BATTERY_TYPE(
    GT_BATTERY_CODE_ID    NUMBER(10, 0)    NOT NULL,
    GT_BATTERY_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK337 PRIMARY KEY (GT_BATTERY_CODE_ID, GT_BATTERY_TYPE_ID)
)
;
-- 
-- TABLE: GT_BATTTERY_BATTERY_TYPE 
--

ALTER TABLE GT_BATTERY_BATTERY_TYPE ADD CONSTRAINT RefGT_BATTERY_TYPE888 
    FOREIGN KEY (GT_BATTERY_TYPE_ID)
    REFERENCES GT_BATTERY_TYPE(GT_BATTERY_TYPE_ID)
;

ALTER TABLE GT_BTTTERY_BATTERY_TYPE ADD CONSTRAINT RefGT_BATTERY889 
    FOREIGN KEY (GT_BATTERY_CODE_ID)
    REFERENCES GT_BATTERY(GT_BATTERY_CODE_ID)
	
-- need to record the battery type (rechargabel, primary etc.) against the batter entry now
ALTER TABLE SUPPLIER.GT_PDA_BATTERY
ADD (GT_BATTERY_TYPE_ID NUMBER(10) DEFAULT 1 NOT NULL);

-- voltage can be so quite a few dec place
ALTER TABLE SUPPLIER.GT_BATTERY
MODIFY(VOLTAGE NUMBER(10,6));

-- insert battery chem and battery base data
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (1 ,'Ni-Cd' ,3 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (2 ,'Alkaline' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (3 ,'Li-Ion' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (4 ,'Li-Pol' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (5 ,'Lithium' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (6 ,'Ni-Mh' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (7 ,'Silver Oxide' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (8 ,'Zinc Carbon' ,1 );
INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (9 ,'Zn-air' ,1 );

INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (1 ,'LR03' ,2 ,11.04125 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (2 ,'LR14' ,2 ,68.075 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (3 ,'LR20' ,2 ,140.1597 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (4 ,'LR43' ,2 ,1.45 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (5 ,'LR44' ,2 ,3.355 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (6 ,'LR54' ,2 ,1.1 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (7 ,'LR55' ,2 ,0.9 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (8 ,'LR6' ,2 ,23.4325 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (9 ,'LR61' ,2 ,6.25 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (10 ,'LR9' ,2 ,4.5 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (11 ,'LR1' ,2 ,9.17 , 1.9,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (12 ,'3LR12' ,2 ,160 , 4.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (13 ,'4LR44' ,2 ,14 , 6,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (14 ,'6LR61' ,2 ,45.418 , 9,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (15 ,'MN21' ,2 ,7.4 , 12,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (16 ,'4LR61' ,2 ,30 , 6,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (17 ,'LR41' ,2 ,0.7 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (18 ,'LR48' ,2 ,0.92 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (19 ,'18500' ,3 ,35 , 3.6,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (20 ,'BP508' ,3 ,76 , 7.4,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (21 ,'ICR18650' ,3 ,44 , 3.7,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (22 ,'LP401230' ,4 ,2.5 , 3.7,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (23 ,'FR6' ,5 ,13.85 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (24 ,'CP3553' ,5 ,36.6 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (25 ,'CR1216' ,5 ,0.666667 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (26 ,'CR1220' ,5 ,0.926667 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (27 ,'CR123A' ,5 ,16.625 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (28 ,'CR1616' ,5 ,1.165 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (29 ,'CR1620' ,5 ,1.268 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (30 ,'CR17335' ,5 ,13.8365 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (31 ,'CR2' ,5 ,11.048 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (32 ,'CR2016' ,5 ,1.758 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (33 ,'CR2025' ,5 ,2.38 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (34 ,'CR2032' ,5 ,2.945 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (35 ,'CR2320' ,5 ,3 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (36 ,'CR2430' ,5 ,4.2225 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (37 ,'CR2450' ,5 ,6.375 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (38 ,'CRV3' ,5 ,36.95 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (39 ,'2CR5' ,5 ,38.86667 , 6,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (40 ,'CRP2' ,5 ,37.5 , 6,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (41 ,'CR1225' ,5 ,0.9 , 3,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (42 ,'INR18500' ,5 ,20 , 3.7,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (43 ,'L92' ,5 ,7.4 , 1.5,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (44 ,'PX 28L' ,5 ,9.4 , 6,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (45 ,'R6' ,1 ,22 , 1.5,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (46 ,'Sub C' ,1 ,47 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (47 ,'HR03' ,6 ,13 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (48 ,'HR14' ,6 ,67.98667 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (49 ,'HR20' ,6 ,76 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (50 ,'HR6' ,6 ,29.5 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (51 ,'HR6F22' ,6 ,43.36667 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (52 ,'1/2HR6' ,6 ,11 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (53 ,'1/3AA' ,6 ,8 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (54 ,'1/3AAA' ,6 ,21 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (55 ,'2/3A' ,6 ,20 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (56 ,'2/3AA' ,6 ,13 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (57 ,'4/5A' ,6 ,35 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (58 ,'4/5AA' ,6 ,22 , 1.2,1);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (59 ,'SR41' ,7 ,0.6725 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (60 ,'SR42' ,7 ,1.245 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (61 ,'SR43' ,7 ,1.726667 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (62 ,'SR44' ,7 ,2.3325 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (63 ,'SR45' ,7 ,1.055 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (64 ,'SR48' ,7 ,1.066667 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (65 ,'SR54' ,7 ,1.27 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (66 ,'SR55' ,7 ,0.9 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (67 ,'SR57' ,7 ,0.79 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (68 ,'SR58' ,7 ,0.416 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (69 ,'SR59' ,7 ,0.5225 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (70 ,'SR60' ,7 ,0.34 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (71 ,'SR62' ,7 ,0.18 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (72 ,'SR63' ,7 ,0.235 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (73 ,'SR64' ,7 ,0.285 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (74 ,'SR65' ,7 ,0.25 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (75 ,'SR66' ,7 ,0.397 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (76 ,'SR67' ,7 ,0.37 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (77 ,'SR68' ,7 ,0.516667 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (78 ,'SR69' ,7 ,0.636667 , 1.55,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (79 ,'6F22 ' ,8 ,36 , 9,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (80 ,'PR41' ,9 ,0.5025 , 1.4,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (81 ,'PR44' ,9 ,1.833333 , 1.4,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (82 ,'PR48' ,9 ,0.8 , 1.4,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (83 ,'PR63' ,9 ,0.19 , 1.4,0);
INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE) VALUES	 (84 ,'PR70' ,9 ,0.3 , 1.4,0);


-- set up the mappings between battery and battery type - based on rechargable / not rechargeable for convenience atm but
INSERT INTO SUPPLIER.GT_BATTERY_BATTERY_TYPE (GT_BATTERY_CODE_ID, GT_BATTERY_TYPE_ID) 
    SELECT GT_BATTERY_CODE_ID, GT_BATTERY_TYPE_ID FROM gt_battery_type bt, gt_battery b WHERE b.RECHARCHABLE = bt.RECHARGABLE;

	
ALTER TABLE SUPPLIER.GT_PDA_BATTERY
MODIFY(GT_BATTERY_TYPE_ID  DEFAULT NULL);


@update_tail