-- Please update version.sql too -- this keeps clean builds in sync
define version=72
@update_header

INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(194,10,'Lifestyle - Gift Wrap',0,0,2,4,'g',-1,0);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(195,10,'Lifestyle - Greetings Cards',0,0,2,4,'g',-1,0);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(196,10,'Lifestyle - Christmas Decorations',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(197,10,'Lifestyle - Novelty items (unpowered)',0,0,2,4,'g',-1,0);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(198,10,'Sponges',3,0,2,4,'g',-1,0);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(199,10,'Photo - Audio/ Visual Equipment',0,0,2,4,'g',30,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(200,10,'Baby - Baby Monitors',0,0,2,4,'g',30,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(201,10,'Photo - Battery Chargers',0,0,2,4,'g',5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(202,10,'Beauty Accessories - (electrical)',0,0,2,4,'g',1,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(203,10,'Lifestyle - Blankets, heated',0,0,2,4,'g',15,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(204,10,'Healthcare - Blood glucose / pressure monitors',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(205,10,'Baby - Bottle Warmers',0,0,2,4,'g',2,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(206,10,'Baby - Breast pump (electrical)',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(207,10,'Lifestyle - Clock / Alarm (electrical)',0,0,2,4,'g',30,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(208,10,'Electrical Beauty - Depilatory',0,0,2,4,'g',5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(209,10,'Photo - Digital Photo Frames',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(210,10,'Lifestyle - Fans',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(211,10,'Electrical Beauty - Hairstylers (Straightners / Curlers)',0,0,2,4,'g',5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(212,10,'Electrical Beauty - Hairdryers',0,0,2,4,'g',10,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(213,10,'Lifestyle - Kitchen electricals',0,0,2,4,'g',30,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(214,10,'Healthcare - Lamps (SAD etc)',0,0,2,4,'g',30,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(215,10,'Healthcare - Massage',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(216,10,'Baby - Night Lights / Torches',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(217,10,'Lifestyle - Novelty items (electric)',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(218,10,'Photo - Printers',0,0,2,4,'g',1,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(219,10,'Photo - Radio / CD player',0,0,2,4,'g',30,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(220,10,'Electrical Beauty - Shavers',0,0,2,4,'g',5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(221,10,'Baby - Sterilsers',0,0,2,4,'g',10,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(222,10,'Electrical Beauty - Toothbrush',0,0,2,4,'g',5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(223,10,'Lifestyle - Toys (electric)',0,0,2,4,'g',0.5,1);
INSERT INTO gt_product_type (gt_product_type_id, gt_product_type_group_id, description, water_usage_factor, use_energy_score, gt_product_class_id, gt_access_visc_type_id, unit, hrs_used_per_month, mains_powered) VALUES	(224,10,'Healthcare - Vaporisers',0,0,2,4,'g',0.5,1);


@update_tail