-- Please update version.sql too -- this keeps clean builds in sync
define version=29
@update_header

	-- new water user type
	INSERT INTO gt_water_use_type (gt_water_use_type_id, description, water_capacity_ltr) VALUES (5, 'Sink', 5);

--Add missing products
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) 
    VALUES (136, 1, 'Bath Salts (by weight)', 2, 20, 2,  4, 1, 4,  'g');

INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) 
    VALUES (137, 1, 'Blemish Stick (by weight)', 4, 0.1,  4,0, 1, 4,  'g');
	
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) 
    VALUES (138, 1, 'Skin lotion', 4, 2,  4 ,0, 1, 2,  'ml');
    
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) 
    VALUES (139, 1, 'Skin gel', 4, 2,  3 ,0, 1, 1,  'ml');
	

INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(140,1,'Eye Liner Pencil',4,0.1,4,0,1,4, 'g');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(141,1,'Lip Liner Pencil',4,0.1,4,0,1,4, 'g');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(142,1,'Eyeshadow mousse',4,0.1,4,0,1,3, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(143,1,'Felt tip products (lip/eye)',4,0.1,4,0,1,1, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(144,1,'Nail top coat',4,0.1,2,0,1,1, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(145,1,'Foundation W/Si Mattifying Fdn',4,0.3,3,0,1,2, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(146,1,'Foundation W/Si Essentially Natural Fdn',4,0.3,3,0,1,2, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(147,1,'Foundation W/Si Instant Radiance Fdn',4,0.3,3,0,1,2, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(148,1,'Instant Radiance/Under Eye Concealer',4,0.1,4,0,1,2, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(149,1,'Hotpour concealers',4,0.1,4,0,1,4, 'g');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(150,1,'Bronzing Silk Legs/Stocking Cream',4,5,4,0,1,1, 'ml');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(151,1,'Blush stick',4,0.1,4,0,1,4, 'g');
INSERT INTO GT_PRODUCT_TYPE (GT_PRODUCT_TYPE_ID, GT_PRODUCT_TYPE_GROUP_ID, DESCRIPTION, GT_WATER_USE_TYPE_ID, WATER_USAGE_FACTOR, MNFCT_ENERGY_SCORE, USE_ENERGY_SCORE, GT_PRODUCT_CLASS_ID,GT_ACCESS_VISC_TYPE_ID, UNIT) VALUES	(152,1,'Cream Blush',4,0.1,4,0,1,4, 'g');

	
	
-- delete prod no longer in spreadsheet
DELETE FROM GT_TAG_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID = 84;
DELETE FROM GT_USER_REPORT_PRODUCT_TYPES WHERE GT_PRODUCT_TYPE_ID = 84;
DELETE FROM GT_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID = 84;

-- delete prod no longer in spreadsheet
DELETE FROM GT_TAG_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID = 66;
DELETE FROM GT_USER_REPORT_PRODUCT_TYPES WHERE GT_PRODUCT_TYPE_ID =66;
DELETE FROM GT_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID =66;


-- delete prod no longer in spreadsheet
DELETE FROM GT_TAG_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID = 114;
DELETE FROM GT_USER_REPORT_PRODUCT_TYPES WHERE GT_PRODUCT_TYPE_ID = 114;
DELETE FROM GT_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID =114;


DELETE FROM GT_TAG_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID = 63;
DELETE FROM GT_USER_REPORT_PRODUCT_TYPES WHERE GT_PRODUCT_TYPE_ID =63;
DELETE FROM GT_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID =63;

DELETE FROM GT_TAG_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID = 131;
DELETE FROM GT_USER_REPORT_PRODUCT_TYPES WHERE GT_PRODUCT_TYPE_ID =131;
DELETE FROM GT_PRODUCT_TYPE WHERE GT_PRODUCT_TYPE_ID =131


UPDATE gt_product_type SET gt_product_type_group_id = 6 WHERE gt_product_type_id = 133;


		
@update_tail