define version=100
@update_header



ALTER TABLE gt_food_answers DROP COLUMN gm_ingredients;

ALTER TABLE gt_food_answers ADD gt_water_stress_region_id NUMBER(10);
ALTER TABLE gt_food_answers ADD data_quality_type_id NUMBER(10);

ALTER TABLE gt_food_answers ADD CONSTRAINT RefGT_DATA_QUALITY_TYPE_FOOD
	FOREIGN KEY (DATA_QUALITY_TYPE_ID)
	REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;

ALTER TABLE GT_FOOD_ANSWERS ADD CONSTRAINT RefGT_WATER_STRESS_REGION1028 
    FOREIGN KEY (GT_WATER_STRESS_REGION_ID)
    REFERENCES GT_WATER_STRESS_REGION(GT_WATER_STRESS_REGION_ID)
;

ALTER TABLE gt_fd_ingredient ADD contains_gm NUMBER(1) NOT NULL;

ALTER TABLE gt_fd_ingred_type ADD env_impact_score NUMBER(4, 2) NOT NULL;
ALTER TABLE gt_fd_ingred_type ADD water_impact_score NUMBER(4, 2) NOT NULL;
ALTER TABLE gt_fd_ingred_type ADD pesticide_score NUMBER(4, 2) NOT NULL;
ALTER TABLE gt_fd_ingred_type ADD default_gt_sa_score NUMBER(10, 0) NOT NULL;

ALTER TABLE gt_fd_scheme ADD score NUMBER(10, 2);
ALTER TABLE gt_fd_portion_type ADD score NUMBER(10, 2);

CREATE TABLE GT_FOOD_SA_Q(
    PRODUCT_ID           NUMBER(10, 0)    NOT NULL,
    REVISION_ID          NUMBER(10, 0)    NOT NULL,
    GT_SA_QUESTION_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK408 PRIMARY KEY (PRODUCT_ID, REVISION_ID, GT_SA_QUESTION_ID)
)
;



-- 
-- TABLE: GT_SA_INGRED_PROD_TYPE 
--

CREATE TABLE GT_SA_INGRED_PROD_TYPE(
    GT_SA_SCORE             NUMBER(10, 2),
    GT_PRODUCT_TYPE_ID      NUMBER(10, 0)    NOT NULL,
    GT_FD_INGRED_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK406 PRIMARY KEY (GT_PRODUCT_TYPE_ID, GT_FD_INGRED_TYPE_ID)
)
;



-- 
-- TABLE: GT_SA_ISSUE 
--

CREATE TABLE GT_SA_ISSUE(
    GT_SA_ISSUE_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION       VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK405 PRIMARY KEY (GT_SA_ISSUE_ID)
)
;



-- 
-- TABLE: GT_SA_Q_PROD_TYPE 
--

CREATE TABLE GT_SA_Q_PROD_TYPE(
    GT_SA_QUESTION_ID     NUMBER(10, 0)    NOT NULL,
    GT_PRODUCT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    QUESTION_TEXT         VARCHAR2(255),
    GT_SA_SCORE           NUMBER(10, 2),
    CONSTRAINT PK404 PRIMARY KEY (GT_SA_QUESTION_ID, GT_PRODUCT_TYPE_ID)
)
;



-- 
-- TABLE: GT_SA_QUESTION 
--

CREATE TABLE GT_SA_QUESTION(
    GT_SA_QUESTION_ID        NUMBER(10, 0)    NOT NULL,
    HELP_TEXT                VARCHAR2(255),
    DEFAULT_QUESTION_TEXT    VARCHAR2(255)    NOT NULL,
    DEFAULT_GT_SA_SCORE      NUMBER(10, 2)    NOT NULL,
    QUESTION_NAME            VARCHAR2(255)    NOT NULL,
    GT_SA_ISSUE_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK407 PRIMARY KEY (GT_SA_QUESTION_ID)
)
;


ALTER TABLE GT_FOOD_SA_Q ADD CONSTRAINT RefGT_SA_QUESTION1020 
    FOREIGN KEY (GT_SA_QUESTION_ID)
    REFERENCES GT_SA_QUESTION(GT_SA_QUESTION_ID)
;

ALTER TABLE GT_FOOD_SA_Q ADD CONSTRAINT RefGT_FOOD_ANSWERS1021 
    FOREIGN KEY (PRODUCT_ID, REVISION_ID)
    REFERENCES GT_FOOD_ANSWERS(PRODUCT_ID, REVISION_ID)
;


-- 
-- TABLE: GT_SA_INGRED_PROD_TYPE 
--

ALTER TABLE GT_SA_INGRED_PROD_TYPE ADD CONSTRAINT RefGT_FD_INGRED_TYPE1022 
    FOREIGN KEY (GT_FD_INGRED_TYPE_ID)
    REFERENCES GT_FD_INGRED_TYPE(GT_FD_INGRED_TYPE_ID)
;

ALTER TABLE GT_SA_INGRED_PROD_TYPE ADD CONSTRAINT RefGT_PRODUCT_TYPE1023 
    FOREIGN KEY (GT_PRODUCT_TYPE_ID)
    REFERENCES GT_PRODUCT_TYPE(GT_PRODUCT_TYPE_ID)
;


-- 
-- TABLE: GT_SA_Q_PROD_TYPE 
--

ALTER TABLE GT_SA_Q_PROD_TYPE ADD CONSTRAINT RefGT_PRODUCT_TYPE1024 
    FOREIGN KEY (GT_PRODUCT_TYPE_ID)
    REFERENCES GT_PRODUCT_TYPE(GT_PRODUCT_TYPE_ID)
;

ALTER TABLE GT_SA_Q_PROD_TYPE ADD CONSTRAINT RefGT_SA_QUESTION1025 
    FOREIGN KEY (GT_SA_QUESTION_ID)
    REFERENCES GT_SA_QUESTION(GT_SA_QUESTION_ID)
;


-- 
-- TABLE: GT_SA_QUESTION 
--

ALTER TABLE GT_SA_QUESTION ADD CONSTRAINT RefGT_SA_ISSUE1026 
    FOREIGN KEY (GT_SA_ISSUE_ID)
    REFERENCES GT_SA_ISSUE(GT_SA_ISSUE_ID)
;

--make new table for product grouping....
CREATE TABLE gt_product_group (
	gt_product_group_id NUMBER(10) NOT NULL PRIMARY KEY,
	description VARCHAR(255) NOT NULL
);

CREATE TABLE tag_group_filter (
	tag_id NUMBER(10) NOT NULL,
	gt_product_group_id NUMBER(10) NOT NULL,
	CONSTRAINT pk_tag_group_filter PRIMARY KEY (tag_id, gt_product_group_id)
);

ALTER TABLE tag_group_filter ADD CONSTRAINT fk_tgf_tag_id 
FOREIGN KEY (tag_id) REFERENCES tag(tag_id);

ALTER TABLE tag_group_filter ADD CONSTRAINT fk_tgf_gt_product_group_id
FOREIGN KEY (gt_product_group_id) REFERENCES gt_product_group(gt_product_group_id);


@update_tail