-- Please update version.sql too -- this keeps clean builds in sync
define version=8
@update_header

-- add new viscosity type
INSERT INTO GT_ACCESS_VISC_TYPE  (GT_ACCESS_VISC_TYPE_ID, DESCRIPTION, POS)
	VALUES (4, 'Solid', 4);

-- basedata
INSERT INTO GT_PDA_ACCRED_TYPE (GT_PDA_ACCRED_TYPE_ID, DESCRIPTION, SCORE) VALUES (1, 'Accredited source (priority)', 1);
INSERT INTO GT_PDA_ACCRED_TYPE (GT_PDA_ACCRED_TYPE_ID, DESCRIPTION, SCORE) VALUES (2, 'Accredited source (other)', 2);
INSERT INTO GT_PDA_ACCRED_TYPE (GT_PDA_ACCRED_TYPE_ID, DESCRIPTION, SCORE) VALUES (3, 'Known legal source ', 4);
INSERT INTO GT_PDA_ACCRED_TYPE (GT_PDA_ACCRED_TYPE_ID, DESCRIPTION, SCORE) VALUES (4, 'Unknown source', 5);

INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (8, 'Mineral derived / synthetic materials', 0, 0); 
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (7, 'Threatened or endangered species', 1, 10); 
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (6, 'Unknown Sources', 1, 5); 
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (5, 'Wild Harvested', 1, 3); 
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (4, 'Processed materials derived from palm or vegetable oils', 1, 0);
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (3, 'Palm Oil and close derivatives', 1, 4);
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (2, 'Intensively farmed materials', 1, 4); 
INSERT INTO GT_PDA_PROVENANCE_TYPE (GT_PDA_PROVENANCE_TYPE_ID, DESCRIPTION, NATURAL, SCORE) VALUES (1, 'Grown on established mixed agricultural land', 1, 2); 

INSERT INTO GT_PDA_DURABILITY_TYPE (GT_PDA_DURABILITY_TYPE_ID, DESCRIPTION, SCORE) VALUES (1, 'Formulated / Consumables', 1);
INSERT INTO GT_PDA_DURABILITY_TYPE (GT_PDA_DURABILITY_TYPE_ID, DESCRIPTION, SCORE) VALUES (2, 'Durable - long life', 2);
INSERT INTO GT_PDA_DURABILITY_TYPE (GT_PDA_DURABILITY_TYPE_ID, DESCRIPTION, SCORE) VALUES (3, 'Durable - short life', 3);
INSERT INTO GT_PDA_DURABILITY_TYPE (GT_PDA_DURABILITY_TYPE_ID, DESCRIPTION, SCORE) VALUES (4, 'Single use / Disposable', 5);

-- set these to null by default
ALTER TABLE GT_PDA_ACCRED_TYPE MODIFY(SCORE  DEFAULT NULL);
ALTER TABLE GT_PDA_PROVENANCE_TYPE MODIFY(SCORE  DEFAULT NULL);
	
-- viscosity type shouldn't be defaulted
ALTER TABLE GT_PRODUCT_TYPE MODIFY(GT_ACCESS_VISC_TYPE_ID  DEFAULT NULL);
	
@update_tail