-- Please update version.sql too -- this keeps clean builds in sync
define version=53

@update_header

	-- battery chem base data
	ALTER TABLE SUPPLIER.GT_BATTERY_CHEM
	ADD (ENV_SCORE NUMBER(10,2) NOT NULL);
	
	-- add battery chm basedata
	INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (1, 'Ni-Cd', 3);
	INSERT INTO SUPPLIER.GT_BATTERY_CHEM (GT_BATTERY_CHEM_ID, DESCRIPTION, ENV_SCORE) VALUES (2, 'Other', 1);
	
	-- add some fake test batteries
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (1, 'P123', 1, 11.2, 1.5, 0, 1, 2, 1);
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (2, 'P124', 2, 13.4, 9, 0, 2, 3, 1);
		
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (3, 'PR876', 1, 18.2, 1.5, 1, 3, 2, 2);
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (4, 'PR877', 2, 23.4, 9, 1, 4, 3, 2);
		
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (5, 'F996', 1, 1.0, 1.5, 0, 5, 5, 3);
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (6, 'F997', 2, 3.3, 9, 0, 5, 5, 3);
		
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (7, 'FR111', 1, 21.0, 1.5, 0, 3, 3, 4);
	INSERT INTO SUPPLIER.GT_BATTERY (GT_BATTERY_CODE_ID, GT_BATTERY_CODE, GT_BATTERY_CHEM_ID, AVERAGE_WEIGHT_G, VOLTAGE, RECHARCHABLE,  CHEM_SCORE, WASTE_SCORE, GT_BATTERY_TYPE_ID) 
		VALUES (8, 'FR112', 2, 33, 2, 0, 3, 3, 4);

@update_tail