
-- Please update version.sql too -- this keeps clean builds in sync
define version=61
@update_header


ALTER TABLE SUPPLIER.GT_ENDANGERED_SPECIES
ADD (RISK_SCORE NUMBER(4,2));

UPDATE GT_ENDANGERED_SPECIES SET RISK_SCORE = 10;

ALTER TABLE SUPPLIER.GT_ENDANGERED_SPECIES
MODIFY(RISK_SCORE  NOT NULL);

@update_tail