-- Please update version.sql too -- this keeps clean builds in sync
define version=80
@update_header

CREATE TABLE DATA_QUALITY_TYPE(
  DATA_QUALITY_TYPE_ID    NUMBER(10, 0)    NOT NULL,
  DESCRIPTION             VARCHAR2(255)    NOT NULL,
  SCORE                   NUMBER(10, 0)    NOT NULL,
  CONSTRAINT PK363 PRIMARY KEY (DATA_QUALITY_TYPE_ID)
)
;

insert into data_quality_type values (1, 'Measured (High accuracy)', 1);
insert into data_quality_type values (2, 'Partially estimated (Medium accuracy)', 2);
insert into data_quality_type values (3, 'Fully estimated (Low accuracy)', 3);

ALTER TABLE gt_product_answers ADD data_quality_type_id NUMBER(10, 0);
ALTER TABLE gt_pdesign_answers ADD data_quality_type_id NUMBER(10, 0);
ALTER TABLE gt_formulation_answers ADD data_quality_type_id NUMBER(10, 0);
ALTER TABLE gt_packaging_answers ADD data_quality_type_id NUMBER(10, 0);
ALTER TABLE gt_supplier_answers ADD data_quality_type_id NUMBER(10, 0);
ALTER TABLE gt_transport_answers ADD data_quality_type_id NUMBER(10, 0);


ALTER TABLE GT_FORMULATION_ANSWERS ADD CONSTRAINT RefDATA_QUALITY_TYPE952 
    FOREIGN KEY (DATA_QUALITY_TYPE_ID)
    REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;

ALTER TABLE GT_PACKAGING_ANSWERS ADD CONSTRAINT RefDATA_QUALITY_TYPE953 
    FOREIGN KEY (DATA_QUALITY_TYPE_ID)
    REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;

ALTER TABLE GT_PDESIGN_ANSWERS ADD CONSTRAINT RefDATA_QUALITY_TYPE954 
    FOREIGN KEY (DATA_QUALITY_TYPE_ID)
    REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;

ALTER TABLE GT_PRODUCT_ANSWERS ADD CONSTRAINT RefDATA_QUALITY_TYPE946 
    FOREIGN KEY (DATA_QUALITY_TYPE_ID)
    REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;

ALTER TABLE GT_SUPPLIER_ANSWERS ADD CONSTRAINT RefDATA_QUALITY_TYPE955 
    FOREIGN KEY (DATA_QUALITY_TYPE_ID)
    REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;

ALTER TABLE GT_TRANSPORT_ANSWERS ADD CONSTRAINT RefDATA_QUALITY_TYPE956 
    FOREIGN KEY (DATA_QUALITY_TYPE_ID)
    REFERENCES DATA_QUALITY_TYPE(DATA_QUALITY_TYPE_ID)
;


@update_tail