-- Please update version.sql too -- this keeps clean builds in sync
define version=57
@update_header

-- 
-- TABLE: GT_PACK_STYLE_TYPE 
--

CREATE TABLE GT_PACK_STYLE_TYPE(
    GT_PACK_STYLE_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION              VARCHAR2(255)    NOT NULL,
    POS                      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK339 PRIMARY KEY (GT_PACK_STYLE_TYPE_ID)
)
;

INSERT INTO GT_PACK_STYLE_TYPE (GT_PACK_STYLE_TYPE_ID, DESCRIPTION, POS) VALUES (1, 'Doubled walled jar', 1);
INSERT INTO GT_PACK_STYLE_TYPE (GT_PACK_STYLE_TYPE_ID, DESCRIPTION, POS) VALUES (2, 'Contains loose filled tablets in bottles/jars/tubs (eg: vitamins)', 1);
INSERT INTO GT_PACK_STYLE_TYPE (GT_PACK_STYLE_TYPE_ID, DESCRIPTION, POS) VALUES (3, 'Blister trays of tablets in cartons', 1);
INSERT INTO GT_PACK_STYLE_TYPE (GT_PACK_STYLE_TYPE_ID, DESCRIPTION, POS) VALUES (4, 'Gift set in a carton', 1);
INSERT INTO GT_PACK_STYLE_TYPE (GT_PACK_STYLE_TYPE_ID, DESCRIPTION, POS) VALUES (5, 'Other', 1);

ALTER TABLE GT_PACKAGING_ANSWERS ADD CONSTRAINT RefGT_PACK_STYLE_TYPE895 
    FOREIGN KEY (PACK_STYLE_TYPE)
    REFERENCES GT_PACK_STYLE_TYPE(GT_PACK_STYLE_TYPE_ID)
;



@update_tail