define rap4_version=2
@update_header

-- 
-- TABLE: CARD_GROUP_PROGRESSION 
--

CREATE TABLE CARD_GROUP_PROGRESSION(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    CARD_GROUP_ID       NUMBER(10, 0)    NOT NULL,
    FROM_CARD_ID        NUMBER(10, 0)    NOT NULL,
    FROM_CARD_ACTION    VARCHAR2(100)    NOT NULL,
    TO_CARD_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK211 PRIMARY KEY (APP_SID, CARD_GROUP_ID, FROM_CARD_ID, FROM_CARD_ACTION)
)
;

-- 
-- TABLE: CARD_PROGRESSION_ACTION 
--

CREATE TABLE CARD_PROGRESSION_ACTION(
    CARD_ID    NUMBER(10, 0)    NOT NULL,
    ACTION     VARCHAR2(100)    NOT NULL,
    CONSTRAINT check_is_lower CHECK (action = lower(trim(action))),
    CONSTRAINT PK210 PRIMARY KEY (CARD_ID, ACTION)
)
;


-- 
-- TABLE: CARD_GROUP_PROGRESSION 
--

ALTER TABLE CARD_GROUP_PROGRESSION ADD CONSTRAINT RefCARD_GROUP_CARD521 
    FOREIGN KEY (APP_SID, CARD_GROUP_ID, TO_CARD_ID)
    REFERENCES CARD_GROUP_CARD(APP_SID, CARD_GROUP_ID, CARD_ID)
;

ALTER TABLE CARD_GROUP_PROGRESSION ADD CONSTRAINT RefCARD_PROGRESSION_ACTION522 
    FOREIGN KEY (FROM_CARD_ID, FROM_CARD_ACTION)
    REFERENCES CARD_PROGRESSION_ACTION(CARD_ID, ACTION)
;

ALTER TABLE CARD_GROUP_PROGRESSION ADD CONSTRAINT RefCARD_GROUP_CARD523 
    FOREIGN KEY (APP_SID, CARD_GROUP_ID, FROM_CARD_ID)
    REFERENCES CARD_GROUP_CARD(APP_SID, CARD_GROUP_ID, CARD_ID)
;


-- 
-- TABLE: CARD_PROGRESSION_ACTION 
--

ALTER TABLE CARD_PROGRESSION_ACTION ADD CONSTRAINT RefCARD524 
    FOREIGN KEY (CARD_ID)
    REFERENCES CARD(CARD_ID)
;

ALTER TABLE CARD_GROUP_CARD ADD (
	FORCE_TERMINATE            NUMBER(1, 0)     DEFAULT 0 NOT NULL
);

CREATE OR REPLACE TYPE T_CARD_ACTION_ROW AS 
  OBJECT ( 
	ON_ACTION			VARCHAR2(100),
	GO_TO_JS_CLASS		VARCHAR2(1000)
  );
/

CREATE OR REPLACE TYPE T_CARD_ACTION_LIST AS 
  TABLE OF T_CARD_ACTION_ROW;
/

@@..\..\card_pkg
@@..\..\card_body

BEGIN
	user_pkg.LogonAdmin;
	
	INSERT INTO card_group
	(card_group_id, name, description, require_all_cards)
	VALUES
	(12, 'Component Builder', 'Used to build the component tree', 0);

	card_pkg.RegisterCard(
		'A blank card used for testing', 
		'Credit360.Chain.Cards.Testing',
		'/csr/site/chain/cards/testingCards.js', 
		'Chain.Cards.ProgressionTestingCard',
		T_STRING_LIST('trigger1', 'trigger2')
	);
END;
/

@update_tail