define rap4_version=9
@update_header

-- 
-- TABLE: COMPONENT_TYPE_CONTAINMENT 
--

CREATE TABLE COMPONENT_TYPE_CONTAINMENT(
    APP_SID                        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    CONTAINER_COMPONENT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CHILD_COMPONENT_TYPE_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK216 PRIMARY KEY (APP_SID, CONTAINER_COMPONENT_TYPE_ID, CHILD_COMPONENT_TYPE_ID)
)
;

-- 
-- TABLE: COMPONENT_TYPE_CONTAINMENT 
--

ALTER TABLE COMPONENT_TYPE_CONTAINMENT ADD CONSTRAINT RefCOMPONENT_TYPE532 
    FOREIGN KEY (APP_SID, CHILD_COMPONENT_TYPE_ID)
    REFERENCES COMPONENT_TYPE(APP_SID, COMPONENT_TYPE_ID)
;

ALTER TABLE COMPONENT_TYPE_CONTAINMENT ADD CONSTRAINT RefCOMPONENT_TYPE533 
    FOREIGN KEY (APP_SID, CONTAINER_COMPONENT_TYPE_ID)
    REFERENCES COMPONENT_TYPE(APP_SID, COMPONENT_TYPE_ID)
;

@..\..\component_pkg
@..\..\component_body



@update_tail