--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      NPSL Ltd
-- Project :      actions.dm1
-- Author :       Richard Kirby
--
-- Date Created : Tuesday, August 06, 2013 16:28:40
-- Target DBMS : Oracle 10g
--

-- 
-- SEQUENCE: CNT_SEQ 
--

CREATE SEQUENCE ACTIONS.CNT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: FILE_UPLOAD_GROUP_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.FILE_UPLOAD_GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: FILE_UPLOAD_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.FILE_UPLOAD_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: IMPORT_MAPPING_POS_SEQ 
--

CREATE SEQUENCE ACTIONS.IMPORT_MAPPING_POS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: IMPORT_TEMPLATE_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.IMPORT_TEMPLATE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: IND_TEMPLATE_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.IND_TEMPLATE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

-- 
-- SEQUENCE: RECKONER_CONST_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.RECKONER_CONST_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: RECKONER_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.RECKONER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: RECKONER_INPUT_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.RECKONER_INPUT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: RECKONER_OUTPUT_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.RECKONER_OUTPUT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: REPORT_TEMPLATE_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.REPORT_TEMPLATE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: ROLE_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.ROLE_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: SCRIPT_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.SCRIPT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

-- 
-- SEQUENCE: TAG_GROUP_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.TAG_GROUP_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TAG_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.TAG_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TASK_COMMENT_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.TASK_COMMENT_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TASK_PERIOD_STATUS_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.TASK_PERIOD_STATUS_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TASK_STATUS_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.TASK_STATUS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TASK_STATUS_TRANSITION_ID_SEQ 
--

CREATE SEQUENCE ACTIONS.TASK_STATUS_TRANSITION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: ACTIONS.AGGR_TASK_IND_DEPENDENCY 
--

CREATE TABLE ACTIONS.AGGR_TASK_IND_DEPENDENCY(
    APP_SID     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    IND_SID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_AGGR_TASK_IND_DEPENDENCY PRIMARY KEY (APP_SID, TASK_SID, IND_SID)
)
;



-- 
-- TABLE: ACTIONS.AGGR_TASK_PERIOD 
--

CREATE TABLE ACTIONS.AGGR_TASK_PERIOD(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID                 NUMBER(10, 0)    NOT NULL,
    START_DTM                DATE             NOT NULL,
    REGION_SID               NUMBER(10, 0)    NOT NULL,
    PROJECT_SID              NUMBER(10, 0),
    TASK_PERIOD_STATUS_ID    NUMBER(10, 0),
    END_DTM                  DATE             NOT NULL,
    FIELDS_XML               CLOB,
    NEEDS_AGGREGATION        NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AGGR_TASK_PERIOD PRIMARY KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
)
;



-- 
-- TABLE: ACTIONS.AGGR_TASK_PERIOD_OVERRIDE 
--

CREATE TABLE ACTIONS.AGGR_TASK_PERIOD_OVERRIDE(
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID             NUMBER(10, 0)    NOT NULL,
    START_DTM            DATE             NOT NULL,
    REGION_SID           NUMBER(10, 0)    NOT NULL,
    OVERRIDDEN_BY_SID    NUMBER(10, 0)    NOT NULL,
    OVERRIDDEN_DTM       DATE             NOT NULL,
    REASON               CLOB             NOT NULL,
    CONSTRAINT PK_AGGR_TASK_PERIOD_OVERRIDE PRIMARY KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
)
;



-- 
-- TABLE: ACTIONS.AGGR_TASK_TASK_DEPENDENCY 
--

CREATE TABLE ACTIONS.AGGR_TASK_TASK_DEPENDENCY(
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID               NUMBER(10, 0)    NOT NULL,
    DEPENDS_ON_TASK_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_AGGR_TASK_TASK_DEPENDENCY PRIMARY KEY (APP_SID, TASK_SID, DEPENDS_ON_TASK_SID)
)
;



-- 
-- TABLE: ACTIONS.ALLOW_TRANSITION 
--

CREATE TABLE ACTIONS.ALLOW_TRANSITION(
    APP_SID                      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_TRANSITION_ID    NUMBER(10, 0)    NOT NULL,
    USER_OR_GROUP_SID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_ALLOW_TRANSITION PRIMARY KEY (APP_SID, TASK_STATUS_TRANSITION_ID, USER_OR_GROUP_SID)
)
;



-- 
-- TABLE: ACTIONS.CSR_TASK_ROLE_MEMBER 
--

CREATE TABLE ACTIONS.CSR_TASK_ROLE_MEMBER(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID           NUMBER(10, 0)    NOT NULL,
    ROLE_SID           NUMBER(10, 0)    NOT NULL,
    USER_SID           NUMBER(10, 0)    NOT NULL,
    GENERATE_ALERTS    NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CHECK (GENERATE_ALERTS IN(0,1)),
    CONSTRAINT PK_TASK_ROLE_MEMBER_1 PRIMARY KEY (APP_SID, TASK_SID, ROLE_SID, USER_SID)
)
;



-- 
-- TABLE: ACTIONS.CUSTOMER_OPTIONS 
--

CREATE TABLE ACTIONS.CUSTOMER_OPTIONS(
    APP_SID                          NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SHOW_REGIONS                     NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    RESTRICT_BY_REGION               NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    BROWSE_SHOWS_CHILDREN            NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    AGGREGATE_TASK_TREE              NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    SHOW_WEIGHTINGS                  NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    SHOW_ACTION_TYPE                 NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    GREYOUT_UNASSOC_TASKS            NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    ALLOW_PERF_OVERRIDE              NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    ALLOW_PARENT_OVERRIDE            NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    USE_ACTIONS_V2                   NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    SHOW_TASK_PERIOD_PCT             NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    ACTION_GRID_PATH                 VARCHAR2(1024),
    AGGR_ACTION_GRID_PATH            VARCHAR2(1024),
    DEFAULT_VALUE_SCRIPT_ID          NUMBER(10, 0),
    INITIATIVE_END_DTM               DATE,
    REGION_PICKER_CONFIG             VARCHAR2(2048),
    USE_STANDARD_REGION_PICKER       NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    INITIATIVE_NAME_GEN_PROC         VARCHAR2(256),
    INITIATIVE_REMINDER_ALERTS       NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    INITIATIVE_HIDE_ONGOING_RADIO    NUMBER(1, 0)      DEFAULT 0,
    INITIATIVE_NEW_DAYS              NUMBER(10, 0)     DEFAULT 5 NOT NULL,
    GANTT_PERIOD_COLOUR              NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    REGION_LEVEL                     NUMBER(10, 0)     NOT NULL,
    COUNTRY_LEVEL                    NUMBER(10, 0)     NOT NULL,
    PROPERTY_LEVEL                   NUMBER(10, 0)     NOT NULL,
    INITIATIVES_HOST                 VARCHAR2(256),
    MY_INITIATIVES_OPTIONS           VARCHAR2(1024),
    AUTO_COMPLETE_DATE               NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    UPDATE_REF_ON_AMEND              NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CHECK (INITIATIVE_REMINDER_ALERTS IN (0,1)),
    CHECK (INITIATIVE_HIDE_ONGOING_RADIO IN (0,1)),
    CHECK (GANTT_PERIOD_COLOUR IN(0,1)),
    CHECK (USE_STANDARD_REGION_PICKER IN(0,1)),
    CHECK (AUTO_COMPLETE_DATE IN(0,1)),
    CHECK (UPDATE_REF_ON_AMEND IN(0,1)),
    CONSTRAINT PK_CUSTOMER_OPTIONS PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: ACTIONS.FILE_UPLOAD 
--

CREATE TABLE ACTIONS.FILE_UPLOAD(
    APP_SID      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FILE_ID      NUMBER(10, 0)    NOT NULL,
    FILE_NAME    VARCHAR2(256)    NOT NULL,
    MIME_TYPE    VARCHAR2(256)    NOT NULL,
    DATA         BLOB,
    CONSTRAINT PK_FILE_UPLOAD PRIMARY KEY (APP_SID, FILE_ID)
)
;



-- 
-- TABLE: ACTIONS.FILE_UPLOAD_GROUP 
--

CREATE TABLE ACTIONS.FILE_UPLOAD_GROUP(
    APP_SID                 NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FILE_UPLOAD_GROUP_ID    NUMBER(10, 0)     NOT NULL,
    NAME                    VARCHAR2(256)     NOT NULL,
    LABEL                   VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK_FILE_UPLOAD_GROUP PRIMARY KEY (APP_SID, FILE_UPLOAD_GROUP_ID)
)
;



-- 
-- TABLE: ACTIONS.FILE_UPLOAD_GROUP_MEMBER 
--

CREATE TABLE ACTIONS.FILE_UPLOAD_GROUP_MEMBER(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FILE_UPLOAD_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    FILE_ID                 NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_FILE_UPLOAD_GROUP_MEMBER PRIMARY KEY (APP_SID, FILE_UPLOAD_GROUP_ID, FILE_ID)
)
;



-- 
-- TABLE: ACTIONS.IMPORT_MAPPING_MRU 
--

CREATE TABLE ACTIONS.IMPORT_MAPPING_MRU(
    APP_SID         NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CSR_USER_SID    NUMBER(10, 0)     NOT NULL,
    FROM_NAME       VARCHAR2(1024)    NOT NULL,
    TO_NAME         VARCHAR2(1024)    NOT NULL,
    POS             NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK141 PRIMARY KEY (APP_SID, CSR_USER_SID, FROM_NAME, TO_NAME)
)
;



-- 
-- TABLE: ACTIONS.IMPORT_TEMPLATE 
--

CREATE TABLE ACTIONS.IMPORT_TEMPLATE(
    APP_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IMPORT_TEMPLATE_ID    NUMBER(10, 0)     NOT NULL,
    NAME                  VARCHAR2(1024)    NOT NULL,
    HEADING_ROW_IDX       NUMBER(10, 0)     NOT NULL,
    WORKSHEET_NAME        VARCHAR2(1024)    NOT NULL,
    PROJECT_SID           NUMBER(10, 0),
    WORKBOOK              BLOB,
    IS_DEFAULT            NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CHECK (IS_DEFAULT IN(0,1)),
    CONSTRAINT PK148 PRIMARY KEY (APP_SID, IMPORT_TEMPLATE_ID)
)
;



-- 
-- TABLE: ACTIONS.IMPORT_TEMPLATE_MAPPING 
--

CREATE TABLE ACTIONS.IMPORT_TEMPLATE_MAPPING(
    APP_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IMPORT_TEMPLATE_ID    NUMBER(10, 0)     NOT NULL,
    TO_NAME               VARCHAR2(1024)    NOT NULL,
    FROM_IDX              NUMBER(10, 0)     NOT NULL,
    FROM_NAME             VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK149 PRIMARY KEY (APP_SID, IMPORT_TEMPLATE_ID, TO_NAME)
)
;



-- 
-- TABLE: ACTIONS.IND_TEMPLATE 
--

CREATE TABLE ACTIONS.IND_TEMPLATE(
    APP_SID                 NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IND_TEMPLATE_ID         NUMBER(10, 0)     NOT NULL,
    NAME                    VARCHAR2(255)     NOT NULL,
    DESCRIPTION             VARCHAR2(1023)    NOT NULL,
    INPUT_LABEL             VARCHAR2(1024)    NOT NULL,
    TOLERANCE_TYPE          NUMBER(2, 0)      DEFAULT 0 NOT NULL,
    PCT_UPPER_TOLERANCE     NUMBER(10, 4)     DEFAULT 1 NOT NULL,
    PCT_LOWER_TOLERANCE     NUMBER(10, 4)     DEFAULT 1 NOT NULL,
    MEASURE_SID             NUMBER(10, 0)     NOT NULL,
    SCALE                   NUMBER(10, 0)     DEFAULT 0,
    FORMAT_MASK             VARCHAR2(255)     DEFAULT '#,##0',
    TARGET_DIRECTION        NUMBER(10, 0)     DEFAULT 1,
    INFO_XML                SYS.XMLType,
    DIVISIBLE               NUMBER(10, 0)     DEFAULT 1,
    AGGREGATE               VARCHAR2(24)      DEFAULT 'SUM',
    PER_PERIOD_DURATION     NUMBER(10, 0),
    ONE_OFF_NTH_PERIOD      NUMBER(10, 0),
    IS_ONGOING              NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CALCULATION             SYS.XMLType,
    IS_STORED_CALC          NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CALC_PERIOD_DURATION    NUMBER(10, 0),
    IS_NPV                  NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    FACTOR_TYPE_ID          NUMBER(10, 0),
    GAS_MEASURE_SID         NUMBER(10, 0),
    INFO_TEXT               VARCHAR2(4000),
    CHECK (IS_ONGOING IN(0,1)),
    CHECK (IS_STORED_CALC IN(0,1)),
    CHECK (IS_NPV IN(0,1)),
    CONSTRAINT CHK_NPV_STORED_NODIV CHECK (IS_NPV = 0 OR (IS_STORED_CALC = 1 AND DIVISIBLE = 0)),
    CONSTRAINT PK_IND_TEMPLATE PRIMARY KEY (APP_SID, IND_TEMPLATE_ID)
)
;



-- 
-- TABLE: ACTIONS.IND_TEMPLATE_GROUP 
--

CREATE TABLE ACTIONS.IND_TEMPLATE_GROUP(
    APP_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID           NUMBER(10, 0)     NOT NULL,
    POS_GROUP             NUMBER(10, 0)     NOT NULL,
    IS_GROUP_MANDATORY    NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    LABEL                 VARCHAR2(1024),
    INFO_TEXT             VARCHAR2(4000),
    CHECK (IS_GROUP_MANDATORY IN(0,1)),
    CONSTRAINT PK159 PRIMARY KEY (APP_SID, PROJECT_SID, POS_GROUP)
)
;



-- 
-- TABLE: ACTIONS.INITIATIVE_EXTRA_INFO 
--

CREATE TABLE ACTIONS.INITIATIVE_EXTRA_INFO(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID          NUMBER(10, 0)    NOT NULL,
    ONE_OFF_SAVING    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK_INITIATIVE_EXTRA_INFO PRIMARY KEY (APP_SID, TASK_SID)
)
;



-- 
-- TABLE: ACTIONS.INITIATIVE_PROJECT_TEAM 
--

CREATE TABLE ACTIONS.INITIATIVE_PROJECT_TEAM(
    APP_SID     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    NAME        VARCHAR2(512)    NOT NULL,
    EMAIL       VARCHAR2(512)
)
;



-- 
-- TABLE: ACTIONS.INITIATIVE_SPONSOR 
--

CREATE TABLE ACTIONS.INITIATIVE_SPONSOR(
    APP_SID     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    NAME        VARCHAR2(512)    NOT NULL,
    EMAIL       VARCHAR2(512)
)
;



-- 
-- TABLE: ACTIONS.INSTANCE_GAS_IND 
--

CREATE TABLE ACTIONS.INSTANCE_GAS_IND(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID                NUMBER(10, 0)    NOT NULL,
    FROM_IND_TEMPLATE_ID    NUMBER(10, 0)    NOT NULL,
    IND_SID                 NUMBER(10, 0)    NOT NULL,
    GAS_METRIC_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK156 PRIMARY KEY (APP_SID, TASK_SID, FROM_IND_TEMPLATE_ID, IND_SID)
)
;



-- 
-- TABLE: ACTIONS.PERIODIC_ALERT 
--

CREATE TABLE ACTIONS.PERIODIC_ALERT(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    ALERT_TYPE_ID     NUMBER(10, 0)    NOT NULL,
    DATA_SP           VARCHAR2(256)    NOT NULL,
    RECURRENCE_XML    SYS.XMLType      NOT NULL,
    CONSTRAINT PK136 PRIMARY KEY (APP_SID, ALERT_TYPE_ID)
)
;



-- 
-- TABLE: ACTIONS.PERIODIC_ALERT_USER 
--

CREATE TABLE ACTIONS.PERIODIC_ALERT_USER(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    ALERT_TYPE_ID     NUMBER(10, 0)    NOT NULL,
    CSR_USER_SID      NUMBER(10, 0)    NOT NULL,
    LAST_FIRE_DATE    DATE,
    NEXT_FIRE_DATE    DATE,
    CONSTRAINT PK138 PRIMARY KEY (APP_SID, ALERT_TYPE_ID, CSR_USER_SID)
)
;



-- 
-- TABLE: ACTIONS.PERIODIC_REPORT_TEMPLATE 
--

CREATE TABLE ACTIONS.PERIODIC_REPORT_TEMPLATE(
    APP_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REPORT_TEMPLATE_ID    NUMBER(10, 0)     NOT NULL,
    DESCRIPTION           VARCHAR2(1024)    NOT NULL,
    TEMPLATE_XML          SYS.XMLType       NOT NULL,
    CONSTRAINT PK143 PRIMARY KEY (APP_SID, REPORT_TEMPLATE_ID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT 
--

CREATE TABLE ACTIONS.PROJECT(
    APP_SID                   NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID               NUMBER(10, 0)     NOT NULL,
    NAME                      VARCHAR2(1024)    NOT NULL,
    MAX_PERIOD_DURATION       NUMBER(10, 0)     DEFAULT 3,
    start_dtm                 DATE              NOT NULL,
    END_DTM                   DATE              NOT NULL,
    TASK_FIELDS_XML           CLOB              NOT NULL,
    TASK_PERIOD_FIELDS_XML    CLOB              NOT NULL,
    NEXT_ID                   NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    IND_SID                   NUMBER(10, 0)     NOT NULL,
    ICON                      VARCHAR2(256),
    ABBREVIATION              VARCHAR2(16),
    POS_GROUP                 NUMBER(10, 0),
    POS                       NUMBER(10, 0),
    ONGOING_END_DTM           DATE,
    IS_INITIATIVES            NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    CATEGORY_LEVEL            NUMBER(10, 0),
    CHECK (IS_INITIATIVES IN(0,1)),
    CONSTRAINT CHK_ONGOING_DTM CHECK (IS_INITIATIVES = 0 OR ONGOING_END_DTM IS NOT NULL),
    CONSTRAINT PK_PROJECT PRIMARY KEY (APP_SID, PROJECT_SID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_FILE_UPLOAD_GROUP 
--

CREATE TABLE ACTIONS.PROJECT_FILE_UPLOAD_GROUP(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FILE_UPLOAD_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    PROJECT_SID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_PROJECT_FILE_UPLOAD_GROUP PRIMARY KEY (APP_SID, FILE_UPLOAD_GROUP_ID, PROJECT_SID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_IND_TEMPLATE 
--

CREATE TABLE ACTIONS.PROJECT_IND_TEMPLATE(
    APP_SID                NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID            NUMBER(10, 0)     NOT NULL,
    IND_TEMPLATE_ID        NUMBER(10, 0)     NOT NULL,
    POS                    NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    POS_GROUP              NUMBER(10, 0)     NOT NULL,
    IS_MANDATORY           NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    UPDATE_PER_PERIOD      NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    DEFAULT_VALUE          NUMBER(24, 10),
    INPUT_DP               NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    SAVING_TEMPLATE_ID     NUMBER(10, 0),
    ONGOING_TEMPLATE_ID    NUMBER(10, 0),
    MERGED_TEMPLATE_ID     NUMBER(10, 0),
    DISPLAY_CONTEXT        VARCHAR2(255)     DEFAULT 'ALL',
    CHECK (UPDATE_PER_PERIOD IN(0,1)),
    CHECK (DISPLAY_CONTEXT IN('ALL', 'CREATE', 'PORTLET')),
    CONSTRAINT PK_PROJECT_IND_TEMPLATE PRIMARY KEY (APP_SID, PROJECT_SID, IND_TEMPLATE_ID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE 
--

CREATE TABLE ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID             NUMBER(10, 0)    NOT NULL,
    FROM_IND_TEMPLATE_ID    NUMBER(10, 0)    NOT NULL,
    IND_SID                 NUMBER(10, 0),
    CONSTRAINT PK_PROJECT_IND_TEMPLATE_INST PRIMARY KEY (APP_SID, PROJECT_SID, FROM_IND_TEMPLATE_ID)
)
;



ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE ADD CHECK 
	(IND_SID IS NOT NULL) 
	DEFERRABLE INITIALLY DEFERRED;
-- 
-- TABLE: ACTIONS.PROJECT_REGION_ROLE_MEMBER 
--

CREATE TABLE ACTIONS.PROJECT_REGION_ROLE_MEMBER(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID           NUMBER(10, 0)    NOT NULL,
    REGION_SID            NUMBER(10, 0)    NOT NULL,
    ROLE_SID              NUMBER(10, 0)    NOT NULL,
    USER_SID              NUMBER(10, 0)    NOT NULL,
    INHERITED_FROM_SID    NUMBER(10, 0)    NOT NULL,
    GENERATE_ALERTS       NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CHECK (GENERATE_ALERTS IN(0,1)),
    CONSTRAINT PK145 PRIMARY KEY (APP_SID, PROJECT_SID, REGION_SID, ROLE_SID, USER_SID, INHERITED_FROM_SID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_ROLE 
--

CREATE TABLE ACTIONS.PROJECT_ROLE(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID    NUMBER(10, 0)    NOT NULL,
    ROLE_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_PROJECT_ROLE PRIMARY KEY (APP_SID, PROJECT_SID, ROLE_ID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_ROLE_MEMBER 
--

CREATE TABLE ACTIONS.PROJECT_ROLE_MEMBER(
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID          NUMBER(10, 0)    NOT NULL,
    ROLE_ID              NUMBER(10, 0)    NOT NULL,
    USER_OR_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_PROJECT_ROLE_MEMBER PRIMARY KEY (APP_SID, PROJECT_SID, ROLE_ID, USER_OR_GROUP_SID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_TAG_GROUP 
--

CREATE TABLE ACTIONS.PROJECT_TAG_GROUP(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    PROJECT_SID     NUMBER(10, 0)    NOT NULL,
    POS             NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PROJECT_TAG_GROUP PRIMARY KEY (APP_SID, TAG_GROUP_ID, PROJECT_SID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_TASK_PERIOD_STATUS 
--

CREATE TABLE ACTIONS.PROJECT_TASK_PERIOD_STATUS(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID              NUMBER(10, 0)    NOT NULL,
    TASK_PERIOD_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_PROJECT_TASK_PERIOD_STATUS PRIMARY KEY (APP_SID, PROJECT_SID, TASK_PERIOD_STATUS_ID)
)
;



-- 
-- TABLE: ACTIONS.PROJECT_TASK_STATUS 
--

CREATE TABLE ACTIONS.PROJECT_TASK_STATUS(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID       NUMBER(10, 0)    NOT NULL,
    TASK_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_PROJECT_TASK_STATUS PRIMARY KEY (APP_SID, PROJECT_SID, TASK_STATUS_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER 
--

CREATE TABLE ACTIONS.RECKONER(
    RECKONER_ID    NUMBER(10, 0)     NOT NULL,
    LABEL          VARCHAR2(256)     NOT NULL,
    DESCRIPTION    VARCHAR2(4000),
    SCRIPT         CLOB,
    CONSTRAINT PK106 PRIMARY KEY (RECKONER_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER_CONST 
--

CREATE TABLE ACTIONS.RECKONER_CONST(
    RECKONER_CONST_ID    NUMBER(10, 0)     NOT NULL,
    NAME                 VARCHAR2(256)     NOT NULL,
    LABEL                VARCHAR2(256)     NOT NULL,
    VAL                  NUMBER(24, 10)    NOT NULL,
    CONSTRAINT PK108 PRIMARY KEY (RECKONER_CONST_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER_CONST_DEP 
--

CREATE TABLE ACTIONS.RECKONER_CONST_DEP(
    RECKONER_ID          NUMBER(10, 0)    NOT NULL,
    RECKONER_CONST_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK111 PRIMARY KEY (RECKONER_ID, RECKONER_CONST_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER_INPUT 
--

CREATE TABLE ACTIONS.RECKONER_INPUT(
    RECKONER_ID          NUMBER(10, 0)    NOT NULL,
    RECKONER_INPUT_ID    NUMBER(10, 0)    NOT NULL,
    NAME                 VARCHAR2(256)    NOT NULL,
    LABEL                VARCHAR2(256)    NOT NULL,
    POS                  NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK107 PRIMARY KEY (RECKONER_ID, RECKONER_INPUT_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER_OUTPUT 
--

CREATE TABLE ACTIONS.RECKONER_OUTPUT(
    RECKONER_ID           NUMBER(10, 0)    NOT NULL,
    RECKONER_OUTPUT_ID    NUMBER(10, 0)    NOT NULL,
    NAME                  VARCHAR2(256)    NOT NULL,
    LABEL                 VARCHAR2(256)    NOT NULL,
    MAP_TO                VARCHAR2(256),
    CONSTRAINT PK109 PRIMARY KEY (RECKONER_ID, RECKONER_OUTPUT_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER_TAG 
--

CREATE TABLE ACTIONS.RECKONER_TAG(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID     NUMBER(10, 0)    NOT NULL,
    TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    TAG_ID          NUMBER(10, 0)    NOT NULL,
    RECKONER_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RECKONER_TAG PRIMARY KEY (APP_SID, PROJECT_SID, TAG_GROUP_ID, TAG_ID, RECKONER_ID)
)
;



-- 
-- TABLE: ACTIONS.RECKONER_TAG_GROUP 
--

CREATE TABLE ACTIONS.RECKONER_TAG_GROUP(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    PROJECT_SID     NUMBER(10, 0)    NOT NULL,
    TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RECKONER_TAG_GROUP PRIMARY KEY (APP_SID, PROJECT_SID, TAG_GROUP_ID)
)
;



-- 
-- TABLE: ACTIONS.ROLE 
--

CREATE TABLE ACTIONS.ROLE(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    ROLE_ID                   NUMBER(10, 0)    NOT NULL,
    NAME                      VARCHAR2(255)    NOT NULL,
    PERMISSION_SET_ON_TASK    NUMBER(10, 0),
    SHOW_IN_FILTER            NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (APP_SID, ROLE_ID)
)
;



-- 
-- TABLE: ACTIONS.ROOT_IND_TEMPLATE_INSTANCE 
--

CREATE TABLE ACTIONS.ROOT_IND_TEMPLATE_INSTANCE(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FROM_IND_TEMPLATE_ID    NUMBER(10, 0)    NOT NULL,
    IND_SID                 NUMBER(10, 0),
    CONSTRAINT PK_ROOT_IND_TEMPLATE_INSTANCE PRIMARY KEY (APP_SID, FROM_IND_TEMPLATE_ID)
)
;



ALTER TABLE ACTIONS.ROOT_IND_TEMPLATE_INSTANCE ADD CHECK 
	(IND_SID IS NOT NULL) 
	DEFERRABLE INITIALLY DEFERRED;
-- 
-- TABLE: ACTIONS.SCENARIO_FILTER 
--

CREATE TABLE ACTIONS.SCENARIO_FILTER(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SCENARIO_SID    NUMBER(10, 0)    NOT NULL,
    RULE_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK161 PRIMARY KEY (APP_SID, SCENARIO_SID, RULE_ID)
)
;



-- 
-- TABLE: ACTIONS.SCENARIO_FILTER_STATUS 
--

CREATE TABLE ACTIONS.SCENARIO_FILTER_STATUS(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SCENARIO_SID      NUMBER(10, 0)    NOT NULL,
    RULE_ID           NUMBER(10, 0)    NOT NULL,
    TASK_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK164 PRIMARY KEY (APP_SID, SCENARIO_SID, RULE_ID, TASK_STATUS_ID)
)
;



-- 
-- TABLE: ACTIONS.SCRIPT 
--

CREATE TABLE ACTIONS.SCRIPT(
    APP_SID      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SCRIPT_ID    NUMBER(10, 0)    NOT NULL,
    SCRIPT       CLOB,
    CONSTRAINT PK_SCRIPT PRIMARY KEY (APP_SID, SCRIPT_ID)
)
;



-- 
-- TABLE: ACTIONS.TAG 
--

CREATE TABLE ACTIONS.TAG(
    APP_SID        NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_ID         NUMBER(10, 0)     NOT NULL,
    TAG            VARCHAR2(512)     NOT NULL,
    EXPLANATION    VARCHAR2(1024),
    CONSTRAINT PK_TAG PRIMARY KEY (APP_SID, TAG_ID)
)
;



-- 
-- TABLE: ACTIONS.TAG_GROUP 
--

CREATE TABLE ACTIONS.TAG_GROUP(
    APP_SID           NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_GROUP_ID      NUMBER(10, 0)     NOT NULL,
    NAME              VARCHAR2(255)     NOT NULL,
    MULTI_SELECT      NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    MANDATORY         NUMBER(10, 0)     DEFAULT 1 NOT NULL,
    RENDER_AS         CHAR(1)           DEFAULT 'X' NOT NULL,
    SHOW_IN_FILTER    NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    LABEL             VARCHAR2(1024),
    CONSTRAINT PK_TAG_GROUP PRIMARY KEY (APP_SID, TAG_GROUP_ID)
)
;



-- 
-- TABLE: ACTIONS.TAG_GROUP_MEMBER 
--

CREATE TABLE ACTIONS.TAG_GROUP_MEMBER(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    TAG_ID          NUMBER(10, 0)    NOT NULL,
    POS             NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    IS_VISIBLE      NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TAG_GROUP_MEMBER PRIMARY KEY (APP_SID, TAG_GROUP_ID, TAG_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK 
--

CREATE TABLE ACTIONS.TASK(
    APP_SID                 NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID                NUMBER(10, 0)     NOT NULL,
    PROJECT_SID             NUMBER(10, 0)     NOT NULL,
    PARENT_TASK_SID         NUMBER(10, 0),
    TASK_STATUS_ID          NUMBER(10, 0)     NOT NULL,
    NAME                    VARCHAR2(1024)    NOT NULL,
    START_DTM               DATE              NOT NULL,
    END_DTM                 DATE              NOT NULL,
    FIELDS_XML              CLOB,
    IS_CONTAINER            NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    INTERNAL_REF            VARCHAR2(255),
    PERIOD_DURATION         NUMBER(10, 0)     NOT NULL,
    BUDGET                  NUMBER(10, 0),
    SHORT_NAME              VARCHAR2(255),
    LAST_TASK_PERIOD_DTM    DATE,
    OWNER_SID               NUMBER(10, 0)     NOT NULL,
    CREATED_DTM             DATE              DEFAULT SYSDATE NOT NULL,
    INPUT_IND_SID           NUMBER(10, 0),
    TARGET_IND_SID          NUMBER(10, 0),
    OUTPUT_IND_SID          NUMBER(10, 0),
    WEIGHTING               NUMBER(5, 4),
    ACTION_TYPE             VARCHAR2(1)       NOT NULL,
    ENTRY_TYPE              VARCHAR2(1)       NOT NULL,
    VALUE_SCRIPT            CLOB,
    AGGREGATE_SCRIPT        CLOB,
    LAST_TRANSITION_ID      NUMBER(10, 0),
    CONSTRAINT PK_TASK PRIMARY KEY (APP_SID, TASK_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_BUDGET_HISTORY 
--

CREATE TABLE ACTIONS.TASK_BUDGET_HISTORY(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID           NUMBER(10, 0)    NOT NULL,
    SET_DTM            DATE             DEFAULT SYSDATE NOT NULL,
    BUDGET             NUMBER(10, 0),
    SET_BY_USER_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_BUDGET_HISTORY PRIMARY KEY (APP_SID, TASK_SID, SET_DTM)
)
;



-- 
-- TABLE: ACTIONS.TASK_BUDGET_PERIOD 
--

CREATE TABLE ACTIONS.TASK_BUDGET_PERIOD(
    APP_SID      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID     NUMBER(10, 0)    NOT NULL,
    START_DTM    DATE             NOT NULL,
    END_DTM      DATE             NOT NULL,
    BUDGET       NUMBER(12, 2)    NOT NULL,
    NOTES        CLOB,
    IS_ACTUAL    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TASK_BUDGET_PERIOD PRIMARY KEY (APP_SID, TASK_SID, START_DTM, END_DTM)
)
;



-- 
-- TABLE: ACTIONS.TASK_COMMENT 
--

CREATE TABLE ACTIONS.TASK_COMMENT(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_COMMENT_ID    NUMBER(10, 0)    NOT NULL,
    TASK_SID           NUMBER(10, 0),
    USER_SID           NUMBER(10, 0)    NOT NULL,
    POSTED_DTM         DATE             DEFAULT SYSDATE NOT NULL,
    COMMENT_TEXT       CLOB,
    CONSTRAINT PK_TASK_COMMENT PRIMARY KEY (APP_SID, TASK_COMMENT_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_FILE_UPLOAD 
--

CREATE TABLE ACTIONS.TASK_FILE_UPLOAD(
    APP_SID     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    FILE_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_FILE_UPLOAD PRIMARY KEY (APP_SID, TASK_SID, FILE_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_IND_DEPENDENCY 
--

CREATE TABLE ACTIONS.TASK_IND_DEPENDENCY(
    APP_SID     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    IND_SID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_IND_DEPENDENCY PRIMARY KEY (APP_SID, TASK_SID, IND_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_IND_TEMPLATE_INSTANCE 
--

CREATE TABLE ACTIONS.TASK_IND_TEMPLATE_INSTANCE(
    APP_SID                        NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID                       NUMBER(10, 0)     NOT NULL,
    FROM_IND_TEMPLATE_ID           NUMBER(10, 0)     NOT NULL,
    IND_SID                        NUMBER(10, 0)     NOT NULL,
    ONGOING_END_DTM                DATE,
    VAL                            NUMBER(24, 10),
    ENTRY_VAL                      NUMBER(24, 10),
    ENTRY_MEASURE_CONVERSION_ID    NUMBER(10, 0),
    CONSTRAINT PK_TASK_IND_TEMPLATE_INSTANCE PRIMARY KEY (APP_SID, TASK_SID, FROM_IND_TEMPLATE_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_INDICATOR 
--

CREATE TABLE ACTIONS.TASK_INDICATOR(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID          NUMBER(10, 0)    NOT NULL,
    INDICATOR_SID     NUMBER(10, 0)    NOT NULL,
    PRIORITY_LEVEL    NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TASK_INDICATOR PRIMARY KEY (APP_SID, TASK_SID, INDICATOR_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_INSTANCE 
--

CREATE TABLE ACTIONS.TASK_INSTANCE(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID       NUMBER(10, 0)    NOT NULL,
    INSTANCE_ID    NUMBER(10, 0)    NOT NULL,
    CONTEXT        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_INSTANCE PRIMARY KEY (APP_SID, TASK_SID, INSTANCE_ID, CONTEXT)
)
;



-- 
-- TABLE: ACTIONS.TASK_PERIOD 
--

CREATE TABLE ACTIONS.TASK_PERIOD(
    APP_SID                           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID                          NUMBER(10, 0)    NOT NULL,
    START_DTM                         DATE             NOT NULL,
    REGION_SID                        NUMBER(10, 0)    NOT NULL,
    PROJECT_SID                       NUMBER(10, 0),
    TASK_PERIOD_STATUS_ID             NUMBER(10, 0),
    END_DTM                           DATE             NOT NULL,
    APPROVED_DTM                      DATE,
    APPROVED_BY_SID                   NUMBER(10, 0),
    PUBLIC_COMMENT_APPROVED_DTM       DATE,
    PUBLIC_COMMENT_APPROVED_BY_SID    NUMBER(10, 0),
    ENTERED_DTM                       DATE             DEFAULT SYSDATE NOT NULL,
    ENTERED_BY_SID                    NUMBER(10, 0)    NOT NULL,
    FIELDS_XML                        CLOB,
    NEEDS_AGGREGATION                 NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TASK_PERIOD PRIMARY KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_PERIOD_FILE_UPLOAD 
--

CREATE TABLE ACTIONS.TASK_PERIOD_FILE_UPLOAD(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID      NUMBER(10, 0)    NOT NULL,
    START_DTM     DATE             NOT NULL,
    REGION_SID    NUMBER(10, 0)    NOT NULL,
    FILE_ID       NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_PERIOD_FILE_UPLOAD PRIMARY KEY (APP_SID, TASK_SID, START_DTM, REGION_SID, FILE_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_PERIOD_OVERRIDE 
--

CREATE TABLE ACTIONS.TASK_PERIOD_OVERRIDE(
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID             NUMBER(10, 0)    NOT NULL,
    START_DTM            DATE             NOT NULL,
    REGION_SID           NUMBER(10, 0)    NOT NULL,
    OVERRIDDEN_BY_SID    NUMBER(10, 0)    NOT NULL,
    OVERRIDDEN_DTM       DATE             NOT NULL,
    REASON               CLOB             NOT NULL,
    CONSTRAINT PK_TASK_PERIOD_OVERRIDE PRIMARY KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_PERIOD_STATUS 
--

CREATE TABLE ACTIONS.TASK_PERIOD_STATUS(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_PERIOD_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    LABEL                    VARCHAR2(255)    NOT NULL,
    COLOUR                   NUMBER(10, 0),
    SPECIAL_MEANING          VARCHAR2(40),
    MEANS_PCT_COMPLETE       NUMBER(3, 2),
    MEANS_TASK_STATUS_ID     NUMBER(10, 0),
    CONSTRAINT PK_TASK_PERIOD_STATUS PRIMARY KEY (APP_SID, TASK_PERIOD_STATUS_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_RECALC_JOB 
--

CREATE TABLE ACTIONS.TASK_RECALC_JOB(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID      NUMBER(10, 0)    NOT NULL,
    PROCESSING    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK_TASK_RECALC_JOB PRIMARY KEY (APP_SID, TASK_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_RECALC_PERIOD 
--

CREATE TABLE ACTIONS.TASK_RECALC_PERIOD(
    APP_SID      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID     NUMBER(10, 0)    NOT NULL,
    START_DTM    DATE             NOT NULL,
    END_DTM      DATE             NOT NULL,
    CONSTRAINT PK122 PRIMARY KEY (APP_SID, TASK_SID, START_DTM)
)
;



-- 
-- TABLE: ACTIONS.TASK_RECALC_REGION 
--

CREATE TABLE ACTIONS.TASK_RECALC_REGION(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID      NUMBER(10, 0)    NOT NULL,
    REGION_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK121 PRIMARY KEY (APP_SID, TASK_SID, REGION_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_REGION 
--

CREATE TABLE ACTIONS.TASK_REGION(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID        NUMBER(10, 0)    NOT NULL,
    REGION_SID      NUMBER(10, 0)    NOT NULL,
    USE_FOR_CALC    NUMBER(1, 0),
    CONSTRAINT PK_TASK_REGION PRIMARY KEY (APP_SID, TASK_SID, REGION_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_ROLE_MEMBER 
--

CREATE TABLE ACTIONS.TASK_ROLE_MEMBER(
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID             NUMBER(10, 0)    NOT NULL,
    USER_OR_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    PROJECT_SID          NUMBER(10, 0)    NOT NULL,
    ROLE_ID              NUMBER(10, 0)    NOT NULL,
    POS                  NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TASK_ROLE_MEMBER PRIMARY KEY (APP_SID, TASK_SID, USER_OR_GROUP_SID, PROJECT_SID, ROLE_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_STATUS 
--

CREATE TABLE ACTIONS.TASK_STATUS(
    APP_SID             NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_ID      NUMBER(10, 0)     NOT NULL,
    LABEL               VARCHAR2(255)     NOT NULL,
    NOTE                VARCHAR2(1024),
    IS_DEFAULT          NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    IS_LIVE             NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    IS_REJECTED         NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    IS_STOPPED          NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    MEANS_COMPLETED     NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    MEANS_TERMINATED    NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    BELONGS_TO_OWNER    NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    OWNER_CAN_SEE       NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    COLOUR              NUMBER(10, 0)     NOT NULL,
    IS_DRAFT            NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    MEANS_BACK          NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    SHOW_IN_FILTER      NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    CHECK (IS_LIVE IN(0,1)),
    CHECK (IS_REJECTED IN(0,1)),
    CHECK (IS_DEFAULT IN(0,1)),
    CHECK (IS_STOPPED IN(0,1)),
    CHECK (MEANS_COMPLETED IN(0,1)),
    CHECK (MEANS_TERMINATED IN(0,1)),
    CHECK (BELONGS_TO_OWNER IN(0,1)),
    CHECK (OWNER_CAN_SEE IN(0,1)),
    CHECK (IS_DRAFT IN(0,1)),
    CHECK (MEANS_BACK IN(0,1)),
    CHECK (SHOW_IN_FILTER IN(0,1)),
    CONSTRAINT PK_TASK_STATUS PRIMARY KEY (APP_SID, TASK_STATUS_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_STATUS_HISTORY 
--

CREATE TABLE ACTIONS.TASK_STATUS_HISTORY(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID           NUMBER(10, 0)    NOT NULL,
    SET_DTM            DATE             NOT NULL,
    CNT                NUMBER(10, 0)    NOT NULL,
    TASK_STATUS_ID     NUMBER(10, 0),
    SET_BY_USER_SID    NUMBER(10, 0)    NOT NULL,
    COMMENT_TEXT       CLOB,
    CONSTRAINT PK_TASK_STATUS_HISTORY PRIMARY KEY (APP_SID, TASK_SID, SET_DTM, CNT)
)
;



-- 
-- TABLE: ACTIONS.TASK_STATUS_ROLE 
--

CREATE TABLE ACTIONS.TASK_STATUS_ROLE(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_ID     NUMBER(10, 0)    NOT NULL,
    ROLE_SID           NUMBER(10, 0)    NOT NULL,
    GENERATE_ALERTS    NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    CHECK (GENERATE_ALERTS IN(0,1)),
    CONSTRAINT PK125 PRIMARY KEY (APP_SID, TASK_STATUS_ID, ROLE_SID)
)
;



-- 
-- TABLE: ACTIONS.TASK_STATUS_TRANSITION 
--

CREATE TABLE ACTIONS.TASK_STATUS_TRANSITION(
    APP_SID                      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_TRANSITION_ID    NUMBER(10, 0)    NOT NULL,
    TO_TASK_STATUS_ID            NUMBER(10, 0)    NOT NULL,
    FROM_TASK_STATUS_ID          NUMBER(10, 0),
    ALERT_TYPE_ID                NUMBER(10, 0),
    ASK_FOR_COMMENT              NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    SAVE_DATA                    NUMBER(1, 0)     DEFAULT 1 NOT NULL,
    BUTTON_TEXT                  VARCHAR2(255),
    PAGE_BACK                    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    POS                          NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CHECK (ASK_FOR_COMMENT IN(0,1)),
    CHECK (SAVE_DATA IN(0,1)),
    CHECK (PAGE_BACK IN(0,1)),
    CONSTRAINT PK127 PRIMARY KEY (APP_SID, TASK_STATUS_TRANSITION_ID),
    CONSTRAINT CONS_TASK_STATUS_TRANSITION  UNIQUE (TASK_STATUS_TRANSITION_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_TAG 
--

CREATE TABLE ACTIONS.TASK_TAG(
    APP_SID     NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    TAG_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_TAG PRIMARY KEY (APP_SID, TASK_SID, TAG_ID)
)
;



-- 
-- TABLE: ACTIONS.TASK_TASK_DEPENDENCY 
--

CREATE TABLE ACTIONS.TASK_TASK_DEPENDENCY(
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID               NUMBER(10, 0)    NOT NULL,
    DEPENDS_ON_TASK_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_TASK_TASK_DEPENDENCY PRIMARY KEY (APP_SID, TASK_SID, DEPENDS_ON_TASK_SID)
)
;



-- 
-- TABLE: ACTIONS.AGGR_TASK_IND_DEPENDENCY 
--

ALTER TABLE ACTIONS.AGGR_TASK_IND_DEPENDENCY ADD CONSTRAINT RefTASK70 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.AGGR_TASK_PERIOD 
--

ALTER TABLE ACTIONS.AGGR_TASK_PERIOD ADD CONSTRAINT RefTASK62 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.AGGR_TASK_PERIOD ADD CONSTRAINT RefPROJECT_TASK_PERIOD_STATU65 
    FOREIGN KEY (APP_SID, PROJECT_SID, TASK_PERIOD_STATUS_ID)
    REFERENCES ACTIONS.PROJECT_TASK_PERIOD_STATUS(APP_SID, PROJECT_SID, TASK_PERIOD_STATUS_ID)
;

-- 
-- TABLE: ACTIONS.AGGR_TASK_PERIOD_OVERRIDE 
--

ALTER TABLE ACTIONS.AGGR_TASK_PERIOD_OVERRIDE ADD CONSTRAINT RefAGGR_TASK_PERIOD100 
    FOREIGN KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
    REFERENCES ACTIONS.AGGR_TASK_PERIOD(APP_SID, TASK_SID, START_DTM, REGION_SID)
;

-- 
-- TABLE: ACTIONS.AGGR_TASK_TASK_DEPENDENCY 
--

ALTER TABLE ACTIONS.AGGR_TASK_TASK_DEPENDENCY ADD CONSTRAINT RefTASK71 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.AGGR_TASK_TASK_DEPENDENCY ADD CONSTRAINT RefTASK72 
    FOREIGN KEY (APP_SID, DEPENDS_ON_TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.ALLOW_TRANSITION 
--

ALTER TABLE ACTIONS.ALLOW_TRANSITION ADD CONSTRAINT RefTASK_STATUS_TRANSITION241 
    FOREIGN KEY (APP_SID, TASK_STATUS_TRANSITION_ID)
    REFERENCES ACTIONS.TASK_STATUS_TRANSITION(APP_SID, TASK_STATUS_TRANSITION_ID)
;


-- 
-- TABLE: ACTIONS.CSR_TASK_ROLE_MEMBER 
--

ALTER TABLE ACTIONS.CSR_TASK_ROLE_MEMBER ADD CONSTRAINT RefTASK258 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.CUSTOMER_OPTIONS 
--

ALTER TABLE ACTIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefSCRIPT98 
    FOREIGN KEY (APP_SID, DEFAULT_VALUE_SCRIPT_ID)
    REFERENCES ACTIONS.SCRIPT(APP_SID, SCRIPT_ID)
;

-- 
-- TABLE: ACTIONS.FILE_UPLOAD_GROUP_MEMBER 
--

ALTER TABLE ACTIONS.FILE_UPLOAD_GROUP_MEMBER ADD CONSTRAINT RefFILE_UPLOAD185 
    FOREIGN KEY (APP_SID, FILE_ID)
    REFERENCES ACTIONS.FILE_UPLOAD(APP_SID, FILE_ID)
;

ALTER TABLE ACTIONS.FILE_UPLOAD_GROUP_MEMBER ADD CONSTRAINT RefFILE_UPLOAD_GROUP186 
    FOREIGN KEY (APP_SID, FILE_UPLOAD_GROUP_ID)
    REFERENCES ACTIONS.FILE_UPLOAD_GROUP(APP_SID, FILE_UPLOAD_GROUP_ID)
;


-- 
-- TABLE: ACTIONS.IMPORT_TEMPLATE 
--

ALTER TABLE ACTIONS.IMPORT_TEMPLATE ADD CONSTRAINT RefPROJECT299 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

-- 
-- TABLE: ACTIONS.IMPORT_TEMPLATE_MAPPING 
--

ALTER TABLE ACTIONS.IMPORT_TEMPLATE_MAPPING ADD CONSTRAINT RefIMPORT_TEMPLATE301 
    FOREIGN KEY (APP_SID, IMPORT_TEMPLATE_ID)
    REFERENCES ACTIONS.IMPORT_TEMPLATE(APP_SID, IMPORT_TEMPLATE_ID)
;


-- 
-- TABLE: ACTIONS.IND_TEMPLATE_GROUP 
--

ALTER TABLE ACTIONS.IND_TEMPLATE_GROUP ADD CONSTRAINT RefPROJECT317 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;


-- 
-- TABLE: ACTIONS.INITIATIVE_EXTRA_INFO 
--

ALTER TABLE ACTIONS.INITIATIVE_EXTRA_INFO ADD CONSTRAINT RefTASK106 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.INITIATIVE_PROJECT_TEAM 
--

ALTER TABLE ACTIONS.INITIATIVE_PROJECT_TEAM ADD CONSTRAINT RefTASK107 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.INITIATIVE_SPONSOR 
--

ALTER TABLE ACTIONS.INITIATIVE_SPONSOR ADD CONSTRAINT RefTASK193 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.INSTANCE_GAS_IND 
--

ALTER TABLE ACTIONS.INSTANCE_GAS_IND ADD CONSTRAINT RefTASK_IND_TEMPLATE_INSTAN314 
    FOREIGN KEY (APP_SID, TASK_SID, FROM_IND_TEMPLATE_ID)
    REFERENCES ACTIONS.TASK_IND_TEMPLATE_INSTANCE(APP_SID, TASK_SID, FROM_IND_TEMPLATE_ID)
;


-- 
-- TABLE: ACTIONS.PERIODIC_ALERT_USER 
--

ALTER TABLE ACTIONS.PERIODIC_ALERT_USER ADD CONSTRAINT RefPERIODIC_ALERT273 
    FOREIGN KEY (APP_SID, ALERT_TYPE_ID)
    REFERENCES ACTIONS.PERIODIC_ALERT(APP_SID, ALERT_TYPE_ID)
;

-- 
-- TABLE: ACTIONS.PROJECT_FILE_UPLOAD_GROUP 
--

ALTER TABLE ACTIONS.PROJECT_FILE_UPLOAD_GROUP ADD CONSTRAINT RefPROJECT187 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE ACTIONS.PROJECT_FILE_UPLOAD_GROUP ADD CONSTRAINT RefFILE_UPLOAD_GROUP188 
    FOREIGN KEY (APP_SID, FILE_UPLOAD_GROUP_ID)
    REFERENCES ACTIONS.FILE_UPLOAD_GROUP(APP_SID, FILE_UPLOAD_GROUP_ID)
;


-- 
-- TABLE: ACTIONS.PROJECT_IND_TEMPLATE 
--

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE ADD CONSTRAINT RefIND_TEMPLATE233 
    FOREIGN KEY (APP_SID, SAVING_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE ADD CONSTRAINT RefIND_TEMPLATE278 
    FOREIGN KEY (APP_SID, ONGOING_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE ADD CONSTRAINT RefIND_TEMPLATE280 
    FOREIGN KEY (APP_SID, MERGED_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE ADD CONSTRAINT RefIND_TEMPLATE_GROUP318 
    FOREIGN KEY (APP_SID, PROJECT_SID, POS_GROUP)
    REFERENCES ACTIONS.IND_TEMPLATE_GROUP(APP_SID, PROJECT_SID, POS_GROUP)
;

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE ADD CONSTRAINT RefPROJECT90 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE ADD CONSTRAINT RefIND_TEMPLATE91 
    FOREIGN KEY (APP_SID, IND_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;


-- 
-- TABLE: ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE 
--

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefIND_TEMPLATE92 
    FOREIGN KEY (APP_SID, FROM_IND_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;

ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefPROJECT93 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

-- 
-- TABLE: ACTIONS.PROJECT_REGION_ROLE_MEMBER 
--

ALTER TABLE ACTIONS.PROJECT_REGION_ROLE_MEMBER ADD CONSTRAINT RefPROJECT295 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;


-- 
-- TABLE: ACTIONS.PROJECT_ROLE 
--

ALTER TABLE ACTIONS.PROJECT_ROLE ADD CONSTRAINT RefPROJECT27 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE ACTIONS.PROJECT_ROLE ADD CONSTRAINT RefROLE30 
    FOREIGN KEY (APP_SID, ROLE_ID)
    REFERENCES ACTIONS.ROLE(APP_SID, ROLE_ID)
;


-- 
-- TABLE: ACTIONS.PROJECT_ROLE_MEMBER 
--

ALTER TABLE ACTIONS.PROJECT_ROLE_MEMBER ADD CONSTRAINT RefPROJECT_ROLE31 
    FOREIGN KEY (APP_SID, PROJECT_SID, ROLE_ID)
    REFERENCES ACTIONS.PROJECT_ROLE(APP_SID, PROJECT_SID, ROLE_ID)
;


-- 
-- TABLE: ACTIONS.PROJECT_TAG_GROUP 
--

ALTER TABLE ACTIONS.PROJECT_TAG_GROUP ADD CONSTRAINT RefPROJECT39 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE ACTIONS.PROJECT_TAG_GROUP ADD CONSTRAINT RefTAG_GROUP40 
    FOREIGN KEY (APP_SID, TAG_GROUP_ID)
    REFERENCES ACTIONS.TAG_GROUP(APP_SID, TAG_GROUP_ID)
;


-- 
-- TABLE: ACTIONS.PROJECT_TASK_PERIOD_STATUS 
--

ALTER TABLE ACTIONS.PROJECT_TASK_PERIOD_STATUS ADD CONSTRAINT RefPROJECT22 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE ACTIONS.PROJECT_TASK_PERIOD_STATUS ADD CONSTRAINT RefTASK_PERIOD_STATUS23 
    FOREIGN KEY (APP_SID, TASK_PERIOD_STATUS_ID)
    REFERENCES ACTIONS.TASK_PERIOD_STATUS(APP_SID, TASK_PERIOD_STATUS_ID)
;


-- 
-- TABLE: ACTIONS.PROJECT_TASK_STATUS 
--

ALTER TABLE ACTIONS.PROJECT_TASK_STATUS ADD CONSTRAINT RefPROJECT19 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE ACTIONS.PROJECT_TASK_STATUS ADD CONSTRAINT RefTASK_STATUS20 
    FOREIGN KEY (APP_SID, TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;


-- 
-- TABLE: ACTIONS.RECKONER_CONST_DEP 
--

ALTER TABLE ACTIONS.RECKONER_CONST_DEP ADD CONSTRAINT RefRECKONER_CONST201 
    FOREIGN KEY (RECKONER_CONST_ID)
    REFERENCES ACTIONS.RECKONER_CONST(RECKONER_CONST_ID)
;

ALTER TABLE ACTIONS.RECKONER_CONST_DEP ADD CONSTRAINT RefRECKONER202 
    FOREIGN KEY (RECKONER_ID)
    REFERENCES ACTIONS.RECKONER(RECKONER_ID)
;


-- 
-- TABLE: ACTIONS.RECKONER_INPUT 
--

ALTER TABLE ACTIONS.RECKONER_INPUT ADD CONSTRAINT RefRECKONER203 
    FOREIGN KEY (RECKONER_ID)
    REFERENCES ACTIONS.RECKONER(RECKONER_ID)
;


-- 
-- TABLE: ACTIONS.RECKONER_OUTPUT 
--

ALTER TABLE ACTIONS.RECKONER_OUTPUT ADD CONSTRAINT RefRECKONER204 
    FOREIGN KEY (RECKONER_ID)
    REFERENCES ACTIONS.RECKONER(RECKONER_ID)
;


-- 
-- TABLE: ACTIONS.RECKONER_TAG 
--

ALTER TABLE ACTIONS.RECKONER_TAG ADD CONSTRAINT RefTAG_GROUP_MEMBER218 
    FOREIGN KEY (APP_SID, TAG_GROUP_ID, TAG_ID)
    REFERENCES ACTIONS.TAG_GROUP_MEMBER(APP_SID, TAG_GROUP_ID, TAG_ID)
;

ALTER TABLE ACTIONS.RECKONER_TAG ADD CONSTRAINT RefRECKONER_TAG_GROUP219 
    FOREIGN KEY (APP_SID, PROJECT_SID, TAG_GROUP_ID)
    REFERENCES ACTIONS.RECKONER_TAG_GROUP(APP_SID, PROJECT_SID, TAG_GROUP_ID)
;

ALTER TABLE ACTIONS.RECKONER_TAG ADD CONSTRAINT RefRECKONER220 
    FOREIGN KEY (RECKONER_ID)
    REFERENCES ACTIONS.RECKONER(RECKONER_ID)
;


-- 
-- TABLE: ACTIONS.RECKONER_TAG_GROUP 
--

ALTER TABLE ACTIONS.RECKONER_TAG_GROUP ADD CONSTRAINT RefPROJECT_TAG_GROUP217 
    FOREIGN KEY (APP_SID, TAG_GROUP_ID, PROJECT_SID)
    REFERENCES ACTIONS.PROJECT_TAG_GROUP(APP_SID, TAG_GROUP_ID, PROJECT_SID)
;


-- 
-- TABLE: ACTIONS.ROOT_IND_TEMPLATE_INSTANCE 
--

ALTER TABLE ACTIONS.ROOT_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefIND_TEMPLATE94 
    FOREIGN KEY (APP_SID, FROM_IND_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;

-- 
-- TABLE: ACTIONS.SCENARIO_FILTER_STATUS 
--

ALTER TABLE ACTIONS.SCENARIO_FILTER_STATUS ADD CONSTRAINT RefTASK_STATUS327 
    FOREIGN KEY (APP_SID, TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

ALTER TABLE ACTIONS.SCENARIO_FILTER_STATUS ADD CONSTRAINT RefSCENARIO_FILTER332 
    FOREIGN KEY (APP_SID, SCENARIO_SID, RULE_ID)
    REFERENCES ACTIONS.SCENARIO_FILTER(APP_SID, SCENARIO_SID, RULE_ID)
;


-- 
-- TABLE: ACTIONS.TAG_GROUP_MEMBER 
--

ALTER TABLE ACTIONS.TAG_GROUP_MEMBER ADD CONSTRAINT RefTAG_GROUP41 
    FOREIGN KEY (APP_SID, TAG_GROUP_ID)
    REFERENCES ACTIONS.TAG_GROUP(APP_SID, TAG_GROUP_ID)
;

ALTER TABLE ACTIONS.TAG_GROUP_MEMBER ADD CONSTRAINT RefTAG42 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES ACTIONS.TAG(APP_SID, TAG_ID)
;


-- 
-- TABLE: ACTIONS.TASK 
--

ALTER TABLE ACTIONS.TASK ADD CONSTRAINT RefTASK2 
    FOREIGN KEY (APP_SID, PARENT_TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.TASK ADD CONSTRAINT RefPROJECT_TASK_STATUS21 
    FOREIGN KEY (APP_SID, PROJECT_SID, TASK_STATUS_ID)
    REFERENCES ACTIONS.PROJECT_TASK_STATUS(APP_SID, PROJECT_SID, TASK_STATUS_ID)
;

ALTER TABLE ACTIONS.TASK ADD CONSTRAINT FK_TASK_ST_TR_TASK 
    FOREIGN KEY (LAST_TRANSITION_ID)
    REFERENCES ACTIONS.TASK_STATUS_TRANSITION(TASK_STATUS_TRANSITION_ID) ON DELETE SET NULL
;


-- 
-- TABLE: ACTIONS.TASK_BUDGET_HISTORY 
--

ALTER TABLE ACTIONS.TASK_BUDGET_HISTORY ADD CONSTRAINT RefTASK32 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.TASK_BUDGET_PERIOD 
--

ALTER TABLE ACTIONS.TASK_BUDGET_PERIOD ADD CONSTRAINT RefTASK14 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_COMMENT 
--

ALTER TABLE ACTIONS.TASK_COMMENT ADD CONSTRAINT RefTASK7 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.TASK_FILE_UPLOAD 
--

ALTER TABLE ACTIONS.TASK_FILE_UPLOAD ADD CONSTRAINT RefFILE_UPLOAD79 
    FOREIGN KEY (APP_SID, FILE_ID)
    REFERENCES ACTIONS.FILE_UPLOAD(APP_SID, FILE_ID)
;

ALTER TABLE ACTIONS.TASK_FILE_UPLOAD ADD CONSTRAINT RefTASK80 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_IND_DEPENDENCY 
--

ALTER TABLE ACTIONS.TASK_IND_DEPENDENCY ADD CONSTRAINT RefTASK55 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.TASK_IND_TEMPLATE_INSTANCE 
--

ALTER TABLE ACTIONS.TASK_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefTASK95 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.TASK_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefIND_TEMPLATE96 
    FOREIGN KEY (APP_SID, FROM_IND_TEMPLATE_ID)
    REFERENCES ACTIONS.IND_TEMPLATE(APP_SID, IND_TEMPLATE_ID)
;

-- 
-- TABLE: ACTIONS.TASK_INDICATOR 
--

ALTER TABLE ACTIONS.TASK_INDICATOR ADD CONSTRAINT RefTASK16 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.TASK_INSTANCE 
--

ALTER TABLE ACTIONS.TASK_INSTANCE ADD CONSTRAINT RefTASK50 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_PERIOD 
--

ALTER TABLE ACTIONS.TASK_PERIOD ADD CONSTRAINT RefTASK6 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.TASK_PERIOD ADD CONSTRAINT RefPROJECT_TASK_PERIOD_STATU26 
    FOREIGN KEY (APP_SID, PROJECT_SID, TASK_PERIOD_STATUS_ID)
    REFERENCES ACTIONS.PROJECT_TASK_PERIOD_STATUS(APP_SID, PROJECT_SID, TASK_PERIOD_STATUS_ID)
;

ALTER TABLE ACTIONS.TASK_PERIOD ADD CONSTRAINT RefTASK_REGION102 
    FOREIGN KEY (APP_SID, TASK_SID, REGION_SID)
    REFERENCES ACTIONS.TASK_REGION(APP_SID, TASK_SID, REGION_SID)
;


-- 
-- TABLE: ACTIONS.TASK_PERIOD_FILE_UPLOAD 
--

ALTER TABLE ACTIONS.TASK_PERIOD_FILE_UPLOAD ADD CONSTRAINT RefFILE_UPLOAD81 
    FOREIGN KEY (APP_SID, FILE_ID)
    REFERENCES ACTIONS.FILE_UPLOAD(APP_SID, FILE_ID)
;

ALTER TABLE ACTIONS.TASK_PERIOD_FILE_UPLOAD ADD CONSTRAINT RefTASK_PERIOD82 
    FOREIGN KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
    REFERENCES ACTIONS.TASK_PERIOD(APP_SID, TASK_SID, START_DTM, REGION_SID)
;


-- 
-- TABLE: ACTIONS.TASK_PERIOD_OVERRIDE 
--

ALTER TABLE ACTIONS.TASK_PERIOD_OVERRIDE ADD CONSTRAINT RefTASK_PERIOD74 
    FOREIGN KEY (APP_SID, TASK_SID, START_DTM, REGION_SID)
    REFERENCES ACTIONS.TASK_PERIOD(APP_SID, TASK_SID, START_DTM, REGION_SID)
;

-- 
-- TABLE: ACTIONS.TASK_PERIOD_STATUS 
--

ALTER TABLE ACTIONS.TASK_PERIOD_STATUS ADD CONSTRAINT RefTASK_STATUS254 
    FOREIGN KEY (APP_SID, MEANS_TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

-- 
-- TABLE: ACTIONS.TASK_RECALC_JOB 
--

ALTER TABLE ACTIONS.TASK_RECALC_JOB ADD CONSTRAINT RefTASK56 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_RECALC_PERIOD 
--

ALTER TABLE ACTIONS.TASK_RECALC_PERIOD ADD CONSTRAINT RefTASK_RECALC_JOB226 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK_RECALC_JOB(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_RECALC_REGION 
--

ALTER TABLE ACTIONS.TASK_RECALC_REGION ADD CONSTRAINT RefTASK_REGION227 
    FOREIGN KEY (APP_SID, TASK_SID, REGION_SID)
    REFERENCES ACTIONS.TASK_REGION(APP_SID, TASK_SID, REGION_SID)
;

ALTER TABLE ACTIONS.TASK_RECALC_REGION ADD CONSTRAINT RefTASK_RECALC_JOB228 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK_RECALC_JOB(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_REGION 
--

ALTER TABLE ACTIONS.TASK_REGION ADD CONSTRAINT RefTASK52 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.TASK_ROLE_MEMBER 
--

ALTER TABLE ACTIONS.TASK_ROLE_MEMBER ADD CONSTRAINT RefTASK4 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.TASK_ROLE_MEMBER ADD CONSTRAINT RefPROJECT_ROLE_MEMBER5 
    FOREIGN KEY (APP_SID, PROJECT_SID, ROLE_ID, USER_OR_GROUP_SID)
    REFERENCES ACTIONS.PROJECT_ROLE_MEMBER(APP_SID, PROJECT_SID, ROLE_ID, USER_OR_GROUP_SID)
;


-- 
-- TABLE: ACTIONS.TASK_STATUS_HISTORY 
--

ALTER TABLE ACTIONS.TASK_STATUS_HISTORY ADD CONSTRAINT RefTASK_STATUS47 
    FOREIGN KEY (APP_SID, TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

ALTER TABLE ACTIONS.TASK_STATUS_HISTORY ADD CONSTRAINT RefTASK48 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

-- 
-- TABLE: ACTIONS.TASK_STATUS_ROLE 
--

ALTER TABLE ACTIONS.TASK_STATUS_ROLE ADD CONSTRAINT RefTASK_STATUS244 
    FOREIGN KEY (APP_SID, TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;


-- 
-- TABLE: ACTIONS.TASK_STATUS_TRANSITION 
--

ALTER TABLE ACTIONS.TASK_STATUS_TRANSITION ADD CONSTRAINT RefTASK_STATUS245 
    FOREIGN KEY (APP_SID, FROM_TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

ALTER TABLE ACTIONS.TASK_STATUS_TRANSITION ADD CONSTRAINT RefTASK_STATUS247 
    FOREIGN KEY (APP_SID, TO_TASK_STATUS_ID)
    REFERENCES ACTIONS.TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

-- 
-- TABLE: ACTIONS.TASK_TAG 
--

ALTER TABLE ACTIONS.TASK_TAG ADD CONSTRAINT RefTAG43 
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES ACTIONS.TAG(APP_SID, TAG_ID)
;

ALTER TABLE ACTIONS.TASK_TAG ADD CONSTRAINT RefTASK44 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


-- 
-- TABLE: ACTIONS.TASK_TASK_DEPENDENCY 
--

ALTER TABLE ACTIONS.TASK_TASK_DEPENDENCY ADD CONSTRAINT RefTASK59 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;

ALTER TABLE ACTIONS.TASK_TASK_DEPENDENCY ADD CONSTRAINT RefTASK60 
    FOREIGN KEY (APP_SID, DEPENDS_ON_TASK_SID)
    REFERENCES ACTIONS.TASK(APP_SID, TASK_SID)
;


