 
ALTER TABLE ACTIONS.AGGR_TASK_IND_DEPENDENCY ADD CONSTRAINT RefIND146 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

 
ALTER TABLE ACTIONS.AGGR_TASK_PERIOD ADD CONSTRAINT RefREGION147 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

 
ALTER TABLE ACTIONS.AGGR_TASK_PERIOD_OVERRIDE ADD CONSTRAINT RefCSR_USER148 
    FOREIGN KEY (APP_SID, OVERRIDDEN_BY_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.CSR_TASK_ROLE_MEMBER ADD CONSTRAINT RefROLE257 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID)
;

ALTER TABLE ACTIONS.CSR_TASK_ROLE_MEMBER ADD CONSTRAINT RefCSR_USER270 
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOMER150 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE ACTIONS.FILE_UPLOAD ADD CONSTRAINT RefCUSTOMER151 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE ACTIONS.FILE_UPLOAD_GROUP ADD CONSTRAINT RefCUSTOMER190 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE ACTIONS.IMPORT_MAPPING_MRU ADD CONSTRAINT RefCSR_USER276 
    FOREIGN KEY (APP_SID, CSR_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.IMPORT_TEMPLATE ADD CONSTRAINT RefCUSTOMER300 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;



ALTER TABLE ACTIONS.IND_TEMPLATE ADD CONSTRAINT RefMEASURE153 
    FOREIGN KEY (APP_SID, MEASURE_SID)
    REFERENCES CSR.MEASURE(APP_SID, MEASURE_SID)
;



ALTER TABLE ACTIONS.PERIODIC_ALERT ADD CONSTRAINT RefCUSTOMER271 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE ACTIONS.PERIODIC_ALERT ADD CONSTRAINT RefALERT_TYPE272 
    FOREIGN KEY (ALERT_TYPE_ID)
    REFERENCES CSR.STD_ALERT_TYPE(STD_ALERT_TYPE_ID)
;

 
ALTER TABLE ACTIONS.PERIODIC_ALERT_USER ADD CONSTRAINT RefCSR_USER274 
    FOREIGN KEY (APP_SID, CSR_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE ACTIONS.PERIODIC_REPORT_TEMPLATE ADD CONSTRAINT RefCUSTOMER282 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE ACTIONS.PROJECT ADD CONSTRAINT RefIND155 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE ACTIONS.PROJECT ADD CONSTRAINT RefCUSTOMER156 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

 
ALTER TABLE ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefIND157 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE ACTIONS.PROJECT_REGION_ROLE_MEMBER ADD CONSTRAINT RefROLE291 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID)
;

ALTER TABLE ACTIONS.PROJECT_REGION_ROLE_MEMBER ADD CONSTRAINT RefCSR_USER292 
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE ACTIONS.PROJECT_REGION_ROLE_MEMBER ADD CONSTRAINT RefREGION293 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE ACTIONS.PROJECT_REGION_ROLE_MEMBER ADD CONSTRAINT RefREGION294 
    FOREIGN KEY (APP_SID, INHERITED_FROM_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

-- TABLE: ACTIONS.ROLE 
--

ALTER TABLE ACTIONS.ROLE ADD CONSTRAINT RefCUSTOMER160 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE ACTIONS.ROOT_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefIND161 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;


-- 
-- TABLE: ACTIONS.SCRIPT 
--

ALTER TABLE ACTIONS.SCRIPT ADD CONSTRAINT RefCUSTOMER162 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


-- 
-- TABLE: ACTIONS.TAG 
--

ALTER TABLE ACTIONS.TAG ADD CONSTRAINT RefCUSTOMER163 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


-- 
-- TABLE: ACTIONS.TAG_GROUP 
--

ALTER TABLE ACTIONS.TAG_GROUP ADD CONSTRAINT RefCUSTOMER164 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


ALTER TABLE ACTIONS.TASK ADD CONSTRAINT RefIND165 
    FOREIGN KEY (APP_SID, INPUT_IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE ACTIONS.TASK ADD CONSTRAINT RefIND166 
    FOREIGN KEY (APP_SID, TARGET_IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE ACTIONS.TASK ADD CONSTRAINT RefIND167 
    FOREIGN KEY (APP_SID, OUTPUT_IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE ACTIONS.TASK_BUDGET_HISTORY ADD CONSTRAINT RefCSR_USER168 
    FOREIGN KEY (APP_SID, SET_BY_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.TASK_COMMENT ADD CONSTRAINT RefCSR_USER169 
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.TASK_IND_DEPENDENCY ADD CONSTRAINT RefIND170 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;


ALTER TABLE ACTIONS.TASK_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefIND171 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;


ALTER TABLE ACTIONS.TASK_INDICATOR ADD CONSTRAINT RefIND172 
    FOREIGN KEY (APP_SID, INDICATOR_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;


ALTER TABLE ACTIONS.TASK_PERIOD_OVERRIDE ADD CONSTRAINT RefCSR_USER173 
    FOREIGN KEY (APP_SID, OVERRIDDEN_BY_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.TASK_PERIOD_STATUS ADD CONSTRAINT RefCUSTOMER174 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE ACTIONS.TASK_REGION ADD CONSTRAINT RefREGION175 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;


-- TABLE: ACTIONS.TASK_STATUS 
--

ALTER TABLE ACTIONS.TASK_STATUS ADD CONSTRAINT RefCUSTOMER176 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


-- 
ALTER TABLE ACTIONS.TASK_STATUS_HISTORY ADD CONSTRAINT RefCSR_USER177 
    FOREIGN KEY (APP_SID, SET_BY_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE ACTIONS.TASK_STATUS_ROLE ADD CONSTRAINT RefROLE243 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID)
;

ALTER TABLE ACTIONS.TASK_STATUS_TRANSITION ADD CONSTRAINT RefCUSTOMER246 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE ACTIONS.TASK_STATUS_TRANSITION ADD CONSTRAINT RefALERT_TYPE249 
    FOREIGN KEY (ALERT_TYPE_ID)
    REFERENCES CSR.STD_ALERT_TYPE(STD_ALERT_TYPE_ID)
;


-- TABLE: IND_TEMPLATE

ALTER TABLE ACTIONS.IND_TEMPLATE ADD CONSTRAINT RefMEASURE304 
    FOREIGN KEY (APP_SID, GAS_MEASURE_SID)
    REFERENCES CSR.MEASURE(APP_SID, MEASURE_SID)
;

ALTER TABLE ACTIONS.IND_TEMPLATE ADD CONSTRAINT RefFACTOR_TYPE305 
    FOREIGN KEY (FACTOR_TYPE_ID)
    REFERENCES CSR.FACTOR_TYPE(FACTOR_TYPE_ID)
;

-- TABLE: TASK_IND_TEMPLATE_INSTANCE

ALTER TABLE ACTIONS.TASK_IND_TEMPLATE_INSTANCE ADD CONSTRAINT RefMEASURE_CONVERSION309 
    FOREIGN KEY (APP_SID, ENTRY_MEASURE_CONVERSION_ID)
    REFERENCES CSR.MEASURE_CONVERSION(APP_SID, MEASURE_CONVERSION_ID)
;

-- TABLE: INSTANCE_GAS_IND

ALTER TABLE ACTIONS.INSTANCE_GAS_IND ADD CONSTRAINT FK_IND_INST_GAS_IND 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

-- TABLE: SCENARIO_FILTER_STATUS

ALTER TABLE ACTIONS.SCENARIO_FILTER_STATUS ADD CONSTRAINT FK_SCN_RULE_FILTER_STAT
    FOREIGN KEY (APP_SID, SCENARIO_SID, RULE_ID)
    REFERENCES CSR.SCENARIO_RULE(APP_SID, SCENARIO_SID, RULE_ID)
;