whenever oserror exit failure rollback
whenever sqlerror exit failure rollback

create index chain.ix_al_ent_al_ent_app_ent_tpl on chain.alert_entry (app_sid, alert_entry_type_id, template_name);
create index chain.ix_alert_entry_alrt_en_type on chain.alert_entry (alert_entry_type_id);
create index chain.ix_alert_entry_user_sid on chain.alert_entry (app_sid, user_sid);
create index chain.ix_alert_entry_alert_sid_u on chain.alert_entry (app_sid, user_sid, owner_scheduled_alert_id);
create index chain.ix_alert_entry_t_alert_entry_t on chain.alert_entry_template (alert_entry_type_id);
create index chain.ix_applied_compa_group_capabil on chain.applied_company_capability (group_capability_id);
create index chain.ix_card_group_ca_required_capa on chain.card_group_card (required_capability_id);
create index chain.ix_card_group_ca_card_id on chain.card_group_card (card_id);
create index chain.ix_card_group_ca_card_group_id on chain.card_group_card (card_group_id);
create index chain.ix_card_group_pr_card_group_id on chain.card_group_progression (app_sid, card_group_id, to_card_id);
create index chain.ix_card_group_pr_from_card_id_ on chain.card_group_progression (from_card_id, from_card_action);
create index chain.ix_chain_user_default_compa on chain.chain_user (app_sid, default_company_sid);
create index chain.ix_chain_user_merged_to_use on chain.chain_user (app_sid, merged_to_user_sid);
create index chain.ix_chain_user_registration_ on chain.chain_user (registration_status_id);
create index chain.ix_chain_user_visibility_id on chain.chain_user (visibility_id);
create index chain.ix_company_country_code on chain.company (country_code);
create index chain.ix_company_metri_company_sid on chain.company_metric (app_sid, company_sid);
create index chain.ix_component_app_sid on chain.component (app_sid);
create index chain.ix_component_sou_component_typ on chain.component_source (component_type_id, app_sid);
create index chain.ix_component_typ_app_sid on chain.component_type (app_sid);
create index chain.ix_component_typ_child_compone on chain.component_type_containment (child_component_type_id, app_sid);
create index chain.ix_component_typ_container_com on chain.component_type_containment (container_component_type_id, app_sid);
create index chain.ix_group_capabil_capability_id on chain.group_capability (capability_id);
create index chain.ix_group_capabil_group_capabil on chain.group_capability_override (group_capability_id);
create index chain.ix_invitation_from_user_sid on chain.invitation (app_sid, from_user_sid);
create index chain.ix_invitation_to_user_sid on chain.invitation (app_sid, to_user_sid);
create index chain.ix_invitation_cancelled_by_ on chain.invitation (app_sid, cancelled_by_user_sid);
create index chain.ix_invitation_from_company_ on chain.invitation (app_sid, from_company_sid);
create index chain.ix_invitation_to_company_si on chain.invitation (app_sid, to_company_sid);
create index chain.ix_invitation_reinvitation_ on chain.invitation (app_sid, reinvitation_of_invitation_id);
create index chain.ix_invitation_invitation_st on chain.invitation (invitation_status_id);
create index chain.ix_invitation_invitation_ty on chain.invitation (invitation_type_id);
create index chain.ix_invitation_qn_added_by_user on chain.invitation_qnr_type (app_sid, added_by_user_sid);
create index chain.ix_invitation_qn_questionnaire on chain.invitation_qnr_type (app_sid, questionnaire_type_id);
create index chain.ix_newsflash_com_company_sid on chain.newsflash_company (app_sid, company_sid);
create index chain.ix_newsflash_use_user_sid on chain.newsflash_user_settings (app_sid, user_sid);
create index chain.ix_product_app_sid on chain.product (app_sid);
create index chain.ix_product_metri_app_sid on chain.product_metric_type (app_sid);
create index chain.ix_qnr_share_log_user_sid on chain.qnr_share_log_entry (app_sid, user_sid);
create index chain.ix_qnr_share_log_company_sid on chain.qnr_share_log_entry (app_sid, company_sid);
create index chain.ix_qnr_share_log_share_status_ on chain.qnr_share_log_entry (share_status_id);
create index chain.ix_qnr_status_lo_user_sid on chain.qnr_status_log_entry (app_sid, user_sid);
create index chain.ix_qnr_status_lo_questionnaire on chain.qnr_status_log_entry (questionnaire_status_id);
create index chain.ix_questionnaire_questionnaire on chain.questionnaire (app_sid, questionnaire_type_id);
create index chain.ix_questionnaire_quest_metric on chain.questionnaire_metric (app_sid, questionnaire_metric_type_id);
create index chain.ix_questionnaire_quest_metrict on chain.questionnaire_metric_type (app_sid, questionnaire_type_id);
create index chain.ix_questionnaire_quest_share on chain.questionnaire_share (app_sid, questionnaire_id);
create index chain.ix_questionnaire_group_name on chain.questionnaire_type (app_sid, group_name);
create index chain.ix_reset_passwor_user_sid on chain.reset_password (app_sid, user_sid);
create index chain.ix_reset_passwor_accept_invita on chain.reset_password (app_sid, accept_invitation_on_reset);
create index chain.ix_scheduled_ale_user_sid on chain.scheduled_alert (app_sid, user_sid);
create index chain.ix_supplier_rela_supplier_comp on chain.supplier_relationship (app_sid, supplier_company_sid);
create index chain.ix_task_last_updated_ on chain.task (app_sid, last_updated_by_sid);
create index chain.ix_task_app_sid on chain.task (app_sid);
create index chain.ix_task_task_status_i on chain.task (task_status_id);
create index chain.ix_task_task_type_id_ on chain.task (task_type_id, app_sid);
create index chain.ix_task_entry_app_sid on chain.task_entry (app_sid);
create index chain.ix_task_entry_task_id_app_s on chain.task_entry (task_id, app_sid);
create index chain.ix_task_type_app_sid on chain.task_type (app_sid);
create index chain.ix_task_type_parent_task_t on chain.task_type (parent_task_type_id, app_sid);
create index chain.ix_all_component_editor_card_g on chain.all_component_type (editor_card_group_id);
create index chain.ix_amount_unit_app_sid on chain.amount_unit (app_sid);
create index chain.ix_company_sector_id on chain.company (app_sid, sector_id);
create index chain.ix_component_created_by_si on chain.component (app_sid, created_by_sid);
create index chain.ix_component_doc_file_upload_s on chain.component_document (app_sid, file_upload_sid);
create index chain.ix_component_sou_card_group_id on chain.component_source (card_group_id);
create index chain.ix_component_typ_component_typ on chain.component_type (component_type_id);
create index chain.ix_compound_filt_card_group_id on chain.compound_filter (card_group_id);
create index chain.ix_compound_filt_created_by_us on chain.compound_filter (app_sid, created_by_user_sid);
create index chain.ix_compound_filt_read_only_sav on chain.compound_filter (app_sid, read_only_saved_filter_sid);
create index chain.ix_default_messa_addressing_ty on chain.default_message_definition (addressing_type_id);
create index chain.ix_default_messa_completion_ty on chain.default_message_definition (completion_type_id);
create index chain.ix_default_messa_message_prior on chain.default_message_definition (message_priority_id);
create index chain.ix_default_messa_repeat_type_i on chain.default_message_definition (repeat_type_id);
create index chain.ix_file_group_company_sid on chain.file_group (app_sid, company_sid);
create index chain.ix_file_group_download_perm on chain.file_group (download_permission_id);
create index chain.ix_file_group_file_group_mo on chain.file_group (file_group_model_id);
create index chain.ix_file_group_fi_file_upload_s on chain.file_group_file (app_sid, file_upload_sid);
create index chain.ix_file_upload_download_perm on chain.file_upload (download_permission_id);
create index chain.ix_file_upload_lang on chain.file_upload (app_sid, lang);
create index chain.ix_filter_compound_filt on chain.filter (app_sid, compound_filter_id);
create index chain.ix_filter_filter_type_i on chain.filter (filter_type_id);
create index chain.ix_filter_field_filter_id on chain.filter_field (app_sid, filter_id);
create index chain.ix_filter_value_filter_field_ on chain.filter_value (app_sid, filter_field_id);
create index chain.ix_filter_value_compound_filt on chain.filter_value (app_sid, compound_filter_id_value);
create index chain.ix_message_re_user_sid on chain.message (app_sid, re_user_sid);
create index chain.ix_message_completed_by_ on chain.message (app_sid, completed_by_user_sid);
create index chain.ix_message_re_company_si on chain.message (app_sid, re_company_sid);
create index chain.ix_message_re_component_ on chain.message (app_sid, re_component_id);
create index chain.ix_message_message_defin on chain.message (message_definition_id);
create index chain.ix_message_re_questionna on chain.message (app_sid, re_questionnaire_type_id);
create index chain.ix_message_defin_message_defin on chain.message_definition (message_definition_id);
create index chain.ix_message_defin_message_prior on chain.message_definition (message_priority_id);
create index chain.ix_message_param_message_defin on chain.message_param (message_definition_id, param_name);
create index chain.ix_message_recip_recipient_id on chain.message_recipient (app_sid, recipient_id);
create index chain.ix_message_recip_message_id on chain.message_recipient (app_sid, message_id);
create index chain.ix_message_refre_refresh_user_ on chain.message_refresh_log (app_sid, refresh_user_sid);
create index chain.ix_product_last_publishe on chain.product_revision (app_sid, last_published_by_user_sid);
create index chain.ix_product_validated_root_c on chain.product_revision (app_sid, validated_root_component_id);
create index chain.ix_purchase_purchaser_com on chain.purchase (app_sid, purchaser_company_sid, purchase_channel_id);
create index chain.ix_purchase_purchs_compan on chain.purchase (app_sid, purchaser_company_sid);
create index chain.ix_purchase_amount_unit_i on chain.purchase (amount_unit_id, app_sid);
create index chain.ix_purchased_com_company_sid_s on chain.purchased_component (app_sid, company_sid, supplier_company_sid);
create index chain.ix_purchased_com_acceptance_st on chain.purchased_component (acceptance_status_id);
create index chain.ix_purchased_com_mapped_by_use on chain.purchased_component (app_sid, mapped_by_user_sid);
create index chain.ix_purchased_com_component_id_ on chain.purchased_component (app_sid, component_id, component_type_id, company_sid);
create index chain.ix_purchased_com_component_sup on chain.purchased_component (component_supplier_type_id);
create index chain.ix_purchased_com_supplier_prod on chain.purchased_component (app_sid, supplier_product_id);
create index chain.ix_purchased_com_company_sid_u on chain.purchased_component (app_sid, company_sid, uninvited_supplier_sid);
create index chain.ix_purchaser_fol_user_sid on chain.purchaser_follower (app_sid, user_sid);
create index chain.ix_recipient_to_user_sid on chain.recipient (app_sid, to_user_sid);
create index chain.ix_recipient_to_company_si on chain.recipient (app_sid, to_company_sid);
create index chain.ix_supplier_foll_user_sid on chain.supplier_follower (app_sid, user_sid);
create index chain.ix_task_owner_company on chain.task (app_sid, owner_company_sid, supplier_company_sid);
create index chain.ix_task_last_task_sta on chain.task (last_task_status_id);
create index chain.ix_task_action_l_task_action_i on chain.task_action_lookup (task_action_id);
create index chain.ix_task_action_l_from_task_sta on chain.task_action_lookup (from_task_status_id);
create index chain.ix_task_action_l_to_task_statu on chain.task_action_lookup (to_task_status_id);
create index chain.ix_task_action_t_on_task_actio on chain.task_action_trigger (on_task_action_id);
create index chain.ix_task_action_t_trigger_task_ on chain.task_action_trigger (trigger_task_action_id);
create index chain.ix_task_action_t_task_type_id_ on chain.task_action_trigger (task_type_id, app_sid);
create index chain.ix_task_action_t_task_action_i on chain.task_action_trigger_transition (task_action_id);
create index chain.ix_task_action_t_from_task_sta on chain.task_action_trigger_transition (from_task_status_id);
create index chain.ix_task_action_t_to_task_statu on chain.task_action_trigger_transition (to_task_status_id);
create index chain.ix_task_entry_task_entry_ty on chain.task_entry (task_entry_type_id);
create index chain.ix_task_entry_fi_file_upload_s on chain.task_entry_file (app_sid, file_upload_sid);
create index chain.ix_task_invitati_invitation_id on chain.task_invitation_qnr_type (app_sid, invitation_id, questionnaire_type_id);
create index chain.ix_task_invitati_task_id_app_s on chain.task_invitation_qnr_type (task_id, app_sid);
create index chain.ix_task_type_card_id on chain.task_type (card_id);
create index chain.ix_task_type_task_scheme_i on chain.task_type (task_scheme_id, app_sid);
create index chain.ix_task_type_default_task_ on chain.task_type (default_task_status_id);
create index chain.ix_uninvited_sup_country_code on chain.uninvited_supplier (country_code);
create index chain.ix_uninvited_sup_created_as_co on chain.uninvited_supplier (app_sid, created_as_company_sid);
create index chain.ix_user_message__message_id on chain.user_message_log (app_sid, message_id);
create index chain.ix_component_tag_component_id on chain.component_tag (app_sid, component_id);
create index chain.ix_company_tag_g_tag_group_id on chain.company_tag_group (app_sid, tag_group_id);

create index chain.ix_busness_unit_parent on chain.business_unit(app_sid,parent_business_unit_id);
create index chain.ix_company_company_type on chain.company(app_sid,company_type_id);
create index chain.ix_company_parent_company on chain.company(app_sid,parent_sid);
create index chain.ix_ctc_ctr_relationship on chain.company_type_capability(app_sid,secondary_company_type_id,primary_company_type_id);
create index chain.ix_ctr_company_type_2 on chain.company_type_relationship(app_sid,secondary_company_type_id);
create index chain.ix_fu_cu_last_modified_by_sid on chain.file_upload(app_sid,last_modified_by_sid);
create index chain.ix_invitation_company_obo on chain.invitation(app_sid,on_behalf_of_company_sid);
create index chain.ix_translation_set_iut on chain.invitation_user_tpl(app_sid,lang);
--create index chain.ix_ref_id_label_comp_typ on chain.reference_id_label(app_sid,company_type_id);
create index chain.ix_sector_parent_id on chain.sector(app_sid,parent_sector_id);
create index chain.ix_primary_ct_role_sid on chain.company_type_capability(app_sid, primary_company_type_id, primary_company_type_role_sid);
create index chain.ix_activity_assigned_to_u on chain.activity (app_sid, assigned_to_user_sid);
create index chain.ix_activity_activity_type on chain.activity (app_sid, activity_type_id);
create index chain.ix_activity_activity_id_a on chain.activity (app_sid, activity_id, assigned_to_user_sid, assigned_to_role_sid);
create index chain.ix_activity_project_id on chain.activity (app_sid, project_id);
create index chain.ix_activity_target_compan on chain.activity (app_sid, target_company_sid);
create index chain.ix_activity_created_by_si on chain.activity (app_sid, created_by_sid);
create index chain.ix_activity_activity_ty_ou on chain.activity (app_sid, activity_type_id, outcome_type_id);
create index chain.ix_activity_created_by_co on chain.activity (app_sid, created_by_company_sid);
create index chain.ix_activity_target_user_s on chain.activity (app_sid, target_user_sid);
create index chain.ix_activity_created_by_ac on chain.activity (app_sid, created_by_activity_id);
create index chain.ix_activity_invo_role_sid on chain.activity_involvement (app_sid, role_sid);
create index chain.ix_activity_invo_user_sid on chain.activity_involvement (app_sid, user_sid);
create index chain.ix_activity_log_reply_to_acti on chain.activity_log (app_sid, reply_to_activity_log_id);
create index chain.ix_activity_log_logged_by_use on chain.activity_log (app_sid, logged_by_user_sid);
create index chain.ix_activity_log_activity_id on chain.activity_log (app_sid, activity_id);
create index chain.ix_activity_log__activity_log_ on chain.activity_log_file (app_sid, activity_log_id);
create index chain.ix_activity_outc_outcome_type_ on chain.activity_outcome_type (app_sid, outcome_type_id);
create index chain.ix_activity_outc_generate_acti on chain.activity_outcome_type_action (app_sid, generate_activity_type_id);
create index chain.ix_activity_tag_activity_id_a on chain.activity_tag (app_sid, activity_id, activity_type_id);
create index chain.ix_activity_tag_activity_type on chain.activity_tag (app_sid, activity_type_id, tag_group_id);
create index chain.ix_activity_tag_tag_group_id_ on chain.activity_tag (app_sid, tag_group_id, tag_id);
create index chain.ix_activity_type_generate_acti on chain.activity_type_action (app_sid, generate_activity_type_id);
create index chain.ix_activity_type_customer_aler on chain.activity_type_alert (app_sid, customer_alert_type_id);
create index chain.ix_activity_type_activity_type on chain.activity_type_alert_role (app_sid, activity_type_id, customer_alert_type_id);
create index chain.ix_activity_type_role_sid on chain.activity_type_alert_role (app_sid, role_sid);
create index chain.ix_activity_type_user_sid on chain.activity_type_default_user (app_sid, user_sid);
create index chain.ix_activity_type_tag_group_id on chain.activity_type_tag_group (app_sid, tag_group_id);
create index chain.ix_alert_entry_alert_ent_tpl on chain.alert_entry (alert_entry_type_id, template_name);
create index chain.ix_alert_entry_owner_schedul on chain.alert_entry (app_sid, owner_scheduled_alert_id, user_sid, alert_entry_type_id);
create index chain.ix_alert_entry_company_sid on chain.alert_entry (app_sid, company_sid);
create index chain.ix_alert_entry_message_id on chain.alert_entry (app_sid, message_id);
create index chain.ix_audit_request_requested_by_ on chain.audit_request (app_sid, requested_by_company_sid);
create index chain.ix_audit_request_audit_sid on chain.audit_request (app_sid, audit_sid);
create index chain.ix_audit_request_auditor_compa on chain.audit_request (app_sid, auditor_company_sid);
create index chain.ix_audit_request_req_by_user on chain.audit_request (app_sid, requested_by_user_sid);
create index chain.ix_audit_request_auditee_compa on chain.audit_request (app_sid, auditee_company_sid);
create index chain.ix_audit_request_user_sid on chain.audit_request_alert (app_sid, user_sid);
create index chain.ix_card_init_par_param_type_id on chain.card_init_param (param_type_id);
create index chain.ix_card_init_par_card_id on chain.card_init_param (card_id);
create index chain.ix_card_init_par_card_group_id on chain.card_init_param (card_group_id);
create index chain.ix_chain_user_em_user_sid on chain.chain_user_email_address_log (app_sid, user_sid);
create index chain.ix_chain_user_em_modified_by_s on chain.chain_user_email_address_log (app_sid, modified_by_sid);
create index chain.ix_company_func__questionnaire on chain.company_func_qnr_action (questionnaire_action_id);
create index chain.ix_company_group_company_group on chain.company_group (company_group_type_id);
create index chain.ix_company_heade_plugin_id on chain.company_header (plugin_id);
create index chain.ix_company_heade_page_company_ on chain.company_header (app_sid, page_company_type_id);
create index chain.ix_company_heade_user_company_ on chain.company_header (app_sid, user_company_type_id);
create index chain.ix_company_heade_plugin_type_i on chain.company_header (plugin_type_id);
create index chain.ix_company_produ_product_type_ on chain.company_product_type (app_sid, product_type_id);
create index chain.ix_company_refer_company_sid on chain.company_reference (app_sid, company_sid);
create index chain.ix_company_tab_plugin_id on chain.company_tab (plugin_id);
create index chain.ix_company_tab_user_company_ on chain.company_tab (app_sid, user_company_type_id);
create index chain.ix_company_tab_plugin_type_i on chain.company_tab (plugin_type_id);
create index chain.ix_company_tab_page_company_ on chain.company_tab (app_sid, page_company_type_id);
create index chain.ix_company_tab_bus_rel_type on chain.company_tab (app_sid, business_relationship_type_id);
create index chain.ix_company_type_user_role_sid on chain.company_type (app_sid, user_role_sid);
create index chain.ix_company_type_user_group_si on chain.company_type (user_group_sid);
create index chain.ix_company_type_region_root_s on chain.company_type (app_sid, region_root_sid);
create index chain.ix_company_type_default_regio on chain.company_type (app_sid, default_region_type);
create index chain.ix_company_type_pcomp_scomp on chain.company_type_capability (app_sid, primary_company_type_id, secondary_company_type_id);
create index chain.ix_company_type_pcomp_grp on chain.company_type_capability (primary_company_group_type_id);
create index chain.ix_comp_typ_pcomp_scomp_tcomp on chain.company_type_capability (app_sid, primary_company_type_id, secondary_company_type_id, tertiary_company_type_id);
create index chain.ix_company_type__capability_id on chain.company_type_capability (capability_id);
create index chain.ix_company_type__flow_sid on chain.company_type_relationship (app_sid, flow_sid);
create index chain.ix_company_type__role_sid on chain.company_type_role (app_sid, role_sid);
create index chain.ix_customer_aler_alert_entry_t on chain.customer_alert_entry_template (alert_entry_type_id);
create index chain.ix_customer_aler_app_sid on chain.customer_alert_entry_type (app_sid);
create index chain.ix_flow_filter_saved_filter_ on chain.flow_filter (app_sid, saved_filter_sid);
create index chain.ix_flow_question_questionnaire on chain.flow_questionnaire_type (app_sid, questionnaire_type_id);
create index chain.ix_invitation_qn_component_id on chain.invitation_qnr_type_component (app_sid, component_id);
create index chain.ix_message_re_invitation on chain.message (app_sid, re_invitation_id);
create index chain.ix_message_re_audit_requ on chain.message (app_sid, re_audit_request_id);
create index chain.ix_message_re_secondary_ on chain.message (app_sid, re_secondary_company_sid);
create index chain.ix_message_defin_completion_ty on chain.message_definition (completion_type_id);
create index chain.ix_product_type__tag_id on chain.product_type_tag (app_sid, tag_id);
create index chain.ix_qnnaire_share_user_sid on chain.qnnaire_share_alert_log (app_sid, user_sid);
create index chain.ix_qnnaire_share_std_alert_typ on chain.qnnaire_share_alert_log (std_alert_type_id);
create index chain.ix_qnr_action_se_company_funct on chain.qnr_action_security_mask (company_function_id, questionnaire_action_id);
create index chain.ix_qnr_action_se_action_securi on chain.qnr_action_security_mask (action_security_type_id);
create index chain.ix_qnr_security__action_securi on chain.qnr_security_scheme_config (action_security_type_id);
create index chain.ix_qnr_security__company_funct on chain.qnr_security_scheme_config (company_function_id, questionnaire_action_id);
create index chain.ix_questionnaire_company_sid on chain.questionnaire (app_sid, company_sid);
create index chain.ix_questionnaire_component_id on chain.questionnaire (app_sid, component_id);
create index chain.ix_questionnaire_invitation_id on chain.questionnaire_invitation (app_sid, invitation_id);
create index chain.ix_questionnaire_security_sche on chain.questionnaire_type (security_scheme_id);
create index chain.ix_question_user_comp_sid on chain.questionnaire_user (app_sid, company_sid);
create index chain.ix_questionnaire_user_sid on chain.questionnaire_user (app_sid, user_sid);
create index chain.ix_questionnaire_company_funct on chain.questionnaire_user (company_function_id);
create index chain.ix_questionnaire_ua_question on chain.questionnaire_user_action (app_sid, questionnaire_id, user_sid, company_function_id, company_sid);
create index chain.ix_questionnaire_ua_comp on chain.questionnaire_user_action (company_function_id, questionnaire_action_id);
create index chain.ix_reference_reference_loc on chain.reference (reference_location_id);
create index chain.ix_reference_reference_uni on chain.reference (reference_uniqueness_id);
create index chain.ix_ref_cap_ref on chain.reference_capability (app_sid, reference_id);
create index chain.ix_ref_cap_pri_comp_type on chain.reference_capability (app_sid, primary_company_type_id);
create index chain.ix_ref_cap_sec_comp_type on chain.reference_capability (app_sid, secondary_company_type_id);
create index chain.ix_ref_cap_pri_comp_grp on chain.reference_capability (primary_company_group_type_id);
create index chain.ix_ref_cap_pri_comp_rol on chain.reference_capability (app_sid, primary_company_type_role_sid);
create index chain.ix_saved_filter_compound_filt on chain.saved_filter (app_sid, compound_filter_id, card_group_id);
create index chain.ix_saved_filter_cms_id_col on chain.saved_filter (app_sid, cms_id_column_sid);
create index chain.ix_saved_filter_cms_region_col on chain.saved_filter (app_sid, cms_region_column_sid);
create index chain.ix_saved_filter_cms_date_col on chain.saved_filter (app_sid, cms_date_column_sid);
create index chain.ix_filter_field_cms_col_sid on chain.filter_field (app_sid, column_sid);
create index chain.ix_svd_fltr_alrt_ctmr_alrt_typ on chain.saved_filter_alert (app_sid, customer_alert_type_id);
create index chain.ix_sv_fltr_alert_subs_csr_usr on chain.saved_filter_alert_subscriptn (app_sid, user_sid);
create index chain.ix_sv_fltr_alert_subs_region on chain.saved_filter_alert_subscriptn (app_sid, region_sid);
create index chain.ix_svd_fltr_sent_alert_csr_usr on chain.saved_filter_sent_alert (app_sid, user_sid);
create index chain.ix_svd_fltr_alrt_param_crd_grp on chain.saved_filter_alert_param (card_group_id);
create index chain.ix_scheduled_ale_alert_entry_t on chain.scheduled_alert (alert_entry_type_id);
create index chain.ix_supplier_audi_supplier_comp on chain.supplier_audit (app_sid, supplier_company_sid);
create index chain.ix_supplier_audi_created_by_co on chain.supplier_audit (app_sid, created_by_company_sid);
create index chain.ix_supplier_audi_auditor_compa on chain.supplier_audit (app_sid, auditor_company_sid);
create index chain.ix_supplier_rela_flow_item_id on chain.supplier_relationship (app_sid, flow_item_id);
create index chain.ix_tertiary_rela_primary_compa on chain.tertiary_relationships (app_sid, primary_company_type_id, tertiary_company_type_id);
create index chain.ix_user_alert_en_user_sid on chain.user_alert_entry_type (app_sid, user_sid);
create index chain.ix_validated_pur_mapped_purcha on chain.validated_purchased_component (app_sid, mapped_purchased_component_id);
create index chain.ix_worksheet_fil_file_upload_s on chain.worksheet_file_upload (app_sid, file_upload_sid);
create index chain.ix_component_parent_comp on chain.component (app_sid, parent_component_id);
create index chain.ix_component_amount_unit_i on chain.component (app_sid, amount_unit_id);
create index chain.ix_component_parent_compon on chain.component (app_sid, parent_component_type_id, component_type_id);
create index chain.ix_invitation_ba_lang on chain.invitation_batch (app_sid, lang);
create index chain.ix_product_revis_revision_crea on chain.product_revision (app_sid, revision_created_by_sid);
create index chain.ix_product_revis_product_id_pr on chain.product_revision (app_sid, product_id, previous_end_dtm, previous_rev_number);
create index chain.ix_prch_cmpnt_cpmnt_comp_compt on chain.purchased_component (app_sid, component_id, company_sid, component_type_id);
create index chain.ix_purchased_com_pre_purc on chain.purchased_component (app_sid, previous_purch_component_id);
create index chain.ix_fltr_field_period_set on chain.filter_field (app_sid, period_set_id, period_interval_id);
create index chain.ix_fltr_value_period_interval on chain.filter_value (app_sid, period_set_id, period_interval_id, start_period_id);
create index chain.ix_business_rela_business_rela on chain.business_relationship (app_sid, business_relationship_type_id);
create index chain.ix_business_rela_company_sid on chain.business_relationship_company (app_sid, company_sid);
create index chain.ix_business_rela_business_rel2 on chain.business_relationship_company (app_sid, business_relationship_tier_id);
create index chain.ix_business_rela_tab_sid on chain.business_relationship_type (app_sid, tab_sid);
create index chain.ix_business_rela_tab_sid_colum on chain.business_relationship_type (app_sid, tab_sid, column_sid);
create index chain.ix_business_rel__company_type_ on chain.business_rel_tier_company_type (app_sid, company_type_id);
create index chain.ix_bus_rel_period_bus_rel on chain.business_relationship_period (app_sid, business_relationship_id);
create index chain.ix_component_amount_unit_2 on chain.component (amount_unit_id, app_sid);
create index chain.ix_filter_page_c_group_sid on chain.filter_page_column (group_sid);
create index chain.ix_filter_page_c_card_group_id on chain.filter_page_column (card_group_id);
create index chain.ix_filter_value_saved_filter_ on chain.filter_value (app_sid, saved_filter_sid_value);
create index chain.ix_product_revis_validation_st on chain.product_revision (validation_status_id);
create index chain.ix_saved_filter_card_group_id on chain.saved_filter (card_group_id, region_column_id);
create index chain.ix_saved_filter_group_by_comp on chain.saved_filter (app_sid, group_by_compound_filter_id, card_group_id);
create index chain.ix_saved_filter_card_group_i2 on chain.saved_filter (card_group_id, date_column_id);
create index chain.ix_saved_filter_company_sid on chain.saved_filter (app_sid, company_sid);
create index chain.ix_cap_flow_cap_capability on chain.capability_flow_capability (capability_id);
create index chain.ix_cap_flow_cap_flow_cap on chain.capability_flow_capability (app_sid, flow_capability_id);
create index chain.ix_customer_aggr_initiative_me on chain.customer_aggregate_type (app_sid, initiative_metric_id);
create index chain.ix_customer_aggr_ind_sid on chain.customer_aggregate_type (app_sid, ind_sid);
create index chain.ix_customer_aggr_meter_aggrega on chain.customer_aggregate_type (app_sid, meter_aggregate_type_id);
create index chain.ix_customer_aggr_cms_aggregate on chain.customer_aggregate_type (app_sid, cms_aggregate_type_id);
create index chain.ix_customer_aggr_filter_page_i on chain.customer_aggregate_type (app_sid, filter_page_ind_interval_id);
create index chain.ix_customer_aggr_card_group_id on chain.customer_aggregate_type (card_group_id);
create index chain.ix_customer_aggr_scr_typ_agg on chain.customer_aggregate_type (app_sid, score_type_agg_type_id);
create index chain.ix_customer_aggr_cust_filt_ite on chain.customer_aggregate_type (app_sid, cust_filt_item_agg_type_id);
create index chain.ix_cust_filt_col_card_group_id on chain.customer_filter_column (card_group_id);
create index chain.ix_cust_filt_itm_card_group_id on chain.customer_filter_item (card_group_id);
create index chain.ix_filter_page_i_ind_sid on chain.filter_page_ind (app_sid, ind_sid);
create index chain.ix_filter_page_i_card_group_id on chain.filter_page_ind (card_group_id);
create index chain.ix_filter_page_i_period_set_id on chain.filter_page_ind (app_sid, period_set_id, period_interval_id);
create index chain.ix_saved_filter_customer_aggr on chain.saved_filter_aggregation_type (app_sid, customer_aggregate_type_id);
create index chain.ix_saved_filter_region_sid on chain.saved_filter_region (app_sid, region_sid);
create index chain.ix_company_tab_p_company_sid on chain.company_tab (app_sid, page_company_col_sid);
create index chain.ix_company_tab_u_company_sid on chain.company_tab (app_sid, user_company_col_sid);
create index chain.ix_business_unit_user_sid on chain.business_unit_member (app_sid, user_sid);
create index chain.ix_business_unit_supplier_comp on chain.business_unit_supplier (app_sid, supplier_company_sid);
create index chain.ix_company_heade_page_comp_col on chain.company_header (app_sid, page_company_col_sid);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
create index chain.ix_company_heade_user_comp_col on chain.company_header (app_sid, user_company_col_sid);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
create index chain.ix_company_tab_flow_capabili on chain.company_tab (app_sid, flow_capability_id);
create index chain.ix_company_type__tag_group_id on chain.company_type_tag_group (app_sid, tag_group_id);
create index chain.ix_country_risk__risk_level_id on chain.country_risk_level (app_sid, risk_level_id);
create index chain.ix_filter_page_c_company_tab_i on chain.filter_page_column (app_sid, session_prefix);
create index chain.ix_prod_head_prod_col_sid on chain.product_header (app_sid, product_col_sid);
create index chain.ix_prod_head_user_comp_col_sid on chain.product_header (app_sid, user_company_col_sid);
create index chain.ix_prod_head_prod_comp_type_id on chain.product_header (app_sid, product_company_type_id);
create index chain.ix_prod_head_plugin_id on chain.product_header (plugin_id);
create index chain.ix_prod_head_plugin_type_id on chain.product_header (plugin_type_id);
create index chain.ix_prod_head_user_comp_type_id on chain.product_header (app_sid, user_company_type_id);
create index chain.ix_prod_head_prod_type_id on chain.product_header_product_type (app_sid, product_type_id);
create index chain.ix_prod_supp_plugin_id on chain.product_supplier_tab (plugin_id);
create index chain.ix_prod_supp_prod_comp_type_id on chain.product_supplier_tab (app_sid, product_company_type_id);
create index chain.ix_prod_supp_plugin_type_id on chain.product_supplier_tab (plugin_type_id);
create index chain.ix_prod_supp_user_comp_type_id on chain.product_supplier_tab (app_sid, user_company_type_id);
create index chain.ix_prod_tab_plugin_type_id on chain.product_tab (plugin_type_id);
create index chain.ix_prod_tab_user_comp_col_sid on chain.product_tab (app_sid, user_company_col_sid);
create index chain.ix_prod_tab_user_comp_type_id on chain.product_tab (app_sid, user_company_type_id);
create index chain.ix_prod_tab_prod_comp_type_id on chain.product_tab (app_sid, product_company_type_id);
create index chain.ix_prod_tab_prod_col_sid on chain.product_tab (app_sid, product_col_sid);
create index chain.ix_prod_tab_plugin_id on chain.product_tab (plugin_id);
create index chain.ix_prod_tab_prod_prod_type_ on chain.product_tab_product_type (app_sid, product_type_id);
create index chain.ix_prod_supp_tab_prod_type_id on chain.prod_supp_tab_product_type (app_sid, product_type_id);
create index chain.ix_company_reque_matched_compa on chain.company_request_action (app_sid, matched_company_sid);

create index chain.ix_higg_config_company_type on chain.higg_config (app_sid, company_type_id);
create index chain.ix_higg_config_audit_type on chain.higg_config (app_sid, audit_type_id);
create index chain.ix_higg_config_closure_type on chain.higg_config (app_sid, audit_type_id, closure_type_id);
create index chain.ix_higg_config_audit_coord on chain.higg_config (app_sid, audit_coordinator_sid);
create index chain.ix_higg_config_agg_ind on chain.higg_config (app_sid, aggregate_ind_group_id);
create index chain.ix_higg_mod_t_g_tag_group on chain.higg_module_tag_group (app_sid, tag_group_id);
create index chain.ix_higg_con_mod_higg_config on chain.higg_config_module (app_sid, higg_config_id);
create index chain.ix_higg_con_mod_higg_module on chain.higg_config_module (higg_module_id);
create index chain.ix_higg_mod_sec_higg_module on chain.higg_module_section (higg_module_id);
create index chain.ix_higg_mod_sub_sec_higg_mod on chain.higg_module_sub_section (higg_module_id);
create index chain.ix_higg_mod_sub_sec_higg_sec on chain.higg_module_sub_section (higg_section_id);
create index chain.ix_higg_question_parent on chain.higg_question (parent_question_id);
create index chain.ix_higg_question_module on chain.higg_question (higg_module_id);
create index chain.ix_higg_question_sub_sec on chain.higg_question (higg_sub_section_id);
create index chain.ix_higg_question_sur_qs on chain.higg_question_survey (app_sid, survey_sid);
create index chain.ix_higg_question_sur_qsq on chain.higg_question_survey (app_sid, qs_question_id, survey_version);
create index chain.ix_higg_question_sur_question on chain.higg_question_survey (higg_question_id);
create index chain.ix_higg_qu_opt_question on chain.higg_question_option (higg_module_id, higg_question_id);
create index chain.ix_higg_qu_opt_module on chain.higg_question_option (higg_module_id);
create index chain.ix_higg_qu_opt_sur_qo on chain.higg_question_option_survey (higg_question_id, higg_question_option_id);
create index chain.ix_higg_qu_opt_sur_qsq on chain.higg_question_option_survey (app_sid, survey_sid);
create index chain.ix_higg_qu_opt_sur_qsqo on chain.higg_question_option_survey (app_sid, qs_question_id, qs_question_option_id, survey_version);
create index chain.ix_higg_response_module on chain.higg_response (higg_module_id);
create index chain.ix_higg_response_profile on chain.higg_response (app_sid, higg_profile_id, response_year);
create index chain.ix_higg_section_score_section on chain.higg_section_score (higg_section_id);
create index chain.ix_higg_section_score_res on chain.higg_section_score (app_sid, higg_response_id);
create index chain.ix_higg_sub_sec_score_sub_sec on chain.higg_sub_section_score (higg_sub_section_id);
create index chain.ix_higg_sub_sec_score_sec on chain.higg_sub_section_score (app_sid, higg_response_id, higg_section_id);
create index chain.ix_higg_q_res_response on chain.higg_question_response (app_sid, higg_response_id);
create index chain.ix_higg_q_res_question on chain.higg_question_response (higg_question_id);
create index chain.ix_higg_q_res_option on chain.higg_question_response (higg_question_id, option_id);
create index chain.ix_higg_conf_prof_config on chain.higg_config_profile (app_sid, higg_config_id);
create index chain.ix_higg_conf_prof_profile on chain.higg_config_profile (app_sid, higg_profile_id, response_year);
create index chain.ix_higg_conf_prof_audit on chain.higg_config_profile (app_sid, internal_audit_sid);
create index chain.ix_higg_q_opt_conv_mc on chain.higg_question_opt_conversion (app_sid, measure_conversion_id);
create index chain.ix_higg_q_opt_conv_qo on chain.higg_question_opt_conversion (higg_question_id, higg_question_option_id);

create index chain.ix_dedupe_merge_log_fld on chain.dedupe_merge_log (app_sid, dedupe_field_id);
create index chain.ix_dedupe_merge_log_tg on chain.dedupe_merge_log (app_sid, tag_group_id);
create index chain.ix_dedupe_merge_log_ref on chain.dedupe_merge_log (app_sid, reference_id);
create index chain.ix_dedupe_merge_log_rec_id on chain.dedupe_merge_log (app_sid, dedupe_processed_record_id);
create index chain.ix_dedupe_processed_rec_c_comp on chain.dedupe_processed_record (app_sid, created_company_sid);
create index chain.ix_dedupe_merge_log_col_sid on chain.dedupe_merge_log (app_sid, destination_tab_sid, destination_col_sid);

create index chain.ix_company_type__follower_role on chain.company_type_relationship (app_sid, follower_role_sid);
create index chain.ix_customer_grid_grid_extensio on chain.customer_grid_extension (grid_extension_id);
create index chain.ix_dedupe_mappin_dedupe_field_ on chain.dedupe_mapping (dedupe_field_id);
create index chain.ix_dedupe_mappin_reference_id on chain.dedupe_mapping (app_sid, reference_id);
create index chain.ix_dedupe_mappin_tab_sid_col_s on chain.dedupe_mapping (app_sid, tab_sid, col_sid);
create index chain.ix_dedupe_mappin_tag_group_id on chain.dedupe_mapping (app_sid, tag_group_id);
create index chain.ix_dedupe_match_dedupe_rule_i on chain.dedupe_match (app_sid, dedupe_rule_set_id);
create index chain.ix_dedupe_match_matched_to_co on chain.dedupe_match (app_sid, matched_to_company_sid);
create index chain.ix_dedupe_merge__dedupe_field_ on chain.dedupe_merge_log (dedupe_field_id);
create index chain.ix_dedupe_proces_dedupe_actn on chain.dedupe_processed_record (dedupe_action_type_id);
create index chain.ix_dedupe_proces_matched_by_us on chain.dedupe_processed_record (app_sid, matched_by_user_sid);
create index chain.ix_dedupe_rule_m_dedupe_mappin on chain.dedupe_rule (app_sid, dedupe_mapping_id);
create index chain.ix_filter_export_card_group_id on chain.filter_export_batch (card_group_id);
create index chain.ix_filter_export_compound_filt on chain.filter_export_batch (app_sid, compound_filter_id);
create index chain.ix_grid_extensio_extension_car on chain.grid_extension (extension_card_group_id);
create index chain.ix_task_company_sid on chain.task (app_sid, supplier_company_sid);
create index chain.ix_component_sou_comp_typ_2 on chain.component_source (app_sid, component_type_id);
create index chain.ix_component_typ_child_comp_2 on chain.component_type_containment (app_sid, child_component_type_id);
create index chain.ix_dedupe_mappin_destination_t on chain.dedupe_mapping (app_sid, destination_tab_sid, destination_col_sid);
create index chain.ix_file_upload_company_sid on chain.file_upload (app_sid, company_sid);
create index chain.ix_purchase_amount_unit_i2 on chain.purchase (app_sid, amount_unit_id);
create index chain.ix_task_action_t_task_type_id on chain.task_action_trigger (app_sid, task_type_id);
create index chain.ix_task_type_parent_task_t_2 on chain.task_type (app_sid, parent_task_type_id);
create index chain.ix_task_type_task_scheme_i_2 on chain.task_type (app_sid, task_scheme_id);
create index chain.ix_dedupe_processed_rec_comp on chain.dedupe_processed_record (app_sid, matched_to_company_sid);
CREATE INDEX chain.ix_dedupe_mappin_dedupe_stagin ON chain.dedupe_mapping (app_sid, dedupe_staging_link_id, destination_tab_sid);
CREATE INDEX chain.ix_dedupe_stagin_stag_col ON chain.dedupe_staging_link (app_sid, staging_tab_sid, staging_id_col_sid);
CREATE INDEX chain.ix_dedupe_stagin_parent_stagin ON chain.dedupe_staging_link (app_sid, parent_staging_link_id);
CREATE INDEX chain.ix_dedupe_stagin_stag_tab ON chain.dedupe_staging_link (app_sid, staging_tab_sid);
CREATE INDEX chain.ix_dedupe_stagin_stag_bat_num ON chain.dedupe_staging_link (app_sid, staging_tab_sid, staging_batch_num_col_sid);
CREATE INDEX chain.ix_dedupe_stagin_destination_t ON chain.dedupe_staging_link (app_sid, destination_tab_sid);
create index chain.ix_dedupe_processed_rec_usr on chain.dedupe_processed_record (app_sid, imported_user_sid);
create index chain.ix_dedupe_map_role on chain.dedupe_mapping (app_sid, role_sid);
create index chain.ix_dedupe_log_role on chain.dedupe_merge_log (app_sid, role_sid);
create index chain.ix_dedupe_pp_fld_country_field on chain.dedupe_pp_field_cntry (dedupe_field_id);
create index chain.ix_dedupe_pp_fld_country_count on chain.dedupe_pp_field_cntry (country_code);
create index chain.ix_dedupe_pp_alt_comp_name on chain.dedupe_pp_alt_comp_name (app_sid, company_sid);

create index chain.ix_dedupe_processed_rec_batch on chain.dedupe_processed_record (app_sid, batch_job_id);

create index chain.ix_cmp_typ_scr_clc_cmp_typ on chain.company_type_score_calc (app_sid, company_type_id);
create index chain.ix_cmp_typ_scr_clc_scr_typ on chain.company_type_score_calc (app_sid, score_type_id);
create index chain.ix_cmp_typ_scr_clc_sup_st on chain.company_type_score_calc (app_sid, supplier_score_type_id);

create index chain.ix_cmp_typ_scr_clc_ct_parent on chain.comp_type_score_calc_comp_type (app_sid, company_type_id, score_type_id);
create index chain.ix_cmp_typ_scr_clc_ct_ct on chain.comp_type_score_calc_comp_type (app_sid, company_type_id);
create index chain.ix_cmp_typ_scr_clc_ct_st on chain.comp_type_score_calc_comp_type (app_sid, score_type_id);
create index chain.ix_cmp_typ_scr_clc_ct_sct on chain.comp_type_score_calc_comp_type (app_sid, supplier_company_type_id);
create index chain.ix_cert_type_audit_type on chain.cert_type_audit_type (app_sid, internal_audit_type_id);
create index chain.ix_alt_company_name on chain.alt_company_name (app_sid, company_sid);

create index chain.ix_company_produ_certification on chain.company_product_certification (app_sid, certification_id);
create index chain.ix_company_produ_cert_type on chain.company_product_required_cert (app_sid, certification_type_id);
create index chain.ix_company_tab_default_saved on chain.company_tab (app_sid, default_saved_filter_sid);
create index chain.ix_company_tab_r_company_type_ on chain.company_tab_related_co_type (app_sid, company_type_id);
create index chain.ix_dedupe_stagin_staging_tab_s on chain.dedupe_staging_link (app_sid, staging_tab_sid, staging_source_lookup_col_sid);
create index chain.ix_higg_config_m_score_type_id on chain.higg_config_module (app_sid, score_type_id);
create index chain.ix_product_metri_ind_sid on chain.product_metric_val (app_sid, ind_sid);
create index chain.ix_product_metri_entered_by_si on chain.product_metric_val (app_sid, entered_by_sid);
create index chain.ix_product_suppl_purchaser_com on chain.product_supplier (app_sid, purchaser_company_sid, supplier_company_sid);
create index chain.ix_product_suppl_product_id on chain.product_supplier (app_sid, product_id);
create index chain.ix_product_suppl_certification on chain.product_supplier_certification (app_sid, certification_id);
create index chain.ix_product_suppl_entered_by_si on chain.product_supplier_metric_val (app_sid, entered_by_sid);
create index chain.ix_product_suppl_ind_sid on chain.product_supplier_metric_val (app_sid, ind_sid);
create index chain.ix_prd_mtrc_prd_mtrc_icon on chain.product_metric (product_metric_icon_id);
create index chain.ix_prd_mtrc_prd_type_prd_type on chain.product_metric_product_type (app_sid, product_type_id);
create index chain.ix_prd_mtrc_prd_type_prd_mtrc on chain.product_metric_product_type (app_sid, ind_sid);
create index chain.ix_reference_reference_val on chain.reference (reference_validation_id);
create index chain.ix_company_prod_prod_type on chain.company_product (app_sid, product_type_id);
create index chain.ix_pending_compa_tag_id on chain.pending_company_tag (app_sid, tag_id);
create index chain.ix_pend_company__dedupe_rule_s on chain.pend_company_suggested_match (app_sid, dedupe_rule_set_id);
create index chain.ix_pend_company__matched_compa on chain.pend_company_suggested_match (app_sid, matched_company_sid);
CREATE INDEX chain.ix_requested_by_company_sid ON chain.company (app_sid, requested_by_company_sid);
CREATE INDEX chain.ix_rel_score_purch_suppl ON chain.supplier_relationship_score (app_sid, purchaser_company_sid, supplier_company_sid);
CREATE INDEX chain.ix_rel_score_type ON chain.supplier_relationship_score (app_sid, score_type_id);
CREATE INDEX chain.ix_rel_score_csr_user ON chain.supplier_relationship_score (app_sid, changed_by_user_sid);
CREATE INDEX chain.ix_supplier_relationship_src ON chain.supplier_relationship_source(app_sid, purchaser_company_sid, supplier_company_sid);


CREATE INDEX chain.ix_rel_score_threshold ON chain.supplier_relationship_score (app_sid, score_threshold_id);

CREATE INDEX chain.ix_sup_inv_t_ct_rel ON chain.supplier_involvement_type (app_sid, user_company_type_id, page_company_type_id);
CREATE INDEX chain.ix_sup_inv_t_co_type_role ON chain.supplier_involvement_type (app_sid, user_company_type_id, restrict_to_role_sid);
CREATE INDEX chain.ix_sup_inv_t_role ON chain.supplier_involvement_type (app_sid, restrict_to_role_sid);
CREATE INDEX chain.ix_company_produ_tag_group_id_ on chain.company_product_tag (app_sid, tag_group_id, tag_id);
CREATE INDEX chain.ix_product_suppl_tag_group_id_ on chain.product_supplier_tag (app_sid, tag_group_id, tag_id);

create index chain.ix_product_metric_calc_s_ind_1 on chain.product_metric_calc (app_sid, source_ind_sid_1);
create index chain.ix_product_metric_calc_s_ind_2 on chain.product_metric_calc (app_sid, source_ind_sid_2);

create index chain.ix_bsci_import_batch_job_id on chain.bsci_import (app_sid, batch_job_id);
CREATE INDEX CHAIN.IX_BSCI_SUPPLIER_COMPANY_SID ON CHAIN.BSCI_SUPPLIER (APP_SID, COMPANY_SID);
CREATE INDEX CHAIN.IX_BSCI_SUPPLIER_DET_RSP_ID ON CHAIN.BSCI_SUPPLIER_DET (RSP_ID);
CREATE INDEX CHAIN.IX_BSCI_SUPPLIER_DET_ID ON CHAIN.BSCI_SUPPLIER_DET (BSCI_SUPPLIER_ID);

CREATE INDEX CHAIN.IX_BSCI_AUDIT_AUDIT_SID ON CHAIN.BSCI_AUDIT (APP_SID, INTERNAL_AUDIT_SID);
CREATE INDEX CHAIN.IX_BSCI_2009_AUDIT_AUDIT_ID ON CHAIN.BSCI_2009_AUDIT (APP_SID, BSCI_AUDIT_ID);
CREATE INDEX CHAIN.IX_BSCI_2009_FIND_AUDIT_ID ON CHAIN.BSCI_2009_AUDIT_FINDING (APP_SID, BSCI_2009_AUDIT_ID);
CREATE INDEX CHAIN.IX_BSCI_2009_ASSOC_AUDIT_ID ON CHAIN.BSCI_2009_AUDIT_ASSOCIATE (APP_SID, BSCI_2009_AUDIT_ID);
CREATE INDEX CHAIN.IX_BSCI_2014_AUDIT_AUDIT_ID ON CHAIN.BSCI_2014_AUDIT (APP_SID, BSCI_AUDIT_ID);
CREATE INDEX CHAIN.IX_BSCI_2014_FIND_AUDIT_ID ON CHAIN.BSCI_2014_AUDIT_FINDING (APP_SID, BSCI_2014_AUDIT_ID);
CREATE INDEX CHAIN.IX_BSCI_2014_ASSOC_AUDIT_ID ON CHAIN.BSCI_2014_AUDIT_ASSOCIATE (APP_SID, BSCI_2014_AUDIT_ID);
CREATE INDEX CHAIN.IX_BSCI_EXT_AUDIT_AUDIT_ID ON CHAIN.BSCI_EXT_AUDIT (APP_SID, BSCI_AUDIT_ID);

CREATE INDEX CHAIN.IX_COMP_TAB_TYPE_COMP_TYPE_RL ON CHAIN.COMPANY_TAB_COMPANY_TYPE_ROLE (APP_SID, COMPANY_TYPE_ROLE_ID);
CREATE INDEX CHAIN.IX_COMP_TAB_TYPE_COMP_TAB ON CHAIN.COMPANY_TAB_COMPANY_TYPE_ROLE (APP_SID, COMPANY_TAB_ID);
CREATE INDEX CHAIN.IX_COMP_TAB_TYPE_COMP_GRP_TYPE ON CHAIN.COMPANY_TAB_COMPANY_TYPE_ROLE (COMPANY_GROUP_TYPE_ID);

CREATE INDEX CHAIN.IX_GEOTAG_BATCH_BATCH_JOB_ID ON CHAIN.GEOTAG_BATCH (APP_SID, BATCH_JOB_ID);
CREATE INDEX CHAIN.IX_GEOTAG_BATCH_QUEUE_COMP ON CHAIN.GEOTAG_BATCH_COMPANY_QUEUE (APP_SID, COMPANY_SID);
CREATE INDEX CHAIN.IX_GEOTAG_BATCH_QUEUE_BATCH ON CHAIN.GEOTAG_BATCH_COMPANY_QUEUE (APP_SID, GEOTAG_BATCH_ID);
create index chain.ix_alert_partial_alert_type_id on chain.alert_partial_template (alert_type_id);
create index chain.ix_alert_partial_alert_type_id_p on chain.alert_partial_template_param (alert_type_id, field_name);
create index chain.ix_company_requested_by_ on chain.company (app_sid, requested_by_user_sid);
create index chain.ix_dedupe_proces_parent_proces on chain.dedupe_processed_record (app_sid, parent_processed_record_id);
create index chain.ix_dedupe_rule_dedupe_rule_t on chain.dedupe_rule (dedupe_rule_type_id);
create index chain.ix_dedupe_rule_s_dedupe_match_ on chain.dedupe_rule_set (dedupe_match_type_id);
create index chain.ix_higg_question_qs_question_o on chain.higg_question_option_survey (app_sid, qs_question_option_id, qs_question_id, qs_question_version, qs_question_draft);
create index chain.ix_higg_question_qs_question_i on chain.higg_question_survey (app_sid, qs_question_id, qs_question_version, survey_sid, survey_version);
create index chain.ix_import_source_dedupe_no_mat on chain.import_source (dedupe_no_match_action_id);
create index chain.ix_purchase_component_id on chain.purchase (app_sid, component_id);
create index chain.ix_url_overrides_app_sid on chain.url_overrides (app_sid);
create index chain.ix_capability_capability_gr on chain.capability (capability_group_id);

