BEGIN
	FOR r IN (SELECT TYPE_NAME FROM ALL_TYPES WHERE OWNER='CHAIN' AND TYPE_NAME IN (
				'T_VARCHAR_TABLE',
				'T_NUMERIC_TABLE',
				'T_CARD_ACTION_LIST')) LOOP
		EXECUTE IMMEDIATE 'DROP TYPE CHAIN.'||r.TYPE_NAME;
	END LOOP;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_STRING_LIST IS TABLE OF VARCHAR2(100);
/

CREATE OR REPLACE TYPE CHAIN.T_NUMBER_LIST IS TABLE OF NUMBER(10);
/

CREATE OR REPLACE TYPE CHAIN.T_DATES IS TABLE OF DATE;
/

CREATE OR REPLACE TYPE CHAIN.T_CARD_ACTION_ROW AS
  OBJECT (
	ON_ACTION			VARCHAR2(100),
	GO_TO_JS_CLASS		VARCHAR2(1000)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_CARD_ACTION_LIST AS
  TABLE OF CHAIN.T_CARD_ACTION_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_TASK_ACTION_ROW AS
  OBJECT (
	ON_TASK_ACTION			NUMBER(10),
	TRIGGER_TASK_ACTION		NUMBER(10),
	TRIGGER_TASK_NAME		VARCHAR2(30)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_TASK_ACTION_LIST AS
  TABLE OF CHAIN.T_TASK_ACTION_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_VARCHAR_ROW AS
  OBJECT (
	ITEM	VARCHAR2(255),
	POS		NUMBER(10)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_VARCHAR_TABLE AS
  TABLE OF CHAIN.T_VARCHAR_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_NUMERIC_ROW AS
  OBJECT (
	ITEM		NUMBER(10),
	POS			NUMBER(10)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_NUMERIC_TABLE AS
  TABLE OF CHAIN.T_NUMERIC_ROW;
/


CREATE OR REPLACE TYPE CHAIN.T_NEWSFLASH_ROW AS
  OBJECT (
	NEWSFLASH_ID 		NUMBER(10),
	RELEASED_DTM 		DATE,
	CONTENT 			CLOB,
	FOR_USERS 			NUMBER(1),
	FOR_SUPPLIERS 		NUMBER(1)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_NEWSFLASH_TABLE AS
 TABLE OF T_NEWSFLASH_ROW;
/


CREATE OR REPLACE TYPE CHAIN.T_BUSINESS_UNIT_ROW AS
  OBJECT (
	COMPANY_ID          NUMBER(10),
	DESCRIPTION 		VARCHAR2(255),
	IS_PRIMARY 			NUMBER(1)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_BUSINESS_UNIT_TABLE AS
 TABLE OF T_BUSINESS_UNIT_ROW;
/


CREATE OR REPLACE TYPE CHAIN.T_PRIMARY_CONTACT_ROW AS
  OBJECT (
	COMPANY_ID           NUMBER(10),
	USER_ID 			 NUMBER(10)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_PRIMARY_CONTACT_TABLE AS
 TABLE OF T_PRIMARY_CONTACT_ROW;
/


CREATE OR REPLACE TYPE CHAIN.T_COMPANY_RELATIONSHIP_SIDS AS
	OBJECT (
		PRIMARY_COMPANY_SID			NUMBER(10),
		SECONDARY_COMPANY_SID		NUMBER(10),
		ACTIVE						NUMBER(1),
		MAP MEMBER FUNCTION MAP
			RETURN VARCHAR2
	);
/

CREATE OR REPLACE TYPE CHAIN.T_PERMISSIBLE_TYPES_ROW AS
	OBJECT (
		CAPABILITY_ID				NUMBER(10),
		PRIMARY_COMPANY_TYPE_ID		NUMBER(10),
		SECONDARY_COMPANY_TYPE_ID	NUMBER(10),
		TERTIARY_COMPANY_TYPE_ID	NUMBER(10)
	);
/

CREATE OR REPLACE TYPE CHAIN.T_PERMISSIBLE_TYPES_TABLE AS
	TABLE OF CHAIN.T_PERMISSIBLE_TYPES_ROW;
/

CREATE OR REPLACE TYPE BODY CHAIN.T_COMPANY_RELATIONSHIP_SIDS AS
	MAP MEMBER FUNCTION MAP
		RETURN VARCHAR2
	IS
	BEGIN
		RETURN RPAD(PRIMARY_COMPANY_SID, 10) || '->' || RPAD(SECONDARY_COMPANY_SID, 10);
	END;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_COMPANY_REL_SIDS_TABLE AS
	TABLE OF CHAIN.T_COMPANY_RELATIONSHIP_SIDS;
/

CREATE OR REPLACE TYPE CHAIN.T_COMPANY_RELATIONSHIP_ROW AS
	OBJECT (
		COMPANY_SID					NUMBER(10),
		NAME						VARCHAR(1000),
		COUNTRY_NAME				VARCHAR(1000),
		ACTIVE_RELATIONSHIP			NUMBER(1),
		EDITABLE_RELATIONSHIP		NUMBER(1),--Based on capabilities
		COMPANY_TYPE_DESCRIPTION	VARCHAR(1000),
		RELATIONSHIP_ROLE			NUMBER(1), --1 SUPPLIER, 2 PURCHASER
		HAS_READ_PERMS_ON_COMPANY	NUMBER(1),
		IS_PRIMARY					NUMBER(1),
		CAN_BE_PRIMARY				NUMBER(1)
	);
/

CREATE OR REPLACE TYPE CHAIN.T_COMPANY_RELATIONSHIP_TABLE AS
	TABLE OF CHAIN.T_COMPANY_RELATIONSHIP_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_QNNAIRER_SHARE_ROW AS
	 OBJECT (
		QUESTIONNAIRE_SHARE_ID         NUMBER(10),
		QUESTIONNAIRE_TYPE_ID		   NUMBER(10),
		DUE_BY_DTM 			 		   DATE,
		QNR_OWNER_COMPANY_SID		   NUMBER(10),
		EDIT_URL					   VARCHAR2(4000),
		REMINDER_OFFSET_DAYS		   NUMBER(10),
		NAME						   VARCHAR2(200),
		ENTRY_DTM					   DATE,
		SHARE_STATUS_NAME			   VARCHAR2(200),
		COMPONENT_ID				   NUMBER(10),
		COMPONENT_DESCRIPTION		   VARCHAR2(4000)
	 );
/

CREATE OR REPLACE TYPE CHAIN.T_QNNAIRER_SHARE_TABLE AS
	TABLE OF CHAIN.T_QNNAIRER_SHARE_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_FILTERED_OBJECT_ROW AS
	 OBJECT (
		OBJECT_ID					NUMBER(10),
		GROUP_BY_INDEX				NUMBER(10),
		GROUP_BY_VALUE				NUMBER(10),
		CONSTRUCTOR FUNCTION T_FILTERED_OBJECT_ROW (
			in_object_id	NUMBER
		)
		RETURN SELF AS RESULT,
		MAP MEMBER FUNCTION MAP
			RETURN VARCHAR2
	 );
/

CREATE OR REPLACE TYPE BODY chain.T_FILTERED_OBJECT_ROW IS
	CONSTRUCTOR FUNCTION T_FILTERED_OBJECT_ROW (
		in_object_id	NUMBER
	)
	RETURN SELF AS RESULT
	IS
	BEGIN
		object_id := in_object_id;
		RETURN;
	END;
	MAP MEMBER FUNCTION MAP
		RETURN VARCHAR2
	IS
	BEGIN
		RETURN OBJECT_ID||'@'||GROUP_BY_INDEX||':'||GROUP_BY_VALUE;
	END;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_FILTERED_OBJECT_TABLE AS
	TABLE OF CHAIN.T_FILTERED_OBJECT_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_AGG_TYPE_ROW AS
	 OBJECT (
		CARD_GROUP_ID					NUMBER(10),
		AGGREGATE_TYPE_ID				NUMBER(10),
		DESCRIPTION 					VARCHAR2(1023),
		FORMAT_MASK						VARCHAR2(255),
		FILTER_PAGE_IND_INTERVAL_ID		NUMBER(10),
		ACCUMULATIVE					NUMBER(1),
		AGGREGATE_GROUP					VARCHAR2(255),
		UNIT_OF_MEASURE					VARCHAR2(255),
		NORMALIZE_BY_AGGREGATE_TYPE_ID	NUMBER(10)
	 );
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_AGG_TYPE_TABLE AS
	TABLE OF CHAIN.T_FILTER_AGG_TYPE_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_AGG_TYPE_THRES_ROW AS
	 OBJECT (
		AGGREGATE_TYPE_ID				NUMBER(10),
		MAX_VALUE						NUMBER(15, 5),
		LABEL 							VARCHAR2(255),
		ICON_URL						VARCHAR2(255),
		ICON_DATA						BLOB,
		TEXT_COLOUR						NUMBER(10),
		BACKGROUND_COLOUR				NUMBER(10),
		BAR_COLOUR						NUMBER(10)
	 );
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_AGG_TYPE_THRES_TABLE AS
	TABLE OF CHAIN.T_FILTER_AGG_TYPE_THRES_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_BUS_REL_COMP_ROW AS
	OBJECT (
		STARTING_COMPANY_SID		NUMBER(10),
		BUSINESS_RELATIONSHIP_ID	NUMBER(10),
		BUSINESS_RELATIONSHIP_TIER_ID	NUMBER(10),
		POS							NUMBER(10),
		COMPANY_SID					NUMBER(10),
		MAP MEMBER FUNCTION MAP
			RETURN VARCHAR2
	);
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_OBJECT_DATA_ROW AS
	 OBJECT (
		DATA_TYPE_ID					NUMBER(10),
		AGG_TYPE_ID						NUMBER(10),
		OBJECT_ID						NUMBER(10),
		VAL_NUMBER						NUMBER(24, 10),
		FILTER_VALUE_ID					NUMBER(10)
	 );
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_OBJECT_DATA_TABLE AS
	TABLE OF CHAIN.T_FILTER_OBJECT_DATA_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_GROUP_BY_PIVOT_ROW AS
	 OBJECT (
		OBJECT_ID NUMBER(10),
		FILTER_VALUE_ID1 NUMBER(10),
		FILTER_VALUE_ID2 NUMBER(10),
		FILTER_VALUE_ID3 NUMBER(10),
		FILTER_VALUE_ID4 NUMBER(10)
	 );
/

CREATE OR REPLACE TYPE CHAIN.T_GROUP_BY_PIVOT_TABLE AS
	TABLE OF CHAIN.T_GROUP_BY_PIVOT_ROW;
/


CREATE OR REPLACE TYPE BODY CHAIN.T_BUS_REL_COMP_ROW AS
	MAP MEMBER FUNCTION MAP
		RETURN VARCHAR2
	IS
	BEGIN
		RETURN STARTING_COMPANY_SID||':'||BUSINESS_RELATIONSHIP_ID||'/'||BUSINESS_RELATIONSHIP_TIER_ID||'.'||POS;
	END;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_BUS_REL_COMP_TABLE AS
	TABLE OF CHAIN.T_BUS_REL_COMP_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_SUPPLIER_RELATIONSHIP_ROW AS
	 OBJECT (
		PURCHASER_COMPANY_SID	NUMBER(10),
		SUPPLIER_COMPANY_SID	NUMBER(10),
		SUPPLIER_REGION_SID		NUMBER(10),
		FLOW_ITEM_ID			NUMBER(10)
	 );
/

CREATE OR REPLACE TYPE CHAIN.T_SUPPLIER_RELATIONSHIP_TABLE AS
	TABLE OF CHAIN.T_SUPPLIER_RELATIONSHIP_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_COMPANY_ROW AS
	OBJECT (
		NAME				VARCHAR2(255),
		PARENT_COMPANY_NAME	VARCHAR2(255),
		COMPANY_TYPE		VARCHAR2(255),
		CREATED_DTM			DATE,
		ACTIVATED_DTM		DATE,
		ACTIVE				NUMBER(1),
		ADDRESS				VARCHAR2(1024),
		ADDRESS_1			VARCHAR2(255),
		ADDRESS_2			VARCHAR2(255),
		ADDRESS_3			VARCHAR2(255),
		ADDRESS_4			VARCHAR2(255),
		STATE				VARCHAR2(255),
		POSTCODE			VARCHAR2(32),
		COUNTRY_CODE		VARCHAR2(255),
		PHONE				VARCHAR2(255),
		FAX					VARCHAR2(255),
		WEBSITE				VARCHAR2(255),
		EMAIL				VARCHAR2(255),
		DELETED				NUMBER(1),
		SECTOR				VARCHAR2(255),
		CITY				VARCHAR2(255),
		DEACTIVATED_DTM		DATE,
		PURCHASER_COMPANY	NUMBER(10),
		CONSTRUCTOR FUNCTION T_DEDUPE_COMPANY_ROW
		RETURN self AS RESULT
	);
/

CREATE OR REPLACE TYPE BODY CHAIN.T_DEDUPE_COMPANY_ROW AS
  CONSTRUCTOR FUNCTION T_DEDUPE_COMPANY_ROW
	RETURN SELF AS RESULT
	AS
	BEGIN
		RETURN;
	END;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_VAL_CHANGE AS
  OBJECT (
	MAPPING_FIELD_ID	NUMBER(10),
	OLD_VAL 			VARCHAR2(4000),
	NEW_VAL 			VARCHAR2(4000)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_VAL_CHANGE_TABLE AS
 TABLE OF T_DEDUPE_VAL_CHANGE;
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_USER_ROW AS
	OBJECT (
		EMAIL			VARCHAR2(256), --length matches the one from csr.csr_user
		FULL_NAME		VARCHAR2(256),
		FIRST_NAME		VARCHAR2(256),
		LAST_NAME 		VARCHAR2(256),
		USER_NAME 		VARCHAR2(256),
		FRIENDLY_NAME	VARCHAR2(255),
		PHONE_NUM		VARCHAR2(100),
		JOB_TITLE		VARCHAR2(100),
		CREATED_DTM		DATE,
		USER_REF		VARCHAR2(255),
		ACTIVE			NUMBER(1),
		USER_SID		NUMBER(10),
		CONSTRUCTOR FUNCTION T_DEDUPE_USER_ROW
		RETURN SELF AS RESULT
	);
/

CREATE OR REPLACE TYPE BODY CHAIN.T_DEDUPE_USER_ROW AS
  CONSTRUCTOR FUNCTION T_DEDUPE_USER_ROW
	RETURN SELF AS RESULT
	AS
	BEGIN
		RETURN;
	END;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_USER_TABLE AS
 TABLE OF T_DEDUPE_USER_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_ROLE AS
	OBJECT (
		USER_NAME	VARCHAR2(256),
		ROLE_SID	NUMBER(10),
		IS_SET		NUMBER(1)
	);
/

CREATE OR REPLACE TYPE CHAIN.T_DEDUPE_ROLE_TABLE AS
 TABLE OF T_DEDUPE_ROLE;
/

CREATE OR REPLACE TYPE CHAIN.T_OBJECT_CERTIFICATION_ROW AS
	 OBJECT (
		OBJECT_ID					NUMBER(10),
		CERTIFICATION_TYPE_ID		NUMBER(10),
		IS_CERTIFIED				NUMBER(1),
		FROM_DTM					DATE,
		TO_DTM						DATE,
		MAP MEMBER FUNCTION MAP
			RETURN VARCHAR2
	 );
/

CREATE OR REPLACE TYPE BODY chain.T_OBJECT_CERTIFICATION_ROW IS
	MAP MEMBER FUNCTION MAP
		RETURN VARCHAR2
	IS
	BEGIN
		RETURN OBJECT_ID||'@'||CERTIFICATION_TYPE_ID;
	END;
END;
/

CREATE OR REPLACE TYPE CHAIN.T_OBJECT_CERTIFICATION_TABLE AS
	TABLE OF CHAIN.T_OBJECT_CERTIFICATION_ROW;
/

CREATE OR REPLACE TYPE CSR.T_QS_RESPONSE_PERM_ROW AS
	OBJECT (
		SURVEY_RESPONSE_ID			NUMBER(10),
		OBJECT_ID					NUMBER(10),
		CAN_SEE_RESPONSE			NUMBER(1),
		CAN_SEE_SCORES				NUMBER(1),
		MAP MEMBER FUNCTION MAP
			RETURN VARCHAR2
	);
/

CREATE OR REPLACE TYPE BODY CSR.T_QS_RESPONSE_PERM_ROW AS
	MAP MEMBER FUNCTION MAP
		RETURN VARCHAR2
	IS
	BEGIN
		RETURN SURVEY_RESPONSE_ID || ',' || OBJECT_ID;
	END;
END;
/

CREATE OR REPLACE TYPE CSR.T_QS_RESPONSE_PERM_TABLE AS
	TABLE OF CSR.T_QS_RESPONSE_PERM_ROW;
/

-- Create a single element array of a filtered_object_table to use as a column that gets
-- stored inline in the filter_cache table (instead of a nested table that creates a hidden
-- physical table)
CREATE TYPE CHAIN.T_FILTER_CACHE_VARRAY as VARRAY(1) of chain.T_FILTERED_OBJECT_TABLE;
/

-- Table cannot be in create_schema.sql as it depends on chain.T_FILTERED_OBJECT_TABLE
-- No need for this table to be in csrexp/imp
CREATE TABLE chain.filter_cache (
	app_sid			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	user_sid		NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'SID') NOT NULL,
	act_id			CHAR(36)   DEFAULT SYS_CONTEXT('SECURITY', 'ACT') NOT NULL,
	card_group_id	NUMBER(10) NOT NULL,
	expire_dtm		DATE NOT NULL,
	cms_col_sid		NUMBER(10),
	cached_rows		CHAIN.T_FILTER_CACHE_VARRAY
);

CREATE UNIQUE INDEX chain.uk_filter_cache ON chain.filter_cache(app_sid, card_group_id, user_sid, act_id, cms_col_sid);
CREATE INDEX chain.ix_filter_cache_expry ON chain.filter_cache(expire_dtm);
CREATE INDEX chain.ix_filter_cache_user ON chain.filter_cache(user_sid);

CREATE OR REPLACE TYPE CHAIN.T_SID_AND_DESCRIPTION_ROW AS 
  OBJECT ( 
	pos				NUMBER(10,0),
	sid_id 			NUMBER(10,0),
	description		VARCHAR2(2047)
  );
/
CREATE OR REPLACE TYPE CHAIN.T_SID_AND_DESCRIPTION_TABLE AS 
  TABLE OF CHAIN.T_SID_AND_DESCRIPTION_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_REF_PERM_ROW AS
  OBJECT (
	REFERENCE_ID				NUMBER(10),
	PRIMARY_COMPANY_TYPE_ID		NUMBER(10),
	SECONDARY_COMPANY_TYPE_ID	NUMBER(10),
	PERMISSION_SET				NUMBER(10)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_REF_PERM_TABLE AS
  TABLE OF CHAIN.T_REF_PERM_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_PERMISSION_MATRIX_ROW AS
  OBJECT (
	CAPABILITY_ID 					NUMBER(10),
	PRIMARY_COMPANY_GROUP_TYPE_ID	NUMBER(10),
	PRIMARY_COMPANY_TYPE_ROLE_SID	NUMBER(10)
  );
/

CREATE OR REPLACE TYPE CHAIN.T_PERMISSION_MATRIX_TABLE AS
 TABLE OF T_PERMISSION_MATRIX_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_CUSTOMER_OPTIONS_PARAM_ROW AS
	OBJECT (
		ID        NUMBER(10),     
		NAME      VARCHAR2(100), 
		VALUE     VARCHAR2(4000),
		DATA_TYPE VARCHAR2(100), 
		NULLABLE  NUMBER(1)  
	);
/

CREATE OR REPLACE TYPE CHAIN.T_CUSTOMER_OPTIONS_PARAM_TABLE AS
	TABLE OF CHAIN.T_CUSTOMER_OPTIONS_PARAM_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_MESSAGE_SEARCH_ROW AS
	OBJECT (
		MESSAGE_ID 							NUMBER(10),
		MESSAGE_DEFINITION_ID 				NUMBER(10),
		TO_COMPANY_SID 						NUMBER(10),
		TO_USER_SID 						NUMBER(10),
		RE_COMPANY_SID 						NUMBER(10),
		RE_USER_SID 						NUMBER(10),
		RE_QUESTIONNAIRE_TYPE_ID 			NUMBER(10),
		RE_COMPONENT_ID 					NUMBER(10),
		ORDER_BY_DTM 						TIMESTAMP(6),
		LAST_REFRESHED_BY_USER_SID 			NUMBER(10),
		COMPLETED_BY_USER_SID				NUMBER(10),
		VIEWED_DTM 							TIMESTAMP(6),
		RE_SECONDARY_COMPANY_SID 			NUMBER(10),
		RE_INVITATION_ID 					NUMBER(10),
		RE_AUDIT_REQUEST_ID 				NUMBER(10)
	);
/

CREATE OR REPLACE TYPE CHAIN.T_MESSAGE_SEARCH_TABLE AS
	TABLE OF CHAIN.T_MESSAGE_SEARCH_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_VALUE_MAP_ROW AS
	OBJECT (
		OLD_FILTER_VALUE_ID       NUMBER(10),
		NEW_FILTER_VALUE_ID       NUMBER(10)
	);
/

CREATE OR REPLACE TYPE CHAIN.T_FILTER_VALUE_MAP_TABLE AS
	TABLE OF CHAIN.T_FILTER_VALUE_MAP_ROW;
/

CREATE OR REPLACE TYPE CHAIN.T_REFERENCE_LABEL_ROW AS
	OBJECT (
		COMPANY_SID	NUMBER(10,0),
		NAME		VARCHAR2(255 BYTE),
		LOOKUP_KEY	VARCHAR2(255 BYTE)
	);
/

CREATE OR REPLACE TYPE CHAIN.T_REFERENCE_LABEL_TABLE AS
	TABLE OF CHAIN.T_REFERENCE_LABEL_ROW;
/
