
ALTER TABLE CHAIN.AMOUNT_UNIT ADD CONSTRAINT RefCUSTOMER896
    FOREIGN KEY (APP_SID)
    REFERENCES csr.CUSTOMER(APP_SID)
;


ALTER TABLE CHAIN.CHAIN_USER ADD CONSTRAINT RefCSR_USER60
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES csr.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE CHAIN.CHAIN_USER ADD CONSTRAINT RefCSR_USER227
    FOREIGN KEY (APP_SID, MERGED_TO_USER_SID)
    REFERENCES csr.CSR_USER(APP_SID, CSR_USER_SID)
;


ALTER TABLE CHAIN.COMPANY ADD CONSTRAINT RefCOUNTRY382
    FOREIGN KEY (COUNTRY_CODE)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE CHAIN.COMPONENT_DOCUMENT ADD CONSTRAINT RefCUSTOMER903
    FOREIGN KEY (APP_SID)
    REFERENCES csr.CUSTOMER(APP_SID)
;


ALTER TABLE CHAIN.COMPOUND_FILTER ADD CONSTRAINT FK_CMP_FIL_USER_SID
    FOREIGN KEY (APP_SID, CREATED_BY_USER_SID)
    REFERENCES csr.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE CHAIN.CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOMER81
    FOREIGN KEY (APP_SID)
    REFERENCES csr.CUSTOMER(APP_SID)
;


ALTER TABLE CHAIN.UNINVITED_SUPPLIER ADD CONSTRAINT FK_UNINVITED_SUPPLIER_COUNTRY
    FOREIGN KEY (COUNTRY_CODE)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE CHAIN.ALERT_PARTIAL_TEMPLATE ADD
CONSTRAINT FK_PARTIAL_TEMPALTE_ALTRT_TYPE FOREIGN KEY (ALERT_TYPE_ID) REFERENCES CSR.STD_ALERT_TYPE(STD_ALERT_TYPE_ID);
ALTER TABLE CHAIN.ALERT_PARTIAL_TEMPLATE ADD
CONSTRAINT FK_ALRT_PARTIAL_TPL_APP FOREIGN KEY (APP_SID) REFERENCES CSR.CUSTOMER(APP_SID);

ALTER TABLE CHAIN.ALERT_PARTIAL_TEMPLATE_PARAM ADD
CONSTRAINT FK_PARTIAL_TPL_P_ALTRT_TYPE_P FOREIGN KEY (ALERT_TYPE_ID, FIELD_NAME) REFERENCES CSR.STD_ALERT_TYPE_PARAM(STD_ALERT_TYPE_ID, FIELD_NAME);

ALTER TABLE CHAIN.INVITATION_USER_TPL ADD CONSTRAINT FK_TRANSLATION_SET_IUT
    FOREIGN KEY (APP_SID, LANG)
    REFERENCES ASPEN2.TRANSLATION_SET(APPLICATION_SID, LANG)
;

ALTER TABLE CHAIN.INVITATION_BATCH ADD CONSTRAINT FK_INVIT_BATCH_TRANSLATION_SET
	FOREIGN KEY(APP_SID, LANG) REFERENCES ASPEN2.TRANSLATION_SET(APPLICATION_SID, LANG);

ALTER TABLE CHAIN.WORKSHEET_FILE_UPLOAD ADD CONSTRAINT FK_WS_WSFU
    FOREIGN KEY (APP_SID, WORKSHEET_ID)
    REFERENCES CSR.WORKSHEET(APP_SID, WORKSHEET_ID)
;


ALTER TABLE CHAIN.COMPANY_TAG_GROUP ADD CONSTRAINT FK_COMP_TAG_GROUP_TAG_GROUP
    FOREIGN KEY (APP_SID, TAG_GROUP_ID)
    REFERENCES CSR.TAG_GROUP (APP_SID, TAG_GROUP_ID);

ALTER TABLE CHAIN.COMPONENT_TAG ADD CONSTRAINT FK_COMPONENT_TAG_TAG
    FOREIGN KEY (APP_SID, TAG_ID)
    REFERENCES CSR.TAG (APP_SID, TAG_ID);


ALTER TABLE CHAIN.PURCHASE_TAG ADD CONSTRAINT FK_PURCHASE_TAG_TAG
	FOREIGN KEY (APP_SID, TAG_ID)
	REFERENCES CSR.TAG (APP_SID, TAG_ID);

ALTER TABLE CHAIN.COMPANY_TYPE ADD CONSTRAINT FK_ROLE_CT_USER_ROLE
    FOREIGN KEY (APP_SID, USER_ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID)
;

ALTER TABLE CHAIN.COMPANY_TYPE ADD CONSTRAINT FK_SEC_GT_CT_USER_GROUP
	FOREIGN KEY (USER_GROUP_SID)
	REFERENCES SECURITY.GROUP_TABLE(SID_ID);

ALTER TABLE CHAIN.COMPANY_TYPE ADD CONSTRAINT FK_CT_REGION_ROOT_SID_REGION
	FOREIGN KEY (APP_SID, REGION_ROOT_SID)
	REFERENCES CSR.REGION (APP_SID, REGION_SID);

ALTER TABLE CHAIN.QNNAIRE_SHARE_ALERT_LOG ADD CONSTRAINT FK_REF_STD_ALRT_TYP_QSAL_ALRT
    FOREIGN KEY (STD_ALERT_TYPE_ID)
     REFERENCES CSR.STD_ALERT_TYPE(STD_ALERT_TYPE_ID)
;

ALTER TABLE CHAIN.SUPPLIER_AUDIT ADD CONSTRAINT FK_SUPPL_AUDIT_INTERNAL_AUDIT
    FOREIGN KEY (APP_SID, AUDIT_SID)
    REFERENCES CSR.INTERNAL_AUDIT(APP_SID, INTERNAL_AUDIT_SID)
;

ALTER TABLE CHAIN.FLOW_QUESTIONNAIRE_TYPE ADD CONSTRAINT FK_FLOW_QNR_TYPE_FLOW
    FOREIGN KEY (APP_SID, FLOW_SID)
    REFERENCES CSR.FLOW (APP_SID, FLOW_SID)
;

ALTER TABLE CHAIN.FLOW_FILTER ADD CONSTRAINT FK_FLOW_FILTER_FLOW
    FOREIGN KEY (APP_SID, FLOW_SID)
    REFERENCES CSR.FLOW(APP_SID, FLOW_SID)
	ON DELETE CASCADE
;

ALTER TABLE CHAIN.COMPANY_TYPE_RELATIONSHIP ADD
	CONSTRAINT FK_COMPANY_TYPE_REL_FLOW FOREIGN KEY (app_sid, flow_sid) REFERENCES csr.flow (app_sid, flow_sid);

ALTER TABLE CHAIN.SUPPLIER_RELATIONSHIP ADD
	CONSTRAINT FK_SUPPLIER_REL_FLOW_ITEM FOREIGN KEY (app_sid, flow_item_id) REFERENCES csr.flow_item (app_sid, flow_item_id);

ALTER TABLE CHAIN.COMPANY_TAB ADD CONSTRAINT REF_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID)
;

ALTER TABLE CHAIN.COMPANY_TAB ADD CONSTRAINT REF_PLUGIN_TYPE_ID_PLUGIN_TYPE
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID)
;

ALTER TABLE CHAIN.COMPANY_HEADER ADD CONSTRAINT FK_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID)
;

ALTER TABLE CHAIN.COMPANY_HEADER ADD CONSTRAINT FK_PLUGIN_TYPE_ID_PLUGIN_TYPE
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID)
;

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PR_HD_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID)
;

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PR_HD_PLUGIN_TYPE_ID_PLGN_T
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID)
;

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PR_TB_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID)
;

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PR_TB_PLUGIN_TYPE_ID_PLGN_T
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID)
;

ALTER TABLE CHAIN.AUDIT_REQUEST ADD CONSTRAINT REF_AUDITREQ_REQUSER
    FOREIGN KEY (APP_SID, REQUESTED_BY_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);

ALTER TABLE CHAIN.AUDIT_REQUEST ADD CONSTRAINT REF_AUDITREQ_AUDIT
    FOREIGN KEY (APP_SID, AUDIT_SID)
    REFERENCES CSR.INTERNAL_AUDIT(APP_SID, INTERNAL_AUDIT_SID);

ALTER TABLE CHAIN.AUDIT_REQUEST_ALERT ADD CONSTRAINT REF_AUDITREQALERT_USER
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);


ALTER TABLE CHAIN.ACTIVITY_TYPE_TAG_GROUP ADD CONSTRAINT FK_ACT_TYP_TAG_GROUP_TAG_GRP
    FOREIGN KEY (APP_SID, TAG_GROUP_ID)
    REFERENCES CSR.TAG_GROUP(APP_SID, TAG_GROUP_ID)
;

ALTER TABLE CHAIN.ACTIVITY_TYPE_ALERT ADD CONSTRAINT FK_ACT_TYP_ALRT_CSTMR_ALRT_TYP
    FOREIGN KEY (APP_SID, CUSTOMER_ALERT_TYPE_ID)
    REFERENCES CSR.CUSTOMER_ALERT_TYPE(APP_SID, CUSTOMER_ALERT_TYPE_ID)
;

ALTER TABLE CHAIN.ACTIVITY_TAG ADD CONSTRAINT FK_ACTVTY_TAG_TAG_GROUP_MEMBR
    FOREIGN KEY (APP_SID, TAG_GROUP_ID, TAG_ID)
    REFERENCES CSR.TAG_GROUP_MEMBER(APP_SID, TAG_GROUP_ID, TAG_ID)
;

ALTER TABLE CHAIN.ACTIVITY_TYPE_ALERT_ROLE ADD CONSTRAINT FK_ACT_ALRT_ROLE_ROLE
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID);

ALTER TABLE CHAIN.COMPANY_TYPE_ROLE ADD CONSTRAINT FK_CMPY_TYP_RL_ROLE
	FOREIGN KEY (APP_SID, ROLE_SID)
	REFERENCES CSR.ROLE (APP_SID, ROLE_SID);

ALTER TABLE CHAIN.ACTIVITY_INVOLVEMENT ADD CONSTRAINT FK_ACTVTY_INVL_ROLE
	FOREIGN KEY (APP_SID, ROLE_SID)
	REFERENCES CSR.ROLE (APP_SID, ROLE_SID);

ALTER TABLE CHAIN.PRODUCT_TYPE_TAG ADD CONSTRAINT FK_PRODUCT_TYP_TAG_TAG
	FOREIGN KEY (APP_SID, TAG_ID)
	REFERENCES CSR.TAG (APP_SID, TAG_ID);

ALTER TABLE CHAIN.INVITATION_BATCH ADD CONSTRAINT FK_INVITATION_BATCH_BATCH_JOB
	FOREIGN KEY (APP_SID, BATCH_JOB_ID)
	REFERENCES CSR.BATCH_JOB(APP_SID, BATCH_JOB_ID);


ALTER TABLE CHAIN.PRODUCT_REVISION ADD CONSTRAINT FK_PRODUCT_CREATED_BY_SID_USER
	FOREIGN KEY (APP_SID, REVISION_CREATED_BY_SID)
	REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID);

ALTER TABLE chain.company_type ADD CONSTRAINT fk_comp_type_cust_region_type
	FOREIGN KEY (app_sid, default_region_type)
	REFERENCES csr.customer_region_type (app_sid, region_type);

ALTER TABLE chain.business_relationship_type ADD (
	CONSTRAINT fk_bus_rel_tab FOREIGN KEY (APP_SID, TAB_SID) REFERENCES CMS.TAB(APP_SID, TAB_SID),
	CONSTRAINT fk_bus_rel_tab_column FOREIGN KEY (APP_SID, TAB_SID, COLUMN_SID) REFERENCES CMS.TAB_COLUMN(APP_SID, TAB_SID, COLUMN_SID)
);

ALTER TABLE chain.dedupe_mapping ADD CONSTRAINT FK_DEDUPE_MAPPING_COL
	FOREIGN KEY (app_sid, col_sid, tab_sid)
	REFERENCES cms.tab_column(app_sid, column_sid, tab_sid);

ALTER TABLE chain.dedupe_mapping ADD CONSTRAINT FK_DEDUPE_MAPPING_COL_DEST
	FOREIGN KEY (app_sid, destination_col_sid, destination_tab_sid)
	REFERENCES cms.tab_column(app_sid, column_sid, tab_sid);

ALTER TABLE chain.saved_filter ADD (
	CONSTRAINT fk_saved_filter_cms_region_col
		FOREIGN KEY (app_sid, cms_region_column_sid)
		REFERENCES cms.tab_column (app_sid, column_sid),
	CONSTRAINT fk_saved_filter_cms_date_col
		FOREIGN KEY (app_sid, cms_date_column_sid)
		REFERENCES cms.tab_column (app_sid, column_sid),
	CONSTRAINT fk_saved_filter_cms_id_col
		FOREIGN KEY (app_sid, cms_id_column_sid)
		REFERENCES cms.tab_column (app_sid, column_sid)
);

ALTER TABLE chain.saved_filter_region ADD CONSTRAINT fk_svd_fltr_region_region
	FOREIGN KEY (app_sid, region_sid)
	REFERENCES csr.region (app_sid, region_sid);

ALTER TABLE chain.filter_field ADD (
	CONSTRAINT fk_filter_field_cms_col_sid
		FOREIGN KEY (app_sid, column_sid)
		REFERENCES cms.tab_column (app_sid, column_sid)
);

ALTER TABLE chain.filter_page_column ADD (
	CONSTRAINT fk_fltr_pkg_col_app_sid FOREIGN KEY (app_sid)
		REFERENCES csr.customer (app_sid),
	CONSTRAINT fk_fltr_pg_col_group_sid FOREIGN KEY (group_sid)
		REFERENCES security.group_table (sid_id) ON DELETE CASCADE
);

ALTER TABLE chain.filter_page_ind ADD (
	CONSTRAINT fk_filter_page_ind_ind FOREIGN KEY (app_sid, ind_sid)
		REFERENCES csr.ind (app_sid, ind_sid),
	CONSTRAINT fk_filter_page_ind_prd_inrtvl FOREIGN KEY (app_sid, period_set_id, period_interval_id)
		REFERENCES csr.period_interval (app_sid, period_set_id, period_interval_id)
);

ALTER TABLE chain.saved_filter_alert ADD (
	CONSTRAINT FK_SVD_FLTR_ALRT_CTMR_ALRT_TYP FOREIGN KEY (APP_SID, CUSTOMER_ALERT_TYPE_ID)
		REFERENCES CSR.CUSTOMER_ALERT_TYPE (APP_SID, CUSTOMER_ALERT_TYPE_ID)
);

ALTER TABLE chain.saved_filter_alert_subscriptn ADD (
	CONSTRAINT FK_SV_FLTR_ALERT_SUBS_CSR_USR FOREIGN KEY (APP_SID, USER_SID)
		REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID),
	CONSTRAINT FK_SV_FLTR_ALERT_SUBS_REGION FOREIGN KEY (APP_SID, REGION_SID)
		REFERENCES CSR.REGION (APP_SID, REGION_SID)
);

ALTER TABLE CHAIN.SAVED_FILTER_SENT_ALERT ADD (
	CONSTRAINT FK_SVD_FLTR_SENT_ALERT_CSR_USR FOREIGN KEY (APP_SID, USER_SID)
		REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID)
);

ALTER TABLE CHAIN.CARD_GROUP_CARD ADD CONSTRAINT FK_CARD_GROUP_CARD_APP FOREIGN KEY (APP_SID) REFERENCES CSR.CUSTOMER(APP_SID);
ALTER TABLE CHAIN.CARD_INIT_PARAM ADD CONSTRAINT FK_CARD_INIT_PARAM_APP FOREIGN KEY (APP_SID) REFERENCES CSR.CUSTOMER(APP_SID);
ALTER TABLE CHAIN.COMPOUND_FILTER ADD CONSTRAINT FK_CMP_FIL_APP_SID  FOREIGN KEY (APP_SID) REFERENCES CSR.CUSTOMER(APP_SID);

ALTER TABLE chain.filter_field ADD CONSTRAINT fk_fltr_field_period_set
	FOREIGN KEY (app_sid, period_set_id, period_interval_id)
	REFERENCES csr.period_interval(app_sid, period_set_id, period_interval_id);

ALTER TABLE chain.filter_value ADD CONSTRAINT fk_fltr_value_period_interval
	FOREIGN KEY (app_sid, period_set_id, period_interval_id, start_period_id)
	REFERENCES csr.period_interval_member(app_sid, period_set_id, period_interval_id, start_period_id);


ALTER TABLE CHAIN.CUSTOMER_AGGREGATE_TYPE ADD CONSTRAINT FK_CUSTOM_AGG_TYPE_CMS_AGG_TYP FOREIGN KEY (APP_SID, CMS_AGGREGATE_TYPE_ID)
	REFERENCES CMS.CMS_AGGREGATE_TYPE(APP_SID, CMS_AGGREGATE_TYPE_ID)
	ON DELETE CASCADE;

ALTER TABLE CHAIN.CUSTOMER_AGGREGATE_TYPE ADD CONSTRAINT FK_CUSTOM_AGG_TYPE_INIT_METRIC FOREIGN KEY (APP_SID, INITIATIVE_METRIC_ID)
	REFERENCES CSR.INITIATIVE_METRIC(APP_SID, INITIATIVE_METRIC_ID)
	ON DELETE CASCADE;

ALTER TABLE CHAIN.CUSTOMER_AGGREGATE_TYPE ADD CONSTRAINT FK_CUSTOM_AGG_TYPE_IND FOREIGN KEY (APP_SID, IND_SID)
	REFERENCES CSR.IND(APP_SID, IND_SID)
	ON DELETE CASCADE;

ALTER TABLE CHAIN.CUSTOMER_AGGREGATE_TYPE ADD CONSTRAINT FK_SCORE_TYPE_AGG_TYPE FOREIGN KEY (APP_SID, SCORE_TYPE_AGG_TYPE_ID)
	REFERENCES CSR.SCORE_TYPE_AGG_TYPE(APP_SID, SCORE_TYPE_AGG_TYPE_ID)
	ON DELETE CASCADE;

ALTER TABLE CHAIN.CAPABILITY_FLOW_CAPABILITY ADD CONSTRAINT FK_CAP_FLOW_CAP_FLOW_CAP FOREIGN KEY (APP_SID, FLOW_CAPABILITY_ID)
	REFERENCES CSR.CUSTOMER_FLOW_CAPABILITY (APP_SID, FLOW_CAPABILITY_ID)
	ON DELETE CASCADE;

ALTER TABLE chain.filter_page_cms_table ADD CONSTRAINT fk_filter_page_cms_table_col
	FOREIGN KEY (app_sid, column_sid) REFERENCES cms.tab_column (app_sid, column_sid);

ALTER TABLE CHAIN.CUSTOMER_AGGREGATE_TYPE ADD CONSTRAINT FK_CUST_AGG_TYPE_METER_AGG_TYP FOREIGN KEY (APP_SID, METER_AGGREGATE_TYPE_ID)
	REFERENCES CSR.METER_AGGREGATE_TYPE (APP_SID, METER_AGGREGATE_TYPE_ID)
	ON DELETE CASCADE;

ALTER TABLE CHAIN.COMPANY_TAB ADD CONSTRAINT FK_COMPANY_TAB_PAGE_COMP_COL
	FOREIGN KEY (APP_SID, PAGE_COMPANY_COL_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID)
;

ALTER TABLE CHAIN.COMPANY_TAB ADD CONSTRAINT FK_COMPANY_TAB_USER_COMP_COL
	FOREIGN KEY (APP_SID, USER_COMPANY_COL_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID)
;

ALTER TABLE CHAIN.COMPANY_TYPE_TAG_GROUP ADD CONSTRAINT FK_COMP_TYPE_TAG_GR_TAG_GROUP
	FOREIGN KEY (APP_SID, TAG_GROUP_ID)
	REFERENCES CSR.TAG_GROUP(APP_SID, TAG_GROUP_ID);

ALTER TABLE CHAIN.COMPANY_TAB ADD CONSTRAINT FK_CT_FLOW_CAP
	FOREIGN KEY (APP_SID, FLOW_CAPABILITY_ID)
	REFERENCES CSR.CUSTOMER_FLOW_CAPABILITY (APP_SID, FLOW_CAPABILITY_ID);

ALTER TABLE chain.company_header ADD CONSTRAINT fk_company_hdr_product_col
	FOREIGN KEY (app_sid, page_company_col_sid)
	REFERENCES cms.tab_column(app_sid, column_sid);

ALTER TABLE chain.company_header ADD CONSTRAINT fk_company_hdr_user_comp_col
	FOREIGN KEY (app_sid, user_company_col_sid)
	REFERENCES cms.tab_column(app_sid, column_sid);

ALTER TABLE chain.product_header ADD CONSTRAINT fk_product_hdr_product_col
	FOREIGN KEY (app_sid, product_col_sid)
	REFERENCES cms.tab_column(app_sid, column_sid);

ALTER TABLE chain.product_header ADD CONSTRAINT fk_product_hdr_user_comp_col
	FOREIGN KEY (app_sid, user_company_col_sid)
	REFERENCES cms.tab_column(app_sid, column_sid);

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PRODUCT_TAB_PRODUCT_COL
	FOREIGN KEY (APP_SID, product_col_sid)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID);

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PRODUCT_TAB_USER_COMP_COL
	FOREIGN KEY (APP_SID, USER_COMPANY_COL_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID);


ALTER TABLE chain.country_risk_level ADD CONSTRAINT FK_COUNTRY
	FOREIGN KEY (COUNTRY)
	REFERENCES POSTCODE.COUNTRY (COUNTRY);

-- Higg

ALTER TABLE CHAIN.HIGG_CONFIG ADD CONSTRAINT FK_HIGG_SURVEY
	FOREIGN KEY (APP_SID, SURVEY_SID)
	REFERENCES CSR.QUICK_SURVEY (APP_SID, SURVEY_SID);

ALTER TABLE CHAIN.HIGG_CONFIG ADD CONSTRAINT FK_HIGG_AUDIT_TYPE
	FOREIGN KEY (APP_SID, AUDIT_TYPE_ID)
	REFERENCES CSR.INTERNAL_AUDIT_TYPE (APP_SID, INTERNAL_AUDIT_TYPE_ID);

ALTER TABLE CHAIN.HIGG_CONFIG ADD CONSTRAINT FK_HIGG_CLOSURE_TYPE_ID
	FOREIGN KEY (APP_SID, AUDIT_TYPE_ID, CLOSURE_TYPE_ID)
	REFERENCES CSR.AUDIT_TYPE_CLOSURE_TYPE (APP_SID, INTERNAL_AUDIT_TYPE_ID, AUDIT_CLOSURE_TYPE_ID);

ALTER TABLE CHAIN.HIGG_CONFIG ADD CONSTRAINT FK_HIGG_AUDIT_COORDINATOR_ID
	FOREIGN KEY (APP_SID, AUDIT_COORDINATOR_SID)
	REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);

ALTER TABLE CHAIN.HIGG_QUESTION_SURVEY ADD CONSTRAINT FK_HQS_QUICK_SURVEY
	FOREIGN KEY (APP_SID, SURVEY_SID)
	REFERENCES CSR.QUICK_SURVEY (APP_SID, SURVEY_SID);

ALTER TABLE CHAIN.HIGG_QUESTION_SURVEY ADD CONSTRAINT FK_HQS_QS_QUESTION
	FOREIGN KEY (APP_SID, QS_QUESTION_ID, QS_QUESTION_VERSION, SURVEY_SID, SURVEY_VERSION)
	REFERENCES CSR.QUICK_SURVEY_QUESTION (APP_SID, QUESTION_ID, QUESTION_VERSION, SURVEY_SID, SURVEY_VERSION);

ALTER TABLE CHAIN.HIGG_CONFIG_PROFILE ADD CONSTRAINT FK_HIGG_CON_PRO_AUDIT
	FOREIGN KEY (APP_SID, INTERNAL_AUDIT_SID)
	REFERENCES CSR.INTERNAL_AUDIT (APP_SID, INTERNAL_AUDIT_SID);

ALTER TABLE CHAIN.HIGG_QUESTION_OPT_CONVERSION ADD CONSTRAINT FK_HIGG_Q_O_CONV_CONVERSION
	FOREIGN KEY (APP_SID, MEASURE_CONVERSION_ID)
	REFERENCES CSR.MEASURE_CONVERSION (APP_SID, MEASURE_CONVERSION_ID);

ALTER TABLE CHAIN.HIGG_CONFIG_MODULE ADD CONSTRAINT FK_HIGG_MODULE_SCORE_TYPE_ID
    FOREIGN KEY (APP_SID, SCORE_TYPE_ID)
    REFERENCES CSR.SCORE_TYPE(APP_SID, SCORE_TYPE_ID);

ALTER TABLE CHAIN.HIGG_QUESTION_OPTION_SURVEY ADD CONSTRAINT FK_HQS_QS_QO
	FOREIGN KEY (APP_SID, QS_QUESTION_ID, QS_QUESTION_VERSION, QS_QUESTION_DRAFT, QS_QUESTION_OPTION_ID)
    REFERENCES CSR.QUESTION_OPTION(APP_SID, QUESTION_ID, QUESTION_VERSION, QUESTION_DRAFT, QUESTION_OPTION_ID)
;
-- end Higg

ALTER TABLE CHAIN.DEDUPE_PROCESSED_RECORD ADD CONSTRAINT FK_DEDUPE_PROCESS_REC_USER
	FOREIGN KEY (APP_SID, MATCHED_BY_USER_SID)
	REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE CHAIN.DEDUPE_MAPPING ADD CONSTRAINT FK_MAPPING_TAG_GROUP
	FOREIGN KEY (APP_SID, TAG_GROUP_ID)
	REFERENCES CSR.TAG_GROUP (APP_SID, TAG_GROUP_ID)
;

ALTER TABLE CHAIN.DEDUPE_PP_FIELD_CNTRY ADD CONSTRAINT COUNTRY_DD_PP_FIELD_CNTRY
	FOREIGN KEY (COUNTRY_CODE) REFERENCES POSTCODE.COUNTRY (COUNTRY);

ALTER TABLE CHAIN.DEDUPE_MERGE_LOG ADD CONSTRAINT FK_DEDUPE_MERGE_LOG_TAG_GROUP
	FOREIGN KEY (APP_SID, TAG_GROUP_ID)
	REFERENCES CSR.TAG_GROUP (APP_SID, TAG_GROUP_ID)
;

ALTER TABLE CHAIN.DEDUPE_MERGE_LOG ADD CONSTRAINT FK_DEDUPE_MERGE_LOG_DEST
	FOREIGN KEY (APP_SID, DESTINATION_COL_SID, DESTINATION_TAB_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID, TAB_SID)
;

ALTER TABLE CHAIN.COMPANY_TYPE_RELATIONSHIP ADD CONSTRAINT FK_CO_TYPE_REL_FOLLOWER
	FOREIGN KEY (APP_SID, FOLLOWER_ROLE_SID)
	REFERENCES CSR.ROLE (APP_SID, ROLE_SID)
;

ALTER TABLE CHAIN.BSCI_AUDIT ADD CONSTRAINT FK_BSCI_INTERNAL_AUDIT_SID
	FOREIGN KEY (APP_SID, INTERNAL_AUDIT_SID)
	REFERENCES CSR.INTERNAL_AUDIT (APP_SID, INTERNAL_AUDIT_SID
);

ALTER TABLE CHAIN.BSCI_IMPORT ADD CONSTRAINT FK_BSCI_BATCH_JOB
	FOREIGN KEY (APP_SID, BATCH_JOB_ID)
	REFERENCES CSR.BATCH_JOB(APP_SID, BATCH_JOB_ID
);

ALTER TABLE CHAIN.FILTER_EXPORT_BATCH ADD CONSTRAINT FK_FEB_BATCH_JOB
	FOREIGN KEY (APP_SID, BATCH_JOB_ID)
	REFERENCES CSR.BATCH_JOB (APP_SID, BATCH_JOB_ID);

ALTER TABLE chain.dedupe_staging_link ADD CONSTRAINT fk_staging_link_tab
	FOREIGN KEY (app_sid, staging_tab_sid)
	REFERENCES cms.tab (app_sid, tab_sid);

ALTER TABLE chain.dedupe_staging_link ADD CONSTRAINT fk_staging_link_col
	FOREIGN KEY (app_sid, staging_tab_sid, staging_id_col_sid)
	REFERENCES cms.tab_column (app_sid, tab_sid, column_sid);

ALTER TABLE chain.dedupe_staging_link ADD CONSTRAINT fk_staging_link_batch_col
	FOREIGN KEY (app_sid, staging_tab_sid, staging_batch_num_col_sid)
	REFERENCES cms.tab_column (app_sid, tab_sid, column_sid);

ALTER TABLE chain.dedupe_staging_link ADD CONSTRAINT fk_staging_link_source_col
	FOREIGN KEY (app_sid, staging_tab_sid, staging_source_lookup_col_sid)
	REFERENCES cms.tab_column (app_sid, tab_sid, column_sid);

ALTER TABLE chain.dedupe_staging_link ADD CONSTRAINT fk_staging_link_dest_tab
	FOREIGN KEY (app_sid, destination_tab_sid)
	REFERENCES cms.tab (app_sid, tab_sid);

ALTER TABLE chain.dedupe_processed_record ADD CONSTRAINT fk_dedupe_proc_rec_user
	FOREIGN KEY (app_sid, imported_user_sid)
	REFERENCES csr.csr_user (app_sid, csr_user_sid);

ALTER TABLE chain.dedupe_processed_record ADD CONSTRAINT fk_ddp_prc_rec_batch_job
	FOREIGN KEY (app_sid, batch_job_id)
	REFERENCES csr.batch_job (app_sid, batch_job_id);

ALTER TABLE chain.dedupe_mapping ADD CONSTRAINT fk_dedupe_mapping_role
	FOREIGN KEY (app_sid, role_sid)
	REFERENCES csr.role (app_sid, role_sid);

ALTER TABLE chain.dedupe_merge_log ADD CONSTRAINT fk_dedupe_log_role
	FOREIGN KEY (app_sid, role_sid)
	REFERENCES csr.role (app_sid, role_sid);

ALTER TABLE CHAIN.DEDUPE_BATCH_JOB ADD CONSTRAINT FK_BATCHJOB_DEDUPEBATJOB
    FOREIGN KEY (APP_SID, BATCH_JOB_ID)
    REFERENCES CSR.BATCH_JOB(APP_SID, BATCH_JOB_ID)
;

ALTER TABLE chain.business_relationship_type ADD CONSTRAINT fk_bus_rel_type_per_interval
	FOREIGN KEY (app_sid, period_set_id, period_interval_id)
	REFERENCES csr.period_interval (app_sid, period_set_id, period_interval_id);

ALTER TABLE chain.company_type_score_calc ADD CONSTRAINT fk_cmp_typ_scr_clc_scr_typ
	FOREIGN KEY (app_sid, score_type_id)
	REFERENCES csr.score_type (app_sid, score_type_id);

ALTER TABLE chain.company_type_score_calc ADD CONSTRAINT fk_cmp_typ_scr_clc_sup_st
	FOREIGN KEY (app_sid, supplier_score_type_id)
	REFERENCES csr.score_type (app_sid, score_type_id);

ALTER TABLE chain.comp_type_score_calc_comp_type ADD CONSTRAINT fk_cmp_typ_scr_clc_ct_st
	FOREIGN KEY (app_sid, score_type_id)
	REFERENCES csr.score_type (app_sid, score_type_id);

ALTER TABLE CHAIN.CERT_TYPE_AUDIT_TYPE ADD CONSTRAINT FK_CERT_AUDIT_TYPE_AUDIT_TYPE
	FOREIGN KEY (APP_SID, INTERNAL_AUDIT_TYPE_ID)
	REFERENCES CSR.INTERNAL_AUDIT_TYPE(APP_SID, INTERNAL_AUDIT_TYPE_ID)
;

ALTER TABLE CHAIN.COMPANY_PRODUCT_CERTIFICATION ADD CONSTRAINT FK_COMP_PROD_CERT_CERT
	FOREIGN KEY (APP_SID, CERTIFICATION_ID)
	REFERENCES CSR.INTERNAL_AUDIT (APP_SID, INTERNAL_AUDIT_SID);
	
ALTER TABLE CHAIN.PRODUCT_SUPPLIER_CERTIFICATION ADD CONSTRAINT FK_PROD_SUPP_CERT_CERT
	FOREIGN KEY (APP_SID, CERTIFICATION_ID)
	REFERENCES CSR.INTERNAL_AUDIT (APP_SID, INTERNAL_AUDIT_SID);

ALTER TABLE CHAIN.PRODUCT_METRIC  ADD CONSTRAINT FK_PRODUCT_METRIC_IND
	FOREIGN KEY (APP_SID, IND_SID)
	REFERENCES CSR.IND (APP_SID, IND_SID)
;

ALTER TABLE CHAIN.PRODUCT_METRIC_VAL ADD CONSTRAINT FK_PRODUCT_MTRC_VAL_ENTRD_USR
	FOREIGN KEY (APP_SID, ENTERED_BY_SID)
	REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID)
;
	
ALTER TABLE CHAIN.PRODUCT_SUPPLIER_METRIC_VAL ADD CONSTRAINT FK_SPLD_PRDCT_MTRC_VL_ENTD_USR
	FOREIGN KEY (APP_SID, ENTERED_BY_SID)
	REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID)
;

ALTER TABLE CHAIN.COMPANY ADD CONSTRAINT FK_COMPANY_REQUESTED_BY_USER
	FOREIGN KEY (APP_SID, REQUESTED_BY_USER_SID) REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID);
	
ALTER TABLE CHAIN.PENDING_COMPANY_TAG ADD CONSTRAINT FK_PEND_COMPANY_TAG_TAG
	FOREIGN KEY (APP_SID, TAG_ID) REFERENCES CSR.TAG (APP_SID, TAG_ID);
		
ALTER TABLE CHAIN.SUPPLIER_RELATIONSHIP_SCORE ADD CONSTRAINT FK_SUP_REL_SCORE_TYPE 
	FOREIGN KEY (APP_SID, SCORE_TYPE_ID)
	REFERENCES CSR.SCORE_TYPE(APP_SID, SCORE_TYPE_ID);

ALTER TABLE CHAIN.SUPPLIER_RELATIONSHIP_SCORE ADD CONSTRAINT FK_SUP_REL_SCORE_THRESH_ID 
	FOREIGN KEY (APP_SID, SCORE_THRESHOLD_ID)
	REFERENCES CSR.SCORE_THRESHOLD(APP_SID, SCORE_THRESHOLD_ID);
	
ALTER TABLE CHAIN.SUPPLIER_RELATIONSHIP_SCORE ADD CONSTRAINT FK_SUP_REL_CSR_USER 
	FOREIGN KEY (APP_SID, CHANGED_BY_USER_SID)
	REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);
	
ALTER TABLE chain.supplier_involvement_type ADD CONSTRAINT fk_supp_inv_type_inv_type
	FOREIGN KEY (app_sid, flow_involvement_type_id)
	REFERENCES csr.flow_involvement_type (app_sid, flow_involvement_type_id);

ALTER TABLE chain.supplier_involvement_type ADD CONSTRAINT fk_supp_inv_type_role
	FOREIGN KEY (app_sid, restrict_to_role_sid)
	REFERENCES csr.role(app_sid, role_sid);
	
ALTER TABLE chain.company_product_tag ADD CONSTRAINT FK_COMPANY_PRODUCT_TAG_TAG
	FOREIGN KEY (APP_SID, TAG_GROUP_ID, TAG_ID)
	REFERENCES CSR.TAG_GROUP_MEMBER (APP_SID, TAG_GROUP_ID, TAG_ID);

ALTER TABLE chain.product_supplier_tag ADD CONSTRAINT FK_PRODUCT_SUPPLIER_TAG_TAG
	FOREIGN KEY (APP_SID, TAG_GROUP_ID, TAG_ID)
	REFERENCES CSR.TAG_GROUP_MEMBER (APP_SID, TAG_GROUP_ID, TAG_ID);

ALTER TABLE CHAIN.REFERENCE_CAPABILITY
	ADD CONSTRAINT FK_REF_CAP_PRI_COMP_ROL
	FOREIGN KEY (APP_SID, PRIMARY_COMPANY_TYPE_ROLE_SID)
	REFERENCES CSR.ROLE (APP_SID, ROLE_SID);

ALTER TABLE chain.geotag_batch
	ADD CONSTRAINT fk_geotag_batch_job 
	FOREIGN KEY (app_sid, batch_job_id) 
	REFERENCES csr.batch_job (app_sid, batch_job_id);