@echo off
setlocal
set script=compile_packages.sql
if exist "%script%" del /f "%script%">nul
echo -- Warning: This file is automatically generated by generate_compile_packages.cmd. Any changes made to it will be lost.>"%script%"
for %%i in (*_pkg.sql) do echo PROMPT Compiling %%~ni...>>"%script%" && echo @@%%i>>"%script%"
for %%i in (*_body.sql) do echo PROMPT Compiling %%~ni...>>"%script%" && echo @@%%i>>"%script%"