CREATE TABLE CAMPAIGNS.CAMPAIGN(
	APP_SID						NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	CAMPAIGN_SID				NUMBER(10, 0)	NOT NULL,
	NAME						VARCHAR2(255),
	TABLE_SID					NUMBER(10, 0),
	FILTER_SID					NUMBER(10, 0),
	SURVEY_SID					NUMBER(10, 0),
	FRAME_ID					NUMBER(10, 0),
	SUBJECT						CLOB,
	BODY						CLOB,
	SEND_AFTER_DTM				DATE,
	STATUS						VARCHAR2(20)	 DEFAULT 'draft' NOT NULL,
	SENT_DTM					DATE,
	PERIOD_START_DTM			DATE,
	PERIOD_END_DTM				DATE,
	AUDIENCE_TYPE				CHAR(2)		DEFAULT 'LF' NOT NULL,
	FLOW_SID					NUMBER(10, 0),
	INC_REGIONS_WITH_NO_USERS	NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	SKIP_OVERLAPPING_REGIONS	NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	CARRY_FORWARD_ANSWERS		NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	SEND_TO_COLUMN_SID			NUMBER(10, 0),
	REGION_COLUMN_SID			NUMBER(10, 0),
	CREATED_BY_SID				NUMBER(10, 0),
	FILTER_XML					CLOB,
	RESPONSE_COLUMN_SID			NUMBER(10, 0),
	TAG_LOOKUP_KEY_COLUMN_SID	NUMBER(10, 0),
	IS_SYSTEM_GENERATED			NUMBER(10, 0)	DEFAULT 0 NOT NULL,
	CUSTOMER_ALERT_TYPE_ID		NUMBER(10, 0),
	CAMPAIGN_END_DTM			DATE,
	SEND_ALERT					NUMBER(1, 0)	 DEFAULT 1 NOT NULL,
	DYNAMIC						NUMBER(1, 0)	 DEFAULT 0 NOT NULL,
	RESEND						NUMBER(1, 0)	 DEFAULT 0 NOT NULL,
	CONSTRAINT CHK_CARRY_FORWARD_ANSWERS CHECK (CARRY_FORWARD_ANSWERS IN (0,1)),
	CONSTRAINT CHK_CAMPAIGN_STATUS CHECK (STATUS IN ('draft', 'pending', 'sending', 'sent', 'error', 'emailing')),
	CONSTRAINT CHK_PERIOD_DATES CHECK ((period_start_dtm IS NULL AND period_end_dtm IS NULL) OR period_start_dtm < period_end_dtm),
	CONSTRAINT CHK_CAMPAIGN_AUD_TYPE CHECK (AUDIENCE_TYPE IN ('LF', 'WF')),
	CONSTRAINT CHK_AUDIENCE_REFERENCES CHECK ((AUDIENCE_TYPE='LF' AND FLOW_SID IS NULL) OR
	(AUDIENCE_TYPE='WF' AND TABLE_SID IS NULL AND FILTER_SID IS NULL)),
	CONSTRAINT CHK_QS_CAMP_REG_NO_USR_0_1 CHECK (INC_REGIONS_WITH_NO_USERS IN (0, 1)),
	CONSTRAINT CHK_SURVEY_SID_NOT_DRAFT CHECK ((LOWER(status) != 'draft' AND survey_sid IS NOT NULL) OR
	(LOWER(status) = 'draft' AND survey_sid IS NOT NULL) OR (LOWER(status) = 'draft' AND survey_sid IS NULL)),
	CONSTRAINT PK_CAMPAIGN PRIMARY KEY (APP_SID, CAMPAIGN_SID)
)
;

CREATE TABLE CAMPAIGNS.CAMPAIGN_REGION(
	APP_SID						NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	CAMPAIGN_SID				NUMBER(10, 0)	NOT NULL,
	REGION_SID					NUMBER(10, 0)	NOT NULL,
	HAS_MANUAL_AMENDS			NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	PENDING_DELETION			NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	REGION_SELECTION			VARCHAR2(2)	  	DEFAULT 'R' NOT NULL,
	TAG_ID						NUMBER(10, 0),
	CONSTRAINT CHK_CAMPAIGN_REG_PENDING_DEL CHECK (PENDING_DELETION IN (0,1,2)),
	CONSTRAINT CHK_CAMPAIGN_REGION_AMENDS CHECK (HAS_MANUAL_AMENDS IN (0,1)),
	CONSTRAINT CHK_CAMPAIGN_REGION_RS CHECK (REGION_SELECTION IN ('R','L','P','RT','LT','PT')),
	CONSTRAINT PK_CAMPAIGN_REGION PRIMARY KEY (APP_SID, CAMPAIGN_SID, REGION_SID)
)
;

CREATE TABLE CAMPAIGNS.CAMPAIGN_REGION_RESPONSE (
	APP_SID					NUMBER(10)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	CAMPAIGN_SID			NUMBER(10)	NOT NULL,
	REGION_SID				NUMBER(10)	NOT NULL,
	RESPONSE_ID				NUMBER(10)	NOT NULL,
	SURVEYS_VERSION			NUMBER(1)	NOT NULL,
	FLOW_ITEM_ID			NUMBER(10)	,
	RESPONSE_UUID			VARCHAR2(64)	,
	REGISTERED_IN_ACG_DTM	DATE	,
	CONSTRAINTS PK_CAMPAIGN_REGION_RESPONSE PRIMARY KEY (APP_SID, CAMPAIGN_SID, REGION_SID, RESPONSE_ID)
);

ALTER TABLE CAMPAIGNS.CAMPAIGN_REGION ADD CONSTRAINT FK_CAMPAIGN_REGION_CAMPAIGN 
	FOREIGN KEY (APP_SID, CAMPAIGN_SID) REFERENCES CAMPAIGNS.CAMPAIGN (APP_SID, CAMPAIGN_SID);

ALTER TABLE CAMPAIGNS.CAMPAIGN_REGION_RESPONSE ADD CONSTRAINT FK_CAMP_REGION_RESP_CAMPAIGN 
	FOREIGN KEY (APP_SID, CAMPAIGN_SID) REFERENCES CAMPAIGNS.CAMPAIGN (APP_SID, CAMPAIGN_SID);

CREATE UNIQUE INDEX campaigns.ix_campaign_response_uuid ON campaigns.campaign_region_response (lower(response_uuid));

CREATE INDEX CAMPAIGNS.IX_CAMPAIGN_REGION_TAG_ID ON CAMPAIGNS.CAMPAIGN_REGION(APP_SID, TAG_ID)
;

CREATE INDEX CAMPAIGNS.IX_CAMPAIGN_ALERT_TYPE_ID ON CAMPAIGNS.CAMPAIGN(APP_SID, CUSTOMER_ALERT_TYPE_ID)
;

CREATE INDEX CAMPAIGNS.IX_CAMPAIGN_FLOW_SID ON CAMPAIGNS.CAMPAIGN(APP_SID, FLOW_SID)
;

CREATE INDEX CAMPAIGNS.IX_CAMPAIGN_REG_RESP_FLOW_ITEM ON CAMPAIGNS.CAMPAIGN_REGION_RESPONSE(APP_SID, FLOW_ITEM_ID)
;