--
-- ER/Studio 8.0 SQL Code Generation
-- Project :      DATA MODEL
--
-- Date Created : Tuesday, June 26, 2012 09:00:49
-- Target DBMS : Oracle 10g
--

-- 
-- SEQUENCE: REGION_ID_SEQ 
--

CREATE SEQUENCE REGION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: BREAKDOWN 
--

CREATE TABLE BREAKDOWN(
    APP_SID              NUMBER(10, 0)     NOT NULL,
    BREAKDOWN_TYPE_ID    NUMBER(10, 0)     NOT NULL,
    COMPANY_SID          NUMBER(10, 0)     NOT NULL,
    BREAKDOWN_ID         NUMBER(10, 0)     NOT NULL,
    DESCRIPTION          VARCHAR2(1024)    NOT NULL,
    FTE                  NUMBER(10, 0),
    TURNOVER             NUMBER(10, 0),
    FTE_TRAVEL           NUMBER(10, 0)     NOT NULL,
    IS_REMAINDER         NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    REGION_ID            NUMBER(10, 0),
    CONSTRAINT PK_BREAKDOWN PRIMARY KEY (APP_SID, BREAKDOWN_ID)
)
;



-- 
-- TABLE: BREAKDOWN_EIO 
--

CREATE TABLE BREAKDOWN_EIO(
    BREAKDOWN_ID    NUMBER(10, 0)    NOT NULL,
    EIO_ID          NUMBER(10, 0)    NOT NULL,
    PCT             NUMBER(10, 0)    NOT NULL,
    APP_SID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_BREAKDOWN_EIO PRIMARY KEY (BREAKDOWN_ID, EIO_ID, APP_SID)
)
;



-- 
-- TABLE: BREAKDOWN_TYPE 
--

CREATE TABLE BREAKDOWN_TYPE(
    APP_SID              NUMBER(10, 0)     NOT NULL,
    BREAKDOWN_TYPE_ID    NUMBER(10, 0)     NOT NULL,
    SINGULAR             VARCHAR2(1024)    NOT NULL,
    PLURAL               VARCHAR2(1024)    NOT NULL,
    BY_TURNOVER          NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    BY_FTE               NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    IS_REGION            NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BREAKDOWN_TYPE PRIMARY KEY (APP_SID, BREAKDOWN_TYPE_ID)
)
;



-- 
-- TABLE: BUS_TYPE 
--

CREATE TABLE BUS_TYPE(
    BUS_TYPE_ID                   NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_BUS_TYPE PRIMARY KEY (BUS_TYPE_ID)
)
;



-- 
-- TABLE: BUSINESS_TYPE 
--

CREATE TABLE BUSINESS_TYPE(
    BUSINESS_TYPE_ID    NUMBER(10, 0)     NOT NULL,
    DESCRIPTION         VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK_BUSINESS_TYPE PRIMARY KEY (BUSINESS_TYPE_ID)
)
;



-- 
-- TABLE: CAR 
--

CREATE TABLE CAR(
    CAR_ID                       NUMBER(10, 0)    NOT NULL,
    DESCRIPTION                  VARCHAR2(256)    NOT NULL,
    MANUFACTURER_ID              NUMBER(10, 0)    NOT NULL,
    EFFICIENCY_KM_LITRE          NUMBER(10, 3)    NOT NULL,
    FUEL_TYPE_ID                 CHAR(10)         NOT NULL,
    TRANSMISSION_CODE            VARCHAR2(10)     NOT NULL,
    ENGINE_CAPACITY_CC           NUMBER(10, 3)    NOT NULL,
    KM_PER_LITRE_URBAN           NUMBER(10, 3)    NOT NULL,
    KM_PER_LITRE_EX_URBAN        NUMBER(10, 3)    NOT NULL,
    MILES_PER_GALLON_URBAN       NUMBER(10, 3)    NOT NULL,
    MILES_PER_GALLON_EX_URBAN    NUMBER(10, 3)    NOT NULL,
    MILES_PER_GALLON_COMBINED    NUMBER(10, 3)    NOT NULL,
    CO2_KG_PER_KM                NUMBER(10, 3)    NOT NULL,
    CO_G_PER_KM                  NUMBER(10, 3),
    HC_G_PER_KM                  NUMBER(10, 3),
    NOX_G_PER_KM                 NUMBER(10, 3),
    HC_NOX_G_PER_KM              NUMBER(10, 3),
    EMISSION_PARTIC_G_PER_KM     NUMBER(10, 3),
    EURO_STANDARD                NUMBER(10, 0)    NOT NULL,
    NOISE_LEVEL_DBA              NUMBER(10, 3)    NOT NULL,
    CONSTRAINT PK_CAR PRIMARY KEY (CAR_ID)
)
;



-- 
-- TABLE: CAR_TYPE 
--

CREATE TABLE CAR_TYPE(
    CAR_TYPE_ID                   NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_CAR_TYPE PRIMARY KEY (CAR_TYPE_ID)
)
;



-- 
-- TABLE: CHAIN.COMPANY 
--

CREATE TABLE CHAIN.COMPANY(
    APP_SID        NUMBER(10, 0)    NOT NULL,
    COMPANY_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (APP_SID, COMPANY_SID)
)
;



-- 
-- TABLE: CHAIN.CUSTOMER_OPTIONS 
--

CREATE TABLE CHAIN.CUSTOMER_OPTIONS(
    APP_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK40 PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: COMPANY 
--

CREATE TABLE COMPANY(
    APP_SID                NUMBER(10, 0)    NOT NULL,
    COMPANY_SID            NUMBER(10, 0)    NOT NULL,
    FTE                    NUMBER(10, 0)    NOT NULL,
    TURNOVER               NUMBER(10, 0)    NOT NULL,
    CURRENCY_ID            NUMBER(10, 0)    NOT NULL,
    PERIOD_ID              NUMBER(10, 0)    NOT NULL,
    BUSINESS_TYPE_ID       NUMBER(10, 0)    NOT NULL,
    EIO_ID                 NUMBER(10, 0)    NOT NULL,
    SCOPE_INPUT_TYPE_ID    NUMBER(10, 0),
    SCOPE_1                NUMBER(10, 0),
    SCOPE_2                NUMBER(10, 0),
    CONSTRAINT PK_COMPANY PRIMARY KEY (APP_SID, COMPANY_SID)
)
;



-- 
-- TABLE: COMPANY_CONSUMPTION_TYPE 
--

CREATE TABLE COMPANY_CONSUMPTION_TYPE(
    APP_SID                NUMBER(10, 0)    NOT NULL,
    COMPANY_SID            NUMBER(10, 0)    NOT NULL,
    CONSUMPTION_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    VALUE                  NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_COMPANY_CONSUMPTION_TYPE PRIMARY KEY (APP_SID, COMPANY_SID, CONSUMPTION_TYPE_ID)
)
;



-- 
-- TABLE: CONSUMPTION_TYPE 
--

CREATE TABLE CONSUMPTION_TYPE(
    CONSUMPTION_TYPE_ID      NUMBER(10, 0)     NOT NULL,
    DESCRIPTION              VARCHAR2(10)      NOT NULL,
    KWH_TO_CO2_CONVERSION    NUMBER(20, 10)    NOT NULL,
    UOM_DESC                 VARCHAR2(32)      NOT NULL,
    CONSTRAINT PK_CONSUMPTION_TYPE PRIMARY KEY (CONSUMPTION_TYPE_ID)
)
;



-- 
-- TABLE: CSR.CUSTOMER 
--

CREATE TABLE CSR.CUSTOMER(
    APP_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: CURRENCY 
--

CREATE TABLE CURRENCY(
    CURRENCY_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION    VARCHAR2(256)    NOT NULL,
    SYMBOL         VARCHAR2(4)      NOT NULL,
    CONSTRAINT PK_CURRENCY PRIMARY KEY (CURRENCY_ID)
)
;



-- 
-- TABLE: CURRENCY_PERIOD 
--

CREATE TABLE CURRENCY_PERIOD(
    PERIOD_ID                  NUMBER(10, 0)     NOT NULL,
    CURRENCY_ID                NUMBER(10, 0)     NOT NULL,
    PURCHSE_PWR_PARITY_FACT    NUMBER(30, 20),
    EXCH_RATE_X_PER_DLLR       NUMBER(30, 20),
    INCORRECT_FACTOR           NUMBER(30, 20),
    RATIO_CURRENT_PRICE        NUMBER(30, 20),
    CONSTRAINT PK_CURRENCY_PERIOD PRIMARY KEY (PERIOD_ID, CURRENCY_ID)
)
;



-- 
-- TABLE: CUSTOMER_OPTIONS 
--

CREATE TABLE CUSTOMER_OPTIONS(
    APP_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK39 PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: EC_QUESTIONNAIRE_ANSWERS 
--

CREATE TABLE EC_QUESTIONNAIRE_ANSWERS(
    APP_SID                    NUMBER(10, 0)    NOT NULL,
    COMPANY_SID                NUMBER(10, 0)    NOT NULL,
    RESPONDANT_ID              NUMBER(10, 0)    NOT NULL,
    FULL_TIME_EMPLOYEE         NUMBER(1, 0)     NOT NULL
                               CHECK (FULL_TIME_EMPLOYEE  IN (1,0)),
    WORKING_DAYS_PER_WK        NUMBER(10, 3)    NOT NULL,
    TRAVEL_DAYS_PER_YR         NUMBER(10, 3)    NOT NULL,
    VACATION_DAYS_PER_YR       NUMBER(10, 3)    NOT NULL,
    OTHER_LEAVE_DAYS_PER_YR    NUMBER(10, 3)    NOT NULL,
    CAR_DAYS_PER_WK            NUMBER(10, 3)    NOT NULL
                               CHECK (CAR_DAYS_PER_WK <= 7),
    CAR_JOURNEY_KM             NUMBER(10, 3)    NOT NULL,
    ECQ_CAR_TYPE_ID            NUMBER(10, 0),
    CAR_ID                     NUMBER(10, 0),
    MOTORBIKE_DAYS_PER_WK      NUMBER(10, 3)    NOT NULL
                               CHECK (MOTORBIKE_DAYS_PER_WK <= 7),
    MOTORBIKE_JOURNEY_KM       NUMBER(10, 3)    NOT NULL,
    ECQ_MOTORBIKE_TYPE_ID      NUMBER(10, 0),
    TRAIN_DAYS_PER_WK          NUMBER(10, 3)    NOT NULL
                               CHECK (TRAIN_DAYS_PER_WK <= 7),
    TRAIN_JOURNEY_KM           NUMBER(10, 3)    NOT NULL
                               CHECK (TRAIN_JOURNEY_KM <= 7),
    ECQ_TRAIN_TYPE_ID          NUMBER(10, 0),
    BUS_DAYS_PER_WK            NUMBER(10, 3)    NOT NULL
                               CHECK (BUS_DAYS_PER_WK <= 7),
    BUS_JOURNEY_KM             NUMBER(10, 3)    NOT NULL
                               CHECK (BUS_JOURNEY_KM <= 7),
    ECQ_BUS_TYPE_ID            NUMBER(10, 0),
    BIKE_DAYS_PER_WK           NUMBER(10, 3)    NOT NULL
                               CHECK (BIKE_DAYS_PER_WK <= 7),
    BIKE_JOURNEY_KM            NUMBER(10, 3)    NOT NULL
                               CHECK (BIKE_JOURNEY_KM <= 7),
    WALK_DAYS_PER_WK           NUMBER(10, 3)    NOT NULL
                               CHECK (WALK_DAYS_PER_WK <= 7),
    WALK_JOURNEY_KM            NUMBER(10, 3)    NOT NULL
                               CHECK (WALK_JOURNEY_KM <= 7),
    HOME_DAYS_PER_WK           NUMBER(10, 3)    NOT NULL
                               CHECK (HOME_DAYS_PER_WK <= 7),
    CONSTRAINT PK_EC_QUESTIONNAIRE_ANSWERS PRIMARY KEY (APP_SID, COMPANY_SID, RESPONDANT_ID)
)
;



-- 
-- TABLE: EC_REGION 
--

CREATE TABLE EC_REGION(
    REGION_ID                   NUMBER(10, 0)     NOT NULL,
    HOLIDAYS                    NUMBER(20, 10)    NOT NULL,
    CAR_AVG_PCT_USE             NUMBER(20, 10)    NOT NULL
                                CHECK ((CAR_AVG_PCT_USE <= 100) AND (CAR_AVG_PCT_USE >= 0)),
    BUS_AVG_PCT_USE             NUMBER(20, 10)    NOT NULL
                                CHECK ((BUS_AVG_PCT_USE <= 100) AND (BUS_AVG_PCT_USE >= 0)),
    TRAIN_AVG_PCT_USE           NUMBER(20, 10)    NOT NULL
                                CHECK ((TRAIN_AVG_PCT_USE <= 100) AND (TRAIN_AVG_PCT_USE >= 0)),
    MOTORBIKE_AVG_PCT_USE       NUMBER(20, 10)    NOT NULL
                                CHECK ((MOTORBIKE_AVG_PCT_USE <= 100) AND (MOTORBIKE_AVG_PCT_USE >= 0)),
    BIKE_AVG_PCT_USE            NUMBER(20, 10)    NOT NULL
                                CHECK ((BIKE_AVG_PCT_USE <= 100) AND (BIKE_AVG_PCT_USE >= 0)),
    WALK_AVG_PCT_USE            NUMBER(20, 10)    NOT NULL
                                CHECK ((WALK_AVG_PCT_USE <= 100) AND (WALK_AVG_PCT_USE >= 0)),
    CAR_AVG_JOURNEY_KM          NUMBER(20, 10)    NOT NULL
                                CHECK ((CAR_AVG_JOURNEY_KM <= 100) AND (CAR_AVG_JOURNEY_KM >= 0)),
    BUS_AVG_JOURNEY_KM          NUMBER(20, 10)    NOT NULL
                                CHECK ((BUS_AVG_JOURNEY_KM <= 100) AND (BUS_AVG_JOURNEY_KM >= 0)),
    TRAIN_AVG_JOURNEY_KM        NUMBER(20, 10)    NOT NULL
                                CHECK ((TRAIN_AVG_JOURNEY_KM <= 100) AND (TRAIN_AVG_JOURNEY_KM >= 0)),
    MOTORBIKE_AVG_JOURNEY_KM    NUMBER(20, 10)    NOT NULL
                                CHECK ((MOTORBIKE_AVG_JOURNEY_KM <= 100) AND (MOTORBIKE_AVG_JOURNEY_KM >= 0)),
    BIKE_AVG_JOURNEY_KM         NUMBER(20, 10)    NOT NULL
                                CHECK ((BIKE_AVG_JOURNEY_KM <= 100) AND (BIKE_AVG_JOURNEY_KM >= 0)),
    WALK_AVG_JOURNEY_KM         NUMBER(20, 10)    NOT NULL
                                CHECK ((WALK_AVG_JOURNEY_KM <= 100) AND (WALK_AVG_JOURNEY_KM >= 0)),
    CONSTRAINT PK_EC_REGION PRIMARY KEY (REGION_ID)
)
;



-- 
-- TABLE: ECQ_BUS_TYPE 
--

CREATE TABLE ECQ_BUS_TYPE(
    ECQ_BUS_TYPE_ID               NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_ECQ_BUS_TYPE PRIMARY KEY (ECQ_BUS_TYPE_ID)
)
;



-- 
-- TABLE: ECQ_CAR_TYPE 
--

CREATE TABLE ECQ_CAR_TYPE(
    ECQ_CAR_TYPE_ID        NUMBER(10, 0)     NOT NULL,
    DESCRIPTION            VARCHAR2(256)     NOT NULL,
    EFFICIENCY_KM_LITRE    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_ECQ_CAR_TYPE PRIMARY KEY (ECQ_CAR_TYPE_ID)
)
;



-- 
-- TABLE: ECQ_MOTORBIKE_TYPE 
--

CREATE TABLE ECQ_MOTORBIKE_TYPE(
    ECQ_MOTORBIKE_TYPE_ID         NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_ECQ_MOTORBIKE_TYPE PRIMARY KEY (ECQ_MOTORBIKE_TYPE_ID)
)
;



-- 
-- TABLE: ECQ_TRAIN_TYPE 
--

CREATE TABLE ECQ_TRAIN_TYPE(
    ECQ_TRAIN_TYPE_ID             NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_ECQ_TRAIN_TYPE PRIMARY KEY (ECQ_TRAIN_TYPE_ID)
)
;



-- 
-- TABLE: EIO 
--

CREATE TABLE EIO(
    EIO_ID                    NUMBER(10, 0)     NOT NULL,
    DESCRIPTION               VARCHAR2(256)     NOT NULL,
    EIO_GROUP_ID              NUMBER(10, 0)     NOT NULL,
    EMIS_FCTR_C_TO_G          NUMBER(30, 20)    NOT NULL,
    PCT_ELEC_ENERGY           NUMBER(30, 20)    NOT NULL,
    PCT_OTHER_ENERGY          NUMBER(30, 20)    NOT NULL,
    PCT_USE_PHASE             NUMBER(30, 20)    NOT NULL,
    PCT_WAREHOUSE             NUMBER(30, 20)    NOT NULL,
    PCT_WASTE                 NUMBER(30, 20)    NOT NULL,
    PCT_UPSTREAM_TRANS        NUMBER(30, 20)    NOT NULL,
    PCT_DOWNSTREAM_TRANS      NUMBER(30, 20)    NOT NULL,
    PCT_CTFC_SCOPE_ONE_TWO    NUMBER(30, 20)    NOT NULL,
    CONSTRAINT PK_EIO PRIMARY KEY (EIO_ID)
)
;



-- 
-- TABLE: EIO_GROUP 
--

CREATE TABLE EIO_GROUP(
    EIO_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION     VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK_EIO_GROUP PRIMARY KEY (EIO_GROUP_ID)
)
;



-- 
-- TABLE: EIO_RELATIONSHIP 
--

CREATE TABLE EIO_RELATIONSHIP(
    PRIMARY_EIO_CAT_ID    NUMBER(10, 0)     NOT NULL,
    RELATED_EIO_CAT_ID    NUMBER(10, 0)     NOT NULL,
    PCT                   NUMBER(30, 25)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EIO_RELATIONSHIP PRIMARY KEY (PRIMARY_EIO_CAT_ID, RELATED_EIO_CAT_ID)
)
;



-- 
-- TABLE: FUEL_TYPE 
--

CREATE TABLE FUEL_TYPE(
    FUEL_TYPE_ID          CHAR(10)         NOT NULL,
    DESCRIPTION           VARCHAR2(256)    NOT NULL,
    COST_GBP_PER_LITRE    NUMBER(10, 3)    NOT NULL,
    CONSTRAINT PK_FUEL_TYPE PRIMARY KEY (FUEL_TYPE_ID)
)
;



-- 
-- TABLE: HOT_REGION 
--

CREATE TABLE HOT_REGION(
    REGION_ID            NUMBER(10, 0)     NOT NULL,
    FULL_LIFECYCLE_EF    NUMBER(20, 10)    NOT NULL,
    COMBUSITION_EF       NUMBER(20, 10)    NOT NULL,
    UPSTREAM_EF          NUMBER(20, 10)    NOT NULL,
    TD_LOSS_EF           NUMBER(20, 10)    NOT NULL,
    PCT_PROP_OF_US_EF    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK43 PRIMARY KEY (REGION_ID)
)
;



-- 
-- TABLE: MANUFACTURER 
--

CREATE TABLE MANUFACTURER(
    MANUFACTURER_ID    NUMBER(10, 0)    NOT NULL,
    MANUFACTURER       VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK_MANUFACTURER PRIMARY KEY (MANUFACTURER_ID)
)
;



-- 
-- TABLE: MOTORBIKE_TYPE 
--

CREATE TABLE MOTORBIKE_TYPE(
    MOTORBIKE_TYPE_ID             NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_MOTORBIKE_TYPE PRIMARY KEY (MOTORBIKE_TYPE_ID)
)
;



-- 
-- TABLE: PERIOD 
--

CREATE TABLE PERIOD(
    PERIOD_ID      NUMBER(10, 0)    NOT NULL,
    DESCRIPTION    VARCHAR2(256),
    CONSTRAINT PK_PERIOD PRIMARY KEY (PERIOD_ID)
)
;



-- 
-- TABLE: POSTCODE.COUNTRY 
--

CREATE TABLE POSTCODE.COUNTRY(
    COUNTRY    VARCHAR2(2)    NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (COUNTRY)
)
;



-- 
-- TABLE: REGION 
--

CREATE TABLE REGION(
    REGION_ID      NUMBER(10, 0)     NOT NULL,
    DESCRIPTION    VARCHAR2(1024)    NOT NULL,
    COUNTRY        VARCHAR2(2),
    PARENT_ID      NUMBER(10, 0),
    CONSTRAINT PK_REGION PRIMARY KEY (REGION_ID),
    CONSTRAINT UK_REGION_DESCRIPTION  UNIQUE (DESCRIPTION),
    CONSTRAINT UK_REGION_COUNTRY  UNIQUE (COUNTRY)
)
;



-- 
-- TABLE: SCOPE_INPUT_TYPE 
--

CREATE TABLE SCOPE_INPUT_TYPE(
    SCOPE_INPUT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPTION            VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK_SCOPE_INPUT_TYPE PRIMARY KEY (SCOPE_INPUT_TYPE_ID)
)
;



-- 
-- TABLE: TRAIN_TYPE 
--

CREATE TABLE TRAIN_TYPE(
    TRAIN_TYPE_ID                 NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(256)     NOT NULL,
    KG_CO2_PER_KM_CONTRIBUTION    NUMBER(20, 10)    NOT NULL,
    CONSTRAINT PK_TRAIN_TYPE PRIMARY KEY (TRAIN_TYPE_ID)
)
;



-- 
-- TABLE: BREAKDOWN 
--

ALTER TABLE BREAKDOWN ADD CONSTRAINT RefCUSTOMER_OPTIONS45 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE BREAKDOWN ADD CONSTRAINT RefBREAKDOWN_TYPE17 
    FOREIGN KEY (APP_SID, BREAKDOWN_TYPE_ID)
    REFERENCES BREAKDOWN_TYPE(APP_SID, BREAKDOWN_TYPE_ID)
;

ALTER TABLE BREAKDOWN ADD CONSTRAINT RefCOMPANY18 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE BREAKDOWN ADD CONSTRAINT RefREGION23 
    FOREIGN KEY (REGION_ID)
    REFERENCES REGION(REGION_ID)
;


-- 
-- TABLE: BREAKDOWN_EIO 
--

ALTER TABLE BREAKDOWN_EIO ADD CONSTRAINT RefBREAKDOWN20 
    FOREIGN KEY (APP_SID, BREAKDOWN_ID)
    REFERENCES BREAKDOWN(APP_SID, BREAKDOWN_ID)
;

ALTER TABLE BREAKDOWN_EIO ADD CONSTRAINT RefEIO21 
    FOREIGN KEY (EIO_ID)
    REFERENCES EIO(EIO_ID)
;


-- 
-- TABLE: BREAKDOWN_TYPE 
--

ALTER TABLE BREAKDOWN_TYPE ADD CONSTRAINT RefCUSTOMER_OPTIONS46 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER_OPTIONS(APP_SID)
;


-- 
-- TABLE: CAR 
--

ALTER TABLE CAR ADD CONSTRAINT RefMANUFACTURER27 
    FOREIGN KEY (MANUFACTURER_ID)
    REFERENCES MANUFACTURER(MANUFACTURER_ID)
;

ALTER TABLE CAR ADD CONSTRAINT RefFUEL_TYPE28 
    FOREIGN KEY (FUEL_TYPE_ID)
    REFERENCES FUEL_TYPE(FUEL_TYPE_ID)
;


-- 
-- TABLE: COMPANY 
--

ALTER TABLE COMPANY ADD CONSTRAINT RefCOMPANY49 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE COMPANY ADD CONSTRAINT RefCURRENCY_PERIOD8 
    FOREIGN KEY (PERIOD_ID, CURRENCY_ID)
    REFERENCES CURRENCY_PERIOD(PERIOD_ID, CURRENCY_ID)
;

ALTER TABLE COMPANY ADD CONSTRAINT RefBUSINESS_TYPE9 
    FOREIGN KEY (BUSINESS_TYPE_ID)
    REFERENCES BUSINESS_TYPE(BUSINESS_TYPE_ID)
;

ALTER TABLE COMPANY ADD CONSTRAINT RefEIO11 
    FOREIGN KEY (EIO_ID)
    REFERENCES EIO(EIO_ID)
;

ALTER TABLE COMPANY ADD CONSTRAINT RefSCOPE_INPUT_TYPE24 
    FOREIGN KEY (SCOPE_INPUT_TYPE_ID)
    REFERENCES SCOPE_INPUT_TYPE(SCOPE_INPUT_TYPE_ID)
;


-- 
-- TABLE: COMPANY_CONSUMPTION_TYPE 
--

ALTER TABLE COMPANY_CONSUMPTION_TYPE ADD CONSTRAINT RefCOMPANY25 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE COMPANY_CONSUMPTION_TYPE ADD CONSTRAINT RefCONSUMPTION_TYPE26 
    FOREIGN KEY (CONSUMPTION_TYPE_ID)
    REFERENCES CONSUMPTION_TYPE(CONSUMPTION_TYPE_ID)
;


-- 
-- TABLE: CURRENCY_PERIOD 
--

ALTER TABLE CURRENCY_PERIOD ADD CONSTRAINT RefCURRENCY3 
    FOREIGN KEY (CURRENCY_ID)
    REFERENCES CURRENCY(CURRENCY_ID)
;

ALTER TABLE CURRENCY_PERIOD ADD CONSTRAINT RefPERIOD4 
    FOREIGN KEY (PERIOD_ID)
    REFERENCES PERIOD(PERIOD_ID)
;


-- 
-- TABLE: CUSTOMER_OPTIONS 
--

ALTER TABLE CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOMER_OPTIONS50 
    FOREIGN KEY (APP_SID)
    REFERENCES CHAIN.CUSTOMER_OPTIONS(APP_SID)
;

ALTER TABLE CUSTOMER_OPTIONS ADD CONSTRAINT RefCUSTOMER51 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;


-- 
-- TABLE: EC_QUESTIONNAIRE_ANSWERS 
--

ALTER TABLE EC_QUESTIONNAIRE_ANSWERS ADD CONSTRAINT RefECQ_TRAIN_TYPE32 
    FOREIGN KEY (ECQ_TRAIN_TYPE_ID)
    REFERENCES ECQ_TRAIN_TYPE(ECQ_TRAIN_TYPE_ID)
;

ALTER TABLE EC_QUESTIONNAIRE_ANSWERS ADD CONSTRAINT RefECQ_MOTORBIKE_TYPE33 
    FOREIGN KEY (ECQ_MOTORBIKE_TYPE_ID)
    REFERENCES ECQ_MOTORBIKE_TYPE(ECQ_MOTORBIKE_TYPE_ID)
;

ALTER TABLE EC_QUESTIONNAIRE_ANSWERS ADD CONSTRAINT RefCOMPANY39 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES COMPANY(APP_SID, COMPANY_SID)
;

ALTER TABLE EC_QUESTIONNAIRE_ANSWERS ADD CONSTRAINT RefECQ_CAR_TYPE29 
    FOREIGN KEY (ECQ_CAR_TYPE_ID)
    REFERENCES ECQ_CAR_TYPE(ECQ_CAR_TYPE_ID)
;

ALTER TABLE EC_QUESTIONNAIRE_ANSWERS ADD CONSTRAINT RefCAR30 
    FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID)
;

ALTER TABLE EC_QUESTIONNAIRE_ANSWERS ADD CONSTRAINT RefECQ_BUS_TYPE31 
    FOREIGN KEY (ECQ_BUS_TYPE_ID)
    REFERENCES ECQ_BUS_TYPE(ECQ_BUS_TYPE_ID)
;


-- 
-- TABLE: EC_REGION 
--

ALTER TABLE EC_REGION ADD CONSTRAINT RefREGION36 
    FOREIGN KEY (REGION_ID)
    REFERENCES REGION(REGION_ID)
;


-- 
-- TABLE: EIO 
--

ALTER TABLE EIO ADD CONSTRAINT RefEIO_GROUP10 
    FOREIGN KEY (EIO_GROUP_ID)
    REFERENCES EIO_GROUP(EIO_GROUP_ID)
;


-- 
-- TABLE: EIO_RELATIONSHIP 
--

ALTER TABLE EIO_RELATIONSHIP ADD CONSTRAINT RefEIO12 
    FOREIGN KEY (PRIMARY_EIO_CAT_ID)
    REFERENCES EIO(EIO_ID)
;

ALTER TABLE EIO_RELATIONSHIP ADD CONSTRAINT RefEIO13 
    FOREIGN KEY (RELATED_EIO_CAT_ID)
    REFERENCES EIO(EIO_ID)
;


-- 
-- TABLE: HOT_REGION 
--

ALTER TABLE HOT_REGION ADD CONSTRAINT RefREGION48 
    FOREIGN KEY (REGION_ID)
    REFERENCES REGION(REGION_ID)
;


-- 
-- TABLE: REGION 
--

ALTER TABLE REGION ADD CONSTRAINT RefREGION37 
    FOREIGN KEY (PARENT_ID)
    REFERENCES REGION(REGION_ID)
;

ALTER TABLE REGION ADD CONSTRAINT RefCOUNTRY52 
    FOREIGN KEY (COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;


