-- Please update version.sql too -- this keeps clean builds in sync
define version=65
@update_header

CREATE TABLE TASK_RECALC_PERIOD(
    APP_SID      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID     NUMBER(10, 0)    NOT NULL,
    START_DTM    DATE             NOT NULL,
    END_DTM      DATE             NOT NULL,
    CONSTRAINT PK122 PRIMARY KEY (APP_SID, TASK_SID, START_DTM)
)
;

CREATE TABLE TASK_RECALC_REGION(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_SID      NUMBER(10, 0)    NOT NULL,
    REGION_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK121 PRIMARY KEY (APP_SID, TASK_SID, REGION_SID)
)
;

ALTER TABLE TASK_RECALC_PERIOD ADD CONSTRAINT RefTASK_RECALC_JOB226 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES TASK_RECALC_JOB(APP_SID, TASK_SID)
;

ALTER TABLE TASK_RECALC_REGION ADD CONSTRAINT RefTASK_REGION227 
    FOREIGN KEY (APP_SID, TASK_SID, REGION_SID)
    REFERENCES TASK_REGION(APP_SID, TASK_SID, REGION_SID)
;

ALTER TABLE TASK_RECALC_REGION ADD CONSTRAINT RefTASK_RECALC_JOB228 
    FOREIGN KEY (APP_SID, TASK_SID)
    REFERENCES TASK_RECALC_JOB(APP_SID, TASK_SID)
;

-- Recompile SPs
@../dependency_pkg
@../task_pkg
@../dependency_body
@../task_body

-- RLS
@../rls

@update_tail
