-- Please update version.sql too -- this keeps clean builds in sync
define version=42
@update_header

CREATE TABLE ALLOW_TASK_STATUS_CHANGE(
    TASK_STATUS_ID       NUMBER(10, 0)    NOT NULL,
    USER_OR_GROUP_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK84 PRIMARY KEY (TASK_STATUS_ID, USER_OR_GROUP_SID)
)
;

ALTER TABLE ALLOW_TASK_STATUS_CHANGE ADD CONSTRAINT RefTASK_STATUS109 
    FOREIGN KEY (TASK_STATUS_ID)
    REFERENCES TASK_STATUS(TASK_STATUS_ID)
;

@update_tail
