-- Please update version.sql too -- this keeps clean builds in sync
define version=41
@update_header

CREATE TABLE INITIATIVE_EXTRA_INFO(
    TASK_SID          NUMBER(10, 0)    NOT NULL,
    ONE_OFF_SAVING    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK80 PRIMARY KEY (TASK_SID)
)
;

CREATE TABLE INITIATIVE_PROJECT_TEAM(
    TASK_SID    NUMBER(10, 0)    NOT NULL,
    NAME        VARCHAR2(512)    NOT NULL,
    EMAIL       VARCHAR2(512)
)
;

ALTER TABLE INITIATIVE_EXTRA_INFO ADD CONSTRAINT RefTASK106 
    FOREIGN KEY (TASK_SID)
    REFERENCES TASK(TASK_SID)
;

ALTER TABLE INITIATIVE_PROJECT_TEAM ADD CONSTRAINT RefTASK107 
    FOREIGN KEY (TASK_SID)
    REFERENCES TASK(TASK_SID)
;

@update_tail
