-- Please update version.sql too -- this keeps clean builds in sync
define version=87
@update_header

create index actions.ix_aggr_task_ind_ind_sid on actions.aggr_task_ind_dependency (app_sid, ind_sid);
create index actions.ix_aggr_task_per_project_sid_t on actions.aggr_task_period (app_sid, project_sid, task_period_status_id);
create index actions.ix_aggr_task_per_region_sid on actions.aggr_task_period (app_sid, region_sid);
create index actions.ix_aggr_task_per_overridden_by on actions.aggr_task_period_override (app_sid, overridden_by_sid);
create index actions.ix_aggr_task_tas_depends_on_ta on actions.aggr_task_task_dependency (app_sid, depends_on_task_sid);
create index actions.ix_csr_task_role_user_sid on actions.csr_task_role_member (app_sid, user_sid);
create index actions.ix_csr_task_role_role_sid on actions.csr_task_role_member (app_sid, role_sid);
create index actions.ix_customer_opti_default_value on actions.customer_options (app_sid, default_value_script_id);
create index actions.ix_file_upload_g_file_id on actions.file_upload_group_member (app_sid, file_id);
create index actions.ix_import_templa_project_sid on actions.import_template (app_sid, project_sid);
create index actions.ix_ind_template_measure_sid on actions.ind_template (app_sid, measure_sid);
create index actions.ix_initiative_pr_task_sid on actions.initiative_project_team (app_sid, task_sid);
create index actions.ix_initiative_sp_task_sid on actions.initiative_sponsor (app_sid, task_sid);
create index actions.ix_periodic_aler_alert_type_id on actions.periodic_alert (alert_type_id);
create index actions.ix_periodic_aler_csr_user_sid on actions.periodic_alert_user (app_sid, csr_user_sid);
create index actions.ix_project_ind_sid on actions.project (app_sid, ind_sid);
create index actions.ix_project_file__project_sid on actions.project_file_upload_group (app_sid, project_sid);
create index actions.ix_project_ind_t_saving_templa on actions.project_ind_template (app_sid, saving_template_id);
create index actions.ix_project_ind_t_ongoing_templ on actions.project_ind_template (app_sid, ongoing_template_id);
create index actions.ix_project_ind_t_merged_templa on actions.project_ind_template (app_sid, merged_template_id);
create index actions.ix_project_ind_t_ind_template_ on actions.project_ind_template (app_sid, ind_template_id);
create index actions.ix_project_ind_t_ind_sid on actions.project_ind_template_instance (app_sid, ind_sid);
create index actions.ix_project_ind_t_from_ind_temp on actions.project_ind_template_instance (app_sid, from_ind_template_id);
create index actions.ix_project_regio_user_sid on actions.project_region_role_member (app_sid, user_sid);
create index actions.ix_project_regio_region_sid on actions.project_region_role_member (app_sid, region_sid);
create index actions.ix_project_regio_inherited_fro on actions.project_region_role_member (app_sid, inherited_from_sid);
create index actions.ix_project_regio_role_sid on actions.project_region_role_member (app_sid, role_sid);
create index actions.ix_project_role_role_id on actions.project_role (app_sid, role_id);
create index actions.ix_project_tag_g_project_sid on actions.project_tag_group (app_sid, project_sid);
create index actions.ix_project_task__task_period_s on actions.project_task_period_status (app_sid, task_period_status_id);
create index actions.ix_project_task__task_status_i on actions.project_task_status (app_sid, task_status_id);
create index actions.ix_reckoner_cons_reckoner_cons on actions.reckoner_const_dep (reckoner_const_id);
create index actions.ix_reckoner_tag_reckoner_id on actions.reckoner_tag (reckoner_id);
create index actions.ix_reckoner_tag_tag_group_id_ on actions.reckoner_tag (app_sid, tag_group_id, tag_id);
create index actions.ix_reckoner_tag__tag_group_id_ on actions.reckoner_tag_group (app_sid, tag_group_id, project_sid);
create index actions.ix_root_ind_temp_ind_sid on actions.root_ind_template_instance (app_sid, ind_sid);
create index actions.ix_tag_group_mem_tag_id on actions.tag_group_member (app_sid, tag_id);
create index actions.ix_task_input_ind_sid on actions.task (app_sid, input_ind_sid);
create index actions.ix_task_target_ind_si on actions.task (app_sid, target_ind_sid);
create index actions.ix_task_output_ind_si on actions.task (app_sid, output_ind_sid);
create index actions.ix_task_project_sid_t on actions.task (app_sid, project_sid, task_status_id);
create index actions.ix_task_parent_task_s on actions.task (app_sid, parent_task_sid);
create index actions.ix_task_last_transiti on actions.task (app_sid, last_transition_id);
create index actions.ix_task_budget_h_set_by_user_s on actions.task_budget_history (app_sid, set_by_user_sid);
create index actions.ix_task_comment_user_sid on actions.task_comment (app_sid, user_sid);
create index actions.ix_task_comment_task_sid on actions.task_comment (app_sid, task_sid);
create index actions.ix_task_file_upl_file_id on actions.task_file_upload (app_sid, file_id);
create index actions.ix_task_indicato_indicator_sid on actions.task_indicator (app_sid, indicator_sid);
create index actions.ix_task_ind_depe_ind_sid on actions.task_ind_dependency (app_sid, ind_sid);
create index actions.ix_task_ind_temp_ind_sid on actions.task_ind_template_instance (app_sid, ind_sid);
create index actions.ix_task_ind_temp_from_ind_temp on actions.task_ind_template_instance (app_sid, from_ind_template_id);
create index actions.ix_task_period_project_sid_t on actions.task_period (app_sid, project_sid, task_period_status_id);
create index actions.ix_task_period_task_sid_regi on actions.task_period (app_sid, task_sid, region_sid);
create index actions.ix_task_period_f_file_id on actions.task_period_file_upload (app_sid, file_id);
create index actions.ix_task_period_o_overridden_by on actions.task_period_override (app_sid, overridden_by_sid);
create index actions.ix_task_period_s_means_task_st on actions.task_period_status (app_sid, means_task_status_id);
create index actions.ix_task_region_region_sid on actions.task_region (app_sid, region_sid);
create index actions.ix_task_role_mem_project_sid_r on actions.task_role_member (app_sid, project_sid, role_id, user_or_group_sid);
create index actions.ix_task_status_h_set_by_user_s on actions.task_status_history (app_sid, set_by_user_sid);
create index actions.ix_task_status_h_task_status_i on actions.task_status_history (app_sid, task_status_id);
create index actions.ix_task_status_r_role_sid on actions.task_status_role (app_sid, role_sid);
create index actions.ix_task_status_t_alert_type_id on actions.task_status_transition (alert_type_id);
create index actions.ix_task_status_t_from_task_sta on actions.task_status_transition (app_sid, from_task_status_id);
create index actions.ix_task_status_t_to_task_statu on actions.task_status_transition (app_sid, to_task_status_id);
create index actions.ix_task_tag_tag_id on actions.task_tag (app_sid, tag_id);
create index actions.ix_task_task_dep_depends_on_ta on actions.task_task_dependency (app_sid, depends_on_task_sid);

@update_tail
