-- Please update version.sql too -- this keeps clean builds in sync
define version=84
@update_header

CREATE SEQUENCE IMPORT_TEMPLATE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE TABLE IMPORT_TEMPLATE(
    APP_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IMPORT_TEMPLATE_ID    NUMBER(10, 0)     NOT NULL,
    HEADING_ROW_IDX       NUMBER(10, 0)     NOT NULL,
    WORKSHEET_NAME        VARCHAR2(1024)    NOT NULL,
    PROJECT_SID           NUMBER(10, 0),
    WORKBOOK              BLOB              NOT NULL,
    CONSTRAINT PK148 PRIMARY KEY (APP_SID, IMPORT_TEMPLATE_ID)
)
;

CREATE TABLE IMPORT_TEMPLATE_MAPPING(
    APP_SID               NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IMPORT_TEMPLATE_ID    NUMBER(10, 0)     NOT NULL,
    TO_NAME               VARCHAR2(1024)      NOT NULL,
    FROM_NAME             VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK149 PRIMARY KEY (APP_SID, IMPORT_TEMPLATE_ID, TO_NAME)
)
;

ALTER TABLE IMPORT_TEMPLATE ADD CONSTRAINT RefPROJECT299 
    FOREIGN KEY (APP_SID, PROJECT_SID)
    REFERENCES PROJECT(APP_SID, PROJECT_SID)
;

ALTER TABLE IMPORT_TEMPLATE ADD CONSTRAINT RefCUSTOMER300 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE IMPORT_TEMPLATE_MAPPING ADD CONSTRAINT RefIMPORT_TEMPLATE301 
    FOREIGN KEY (APP_SID, IMPORT_TEMPLATE_ID)
    REFERENCES IMPORT_TEMPLATE(APP_SID, IMPORT_TEMPLATE_ID)
;


@../rls
@../importer_pkg
@../importer_body

@update_tail
