-- Please update version.sql too -- this keeps clean builds in sync
define version=72
@update_header

CREATE GLOBAL TEMPORARY TABLE TEMP_TASK_SIDS
(
	TASK_SID 			NUMBER(10, 0)	NOT NULL
)
ON COMMIT DELETE ROWS;

DROP TABLE ALLOW_TASK_STATUS_CHANGE CASCADE CONSTRAINTS;

CREATE SEQUENCE TASK_STATUS_TRANSITION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE TABLE ALLOW_TRANSITION(
    APP_SID                      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_TRANSITION_ID    NUMBER(10, 0)    NOT NULL,
    USER_OR_GROUP_SID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_ALLOW_TRANSITION PRIMARY KEY (APP_SID, TASK_STATUS_TRANSITION_ID, USER_OR_GROUP_SID)
)
;

ALTER TABLE TASK_STATUS ADD (
	BUTTON_TEXT         VARCHAR2(255),
	NOTE                VARCHAR2(1024),
	MEANS_COMPLETED     NUMBER(1, 0)      DEFAULT 0 NOT NULL
                        CHECK (MEANS_COMPLETED IN(0,1)),
    MEANS_TERMINATED    NUMBER(1, 0)      DEFAULT 0 NOT NULL
                        CHECK (MEANS_TERMINATED IN(0,1)),
    BELONGS_TO_OWNER    NUMBER(1, 0)      DEFAULT 0 NOT NULL
                        CHECK (BELONGS_TO_OWNER IN(0,1))
)
;

CREATE TABLE TASK_STATUS_ROLE(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    ROLE_SID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK125 PRIMARY KEY (APP_SID, TASK_STATUS_ID, ROLE_SID)
)
;

CREATE TABLE TASK_STATUS_TRANSITION(
    APP_SID                      NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TASK_STATUS_TRANSITION_ID    NUMBER(10, 0)    NOT NULL,
    TO_TASK_STATUS_ID            NUMBER(10, 0)	  NOT NULL,
    FROM_TASK_STATUS_ID          NUMBER(10, 0),
    POS                          NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK127 PRIMARY KEY (APP_SID, TASK_STATUS_TRANSITION_ID)
)
;

ALTER TABLE ALLOW_TRANSITION ADD CONSTRAINT RefTASK_STATUS_TRANSITION241 
    FOREIGN KEY (APP_SID, TASK_STATUS_TRANSITION_ID)
    REFERENCES TASK_STATUS_TRANSITION(APP_SID, TASK_STATUS_TRANSITION_ID)
;

ALTER TABLE TASK_STATUS_ROLE ADD CONSTRAINT RefROLE243 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID)
;

ALTER TABLE TASK_STATUS_ROLE ADD CONSTRAINT RefTASK_STATUS244 
    FOREIGN KEY (APP_SID, TASK_STATUS_ID)
    REFERENCES TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

ALTER TABLE TASK_STATUS_TRANSITION ADD CONSTRAINT RefTASK_STATUS245 
    FOREIGN KEY (APP_SID, FROM_TASK_STATUS_ID)
    REFERENCES TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

ALTER TABLE TASK_STATUS_TRANSITION ADD CONSTRAINT RefCUSTOMER246 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE TASK_STATUS_TRANSITION ADD CONSTRAINT RefTASK_STATUS247 
    FOREIGN KEY (APP_SID, TO_TASK_STATUS_ID)
    REFERENCES TASK_STATUS(APP_SID, TASK_STATUS_ID)
;

grant select, delete on TASK_STATUS_ROLE to csr;
grant select, delete on TASK_STATUS_TRANSITION to csr;
grant select, delete on ALLOW_TRANSITION to csr;

@../create_views
@../rls

@../gantt_pkg
@../initiative_pkg

@../gantt_body
@../initiative_body

connect csr/csr@&_CONNECT_IDENTIFIER
@../../csr_data_body
connect actions/actions@&_CONNECT_IDENTIFIER

@update_tail
