
-- 
-- TABLE: TASK_INSTANCE 
--

CREATE TABLE TASK_INSTANCE(
    TASK_SID       NUMBER(10, 0)    NOT NULL,
    INSTANCE_ID    NUMBER(10, 0)    NOT NULL,
    CONTEXT        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK15_1 PRIMARY KEY (TASK_SID, INSTANCE_ID, CONTEXT)
)
;




-- 
-- TABLE: TASK_INSTANCE 
--

ALTER TABLE TASK_INSTANCE ADD CONSTRAINT RefTASK50 
    FOREIGN KEY (TASK_SID)
    REFERENCES TASK(TASK_SID)
;

