-- Please update version.sql too -- this keeps clean builds in sync
define version=17
@update_header

ALTER TABLE CUSTOMER_OPTIONS ADD(
	AGGREGATE_TASK_TREE      NUMBER(1, 0)     DEFAULT 0 NOT NULL
);

CREATE TABLE AGGR_TASK_PERIOD(
    TASK_SID                 NUMBER(10, 0)    NOT NULL,
    START_DTM                DATE             NOT NULL,
    REGION_SID               NUMBER(10, 0)    NOT NULL,
    PROJECT_SID              NUMBER(10, 0),
    TASK_PERIOD_STATUS_ID    NUMBER(10, 0),
    NEEDS_AGGREGATION         NUMBER(1, 0)    DEFAULT 0 NOT NULL,
    END_DTM                  DATE             NOT NULL,
    FIELDS_XML               CLOB,
    CONSTRAINT PK7_1 PRIMARY KEY (TASK_SID, START_DTM, REGION_SID)
);

ALTER TABLE AGGR_TASK_PERIOD ADD CONSTRAINT RefTASK62 
    FOREIGN KEY (TASK_SID)
    REFERENCES TASK(TASK_SID)
;

ALTER TABLE AGGR_TASK_PERIOD ADD CONSTRAINT RefPROJECT_TASK_PERIOD_STATU65 
    FOREIGN KEY (PROJECT_SID, TASK_PERIOD_STATUS_ID)
    REFERENCES PROJECT_TASK_PERIOD_STATUS(PROJECT_SID, TASK_PERIOD_STATUS_ID)
;

@update_tail