--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      TEST
-- Project :      newSchema.dm1
-- Author :       TEST
--
-- Date Created : Friday, November 15, 2013 16:02:18
-- Target DBMS : Oracle 10g
--

-- 
-- TABLE: FOREST_SOURCE_CAT 
--

CREATE TABLE SUPPLIER.FOREST_SOURCE_CAT(
    FOREST_SOURCE_CAT_CODE    VARCHAR2(32)      NOT NULL,
    NAME                      VARCHAR2(256)     NOT NULL,
    DESCRIPTION               VARCHAR2(1024),
    CONSTRAINT PK55 PRIMARY KEY (FOREST_SOURCE_CAT_CODE)
)
;



-- 
-- TABLE: RECYC_FSCC_CS_MAP 
--

CREATE TABLE SUPPLIER.RECYC_FSCC_CS_MAP(
    FOREST_SOURCE_CAT_CODE    VARCHAR2(32)     NOT NULL,
    CERT_SCHEME_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK423 PRIMARY KEY (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID)
)
;



-- 
-- TABLE: SUPPLIER.ALL_PRODUCT 
--

CREATE TABLE SUPPLIER.ALL_PRODUCT(
    PRODUCT_ID              NUMBER(10, 0)     NOT NULL,
    PRODUCT_CODE            VARCHAR2(256)     NOT NULL,
    DESCRIPTION             VARCHAR2(1024)    NOT NULL,
    SUPPLIER_COMPANY_SID    NUMBER(10, 0)     NOT NULL,
    ACTIVE                  NUMBER(1, 0)      NOT NULL,
    DELETED                 NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    APP_SID                 NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (PRODUCT_ID)
)
;



-- 
-- TABLE: SUPPLIER.BLEACHING_PROCESS 
--

CREATE TABLE SUPPLIER.BLEACHING_PROCESS(
    BLEACHING_PROCESS_ID    NUMBER(10, 0)     NOT NULL,
    NAME                    VARCHAR2(256)     NOT NULL,
    DESCRIPTION             VARCHAR2(1024),
    CONSTRAINT PK63 PRIMARY KEY (BLEACHING_PROCESS_ID)
)
;



-- 
-- TABLE: SUPPLIER.CERT_SCHEME 
--

CREATE TABLE SUPPLIER.CERT_SCHEME(
    CERT_SCHEME_ID       NUMBER(10, 0)     NOT NULL,
    NAME                 VARCHAR2(255)     NOT NULL,
    DESCRIPTION          VARCHAR2(1024),
    VERIFIED_FSCC        VARCHAR2(32)      NOT NULL,
    NON_VERIFIED_FSCC    VARCHAR2(32)      NOT NULL,
    ALLOW_USER_SELECT    NUMBER(1, 0)      DEFAULT 1 NOT NULL
                         CHECK (ALLOW_USER_SELECT IN (1,0)),
    CONSTRAINT PK50 PRIMARY KEY (CERT_SCHEME_ID)
)
;



-- 
-- TABLE: SUPPLIER.COUNTRY 
--

CREATE TABLE SUPPLIER.COUNTRY(
    COUNTRY_CODE      VARCHAR2(8)      NOT NULL,
    COUNTRY           VARCHAR2(256)    NOT NULL,
    MEANS_VERIFIED    NUMBER(1, 0)     DEFAULT 1 NOT NULL
                      CHECK (MEANS_VERIFIED IN (1,0)),
    CONSTRAINT PK54 PRIMARY KEY (COUNTRY_CODE)
)
;



-- 
-- TABLE: SUPPLIER.DOCUMENT_GROUP 
--

CREATE TABLE SUPPLIER.DOCUMENT_GROUP(
    DOCUMENT_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK59 PRIMARY KEY (DOCUMENT_GROUP_ID)
)
;



-- 
-- TABLE: SUPPLIER.PRODUCT_PART 
--

CREATE TABLE SUPPLIER.PRODUCT_PART(
    PRODUCT_PART_ID    NUMBER(10, 0)    NOT NULL,
    PART_TYPE_ID       NUMBER(10, 0)    NOT NULL,
    PARENT_ID          NUMBER(10, 0),
    PRODUCT_ID         NUMBER(10, 0),
    CONSTRAINT PK27 PRIMARY KEY (PRODUCT_PART_ID)
)
;



-- 
-- TABLE: SUPPLIER.SUPPLIER_ANSWERS_WOOD 
--

CREATE TABLE SUPPLIER.SUPPLIER_ANSWERS_WOOD(
    COMPANY_SID          NUMBER(10, 0)    NOT NULL,
    LEGAL_PROCS          NUMBER(1, 0)     NOT NULL,
    LEGAL_PROC_NOTE      CLOB,
    DECLARE_NO_APP       NUMBER(1, 0)     NOT NULL,
    DECLARE_NO_CITIES    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK143 PRIMARY KEY (COMPANY_SID)
)
;



-- 
-- TABLE: SUPPLIER.TREE_SPECIES 
--

CREATE TABLE SUPPLIER.TREE_SPECIES(
    SPECIES_CODE      VARCHAR2(32)     NOT NULL,
    GENUS             VARCHAR2(256),
    SPECIES           VARCHAR2(256),
    COMMON_NAME       VARCHAR2(256),
    MEANS_VERIFIED    NUMBER(1, 0)     DEFAULT 1 NOT NULL
                      CHECK (MEANS_VERIFIED IN (1,0)),
    CONSTRAINT PK49 PRIMARY KEY (SPECIES_CODE)
)
;



-- 
-- TABLE: SUPPLIER.UNIT 
--

CREATE TABLE SUPPLIER.UNIT(
    UNIT_ID         NUMBER(10, 0)    NOT NULL,
    NAME            VARCHAR2(255)    NOT NULL,
    SYMBOL          VARCHAR2(10)     NOT NULL,
    UNIT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK64 PRIMARY KEY (UNIT_ID)
)
;



-- 
-- TABLE: SUPPLIER.WOOD_PART_DESCRIPTION 
--

CREATE TABLE SUPPLIER.WOOD_PART_DESCRIPTION(
    PRODUCT_PART_ID               NUMBER(10, 0)     NOT NULL,
    DESCRIPTION                   VARCHAR2(1024)    NOT NULL,
    NUMBER_IN_PRODUCT             NUMBER(10, 2)     NOT NULL,
    WEIGHT                        NUMBER(10, 4)     NOT NULL,
    WEIGHT_UNIT_ID                NUMBER(10, 0)     NOT NULL,
    PRE_RECYCLED_PCT              NUMBER(10, 2)     NOT NULL,
    POST_RECYCLED_PCT             NUMBER(10, 2)     NOT NULL,
    PRE_RECYCLED_DOC_GROUP_ID     NUMBER(10, 0),
    POST_RECYCLED_DOC_GROUP_ID    NUMBER(10, 0),
    PRE_CERT_SCHEME_ID            NUMBER(10, 0)     NOT NULL,
    POST_CERT_SCHEME_ID           NUMBER(10, 0)     NOT NULL,
    PRE_RECYCLED_COUNTRY_CODE     VARCHAR2(8)       NOT NULL,
    POST_RECYCLED_COUNTRY_CODE    VARCHAR2(8)       NOT NULL,
    CONSTRAINT PK30 PRIMARY KEY (PRODUCT_PART_ID)
)
;



-- 
-- TABLE: SUPPLIER.WOOD_PART_WOOD 
--

CREATE TABLE SUPPLIER.WOOD_PART_WOOD(
    PRODUCT_PART_ID         NUMBER(10, 0)     NOT NULL,
    SPECIES_CODE            VARCHAR2(32)      NOT NULL,
    REGION                  VARCHAR2(255),
    CERT_DOC_GROUP_ID       NUMBER(10, 0),
    BLEACHING_PROCESS_ID    NUMBER(10, 0)     NOT NULL,
    WRME_WOOD_TYPE_ID       NUMBER(10, 0)     NOT NULL,
    CERT_SCHEME_ID          NUMBER(10, 0)     NOT NULL,
    COUNTRY_CODE            VARCHAR2(8)       NOT NULL,
    OLD_FSCC_DESC           VARCHAR2(1000),
    CONSTRAINT PK28 PRIMARY KEY (PRODUCT_PART_ID)
)
;



-- 
-- TABLE: SUPPLIER.WOOD_PRODUCT_ANSWERS 
--

CREATE TABLE SUPPLIER.WOOD_PRODUCT_ANSWERS(
    PRODUCT_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK56 PRIMARY KEY (PRODUCT_ID)
)
;



-- 
-- TABLE: SUPPLIER.WRME_WOOD_TYPE 
--

CREATE TABLE SUPPLIER.WRME_WOOD_TYPE(
    WRME_WOOD_TYPE_ID        NUMBER(10, 0)     NOT NULL,
    DESCRIPTION              VARCHAR2(255)     NOT NULL,
    FACTOR_PER_METRIC_TON    NUMBER(10, 5)     NOT NULL,
    EXPLANATION              VARCHAR2(1024),
    CONSTRAINT PK95 PRIMARY KEY (WRME_WOOD_TYPE_ID)
)
;



-- 
-- TABLE: RECYC_FSCC_CS_MAP 
--

ALTER TABLE RECYC_FSCC_CS_MAP ADD CONSTRAINT FK_RECYC_CS_MAP 
    FOREIGN KEY (CERT_SCHEME_ID)
    REFERENCES SUPPLIER.CERT_SCHEME(CERT_SCHEME_ID)
;

ALTER TABLE RECYC_FSCC_CS_MAP ADD CONSTRAINT FK_RECYC_FSCC_MAP 
    FOREIGN KEY (FOREST_SOURCE_CAT_CODE)
    REFERENCES FOREST_SOURCE_CAT(FOREST_SOURCE_CAT_CODE)
;


-- 
-- TABLE: SUPPLIER.CERT_SCHEME 
--

ALTER TABLE SUPPLIER.CERT_SCHEME ADD CONSTRAINT FK_FSC_CS_NON_VERF 
    FOREIGN KEY (NON_VERIFIED_FSCC)
    REFERENCES FOREST_SOURCE_CAT(FOREST_SOURCE_CAT_CODE)
;

ALTER TABLE SUPPLIER.CERT_SCHEME ADD CONSTRAINT FK_FSC_CS_VERF 
    FOREIGN KEY (VERIFIED_FSCC)
    REFERENCES FOREST_SOURCE_CAT(FOREST_SOURCE_CAT_CODE)
;


-- 
-- TABLE: SUPPLIER.PRODUCT_PART 
--

ALTER TABLE SUPPLIER.PRODUCT_PART ADD CONSTRAINT RefALL_PRODUCT103 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES SUPPLIER.ALL_PRODUCT(PRODUCT_ID)
;

ALTER TABLE SUPPLIER.PRODUCT_PART ADD CONSTRAINT REFPRODUCT_PART40 
    FOREIGN KEY (PARENT_ID)
    REFERENCES SUPPLIER.PRODUCT_PART(PRODUCT_PART_ID)
;


-- 
-- TABLE: SUPPLIER.WOOD_PART_DESCRIPTION 
--

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFCERT_SCHEME135 
    FOREIGN KEY (POST_CERT_SCHEME_ID)
    REFERENCES SUPPLIER.CERT_SCHEME(CERT_SCHEME_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFCERT_SCHEME141 
    FOREIGN KEY (PRE_CERT_SCHEME_ID)
    REFERENCES SUPPLIER.CERT_SCHEME(CERT_SCHEME_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFCOUNTRY159 
    FOREIGN KEY (PRE_RECYCLED_COUNTRY_CODE)
    REFERENCES SUPPLIER.COUNTRY(COUNTRY_CODE)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFCOUNTRY160 
    FOREIGN KEY (POST_RECYCLED_COUNTRY_CODE)
    REFERENCES SUPPLIER.COUNTRY(COUNTRY_CODE)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFDOCUMENT_GROUP90 
    FOREIGN KEY (PRE_RECYCLED_DOC_GROUP_ID)
    REFERENCES SUPPLIER.DOCUMENT_GROUP(DOCUMENT_GROUP_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFDOCUMENT_GROUP91 
    FOREIGN KEY (POST_RECYCLED_DOC_GROUP_ID)
    REFERENCES SUPPLIER.DOCUMENT_GROUP(DOCUMENT_GROUP_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFPRODUCT_PART93 
    FOREIGN KEY (PRODUCT_PART_ID)
    REFERENCES SUPPLIER.PRODUCT_PART(PRODUCT_PART_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_DESCRIPTION ADD CONSTRAINT REFUNIT92 
    FOREIGN KEY (WEIGHT_UNIT_ID)
    REFERENCES SUPPLIER.UNIT(UNIT_ID)
;


-- 
-- TABLE: SUPPLIER.WOOD_PART_WOOD 
--

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT RefCOUNTRY140 
    FOREIGN KEY (COUNTRY_CODE)
    REFERENCES SUPPLIER.COUNTRY(COUNTRY_CODE)
;

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT FK_CS_WPW_CERT_ID 
    FOREIGN KEY (CERT_SCHEME_ID)
    REFERENCES SUPPLIER.CERT_SCHEME(CERT_SCHEME_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT REFBLEACHING_PROCESS104 
    FOREIGN KEY (BLEACHING_PROCESS_ID)
    REFERENCES SUPPLIER.BLEACHING_PROCESS(BLEACHING_PROCESS_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT REFDOCUMENT_GROUP96 
    FOREIGN KEY (CERT_DOC_GROUP_ID)
    REFERENCES SUPPLIER.DOCUMENT_GROUP(DOCUMENT_GROUP_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT REFPRODUCT_PART99 
    FOREIGN KEY (PRODUCT_PART_ID)
    REFERENCES SUPPLIER.PRODUCT_PART(PRODUCT_PART_ID)
;

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT REFTREE_SPECIES103 
    FOREIGN KEY (SPECIES_CODE)
    REFERENCES SUPPLIER.TREE_SPECIES(SPECIES_CODE)
;

ALTER TABLE SUPPLIER.WOOD_PART_WOOD ADD CONSTRAINT REFWRME_WOOD_TYPE128 
    FOREIGN KEY (WRME_WOOD_TYPE_ID)
    REFERENCES SUPPLIER.WRME_WOOD_TYPE(WRME_WOOD_TYPE_ID)
;


-- 
-- TABLE: SUPPLIER.WOOD_PRODUCT_ANSWERS 
--

ALTER TABLE SUPPLIER.WOOD_PRODUCT_ANSWERS ADD CONSTRAINT REFALL_PRODUCT121 
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES SUPPLIER.ALL_PRODUCT(PRODUCT_ID)
;


