-- Please update version.sql too -- this keeps clean builds in sync
define version=2815
define minor_version=26
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
ALTER TABLE CSRIMP.CHAIN_BU_REL_TIE_COM_TYP DROP COLUMN BUSINESS_RELATIONSHIP_TYPE_ID;

ALTER TABLE cms.debug_ddl_log ADD csrimp_session_id	NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID'); 
ALTER TABLE cms.debug_ddl_log ADD processed_dtm	DATE; 
ALTER TABLE cms.debug_ddl_log ADD CONSTRAINT fk_debug_ddl_log FOREIGN KEY (csrimp_session_id)
	REFERENCES csrimp.csrimp_session (csrimp_session_id)
	ON DELETE CASCADE;

--(auto-gen)add CSRIMP_SESSION_ID tp PK/UC
ALTER TABLE CSRIMP.ASPEN2_TRANSLATED DROP constraint PK_ASPEN2_TRANSLATED DROP INDEX;
ALTER TABLE CSRIMP.ASPEN2_TRANSLATED ADD constraint PK_ASPEN2_TRANSLATED PRIMARY KEY (CSRIMP_SESSION_ID,LANG,ORIGINAL_HASH);
ALTER TABLE CSRIMP.ASPEN2_TRANSLATION DROP constraint PK_ASPEN2_TRANSLATION DROP INDEX;
ALTER TABLE CSRIMP.ASPEN2_TRANSLATION ADD constraint PK_ASPEN2_TRANSLATION PRIMARY KEY (CSRIMP_SESSION_ID,ORIGINAL_HASH);
ALTER TABLE CSRIMP.ASPEN2_TRANSLATION_SET DROP constraint PK_ASPEN2_TRANSLATION_SET DROP INDEX;
ALTER TABLE CSRIMP.ASPEN2_TRANSLATION_SET ADD constraint PK_ASPEN2_TRANSLATION_SET PRIMARY KEY (CSRIMP_SESSION_ID,LANG);
ALTER TABLE CSRIMP.ASPEN2_TRANSLATION_SET_INCL DROP constraint PK_ASPEN2_TRANS_SET_INCL DROP INDEX;
ALTER TABLE CSRIMP.ASPEN2_TRANSLATION_SET_INCL ADD constraint PK_ASPEN2_TRANS_SET_INCL PRIMARY KEY (CSRIMP_SESSION_ID,LANG,POS);
ALTER TABLE CSRIMP.MAP_CHAIN_BUSINE_RELATIO DROP constraint PK_MAP_CHAIN_BUSINE_RELATIO DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_BUSINE_RELATIO ADD constraint PK_MAP_CHAIN_BUSINE_RELATIO PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BUSINESS_RELATIONSHIP_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_BUSINE_RELATIO DROP constraint UK_MAP_CHAIN_BUSINE_RELATIO DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_BUSINE_RELATIO ADD constraint UK_MAP_CHAIN_BUSINE_RELATIO UNIQUE (CSRIMP_SESSION_ID,NEW_BUSINESS_RELATIONSHIP_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TIER DROP constraint PK_MAP_CHAIN_BUSIN_REL_TIER DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TIER ADD constraint PK_MAP_CHAIN_BUSIN_REL_TIER PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BUSINESS_REL_TIER_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TIER DROP constraint UK_MAP_CHAIN_BUSIN_REL_TIER DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TIER ADD constraint UK_MAP_CHAIN_BUSIN_REL_TIER UNIQUE (CSRIMP_SESSION_ID,NEW_BUSINESS_REL_TIER_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TYPE DROP constraint PK_MAP_CHAIN_BUSIN_REL_TYPE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TYPE ADD constraint PK_MAP_CHAIN_BUSIN_REL_TYPE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BUSINESS_REL_TYPE_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TYPE DROP constraint UK_MAP_CHAIN_BUSIN_REL_TYPE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_BUSIN_REL_TYPE ADD constraint UK_MAP_CHAIN_BUSIN_REL_TYPE UNIQUE (CSRIMP_SESSION_ID,NEW_BUSINESS_REL_TYPE_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_PRODUCT_TYPE DROP constraint PK_MAP_CHAIN_PRODUCT_TYPE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_PRODUCT_TYPE ADD constraint PK_MAP_CHAIN_PRODUCT_TYPE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_PRODUCT_TYPE_ID);
ALTER TABLE CSRIMP.MAP_CHAIN_PRODUCT_TYPE DROP constraint UK_MAP_CHAIN_PRODUCT_TYPE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHAIN_PRODUCT_TYPE ADD constraint UK_MAP_CHAIN_PRODUCT_TYPE UNIQUE (CSRIMP_SESSION_ID,NEW_PRODUCT_TYPE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_CAS_GROUP DROP constraint PK_MAP_CHEM_CAS_GROUP DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_CAS_GROUP ADD constraint PK_MAP_CHEM_CAS_GROUP PRIMARY KEY (CSRIMP_SESSION_ID,OLD_CAS_GROUP_ID);
ALTER TABLE CSRIMP.MAP_CHEM_CAS_GROUP DROP constraint UK_MAP_CHEM_CAS_GROUP DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_CAS_GROUP ADD constraint UK_MAP_CHEM_CAS_GROUP UNIQUE (CSRIMP_SESSION_ID,NEW_CAS_GROUP_ID);
ALTER TABLE CSRIMP.MAP_CHEM_CLASSIFICATION DROP constraint PK_MAP_CHEM_CLASSIFICATION DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_CLASSIFICATION ADD constraint PK_MAP_CHEM_CLASSIFICATION PRIMARY KEY (CSRIMP_SESSION_ID,OLD_CLASSIFICATION_ID);
ALTER TABLE CSRIMP.MAP_CHEM_CLASSIFICATION DROP constraint UK_MAP_CHEM_CLASSIFICATION DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_CLASSIFICATION ADD constraint UK_MAP_CHEM_CLASSIFICATION UNIQUE (CSRIMP_SESSION_ID,NEW_CLASSIFICATION_ID);
ALTER TABLE CSRIMP.MAP_CHEM_MANUFACTURER DROP constraint PK_MAP_CHEM_MANUFACTURER DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_MANUFACTURER ADD constraint PK_MAP_CHEM_MANUFACTURER PRIMARY KEY (CSRIMP_SESSION_ID,OLD_MANUFACTURER_ID);
ALTER TABLE CSRIMP.MAP_CHEM_MANUFACTURER DROP constraint UK_MAP_CHEM_MANUFACTURER DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_MANUFACTURER ADD constraint UK_MAP_CHEM_MANUFACTURER UNIQUE (CSRIMP_SESSION_ID,NEW_MANUFACTURER_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE DROP constraint PK_MAP_CHEM_SUBSTANCE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE ADD constraint PK_MAP_CHEM_SUBSTANCE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBSTANCE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE DROP constraint UK_MAP_CHEM_SUBSTANCE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE ADD constraint UK_MAP_CHEM_SUBSTANCE UNIQUE (CSRIMP_SESSION_ID,NEW_SUBSTANCE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE_FILE DROP constraint PK_MAP_CHEM_SUBSTANCE_FILE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE_FILE ADD constraint PK_MAP_CHEM_SUBSTANCE_FILE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBSTANCE_FILE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE_FILE DROP constraint UK_MAP_CHEM_SUBSTANCE_FILE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUBSTANCE_FILE ADD constraint UK_MAP_CHEM_SUBSTANCE_FILE UNIQUE (CSRIMP_SESSION_ID,NEW_SUBSTANCE_FILE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUBST_PROCE_USE DROP constraint PK_MAP_CHEM_SUBST_PROCE_USE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUBST_PROCE_USE ADD constraint PK_MAP_CHEM_SUBST_PROCE_USE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBSTANCE_PROCESS_USE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUBST_PROCE_USE DROP constraint UK_MAP_CHEM_SUBST_PROCE_USE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUBST_PROCE_USE ADD constraint UK_MAP_CHEM_SUBST_PROCE_USE UNIQUE (CSRIMP_SESSION_ID,NEW_SUBSTANCE_PROCESS_USE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_AUDIT_LOG DROP constraint PK_MAP_CHEM_SUB_AUDIT_LOG DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_AUDIT_LOG ADD constraint PK_MAP_CHEM_SUB_AUDIT_LOG PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUB_AUDIT_LOG_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_AUDIT_LOG DROP constraint UK_MAP_CHEM_SUB_AUDIT_LOG DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_AUDIT_LOG ADD constraint UK_MAP_CHEM_SUB_AUDIT_LOG UNIQUE (CSRIMP_SESSION_ID,NEW_SUB_AUDIT_LOG_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_CHA DROP constraint PK_MAP_CHEM_SUB_PRO_USE_CHA DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_CHA ADD constraint PK_MAP_CHEM_SUB_PRO_USE_CHA PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBST_PROC_USE_CHANGE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_CHA DROP constraint UK_MAP_CHEM_SUB_PRO_USE_CHA DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_CHA ADD constraint UK_MAP_CHEM_SUB_PRO_USE_CHA UNIQUE (CSRIMP_SESSION_ID,NEW_SUBST_PROC_USE_CHANGE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_FIL DROP constraint PK_MAP_CHEM_SUB_PRO_USE_FIL DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_FIL ADD constraint PK_MAP_CHEM_SUB_PRO_USE_FIL PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBST_PROC_USE_FILE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_FIL DROP constraint UK_MAP_CHEM_SUB_PRO_USE_FIL DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_PRO_USE_FIL ADD constraint UK_MAP_CHEM_SUB_PRO_USE_FIL UNIQUE (CSRIMP_SESSION_ID,NEW_SUBST_PROC_USE_FILE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_RGN_PRO_PRO DROP constraint PK_MAP_CHEM_SUB_RGN_PRO_PRO DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_RGN_PRO_PRO ADD constraint PK_MAP_CHEM_SUB_RGN_PRO_PRO PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBST_RGN_PROC_PROCESS_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SUB_RGN_PRO_PRO DROP constraint UK_MAP_CHEM_SUB_RGN_PRO_PRO DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SUB_RGN_PRO_PRO ADD constraint UK_MAP_CHEM_SUB_RGN_PRO_PRO UNIQUE (CSRIMP_SESSION_ID,NEW_SUBST_RGN_PROC_PROCESS_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SU_PR_CA_DE_CHG DROP constraint PK_MAP_CHEM_SU_PR_CA_DE_CHG DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SU_PR_CA_DE_CHG ADD constraint PK_MAP_CHEM_SU_PR_CA_DE_CHG PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUBST_PROC_CAS_DEST_CHG_ID);
ALTER TABLE CSRIMP.MAP_CHEM_SU_PR_CA_DE_CHG DROP constraint UK_MAP_CHEM_SU_PR_CA_DE_CHG DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_SU_PR_CA_DE_CHG ADD constraint UK_MAP_CHEM_SU_PR_CA_DE_CHG UNIQUE (CSRIMP_SESSION_ID,NEW_SUBST_PROC_CAS_DEST_CHG_ID);
ALTER TABLE CSRIMP.MAP_CHEM_USAGE DROP constraint PK_MAP_CHEM_USAGE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_USAGE ADD constraint PK_MAP_CHEM_USAGE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_USAGE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_USAGE DROP constraint UK_MAP_CHEM_USAGE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_USAGE ADD constraint UK_MAP_CHEM_USAGE UNIQUE (CSRIMP_SESSION_ID,NEW_USAGE_ID);
ALTER TABLE CSRIMP.MAP_CHEM_USAGE_AUDIT_LOG DROP constraint PK_MAP_CHEM_USAGE_AUDIT_LOG DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_USAGE_AUDIT_LOG ADD constraint PK_MAP_CHEM_USAGE_AUDIT_LOG PRIMARY KEY (CSRIMP_SESSION_ID,OLD_USAGE_AUDIT_LOG_ID);
ALTER TABLE CSRIMP.MAP_CHEM_USAGE_AUDIT_LOG DROP constraint UK_MAP_CHEM_USAGE_AUDIT_LOG DROP INDEX;
ALTER TABLE CSRIMP.MAP_CHEM_USAGE_AUDIT_LOG ADD constraint UK_MAP_CHEM_USAGE_AUDIT_LOG UNIQUE (CSRIMP_SESSION_ID,NEW_USAGE_AUDIT_LOG_ID);
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN DROP constraint PK_MAP_CT_BREAKDOWN DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN ADD constraint PK_MAP_CT_BREAKDOWN PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BREAKDOWN_ID);
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN DROP constraint UK_MAP_CT_BREAKDOWN DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN ADD constraint UK_MAP_CT_BREAKDOWN UNIQUE (CSRIMP_SESSION_ID,NEW_BREAKDOWN_ID);
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_GROUP DROP constraint PK_MAP_CT_BREAKDOWN_GROUP DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_GROUP ADD constraint PK_MAP_CT_BREAKDOWN_GROUP PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BREAKDOWN_GROUP_ID);
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_GROUP DROP constraint UK_MAP_CT_BREAKDOWN_GROUP DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_GROUP ADD constraint UK_MAP_CT_BREAKDOWN_GROUP UNIQUE (CSRIMP_SESSION_ID,NEW_BREAKDOWN_GROUP_ID);
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_TYPE DROP constraint PK_MAP_CT_BREAKDOWN_TYPE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_TYPE ADD constraint PK_MAP_CT_BREAKDOWN_TYPE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BREAKDOWN_TYPE_ID);
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_TYPE DROP constraint UK_MAP_CT_BREAKDOWN_TYPE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BREAKDOWN_TYPE ADD constraint UK_MAP_CT_BREAKDOWN_TYPE UNIQUE (CSRIMP_SESSION_ID,NEW_BREAKDOWN_TYPE_ID);
ALTER TABLE CSRIMP.MAP_CT_BT_TRIP_ENTRY DROP constraint PK_MAP_CT_BT_TRIP_ENTRY DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BT_TRIP_ENTRY ADD constraint PK_MAP_CT_BT_TRIP_ENTRY PRIMARY KEY (CSRIMP_SESSION_ID,OLD_BT_TRIP_ENTRY_ID);
ALTER TABLE CSRIMP.MAP_CT_BT_TRIP_ENTRY DROP constraint UK_MAP_CT_BT_TRIP_ENTRY DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_BT_TRIP_ENTRY ADD constraint UK_MAP_CT_BT_TRIP_ENTRY UNIQUE (CSRIMP_SESSION_ID,NEW_BT_TRIP_ENTRY_ID);
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNAIRE DROP constraint PK_MAP_CT_EC_QUESTIONNAIRE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNAIRE ADD constraint PK_MAP_CT_EC_QUESTIONNAIRE PRIMARY KEY (CSRIMP_SESSION_ID,OLD_EC_QUESTIONNAIRE_ID);
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNAIRE DROP constraint UK_MAP_CT_EC_QUESTIONNAIRE DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNAIRE ADD constraint UK_MAP_CT_EC_QUESTIONNAIRE UNIQUE (CSRIMP_SESSION_ID,NEW_EC_QUESTIONNAIRE_ID);
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNA_ANS DROP constraint PK_MAP_CT_EC_QUESTIONNA_ANS DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNA_ANS ADD constraint PK_MAP_CT_EC_QUESTIONNA_ANS PRIMARY KEY (CSRIMP_SESSION_ID,OLD_EC_QUESTIONNAIRE_ANS_ID);
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNA_ANS DROP constraint UK_MAP_CT_EC_QUESTIONNA_ANS DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_EC_QUESTIONNA_ANS ADD constraint UK_MAP_CT_EC_QUESTIONNA_ANS UNIQUE (CSRIMP_SESSION_ID,NEW_EC_QUESTIONNAIRE_ANS_ID);
ALTER TABLE CSRIMP.MAP_CT_PS_ITEM DROP constraint PK_MAP_CT_PS_ITEM DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_PS_ITEM ADD constraint PK_MAP_CT_PS_ITEM PRIMARY KEY (CSRIMP_SESSION_ID,OLD_PS_ITEM_ID);
ALTER TABLE CSRIMP.MAP_CT_PS_ITEM DROP constraint UK_MAP_CT_PS_ITEM DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_PS_ITEM ADD constraint UK_MAP_CT_PS_ITEM UNIQUE (CSRIMP_SESSION_ID,NEW_PS_ITEM_ID);
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER DROP constraint PK_MAP_CT_SUPPLIER DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER ADD constraint PK_MAP_CT_SUPPLIER PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUPPLIER_ID);
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER DROP constraint UK_MAP_CT_SUPPLIER DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER ADD constraint UK_MAP_CT_SUPPLIER UNIQUE (CSRIMP_SESSION_ID,NEW_SUPPLIER_ID);
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER_CONTACT DROP constraint PK_MAP_CT_SUPPLIER_CONTACT DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER_CONTACT ADD constraint PK_MAP_CT_SUPPLIER_CONTACT PRIMARY KEY (CSRIMP_SESSION_ID,OLD_SUPPLIER_CONTACT_ID);
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER_CONTACT DROP constraint UK_MAP_CT_SUPPLIER_CONTACT DROP INDEX;
ALTER TABLE CSRIMP.MAP_CT_SUPPLIER_CONTACT ADD constraint UK_MAP_CT_SUPPLIER_CONTACT UNIQUE (CSRIMP_SESSION_ID,NEW_SUPPLIER_CONTACT_ID);
ALTER TABLE CSRIMP.MAP_CUSTOMER_FLOW_CAP DROP constraint PK_MAP_CUSTOMER_FLOW_CAP DROP INDEX;
ALTER TABLE CSRIMP.MAP_CUSTOMER_FLOW_CAP ADD constraint PK_MAP_CUSTOMER_FLOW_CAP PRIMARY KEY (CSRIMP_SESSION_ID,OLD_CUSTOMER_FLOW_CAP_ID);
ALTER TABLE CSRIMP.MAP_CUSTOMER_FLOW_CAP DROP constraint UK_MAP_CUSTOMER_FLOW_CAP DROP INDEX;
ALTER TABLE CSRIMP.MAP_CUSTOMER_FLOW_CAP ADD constraint UK_MAP_CUSTOMER_FLOW_CAP UNIQUE (CSRIMP_SESSION_ID,NEW_CUSTOMER_FLOW_CAP_ID);
ALTER TABLE CSRIMP.MAP_DELEGATION_LAYOUT DROP constraint PK_MAP_DELEGATION_LAYOUT DROP INDEX;
ALTER TABLE CSRIMP.MAP_DELEGATION_LAYOUT ADD constraint PK_MAP_DELEGATION_LAYOUT PRIMARY KEY (CSRIMP_SESSION_ID,OLD_DELEGATION_LAYOUT_ID);
ALTER TABLE CSRIMP.MAP_DELEGATION_LAYOUT DROP constraint UK_MAP_DELEGATION_LAYOUT DROP INDEX;
ALTER TABLE CSRIMP.MAP_DELEGATION_LAYOUT ADD constraint UK_MAP_DELEGATION_LAYOUT UNIQUE (CSRIMP_SESSION_ID,NEW_DELEGATION_LAYOUT_ID);
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY DROP constraint PK_MAP_IA_TYPE_SURVEY DROP INDEX;
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY ADD constraint PK_MAP_IA_TYPE_SURVEY PRIMARY KEY (CSRIMP_SESSION_ID,OLD_IA_TYPE_SURVEY_ID);
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY DROP constraint UK_MAP_IA_TYPE_SURVEY DROP INDEX;
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY ADD constraint UK_MAP_IA_TYPE_SURVEY UNIQUE (CSRIMP_SESSION_ID,NEW_IA_TYPE_SURVEY_ID);
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY_GROUP DROP constraint PK_MAP_IA_TYPE_SURVEY_GROUP DROP INDEX;
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY_GROUP ADD constraint PK_MAP_IA_TYPE_SURVEY_GROUP PRIMARY KEY (CSRIMP_SESSION_ID,OLD_IA_TYPE_SURVEY_GROUP_ID);
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY_GROUP DROP constraint UK_MAP_IA_TYPE_SURVEY_GROUP DROP INDEX;
ALTER TABLE CSRIMP.MAP_IA_TYPE_SURVEY_GROUP ADD constraint UK_MAP_IA_TYPE_SURVEY_GROUP UNIQUE (CSRIMP_SESSION_ID,NEW_IA_TYPE_SURVEY_GROUP_ID);

-- csrimp.map_plugin_type was missing from csr/db/csrimp/map_tables.sql
DECLARE
	v_count			NUMBER;
BEGIN
	SELECT COUNT(*)
	  INTO v_count
	  FROM all_tables
	 WHERE UPPER(owner) = 'CSRIMP'
	   AND UPPER(table_name) = 'MAP_PLUGIN_TYPE';
	
	IF v_count = 0 THEN
		EXECUTE IMMEDIATE
			'CREATE TABLE csrimp.map_plugin_type ('||
			'    CSRIMP_SESSION_ID		NUMBER(10) DEFAULT SYS_CONTEXT(''SECURITY'', ''CSRIMP_SESSION_ID'') NOT NULL,'||
			'    old_plugin_type_id		NUMBER(10) NOT NULL,'||
			'    new_plugin_type_id		NUMBER(10) NOT NULL,'||
			'    CONSTRAINT pk_map_plugin_type_id PRIMARY KEY (csrimp_session_id, old_plugin_type_id) USING INDEX,'||
			'    CONSTRAINT uk_map_plugin_type_id UNIQUE (csrimp_session_id, new_plugin_type_id) USING INDEX,'||
			'    CONSTRAINT fk_map_plugin_type_is FOREIGN KEY'||
			'        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)'||
			'        ON DELETE CASCADE'||
			')';
	ELSE
		EXECUTE IMMEDIATE 'ALTER TABLE CSRIMP.MAP_PLUGIN_TYPE DROP constraint PK_MAP_PLUGIN_TYPE_ID DROP INDEX';
		EXECUTE IMMEDIATE 'ALTER TABLE CSRIMP.MAP_PLUGIN_TYPE ADD constraint PK_MAP_PLUGIN_TYPE_ID PRIMARY KEY (CSRIMP_SESSION_ID,OLD_PLUGIN_TYPE_ID)';
		EXECUTE IMMEDIATE 'ALTER TABLE CSRIMP.MAP_PLUGIN_TYPE DROP constraint UK_MAP_PLUGIN_TYPE_ID DROP INDEX';
		EXECUTE IMMEDIATE 'ALTER TABLE CSRIMP.MAP_PLUGIN_TYPE ADD constraint UK_MAP_PLUGIN_TYPE_ID UNIQUE (CSRIMP_SESSION_ID,NEW_PLUGIN_TYPE_ID)';
	END IF;
END;
/


-- *** Functions ***
DROP FUNCTION aspen2.to_string;
-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please add the path to the create_views file which will contain your view changes.  I will use this version when making the major scripts.

-- *** Data changes ***
-- RLS
DECLARE
	FEATURE_NOT_ENABLED EXCEPTION;
	PRAGMA EXCEPTION_INIT(FEATURE_NOT_ENABLED, -439);
    POLICY_ALREADY_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(POLICY_ALREADY_EXISTS, -28101);
BEGIN
 	FOR r IN (
		SELECT c.owner, c.table_name, c.nullable, (SUBSTR(c.table_name, 1, 26) || '_POL') policy_name
		  FROM all_tables t
		  JOIN all_tab_columns c ON t.owner = c.owner AND t.table_name = c.table_name
		 WHERE t.owner IN ('CMS') AND (t.dropped = 'NO' OR t.dropped IS NULL) AND c.column_name = 'CSRIMP_SESSION_ID'
		   AND t.table_name IN (
				'DEBUG_DDL_LOG'
		   )
 	)
 	LOOP
		dbms_output.put_line('Writing policy '||r.policy_name);
		dbms_rls.add_policy(
			object_schema   => r.owner,
			object_name     => r.table_name,
			policy_name     => r.policy_name, 
			function_schema => 'CMS',
			policy_function => 'SessionIDCheck',
			statement_types => 'select, insert, update, delete',
			update_check	=> true,
			policy_type     => dbms_rls.context_sensitive);
	END LOOP;
EXCEPTION
	WHEN POLICY_ALREADY_EXISTS THEN
		DBMS_OUTPUT.PUT_LINE('Policy exists');
	WHEN FEATURE_NOT_ENABLED THEN
		DBMS_OUTPUT.PUT_LINE('RLS policies not applied as feature not enabled');
END;
/

-- Data

-- ** New package grants **

-- *** Packages ***
@../../../aspen2/cms/db/tab_body
@../csrimp/imp_body

@update_tail
