-- Please update version.sql too -- this keeps clean builds in sync
define version=3218
define minor_version=1
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables

ALTER TABLE csr.tpl_report_tag DROP CONSTRAINT ct_tpl_report_tag;
ALTER TABLE CSR.TPL_REPORT_TAG ADD (
	CONSTRAINT CT_TPL_REPORT_TAG CHECK (
		(TAG_TYPE IN (1,4,5,14) AND TPL_REPORT_TAG_IND_ID IS NOT NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 6 AND TPL_REPORT_TAG_EVAL_ID IS NOT NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE IN (2,3,101) AND TPL_REPORT_TAG_DATAVIEW_ID IS NOT NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 7 AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NOT NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 8 AND TPL_REP_CUST_TAG_TYPE_ID IS NOT NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 9 AND TPL_REPORT_TAG_TEXT_ID IS NOT NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = -1 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 10 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NOT NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 11 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NOT NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 102 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NOT NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 103 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NOT NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 12 AND TPL_REPORT_TAG_QC_ID IS NOT NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 13 AND TPL_REPORT_TAG_SUGGESTION_ID IS NOT NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL)
	)
);

ALTER TABLE csrimp.tpl_report_tag DROP CONSTRAINT ct_tpl_report_tag;
ALTER TABLE CSRIMP.TPL_REPORT_TAG ADD (
	CONSTRAINT CT_TPL_REPORT_TAG CHECK (
		(TAG_TYPE IN (1,4,5,14) AND TPL_REPORT_TAG_IND_ID IS NOT NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 6 AND TPL_REPORT_TAG_EVAL_ID IS NOT NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE IN (2,3,101) AND TPL_REPORT_TAG_DATAVIEW_ID IS NOT NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 7 AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NOT NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 8 AND TPL_REP_CUST_TAG_TYPE_ID IS NOT NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 9 AND TPL_REPORT_TAG_TEXT_ID IS NOT NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = -1 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 10 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NOT NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 11 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NOT NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 102 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NOT NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 103 AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NOT NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 12 AND TPL_REPORT_TAG_QC_ID IS NOT NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL AND TPL_REPORT_TAG_SUGGESTION_ID IS NULL)
		OR (TAG_TYPE = 13 AND TPL_REPORT_TAG_SUGGESTION_ID IS NOT NULL AND TPL_REPORT_TAG_DATAVIEW_ID IS NULL AND TPL_REPORT_TAG_IND_ID IS NULL AND TPL_REPORT_TAG_EVAL_ID IS NULL AND TPL_REPORT_TAG_LOGGING_FORM_ID IS NULL AND TPL_REP_CUST_TAG_TYPE_ID IS NULL AND TPL_REPORT_TAG_TEXT_ID IS NULL AND TPL_REPORT_NON_COMPL_ID IS NULL AND TPL_REPORT_TAG_APP_NOTE_ID IS NULL AND TPL_REPORT_TAG_APP_MATRIX_ID IS NULL AND TPL_REPORT_TAG_REG_DATA_ID IS NULL)
	)
);

ALTER TABLE CSR.TPL_REPORT_TAG_IND ADD (SHOW_FULL_PATH NUMBER(1) DEFAULT 0 NOT NULL);
ALTER TABLE CSR.TPL_REPORT_TAG_IND ADD CONSTRAINT CHK_TPL_RPT_TAG_IND_SFP CHECK (SHOW_FULL_PATH IN (1,0));

ALTER TABLE CSRIMP.TPL_REPORT_TAG_IND ADD (SHOW_FULL_PATH NUMBER(1) NOT NULL);
ALTER TABLE CSRIMP.TPL_REPORT_TAG_IND ADD CONSTRAINT CHK_TPL_RPT_TAG_IND_SFP CHECK (SHOW_FULL_PATH IN (1,0));

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../templated_report_pkg

@../schema_body
@../templated_report_body
@../csrimp/imp_body

@update_tail
