--Please update version.sql too -- this keeps clean builds in sync
define version=2722
@update_header

ALTER TABLE CSR.PROJECT_TAG_GROUP ADD(
	DEFAULT_TAG_ID    NUMBER(10, 0)
);

ALTER TABLE CSR.PROJECT_TAG_GROUP ADD CONSTRAINT FK_TAGGRPMBR_PRJTAGGRP 
    FOREIGN KEY (APP_SID, TAG_GROUP_ID, DEFAULT_TAG_ID)
    REFERENCES CSR.TAG_GROUP_MEMBER(APP_SID, TAG_GROUP_ID, TAG_ID)
;

ALTER TABLE CSR.AGGR_TAG_GROUP ADD(
	COUNT_IND_SID        NUMBER(10, 0)
);

ALTER TABLE CSR.AGGR_TAG_GROUP ADD CONSTRAINT FK_IND_AGGR_TAG_GROUP 
    FOREIGN KEY (APP_SID, COUNT_IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE CSR.FLOW_STATE_GROUP ADD(
	COUNT_IND_SID        NUMBER(10, 0)
);

ALTER TABLE CSR.FLOW_STATE_GROUP ADD CONSTRAINT FK_IND_FLOW_STATE_GROUP 
    FOREIGN KEY (APP_SID, COUNT_IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

CREATE INDEX CSR.IX_TAGGRPMBR_PRJTAGGRP ON CSR.PROJECT_TAG_GROUP (APP_SID, TAG_GROUP_ID, DEFAULT_TAG_ID);
CREATE INDEX CSR.IX_IND_AGGR_TAG_GROUP ON CSR.AGGR_TAG_GROUP (APP_SID, COUNT_IND_SID);
CREATE INDEX CSR.IX_IND_FLOW_STATE_GROUP ON CSR.FLOW_STATE_GROUP (APP_SID, COUNT_IND_SID);

@../initiative_project_body
@../initiative_aggr_body

@update_tail
