-- Please update version.sql too -- this keeps clean builds in sync
define version=3200
define minor_version=8
@update_header

-- *** DDL ***
-- Create tables

CREATE SEQUENCE CSR.SYS_TRANS_AUDIT_LOG_SEQ
;

CREATE TABLE CSR.SYS_TRANSLATIONS_AUDIT_LOG(
	SYS_TRANSLATIONS_AUDIT_LOG_ID	NUMBER(10)        NOT NULL,
	AUDIT_DATE						DATE DEFAULT      SYSDATE NOT NULL,
	APP_SID							NUMBER(10,0)      DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	TRANSLATED_ID					NUMBER(10,0)      NOT NULL,
	USER_SID						NUMBER(10,0)      NOT NULL,
	DESCRIPTION						VARCHAR2(4000)    NOT NULL,
	CONSTRAINT PK_SYS_TRANS_AUDIT_LOG PRIMARY KEY (SYS_TRANSLATIONS_AUDIT_LOG_ID)
)
;

CREATE TABLE CSRIMP.SYS_TRANSLATIONS_AUDIT_LOG(
	CSRIMP_SESSION_ID				NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	SYS_TRANSLATIONS_AUDIT_LOG_ID	NUMBER(10)			NOT NULL,
	AUDIT_DATE						DATE DEFAULT		SYSDATE NOT NULL,
	APP_SID							NUMBER(10,0)		DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	TRANSLATED_ID					NUMBER(10,0)		NOT NULL,
	USER_SID						NUMBER(10,0)		NOT NULL,
	DESCRIPTION						VARCHAR2(4000)		NOT NULL,
	CONSTRAINT PK_SYS_TRANS_AUDIT_LOG PRIMARY KEY (CSRIMP_SESSION_ID, SYS_TRANSLATIONS_AUDIT_LOG_ID),
	CONSTRAINT FK_SYS_TRANS_AUDIT_LOG FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
)
;

CREATE TABLE CSRIMP.MAP_SYS_TRANS_AUDIT_LOG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_SYS_TRANS_AUDIT_LOG_ID NUMBER(10) NOT NULL,
	NEW_SYS_TRANS_AUDIT_LOG_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_SYS_TRANS_AUDIT_LOG PRIMARY KEY (CSRIMP_SESSION_ID, OLD_SYS_TRANS_AUDIT_LOG_ID) USING INDEX,
	CONSTRAINT UK_MAP_SYS_TRANS_AUDIT_LOG UNIQUE (CSRIMP_SESSION_ID, NEW_SYS_TRANS_AUDIT_LOG_ID) USING INDEX,
	CONSTRAINT FK_MAP_SYS_TRANS_AUDIT_LOG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
)
;

-- Alter tables

-- *** Grants ***
GRANT SELECT, UPDATE, DELETE ON aspen2.translated TO csr;
GRANT SELECT, DELETE ON aspen2.translation TO csr;
GRANT SELECT ON csr.sys_trans_audit_log_seq to csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.sys_translations_audit_log TO csrimp;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.sys_translations_audit_log TO tool_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../customer_pkg
@../schema_pkg

@../customer_body
@../csr_app_body
@../csrimp/imp_body
@../schema_body
@update_tail
