-- Please update version.sql too -- this keeps clean builds in sync
define version=1456
@update_header

CREATE TABLE CSR.REGION_METRIC(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    MEASURE_SID              NUMBER(10, 0)    NOT NULL,
    MEASURE_CONVERSION_ID    NUMBER(10, 0),
    LOOKUP_KEY               VARCHAR2(256)    NOT NULL,
    IND_SID                  NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_REGION_METRIC PRIMARY KEY (APP_SID, IND_SID)
);

CREATE TABLE CSR.REGION_METRIC_VAL(
    APP_SID           NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SID        NUMBER(10, 0)     NOT NULL,
    IND_SID           NUMBER(10, 0)     NOT NULL,
    EFFECTIVE_DTM     DATE              NOT NULL,
    ENTERED_BY_SID    NUMBER(10, 0)     NOT NULL,
    ENTERED_DTM       DATE              NOT NULL,
    VAL               NUMBER(24, 10),
    NOTE              VARCHAR2(4000),
    CONSTRAINT PK_REGION_METRIC_VAL PRIMARY KEY (APP_SID, REGION_SID, IND_SID, EFFECTIVE_DTM)
);

CREATE TABLE CSR.REGION_TYPE_METRIC(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_TYPE    NUMBER(2, 0)     NOT NULL,
    IND_SID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_REGION_TYPE_METRIC PRIMARY KEY (APP_SID, REGION_TYPE, IND_SID)
);


ALTER TABLE CSR.REGION_METRIC ADD CONSTRAINT FK_CONV_REGION_METRIC
    FOREIGN KEY (APP_SID, MEASURE_CONVERSION_ID, MEASURE_SID)
    REFERENCES CSR.MEASURE_CONVERSION(APP_SID, MEASURE_CONVERSION_ID, MEASURE_SID)
;

ALTER TABLE CSR.REGION_METRIC ADD CONSTRAINT FK_CUST_REGION_METRIC 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.REGION_METRIC ADD CONSTRAINT FK_IND_REGION_METRIC 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE CSR.REGION_METRIC ADD CONSTRAINT FK_INDM_REGION_METRIC 
    FOREIGN KEY (APP_SID, IND_SID, MEASURE_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID, MEASURE_SID)
;

ALTER TABLE CSR.REGION_METRIC ADD CONSTRAINT FK_MEASURE_REGION_METRIC 
    FOREIGN KEY (APP_SID, MEASURE_SID)
    REFERENCES CSR.MEASURE(APP_SID, MEASURE_SID)
;

ALTER TABLE CSR.REGION_METRIC_VAL ADD CONSTRAINT FK_REGION_RMETRIC_VAL 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.REGION_METRIC_VAL ADD CONSTRAINT FK_RMETRIC_RMETRIC_VAL 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.REGION_METRIC(APP_SID, IND_SID)
;

ALTER TABLE CSR.REGION_METRIC_VAL ADD CONSTRAINT FK_RTYPE_RMETRIC_VAL 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.REGION_METRIC_VAL ADD CONSTRAINT FK_USER_RMETRIC_VAL 
    FOREIGN KEY (APP_SID, ENTERED_BY_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE CSR.REGION_TYPE_METRIC ADD CONSTRAINT FK_CUST_RTYPE_RTYPE_METRIC 
    FOREIGN KEY (APP_SID, REGION_TYPE)
    REFERENCES CSR.CUSTOMER_REGION_TYPE(APP_SID, REGION_TYPE)
;

ALTER TABLE CSR.REGION_TYPE_METRIC ADD CONSTRAINT FK_RMETRIC_RTYPE_METRIC 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.REGION_METRIC(APP_SID, IND_SID)
;

CREATE INDEX CSR.IX_CONV_REGION_METRIC ON CSR.REGION_METRIC (APP_SID, MEASURE_CONVERSION_ID, MEASURE_SID);
CREATE INDEX CSR.IX_CUST_REGION_METRIC ON CSR.REGION_METRIC (APP_SID);
CREATE INDEX CSR.IX_INDM_REGION_METRIC ON CSR.REGION_METRIC (APP_SID, IND_SID, MEASURE_SID);
CREATE INDEX CSR.IX_MEASURE_REGION_METRIC ON CSR.REGION_METRIC (APP_SID, MEASURE_SID);
CREATE INDEX CSR.IX_REGION_RMETRIC_VAL ON CSR.REGION_METRIC_VAL (APP_SID, REGION_SID);
CREATE INDEX CSR.IX_RMETRIC_RMETRIC_VAL ON CSR.REGION_METRIC_VAL (APP_SID, IND_SID);
CREATE INDEX CSR.IX_RTYPE_RMETRIC_VAL ON CSR.REGION_METRIC_VAL (APP_SID);
CREATE INDEX CSR.IX_USER_RMETRIC_VAL ON CSR.REGION_METRIC_VAL (APP_SID, ENTERED_BY_SID);
CREATE INDEX CSR.IX_CUST_RTYPE_RTYPE_METRIC ON CSR.REGION_TYPE_METRIC  (APP_SID, REGION_TYPE);
CREATE INDEX CSR.IX_RMETRIC_RTYPE_METRIC ON CSR.REGION_TYPE_METRIC (APP_SID, IND_SID);


BEGIN
	INSERT INTO CSR.SOURCE_TYPE ( SOURCE_TYPE_ID, DESCRIPTION) VALUES (14, 'Region metric');
END;
/


@../csr_data_pkg
@../region_metric_pkg

@../region_body
@../indicator_body
@../region_metric_body


@update_tail
