-- Please update version.sql too -- this keeps clean builds in sync
define version=52
@update_header


-- 
-- SEQUENCE: ACCURACY_TYPE_ID_SEQ 
--

CREATE SEQUENCE ACCURACY_TYPE_ID_SEQ 
    START WITH 50
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

-- 
-- SEQUENCE: ACCURACY_TYPE_OPTION_ID_SEQ 
--

CREATE SEQUENCE ACCURACY_TYPE_OPTION_ID_SEQ 
    START WITH 50
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

DROP SEQUENCE DATA_SOURCE_ID_SEQ;
DROP SEQUENCE DATA_SOURCE_TYPE_ID_SEQ;

-- 
-- TABLE: ACCURACY_TYPE 
--

ALTER TABLE DATA_SOURCE_TYPE DROP CONSTRAINT PK162 CASCADE;
DROP INDEX PK162;

CREATE TABLE ACCURACY_TYPE (
    ACCURACY_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CSR_ROOT_SID        NUMBER(10, 0)    NOT NULL,
    LABEL               VARCHAR2(255)    NOT NULL,
    Q_OR_C              CHAR(1)           DEFAULT 'Q' NOT NULL,
    MAX_SCORE           NUMBER(10, 0)     DEFAULT 10 NOT NULL,
    CONSTRAINT PK162 PRIMARY KEY (ACCURACY_TYPE_ID)
)
;


INSERT INTO ACCURACY_TYPE (ACCURACY_TYPE_ID, CSR_ROOT_SID, LABEL, Q_OR_C, MAX_SCORE)
	SELECT data_source_type_id, csr_root_sid, label, q_or_c, max_score FROM data_source_type;

COMMIT;


-- 
-- TABLE: ACCURACY_TYPE_OPTION 
--
ALTER TABLE DATA_SOURCE DROP CONSTRAINT PK166 CASCADE;
DROP INDEX PK166;

CREATE TABLE ACCURACY_TYPE_OPTION(
    ACCURACY_TYPE_OPTION_ID    NUMBER(10, 0)    NOT NULL,
    ACCURACY_TYPE_ID           NUMBER(10, 0)    NOT NULL,
    LABEL                      VARCHAR2(255)    NOT NULL,
    ACCURACY_WEIGHTING         NUMBER(10, 0)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK166 PRIMARY KEY (ACCURACY_TYPE_OPTION_ID)
)
;


INSERT INTO ACCURACY_TYPE_OPTION (accuracy_type_option_id, ACCURACY_TYPE_ID, LABEL, accuracy_weighting)
	SELECT data_source_id, data_source_type_id, label, accuracy_weighting FROM data_source;

COMMIT;



-- 
-- TABLE: IND_ACCURACY_TYPE 
--
ALTER TABLE IND_DATA_SOURCE_TYPE DROP CONSTRAINT PK165 CASCADE;
DROP INDEX PK165;

CREATE TABLE IND_ACCURACY_TYPE(
    IND_SID             NUMBER(10, 0)    NOT NULL,
    ACCURACY_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK165 PRIMARY KEY (IND_SID, ACCURACY_TYPE_ID)
)
;

INSERT INTO IND_ACCURACY_TYPE (ind_sid, accuracy_type_id)
	SELECT ind_sid, data_source_type_id FROM ind_data_source_type;

COMMIT;



-- 
-- TABLE: SHEET_VALUE_ACCURACY 
--
ALTER TABLE SHEET_VALUE_DATA_SOURCE DROP CONSTRAINT PK167_1 CASCADE;
DROP INDEX PK167_1;


CREATE TABLE SHEET_VALUE_ACCURACY(
    SHEET_VALUE_ID             NUMBER(10, 0)    NOT NULL,
    ACCURACY_TYPE_OPTION_ID    NUMBER(10, 0)    NOT NULL,
    PCT                        NUMBER(10, 4)    DEFAULT 1 NOT NULL,
    CONSTRAINT PK167_1 PRIMARY KEY (SHEET_VALUE_ID, ACCURACY_TYPE_OPTION_ID)
)
;


INSERT INTO SHEET_VALUE_ACCURACY (sheet_value_id, accuracy_type_option_id, pct)
	SELECT sheet_value_id, data_source_id, NVL(pct,0) FROM SHEET_VALUE_DATA_SOURCE;

COMMIT;



-- 
-- TABLE: VAL_ACCURACY 
--
ALTER TABLE VAL_DATA_SOURCE DROP CONSTRAINT PK167 CASCADE;
DROP INDEX PK167;

CREATE TABLE VAL_ACCURACY(
    VAL_ID                     NUMBER(10, 0)    NOT NULL,
    ACCURACY_TYPE_OPTION_ID    NUMBER(10, 0)    NOT NULL,
    PCT                        NUMBER(10, 4)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK167 PRIMARY KEY (VAL_ID, ACCURACY_TYPE_OPTION_ID)
)
;

INSERT INTO VAL_ACCURACY (val_id, accuracy_type_option_id, pct)
	SELECT val_id, data_source_id, pct FROM VAL_DATA_SOURCE;

COMMIT;



-- 
-- TABLE: SHEET_VALUE_ACCURACY 
--

ALTER TABLE SHEET_VALUE_ACCURACY ADD CONSTRAINT RefACCURACY_TYPE_OPTION438 
    FOREIGN KEY (ACCURACY_TYPE_OPTION_ID)
    REFERENCES ACCURACY_TYPE_OPTION(ACCURACY_TYPE_OPTION_ID)
;

ALTER TABLE SHEET_VALUE_ACCURACY ADD CONSTRAINT RefSHEET_VALUE439 
    FOREIGN KEY (SHEET_VALUE_ID)
    REFERENCES SHEET_VALUE(SHEET_VALUE_ID)
;



-- 
-- TABLE: VAL_ACCURACY 
--

ALTER TABLE VAL_ACCURACY ADD CONSTRAINT RefACCURACY_TYPE_OPTION440 
    FOREIGN KEY (ACCURACY_TYPE_OPTION_ID)
    REFERENCES ACCURACY_TYPE_OPTION(ACCURACY_TYPE_OPTION_ID)
;

ALTER TABLE VAL_ACCURACY ADD CONSTRAINT RefVAL441 
    FOREIGN KEY (VAL_ID)
    REFERENCES VAL(VAL_ID)
;



/*
-- only run this when we're sure the rest is ok
DROP TABLE DATA_SOURCE_TYPE PURGE;
DROP TABLE DATA_SOURCE PURGE;
DROP TABLE IND_DATA_SOURCE_TYPE PURGE;
DROP TABLE SHEET_VALUE_DATA_SOURCE PURGE;
DROP TABLE VAL_DATA_SOURCE PURGE;

*/

@update_tail
