-- Please update version.sql too -- this keeps clean builds in sync
define version=1677
@update_header

ALTER TABLE CSR.DELEG_REPORT_DELEG_PLAN DROP CONSTRAINT PK_DELEG_REPORT_DELEG_PLAN;
ALTER TABLE CSR.DELEG_REPORT_DELEG_PLAN ADD CONSTRAINT PK_DELEG_REPORT_DELEG_PLAN PRIMARY KEY (APP_SID, DELEG_REPORT_SID, DELEG_PLAN_SID);

ALTER TABLE CSR.DELEG_REPORT_REGION DROP CONSTRAINT PK_DELEG_REPORT_REGION;
ALTER TABLE CSR.DELEG_REPORT_REGION ADD CONSTRAINT PK_DELEG_REPORT_REGION PRIMARY KEY (APP_SID, DELEG_REPORT_SID, ROOT_REGION_SID);

@update_tail
