-- Please update version.sql too -- this keeps clean builds in sync
define version=2054
@update_header

ALTER TABLE CSR.EST_SPACE_ATTR DROP CONSTRAINT FK_EST_SPACEATTR_SPACE;
ALTER TABLE CSR.EST_SPACE_ATTR ADD CONSTRAINT FK_EST_SPACEATTR_SPACE 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID)
    REFERENCES CSR.EST_SPACE(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID)
    DEFERRABLE INITIALLY DEFERRED
;

ALTER TABLE CSR.EST_BUILDING_METRIC DROP CONSTRAINT FK_EST_BLDMET_BLDNG;
ALTER TABLE CSR.EST_BUILDING_METRIC ADD CONSTRAINT FK_EST_BLDMET_BLDNG 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    REFERENCES CSR.EST_BUILDING(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    DEFERRABLE INITIALLY DEFERRED
;


ALTER TABLE CSR.EST_SPACE DROP CONSTRAINT FK_EST_SPACE_BLDNG;
ALTER TABLE CSR.EST_SPACE ADD CONSTRAINT FK_EST_SPACE_BLDNG 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    REFERENCES CSR.EST_BUILDING(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    DEFERRABLE INITIALLY DEFERRED
;

ALTER TABLE CSR.EST_ENERGY_METER DROP CONSTRAINT FK_EST_METER_BLDNG;
ALTER TABLE CSR.EST_ENERGY_METER ADD CONSTRAINT FK_EST_METER_BLDNG 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    REFERENCES CSR.EST_BUILDING(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    DEFERRABLE INITIALLY DEFERRED
;

ALTER TABLE CSR.EST_WATER_METER DROP CONSTRAINT FK_WMETER_BLDNG;
ALTER TABLE CSR.EST_WATER_METER ADD CONSTRAINT FK_WMETER_BLDNG 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    REFERENCES CSR.EST_BUILDING(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID)
    DEFERRABLE INITIALLY DEFERRED
;

ALTER TABLE CSR.EST_ENERGY_METER DROP CONSTRAINT FK_EST_METER_SPACE;
ALTER TABLE CSR.EST_ENERGY_METER ADD CONSTRAINT FK_EST_METER_SPACE 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID)
    REFERENCES CSR.EST_SPACE(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID)
    DEFERRABLE INITIALLY DEFERRED
;

ALTER TABLE CSR.EST_WATER_METER DROP CONSTRAINT FK_WMETER_SPACE;
ALTER TABLE CSR.EST_WATER_METER ADD CONSTRAINT FK_WMETER_SPACE 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID)
    REFERENCES CSR.EST_SPACE(APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID)
    DEFERRABLE INITIALLY DEFERRED
;

CREATE UNIQUE INDEX CSR.UK_BUILDING_ID ON CSR.EST_BUILDING(APP_SID, EST_ACCOUNT_SID, PM_BUILDING_ID);


@../energy_star_body

@update_tail
