-- Please update version.sql too -- this keeps clean builds in sync
define version=1158
@update_header

DROP INDEX CT.IDX_BD_TYPE_1;
DROP INDEX CT.IDX_BD_TYPE_2;
DROP INDEX CT.IDX_BD_TYPE_3;

CREATE UNIQUE INDEX CT.IDX_BD_TYPE_1 ON CT.BREAKDOWN_TYPE (APP_SID,LOWER(SINGULAR),IS_HOTSPOT,COMPANY_SID);
CREATE UNIQUE INDEX CT.IDX_BD_TYPE_2 ON CT.BREAKDOWN_TYPE (APP_SID,LOWER(PLURAL),IS_HOTSPOT,COMPANY_SID);
CREATE UNIQUE INDEX CT.IDX_BD_TYPE_3 ON CT.BREAKDOWN_TYPE (APP_SID, CASE "IS_REGION"
  WHEN 1 THEN
    (-1)
  ELSE
    "BREAKDOWN_TYPE_ID"
  END,IS_HOTSPOT,COMPANY_SID);
  
ALTER TABLE CT.BREAKDOWN_TYPE DROP CONSTRAINT CC_BD_TYPE_COMPANY_SID;
ALTER TABLE CT.BREAKDOWN_TYPE ADD CONSTRAINT CC_BD_TYPE_COMPANY_SID 
    CHECK ((COMPANY_SID IS NULL AND IS_REGION = 1) OR (COMPANY_SID IS NOT NULL));
	
@..\ct\breakdown_type_body
 
@update_tail