-- Please update version.sql too -- this keeps clean builds in sync
define version=1909
@update_header

ALTER TABLE SUPPLIER.WOOD_PART_WOOD DROP COLUMN FOREST_SOURCE_CAT_CODE;

-- we still need mapping for the recycled stuff
CREATE TABLE SUPPLIER.RECYC_FSCC_CS_MAP(
    FOREST_SOURCE_CAT_CODE    VARCHAR2(32)     NOT NULL,
    CERT_SCHEME_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK423 PRIMARY KEY (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID)
)
;

ALTER TABLE SUPPLIER.RECYC_FSCC_CS_MAP ADD CONSTRAINT FK_RECYC_CS_MAP 
    FOREIGN KEY (CERT_SCHEME_ID)
    REFERENCES SUPPLIER.CERT_SCHEME(CERT_SCHEME_ID)
;

ALTER TABLE SUPPLIER.RECYC_FSCC_CS_MAP ADD CONSTRAINT FK_RECYC_FSCC_MAP 
    FOREIGN KEY (FOREST_SOURCE_CAT_CODE)
    REFERENCES SUPPLIER.FOREST_SOURCE_CAT(FOREST_SOURCE_CAT_CODE)
;
 

	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RI', 1);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RI', 9);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RI', 14);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RI', 15);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RI', 16);
	
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RII', 1);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RII', 5);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RII', 9);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RII', 14);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RII', 15);
	INSERT INTO SUPPLIER.RECYC_FSCC_CS_MAP (FOREST_SOURCE_CAT_CODE, CERT_SCHEME_ID) VALUES ('RII', 16);
 


@..\supplier\wood\part_description_body
@..\supplier\wood\part_wood_pkg
@..\supplier\wood\part_wood_body
@..\supplier\wood\product_wood_body
@..\supplier\wood\report_wood_body

@update_tail
