-- Please update version.sql too -- this keeps clean builds in sync
define version=2208
@update_header

-- Create new types for csr.deleg_grid_variance.
CREATE OR REPLACE TYPE CSR.T_DELEG_GRID_VAR_ROW AS OBJECT
(
	id			VARCHAR2(255),
	label			VARCHAR2(255),
	variance		VARCHAR2(255),
	explanation		CLOB
);
/

CREATE OR REPLACE TYPE CSR.T_DELEG_GRID_VAR_TABLE AS
  TABLE OF CSR.T_DELEG_GRID_VAR_ROW;
/

ALTER TABLE CSR.DELEGATION_GRID ADD (
	VARIANCE_VALIDATION_SP		VARCHAR2(255)
);

CREATE TABLE CSR.DELEG_GRID_VARIANCE (
	APP_SID					NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY','APP'),
	ID						VARCHAR2(255) NOT NULL,
	ROOT_DELEGATION_SID		NUMBER(10) NOT NULL,
	REGION_SID				NUMBER(10) NOT NULL,
	START_DTM				DATE NOT NULL,
	END_DTM					DATE NOT NULL,
	GRID_IND_SID			NUMBER(10) NOT NULL,
	LABEL					VARCHAR2(255) NOT NULL,
	VARIANCE				VARCHAR2(255) NOT NULL,
	EXPLANATION				CLOB,
	ACTIVE					NUMBER(1) DEFAULT 1,
	CURR_VALUE				NUMBER,
	PREV_VALUE				NUMBER,
	CONSTRAINT PK_DELEG_GRID_VAR PRIMARY KEY (APP_SID, ROOT_DELEGATION_SID, REGION_SID, START_DTM, END_DTM, GRID_IND_SID, ID)
);

ALTER TABLE CSR.DELEG_GRID_VARIANCE ADD CONSTRAINT FK_DEL_GRID_VAR_IND FOREIGN KEY (APP_SID, GRID_IND_SID)
	REFERENCES CSR.DELEGATION_GRID (APP_SID, IND_SID);

-- CSRIMP Changes.
CREATE TABLE CSRIMP.DELEG_GRID_VARIANCE (
	CSRIMP_SESSION_ID		NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ID						VARCHAR2(255) NOT NULL,
	ROOT_DELEGATION_SID		NUMBER(10) NOT NULL,
	REGION_SID				NUMBER(10) NOT NULL,
	START_DTM				DATE NOT NULL,
	END_DTM					DATE NOT NULL,
	GRID_IND_SID			NUMBER(10) NOT NULL,
	LABEL					VARCHAR2(255) NOT NULL,
	VARIANCE				VARCHAR2(255) NOT NULL,
	EXPLANATION				CLOB,
	ACTIVE					NUMBER(1) DEFAULT 1,
	CURR_VALUE				NUMBER,
	PREV_VALUE				NUMBER,
	CONSTRAINT PK_DELEG_GRID_VAR PRIMARY KEY (CSRIMP_SESSION_ID, ID, ROOT_DELEGATION_SID, REGION_SID, START_DTM, END_DTM, GRID_IND_SID)
);

ALTER TABLE CSRIMP.DELEG_GRID_VARIANCE ADD CONSTRAINT FK_DELEG_GRID_VAR_IMP_S FOREIGN KEY (CSRIMP_SESSION_ID)
	REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
    	ON DELETE CASCADE;

ALTER TABLE CSRIMP.DELEG_GRID_VARIANCE ADD CONSTRAINT FK_DEL_GRID_VAR_IND FOREIGN KEY (CSRIMP_SESSION_ID, GRID_IND_SID)
	REFERENCES CSRIMP.DELEGATION_GRID (CSRIMP_SESSION_ID, IND_SID);

GRANT INSERT ON CSR.DELEG_GRID_VARIANCE TO CSRIMP;

@../delegation_pkg
@../csrimp/imp_pkg
@../schema_pkg
@../delegation_body
@../csr_data_body
@../csrimp/imp_body
@../schema_body

@update_tail
