-- Please update version.sql too -- this keeps clean builds in sync
define version=413
@update_header

CREATE SEQUENCE HELP_IMAGE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE SEQUENCE HELP_TAG_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE TABLE HELP_IMAGE(
    IMAGE_ID         NUMBER(10, 0)     NOT NULL,
    APP_SID          NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    MIME_TYPE        VARCHAR2(100)     NOT NULL,
    SHA1             RAW(20)           NOT NULL,
    FILENAME         VARCHAR2(200)     NOT NULL,
    DESCRIPTION      VARCHAR2(1000),
    DATA             BLOB              NOT NULL,
    MODIFIED_DTM     TIMESTAMP(6)      DEFAULT systimestamp NOT NULL,
    WIDTH            NUMBER(10, 0),
    HEIGHT           NUMBER(10, 0),
    IMAGE_LANG_ID    NUMBER(10, 0)     NOT NULL,
    RECYCLED         NUMBER(1, 0)      NOT NULL
					CHECK (RECYCLED IN (0,1)),
    CONSTRAINT PK_HELP_IMAGE PRIMARY KEY (IMAGE_ID)
    USING INDEX
TABLESPACE INDX
)
;

CREATE TABLE HELP_IMAGE_TAG(
    PARENT_TAG_ID    NUMBER(10, 0)    NOT NULL,
    IMAGE_ID         NUMBER(10, 0)    NOT NULL,
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    CONSTRAINT PK_HELP_IMAGE_TAG PRIMARY KEY (PARENT_TAG_ID, IMAGE_ID)
    USING INDEX
TABLESPACE INDX
)
;

CREATE TABLE HELP_TAG(
    TAG_ID           NUMBER(10, 0)    NOT NULL,
    APP_SID          NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TAG              VARCHAR2(300)    NOT NULL,
    PARENT_TAG_ID    NUMBER(10, 0),
    CONSTRAINT PK_HELP_TAG PRIMARY KEY (TAG_ID)
    USING INDEX
TABLESPACE INDX
)
;

ALTER TABLE HELP_IMAGE ADD CONSTRAINT RefHELP_LANG1446 
    FOREIGN KEY (IMAGE_LANG_ID)
    REFERENCES HELP_LANG(HELP_LANG_ID)
;

ALTER TABLE HELP_IMAGE_TAG ADD CONSTRAINT FK_HELP_IMAGE_IMAGE_TAG 
    FOREIGN KEY (IMAGE_ID)
    REFERENCES HELP_IMAGE(IMAGE_ID) ON DELETE CASCADE
;

ALTER TABLE HELP_IMAGE_TAG ADD CONSTRAINT FK_HELP_TAG_IMAGE_TAG 
    FOREIGN KEY (PARENT_TAG_ID)
    REFERENCES HELP_TAG(TAG_ID) ON DELETE CASCADE
;

CREATE TABLE HELP_TOPIC_IMAGE(
    HELP_TOPIC_ID    NUMBER(10, 0)    NOT NULL,
    HELP_LANG_ID     NUMBER(10, 0)    NOT NULL,
    HELP_IMAGE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK683 PRIMARY KEY (HELP_TOPIC_ID, HELP_LANG_ID, HELP_IMAGE_ID)
)
;

DECLARE
BEGIN	
	FOR r IN (
		SELECT constraint_name 
	  	  FROM user_constraints
		 WHERE table_name = 'HELP_TOPIC_FILE' 
		   and constraint_type = 'R'
	) 
	LOOP
		EXECUTE IMMEDIATE 'ALTER TABLE csr.help_topic_file DROP CONSTRAINT ' || r.constraint_name;
	END LOOP;
END;
/

ALTER TABLE HELP_TOPIC_FILE ADD CONSTRAINT RefHELP_TOPIC_TEXT1447 
    FOREIGN KEY (HELP_TOPIC_ID, HELP_LANG_ID)
    REFERENCES HELP_TOPIC_TEXT(HELP_TOPIC_ID, HELP_LANG_ID)
;

ALTER TABLE HELP_TOPIC_IMAGE ADD CONSTRAINT RefHELP_IMAGE1448 
    FOREIGN KEY (HELP_IMAGE_ID)
    REFERENCES HELP_IMAGE(IMAGE_ID)
;

ALTER TABLE HELP_TOPIC_IMAGE ADD CONSTRAINT RefHELP_TOPIC_TEXT1449 
    FOREIGN KEY (HELP_TOPIC_ID, HELP_LANG_ID)
    REFERENCES HELP_TOPIC_TEXT(HELP_TOPIC_ID, HELP_LANG_ID)
;

@..\help\help_pkg
@..\help\help_image_pkg

@..\help\help_body
@..\help\help_image_body

GRANT EXECUTE ON help_image_pkg TO web_user;

GRANT SELECT, REFERENCES, UPDATE ON help_image TO web_user;
GRANT CHANGE notification TO web_user;

@update_tail
