-- Please update version.sql too -- this keeps clean builds in sync
define version=789
@update_header

ALTER TABLE CHAIN.CUSTOMER_OPTIONS
ADD (CHAIN_IS_VISIBLE_TO_TOP NUMBER(1) DEFAULT 0 NOT NULL);

ALTER TABLE CHAIN.PURCHASED_COMPONENT
ADD (PURCHASES_LOCKED NUMBER(1) DEFAULT 0 NOT NULL);

INSERT INTO chain.DOWNLOAD_PERMISSION (DOWNLOAD_PERMISSION_ID, DESCRIPTION)
VALUES (3, 'Standard capability based permissions plus permission for any company that passes transparency check for the ownwer company');

INSERT INTO chain.DOWNLOAD_PERMISSION (DOWNLOAD_PERMISSION_ID, DESCRIPTION)
VALUES (4, 'Owner company and any company that passes transparency check for the ownwer company - standard checks not used');


CREATE GLOBAL TEMPORARY TABLE CHAIN.TT_PURCHASES
(
	PERIOD_ID					NUMBER(10) NOT NULL,
	PERIOD_START_DATE 	        DATE NOT NULL,
	PERIOD_END_DATE     	    DATE NOT NULL,
	COMPONENT_ID		        NUMBER(10) NOT NULL,
	COMPANY_SID     			NUMBER(10) NOT NULL,
	PURCHASE_CHANNEL_ID			NUMBER(10),
	PURCHASE_START_DATE         DATE NOT NULL,
	PURCHASE_END_DATE           DATE,
    RAW_AMOUNT                  NUMBER(15,5) NOT NULL,
    ADJUSTED_AMOUNT             NUMBER(15,5),
    AMOUNT_UNIT_ID              NUMBER(15,5), 
    UNIT_TYPE                   VARCHAR2(32),
	CONVERSION_TO_BASE			NUMBER(20,10),
	SUPPLIER_PRODUCT_ID			NUMBER(10)
)
ON COMMIT DELETE ROWS;

ALTER TABLE CHAIN.AMOUNT_UNIT
ADD (CONVERSION_TO_BASE NUMBER(20,10));


@update_tail
