-- Please update version.sql too -- this keeps clean builds in sync
define version=744
@update_header

connect security/security@&_CONNECT_IDENTIFIER

GRANT EXECUTE ON security.T_ORDERED_SID_ROW TO csr;

connect csr/csr@&_CONNECT_IDENTIFIER

CREATE TABLE csr.QS_FILTER_CONDITION(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FILTER_ID                NUMBER(10, 0)    NOT NULL,
    QS_FILTER_CONDITION_ID   NUMBER(10, 0)    NOT NULL,
    QUESTION_ID              NUMBER(10, 0)    NOT NULL,
    COMPARATOR               VARCHAR2(20)     NOT NULL,
    COMPARE_TO_QUESTION_ID   NUMBER(10, 0),
    COMPARE_TO_STR_VAL       VARCHAR2(2047),
    COMPARE_TO_NUM_VAL       NUMBER(24, 10),
    COMPARE_TO_OPTION_ID     NUMBER(10, 0),
    CONSTRAINT PK_QS_FILTER_CONDITION PRIMARY KEY (APP_SID, FILTER_ID, QS_FILTER_CONDITION_ID)
);

ALTER TABLE csr.QS_FILTER_CONDITION ADD CONSTRAINT FK_QS_FIL_COND_QN
    FOREIGN KEY (APP_SID, QUESTION_ID)
    REFERENCES CSR.QUICK_SURVEY_QUESTION(APP_SID, QUESTION_ID);

ALTER TABLE csr.QS_FILTER_CONDITION ADD CONSTRAINT FK_QS_FIL_COND_CMP_QN 
    FOREIGN KEY (APP_SID, COMPARE_TO_QUESTION_ID)
    REFERENCES CSR.QUICK_SURVEY_QUESTION(APP_SID, QUESTION_ID);

ALTER TABLE csr.QS_FILTER_CONDITION ADD CONSTRAINT FK_QS_FIL_COND_CMP_OP
    FOREIGN KEY (QUESTION_ID, COMPARE_TO_OPTION_ID)
    REFERENCES CSR.QS_QUESTION_OPTION(QUESTION_ID, QUESTION_OPTION_ID);

-- These are run from chain\latest131
--@..\quick_survey_pkg
--@..\quick_survey_body

@update_tail
