-- Please update version.sql too -- this keeps clean builds in sync
define version=330
@update_header

ALTER TABLE UTILITY_CONTRACT DROP CONSTRAINT RefUTILITY_SUPPLIER1160
;
ALTER TABLE UTILITY_CONTRACT ADD CONSTRAINT RefUTILITY_SUPPLIER1160
    FOREIGN KEY (APP_SID, UTILITY_SUPPLIER_ID)
    REFERENCES UTILITY_SUPPLIER(APP_SID, UTILITY_SUPPLIER_ID) ON DELETE CASCADE
;

ALTER TABLE UTILITY_INVOICE DROP CONSTRAINT RefUTILITY_CONTRACT1163
;
ALTER TABLE UTILITY_INVOICE ADD CONSTRAINT RefUTILITY_CONTRACT1163
    FOREIGN KEY (APP_SID, UTILITY_CONTRACT_ID)
    REFERENCES UTILITY_CONTRACT(APP_SID, UTILITY_CONTRACT_ID) ON DELETE CASCADE
;

CREATE OR REPLACE TRIGGER UTILIY_CONTRACT_BD_TRIGGER
BEFORE DELETE
    ON UTILITY_CONTRACT
    FOR EACH ROW
DECLARE
BEGIN
    UPDATE all_meter 
       SET utility_contract_id = NULL
     WHERE utility_contract_id = :OLD.utility_contract_id;
END;
/

@update_tail
