-- Please update version.sql too -- this keeps clean builds in sync
define version=1800
@update_header

begin
	INSERT INTO CSR.STD_MEASURE (STD_MEASURE_ID, NAME, DESCRIPTION, SCALE, FORMAT_MASK, REGIONAL_AGGREGATION, CUSTOM_FIELD, PCT_OWNERSHIP_APPLIES, M, KG, S, A, K, MOL, CD)
	VALUES (35, 'm^3.s^-1', 'm^3.s^-1', 0, '#,##0', 'sum', NULL, 0, 3, 0, -1, 0, 0, 0, 0);

	INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE)
	VALUES (26201, 35, 'm^3/s', 1, 1, 0, 0);

	INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE)
	VALUES (26202, 35, 'l/hour', 3600000, 1, 0, 0);
end;
/

@update_tail