-- Please update version.sql too -- this keeps clean builds in sync
define version=1072
@update_header

ALTER TABLE CSR.PROPERTY ADD
(
    TELEPHONE             VARCHAR2(200 BYTE),
    STREET_ADDRESS        VARCHAR2(200 BYTE),
    CITY                  VARCHAR2(200 BYTE),
    STATE                 VARCHAR2(200 BYTE),
    POSTCODE              VARCHAR2(200 BYTE),
    MANAGER_CSR_USER_SID  NUMBER(10,0),
    NEIGH_ASSMT_DIRTY     NUMBER(1) DEFAULT -1 NOT NULL
);

ALTER TABLE CSR.PROPERTY MODIFY
(
    GROUP_ID             NUMBER(10, 0) NULL
);

ALTER TABLE CSR.PROPERTY ADD CONSTRAINT PROPERTY_CSR_USER FOREIGN KEY (APP_SID, MANAGER_CSR_USER_SID) REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);

COMMENT ON COLUMN CSR.PROPERTY.APP_SID IS 'app';
COMMENT ON COLUMN CSR.PROPERTY.REGION_SID IS 'region';
COMMENT ON COLUMN CSR.PROPERTY.MANAGER_CSR_USER_SID IS 'user';

@update_tail