-- Please update version.sql too -- this keeps clean builds in sync
define version=1715
@update_header

--re-create renamed column in index
BEGIN
	
	FOR r IN (SELECT index_name FROM all_indexes WHERE owner='CHAIN' AND index_name='UK_CTC_UNIQUE_PERMISSION_SET' AND dropped='NO') 
	LOOP
		EXECUTE IMMEDIATE 'DROP INDEX CHAIN.UK_CTC_UNIQUE_PERMISSION_SET';
	END LOOP;
	
	FOR r IN (SELECT index_name FROM all_indexes WHERE owner='CHAIN' AND index_name='IX_CTC_CTR_RELATIONSHIP' AND dropped='NO') 
	LOOP
		EXECUTE IMMEDIATE 'DROP INDEX CHAIN.IX_CTC_CTR_RELATIONSHIP';
	END LOOP;
	
	FOR r IN (SELECT index_name FROM all_indexes WHERE owner='CHAIN' AND index_name='IX_CTR_COMPANY_TYPE_2' AND dropped='NO') 
	LOOP
		EXECUTE IMMEDIATE 'DROP INDEX CHAIN.IX_CTR_COMPANY_TYPE_2';
	END LOOP;
	
	FOR r IN (SELECT index_name FROM all_indexes WHERE owner='CHAIN' AND index_name='IX_INVITE_OBO_CTR_OBOCTCICT' AND dropped='NO') 
	LOOP
		EXECUTE IMMEDIATE 'DROP INDEX CHAIN.IX_INVITE_OBO_CTR_OBOCTCICT';
	END LOOP;
	
END;
/

CREATE INDEX CHAIN.IX_CTC_CTR_RELATIONSHIP ON CHAIN.COMPANY_TYPE_CAPABILITY(APP_SID,SECONDARY_COMPANY_TYPE_ID,PRIMARY_COMPANY_TYPE_ID);

CREATE INDEX CHAIN.IX_CTR_COMPANY_TYPE_2 ON CHAIN.COMPANY_TYPE_RELATIONSHIP(APP_SID,SECONDARY_COMPANY_TYPE_ID);

/* New constraint, unique index for COMPANY_TYPE_CAPABILITY*/
ALTER TABLE CHAIN.COMPANY_TYPE_CAPABILITY ADD CONSTRAINT CC_SECONDARY_TERTIARY CHECK (TERTIARY_COMPANY_TYPE_ID IS NULL OR (TERTIARY_COMPANY_TYPE_ID IS NOT NULL AND SECONDARY_COMPANY_TYPE_ID IS NOT NULL));

CREATE UNIQUE INDEX CHAIN.UK_CTC_UNIQUE_PERMISSION_SET ON CHAIN.COMPANY_TYPE_CAPABILITY
(APP_SID, PRIMARY_COMPANY_TYPE_ID, PRIMARY_COMPANY_GROUP_TYPE_ID, CAPABILITY_ID, 
	NVL2(SECONDARY_COMPANY_TYPE_ID, NVL2(TERTIARY_COMPANY_TYPE_ID, 'T' || TERTIARY_COMPANY_TYPE_ID || 'R' || SECONDARY_COMPANY_TYPE_ID, 'R' || SECONDARY_COMPANY_TYPE_ID), 'C' || PRIMARY_COMPANY_TYPE_ID));



@update_tail
