-- Please update version.sql too -- this keeps clean builds in sync
define version=2572
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
DECLARE
	v_cnt	NUMBER(10);
BEGIN
	SELECT count(*) 
	  INTO v_cnt
	  FROM all_tables
	 WHERE table_name = 'TRAINER'
	   AND owner = 'CSR';
	
	IF v_cnt = 1 THEN
		BEGIN
			SELECT COUNT(*)
			  INTO v_cnt
			  FROM ALL_CONSTRAINTS
			 WHERE OWNER = 'CSR'
			   AND TABLE_NAME='TRAINER'
			   AND CONSTRAINT_NAME='UNQ_TRAINER';
			
			IF v_cnt = 1 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER DROP CONSTRAINT UNQ_TRAINER';
			END IF;
			
			SELECT COUNT(*)
			  INTO v_cnt
			  FROM ALL_CONSTRAINTS
			 WHERE OWNER = 'CSR'
			   AND TABLE_NAME='TRAINER'
			   AND CONSTRAINT_NAME='CK_TRAINER';
			
			IF v_cnt = 1 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER DROP CONSTRAINT CK_TRAINER DROP INDEX';
			END IF;
			
			SELECT COUNT(*)
			  INTO v_cnt
			  FROM ALL_INDEXES
			 WHERE OWNER = 'CSR'
			   AND TABLE_NAME='TRAINER'
			   AND INDEX_NAME='IDX_UK_TRAINER';
			
			IF v_cnt = 1 THEN
				EXECUTE IMMEDIATE 'DROP INDEX CSR.IDX_UK_TRAINER';
			END IF;
		
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'TRAINER'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'NAME'
			   AND NULLABLE = 'N';
			
			IF v_cnt = 1 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER MODIFY NAME VARCHAR2(256) NULL';
				
			END IF;
			
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'TRAINER'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'USER_SID';
			
			IF v_cnt = 0 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER ADD USER_SID NUMBER(10)';
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER ADD CONSTRAINT FK_TRAINER_USER 
				FOREIGN KEY (APP_SID, USER_SID) REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID)';
			END IF;
			
			EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER ADD CONSTRAINT UNQ_TRAINER UNIQUE (APP_SID, NAME, USER_SID)';			
			EXECUTE IMMEDIATE 'ALTER TABLE CSR.TRAINER ADD CONSTRAINT CK_TRAINER CHECK ((NAME IS NOT NULL AND USER_SID IS NULL) OR (USER_SID IS NOT NULL AND NAME IS NULL))';			
			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX CSR.IDX_UK_TRAINER ON CSR.TRAINER(APP_SID, NVL(UPPER(NAME),''USR''||TO_CHAR(USER_SID)))';
		END;
	END IF;
END;
/

DECLARE
	v_cnt	NUMBER(10);
BEGIN
	SELECT count(*) 
	  INTO v_cnt
	  FROM all_tables
	 WHERE table_name = 'COURSE'
	   AND owner = 'CSR';
	
	IF v_cnt = 1 THEN
		BEGIN
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'COURSE'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'VERSION'
			   AND DATA_TYPE='NUMBER';
			   
			IF v_cnt = 1 THEN
				UPDATE CSR.COURSE SET VERSION = NULL;
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.COURSE MODIFY VERSION VARCHAR2(50)';
			END IF;
			
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'COURSE'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'PASS_FAIL';
			
			IF v_cnt = 0 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.COURSE ADD PASS_FAIL NUMBER(1) DEFAULT 0 NOT NULL';
			END IF;
			
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'COURSE'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'ABSOLUTE_DEADLINE';
			
			IF v_cnt = 0 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.COURSE ADD ABSOLUTE_DEADLINE DATE';
			END IF;
			
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'COURSE'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'COURSE_GROUP'
			   AND DATA_TYPE='VARCHAR2';
			   
			IF v_cnt = 1 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.FUNCTION_COURSE DISABLE CONSTRAINT FK_FUNCTION_COURSE_COURSE';
				EXECUTE IMMEDIATE 'TRUNCATE TABLE CSR.FUNCTION_COURSE';
				EXECUTE IMMEDIATE 'TRUNCATE TABLE CSR.COURSE';
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.COURSE MODIFY COURSE_GROUP NUMBER(10) NOT NULL';
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.FUNCTION_COURSE ENABLE CONSTRAINT FK_FUNCTION_COURSE_COURSE';
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.COURSE ADD CONSTRAINT FK_COURSE_REGION 
				FOREIGN KEY (APP_SID, COURSE_GROUP) REFERENCES CSR.REGION (APP_SID, REGION_SID)';
			END IF;
		END;
	END IF;
END;
/

DECLARE
	v_cnt	NUMBER(10);
BEGIN
	SELECT count(*) 
	  INTO v_cnt
	  FROM all_tables
	 WHERE table_name = 'COURSE_TYPE'
	   AND owner = 'CSR';
	
	IF v_cnt = 1 THEN
		BEGIN
			SELECT COUNT(*)
			  INTO v_cnt 
			  FROM all_tab_cols
			 WHERE table_name = 'COURSE_TYPE'
			   AND owner = 'CSR'
			   AND COLUMN_NAME = 'USER_RELATIONSHIP_TYPE_ID'
			   AND NULLABLE = 'Y';
			   
			IF v_cnt = 1 THEN
				EXECUTE IMMEDIATE 'ALTER TABLE CSR.COURSE_TYPE MODIFY USER_RELATIONSHIP_TYPE_ID NOT NULL';
			END IF;
		END;
	END IF;
END;
/

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***

-- *** Data changes ***
-- RLS

-- Data

-- *** Packages ***
@../training_pkg
@../training_body

@update_tail
