-- Please update version.sql too -- this keeps clean builds in sync
define version=2111
@update_header

	INSERT INTO CSR.STD_MEASURE_CONVERSION(STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28122, 9, 'g/MJ', 1000000000, 1, 0, 1);
	INSERT INTO CSR.STD_MEASURE_CONVERSION(STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28123, 8, 'g/ml', 1000, 1, 0, 1);
	INSERT INTO CSR.STD_MEASURE_CONVERSION(STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28124, 8, 'hl/tonne', 0.00001, 1, 0, 1);

@update_tail