-- Please update version.sql too -- this keeps clean builds in sync
define version=3124
define minor_version=8
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CSR.SECONDARY_REGION_TREE_CTRL(
	APP_SID				NUMBER(10, 0)		DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	REGION_SID			NUMBER(10, 0)		NOT NULL,
	SP_NAME				VARCHAR2(30)		NOT NULL,
	REGION_ROOT_SID		NUMBER(10, 0),
	TAG_ID				NUMBER(10, 0),
	TAG_GROUP_IDS		VARCHAR2(1024),
	REDUCE_CONTENTION	NUMBER(1)			DEFAULT 0,
	APPLY_DELEG_PLANS	NUMBER(1)			DEFAULT 0,
	USER_SID			NUMBER(10, 0),
	LAST_RUN_DTM		DATE,
	CONSTRAINT PK_SECONDARY_REGION_TREE_LOG PRIMARY KEY (APP_SID, REGION_SID),
	CONSTRAINT CK_SRT_REDUCE_CONTENTION CHECK (REDUCE_CONTENTION IN (1,0)),
	CONSTRAINT CK_SRT_APPLY_DELEG_PLANS CHECK (APPLY_DELEG_PLANS IN (1,0))
);

ALTER TABLE CSR.SECONDARY_REGION_TREE_CTRL ADD CONSTRAINT FK_SCNDRY_RGN_TREE_CTRL_REGION
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.REGION(APP_SID, REGION_SID)
;
ALTER TABLE CSR.SECONDARY_REGION_TREE_CTRL ADD CONSTRAINT FK_SCNDRY_RGN_TREE_CTRL_REG_RT
	FOREIGN KEY (APP_SID, REGION_ROOT_SID)
	REFERENCES CSR.REGION(APP_SID, REGION_SID)
;
ALTER TABLE CSR.SECONDARY_REGION_TREE_CTRL ADD CONSTRAINT FK_SCNDRY_RGN_TREE_CTRL_USER
	FOREIGN KEY (APP_SID, USER_SID)
	REFERENCES CSR.CSR_USER (APP_SID, CSR_USER_SID)
;

CREATE TABLE CSRIMP.SECONDARY_REGION_TREE_CTRL(
	CSRIMP_SESSION_ID	NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID			NUMBER(10, 0)		NOT NULL,
	SP_NAME				VARCHAR2(30)		NOT NULL,
	REGION_ROOT_SID		NUMBER(10, 0),
	TAG_ID				NUMBER(10, 0),
	TAG_GROUP_IDS		VARCHAR2(1024),
	REDUCE_CONTENTION	NUMBER(1)			DEFAULT 0,
	APPLY_DELEG_PLANS	NUMBER(1)			DEFAULT 0,
	USER_SID			NUMBER(10, 0),
	LAST_RUN_DTM		DATE,
	CONSTRAINT PK_SECONDARY_REGION_TREE_LOG PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID),
	CONSTRAINT CK_SRT_REDUCE_CONTENTION CHECK (REDUCE_CONTENTION IN (1,0)),
	CONSTRAINT CK_SRT_APPLY_DELEG_PLANS CHECK (APPLY_DELEG_PLANS IN (1,0))
);

-- Alter tables

-- *** Grants ***
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.secondary_region_tree_ctrl TO tool_user;
GRANT SELECT, INSERT, UPDATE ON csr.secondary_region_tree_ctrl TO csrimp;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../schema_pkg

@../csr_app_body
@../region_tree_body
@../schema_body

@../csrimp/imp_pkg
@../csrimp/imp_body

@update_tail
