-- Please update version.sql too -- this keeps clean builds in sync
define version=2449
@update_header

GRANT INSERT ON CSR.CUSTOMER_FLOW_ALERT_CLASS TO CSRIMP;

ALTER TABLE CSRIMP.FLOW ADD (FLOW_ALERT_CLASS VARCHAR2(256));

CREATE TABLE CSRIMP.FLOW_CUSTOMER_ALERT_CLASS (
	CSRIMP_SESSION_ID			NUMBER(10)		DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FLOW_ALERT_CLASS			VARCHAR2(256) NOT NULL,
	CONSTRAINT PK_FLOW_CUSTOMER_ALERT_CLASS PRIMARY KEY (CSRIMP_SESSION_ID, FLOW_ALERT_CLASS),
    CONSTRAINT FK_FLOW_CUST_ALERT_CLASS_IS FOREIGN KEY
    	(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
    	ON DELETE CASCADE
);

GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.FLOW_CUSTOMER_ALERT_CLASS TO WEB_USER;

ALTER TABLE CSRIMP.QUICK_SURVEY_VERSION ADD (PUBLISHED_BY_SID NUMBER(10));

ALTER TABLE CSRIMP.QUICK_SURVEY ADD (AUDITING_AUDIT_TYPE_ID	NUMBER(10));

UPDATE CHAIN.DEFAULT_MESSAGE_DEFINITION
   SET MESSAGE_TEMPLATE = 'Invitation rejected by {reUser} from {reCompany}. {inviteDetails:OPEN}Click here to view invitation details{inviteDetails:CLOSE}'
 WHERE MESSAGE_TEMPLATE = 'Invitation rejected by {reUser} from {reCompany}.';
 
@..\schema_pkg
@..\schema_body
@..\csrimp\imp_body

@update_tail
