-- Please update version.sql too -- this keeps clean builds in sync
define version=2155
@update_header

CREATE TABLE CSR.MODEL_DELEG_IMPORT (
    APP_SID             NUMBER(10)          DEFAULT sys_context('security','app') NOT NULL,
    DELEGATION_SID      NUMBER(10)          NOT NULL,
    MODEL_SID           NUMBER(10)          NOT NULL,
    CONSTRAINT PK_MODEL_DELEG_IMPORT PRIMARY KEY (APP_SID, DELEGATION_SID, MODEL_SID),
    CONSTRAINT FK_MOD_DLG_IMP_MODEL FOREIGN KEY (APP_SID, MODEL_SID) REFERENCES CSR.MODEL (APP_SID, MODEL_SID) ON DELETE CASCADE,
    CONSTRAINT FK_MOD_DLG_IMP_DELEG FOREIGN KEY (APP_SID, DELEGATION_SID) REFERENCES CSR.DELEGATION (APP_SID, DELEGATION_SID) ON DELETE CASCADE
);

@../model_pkg 
@../model_body

@update_tail