-- Please update version.sql too -- this keeps clean builds in sync
define version=1205
@update_header

CREATE TABLE CT.PS_SPEND_BREAKDOWN (
    APP_SID NUMBER(10) NOT NULL,
    COMPANY_SID NUMBER(10) NOT NULL,
    BREAKDOWN_ID NUMBER(10) NOT NULL,
    REGION_ID NUMBER(10) NOT NULL,
    SPEND NUMBER(20,10) NOT NULL,
    CONSTRAINT PK_PS_SPEND PRIMARY KEY (APP_SID, COMPANY_SID, BREAKDOWN_ID, REGION_ID)
);

ALTER TABLE CT.PS_SPEND_BREAKDOWN ADD CONSTRAINT PS_OPT_PS_SPEND 
    FOREIGN KEY (APP_SID, COMPANY_SID) REFERENCES CT.PS_OPTIONS (APP_SID,COMPANY_SID);

ALTER TABLE CT.PS_SPEND_BREAKDOWN ADD CONSTRAINT B_R_PS_SPEND 
    FOREIGN KEY (APP_SID, BREAKDOWN_ID, REGION_ID) REFERENCES CT.BREAKDOWN_REGION (APP_SID,BREAKDOWN_ID,REGION_ID);
	
@..\ct\products_services_pkg

@..\ct\products_services_body
@..\ct\supplier_body
	
@update_tail