-- Please update version.sql too -- this keeps clean builds in sync
define version=899
@update_header

CREATE SEQUENCE CSR.DELEG_PLAN_APPLIED_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER;

ALTER TABLE CSR.DELEG_PLAN ADD (
    ACTIVE             NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    NOTES              CLOB,
    CONSTRAINT CHK_DELEG_PLAN_ACTIVE CHECK (ACTIVE IN (0,1))
 );

CREATE TABLE CSR.DELEG_PLAN_APPLIED(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEG_PLAN_APPLIED_ID    NUMBER(10, 0)    NOT NULL,
    DELEG_PLAN_SID           NUMBER(10, 0)    NOT NULL,
    APPLIED_BY_USER_SID      NUMBER(10, 0)    NOT NULL,
    APPLIED_DTM              DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DELEG_PLAN_LOG PRIMARY KEY (APP_SID, DELEG_PLAN_APPLIED_ID)
);

ALTER TABLE CSR.DELEG_PLAN_DELEG_REGION ADD (
    REGION_COLLATION           VARCHAR2(1)      DEFAULT 'S' NOT NULL,
    CONSTRAINT CHK_DLG_PLN_DLG_RGN_RC CHECK (REGION_COLLATION IN ('S','M'))
);

ALTER TABLE CSR.DELEG_PLAN_APPLIED ADD CONSTRAINT FK_DELEG_PLAN_DP_APPLIED
    FOREIGN KEY (APP_SID, DELEG_PLAN_SID)
    REFERENCES CSR.DELEG_PLAN(APP_SID, DELEG_PLAN_SID);

ALTER TABLE CSR.DELEG_PLAN_APPLIED ADD CONSTRAINT FK_USER_DELEG_PLAN_LOG 
    FOREIGN KEY (APP_SID, APPLIED_BY_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);


@update_tail
