-- Please update version.sql too -- this keeps clean builds in sync
define version=142
@update_header


-- 
-- SEQUENCE: METER_READING_ID_SEQ 
--

CREATE SEQUENCE METER_READING_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: METER 
--

CREATE TABLE METER(
    REGION_SID                        NUMBER(10, 0)     NOT NULL,
    NOTE                              VARCHAR2(4000),
    PRIMARY_IND_SID                   NUMBER(10, 0)     NOT NULL,
    PRIMAY_MEASURE_CONVERSION_ID      NUMBER(10, 0),
    PRO_RATA_IND_SID                  NUMBER(10, 0),
    PRO_RATA_MEASURE_CONVERSION_ID    NUMBER(10, 0),
    CONSTRAINT PK406 PRIMARY KEY (REGION_SID)
)
;



-- 
-- TABLE: METER_READING 
--

CREATE TABLE METER_READING(
    REGION_SID             NUMBER(10, 0)     NOT NULL,
    METER_READING_ID       NUMBER(10, 0)     NOT NULL,
    READING_DTM            DATE              NOT NULL,
    VAL_NUMBER             NUMBER(24, 10)    NOT NULL,
    ENTERED_BY_USER_SID    NUMBER(10, 0)     NOT NULL,
    ENTERED_DTM            DATE               DEFAULT SYSDATE NOT NULL,
    NOTE                   VARCHAR2(4000),
    CONSTRAINT PK407 PRIMARY KEY (METER_READING_ID)
)
;



ALTER TABLE REGION ADD (
    DISPOSAL_DTM          DATE,
    REGION_TYPE           NUMBER(2, 0)      DEFAULT 0 NOT NULL
);

-- assume disposal date is now if active == 0
UPDATE REGION SET disposal_dtm = SYSDATE WHERE active = 0;

-- now add the constraint
ALTER TABLE REGION ADD (
    CONSTRAINT DISPOSAL_DTM_ACTIVE CHECK ((active = 0 AND disposal_dtm IS NOT NULL) OR active = 1)
);


ALTER TABLE METER ADD CONSTRAINT RefIND779 
    FOREIGN KEY (PRIMARY_IND_SID)
    REFERENCES IND(IND_SID)
;

ALTER TABLE METER ADD CONSTRAINT RefMEASURE_CONVERSION780 
    FOREIGN KEY (PRIMAY_MEASURE_CONVERSION_ID)
    REFERENCES MEASURE_CONVERSION(MEASURE_CONVERSION_ID)
;

ALTER TABLE METER ADD CONSTRAINT RefIND781 
    FOREIGN KEY (PRO_RATA_IND_SID)
    REFERENCES IND(IND_SID)
;

ALTER TABLE METER ADD CONSTRAINT RefMEASURE_CONVERSION782 
    FOREIGN KEY (PRO_RATA_MEASURE_CONVERSION_ID)
    REFERENCES MEASURE_CONVERSION(MEASURE_CONVERSION_ID)
;

ALTER TABLE METER ADD CONSTRAINT RefREGION783 
    FOREIGN KEY (REGION_SID)
    REFERENCES REGION(REGION_SID)
;


-- 
-- TABLE: METER_READING 
--

ALTER TABLE METER_READING ADD CONSTRAINT RefCSR_USER784 
    FOREIGN KEY (ENTERED_BY_USER_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE METER_READING ADD CONSTRAINT RefMETER785 
    FOREIGN KEY (REGION_SID)
    REFERENCES METER(REGION_SID)
;



@update_tail
