-- Please update version.sql too -- this keeps clean builds in sync
define version=1988
@update_header

	CREATE TABLE CSR.PLUGIN_LOOKUP (	
		APP_SID 		NUMBER(10,0) 	DEFAULT SYS_CONTEXT('security','app'), 
		PLUGIN_NAME 	VARCHAR2(255) 	NOT NULL,
		LABEL			VARCHAR2(255) 	NOT NULL,
		FORM_PATH 		VARCHAR2(255) 	NOT NULL,
		TABLE_NAME		VARCHAR2(255) 	NOT NULL,
		TABLE_USER		VARCHAR2(255) 	NOT NULL,
		CONSTRAINT PK_PLUGIN_LOOKUP 
			PRIMARY KEY (APP_SID, PLUGIN_NAME)
	);
	
	DROP TABLE CSR.SECTION_PLUGIN_LOOKUP CASCADE CONSTRAINTS;
	
	CREATE TABLE CSR.SECTION_PLUGIN_LOOKUP (	
		APP_SID 		NUMBER(10,0) 	DEFAULT SYS_CONTEXT('security','app'), 
		PLUGIN_NAME 	VARCHAR2(255) 	NOT NULL,
		SECTION_SID		NUMBER(10,0)	NOT NULL,
		CONSTRAINT PK_SECTION_PLUGIN_LOOKUP 
			PRIMARY KEY (APP_SID, PLUGIN_NAME, SECTION_SID),
		CONSTRAINT FK_SECT_SECT_PLUGIN_LOOKUP 
			FOREIGN KEY (APP_SID, SECTION_SID) 
			REFERENCES CSR.SECTION(APP_SID, SECTION_SID) 
			ON DELETE CASCADE,
		CONSTRAINT FK_PLGN_LKUP_SECT_PLGN_LKUP 
			FOREIGN KEY (APP_SID, PLUGIN_NAME) 
			REFERENCES CSR.PLUGIN_LOOKUP(APP_SID, PLUGIN_NAME) 
			ON DELETE CASCADE
	);
	
	INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Use section forms', 0);
	
	@../section_pkg
	@../section_body

@update_tail
