-- Please update version.sql too -- this keeps clean builds in sync
define version=3156
define minor_version=5
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE SURVEYS.IMPORT_MAP(
	APP_SID						NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SURVEY_SID					NUMBER(10, 0)	NOT NULL,
	IMPORT_MAP_ID				NUMBER(10, 0)	NOT NULL,
	IMPORT_MAP_NAME				VARCHAR2(255)	NOT NULL,
	HIDDEN						NUMBER(1)		NOT NULL,
	CONSTRAINT PK_SURVEY_IMPORT_MAP PRIMARY KEY (APP_SID, IMPORT_MAP_ID)
)
;

CREATE TABLE SURVEYS.IMPORT_MAP_ITEM(
	APP_SID						NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	IMPORT_MAP_ID				NUMBER(10, 0)	NOT NULL,
	IMPORT_MAP_ITEM_ID			NUMBER(10, 0)	NOT NULL,
	CELL_PATH					VARCHAR2(255)	NOT NULL,
	DATA_POINT					VARCHAR2(255)	NOT NULL,
	IMPORT_TO					NUMBER(10) 		NOT NULL,
	OTHER_OPTION				VARCHAR2(255)	NULL,
	CONSTRAINT PK_SURVEY_IMPORT_MAP_ITEM PRIMARY KEY (APP_SID, IMPORT_MAP_ITEM_ID)
)
;

CREATE TABLE SURVEYS.IMPORT_MAP_ITEM_TARGET(
	IMPORT_MAP_ITEM_TARGET_ID	NUMBER(10, 0) NOT NULL,
	NAME						VARCHAR2(20),
	CONSTRAINT PK_IMP_MAP_ITEM_TARGET PRIMARY KEY (IMPORT_MAP_ITEM_TARGET_ID)
);
 

CREATE SEQUENCE SURVEYS.IMPORT_MAP_ID_SEQ
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE
;

CREATE SEQUENCE SURVEYS.IMPORT_MAP_ITEM_ID_SEQ
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE
;
 
-- Alter tables
ALTER TABLE SURVEYS.IMPORT_MAP_ITEM ADD CONSTRAINT FK_IMPORT_MAP
	FOREIGN KEY (APP_SID, IMPORT_MAP_ID)
	REFERENCES SURVEYS.IMPORT_MAP(APP_SID, IMPORT_MAP_ID) DEFERRABLE INITIALLY DEFERRED
;

ALTER TABLE SURVEYS.IMPORT_MAP_ITEM ADD CONSTRAINT FK_IMP_MAP_ITEM_TARGET
	FOREIGN KEY (IMPORT_TO)
	REFERENCES SURVEYS.IMPORT_MAP_ITEM_TARGET(IMPORT_MAP_ITEM_TARGET_ID)
;

-- *** Grants ***

CREATE OR REPLACE PACKAGE surveys.import_map_pkg AS
END;
/

CREATE OR REPLACE PACKAGE BODY surveys.import_map_pkg AS
END;
/

GRANT EXECUTE ON surveys.import_map_pkg to web_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data
INSERT INTO SURVEYS.IMPORT_MAP_ITEM_TARGET (IMPORT_MAP_ITEM_TARGET_ID, NAME) VALUES (1, 'Response');
INSERT INTO SURVEYS.IMPORT_MAP_ITEM_TARGET (IMPORT_MAP_ITEM_TARGET_ID, NAME) VALUES (2, 'Comment');
INSERT INTO SURVEYS.IMPORT_MAP_ITEM_TARGET (IMPORT_MAP_ITEM_TARGET_ID, NAME) VALUES (3, 'Other');

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***

--@..\surveys\import_map_pkg
--@..\surveys\import_map_body

@update_tail
