-- Please update version.sql too -- this keeps clean builds in sync
define version=3061
define minor_version=29
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
ALTER TABLE CSR.SCORE_TYPE_AGG_TYPE ADD APPLIES_TO_AUDITS NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE CSR.SCORE_TYPE_AGG_TYPE DROP CONSTRAINT CHK_SCORE_TYPE_AGG_TYPE;

ALTER TABLE CSR.SCORE_TYPE_AGG_TYPE ADD CONSTRAINT CHK_SCORE_TYPE_AGG_TYPE CHECK(
	(APPLIES_TO_NC_SCORE = 1 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 0 AND IA_TYPE_SURVEY_GROUP_ID IS NULL AND APPLIES_TO_AUDITS = 0) OR
	(APPLIES_TO_NC_SCORE = 0 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 1 AND IA_TYPE_SURVEY_GROUP_ID IS NULL AND APPLIES_TO_AUDITS = 0) OR
	(APPLIES_TO_NC_SCORE = 0 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 0 AND IA_TYPE_SURVEY_GROUP_ID IS NOT NULL AND APPLIES_TO_AUDITS = 0) OR
	(APPLIES_TO_NC_SCORE = 0 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 0 AND IA_TYPE_SURVEY_GROUP_ID IS NULL AND APPLIES_TO_AUDITS = 1)
);

ALTER TABLE CSRIMP.SCORE_TYPE_AGG_TYPE ADD APPLIES_TO_AUDITS NUMBER(1) NOT NULL;
ALTER TABLE CSRIMP.SCORE_TYPE_AGG_TYPE DROP CONSTRAINT CHK_SCORE_TYPE_AGG_TYPE;

ALTER TABLE CSRIMP.SCORE_TYPE_AGG_TYPE ADD CONSTRAINT CHK_SCORE_TYPE_AGG_TYPE CHECK(
	(APPLIES_TO_NC_SCORE = 1 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 0 AND IA_TYPE_SURVEY_GROUP_ID IS NULL AND APPLIES_TO_AUDITS = 0) OR
	(APPLIES_TO_NC_SCORE = 0 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 1 AND IA_TYPE_SURVEY_GROUP_ID IS NULL AND APPLIES_TO_AUDITS = 0) OR
	(APPLIES_TO_NC_SCORE = 0 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 0 AND IA_TYPE_SURVEY_GROUP_ID IS NOT NULL AND APPLIES_TO_AUDITS = 0) OR
	(APPLIES_TO_NC_SCORE = 0 AND APPLIES_TO_PRIMARY_AUDIT_SURVY = 0 AND IA_TYPE_SURVEY_GROUP_ID IS NULL AND APPLIES_TO_AUDITS = 1)
);

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../quick_survey_pkg
@../quick_survey_body

@../util_script_body
@../audit_report_body

@update_tail
