-- Please update version.sql too -- this keeps clean builds in sync
define version=518
@update_header

connect cms/cms@&_CONNECT_IDENTIFIER

GRANT EXECUTE ON web_publication_pkg TO csr; 

connect csr/csr@&_CONNECT_IDENTIFIER

DROP TABLE AXIS CASCADE CONSTRAINTS;

DROP TABLE AXIS_MEMBER CASCADE CONSTRAINTS;

-- DROP TABLE RELATED_AXIS CASCADE CONSTRAINTS;

DROP TABLE RELATED_AXIS_MEMBER CASCADE CONSTRAINTS;

DROP TABLE IND_PAGE_PRIMARY_AXIS_MEMBER CASCADE CONSTRAINTS;

DROP TABLE IND_PAGE_RELATED_AXIS_MEMBER CASCADE CONSTRAINTS;


CREATE TABLE CSR.AXIS(
    APP_SID                        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    AXIS_ID                        NUMBER(10, 0)    NOT NULL,
    NAME                           VARCHAR2(255)    NOT NULL,
    LABEL                          VARCHAR2(255)    NOT NULL,
    CMS_TABLE                      VARCHAR2(30)     NOT NULL,
    AXIS_MEMBER_PAGE_TEMPLATE      VARCHAR2(255)    NOT NULL,
    PRIMARY_ACTION_TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    RELATED_ACTION_TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    PRIMARY_TAG_GROUP_ID           NUMBER(10, 0)    NOT NULL,
    RELATED_TAG_GROUP_ID           NUMBER(10, 0)    NOT NULL,
    LEFT_SIDE_TYPE                 NUMBER(1, 0),
    RIGHT_SIDE_TYPE                NUMBER(1, 0),
    LEFT_SIDE_AXIS_ID              NUMBER(10, 0),
    RIGHT_SIDE_AXIS_ID             NUMBER(10, 0),
    CONSTRAINT CS_RIGHT_SIDE CHECK ((RIGHT_SIDE_TYPE = 1 AND RIGHT_SIDE_AXIS_ID IS NOT NULL) OR (RIGHT_SIDE_TYPE IN (2,3) AND RIGHT_SIDE_AXIS_ID IS NULL) OR RIGHT_SIDE_TYPE IS NULL),
    CONSTRAINT CS_LEFT_SIDE CHECK ((LEFT_SIDE_TYPE = 1 AND LEFT_SIDE_AXIS_ID IS NOT NULL) OR (LEFT_SIDE_TYPE IN (2,3) AND LEFT_SIDE_AXIS_ID IS NULL) OR LEFT_SIDE_TYPE IS NULL),
    CHECK (LEFT_SIDE_TYPE IN (1,2,3)),
    CHECK (RIGHT_SIDE_TYPE IN (1,2,3)),
    CONSTRAINT PK_AXIS PRIMARY KEY (APP_SID, AXIS_ID)
)
;

CREATE TABLE CSR.RELATED_AXIS_MEMBER(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    AXIS_MEMBER_ID            NUMBER(10, 0)    NOT NULL,
    RELATED_AXIS_MEMBER_ID    NUMBER(10, 0)    NOT NULL,
    RELATED_AXIS_ID           NUMBER(10, 0)    NOT NULL,
    AXIS_ID                   NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RELATED_AXIS_MEMBER PRIMARY KEY (APP_SID, AXIS_MEMBER_ID, RELATED_AXIS_MEMBER_ID, RELATED_AXIS_ID, AXIS_ID)
)
;

CREATE TABLE CSR.AXIS_MEMBER(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    AXIS_MEMBER_ID           NUMBER(10, 0)    NOT NULL,
    AXIS_ID                  NUMBER(10, 0)    NOT NULL,
    NAME                     VARCHAR2(255)    NOT NULL,
    LABEL                    VARCHAR2(255)    NOT NULL,
    PRIMARY_ACTION_TAG_ID    NUMBER(10, 0)    NOT NULL,
    PRIMARY_TAG_ID           NUMBER(10, 0)    NOT NULL,
    RELATED_TAG_ID           NUMBER(10, 0)    NOT NULL,
    RELATED_ACTION_TAG_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_AXIS_MEMBER PRIMARY KEY (APP_SID, AXIS_MEMBER_ID),
    CONSTRAINT UK_AXIS_MEMBER UNIQUE (APP_SID, AXIS_ID, AXIS_MEMBER_ID)
)
;


CREATE TABLE RELATED_AXIS(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    AXIS_ID            NUMBER(10, 0)    NOT NULL,
    RELATED_AXIS_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RELATED_AXIS PRIMARY KEY (APP_SID, AXIS_ID, RELATED_AXIS_ID)
)
;

-- 
-- TABLE: CSR.AXIS 
--

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_AXIS_REL_AXIS_LEFT 
    FOREIGN KEY (APP_SID, AXIS_ID, LEFT_SIDE_AXIS_ID)
    REFERENCES RELATED_AXIS(APP_SID, AXIS_ID, RELATED_AXIS_ID)
;

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_AXIS_REL_AXIS_RIGHT 
    FOREIGN KEY (APP_SID, AXIS_ID, RIGHT_SIDE_AXIS_ID)
    REFERENCES RELATED_AXIS(APP_SID, AXIS_ID, RELATED_AXIS_ID)
;

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_CUSTOMER_AXIS 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_PRI_ACTION_TAG_GRP 
    FOREIGN KEY (PRIMARY_ACTION_TAG_GROUP_ID, APP_SID)
    REFERENCES ACTIONS.TAG_GROUP(TAG_GROUP_ID, APP_SID)
;

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_PRI_TAG_GROUP_AXIS 
    FOREIGN KEY (APP_SID, PRIMARY_TAG_GROUP_ID)
    REFERENCES TAG_GROUP(APP_SID, TAG_GROUP_ID)
;

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_REL_ACTION_TAG_GRP 
    FOREIGN KEY (RELATED_ACTION_TAG_GROUP_ID, APP_SID)
    REFERENCES ACTIONS.TAG_GROUP(TAG_GROUP_ID, APP_SID)
;

ALTER TABLE CSR.AXIS ADD CONSTRAINT FK_REL_TAG_GROUP_AXIS 
    FOREIGN KEY (APP_SID, RELATED_TAG_GROUP_ID)
    REFERENCES TAG_GROUP(APP_SID, TAG_GROUP_ID)
;


-- 
-- TABLE: CSR.AXIS_MEMBER 
--

ALTER TABLE CSR.AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MEM_ACTION_TAG 
    FOREIGN KEY (PRIMARY_ACTION_TAG_ID, APP_SID)
    REFERENCES ACTIONS.TAG(TAG_ID, APP_SID)
;

ALTER TABLE CSR.AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MEM_ACTION_TAG_REL 
    FOREIGN KEY (RELATED_ACTION_TAG_ID, APP_SID)
    REFERENCES ACTIONS.TAG(TAG_ID, APP_SID)
;

ALTER TABLE CSR.AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MEMBER 
    FOREIGN KEY (APP_SID, AXIS_ID)
    REFERENCES CSR.AXIS(APP_SID, AXIS_ID)
;

ALTER TABLE CSR.AXIS_MEMBER ADD CONSTRAINT FK_CUSTOMER_AXIS_MEMBER 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

ALTER TABLE CSR.AXIS_MEMBER ADD CONSTRAINT FK_TAG_AXIS_MEMBER 
    FOREIGN KEY (APP_SID, PRIMARY_TAG_ID)
    REFERENCES TAG(APP_SID, TAG_ID)
;

ALTER TABLE CSR.AXIS_MEMBER ADD CONSTRAINT FK_TAG_AXIS_MEMBER_REL 
    FOREIGN KEY (APP_SID, RELATED_TAG_ID)
    REFERENCES TAG(APP_SID, TAG_ID)
;

-- 
-- TABLE: CSR.RELATED_AXIS_MEMBER 
--

ALTER TABLE CSR.RELATED_AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MBR_REL_AXIS_MBR 
    FOREIGN KEY (APP_SID, AXIS_ID, RELATED_AXIS_MEMBER_ID)
    REFERENCES CSR.AXIS_MEMBER(APP_SID, AXIS_ID, AXIS_MEMBER_ID)
;

ALTER TABLE CSR.RELATED_AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MBR_REL_AXIS_MBR_REL 
    FOREIGN KEY (APP_SID, AXIS_ID, AXIS_MEMBER_ID)
    REFERENCES CSR.AXIS_MEMBER(APP_SID, AXIS_ID, AXIS_MEMBER_ID)
;

ALTER TABLE CSR.RELATED_AXIS_MEMBER ADD CONSTRAINT FK_REL_AXIS_REL_AXIS_MBR 
    FOREIGN KEY (APP_SID, AXIS_ID, RELATED_AXIS_ID)
    REFERENCES RELATED_AXIS(APP_SID, AXIS_ID, RELATED_AXIS_ID)
;

-- TABLE: RELATED_AXIS 
--

ALTER TABLE RELATED_AXIS ADD CONSTRAINT FK_AXIS_REL_AXIS 
    FOREIGN KEY (APP_SID, RELATED_AXIS_ID)
    REFERENCES CSR.AXIS(APP_SID, AXIS_ID)
;

ALTER TABLE RELATED_AXIS ADD CONSTRAINT FK_AXIS_REL_AXIS_2 
    FOREIGN KEY (APP_SID, AXIS_ID)
    REFERENCES CSR.AXIS(APP_SID, AXIS_ID)
;


-- Create the new strategy package
@..\strategy_pkg
@..\strategy_body

@update_tail

