-- Please update version.sql too -- this keeps clean builds in sync
define version=503
@update_header

ALTER TABLE dataview_ind_member
	ADD NORMALIZATION_IND_SID NUMBER(10, 0);

CREATE TABLE NORMALIZATION_IND(
    APP_SID    NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IND_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK827 PRIMARY KEY (APP_SID, IND_SID)
)
;

ALTER TABLE DATAVIEW_IND_MEMBER ADD CONSTRAINT RefNORMALIZATION_IND1800 
    FOREIGN KEY (APP_SID, NORMALIZATION_IND_SID)
    REFERENCES NORMALIZATION_IND(APP_SID, IND_SID)
;

ALTER TABLE NORMALIZATION_IND ADD CONSTRAINT RefIND1801 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID)
;

@update_tail
