-- Please update version.sql too -- this keeps clean builds in sync
define version=2046
@update_header

-- Data tables
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CSRIMP.PLUGIN_TYPE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CSRIMP.PLUGIN_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_PLUGIN_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PLUGIN_TYPE_ID),
	CONSTRAINT FK_PLUGIN_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CSRIMP.PLUGIN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE CSRIMP.PLUGIN (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PLUGIN_ID NUMBER(10,0) NOT NULL,
	CS_CLASS VARCHAR2(255) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL,
	JS_CLASS VARCHAR2(255) NOT NULL,
	JS_INCLUDE VARCHAR2(255) NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_PLUGIN PRIMARY KEY (CSRIMP_SESSION_ID, PLUGIN_ID),
	CONSTRAINT FK_PLUGIN_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_TYPE_SPACE_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PROPERTY_TYPE_ID NUMBER(10,0) NOT NULL,
	SPACE_TYPE_ID NUMBER(10,0) NOT NULL,
	IS_HIDDEN NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_PROPERTY_TYPE_SPACE_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PROPERTY_TYPE_ID, SPACE_TYPE_ID),
	CONSTRAINT FK_PROPERTY_TYPE_SPACE_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Package grants
GRANT SELECT, INSERT, UPDATE ON CSR.PLUGIN_TYPE TO CSRIMP;
GRANT SELECT, INSERT, UPDATE ON CSR.PLUGIN TO CSRIMP;
GRANT SELECT, INSERT, UPDATE ON CSR.PROPERTY_TYPE_SPACE_TYPE TO CSRIMP;

-- Object grants
GRANT SELECT, INSERT, UPDATE, DELETE ON CSRIMP.PLUGIN_TYPE TO WEB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON CSRIMP.PLUGIN TO WEB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON CSRIMP.PROPERTY_TYPE_SPACE_TYPE TO WEB_USER;

@update_tail
