-- Please update version.sql too -- this keeps clean builds in sync
define version=449
@update_header

CREATE TABLE EXCEL_EXPORT_OPTIONS(
    APP_SID                        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DATAVIEW_SID                   NUMBER(10, 0)    NOT NULL,
    IND_SHOW_SID                   NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    IND_SHOW_INFO                  NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    IND_SHOW_TAGS                  NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_SID                NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_INACTIVE           NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_INFO               NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_TAGS               NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_TYPE               NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_REF                NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_ACQUISITION_DTM    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_DISPOSAL_DTM       NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    REGION_SHOW_ROLES              NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_REF                 NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_LOCATION            NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_SOURCE_TYPE         NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_NOTE                NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_CRC                 NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_IND                 NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_MEASURE             NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_SUPPLIER            NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    METER_SHOW_CONTRACT            NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CHECK (IND_SHOW_SID IN (0,1)),
    CHECK (IND_SHOW_INFO IN (0,1)),
    CHECK (IND_SHOW_TAGS IN (0,1)),
    CHECK (REGION_SHOW_SID IN (0,1)),
    CHECK (REGION_SHOW_INACTIVE IN (0,1)),
    CHECK (REGION_SHOW_INFO IN (0,1)),
    CHECK (REGION_SHOW_TAGS IN (0,1)),
    CHECK (REGION_SHOW_TYPE IN (0,1)),
    CHECK (REGION_SHOW_REF IN (0,1)),
    CHECK (REGION_SHOW_ACQUISITION_DTM IN (0,1)),
    CHECK (REGION_SHOW_DISPOSAL_DTM IN (0,1)),
    CHECK (REGION_SHOW_ROLES IN (0,1)),
    CHECK (METER_SHOW_REF IN (0,1)),
    CHECK (METER_SHOW_LOCATION IN (0,1)),
    CHECK (METER_SHOW_SOURCE_TYPE IN (0,1)),
    CHECK (METER_SHOW_NOTE IN (0,1)),
    CHECK (METER_SHOW_CRC IN (0,1)),
    CHECK (METER_SHOW_IND IN (0,1)),
    CHECK (METER_SHOW_MEASURE IN (0,1)),
    CHECK (METER_SHOW_SUPPLIER IN (0,1)),
    CHECK (METER_SHOW_CONTRACT IN (0,1)),
    CONSTRAINT PK766 PRIMARY KEY (APP_SID, DATAVIEW_SID)
)
;

ALTER TABLE EXCEL_EXPORT_OPTIONS ADD CONSTRAINT RefDATAVIEW1637 
    FOREIGN KEY (APP_SID, DATAVIEW_SID)
    REFERENCES CSR.DATAVIEW(APP_SID, DATAVIEW_SID)
;

@../division_pkg
@../division_body
@../utility_report_pkg
@../utility_report_body
@../excel_export_pkg
@../excel_export_body
@../web_grants
@../rls

@update_tail
