-- Please update version.sql too -- this keeps clean builds in sync
define version=2295
@update_header


CREATE TABLE CSR.PLUGIN_LOOKUP_FLOW_STATE (	
	APP_SID 		NUMBER(10,0) 	DEFAULT SYS_CONTEXT('security','app'), 
	PLUGIN_NAME 	VARCHAR2(255) 	NOT NULL,
    FLOW_SID        NUMBER(10, 0)    NOT NULL,
    FLOW_STATE_ID   NUMBER(10, 0)    NOT NULL,
	CONSTRAINT PK_PLUGIN_LOOKUP_FLOW_STATE 
		PRIMARY KEY (APP_SID, PLUGIN_NAME, FLOW_SID,FLOW_STATE_ID),
	CONSTRAINT FK_PLGN_LKUP_FLW_ST_FLW_ST 
		FOREIGN KEY (APP_SID, FLOW_SID,FLOW_STATE_ID) 
		REFERENCES CSR.SECTION_ROUTED_FLOW_STATE(APP_SID, FLOW_SID, FLOW_STATE_ID)
		ON DELETE CASCADE,
	CONSTRAINT FK_PLGN_LKUP_FLW_ST_PLGN_LKUP 
		FOREIGN KEY (APP_SID, PLUGIN_NAME) 
		REFERENCES CSR.PLUGIN_LOOKUP(APP_SID, PLUGIN_NAME) 
		ON DELETE CASCADE
);

@../section_body
@update_tail