-- Please update version.sql too -- this keeps clean builds in sync
define version=1191
@update_header

ALTER TABLE CT.EC_PROFILE
 DROP CONSTRAINT CC_EC_PROFILE_MB_JOURNEY_KM;

ALTER TABLE CT.EC_PROFILE
 DROP CONSTRAINT CC_EC_PROFILE_CAR_AVG_DIST;

ALTER TABLE CT.EC_PROFILE
 DROP CONSTRAINT CC_EC_PROFILE_BUS_AVG_DIST;

ALTER TABLE CT.EC_PROFILE
 DROP CONSTRAINT CC_EC_PROFILE_BIKE_AVG_DIST;

ALTER TABLE CT.EC_PROFILE
 DROP CONSTRAINT CC_EC_PROFILE_WALK_AVG_DIST;

ALTER TABLE CT.EC_PROFILE
 DROP CONSTRAINT CC_EC_PROFILE_TRAIN_AVG_DIST;

ALTER TABLE ct.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_BIKE_AVG_DIST 
    CHECK (BIKE_AVG_DIST >= 0);

ALTER TABLE ct.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_BUS_AVG_DIST 
    CHECK (BUS_AVG_DIST >= 0);

ALTER TABLE ct.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_CAR_AVG_DIST 
    CHECK (CAR_AVG_DIST >= 0);

ALTER TABLE ct.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_MB_JOURNEY_KM 
    CHECK (MOTORBIKE_AVG_DIST >= 0);

ALTER TABLE ct.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_TRAIN_AVG_DIST 
    CHECK (TRAIN_AVG_DIST >= 0);

ALTER TABLE ct.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_WALK_AVG_DIST 
    CHECK (WALK_AVG_DIST >= 0);

-- emission table by trave mode for EC
CREATE TABLE ct.EC_EMISSIONS (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    BREAKDOWN_ID NUMBER(10) NOT NULL,
    REGION_ID NUMBER(10) NOT NULL,
    CALCULATION_SOURCE_ID NUMBER(10) NOT NULL,
    CAR_KG_CO2 NUMBER(30,10) NOT NULL,
    BUS_KG_CO2 NUMBER(30,10) NOT NULL,
    TRAIN_KG_CO2 NUMBER(30,10) NOT NULL,
    MOTORBIKE_KG_CO2 NUMBER(30,10) NOT NULL,
    BIKE_KG_CO2 NUMBER(30,10) NOT NULL,
    WALK_KG_CO2 NUMBER(30,10) NOT NULL,
    CONSTRAINT PK_EC_EM PRIMARY KEY (APP_SID, BREAKDOWN_ID, REGION_ID, CALCULATION_SOURCE_ID)
);

ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT CC_EC_EM_BIKE_KG_CO2 
    CHECK (BIKE_KG_CO2 >= 0);

ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT CC_EC_EM_BUS_KG_CO2 
    CHECK (BUS_KG_CO2 >= 0);

ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT CC_EC_EM_CAR_KG_CO2 
    CHECK (CAR_KG_CO2 >= 0);

ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT CC_EC_EM_MOTORBIKE_KG_CO2 
    CHECK (MOTORBIKE_KG_CO2 >= 0);

ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT CC_EC_EM_TRAIN_KG_CO2 
    CHECK (TRAIN_KG_CO2 >= 0);

ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT CC_EC_EM_WALK_KG_CO2 
    CHECK (WALK_KG_CO2 >= 0);
	
ALTER TABLE ct.EC_EMISSIONS ADD CONSTRAINT B_R_EC_EM 
    FOREIGN KEY (APP_SID, BREAKDOWN_ID, REGION_ID) REFERENCES ct.BREAKDOWN_REGION (APP_SID,BREAKDOWN_ID,REGION_ID);
	
@..\ct\breakdown_body
@..\ct\breakdown_type_body
@..\ct\business_travel_pkg
@..\ct\business_travel_body
@..\ct\emp_commute_body
@..\ct\emp_commute_pkg
@..\ct\link_body
@..\ct\value_chain_report_pkg
@..\ct\value_chain_report_body

	
@update_tail
