-- Please update version.sql too -- this keeps clean builds in sync
define version=3495
define minor_version=8
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
ALTER TABLE csr.ind DROP CONSTRAINT CHK_TOLERANCE_NUMBER_OF_PERIODS;
ALTER TABLE csr.ind DROP CONSTRAINT CHK_TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE;

UPDATE csr.ind
   SET TOLERANCE_NUMBER_OF_PERIODS = 3, TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE = 0.5
 WHERE TOLERANCE_TYPE IN (3, 4) AND 
 	(TOLERANCE_NUMBER_OF_PERIODS IS NULL OR TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE IS NULL)
;
  

ALTER TABLE csr.ind ADD CONSTRAINT CHK_IND_TOLERANCE CHECK (
	TOLERANCE_TYPE = 0
	OR (TOLERANCE_TYPE IN (1, 2) AND PCT_UPPER_TOLERANCE IS NOT NULL AND PCT_LOWER_TOLERANCE IS NOT NULL)
	OR (TOLERANCE_TYPE IN (3, 4) AND TOLERANCE_NUMBER_OF_PERIODS IS NOT NULL AND TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE IS NOT NULL)	
);

ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_NUMBER_OF_PERIODS CHECK (
    TOLERANCE_TYPE = 0
	OR (TOLERANCE_TYPE = 1 AND TOLERANCE_NUMBER_OF_PERIODS >= 1 AND TOLERANCE_NUMBER_OF_PERIODS <= 99)
	OR (TOLERANCE_TYPE = 2 AND TOLERANCE_NUMBER_OF_PERIODS >= 1 AND TOLERANCE_NUMBER_OF_PERIODS <= 8)
	OR (TOLERANCE_TYPE = 3 AND TOLERANCE_NUMBER_OF_PERIODS >= 3 AND TOLERANCE_NUMBER_OF_PERIODS <= 99)
	OR (TOLERANCE_TYPE = 4 AND TOLERANCE_NUMBER_OF_PERIODS >= 3 AND TOLERANCE_NUMBER_OF_PERIODS <= 8)
);

ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE CHECK (
	TOLERANCE_TYPE < 3
	OR (TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE >= 0 AND TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE <= 5)
);

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***

@update_tail
