-- Please update version.sql too -- this keeps clean builds in sync
define version=1879
@update_header

CREATE OR REPLACE TYPE CSR.T_AGGREGATE_VAL_ROW AS
  OBJECT (
    IND_SID         NUMBER(10),
    REGION_SID      NUMBER(10),
    START_DTM       DATE,
    END_DTM         DATE,
    VAL_NUMBER      NUMBER(24, 10)
  );
/
CREATE OR REPLACE TYPE CSR.T_AGGREGATE_VAL_TABLE AS
  TABLE OF CSR.T_AGGREGATE_VAL_ROW;
/

CREATE SEQUENCE CSR.FLOW_STATE_GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE SEQUENCE CSR.INITIATIVE_METRID_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

ALTER TABLE CSR.INITIATIVE_METRIC DROP COLUMN IND_SID CASCADE CONSTRAINTS;

ALTER TABLE CSR.INITIATIVE_METRIC ADD (
    MEASURE_SID             NUMBER(10, 0)     NOT NULL,
    CONSTRAINT CONS_INIT_METRIC_MEASURE  UNIQUE (APP_SID, INITIATIVE_METRIC_ID, MEASURE_SID)
)
;

CREATE TABLE CSR.AGGR_REGION(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SID         NUMBER(10, 0)    NOT NULL,
    AGGR_REGION_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_AGGR_REGION PRIMARY KEY (APP_SID, REGION_SID)
)
;

CREATE TABLE CSR.FLOW_STATE_GROUP(
    APP_SID                NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FLOW_STATE_GROUP_ID    NUMBER(10, 0)     NOT NULL,
    LOOKUP_KEY             VARCHAR2(256)     NOT NULL,
    LABEL                  VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK_FLOW_STATE_GROUP PRIMARY KEY (APP_SID, FLOW_STATE_GROUP_ID)
)
;

CREATE TABLE CSR.FLOW_STATE_GROUP_MEMBER(
    APP_SID                NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    FLOW_STATE_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    FLOW_STATE_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_FLOW_STATE_GROUP_MEMBER PRIMARY KEY (APP_SID, FLOW_STATE_GROUP_ID, FLOW_STATE_ID)
)
;

CREATE TABLE CSR.INITIATIVE_METRIC_IND(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    INITIATIVE_METRIC_ID    NUMBER(10, 0)    NOT NULL,
    FLOW_STATE_GROUP_ID     NUMBER(10, 0)    NOT NULL,
    IND_SID                 NUMBER(10, 0)    NOT NULL,
    MEASURE_SID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_INITIATIVE_METRIC_IND PRIMARY KEY (APP_SID, INITIATIVE_METRIC_ID, FLOW_STATE_GROUP_ID)
)
;

ALTER TABLE CSR.AGGR_REGION ADD CONSTRAINT FK_REGION_AGGR_REGION
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.AGGR_REGION ADD CONSTRAINT FK_REGION_AGGR_AGREGION
    FOREIGN KEY (APP_SID, AGGR_REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;   

ALTER TABLE CSR.FLOW_STATE_GROUP ADD CONSTRAINT FK_CUSTOMER_FLSTGRP
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.FLOW_STATE_GROUP_MEMBER ADD CONSTRAINT FK_FLST_FLSTGRPMBR
    FOREIGN KEY (APP_SID, FLOW_STATE_ID)
    REFERENCES CSR.FLOW_STATE(APP_SID, FLOW_STATE_ID)
;

ALTER TABLE CSR.FLOW_STATE_GROUP_MEMBER ADD CONSTRAINT FK_FLSTGRP_FLSTGRPMBR
    FOREIGN KEY (APP_SID, FLOW_STATE_GROUP_ID)
    REFERENCES CSR.FLOW_STATE_GROUP(APP_SID, FLOW_STATE_GROUP_ID)
;

ALTER TABLE CSR.INITIATIVE_METRIC_IND ADD CONSTRAINT FK_INTIMET_INITMETIND_MEAS
    FOREIGN KEY (APP_SID, INITIATIVE_METRIC_ID, MEASURE_SID)
    REFERENCES CSR.INITIATIVE_METRIC(APP_SID, INITIATIVE_METRIC_ID, MEASURE_SID)
;

ALTER TABLE CSR.INITIATIVE_METRIC_IND ADD CONSTRAINT FK_FLSTGRP_INITMETIND
    FOREIGN KEY (APP_SID, FLOW_STATE_GROUP_ID)
    REFERENCES CSR.FLOW_STATE_GROUP(APP_SID, FLOW_STATE_GROUP_ID)
;

ALTER TABLE CSR.INITIATIVE_METRIC_IND ADD CONSTRAINT FK_IND_INITMETIND
    FOREIGN KEY (APP_SID, IND_SID, MEASURE_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID, MEASURE_SID)
;

ALTER TABLE CSR.INITIATIVE_METRIC_IND ADD CONSTRAINT FK_INTIMET_INITMETIND
    FOREIGN KEY (APP_SID, INITIATIVE_METRIC_ID)
    REFERENCES CSR.INITIATIVE_METRIC(APP_SID, INITIATIVE_METRIC_ID)
;

CREATE INDEX CSR.IX_REGION_AGGR_AGREGION ON CSR.AGGR_REGION(APP_SID, AGGR_REGION_SID);
CREATE INDEX CSR.IX_CUSTOMER_FLSTGRP ON CSR.FLOW_STATE_GROUP(APP_SID);
CREATE INDEX CSR.IX_FLST_FLSTGRPMBR ON CSR.FLOW_STATE_GROUP_MEMBER (APP_SID, FLOW_STATE_ID);
CREATE INDEX CSR.IX_FLSTGRP_FLSTGRPMBR ON CSR.FLOW_STATE_GROUP_MEMBER (APP_SID, FLOW_STATE_GROUP_ID);
CREATE INDEX CSR.IX_INTIMET_INITMETIND_MEAS ON CSR.INITIATIVE_METRIC_IND (APP_SID, INITIATIVE_METRIC_ID, MEASURE_SID);
CREATE INDEX CSR.IX_FLSTGRP_INITMETIND ON CSR.INITIATIVE_METRIC_IND (APP_SID, FLOW_STATE_GROUP_ID);
CREATE INDEX CSR.IX_IND_INITMETIND ON CSR.INITIATIVE_METRIC_IND (APP_SID, IND_SID);
CREATE INDEX CSR.IX_INTIMET_INITMETIND ON CSR.INITIATIVE_METRIC_IND (APP_SID, INITIATIVE_METRIC_ID);

BEGIN
    INSERT INTO CSR.region_type
        (region_type, label, class_name)
      VALUES(10, 'Aggregate region', 'CSRAggrRegion');
END;
/

ALTER TABLE CSR.PROJECT_INIT_METRIC_FLOW_STATE DROP CONSTRAINT PK_PRJ_INIT_METRIC_FLOW_STATE;
ALTER TABLE CSR.PROJECT_INIT_METRIC_FLOW_STATE ADD(
    CONSTRAINT PK_PRJ_INIT_METRIC_FLOW_STATE PRIMARY KEY (APP_SID, INITIATIVE_METRIC_ID, FLOW_STATE_ID, PROJECT_SID)
);

@../initiative_metric_pkg
@../initiative_pkg
@../initiative_doc_pkg
@../initiative_project_pkg
@../initiative_import_pkg
@../initiative_aggr_pkg

@../initiative_metric_body
@../initiative_body
@../initiative_doc_body
@../initiative_project_body
@../initiative_import_body
@../initiative_aggr_body

grant execute on csr.initiative_aggr_pkg to web_user;

@update_tail
