-- Please update version.sql too -- this keeps clean builds in sync
define version=216
@update_header

-- constraint tweaks
ALTER TABLE CUSTOMER DROP CONSTRAINT RefREPORTING_PERIOD658 ;

ALTER TABLE CUSTOMER ADD CONSTRAINT RefREPORTING_PERIOD658 
    FOREIGN KEY (CURRENT_REPORTING_PERIOD_SID)
    REFERENCES REPORTING_PERIOD(REPORTING_PERIOD_SID)
 DEFERRABLE INITIALLY DEFERRED;


@update_tail