-- Please update version.sql too -- this keeps clean builds in sync
define version=1142
@update_header

ALTER TABLE CT.BT_OPTIONS DROP CONSTRAINT PK_BT_OPT;
ALTER TABLE CT.BT_OPTIONS ADD CONSTRAINT PK_BT_OPT PRIMARY KEY (APP_SID, COMPANY_SID);

ALTER TABLE CT.EC_OPTIONS DROP CONSTRAINT PK_EC_OPT;
ALTER TABLE CT.EC_OPTIONS ADD CONSTRAINT PK_EC_OPT PRIMARY KEY (APP_SID, COMPANY_SID);

ALTER TABLE CT.PS_OPTIONS DROP CONSTRAINT PK_PS_OPT;
ALTER TABLE CT.PS_OPTIONS ADD CONSTRAINT PK_PS_OPT PRIMARY KEY (APP_SID, COMPANY_SID);

ALTER TABLE CT.UP_OPTIONS DROP CONSTRAINT PK_UP_OPT;
ALTER TABLE CT.UP_OPTIONS ADD CONSTRAINT PK_UP_OPT PRIMARY KEY (APP_SID, COMPANY_SID);

-- initially default to 25 update existing data
ALTER TABLE CT.EC_PROFILE ADD ANNUAL_LEAVE_DAYS NUMBER(20,10) DEFAULT 25 NOT NULL;
-- now drop the default
ALTER TABLE CT.EC_PROFILE MODIFY ANNUAL_LEAVE_DAYS NUMBER(20,10) DEFAULT NULL;
ALTER TABLE CT.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_ANN_LEAVE 
    CHECK (ANNUAL_LEAVE_DAYS >= 0 AND ANNUAL_LEAVE_DAYS <=366);
	
ALTER TABLE CT.EC_PROFILE ADD MODIFIED_BY_SID NUMBER(10);
ALTER TABLE CT.EC_PROFILE ADD LAST_MODIFIED_DTM DATE;
	
ALTER TABLE CT.EC_PROFILE ADD CONSTRAINT CSR_USR_EC_PROFILE 
    FOREIGN KEY (APP_SID, MODIFIED_BY_SID) REFERENCES CSR.CSR_USER (APP_SID,CSR_USER_SID);

ALTER TABLE CT.EC_PROFILE ADD CONSTRAINT CC_EC_PROFILE_MODIFIED_BY_SID 
	CHECK ((MODIFIED_BY_SID IS NULL AND LAST_MODIFIED_DTM IS NULL) OR (MODIFIED_BY_SID IS NOT NULL AND LAST_MODIFIED_DTM IS NOT NULL));
	
ALTER TABLE CT.BT_PROFILE ADD MODIFIED_BY_SID NUMBER(10);
ALTER TABLE CT.BT_PROFILE ADD LAST_MODIFIED_DTM DATE;
	
ALTER TABLE CT.BT_PROFILE ADD CONSTRAINT CC_BT_PRF_MODIFIED_BY_SID 
    CHECK ((MODIFIED_BY_SID IS NULL AND LAST_MODIFIED_DTM IS NULL) OR (MODIFIED_BY_SID IS NOT NULL AND LAST_MODIFIED_DTM IS NOT NULL));
	
	
ALTER TABLE CT.BT_PROFILE ADD CONSTRAINT CSR_USR_BT_PRF 
    FOREIGN KEY (APP_SID, MODIFIED_BY_SID) REFERENCES CSR.CSR_USER (APP_SID,CSR_USER_SID);
	
@..\ct\breakdown_pkg
@..\ct\breakdown_body
@..\ct\breakdown_group_pkg
@..\ct\breakdown_group_body
@..\ct\emp_commute_pkg
@..\ct\emp_commute_body
@..\ct\business_travel_pkg
@..\ct\business_travel_body
@..\ct\snapshot_pkg
@..\ct\snapshot_body

@update_tail
