-- Please update version.sql too -- this keeps clean builds in sync
define version=643
@update_header

CREATE TABLE csr.DELEG_FOR_TPL(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEGATION_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK924 PRIMARY KEY (APP_SID, DELEGATION_SID)
)
;

ALTER TABLE csr.DELEG_FOR_TPL ADD CONSTRAINT RefDELEGATION2046 
    FOREIGN KEY (APP_SID, DELEGATION_SID)
    REFERENCES csr.DELEGATION(APP_SID, DELEGATION_SID)
;

ALTER TABLE csr.DELEG_TPL_DELEG DROP CONSTRAINT RefDELEGATION1974;

ALTER TABLE csr.DELEG_TPL_DELEG ADD CONSTRAINT RefDELEGATION1974 
    FOREIGN KEY (APP_SID, MAP_TO_DELEG_SID)
    REFERENCES csr.DELEGATION(APP_SID, DELEGATION_SID)
;

ALTER TABLE csr.DELEG_TPL_DELEG ADD CONSTRAINT RefDELEG_FOR_TPL2047 
    FOREIGN KEY (APP_SID, DELEGATION_SID)
    REFERENCES csr.DELEG_FOR_TPL(APP_SID, DELEGATION_SID)
;

@update_tail
