-- Please update version.sql too -- this keeps clean builds in sync
define version=2953
define minor_version=7
@update_header

-- *** DDL ***
-- Create tables

CREATE TABLE CHAIN.BSCI_OPTIONS (
	APP_SID							NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	USER_NAME						VARCHAR2(255) NOT NULL,
	PASSWORD						VARCHAR2(255) NOT NULL,
	AUDIT_TYPE_2009_ID				NUMBER(10),
	AUDIT_TYPE_2014_ID				NUMBER(10),
	AUDIT_SCORE_SYNC_ENABLED		NUMBER(1) DEFAULT 0 NOT NULL,
	LAST_AUDIT_SCORE_SYNC_DTM		DATE NULL,
	SUPPLIER_SYNC_ENABLED 			NUMBER(1) DEFAULT 0 NOT NULL,
	LAST_SUPPLIER_SYNC_DTM 			DATE NULL,
	CONSTRAINT PK_BSCI_OPTIONS PRIMARY KEY (APP_SID),
	CONSTRAINT CHK_AUDIT_SCORE_SYNC_ENABLED CHECK (AUDIT_SCORE_SYNC_ENABLED IN (0,1))
);

CREATE TABLE CHAIN.BSCI_AUDIT_2009 (
	APP_SID 					NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	COMPANY_SID 				NUMBER(10,0) NOT NULL,
	AUDIT_REF 					NUMBER(10,0) NOT NULL,
	AUDIT_DATE					DATE NOT NULL,
	AUDIT_EXPIRY_DATE 			DATE NOT NULL,
	AUDIT_SCORE 				NUMBER(10,0) NOT NULL,
	AUDIT_ANNOUNCED 			NUMBER(1) NOT NULL,
	AUDIT_STAGE 				VARCHAR2(255) NOT NULL,
	AUDIT_SUCCESS 				NUMBER(1) NOT NULL,
	AUDIT_ENVIRONMENT 			VARCHAR2(255) NULL,
	LEAD_AUDITOR_NAME			VARCHAR2(255) NULL,
	MAN_DAYS					NUMBER(10,0) NULL,
	AUDITOR_COMMENTS 			VARCHAR2(4000) NULL,
	CYCLE 						VARCHAR2(255) NULL,
	TOTAL_TURNOVER 				NUMBER(10,0),
	INTERVIEW_ESSENTIALS 		VARCHAR2(4000) NULL,
	CONSTRAINT PK_BSCI_AUDIT_2009 PRIMARY KEY (APP_SID, AUDIT_REF),
	CONSTRAINT CHK_AUDIT_ANNOUNCED_2009 CHECK (AUDIT_ANNOUNCED IN (0,1)),
	CONSTRAINT FK_BSCI_AUDIT_2009_COMPANY_SID FOREIGN KEY (APP_SID, COMPANY_SID) REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID)
);

CREATE TABLE CHAIN.BSCI_AUDIT_2014 (
	APP_SID 					NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	COMPANY_SID 				NUMBER(10,0) NOT NULL,
	AUDIT_REF 					NUMBER(10,0) NOT NULL,
	AUDIT_DATE					DATE NOT NULL,
	AUDIT_EXPIRY_DATE 			DATE NOT NULL,
	AUDIT_SCORE 				NUMBER(10,0) NOT NULL,
	AUDIT_ANNOUNCED 			NUMBER(1) NOT NULL,
	AUDIT_STAGE 				VARCHAR2(255) NOT NULL,
	AUDIT_SUCCESS 				NUMBER(1) NOT NULL,
	AUDIT_ENVIRONMENT 			VARCHAR2(255) NULL,
	LEAD_AUDITOR_NAME			VARCHAR2(255) NULL,
	AUDITING_COMPANY 			VARCHAR2(255) NULL,
	AUDITING_COMPANY_BRANCH 	VARCHAR2(255) NULL,
	MAN_DAYS					NUMBER(10,0) NULL,
	NEED_FOLLOW_UP 				VARCHAR2(255) NULL,
	INTERVIEW_ESSENTIALS 		VARCHAR2(4000) NULL,
	CONSTRAINT PK_BSCI_AUDIT_2014 PRIMARY KEY (APP_SID, AUDIT_REF),
	CONSTRAINT CHK_AUDIT_ANNOUNCED_2014 CHECK (AUDIT_ANNOUNCED IN (0,1)),
	CONSTRAINT FK_BSCI_AUDIT_2014_COMPANY_SID FOREIGN KEY (APP_SID, COMPANY_SID) REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID)
);

CREATE TABLE CHAIN.BSCI_FINDING (
	APP_SID 			NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	AUDIT_TYPE_ID 		NUMBER(10,0) NOT NULL,
	AUDIT_REF_2009		NUMBER(10,0) NULL,
	AUDIT_REF_2014 		NUMBER(10,0) NULL,
	MSI_CATEGORY 		VARCHAR2(255) NOT NULL,
	MSI_SUB_CATEGORY 	VARCHAR2(255) NULL,
	SCORE 				NUMBER(10,0) NOT NULL,
	SUMMARY		 		VARCHAR2(4000) NULL,
	QUESTION 			VARCHAR2(2000) NULL,
	GUIDELINES 			VARCHAR2(4000) NULL,
	CONSTRAINT FK_BSCI_AUDIT_2009_REF FOREIGN KEY (APP_SID, AUDIT_REF_2009) REFERENCES CHAIN.BSCI_AUDIT_2009 (APP_SID, AUDIT_REF),
	CONSTRAINT FK_BSCI_AUDIT_2014_REF FOREIGN KEY (APP_SID, AUDIT_REF_2014) REFERENCES CHAIN.BSCI_AUDIT_2014 (APP_SID, AUDIT_REF),
	CONSTRAINT CHK_BSCI_AUDIT_TYPE CHECK ((AUDIT_REF_2009 IS NOT NULL AND AUDIT_REF_2014 IS NOT NULL) OR (AUDIT_REF_2009 IS NULL AND AUDIT_REF_2014 IS NOT NULL) OR (AUDIT_REF_2009 IS NOT NULL AND AUDIT_REF_2014 IS NULL))
);

CREATE TABLE CHAIN.BSCI_ASSOCIATE (
	APP_SID 			NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	ASSOCIATE 			VARCHAR2(255) NOT NULL,
	ASSOCIATE_COUNT 	NUMBER(10,0) NOT NULL,
	AUDIT_REF_2009		NUMBER(10,0) NULL,
	AUDIT_REF_2014 		NUMBER(10,0) NULL,
	CONSTRAINT FK_BSCI_AUDIT_REF_ASS_2014 FOREIGN KEY (APP_SID, AUDIT_REF_2014) REFERENCES CHAIN.BSCI_AUDIT_2014 (APP_SID, AUDIT_REF),
	CONSTRAINT FK_BSCI_AUDIT_REF_ASS_2009 FOREIGN KEY (APP_SID, AUDIT_REF_2009) REFERENCES CHAIN.BSCI_AUDIT_2009 (APP_SID, AUDIT_REF)
);

CREATE TABLE CHAIN.BSCI_SUPPLIER (
    APP_SID                     NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    BSCI_FACTORY_ID             NUMBER(10) NOT NULL,
    COMPANY_SID                 NUMBER(10) NULL,
    ADDRESS                     VARCHAR2(255) NOT NULL,
    CITY                        VARCHAR2(255) NOT NULL,
    INDUSTRY                    VARCHAR2(255) NOT NULL,
    COUNTRY                     VARCHAR2(255) NOT NULL,
    POSTCODE                    VARCHAR2(255) NOT NULL,
    REGION                      VARCHAR2(255) NULL,
    TERRITORY                   VARCHAR2(255) NULL,
    ADDRESS_LOCATION_TYPE       VARCHAR2(255) NOT NULL,
    ALIAS                       VARCHAR2(255) NULL,
    AUDIT_ANNOUNCEMENT_METHOD   VARCHAR2(255) NULL,
    FACTORY_CONTACT             VARCHAR2(255) NOT NULL,
    AUDIT_EXPIRATION_DATE       DATE NULL,
    AUDIT_IN_PROGRESS           VARCHAR2(255) NULL,
    AUDIT_RESULT                VARCHAR2(255) NULL,
    BSCI_COMMENTS               VARCHAR2(4000) NULL,
    LINKED_PARTICIPANTS         VARCHAR2(255) NULL,
    IN_COMMITMENTS              VARCHAR2(255) NULL,
    IN_SUPPLY_CHAIN             VARCHAR2(255) NULL,
    LEGAL_STATUS                VARCHAR2(255) NULL,
    NAME                        VARCHAR2(255) NULL,
    NUMBER_OF_ASSOCIATES        NUMBER(10) NULL,
    NUMBER_OF_BUILDINGS         NUMBER(10) NULL,
    PARTICIPANT_NAME            VARCHAR2(255) NULL,
    PRODUCT_GROUP               VARCHAR2(255) NULL,
    PRODUCT_TYPE                VARCHAR2(255) NULL,
    CODE_OF_CONDUCT_ACCEPTED    VARCHAR2(255) NULL,
    CODE_OF_CONDUCT_SIGNED      VARCHAR2(255) NULL,
    AUDIT_DATE                  DATE NULL,
    SECTOR                      VARCHAR2(255) NULL,
    WEBSITE                     VARCHAR2(255) NULL,
    YEAR_FOUNDED                NUMBER(10),
    AUDIT_TYPE 					VARCHAR2(255) NULL,
    LAST_UPDATED_DATE			DATE NOT NULL,
    CONSTRAINT FK_BSCI_SUPPLIER_COMP FOREIGN KEY (APP_SID, COMPANY_SID) REFERENCES CHAIN.COMPANY (APP_SID, COMPANY_SID),
    CONSTRAINT UK_BSCI_SUPPLIER_ID UNIQUE (APP_SID, BSCI_FACTORY_ID),
    CONSTRAINT UK_BSCI_SUP_NAME_COUNTRY UNIQUE (APP_SID, NAME, COUNTRY)
);

CREATE TABLE CSRIMP.CHAIN_BSCI_OPTIONS (
	CSRIMP_SESSION_ID				NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	USER_NAME						VARCHAR2(255) NOT NULL,
	PASSWORD						VARCHAR2(255) NOT NULL,
	AUDIT_TYPE_2009_ID				NUMBER(10),
	AUDIT_TYPE_2014_ID				NUMBER(10),
	AUDIT_SCORE_SYNC_ENABLED		NUMBER(1) NOT NULL,
	LAST_AUDIT_SCORE_SYNC_DTM		DATE NULL,
	SUPPLIER_SYNC_ENABLED			NUMBER(1) NOT NULL,
	LAST_SUPPLIER_SYNC_DTM 			DATE NULL,
	CONSTRAINT PK_BSCI_OPTIONS PRIMARY KEY (CSRIMP_SESSION_ID),
	CONSTRAINT FK_BO_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BSCI_AUDIT_2009 (
    CSRIMP_SESSION_ID       NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    COMPANY_SID             NUMBER(10,0) NOT NULL,
    AUDIT_REF               NUMBER(10,0) NOT NULL,
    AUDIT_DATE              DATE NOT NULL,
    AUDIT_EXPIRY_DATE       DATE NOT NULL,
    AUDIT_SCORE             NUMBER(10,0) NOT NULL,
    AUDIT_ANNOUNCED         NUMBER(1) NOT NULL,
    AUDIT_STAGE             VARCHAR2(255) NOT NULL,
    AUDIT_SUCCESS               NUMBER(1) NOT NULL,
    AUDIT_ENVIRONMENT       VARCHAR2(255) NULL,
    LEAD_AUDITOR_NAME       VARCHAR2(255) NULL,
    MAN_DAYS                NUMBER(10,0) NULL,
    AUDITOR_COMMENTS        VARCHAR2(4000) NULL,
    CYCLE                   VARCHAR2(255) NULL,
    TOTAL_TURNOVER          NUMBER(10,0),
    INTERVIEW_ESSENTIALS    VARCHAR2(4000) NULL,
    CONSTRAINT PK_BSCI_AUDIT_2009 PRIMARY KEY (CSRIMP_SESSION_ID, AUDIT_REF),
    CONSTRAINT CHK_AUDIT_ANNOUNCED_2009 CHECK (AUDIT_ANNOUNCED IN (0,1)),
    CONSTRAINT FK_BA_2009_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BSCI_AUDIT_2014 (
    CSRIMP_SESSION_ID           NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    COMPANY_SID                 NUMBER(10,0) NOT NULL,
    AUDIT_REF                   NUMBER(10,0) NOT NULL,
    AUDIT_DATE                  DATE NOT NULL,
    AUDIT_EXPIRY_DATE           DATE NOT NULL,
    AUDIT_SCORE                 NUMBER(10,0) NOT NULL,
    AUDIT_ANNOUNCED             NUMBER(1) NOT NULL,
    AUDIT_STAGE                 VARCHAR2(255) NOT NULL,
    AUDIT_SUCCESS               NUMBER(1) NOT NULL,
    AUDIT_ENVIRONMENT           VARCHAR2(255) NULL,
    LEAD_AUDITOR_NAME           VARCHAR2(255) NULL,
    AUDITING_COMPANY            VARCHAR2(255) NULL,
    AUDITING_COMPANY_BRANCH     VARCHAR2(255) NULL,
    MAN_DAYS                    NUMBER(10,0) NULL,
    NEED_FOLLOW_UP              VARCHAR2(255) NULL,
    INTERVIEW_ESSENTIALS        VARCHAR2(4000) NULL,
    CONSTRAINT PK_BSCI_AUDIT_2014 PRIMARY KEY (CSRIMP_SESSION_ID, AUDIT_REF),
    CONSTRAINT CHK_AUDIT_ANNOUNCED_2014 CHECK (AUDIT_ANNOUNCED IN (0,1)),
    CONSTRAINT FK_BA_2014_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BSCI_FINDING (
    CSRIMP_SESSION_ID   NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    AUDIT_TYPE_ID       NUMBER(10,0) NOT NULL,
    AUDIT_REF_2009      NUMBER(10,0) NULL,
    AUDIT_REF_2014      NUMBER(10,0) NULL,
    MSI_CATEGORY        VARCHAR2(255) NOT NULL,
    MSI_SUB_CATEGORY    VARCHAR2(255) NULL,
    SCORE               NUMBER(10,0) NOT NULL,
    SUMMARY             VARCHAR2(4000) NULL,
    QUESTION            VARCHAR2(2000) NULL,
    GUIDELINES          VARCHAR2(4000) NULL,
    CONSTRAINT CHK_BSCI_AUDIT_TYPE CHECK ((AUDIT_REF_2009 IS NOT NULL AND AUDIT_REF_2014 IS NOT NULL) OR (AUDIT_REF_2009 IS NULL AND AUDIT_REF_2014 IS NOT NULL) OR (AUDIT_REF_2009 IS NOT NULL AND AUDIT_REF_2014 IS NULL)),
    CONSTRAINT FK_BF_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BSCI_ASSOCIATE (
    CSRIMP_SESSION_ID   NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    ASSOCIATE           VARCHAR2(255) NOT NULL,
    ASSOCIATE_COUNT     NUMBER(10,0) NOT NULL,
    AUDIT_REF_2009      NUMBER(10,0) NULL,
    AUDIT_REF_2014      NUMBER(10,0) NULL,
    CONSTRAINT FK_BSCI_ASS_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BSCI_SUPPLIER (
    CSRIMP_SESSION_ID           NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    BSCI_FACTORY_ID             NUMBER(10) NOT NULL,
    COMPANY_SID                 NUMBER(10) NULL,
    ADDRESS                     VARCHAR2(255) NOT NULL,
    CITY                        VARCHAR2(255) NOT NULL,
    INDUSTRY                    VARCHAR2(255) NOT NULL,
    COUNTRY                     VARCHAR2(255) NOT NULL,
    POSTCODE                    VARCHAR2(255) NOT NULL,
    REGION                      VARCHAR2(255) NULL,
    TERRITORY                   VARCHAR2(255) NULL,
    ADDRESS_LOCATION_TYPE       VARCHAR2(255) NOT NULL,
    ALIAS                       VARCHAR2(255) NULL,
    AUDIT_ANNOUNCEMENT_METHOD   VARCHAR2(255) NULL,
    FACTORY_CONTACT             VARCHAR2(255) NOT NULL,
    AUDIT_EXPIRATION_DATE       DATE NULL,
    AUDIT_IN_PROGRESS           VARCHAR2(255) NULL,
    AUDIT_RESULT                VARCHAR2(255) NULL,
    BSCI_COMMENTS               VARCHAR2(4000) NULL,
    LINKED_PARTICIPANTS         VARCHAR2(255) NULL,
    IN_COMMITMENTS              VARCHAR2(255) NULL,
    IN_SUPPLY_CHAIN             VARCHAR2(255) NULL,
    LEGAL_STATUS                VARCHAR2(255) NULL,
    NAME                        VARCHAR2(255) NULL,
    NUMBER_OF_ASSOCIATES        NUMBER(10) NULL,
    NUMBER_OF_BUILDINGS         NUMBER(10) NULL,
    PARTICIPANT_NAME            VARCHAR2(255) NULL,
    PRODUCT_GROUP               VARCHAR2(255) NULL,
    PRODUCT_TYPE                VARCHAR2(255) NULL,
    CODE_OF_CONDUCT_ACCEPTED    VARCHAR2(255) NULL,
    CODE_OF_CONDUCT_SIGNED      VARCHAR2(255) NULL,
    AUDIT_DATE                  DATE NULL,
    SECTOR                      VARCHAR2(255) NULL,
    WEBSITE                     VARCHAR2(255) NULL,
    YEAR_FOUNDED                NUMBER(10),
    AUDIT_TYPE                  VARCHAR2(255) NULL,
    LAST_UPDATED_DATE           DATE NOT NULL,
    CONSTRAINT FK_BSCI_SUPPLIER_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Alter tables
ALTER TABLE CSR.AUDIT_CLOSURE_TYPE ADD LOOKUP_KEY VARCHAR2(255);
ALTER TABLE CSRIMP.AUDIT_CLOSURE_TYPE ADD LOOKUP_KEY VARCHAR2(255);

CREATE UNIQUE INDEX CSR.UK_AUDIT_CLOS_TYPE_LKUP_KEY ON CSR.AUDIT_CLOSURE_TYPE (APP_SID, NVL(UPPER(LOOKUP_KEY), TO_CHAR(AUDIT_CLOSURE_TYPE_ID)));

DROP INDEX csr.uk_internal_audit_ref_type;
 
CREATE UNIQUE INDEX csr.uk_internal_audit_ref_type 
		ON csr.internal_audit (
			CASE WHEN internal_audit_ref IS NULL OR deleted = 1 THEN NULL 
				 ELSE app_sid ||'_'|| internal_audit_type_id ||'_'|| internal_audit_ref END
		);


-- *** Grants ***
GRANT REFERENCES ON csr.internal_audit_type TO chain;
GRANT SELECT, INSERT, UPDATE ON chain.bsci_options TO csr;
GRANT INSERT ON chain.bsci_options TO csrimp;
GRANT UPDATE ON csr.internal_audit TO chain;
GRANT SELECT ON chain.reference_id_seq TO csr;
GRANT SELECT ON csr.audit_type_closure_type TO chain;
grant execute on csr.truncatestring to chain;


-- ** Cross schema constraints ***
	
ALTER TABLE CHAIN.BSCI_OPTIONS ADD (
	CONSTRAINT FK_BO_09_AUDIT_TYPE FOREIGN KEY (APP_SID, AUDIT_TYPE_2009_ID) 
		REFERENCES CSR.INTERNAL_AUDIT_TYPE (APP_SID, INTERNAL_AUDIT_TYPE_ID),
	CONSTRAINT FK_BO_14_AUDIT_TYPE FOREIGN KEY (APP_SID, AUDIT_TYPE_2014_ID) 
		REFERENCES CSR.INTERNAL_AUDIT_TYPE (APP_SID, INTERNAL_AUDIT_TYPE_ID)
);

ALTER TABLE CHAIN.BSCI_FINDING ADD 
	CONSTRAINT FK_BSCI_AUDIT_TYPE_ID FOREIGN KEY (APP_SID, AUDIT_TYPE_ID) 
		REFERENCES CSR.INTERNAL_AUDIT_TYPE (APP_SID, INTERNAL_AUDIT_TYPE_ID);

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data


INSERT INTO csr.batch_job_type (batch_job_type_id, description, sp, plugin_name, one_at_a_time, notify_address, notify_after_attempts)
VALUES(26, 'BSCI audit import', NULL, 'chain-bsci-audit', 1, 'support@cr360.com', 3);

INSERT INTO csr.module (module_id, module_name, enable_sp, description)
VALUES (75, 'BSCI Integration', 'EnableBsciIntegration', 'Enables BSCI integration.');

INSERT INTO csr.module_param (module_id, param_name, pos, param_hint)
VALUES (75, 'in_user_name', 0, 'The BSCI user name for the client');

INSERT INTO csr.module_param (module_id, param_name, pos, param_hint)
VALUES (75, 'in_password', 1, 'The BSCI password for the client');

INSERT INTO csr.module_param (module_id, param_name, pos, param_hint)
VALUES (75, 'in_audit_score_sync_enabled', 2, 'Should the audit score synchronization be enabled? Y/N');

INSERT INTO csr.module_param (module_id, param_name, pos, param_hint)
VALUES (75, 'in_last_audit_score_sync_dtm', 3, 'Date from which audits should be synchronized (yyyy-mm-dd or NULL for full history or if not using this feature).');

INSERT INTO csr.module_param (module_id, param_name, pos, param_hint)
VALUES (75, 'in_supplier_sync_enabled', 4, 'Should the supplier synchronization be enabled? Y/N');

INSERT INTO csr.module_param (module_id, param_name, pos, param_hint)
VALUES (75, 'in_last_supplier_sync_dtm', 5, 'Date from which suppliers should be synchronized (yyyy-mm-dd or NULL for full history or if not using this feature).');


BEGIN
	DBMS_SCHEDULER.CREATE_JOB (
		job_name 			=> 'chain.BsciImport',
		job_type 			=> 'PLSQL_BLOCK',
		job_action 			=> 'chain.bsci_pkg.CreateBatchJob;',
		job_class			=> 'low_priority_job',
		start_date 			=> to_timestamp_tz('2008/01/01 05:00 +00:00','YYYY/MM/DD HH24:MI TZH:TZM'),
		repeat_interval 	=> 'FREQ=DAILY',
		enabled 			=> TRUE,
		auto_drop 			=> FALSE,
		comments 			=> 'Create BSCI import batch jobs');
	COMMIT;
END;
/

-- ** New package grants **
CREATE OR REPLACE PACKAGE chain.bsci_pkg AS END;
/
GRANT EXECUTE ON chain.bsci_pkg TO web_user;

-- *** Conditional Packages ***

-- *** Packages ***
@../batch_job_pkg
@../chain/bsci_pkg
@../enable_pkg

@../chain/bsci_body
@../enable_body


@update_tail



