-- Please update version.sql too -- this keeps clean builds in sync
define version=57
@update_header

BEGIN
INSERT INTO SHEET_ACTION ( SHEET_ACTION_ID, DESCRIPTION, COLOUR ) VALUES (11, 'Submitted with modifications', 'O');
INSERT INTO SHEET_ACTION_PERMISSION ( SHEET_ACTION_ID, USER_LEVEL, CAN_SAVE, CAN_SUBMIT, CAN_ACCEPT,CAN_RETURN, CAN_DELEGATE, CAN_VIEW ) VALUES (11, 1, 1, 0, 1, 1, 0, 1);
INSERT INTO SHEET_ACTION_PERMISSION ( SHEET_ACTION_ID, USER_LEVEL, CAN_SAVE, CAN_SUBMIT, CAN_ACCEPT,CAN_RETURN, CAN_DELEGATE, CAN_VIEW ) VALUES (11, 2, 0, 0, 0, 0, 0, 1);
INSERT INTO SHEET_ACTION_PERMISSION ( SHEET_ACTION_ID, USER_LEVEL, CAN_SAVE, CAN_SUBMIT, CAN_ACCEPT,CAN_RETURN, CAN_DELEGATE, CAN_VIEW ) VALUES (11, 3, 0, 0, 0, 0, 0, 0);
END;
/


@update_tail
