-- Please update version.sql too -- this keeps clean builds in sync
define version=489
@update_header

ALTER TABLE ind
	ADD FACTOR_TYPE_ID NUMBER(10, 0);

ALTER TABLE ind
	DROP COLUMN factor_type_map_id;

DROP TABLE factor_type_map;

ALTER TABLE factor_type
	ADD PARENT_ID NUMBER(10, 0);

ALTER TABLE CSR.IND ADD CONSTRAINT RefFACTOR_TYPE1733 
    FOREIGN KEY (FACTOR_TYPE_ID)
    REFERENCES FACTOR_TYPE(FACTOR_TYPE_ID)
;

ALTER TABLE FACTOR_TYPE ADD CONSTRAINT RefFACTOR_TYPE1732 
    FOREIGN KEY (PARENT_ID)
    REFERENCES FACTOR_TYPE(FACTOR_TYPE_ID)
;

@update_tail
