-- Please update version.sql too -- this keeps clean builds in sync
define version=3436
define minor_version=5
@update_header

-- *** DDL ***
-- Create tables

CREATE TABLE CSR.BASELINE_CONFIG (
	APP_SID						NUMBER(10, 0)  DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	BASELINE_CONFIG_ID			NUMBER(10, 0)  NOT NULL,
	BASELINE_NAME				VARCHAR2(200)  NOT NULL,
	BASELINE_LOOKUP_KEY			VARCHAR2(200)  NOT NULL,
	CONSTRAINT pk_baseline_config PRIMARY KEY (APP_SID, BASELINE_CONFIG_ID),
	CONSTRAINT uk_baseline_lookup_key UNIQUE (APP_SID, BASELINE_CONFIG_ID, BASELINE_LOOKUP_KEY)
);

CREATE SEQUENCE CSR.BASELINE_CONFIG_ID_SEQ CACHE 5;


CREATE TABLE CSR.BASELINE_CONFIG_PERIOD (
	APP_SID								NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	BASELINE_CONFIG_PERIOD_ID			NUMBER(10, 0)   NOT NULL,
	BASELINE_CONFIG_ID					NUMBER(10, 0)   NOT NULL,
	BASELINE_PERIOD_DTM					DATE NOT NULL,
	BASELINE_COVER_PERIOD_START_DTM		DATE,
	BASELINE_COVER_PERIOD_END_DTM		DATE,
	CONSTRAINT pk_baseline_config_period PRIMARY KEY (APP_SID, BASELINE_CONFIG_PERIOD_ID),
	CONSTRAINT fk_bsl_config_period_bsl_config FOREIGN KEY 
			(APP_SID, BASELINE_CONFIG_ID) REFERENCES CSR.BASELINE_CONFIG (APP_SID, BASELINE_CONFIG_ID)
);

CREATE SEQUENCE CSR.BASELINE_CONFIG_PERIOD_ID_SEQ CACHE 5;

create index csr.ix_baseline_conf_baseline_conf on csr.baseline_config_period (app_sid, baseline_config_id);

CREATE TABLE CSRIMP.BASELINE_CONFIG (
	CSRIMP_SESSION_ID			NUMBER(10)  DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BASELINE_CONFIG_ID			NUMBER(10, 0)  NOT NULL,
	BASELINE_NAME				VARCHAR2(200)  NOT NULL,
	BASELINE_LOOKUP_KEY			VARCHAR2(200)  NOT NULL,
	CONSTRAINT pk_baseline_config PRIMARY KEY (CSRIMP_SESSION_ID, BASELINE_CONFIG_ID),
	CONSTRAINT FK_BASELINE_CONFIG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.BASELINE_CONFIG_PERIOD (
	CSRIMP_SESSION_ID					NUMBER(10)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BASELINE_CONFIG_PERIOD_ID			NUMBER(10, 0)   NOT NULL,
	BASELINE_CONFIG_ID					NUMBER(10, 0)   NOT NULL,
	BASELINE_PERIOD_DTM					DATE NOT NULL,
	BASELINE_COVER_PERIOD_START_DTM		DATE,
	BASELINE_COVER_PERIOD_END_DTM		DATE,
	CONSTRAINT pk_baseline_config_period PRIMARY KEY (CSRIMP_SESSION_ID, BASELINE_CONFIG_PERIOD_ID),
	CONSTRAINT FK_BASELINE_CONFIG_PERIOD_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);


-- Alter tables

-- *** Grants ***

grant select,insert,update,delete on csrimp.baseline_config to tool_user;
grant select,insert,update,delete on csrimp.baseline_config_period to tool_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON CSR.BASELINE_CONFIG TO CSRIMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON CSR.BASELINE_CONFIG_PERIOD TO CSRIMP;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

CREATE OR REPLACE PACKAGE csr.baseline_pkg AS
    PROCEDURE DUMMY;
END;
/

CREATE OR REPLACE PACKAGE BODY csr.baseline_pkg AS
PROCEDURE DUMMY
AS
    BEGIN
        NULL;
    END;
END;
/

GRANT EXECUTE ON csr.baseline_pkg TO web_user;

-- *** Conditional Packages ***

-- *** Packages ***

@../baseline_pkg
@../csrimp/imp_pkg
@../schema_pkg

@../baseline_body
@../csr_data_body
@../csr_app_body
@../csrimp/imp_body
@../schema_body


@update_tail