-- Please update version.sql too -- this keeps clean builds in sync
define version=1658
@update_header

CREATE UNIQUE INDEX CSR.UK_EST_BUILDING_ESP_ID ON CSR.EST_BUILDING(APP_SID, ESP_ID);
CREATE UNIQUE INDEX CSR.UK_EST_ENERGY_METER_ESP_ID ON CSR.EST_ENERGY_METER(APP_SID, ESP_ID);
CREATE UNIQUE INDEX CSR.UK_EST_SPACE_ESP_ID ON CSR.EST_SPACE(APP_SID, ESP_ID);
CREATE UNIQUE INDEX CSR.UK_EST_WATER_METER_ESP_ID ON CSR.EST_WATER_METER(APP_SID, ESP_ID);

@update_tail


