-- Please update version.sql too -- this keeps clean builds in sync
define version=1674
@update_header

DROP INDEX CSR.UK_EST_BUILDING_REGION_SID;
DROP INDEX CSR.UK_EST_ENERGYM_REGION_SID;
DROP INDEX CSR.UK_EST_SPACE_REGION_SID;
DROP INDEX CSR.UK_EST_WATERM_REGION_SID;

CREATE UNIQUE INDEX CSR.UK_EST_BUILDING_REGION_SID ON CSR.EST_BUILDING(NVL2(REGION_SID, APP_SID, NULL), REGION_SID);
CREATE UNIQUE INDEX CSR.UK_EST_ENERGYM_REGION_SID ON CSR.EST_ENERGY_METER(NVL2(REGION_SID, APP_SID, NULL), REGION_SID);
CREATE UNIQUE INDEX CSR.UK_EST_SPACE_REGION_SID ON CSR.EST_SPACE(NVL2(REGION_SID, APP_SID, NULL), REGION_SID);
CREATE UNIQUE INDEX CSR.UK_EST_WATERM_REGION_SID ON CSR.EST_WATER_METER(NVL2(REGION_SID, APP_SID, NULL), REGION_SID);

@update_tail


