-- Please update version.sql too -- this keeps clean builds in sync
define version=2954
define minor_version=8
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CHAIN.BSCI_AUDIT (
	APP_SID 					NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	COMPANY_SID 				NUMBER(10,0) NOT NULL,
	INTERNAL_AUDIT_SID 			NUMBER(10,0) NULL,
	AUDIT_REF 					NUMBER(10,0) NOT NULL,
	AUDIT_TYPE_ID				NUMBER(10,0) NOT NULL,
	AUDIT_DTM					DATE NOT NULL,
	AUDIT_EXPIRY_DTM 			DATE NOT NULL,
	AUDIT_SCORE 				NUMBER(10,0) NOT NULL,
	AUDIT_ANNOUNCED 			NUMBER(1) NOT NULL,
	AUDIT_STAGE 				VARCHAR2(255) NOT NULL,
	AUDIT_SUCCESS 				NUMBER(1) NOT NULL,
	AUDIT_ENVIRONMENT 			VARCHAR2(255) NULL,
	LEAD_AUDITOR_NAME			VARCHAR2(255) NULL,
	AUDITING_COMPANY			VARCHAR2(255) NULL,
	AUDITING_COMPANY_BRANCH		VARCHAR2(255) NULL,
	MAN_DAYS					NUMBER(10,0) NULL,
	AUDITOR_COMMENTS 			VARCHAR2(4000) NULL,
	NEED_FOLLOW_UP				VARCHAR2(255) NULL,
	CYCLE 						VARCHAR2(255) NULL,
	TOTAL_TURNOVER 				NUMBER(10,0),
	INTERVIEW_ESSENTIALS 		VARCHAR2(4000) NULL,
	CONSTRAINT PK_BSCI_AUDIT PRIMARY KEY (APP_SID, AUDIT_REF),
	CONSTRAINT CHK_AUDIT_ANNOUNCED CHECK (AUDIT_ANNOUNCED IN (0,1)),
	CONSTRAINT FK_BSCI_AUDIT_COMPANY_SID FOREIGN KEY (APP_SID, COMPANY_SID) REFERENCES CHAIN.COMPANY(APP_SID, COMPANY_SID)
);

BEGIN
	-- Copy any existing data into the new table
	INSERT INTO chain.bsci_audit (app_sid, company_sid, internal_audit_sid, audit_ref, audit_type_id, audit_dtm, audit_expiry_dtm, audit_score,
				audit_announced, audit_stage, audit_success, audit_environment, lead_auditor_name, auditing_company,
				auditing_company_branch, man_days, auditor_comments, need_follow_up, cycle, total_turnover, interview_essentials)
		 SELECT ba.app_sid, ba.company_sid, ia.internal_audit_sid, ba.audit_ref, bo.audit_type_2014_id, ba.audit_date, ba.audit_expiry_date, ba.audit_score,
				ba.audit_announced, ba.audit_stage, ba.audit_success, ba.audit_environment, ba.lead_auditor_name, ba.auditing_company,
				ba.auditing_company_branch, ba.man_days, NULL, ba.need_follow_up, NULL, NULL, ba.interview_essentials
		   FROM chain.bsci_audit_2014 ba
		   JOIN chain.bsci_options bo ON ba.app_sid = bo.app_sid
		   JOIN csr.internal_audit ia ON ia.internal_audit_ref = ba.audit_ref AND ia.internal_audit_type_id = bo.audit_type_2009_id AND ia.app_sid = ba.app_sid;

	INSERT INTO chain.bsci_audit (app_sid, company_sid, internal_audit_sid, audit_ref, audit_type_id, audit_dtm, audit_expiry_dtm, audit_score,
				audit_announced, audit_stage, audit_success, audit_environment, lead_auditor_name, auditing_company,
				auditing_company_branch, man_days, auditor_comments, need_follow_up, cycle, total_turnover, interview_essentials)
		 SELECT ba.app_sid, ba.company_sid, ia.internal_audit_sid, ba.audit_ref, bo.audit_type_2009_id, ba.audit_date, ba.audit_expiry_date, ba.audit_score,
			   	ba.audit_announced, ba.audit_stage, ba.audit_success, ba.audit_environment, ba.lead_auditor_name, NULL,
			   	NULL, ba.man_days, ba.auditor_comments, NULL, ba.cycle, ba.total_turnover, ba.interview_essentials
		   FROM chain.bsci_audit_2009 ba
		   JOIN chain.bsci_options bo ON ba.app_sid = bo.app_sid
		   JOIN csr.internal_audit ia ON ia.internal_audit_ref = ba.audit_ref AND ia.internal_audit_type_id = bo.audit_type_2009_id AND ia.app_sid = ba.app_sid;
END;
/

CREATE TABLE CSRIMP.CHAIN_BSCI_AUDIT (
	CSRIMP_SESSION_ID			NUMBER(10, 0)   DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID 				NUMBER(10,0) NOT NULL,
	INTERNAL_AUDIT_SID 			NUMBER(10,0) NULL,
	AUDIT_REF 					NUMBER(10,0) NOT NULL,
	AUDIT_TYPE_ID				NUMBER(10,0) NOT NULL,
	AUDIT_DTM					DATE NOT NULL,
	AUDIT_EXPIRY_DTM 			DATE NOT NULL,
	AUDIT_SCORE 				NUMBER(10,0) NOT NULL,
	AUDIT_ANNOUNCED 			NUMBER(1) NOT NULL,
	AUDIT_STAGE 				VARCHAR2(255) NOT NULL,
	AUDIT_SUCCESS 				NUMBER(1) NOT NULL,
	AUDIT_ENVIRONMENT 			VARCHAR2(255) NULL,
	LEAD_AUDITOR_NAME			VARCHAR2(255) NULL,
	AUDITING_COMPANY			VARCHAR2(255) NULL,
	AUDITING_COMPANY_BRANCH		VARCHAR2(255) NULL,
	MAN_DAYS					NUMBER(10,0) NULL,
	AUDITOR_COMMENTS 			VARCHAR2(4000) NULL,
	NEED_FOLLOW_UP				VARCHAR2(255) NULL,
	CYCLE 						VARCHAR2(255) NULL,
	TOTAL_TURNOVER 				NUMBER(10,0),
	INTERVIEW_ESSENTIALS 		VARCHAR2(4000) NULL,
	CONSTRAINT PK_BSCI_AUDIT PRIMARY KEY (CSRIMP_SESSION_ID, AUDIT_REF),
	CONSTRAINT CHK_AUDIT_ANNOUNCED CHECK (AUDIT_ANNOUNCED IN (0,1)),
	CONSTRAINT FK_BSCI_AUDIT_SESSION FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Alter tables
ALTER TABLE CHAIN.BSCI_FINDING DROP CONSTRAINT FK_BSCI_AUDIT_2009_REF;
ALTER TABLE CHAIN.BSCI_FINDING DROP CONSTRAINT FK_BSCI_AUDIT_2014_REF;
ALTER TABLE CHAIN.BSCI_FINDING DROP CONSTRAINT CHK_BSCI_AUDIT_TYPE;
ALTER TABLE CHAIN.BSCI_ASSOCIATE DROP CONSTRAINT FK_BSCI_AUDIT_REF_ASS_2009;
ALTER TABLE CHAIN.BSCI_ASSOCIATE DROP CONSTRAINT FK_BSCI_AUDIT_REF_ASS_2014;
ALTER TABLE CSRIMP.CHAIN_BSCI_FINDING DROP CONSTRAINT CHK_BSCI_AUDIT_TYPE;

DROP TABLE CHAIN.BSCI_AUDIT_2009;
DROP TABLE CHAIN.BSCI_AUDIT_2014;
DROP TABLE CSRIMP.CHAIN_BSCI_AUDIT_2009 cascade constraints;
DROP TABLE CSRIMP.CHAIN_BSCI_AUDIT_2014 cascade constraints;

ALTER TABLE CHAIN.BSCI_FINDING ADD AUDIT_REF NUMBER(10) NULL;
ALTER TABLE CHAIN.BSCI_ASSOCIATE ADD AUDIT_REF NUMBER(10) NULL;

BEGIN
	UPDATE chain.bsci_finding
	   SET audit_ref = audit_ref_2014
	 WHERE audit_ref_2014 IS NOT NULL;

	UPDATE chain.bsci_finding
	   SET audit_ref = audit_ref_2009
	 WHERE audit_ref_2009 IS NOT NULL;

	UPDATE chain.bsci_associate
	   SET audit_ref = audit_ref_2009
	 WHERE audit_ref_2009 IS NOT NULL;

	UPDATE chain.bsci_associate
	   SET audit_ref = audit_ref_2014
	 WHERE audit_ref_2014 IS NOT NULL;
END;
/

ALTER TABLE CHAIN.BSCI_FINDING MODIFY AUDIT_REF NUMBER(10) NOT NULL;
ALTER TABLE CHAIN.BSCI_ASSOCIATE MODIFY AUDIT_REF NUMBER(10) NOT NULL;
ALTER TABLE CSRIMP.CHAIN_BSCI_FINDING ADD AUDIT_REF NUMBER(10) NOT NULL;
ALTER TABLE CSRIMP.CHAIN_BSCI_ASSOCIATE ADD AUDIT_REF NUMBER(10) NOT NULL;

ALTER TABLE CHAIN.BSCI_FINDING ADD CONSTRAINT FK_BSCI_AUDIT_REF_FIND FOREIGN KEY (APP_SID, AUDIT_REF) REFERENCES CHAIN.BSCI_AUDIT (APP_SID, AUDIT_REF);
ALTER TABLE CHAIN.BSCI_ASSOCIATE ADD CONSTRAINT FK_BSCI_AUDIT_REF_ASS FOREIGN KEY (APP_SID, AUDIT_REF) REFERENCES CHAIN.BSCI_AUDIT (APP_SID, AUDIT_REF);

ALTER TABLE CHAIN.BSCI_FINDING DROP COLUMN AUDIT_REF_2009;
ALTER TABLE CHAIN.BSCI_FINDING DROP COLUMN AUDIT_REF_2014;
ALTER TABLE CSRIMP.CHAIN_BSCI_FINDING DROP COLUMN AUDIT_REF_2009;
ALTER TABLE CSRIMP.CHAIN_BSCI_FINDING DROP COLUMN AUDIT_REF_2014;
ALTER TABLE CHAIN.BSCI_ASSOCIATE DROP COLUMN AUDIT_REF_2009;
ALTER TABLE CHAIN.BSCI_ASSOCIATE DROP COLUMN AUDIT_REF_2014;
ALTER TABLE CSRIMP.CHAIN_BSCI_ASSOCIATE DROP COLUMN AUDIT_REF_2009;
ALTER TABLE CSRIMP.CHAIN_BSCI_ASSOCIATE DROP COLUMN AUDIT_REF_2014;

ALTER TABLE CHAIN.BSCI_SUPPLIER RENAME COLUMN AUDIT_EXPIRATION_DATE TO AUDIT_EXPIRATION_DTM;
ALTER TABLE CHAIN.BSCI_SUPPLIER RENAME COLUMN AUDIT_DATE TO AUDIT_DTM;
ALTER TABLE CHAIN.BSCI_SUPPLIER RENAME COLUMN LAST_UPDATED_DATE TO LAST_UPDATED_DTM;

ALTER TABLE CSRIMP.CHAIN_BSCI_SUPPLIER RENAME COLUMN AUDIT_EXPIRATION_DATE TO AUDIT_EXPIRATION_DTM;
ALTER TABLE CSRIMP.CHAIN_BSCI_SUPPLIER RENAME COLUMN AUDIT_DATE TO AUDIT_DTM;
ALTER TABLE CSRIMP.CHAIN_BSCI_SUPPLIER RENAME COLUMN LAST_UPDATED_DATE TO LAST_UPDATED_DTM;

-- *** Grants ***

-- ** Cross schema constraints ***
ALTER TABLE CHAIN.BSCI_AUDIT ADD CONSTRAINT FK_BSCI_INTERNAL_AUDIT_TYPE_ID
	FOREIGN KEY (APP_SID, AUDIT_TYPE_ID)
	REFERENCES CSR.INTERNAL_AUDIT_TYPE(APP_SID, INTERNAL_AUDIT_TYPE_ID);

ALTER TABLE CHAIN.BSCI_AUDIT ADD CONSTRAINT FK_BSCI_INTERNAL_AUDIT_SID
	FOREIGN KEY (APP_SID, INTERNAL_AUDIT_SID)
	REFERENCES CSR.INTERNAL_AUDIT (APP_SID, INTERNAL_AUDIT_SID);

CREATE INDEX CHAIN.IX_BSCI_AUDIT_COMPANY_AUDIT ON CHAIN.BSCI_AUDIT (APP_SID, COMPANY_SID, INTERNAL_AUDIT_SID, AUDIT_TYPE_ID);

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data


-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../chain/bsci_pkg
@../chain/bsci_body

@update_tail
