-- Please update version.sql too -- this keeps clean builds in sync
define version=44
@update_header


-- 
-- TABLE: AUDIT_LOG 
--

CREATE TABLE AUDIT_LOG(
    AUDIT_DATE       DATE              DEFAULT SYSDATE NOT NULL,
    CSR_ROOT_SID     NUMBER(10, 0)    NOT NULL,
    AUDIT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    OBJECT_SID       NUMBER(10, 0)    NOT NULL,
    USER_SID         NUMBER(10, 0)    NOT NULL,
    DESCRIPTION      VARCHAR2(1023)
)
;



-- 
-- TABLE: AUDIT_TYPE 
--

CREATE TABLE AUDIT_TYPE(
    AUDIT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    LABEL            VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK200 PRIMARY KEY (AUDIT_TYPE_ID)
)
;




BEGIN
INSERT INTO AUDIT_TYPE ( AUDIT_TYPE_ID, LABEL ) VALUES (1, 'Logon');
INSERT INTO AUDIT_TYPE ( AUDIT_TYPE_ID, LABEL ) VALUES (2, 'Logoff');
INSERT INTO AUDIT_TYPE ( AUDIT_TYPE_ID, LABEL ) VALUES (3, 'Super user logon');
INSERT INTO AUDIT_TYPE ( AUDIT_TYPE_ID, LABEL ) VALUES (4, 'Change schema');
INSERT INTO AUDIT_TYPE ( AUDIT_TYPE_ID, LABEL ) VALUES (5, 'Change user');
INSERT INTO AUDIT_TYPE ( AUDIT_TYPE_ID, LABEL ) VALUES (6, 'Value change');
END;
/
commit;


-- 
-- VIEW: AUDIT_VAL_LOG 
--

CREATE OR REPLACE VIEW AUDIT_VAL_LOG AS
SELECT CHANGED_DTM AUDIT_DATE, R.CSR_ROOT_SID, 6 AUDIT_TYPE_ID, vc.IND_SID OBJECT_SID, CHANGED_BY_SID USER_SID,
 'Set "'||I.DESCRIPTION||'", ('||R.DESCRIPTION||') to '||VAL_NUMBER||': '||REASON DESCRIPTION
FROM VAL_CHANGE VC, REGION R, IND I
WHERE VC.REGION_SID = R.REGION_SID
   AND VC.IND_SID = I.IND_SID
;



connect security/security@&&1
grant select on security.website to csr;


@update_tail
