-- Please update version.sql too -- this keeps clean builds in sync
define version=2363
@update_header

CREATE SEQUENCE CSR.MAP_POSTIT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

CREATE SEQUENCE CSR.MAP_NON_COMPLIANCE_FILE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

GRANT SELECT ON CSR.MAP_POSTIT_SEQ TO CSRIMP;
GRANT SELECT ON CSR.MAP_NON_COMPLIANCE_FILE_SEQ TO CSRIMP;

@update_tail
