-- Please update version.sql too -- this keeps clean builds in sync
define version=751
@update_header

ALTER TABLE csr.RELATED_AXIS_MEMBER DROP CONSTRAINT PK_RELATED_AXIS_MEMBER drop index;
ALTER TABLE csr.RELATED_AXIS_MEMBER ADD (REPORTING_PERIOD_SID      NUMBER(10, 0)    NOT NULL);

ALTER TABLE csr.RELATED_AXIS_MEMBER ADD CONSTRAINT PK_RELATED_AXIS_MEMBER PRIMARY KEY (APP_SID, AXIS_ID, RELATED_AXIS_ID, AXIS_MEMBER_ID, RELATED_AXIS_MEMBER_ID, REPORTING_PERIOD_SID)
;

ALTER TABLE csr.RELATED_AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MBR_REL_REP_PERIOD 
    FOREIGN KEY (APP_SID, REPORTING_PERIOD_SID)
    REFERENCES csr.REPORTING_PERIOD(APP_SID, REPORTING_PERIOD_SID)
;

@update_tail
