-- Please update version.sql too -- this keeps clean builds in sync
define version=3197
define minor_version=13
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CSR.OSHA_CONFIG(
	APP_SID					NUMBER(10,0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	CMS_TAB_SID				NUMBER(10,0),
	DATE_CMS_COL_SID		NUMBER(10,0),
	REGION_CMS_COL_SID		NUMBER(10,0),
CONSTRAINT PK_OSHA_CONFIG PRIMARY KEY (APP_SID)
)
;

CREATE TABLE CSRIMP.OSHA_CONFIG(
	CSRIMP_SESSION_ID		NUMBER(10,0)	DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	CMS_TAB_SID				NUMBER(10,0),
	DATE_CMS_COL_SID		NUMBER(10,0),
	REGION_CMS_COL_SID		NUMBER(10,0),
	CONSTRAINT PK_OSHA_CONFIG PRIMARY KEY (CSRIMP_SESSION_ID),
	CONSTRAINT FK_OSHA_CONFIG FOREIGN KEY
    	(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
    	ON DELETE CASCADE
)
;

DROP TABLE CSRIMP.OSHA_MAPPING;

CREATE TABLE CSRIMP.OSHA_MAPPING(
	CSRIMP_SESSION_ID		NUMBER(10,0)	DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OSHA_BASE_DATA_ID		NUMBER(10,0)	NOT NULL,
	IND_SID					NUMBER(10,0),
	CMS_COL_SID				NUMBER(10,0),
	REGION_DATA_MAP_ID		NUMBER(10,0),
	CONSTRAINT PK_OSHA_MAPPING PRIMARY KEY (CSRIMP_SESSION_ID, OSHA_BASE_DATA_ID),
	CONSTRAINT FK_OSHA_MAPPING FOREIGN KEY
    	(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
    	ON DELETE CASCADE
)
;

CREATE TABLE CSR.REGION_DATA_MAP(
	REGION_DATA_MAP_ID				NUMBER(10,0)	NOT NULL,
	DATA_ELEMENT					VARCHAR2(50)	NOT NULL,
	DESCRIPTION						VARCHAR2(4000)	NOT NULL,
	IS_PROPERTY						NUMBER(1)		DEFAULT 0 NOT NULL,
	IS_METER						NUMBER(1)		DEFAULT 0 NOT NULL,
	CONSTRAINT PK_REGION_DATA_MAP 	PRIMARY KEY (REGION_DATA_MAP_ID)
)
;

-- Alter tables

ALTER TABLE CSR.OSHA_MAPPING ADD(
	REGION_DATA_MAP_ID 				NUMBER(10,0)
);

ALTER TABLE CSR.OSHA_MAPPING ADD CONSTRAINT FK_OSHA_MAP_REGION_DATA
    FOREIGN KEY (REGION_DATA_MAP_ID)
    REFERENCES CSR.REGION_DATA_MAP(REGION_DATA_MAP_ID)
;

CREATE INDEX CSR.IX_OSHA_MAPPING_REGION_DATA ON CSR.OSHA_MAPPING(REGION_DATA_MAP_ID);

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (1, 'SID', 'Region id', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (2, 'DESC', 'Region description', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (3, 'REF', 'Region reference', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (4, 'GEO_CITY', 'Region City', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (5, 'GEO_ST_CODE', 'Region State Code', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (6, 'GEO_ST_DESC', 'Region State', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (7, 'GEO_COUNTRY_DESC', 'Region Country', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (8, 'GEO_COUNTRY_CODE', 'Region Country Code', 0, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (9, 'MGNT_COMPANY', 'Management company', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (10, 'FUND', 'Fund', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (11, 'PROP_TYPE', 'Property type', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (12, 'PROP_SUB_TYPE', 'Property sub type', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (13, 'PROP_ADDR1', 'Property Address 1', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (14, 'PROP_ADDR2', 'Property Address 2', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (15, 'PROP_CITY', 'Property city', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (16, 'PROP_STATE', 'Property state', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (17, 'PROP_ZIP', 'Property zip', 1, 0);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (18, 'MET_NUM', 'Meter number', 0, 1);
INSERT INTO CSR.REGION_DATA_MAP (REGION_DATA_MAP_ID, DATA_ELEMENT, DESCRIPTION, IS_PROPERTY, IS_METER) VALUES (19, 'MET_TYPE', 'Meter type', 0, 1);


-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../osha_pkg
@../region_pkg

@../enable_body
@../osha_body
@../region_body

@update_tail
