-- Please update version.sql too -- this keeps clean builds in sync
define version=1538
@update_header

ALTER TABLE CSR.REGION_METRIC ADD (
    IS_MANDATORY    NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CONSTRAINT CHK_REG_METRIC_MAND CHECK (IS_MANDATORY IN (0,1))
);

CREATE TABLE CSR.RULESET(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RULESET_SID             NUMBER(10, 0)    NOT NULL,
    REPORTING_PERIOD_SID    NUMBER(10, 0)    NOT NULL,
    INTERVAL                VARCHAR2(1)      DEFAULT 'y' NOT NULL,
    CONSTRAINT CHK_RULESET_INTERVAL CHECK (INTERVAL IN ('m','q','h','y')),
    CONSTRAINT PK_RULESET PRIMARY KEY (APP_SID, RULESET_SID)
);

CREATE TABLE CSR.RULESET_MEMBER(
    APP_SID        NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RULESET_SID    NUMBER(10, 0)    NOT NULL,
    IND_SID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_RULESET_MEMBER PRIMARY KEY (APP_SID, RULESET_SID, IND_SID)
);

CREATE TABLE CSR.RULESET_RUN(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RULESET_SID     NUMBER(10, 0)    NOT NULL,
    REGION_SID      NUMBER(10, 0)    NOT NULL,
    LAST_RUN_DTM    DATE             DEFAULT SYSDATE,
    CONSTRAINT PK_RULESET_RUN PRIMARY KEY (APP_SID, RULESET_SID, REGION_SID)
);

CREATE TABLE CSR.RULESET_RUN_FINDING(
    APP_SID                  NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    RULESET_SID              NUMBER(10, 0)     NOT NULL,
    REGION_SID               NUMBER(10, 0)     NOT NULL,
    IND_SID                  NUMBER(10, 0)     NOT NULL,
    EXPLANATION              VARCHAR2(4000),
    EXPLAINED_BY_USER_SID    NUMBER(10, 0),
    EXPLAINED_DTM            DATE,
    APPROVED_BY_SID          NUMBER(10, 0),
    APPROVED_DTM             DATE,
    IS_CURRENTLY_VALID       NUMBER(1, 0)      DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_RULESET_FND_VALID CHECK (IS_CURRENTLY_VALID IN (0,1)),
    CONSTRAINT PK_RULESET_RUN_FINDING PRIMARY KEY (APP_SID, RULESET_SID, REGION_SID, IND_SID)
);

ALTER TABLE CSR.RULESET ADD CONSTRAINT FK_RPT_PERIOD_RULESET 
    FOREIGN KEY (APP_SID, REPORTING_PERIOD_SID)
    REFERENCES CSR.REPORTING_PERIOD(APP_SID, REPORTING_PERIOD_SID);

ALTER TABLE CSR.RULESET_MEMBER ADD CONSTRAINT FK_IND_RLSET_MBR 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID);

ALTER TABLE CSR.RULESET_MEMBER ADD CONSTRAINT FK_RLSET_RLSET_MBR 
    FOREIGN KEY (APP_SID, RULESET_SID)
    REFERENCES CSR.RULESET(APP_SID, RULESET_SID);

ALTER TABLE CSR.RULESET_RUN ADD CONSTRAINT FK_REGION_RULESET_RUN 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID);

ALTER TABLE CSR.RULESET_RUN ADD CONSTRAINT FK_RLSET_RLSET_RUN 
    FOREIGN KEY (APP_SID, RULESET_SID)
    REFERENCES CSR.RULESET(APP_SID, RULESET_SID);

ALTER TABLE CSR.RULESET_RUN_FINDING ADD CONSTRAINT FK_RLST_MBR_RLST_RN_FND 
    FOREIGN KEY (APP_SID, RULESET_SID, IND_SID)
    REFERENCES CSR.RULESET_MEMBER(APP_SID, RULESET_SID, IND_SID);

ALTER TABLE CSR.RULESET_RUN_FINDING ADD CONSTRAINT FK_RLST_RUN_RLST_RUN_FND 
    FOREIGN KEY (APP_SID, RULESET_SID, REGION_SID)
    REFERENCES CSR.RULESET_RUN(APP_SID, RULESET_SID, REGION_SID);

ALTER TABLE CSR.RULESET_RUN_FINDING ADD CONSTRAINT FK_USR_RLSET_RUN_FND 
    FOREIGN KEY (APP_SID, EXPLAINED_BY_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);

ALTER TABLE CSR.RULESET_RUN_FINDING ADD CONSTRAINT FK_USR_RLSET_RUN_FND_APR 
    FOREIGN KEY (APP_SID, APPROVED_BY_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID);

-- management company
CREATE SEQUENCE CSR.MGMT_COMPANY_ID
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER;

CREATE TABLE CSR.MGMT_COMPANY(
    APP_SID            NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    MGMT_COMPANY_ID    NUMBER(10, 0)    NOT NULL,
    NAME               VARCHAR2(255)    NOT NULL,
    COMPANY_SID        NUMBER(10, 0),
    CONSTRAINT PK_MGMT_COMPANY PRIMARY KEY (APP_SID, MGMT_COMPANY_ID)
);

ALTER TABLE CSR.PROPERTY ADD (
    MGMT_COMPANY_ID         NUMBER(10, 0),
    MGMT_COMPANY_OTHER      VARCHAR2(255),
    CONSTRAINT CONS_PROP_MGMT_COMPANY CHECK ((MGMT_COMPANY_ID IS NOT NULL AND MGMT_COMPANY_OTHER IS NULL) OR MGMT_COMPANY_ID IS NULL));
 
ALTER TABLE CSR.MGMT_COMPANY ADD CONSTRAINT FK_SUPP_MGMT_COMPANY 
    FOREIGN KEY (APP_SID, COMPANY_SID)
    REFERENCES CSR.SUPPLIER(APP_SID, SUPPLIER_SID);

ALTER TABLE CSR.PROPERTY ADD CONSTRAINT FK_MGMT_CO_PROPERTY 
    FOREIGN KEY (APP_SID, MGMT_COMPANY_ID)
    REFERENCES CSR.MGMT_COMPANY(APP_SID, MGMT_COMPANY_ID);

ALTER TABLE CSR.FUND MODIFY COMPANY_SID NOT NULL;

ALTER TABLE CSR.FUND MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY','APP');

DECLARE
    new_class_id        security.security_pkg.T_SID_ID;
BEGIN  
    security.user_pkg.logonadmin;
    BEGIN 
        security.class_pkg.CreateClass(SYS_CONTEXT('SECURITY', 'ACT'), NULL, 'CSRRuleSet', NULL, NULL, new_class_id);
    EXCEPTION
        WHEN security.security_pkg.DUPLICATE_OBJECT_NAME THEN
            new_class_id:=security.class_pkg.GetClassId('CSRRuleSet');
    END;
END;
/

@update_tail