-- Please update version.sql too -- this keeps clean builds in sync
define version=1614
@update_header

ALTER TABLE CSR.INTERNAL_AUDIT_TYPE ADD(
    ASSIGN_ISSUES_TO_ROLE     NUMBER(1, 0)     DEFAULT 0 NOT NULL,
    CONSTRAINT CHK_IAT_ISS_ASS_ROLE_0_1 CHECK (ASSIGN_ISSUES_TO_ROLE IN (0,1))
)
;

ALTER TABLE CSRIMP.INTERNAL_AUDIT_TYPE ADD ASSIGN_ISSUES_TO_ROLE     NUMBER(1, 0);

UPDATE CSRIMP.INTERNAL_AUDIT_TYPE SET ASSIGN_ISSUES_TO_ROLE=0;

ALTER TABLE CSRIMP.INTERNAL_AUDIT_TYPE MODIFY ASSIGN_ISSUES_TO_ROLE NOT NULL;

ALTER TABLE CSRIMP.INTERNAL_AUDIT_TYPE ADD CONSTRAINT CHK_IAT_ISS_ASS_ROLE_0_1 CHECK (ASSIGN_ISSUES_TO_ROLE IN (0,1));

@..\audit_pkg

@..\audit_body
@..\schema_body
@..\csrimp\imp_body

@update_tail
