-- Please update version.sql too -- this keeps clean builds in sync
define version=1125
@update_header

CREATE TABLE CT.WORKSHEET_TYPE (
    WORKSHEET_TYPE_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_WS_TYPE PRIMARY KEY (WORKSHEET_TYPE_ID)
);

CREATE TABLE CT.WORKSHEET_COLUMN_TYPE (
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    WORKSHEET_TYPE_ID NUMBER(10) NOT NULL,
    JS_ATTRIBUTE VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    MANDATORY NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_WS_COLUMN_TYPE PRIMARY KEY (WORKSHEET_COLUMN_TYPE_ID),
    CONSTRAINT TUC_WS_COLUMN_TYPE_1 UNIQUE (WORKSHEET_TYPE_ID, JS_ATTRIBUTE),
    CONSTRAINT TUC_WS_COLUMN_TYPE_2 UNIQUE (WORKSHEET_TYPE_ID, NAME)
);

ALTER TABLE CT.WORKSHEET_COLUMN_TYPE ADD CONSTRAINT CC_WS_COLUMN_TYPE_MANDATORY 
    CHECK (MANDATORY IN (1,0));

ALTER TABLE CT.WORKSHEET RENAME COLUMN FILE_UPLOAD_SID TO WORKBOOK_SID;

ALTER TABLE CT.WORKSHEET ADD (WORKSHEET_TYPE_ID NUMBER(10) NOT NULL);

ALTER TABLE CT.WORKSHEET_ROW RENAME COLUMN FILE_UPLOAD_SID TO WORKBOOK_SID;

CREATE TABLE CT.WORKSHEET_COLUMN (
    APP_SID NUMBER(10) NOT NULL,
    WORKBOOK_SID NUMBER(10) NOT NULL,
    SHEET_INDEX NUMBER(10) NOT NULL,
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    COLUMN_INDEX NUMBER,
    CONSTRAINT PK_WORKSHEET_COLUMN PRIMARY KEY (APP_SID, WORKBOOK_SID, SHEET_INDEX, WORKSHEET_COLUMN_TYPE_ID),
    CONSTRAINT TUC_WORKSHEET_COLUMN_1 UNIQUE (COLUMN_INDEX, SHEET_INDEX, WORKBOOK_SID, APP_SID)
);

ALTER TABLE CT.WORKSHEET ADD CONSTRAINT WS_TYPE_WORKSHEET 
    FOREIGN KEY (WORKSHEET_TYPE_ID) REFERENCES CT.WORKSHEET_TYPE (WORKSHEET_TYPE_ID);

ALTER TABLE CT.WORKSHEET_COLUMN_TYPE ADD CONSTRAINT WS_TYPE_WS_COLUMN_TYPE 
    FOREIGN KEY (WORKSHEET_TYPE_ID) REFERENCES CT.WORKSHEET_TYPE (WORKSHEET_TYPE_ID);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT WORKSHEET_WS_COLUMN 
    FOREIGN KEY (APP_SID, WORKBOOK_SID, SHEET_INDEX) REFERENCES CT.WORKSHEET (APP_SID,WORKBOOK_SID,SHEET_INDEX);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT WS_COLUMN_TYPE_WS_COLUMN 
    FOREIGN KEY (WORKSHEET_COLUMN_TYPE_ID) REFERENCES CT.WORKSHEET_COLUMN_TYPE (WORKSHEET_COLUMN_TYPE_ID);

@update_tail
