-- Please update version.sql too -- this keeps clean builds in sync
define version=2093
@update_header


/* Allow more than one entry for the same card - different card groups when the param type is SPECIFIC */
ALTER TABLE CHAIN.CARD_INIT_PARAM DROP CONSTRAINT PK481;

ALTER TABLE CHAIN.CARD_INIT_PARAM ADD CONSTRAINT CHK_CARD_INIT_PARAM_PARAM_TYPE 
	CHECK ((PARAM_TYPE_ID = 0 /* GLOBAL */ AND CARD_GROUP_ID IS NULL) OR (PARAM_TYPE_ID = 1 /* SPECIFIC */ AND CARD_GROUP_ID IS NOT NULL));
	
CREATE UNIQUE INDEX CHAIN.UX_CARD_INIT_PARAM ON CHAIN.CARD_INIT_PARAM
	(APP_SID, CARD_ID, KEY, CASE WHEN PARAM_TYPE_ID = 0 /* GLOBAL */ THEN 1 ELSE CARD_GROUP_ID END);

	
/* change PK in INVITATION_QNR_TYPE_COMPONENT */
ALTER TABLE CHAIN.INVITATION_QNR_TYPE_COMPONENT DROP CONSTRAINT PK499 drop index;
ALTER TABLE CHAIN.INVITATION_QNR_TYPE_COMPONENT ADD CONSTRAINT PK499 PRIMARY KEY (APP_SID, INVITATION_ID, QUESTIONNAIRE_TYPE_ID, COMPONENT_ID);


/* make component_id nullable, sync and add fk */
begin
	for r in (select constraint_name from all_constraints where owner='CSR' and constraint_name='PK_SUPPLIER_SURVEY_RESPONSE') loop
		execute immediate 'ALTER TABLE csr.supplier_survey_response DROP CONSTRAINT PK_SUPPLIER_SURVEY_RESPONSE drop index';
	end loop;
end;
/
ALTER TABLE csr.supplier_survey_response ADD CONSTRAINT PK_SUPPLIER_SURVEY_RESPONSE PRIMARY KEY (APP_SID, SURVEY_RESPONSE_ID);

ALTER TABLE csr.supplier_survey_response MODIFY component_id NUMBER(10, 0) NULL;

CREATE UNIQUE INDEX CSR.UX_SUPPLIER_SURVEY_RESPONSE ON CSR.SUPPLIER_SURVEY_RESPONSE
	(APP_SID, SUPPLIER_SID, SURVEY_SID, CASE WHEN COMPONENT_ID IS NULL THEN 1 ELSE COMPONENT_ID END);

BEGIN	
	UPDATE csr.supplier_survey_response
	   SET component_id = NULL
	 WHERE component_id = 0; 
END;
/

GRANT SELECT, REFERENCES ON CHAIN.COMPONENT TO CSR;
 
ALTER TABLE CSR.SUPPLIER_SURVEY_RESPONSE ADD CONSTRAINT FK_SUPPL_SURV_RESP_COMPONENT
	FOREIGN KEY (APP_SID, COMPONENT_ID)
	REFERENCES CHAIN.COMPONENT(APP_SID, COMPONENT_ID);
 

@../quick_survey_body	

@../chain/questionnaire_body	
@../chain/card_body	

@update_tail
