-- Please update version.sql too -- this keeps clean builds in sync
define version=3139
define minor_version=26
@update_header

-- *** DDL ***
-- Create tables
DROP TABLE SURVEYS.ANSWER_FILE;
DROP TABLE SURVEYS.RESPONSE_FILE;

CREATE TABLE SURVEYS.SUBMISSION_FILE(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SUBMISSION_ID			NUMBER(10, 0)	NOT NULL,
	FILENAME				VARCHAR2(255)	NOT NULL,
	URI 					VARCHAR2(2000)	NOT NULL,
	UPLOADED_DTM			DATE			DEFAULT SYSDATE NOT NULL,
	UPLOADED_BY_USER_SID	NUMBER(10, 0)	NOT NULL,
	CONSTRAINT PK_SUBMISSION_FILE PRIMARY KEY (APP_SID, SUBMISSION_ID, FILENAME, URI)
)
;

CREATE INDEX SURVEYS.IX_SUB_FILE_BY_URI ON SURVEYS.SUBMISSION_FILE(APP_SID, FILENAME, URI)
;

CREATE TABLE SURVEYS.ANSWER_FILE(
	APP_SID				NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	ANSWER_FILE_ID		NUMBER(10, 0)	NOT NULL,
	ANSWER_ID			NUMBER(10, 0)	NOT NULL,
	SUBMISSION_ID		NUMBER(10, 0)	NOT NULL,
	FILENAME			VARCHAR2(255)	NOT NULL,
	URI					VARCHAR2(400)	NOT NULL,
	CAPTION				VARCHAR2(1023),
	CONSTRAINT PK_SURVEY_ANSWER_FILE PRIMARY KEY (APP_SID, ANSWER_FILE_ID),
	CONSTRAINT UK_SURVEY_ANSWER_FILE UNIQUE (APP_SID, ANSWER_FILE_ID, ANSWER_ID, SUBMISSION_ID),
	CONSTRAINT UK_SURVEYS_ANSWER_FILE_A UNIQUE (APP_SID, ANSWER_ID, SUBMISSION_ID, FILENAME, URI)
)
;

CREATE INDEX SURVEYS.IX_ANS_FILE_SUB_ID ON SURVEYS.ANSWER_FILE(APP_SID, SUBMISSION_ID);

-- Alter tables
ALTER TABLE SURVEYS.ANSWER_FILE ADD CONSTRAINT FK_ANSWER_FILE_FILE
	FOREIGN KEY (APP_SID, SUBMISSION_ID, FILENAME, URI)
	REFERENCES SURVEYS.SUBMISSION_FILE(APP_SID, SUBMISSION_ID, FILENAME, URI)
;

ALTER TABLE SURVEYS.SUBMISSION_FILE ADD CONSTRAINT FK_SUBMISSION_FILE_RESPONSE
	FOREIGN KEY (APP_SID, SUBMISSION_ID)
	REFERENCES SURVEYS.RESPONSE_SUBMISSION(APP_SID, SUBMISSION_ID)
;

ALTER TABLE SURVEYS.ANSWER_FILE ADD CONSTRAINT FK_ANS_FILE_SUB_ID
	FOREIGN KEY (APP_SID, SUBMISSION_ID)
	REFERENCES SURVEYS.RESPONSE_SUBMISSION(APP_SID, SUBMISSION_ID)
;

ALTER TABLE SURVEYS.ANSWER_FILE ADD CONSTRAINT FK_ANSWER_FILE_ANSWER
	FOREIGN KEY (APP_SID, ANSWER_ID)
	REFERENCES SURVEYS.ANSWER (APP_SID, ANSWER_ID)
;

-- *** Grants ***

-- ** Cross schema constraints ***
ALTER TABLE SURVEYS.SUBMISSION_FILE ADD CONSTRAINT FK_SUB_FILE_CUSTOMER
	FOREIGN KEY (APP_SID)
	REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE SURVEYS.ANSWER_FILE ADD CONSTRAINT FK_ANSWER_FILE_CUSTOMER
	FOREIGN KEY (APP_SID)
	REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE SURVEYS.SUBMISSION_FILE ADD CONSTRAINT FK_SUB_FILE_UPLOADED_USER
	FOREIGN KEY (APP_SID, UPLOADED_BY_USER_SID)
	REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
--@../surveys/survey_pkg
--@../surveys/survey_body

@update_tail
