-- Please update version.sql too -- this keeps clean builds in sync
define version=1801
@update_header

CREATE TABLE CSR.EXPORT_FEED_CMS_FORM (
    APP_SID				NUMBER(10)			DEFAULT sys_context('security','app') NOT NULL,
    EXPORT_FEED_SID		NUMBER(10)			NOT NULL,
    FORM_SID		    NUMBER(10)			NOT NULL,
    FILENAME_MASK		VARCHAR2(255)		NOT NULL,
    FORMAT				NUMBER(1)			NOT NULL,
    INCREMENTAL			NUMBER(1)			NOT NULL,		
    CONSTRAINT PK_EXPORT_FEED_CMS_FORM PRIMARY KEY (APP_SID, EXPORT_FEED_SID, FORM_SID)
);

ALTER TABLE CSR.EXPORT_FEED ADD (
	HOST_KEY          CLOB,
    PASSWORD          VARCHAR2(255));
  

ALTER TABLE CSR.EXPORT_FEED_CMS_FORM ADD CONSTRAINT FK_EXP_FEED_CMS_EXP_FEED
    FOREIGN KEY (EXPORT_FEED_SID, APP_SID) REFERENCES CSR.EXPORT_FEED (EXPORT_FEED_SID,APP_SID);

ALTER TABLE CSR.EXPORT_FEED_CMS_FORM ADD CONSTRAINT FK_EXP_CMS_FORM_TAB
    FOREIGN KEY (APP_SID, FORM_SID) REFERENCES CMS.TAB (APP_SID, TAB_SID);

@update_tail
