-- Please update version.sql too -- this keeps clean builds in sync
define version=1710
@update_header

whenever sqlerror exit failure rollback 
whenever oserror exit failure rollback

SET DEFINE OFF;

-- Standard factor sets
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (32, 'UK Department for Environment, Food & Rural Affairs (Defra) – 2007'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (33, 'UK Department for Environment, Food & Rural Affairs (Defra) – 2008'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (34, 'UK Department for Environment, Food & Rural Affairs (Defra) – 2009'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (35, 'UK Department for Environment, Food & Rural Affairs (Defra) – 2013'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (36, 'Intergovernmental Panel on Climate Change (IPCC) 2006 (Energy Industry)'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (37, 'Intergovernmental Panel on Climate Change (IPCC) 2006 (Manufacturing & Construction)'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (38, 'Intergovernmental Panel on Climate Change (IPCC) 2006 (Agricultural & Residential)'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (39, 'US Environmental Protection Agency (EPA) - Greenhouse Gas Reporting Program'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (40, 'UK CRC Energy Efficiency Scheme'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_FACTOR_SET (STD_FACTOR_SET_ID, NAME) VALUES (41, 'North American Climate Registry (2013)'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

UPDATE CSR.STD_FACTOR_SET SET NAME = 'Intergovernmental Panel on Climate Change (IPCC) 2006 (Commercial & Institutional)'
WHERE STD_FACTOR_SET_ID = 20 AND NAME = 'Intergovernmental Panel on Climate Change (IPCC) 2006';
UPDATE CSR.STD_FACTOR_SET SET NAME = 'North American Climate Registry (2011)'
WHERE STD_FACTOR_SET_ID = 6 AND NAME = 'North American Climate Registry';
UPDATE CSR.STD_FACTOR_SET SET NAME = 'Canada National Inventory Report 2011 (1990-2009)'
WHERE STD_FACTOR_SET_ID = 5 AND NAME = 'Canada National';

-- New standard measure conversions
BEGIN INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C) VALUES (26194, 9, 'kg/MMBTU (US)', 1054804000, 1, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C) VALUES (26195, 9, 'kg/ton-hour', 12660670.23144, 1, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- Correction to tree
UPDATE CSR.FACTOR_TYPE SET PARENT_ID = 10766 WHERE FACTOR_TYPE_ID = 10865;

-- New types for emission factor tree
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14967, 10620, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14968, 14967, 'Grid Heat Generated (Geothermal) - Annual (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14969, 14967, 'Grid Heat Generated (Geothermal) - Rolling Average (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14970, 10636, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14971, 14970, 'Grid Heat Generated (Geothermal) - Annual (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14972, 14970, 'Grid Heat Generated (Geothermal) - Rolling Average (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14973, 10652, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14974, 14973, 'Grid Heat Generated (Geothermal) - Annual (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14975, 14973, 'Grid Heat Generated (Geothermal) - Rolling Average (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14976, 10669, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14977, 14976, 'Grid Heat Transmission Loss (Geothermal) - Annual (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14978, 14976, 'Grid Heat Transmission Loss (Geothermal) - Rolling Average (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14979, 10685, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14980, 14979, 'Grid Heat Transmission Loss (Geothermal) - Annual (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14981, 14979, 'Grid Heat Transmission Loss (Geothermal) - Rolling Average (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14982, 10701, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14983, 14982, 'Grid Heat Transmission Loss (Geothermal) - Annual (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14984, 14982, 'Grid Heat Transmission Loss (Geothermal) - Rolling Average (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14985, 10718, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14986, 14985, 'Grid Heat Consumed (Geothermal) - Annual (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14987, 14985, 'Grid Heat Consumed (Geothermal) - Rolling Average (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14988, 10734, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14989, 14988, 'Grid Heat Consumed (Geothermal) - Annual (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14990, 14988, 'Grid Heat Consumed (Geothermal) - Rolling Average (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14991, 10750, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14992, 14991, 'Grid Heat Consumed (Geothermal) - Annual (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14993, 14991, 'Grid Heat Consumed (Geothermal) - Rolling Average (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14994, 10768, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14995, 14994, 'Non-Grid Heat Generated (Geothermal) - Annual (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14996, 14994, 'Non-Grid Heat Generated (Geothermal) - Rolling Average (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14997, 10784, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14998, 14997, 'Non-Grid Heat Generated (Geothermal) - Annual (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (14999, 14997, 'Non-Grid Heat Generated (Geothermal) - Rolling Average (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15000, 10800, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15001, 15000, 'Non-Grid Heat Generated (Geothermal) - Annual (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15002, 15000, 'Non-Grid Heat Generated (Geothermal) - Rolling Average (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15003, 10817, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15004, 15003, 'Non-Grid Heat Transmission Loss (Geothermal) - Annual (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15005, 15003, 'Non-Grid Heat Transmission Loss (Geothermal) - Rolling Average (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15006, 10833, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15007, 15006, 'Non-Grid Heat Transmission Loss (Geothermal) - Annual (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15008, 15006, 'Non-Grid Heat Transmission Loss (Geothermal) - Rolling Average (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15009, 10849, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15010, 15009, 'Non-Grid Heat Transmission Loss (Geothermal) - Annual (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15011, 15009, 'Non-Grid Heat Transmission Loss (Geothermal) - Rolling Average (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15012, 10866, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15013, 15012, 'Non-Grid Heat Consumed (Geothermal) - Annual (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15014, 15012, 'Non-Grid Heat Consumed (Geothermal) - Rolling Average (Direct)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15015, 10882, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15016, 15015, 'Non-Grid Heat Consumed (Geothermal) - Annual (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15017, 15015, 'Non-Grid Heat Consumed (Geothermal) - Rolling Average (Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15018, 10898, 'Geothermal', null, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15019, 15018, 'Non-Grid Heat Consumed (Geothermal) - Annual (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO CSR.FACTOR_TYPE (FACTOR_TYPE_ID, PARENT_ID, NAME, STD_MEASURE_ID, EGRID) VALUES (15020, 15018, 'Non-Grid Heat Consumed (Geothermal) - Rolling Average (Direct & Upstream)', 9, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

@update_tail