-- Please update version.sql too -- this keeps clean builds in sync
define version=2403
@update_header

--grants for csrexp
grant select, insert, update on chain.alert_partial_template to csrimp;
grant select, insert, update on chain.alert_partial_template to CSR;
grant select, insert, update on chain.alert_partial_template_param to csrimp;
grant select, insert, update on chain.alert_partial_template_param to CSR;
grant select, insert, update on chain.amount_unit to csrimp;
grant select, insert, update on chain.amount_unit to CSR;
grant select, insert, update on chain.applied_company_capability to csrimp;
grant select, insert, update on chain.applied_company_capability to CSR;
grant select, insert, update on chain.audit_request to csrimp;
grant select, insert, update on chain.audit_request to CSR;
grant select, insert, update on chain.audit_request_alert to csrimp;
grant select, insert, update on chain.audit_request_alert to CSR;
grant select, insert, update on chain.business_unit to csrimp;
grant select, insert, update on chain.business_unit to CSR;
grant select, insert, update on chain.business_unit_member to csrimp;
grant select, insert, update on chain.business_unit_member to CSR;
grant select, insert, update on chain.business_unit_supplier to csrimp;
grant select, insert, update on chain.business_unit_supplier to CSR;
grant select, insert, update on chain.chain_user_email_address_log to csrimp;
grant select, insert, update on chain.chain_user_email_address_log to CSR;
grant select, insert, update on chain.company_cc_email to csrimp;
grant select, insert, update on chain.company_cc_email to CSR;
grant select, insert, update on chain.company_header to csrimp;
grant select, insert, update on chain.company_header to CSR;
grant select, insert, update on chain.company_metric_type to csrimp;
grant select, insert, update on chain.company_metric_type to CSR;
grant select, insert, update on chain.company_metric to csrimp;
grant select, insert, update on chain.company_metric to CSR;
grant select, insert, update on chain.company_reference to csrimp;
grant select, insert, update on chain.company_reference to CSR;
grant select, insert, update on chain.company_tab to csrimp;
grant select, insert, update on chain.company_tab to CSR;
grant select, insert, update on chain.company_tag_group to csrimp;
grant select, insert, update on chain.company_tag_group to CSR;
grant select, insert, update on chain.component_type to csrimp;
grant select, insert, update on chain.component_type to CSR;
grant select, insert, update on chain.component_type_containment to csrimp;
grant select, insert, update on chain.component_type_containment to CSR;
grant select, insert, update on chain.component to csrimp;
grant select, insert, update on chain.component to CSR;
grant select, insert, update on chain.file_upload to csrimp;
grant select, insert, update on chain.file_upload to CSR;
grant select, insert, update on chain.component_document to csrimp;
grant select, insert, update on chain.component_document to CSR;
grant select, insert, update on chain.component_source to csrimp;
grant select, insert, update on chain.component_source to CSR;
grant select, insert, update on chain.component_tag to csrimp;
grant select, insert, update on chain.component_tag to CSR;
grant select, insert, update on chain.compound_filter to csrimp;
grant select, insert, update on chain.compound_filter to CSR;
grant select, insert, update on chain.customer_alert_entry_template to csrimp;
grant select, insert, update on chain.customer_alert_entry_template to CSR;
grant select, insert, update on chain.customer_alert_entry_type to csrimp;
grant select, insert, update on chain.customer_alert_entry_type to CSR;
grant select, insert, update on chain.default_product_code_type to csrimp;
grant select, insert, update on chain.default_product_code_type to CSR;
grant select, insert, update on chain.default_supp_rel_code_label to csrimp;
grant select, insert, update on chain.default_supp_rel_code_label to CSR;
grant select, insert, update on chain.email_stub to csrimp;
grant select, insert, update on chain.email_stub to CSR;
grant select, insert, update on chain.file_group to csrimp;
grant select, insert, update on chain.file_group to CSR;
grant select, insert, update on chain.file_group_file to csrimp;
grant select, insert, update on chain.file_group_file to CSR;
grant select, insert, update on chain.filter to csrimp;
grant select, insert, update on chain.filter to CSR;
grant select, insert, update on chain.filter_field to csrimp;
grant select, insert, update on chain.filter_field to CSR;
grant select, insert, update on chain.filter_value to csrimp;
grant select, insert, update on chain.filter_value to CSR;
grant select, insert, update on chain.filtersupplierreportlinks to csrimp;
grant select, insert, update on chain.filtersupplierreportlinks to CSR;
grant select, insert, update on chain.flow_filter to csrimp;
grant select, insert, update on chain.flow_filter to CSR;
grant select, insert, update on chain.invitation to csrimp;
grant select, insert, update on chain.invitation to CSR;
grant select, insert, update on chain.invitation_user_tpl to csrimp;
grant select, insert, update on chain.invitation_user_tpl to CSR;
grant select, insert, update on chain.message_definition to csrimp;
grant select, insert, update on chain.message_definition to CSR;
grant select, insert, update on chain.message_param to csrimp;
grant select, insert, update on chain.message_param to CSR;
grant select, insert, update on chain.questionnaire_group to csrimp;
grant select, insert, update on chain.questionnaire_group to CSR;
grant select, insert, update on chain.questionnaire_type to csrimp;
grant select, insert, update on chain.questionnaire_type to CSR;
grant select, insert, update on chain.flow_questionnaire_type to csrimp;
grant select, insert, update on chain.flow_questionnaire_type to CSR;
grant select, insert, update on chain.invitation_qnr_type_component to csrimp;
grant select, insert, update on chain.invitation_qnr_type_component to CSR;
grant select, insert, update on chain.message to csrimp;
grant select, insert, update on chain.message to CSR;
grant select, insert, update on chain.alert_entry to csrimp;
grant select, insert, update on chain.alert_entry to CSR;
grant select, insert, update on chain.alert_entry_param to csrimp;
grant select, insert, update on chain.alert_entry_param to CSR;
grant select, insert, update on chain.invitation_qnr_type to csrimp;
grant select, insert, update on chain.invitation_qnr_type to CSR;
grant select, insert, update on chain.message_recipient to csrimp;
grant select, insert, update on chain.message_recipient to CSR;
grant select, insert, update on chain.message_refresh_log to csrimp;
grant select, insert, update on chain.message_refresh_log to CSR;
grant select, insert, update on chain.newsflash to csrimp;
grant select, insert, update on chain.newsflash to CSR;
grant select, insert, update on chain.newsflash_company to csrimp;
grant select, insert, update on chain.newsflash_company to CSR;
grant select, insert, update on chain.newsflash_user_settings to csrimp;
grant select, insert, update on chain.newsflash_user_settings to CSR;
grant select, insert, update on chain.product to csrimp;
grant select, insert, update on chain.product to CSR;
grant select, insert, update on chain.product_code_type to csrimp;
grant select, insert, update on chain.product_code_type to CSR;
grant select, insert, update on chain.product_metric_type to csrimp;
grant select, insert, update on chain.product_metric_type to CSR;
grant select, insert, update on chain.product_revision to csrimp;
grant select, insert, update on chain.product_revision to CSR;
grant select, insert, update on chain.purchase_channel to csrimp;
grant select, insert, update on chain.purchase_channel to CSR;
grant select, insert, update on chain.purchased_component to csrimp;
grant select, insert, update on chain.purchased_component to CSR;
grant select, insert, update on chain.purchase to csrimp;
grant select, insert, update on chain.purchase to CSR;
grant select, insert, update on chain.purchase_tag to csrimp;
grant select, insert, update on chain.purchase_tag to CSR;
grant select, insert, update on chain.purchaser_follower to csrimp;
grant select, insert, update on chain.purchaser_follower to CSR;
grant select, insert, update on chain.qnnaire_share_alert_log to csrimp;
grant select, insert, update on chain.qnnaire_share_alert_log to CSR;
grant select, insert, update on chain.qnr_action_security_mask to csrimp;
grant select, insert, update on chain.qnr_action_security_mask to CSR;
grant select, insert, update on chain.questionnaire to csrimp;
grant select, insert, update on chain.questionnaire to CSR;
grant select, insert, update on chain.qnr_share_log_entry to csrimp;
grant select, insert, update on chain.qnr_share_log_entry to CSR;
grant select, insert, update on chain.qnr_status_log_entry to csrimp;
grant select, insert, update on chain.qnr_status_log_entry to CSR;
grant select, insert, update on chain.questionnaire_expiry_alert to csrimp;
grant select, insert, update on chain.questionnaire_expiry_alert to CSR;
grant select, insert, update on chain.questionnaire_invitation to csrimp;
grant select, insert, update on chain.questionnaire_invitation to CSR;
grant select, insert, update on chain.questionnaire_metric_type to csrimp;
grant select, insert, update on chain.questionnaire_metric_type to CSR;
grant select, insert, update on chain.questionnaire_metric to csrimp;
grant select, insert, update on chain.questionnaire_metric to CSR;
grant select, insert, update on chain.questionnaire_share to csrimp;
grant select, insert, update on chain.questionnaire_share to CSR;
grant select, insert, update on chain.questionnaire_user to csrimp;
grant select, insert, update on chain.questionnaire_user to CSR;
grant select, insert, update on chain.questionnaire_user_action to csrimp;
grant select, insert, update on chain.questionnaire_user_action to CSR;
grant select, insert, update on chain.recipient to csrimp;
grant select, insert, update on chain.recipient to CSR;
grant select, insert, update on chain.reference to csrimp;
grant select, insert, update on chain.reference to CSR;
grant select, insert, update on chain.reset_password to csrimp;
grant select, insert, update on chain.reset_password to CSR;
grant select, insert, update on chain.review_alert to csrimp;
grant select, insert, update on chain.review_alert to CSR;
grant select, insert, update on chain.saved_filter to csrimp;
grant select, insert, update on chain.saved_filter to CSR;
grant select, insert, update on chain.scheduled_alert to csrimp;
grant select, insert, update on chain.scheduled_alert to CSR;
grant select, insert, update on chain.supplier_audit to csrimp;
grant select, insert, update on chain.supplier_audit to CSR;
grant select, insert, update on chain.task to csrimp;
grant select, insert, update on chain.task to CSR;
grant select, insert, update on chain.task_action_trigger to csrimp;
grant select, insert, update on chain.task_action_trigger to CSR;
grant select, insert, update on chain.task_entry to csrimp;
grant select, insert, update on chain.task_entry to CSR;
grant select, insert, update on chain.task_entry_date to csrimp;
grant select, insert, update on chain.task_entry_date to CSR;
grant select, insert, update on chain.task_entry_file to csrimp;
grant select, insert, update on chain.task_entry_file to CSR;
grant select, insert, update on chain.task_entry_note to csrimp;
grant select, insert, update on chain.task_entry_note to CSR;
grant select, insert, update on chain.task_scheme to csrimp;
grant select, insert, update on chain.task_scheme to CSR;
grant select, insert, update on chain.task_type to csrimp;
grant select, insert, update on chain.task_type to CSR;
grant select, insert, update on chain.task_invitation_qnr_type to csrimp;
grant select, insert, update on chain.task_invitation_qnr_type to CSR;
grant select, insert, update on chain.ucd_logon to csrimp;
grant select, insert, update on chain.ucd_logon to CSR;
grant select, insert, update on chain.uninvited_supplier to csrimp;
grant select, insert, update on chain.uninvited_supplier to CSR;
grant select, insert, update on chain.url_overrides to csrimp;
grant select, insert, update on chain.url_overrides to CSR;
grant select, insert, update on chain.user_alert_entry_type to csrimp;
grant select, insert, update on chain.user_alert_entry_type to CSR;
grant select, insert, update on chain.user_message_log to csrimp;
grant select, insert, update on chain.user_message_log to CSR;
grant select, insert, update on chain.validated_purchased_component to csrimp;
grant select, insert, update on chain.validated_purchased_component to CSR;
grant select, insert, update on chain.worksheet_file_upload to csrimp;
grant select, insert, update on chain.worksheet_file_upload to CSR;
grant select, insert, update on chain.default_message_definition to csrimp;
grant select, insert, update on chain.default_message_definition to CSR;
grant select, insert, update on chain.message_definition_lookup to csrimp;
grant select, insert, update on chain.message_definition_lookup to CSR;
grant select, insert, update on chain.filter_type to csrimp;
grant select, insert, update on chain.filter_type to CSR;

grant select, insert, update on csr.worksheet to csrimp;
grant select, insert, update on csr.worksheet_column to csrimp;
grant select, insert, update on csr.worksheet_column_value_map to csrimp;
grant select, insert, update on csr.worksheet_row to csrimp;
grant select, insert, update on csr.worksheet_value_map to csrimp;
grant select, insert, update on csr.worksheet_value_map_value to csrimp;

grant select on chain.alert_entry_id_seq to csrimp;
grant select on chain.alert_entry_id_seq to CSR;
grant select on chain.message_id_seq to csrimp;
grant select on chain.message_id_seq to CSR;
grant select on chain.scheduled_alert_id_seq to csrimp;
grant select on chain.scheduled_alert_id_seq to CSR;
grant select on chain.audit_request_id_seq to csrimp;
grant select on chain.audit_request_id_seq to CSR;
grant select on chain.company_header_id_seq to csrimp;
grant select on chain.company_header_id_seq to CSR;
grant select on chain.company_tab_id_seq to csrimp;
grant select on chain.company_tab_id_seq to CSR;
grant select on chain.component_id_seq to csrimp;
grant select on chain.component_id_seq to CSR;
grant select on chain.compound_filter_id_seq to csrimp;
grant select on chain.compound_filter_id_seq to CSR;
grant select on chain.file_group_id_seq to csrimp;
grant select on chain.file_group_id_seq to CSR;
grant select on chain.file_group_file_id_seq to csrimp;
grant select on chain.file_group_file_id_seq to CSR;
grant select on chain.filter_id_seq to csrimp;
grant select on chain.filter_id_seq to CSR;
grant select on chain.filter_type_id_seq to csrimp;
grant select on chain.filter_type_id_seq to CSR;
grant select on chain.filter_field_id_seq to csrimp;
grant select on chain.filter_field_id_seq to CSR;
grant select on chain.filter_value_id_seq to csrimp;
grant select on chain.filter_value_id_seq to CSR;
grant select on chain.questionnaire_type_id_seq to csrimp;
grant select on chain.questionnaire_type_id_seq to CSR;
grant select on chain.invitation_id_seq to csrimp;
grant select on chain.invitation_id_seq to CSR;
grant select on chain.message_definition_id_seq to csrimp;
grant select on chain.message_definition_id_seq to CSR;
grant select on chain.questionnaire_id_seq to csrimp;
grant select on chain.questionnaire_id_seq to CSR;
grant select on chain.recipient_id_seq to csrimp;
grant select on chain.recipient_id_seq to CSR;
grant select on chain.newsflash_id_seq to csrimp;
grant select on chain.newsflash_id_seq to CSR;
grant select on chain.product_id_seq to csrimp;
grant select on chain.product_id_seq to CSR;
grant select on chain.purchase_id_seq to csrimp;
grant select on chain.purchase_id_seq to CSR;
grant select on chain.questionnaire_share_id_seq to csrimp;
grant select on chain.questionnaire_share_id_seq to CSR;
grant select on chain.task_id_seq to csrimp;
grant select on chain.task_id_seq to CSR;
grant select on chain.task_type_id_seq to csrimp;
grant select on chain.task_type_id_seq to CSR;
grant select on chain.task_entry_id_seq to csrimp;
grant select on chain.task_entry_id_seq to CSR;

grant select on csr.worksheet_id_seq to csrimp;
grant select on csr.value_map_id_seq to csrimp;

@../schema_pkg
@../schema_body

@update_tail
