-- Please update version.sql too -- this keeps clean builds in sync
define version=2469
@update_header

DECLARE 
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM CSR.STD_FACTOR 
   WHERE STD_MEASURE_CONVERSION_ID=28147;
  
  IF v_count = 0 THEN
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28147
     WHERE STD_MEASURE_CONVERSION_ID=28145
       AND STD_FACTOR_SET_ID>=50;
    
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28146
     WHERE STD_MEASURE_CONVERSION_ID=28144
       AND STD_FACTOR_SET_ID>=50;
    
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28145
     WHERE STD_MEASURE_CONVERSION_ID=28143
       AND STD_FACTOR_SET_ID>=50;
    
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28144
     WHERE STD_MEASURE_CONVERSION_ID=28142
       AND STD_FACTOR_SET_ID>=50;
    
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28143
     WHERE STD_MEASURE_CONVERSION_ID=28141
       AND STD_FACTOR_SET_ID>=50;
    
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28142
     WHERE STD_MEASURE_CONVERSION_ID=28140
       AND STD_FACTOR_SET_ID>=50;
    
    UPDATE CSR.STD_FACTOR
       SET STD_MEASURE_CONVERSION_ID=28141
     WHERE STD_MEASURE_CONVERSION_ID=28139
       AND STD_FACTOR_SET_ID>=50;
  END IF;
END;
/

@update_tail