-- Please update version.sql too -- this keeps clean builds in sync
define version=13
@update_header


-- 
-- TABLE: DIARY_EVENT 
--

CREATE TABLE DIARY_EVENT(
    DIARY_EVENT_SID    NUMBER(10,0)         NOT NULL,
    CSR_ROOT_SID       NUMBER(10, 0)    NOT NULL,
    DESCRIPTION        VARCHAR2(255)    NOT NULL,
    NOTES              CLOB              DEFAULT EMPTY_CLOB() NULL,
    DTM                DATE             NOT NULL,
    CREATED_DTM        DATE              DEFAULT SYSDATE NOT NULL,
    CREATED_BY_SID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK127 PRIMARY KEY (DIARY_EVENT_SID)
)
;



-- 
-- TABLE: DIARY_EVENT_GROUP 
--

CREATE TABLE DIARY_EVENT_GROUP(
    DIARY_EVENT_SID    NUMBER(10,0)         NOT NULL,
    GROUP_SID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK128 PRIMARY KEY (DIARY_EVENT_SID, GROUP_SID)
)
;


-- 
-- TABLE: DIARY_EVENT 
--

ALTER TABLE DIARY_EVENT ADD CONSTRAINT RefCSR_USER200 
    FOREIGN KEY (CREATED_BY_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE DIARY_EVENT ADD CONSTRAINT RefCUSTOMER201 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;


-- 
-- TABLE: DIARY_EVENT_GROUP 
--

ALTER TABLE DIARY_EVENT_GROUP ADD CONSTRAINT RefDIARY_EVENT202 
    FOREIGN KEY (DIARY_EVENT_SID)
    REFERENCES DIARY_EVENT(DIARY_EVENT_SID)
;


@update_tail
