-- Please update version.sql too -- this keeps clean builds in sync
define version=748
@update_header

ALTER TABLE csr.RELATED_AXIS_MEMBER DROP CONSTRAINT FK_AXIS_MBR_REL_AXIS_MBR;

ALTER TABLE CSR.RELATED_AXIS_MEMBER ADD CONSTRAINT FK_AXIS_MBR_REL_AXIS_MBR 
    FOREIGN KEY (APP_SID, RELATED_AXIS_ID, RELATED_AXIS_MEMBER_ID)
    REFERENCES CSR.AXIS_MEMBER(APP_SID, AXIS_ID, AXIS_MEMBER_ID)
;

@update_tail
