-- Please update version.sql too -- this keeps clean builds in sync
define version=07
@update_header

ALTER TABLE CSR.VAL
MODIFY(VAL_NUMBER NUMBER(20,6));


ALTER TABLE CSR.VAL
MODIFY(ENTRY_VAL_NUMBER NUMBER(20,6));

ALTER TABLE CSR.VAL_CHANGE
MODIFY(VAL_NUMBER NUMBER(20,6));


ALTER TABLE CSR.VAL_CHANGE
MODIFY(ENTRY_VAL_NUMBER NUMBER(20,6));


ALTER TABLE CSR.SHEET_VALUE
MODIFY(VAL_NUMBER NUMBER(20,6));


ALTER TABLE CSR.SHEET_VALUE
MODIFY(ENTRY_VAL_NUMBER NUMBER(20,6));


ALTER TABLE CSR.SHEET_VALUE_CHANGE
MODIFY(VAL_NUMBER NUMBER(20,6));


ALTER TABLE CSR.SHEET_VALUE_CHANGE
MODIFY(ENTRY_VAL_NUMBER NUMBER(20,6));



DROP TYPE T_VAL_TABLE;

CREATE OR REPLACE TYPE T_VAL_ROW AS 
  OBJECT ( 
	PERIOD_START_DTM		DATE,
	PERIOD_END_DTM			DATE,
	VAL_NUMBER			NUMBER(20, 6),
	VAL_NULL			NUMBER(10),
	TARGET_NUMBER			NUMBER(20, 6),
	TARGET_NULL			NUMBER(10),
	ESTIMATED			NUMBER(10),
	VAL_IDS_USED			VARCHAR2(2000),
	REGION_SID			NUMBER(10),
	FLAGS				NUMBER(10)
  );
/
CREATE OR REPLACE TYPE T_VAL_TABLE AS 
  TABLE OF T_VAL_ROW;
/






DROP TYPE T_CHANGES_TABLE;

CREATE OR REPLACE TYPE T_CHANGES_ROW AS 
  OBJECT ( 
	CHANGE_TYPE	NUMBER(10,0),
	FROM_VALUE	NUMBER(20,6),
	TO_VALUE	NUMBER(20,6),
	DESCRIPTION	VARCHAR2(1024)
	
  );
/
CREATE OR REPLACE TYPE T_CHANGES_TABLE AS 
  TABLE OF T_CHANGES_ROW;
/



@update_tail
