-- Please update version.sql too -- this keeps clean builds in sync
define version=1173
@update_header 

UPDATE ct.bt_region_factors SET temp_emission_factor = 950.9254615598 WHERE region_id = 0;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN CAR_PCT TO CAR_USE_PCT
;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN BUS_PCT TO BUS_USE_PCT
;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN TRAIN_PCT TO TRAIN_USE_PCT
;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN MOTORBIKE_PCT TO MOTORBIKE_USE_PCT
;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN BIKE_PCT TO BIKE_USE_PCT
;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN WALK_PCT TO WALK_USE_PCT
;

ALTER TABLE CT.BT_REGION_FACTORS
RENAME COLUMN AIR_PCT TO AIR_USE_PCT
;

ALTER TABLE CT.BT_TRAVEL_MODE
 ADD (IS_DEFAULT  NUMBER(1) DEFAULT 0  NOT NULL);
 
 ALTER TABLE CT.BT_TRAVEL_MODE ADD CONSTRAINT CC_BT_TR_MD_IS_DEFAULT 
    CHECK (IS_DEFAULT IN (1,0));
 
ALTER TABLE CT.BT_TRAVEL_MODE
RENAME COLUMN EF_PER_KM TO EF_KG_CO2_PER_KM;

--- Set travel mode defaults
UPDATE ct.bt_travel_mode SET is_default = 1 WHERE description = 'Average petrol car';
UPDATE ct.bt_travel_mode SET is_default = 1 WHERE description = 'Average petrol motorbike';
UPDATE ct.bt_travel_mode SET is_default = 1 WHERE description = 'Average local bus';
UPDATE ct.bt_travel_mode SET is_default = 1 WHERE description = 'Domestic rail';
UPDATE ct.bt_travel_mode SET is_default = 1 WHERE description = 'Average air travel';

ALTER TABLE CT.BT_PROFILE
ADD (CAR_OCCUPANCY_RATE NUMBER(20,10));

UPDATE CT.BT_PROFILE SET CAR_OCCUPANCY_RATE = 1.2;

ALTER TABLE CT.BT_PROFILE
MODIFY(CAR_OCCUPANCY_RATE  NOT NULL);

ALTER TABLE CT.BT_PROFILE ADD CONSTRAINT CC_BT_PRF_CAR_OCCUPANCY_RATE 
    CHECK (CAR_OCCUPANCY_RATE >= 0);

ALTER TABLE CT.BT_PROFILE
MODIFY(FTE_WHO_TRAVEL_PCT NUMBER(20,17));


ALTER TABLE CT.BT_PROFILE
MODIFY(CAR_USE_PCT NUMBER(20,17));


ALTER TABLE CT.BT_PROFILE
MODIFY(BUS_USE_PCT NUMBER(20,17));


ALTER TABLE CT.BT_PROFILE
MODIFY(TRAIN_USE_PCT NUMBER(20,17));


ALTER TABLE CT.BT_PROFILE
MODIFY(MOTORBIKE_USE_PCT NUMBER(20,17));


ALTER TABLE CT.BT_PROFILE
MODIFY(BIKE_USE_PCT NUMBER(20,17));

ALTER TABLE CT.BT_PROFILE
MODIFY(WALK_USE_PCT NUMBER(20,17));


ALTER TABLE CT.BT_PROFILE
MODIFY(AIR_USE_PCT NUMBER(20,17));

CREATE TABLE CT.BT_EMISSIONS (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    BREAKDOWN_ID NUMBER(10) NOT NULL,
    REGION_ID NUMBER(10) NOT NULL,
    CALCULATION_SOURCE_ID NUMBER(10) NOT NULL,
    CAR_KG_CO2 NUMBER(30,10) NOT NULL,
    BUS_KG_CO2 NUMBER(30,10) NOT NULL,
    TRAIN_KG_CO2 NUMBER(30,10) NOT NULL,
    MOTORBIKE_KG_CO2 NUMBER(30,10) NOT NULL,
    BIKE_KG_CO2 NUMBER(30,10) NOT NULL,
    WALK_KG_CO2 NUMBER(30,10) NOT NULL,
    AIR_KG_CO2 NUMBER(30,10) NOT NULL,
    CONSTRAINT PK_BT_EM PRIMARY KEY (APP_SID, BREAKDOWN_ID, REGION_ID, CALCULATION_SOURCE_ID)
);

CREATE TABLE CT.CALCULATION_SOURCE (
    CALCULATION_SOURCE_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CALCULATION_SOURCE PRIMARY KEY (CALCULATION_SOURCE_ID)
);

INSERT INTO CT.CALCULATION_SOURCE (CALCULATION_SOURCE_ID, DESCRIPTION) VALUES (1, 'Hotspotter');
INSERT INTO CT.CALCULATION_SOURCE (CALCULATION_SOURCE_ID, DESCRIPTION) VALUES (2, 'Profile');
INSERT INTO CT.CALCULATION_SOURCE (CALCULATION_SOURCE_ID, DESCRIPTION) VALUES (3, 'Product');
INSERT INTO CT.CALCULATION_SOURCE (CALCULATION_SOURCE_ID, DESCRIPTION) VALUES (4, 'Questionnaire');
INSERT INTO CT.CALCULATION_SOURCE (CALCULATION_SOURCE_ID, DESCRIPTION) VALUES (5, 'Apportionment');

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_AIR_KG_CO2 
    CHECK (AIR_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_BIKE_KG_CO2 
    CHECK (BIKE_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_BUS_KG_CO2 
    CHECK (BUS_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_CAR_KG_CO2 
    CHECK (CAR_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_MOTORBIKE_KG_CO2 
    CHECK (MOTORBIKE_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_TRAIN_KG_CO2 
    CHECK (TRAIN_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CC_BT_EM_WALK_KG_CO2 
    CHECK (WALK_KG_CO2 >= 0);

ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT B_R_BT_EM 
    FOREIGN KEY (APP_SID, BREAKDOWN_ID, REGION_ID) REFERENCES CT.BREAKDOWN_REGION (APP_SID,BREAKDOWN_ID,REGION_ID);
	
ALTER TABLE CT.BT_EMISSIONS ADD CONSTRAINT CALCULATION_SOURCE_BT_EM 
    FOREIGN KEY (CALCULATION_SOURCE_ID) REFERENCES CT.CALCULATION_SOURCE (CALCULATION_SOURCE_ID);
	
create or replace package ct.value_chain_report_pkg as
procedure dummy;
end;
/
create or replace package body ct.value_chain_report_pkg as
procedure dummy
as
begin
	null;
end;
end;
/
grant execute on ct.value_chain_report_pkg to web_user;
	
@..\ct\rls
@..\ct\ct_pkg	
@..\ct\company_pkg
@..\ct\company_body
@..\ct\breakdown_pkg
@..\ct\breakdown_body
@..\ct\breakdown_type_pkg
@..\ct\breakdown_type_body
@..\ct\breakdown_group_pkg
@..\ct\breakdown_group_body
@..\ct\business_travel_pkg
@..\ct\business_travel_body
@..\ct\products_services_pkg
@..\ct\products_services_body
@..\ct\value_chain_report_pkg
@..\ct\value_chain_report_body
@..\ct\snapshot_body

	
@update_tail