-- Please update version too -- this keeps clean builds in sync
define version=1733
@update_header

CREATE TABLE CSR.BATCH_JOB_CMS_IMPORT (
	APP_SID					NUMBER(10)		DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	BATCH_JOB_ID			NUMBER(10) 		NOT NULL,
	FILE_NAME				VARCHAR2(255)	NOT NULL,
	FILE_DATA				BLOB			NOT NULL,
	TABLE_NAME				VARCHAR2(255)	NOT NULL,
	REGION_SID				NUMBER(10)		NULL,
	FLOW_LABEL				VARCHAR2(255)	NULL,
	SETTINGS_XML			XMLTYPE			NOT NULL,
	CONSTRAINT PK_BJCI PRIMARY KEY (APP_SID, BATCH_JOB_ID) ENABLE
);

ALTER TABLE CSR.BATCH_JOB_CMS_IMPORT ADD CONSTRAINT FK_BJ_BJCI FOREIGN KEY (APP_SID, BATCH_JOB_ID) REFERENCES CSR.BATCH_JOB (APP_SID, BATCH_JOB_ID);

CREATE OR REPLACE PACKAGE CMS.BATCH_IMPORT
AS
PROCEDURE dummy;
END;
/

CREATE OR REPLACE PACKAGE BODY CMS.BATCH_IMPORT
AS
PROCEDURE dummy
AS
BEGIN
	NULL;
END;
END;
/

GRANT EXECUTE ON CMS.BATCH_IMPORT TO CSR;
GRANT SELECT, UPDATE, DELETE, INSERT, REFERENCES ON CSR.BATCH_JOB_CMS_IMPORT TO CMS;

@..\batch_job_pkg

REM @..\..\..\aspen2\cms\db\batch_import_pkg
REM @..\..\..\aspen2\cms\db\batch_import_body

@update_tail