-- Please update version.sql too -- this keeps clean builds in sync
define version=2815
define minor_version=18
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
DROP INDEX CSR.UK_QS_EXPR;
CREATE UNIQUE INDEX CSR.UK_QS_EXPR ON CSR.QUICK_SURVEY_EXPR(APP_SID, SURVEY_SID, SURVEY_VERSION, EXPR_ID);

ALTER TABLE CSR.QUICK_SURVEY_EXPR_ACTION
DROP CONSTRAINT CHK_QS_EXPR_ACTION_TYPE_FK;

ALTER TABLE CSR.QUICK_SURVEY_EXPR DROP COLUMN NAME;
ALTER TABLE CSR.QUICK_SURVEY_EXPR DROP COLUMN DESCRIPTION;

ALTER TABLE CSRIMP.QUICK_SURVEY_EXPR DROP COLUMN NAME;
ALTER TABLE CSRIMP.QUICK_SURVEY_EXPR DROP COLUMN DESCRIPTION;

ALTER TABLE CSRIMP.QUICK_SURVEY_EXPR_ACTION ADD MANDATORY_QUESTION_ID NUMBER(10) NULL;
ALTER TABLE CSRIMP.QUICK_SURVEY_EXPR_ACTION ADD SHOW_PAGE_ID NUMBER(10) NULL;

ALTER TABLE CSR.QUICK_SURVEY_EXPR_ACTION ADD SHOW_PAGE_ID  NUMBER(10) NULL;
ALTER TABLE CSR.QUICK_SURVEY_EXPR_ACTION ADD CONSTRAINT QS_EA_SHOW_PAGE_QUESTION 
    FOREIGN KEY (APP_SID, SHOW_PAGE_ID, SURVEY_VERSION) REFERENCES CSR.QUICK_SURVEY_QUESTION (APP_SID, QUESTION_ID, SURVEY_VERSION);


ALTER TABLE CSR.QUICK_SURVEY_EXPR_ACTION
ADD CONSTRAINT CHK_QS_EXPR_ACTION_TYPE_FK CHECK (
	(ACTION_TYPE = 'nc' AND QS_EXPR_NON_COMPL_ACTION_ID IS NOT NULL
	  AND QS_EXPR_MSG_ACTION_ID IS NULL AND SHOW_QUESTION_ID IS NULL
	  AND MANDATORY_QUESTION_ID IS NULL AND SHOW_PAGE_ID IS NULL)
	OR
	(ACTION_TYPE = 'msg' AND QS_EXPR_NON_COMPL_ACTION_ID IS NULL
	  AND QS_EXPR_MSG_ACTION_ID IS NOT NULL AND SHOW_QUESTION_ID IS NULL
	  AND MANDATORY_QUESTION_ID IS NULL AND SHOW_PAGE_ID IS NULL)
	OR
	(ACTION_TYPE = 'show_q' AND QS_EXPR_NON_COMPL_ACTION_ID IS NULL
	  AND QS_EXPR_MSG_ACTION_ID IS NULL AND SHOW_QUESTION_ID IS NOT NULL
	  AND MANDATORY_QUESTION_ID IS NULL AND SHOW_PAGE_ID IS NULL)
	OR
	(ACTION_TYPE = 'mand_q' AND QS_EXPR_NON_COMPL_ACTION_ID IS NULL
	  AND QS_EXPR_MSG_ACTION_ID IS NULL AND SHOW_QUESTION_ID IS NULL
	  AND MANDATORY_QUESTION_ID IS NOT NULL AND SHOW_PAGE_ID IS NULL)
	OR
	(ACTION_TYPE = 'show_p' AND QS_EXPR_NON_COMPL_ACTION_ID IS NULL
	  AND QS_EXPR_MSG_ACTION_ID IS NULL AND SHOW_QUESTION_ID IS NULL
	  AND MANDATORY_QUESTION_ID IS NULL AND SHOW_PAGE_ID IS NOT NULL)
  );
-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please add the path to the create_views file which will contain your view changes.  I will use this version when making the major scripts.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Packages ***
@../quick_survey_pkg

@../csrimp/imp_body
@../schema_body
@../quick_survey_body
@update_tail
