-- Please update version.sql too -- this keeps clean builds in sync
define version=1133
@update_header

CREATE SEQUENCE CT.WORKSHEET_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;

ALTER TABLE CT.WORKSHEET DROP CONSTRAINT WORKSHEET_ROW_WORKSHEET;

ALTER TABLE CT.WORKSHEET_ROW DROP CONSTRAINT WORKSHEET_WORKSHEET_ROW;

ALTER TABLE CT.WORKSHEET_ROW DROP CONSTRAINT CHAIN_CO_WORKSHEET_ROW;

ALTER TABLE CT.WORKSHEET_COLUMN DROP CONSTRAINT WORKSHEET_WS_COLUMN;

ALTER TABLE CT.WORKSHEET_COLUMN DROP CONSTRAINT WS_COLUMN_TYPE_WS_COLUMN;

ALTER TABLE CT.WORKSHEET DROP CONSTRAINT PK_WORKSHEET;

ALTER TABLE CT.WORKSHEET DROP COLUMN SHEET_INDEX;

ALTER TABLE CT.WORKSHEET DROP COLUMN HEADER_WORKSHEET_ROW_ID;

ALTER TABLE CT.WORKSHEET ADD
    WORKSHEET_ID NUMBER NOT NULL;

ALTER TABLE CT.WORKSHEET ADD
    SHEET_NAME VARCHAR2(1000) NOT NULL;

ALTER TABLE CT.WORKSHEET ADD
    LOWER_SHEET_NAME VARCHAR2(1000) NOT NULL;

ALTER TABLE CT.WORKSHEET ADD    
    HEADER_ROW_INDEX NUMBER(10) NOT NULL;

ALTER TABLE CT.WORKSHEET RENAME COLUMN WORKBOOK_SID TO FILE_UPLOAD_SID;

ALTER TABLE CT.WORKSHEET ADD CONSTRAINT TUC_WORKSHEET_1 
    UNIQUE (APP_SID, FILE_UPLOAD_SID, LOWER_SHEET_NAME);

ALTER TABLE CT.WORKSHEET ADD CONSTRAINT TCC_WORKSHEET_2 
	CHECK (LOWER_SHEET_NAME = LOWER(TRIM(SHEET_NAME)));

ALTER TABLE CT.WORKSHEET ADD CONSTRAINT PK_WORKSHEET 
    PRIMARY KEY (APP_SID, WORKSHEET_ID);

/* ---------------------------------------------------------------------- */
/* Modify table "WORKSHEET_ROW"                                           */
/* ---------------------------------------------------------------------- */

ALTER TABLE CT.WORKSHEET_ROW DROP CONSTRAINT CC_WORKSHEET_ROW_IGNORE;

ALTER TABLE CT.WORKSHEET_ROW DROP CONSTRAINT TUC_WORKSHEET_ROW_1;

ALTER TABLE CT.WORKSHEET_ROW DROP COLUMN WORKBOOK_SID;

ALTER TABLE CT.WORKSHEET_ROW DROP COLUMN SHEET_INDEX;

ALTER TABLE CT.WORKSHEET_ROW ADD
    WORKSHEET_ID NUMBER NOT NULL;

ALTER TABLE CT.WORKSHEET_ROW ADD
    CHECK (ROW_INDEX >= 0);

ALTER TABLE CT.WORKSHEET_ROW ADD CONSTRAINT CC_WORKSHEET_ROW_IGNORE 
    CHECK (IGNORE IN (1,0));

ALTER TABLE CT.WORKSHEET_ROW ADD CONSTRAINT TUC_WORKSHEET_ROW_1 
    UNIQUE (APP_SID, ROW_INDEX, WORKSHEET_ID);

/* ---------------------------------------------------------------------- */
/* Modify table "WORKSHEET_COLUMN"                                        */
/* ---------------------------------------------------------------------- */

ALTER TABLE CT.WORKSHEET_COLUMN DROP CONSTRAINT PK_WORKSHEET_COLUMN;

ALTER TABLE CT.WORKSHEET_COLUMN DROP CONSTRAINT TUC_WORKSHEET_COLUMN_1;

ALTER TABLE CT.WORKSHEET_COLUMN DROP COLUMN WORKBOOK_SID;

ALTER TABLE CT.WORKSHEET_COLUMN DROP COLUMN SHEET_INDEX;

ALTER TABLE CT.WORKSHEET_COLUMN ADD
    WORKSHEET_ID NUMBER NOT NULL;

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT PK_WS_COLUMN 
    PRIMARY KEY (APP_SID, WORKSHEET_ID, WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT TUC_WS_COLUMN_1 
    UNIQUE (COLUMN_INDEX, APP_SID, WORKSHEET_ID);

/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

ALTER TABLE CT.WORKSHEET ADD CONSTRAINT CUSTOMER_OPTIONS_WORKSHEET 
    FOREIGN KEY (APP_SID) REFERENCES CT.CUSTOMER_OPTIONS (APP_SID);

ALTER TABLE CT.WORKSHEET_ROW ADD CONSTRAINT WORKSHEET_WORKSHEET_ROW 
    FOREIGN KEY (APP_SID, WORKSHEET_ID) REFERENCES CT.WORKSHEET (APP_SID,WORKSHEET_ID);

ALTER TABLE CT.WORKSHEET_ROW ADD CONSTRAINT CUSTOMER_OPTIONS_WORKSHEET_ROW 
    FOREIGN KEY (APP_SID) REFERENCES CT.CUSTOMER_OPTIONS (APP_SID);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT WORKSHEET_WS_COLUMN 
    FOREIGN KEY (APP_SID, WORKSHEET_ID) REFERENCES  CT.WORKSHEET (APP_SID,WORKSHEET_ID);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT WS_COLUMN_TYPE_WS_COLUMN 
    FOREIGN KEY (WORKSHEET_COLUMN_TYPE_ID) REFERENCES  CT.WORKSHEET_COLUMN_TYPE (WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.EC_QUESTIONNAIRE DROP COLUMN BREAKDOWN_GROUP_ID;

ALTER TABLE CT.EC_QUESTIONNAIRE ADD
	BREAKDOWN_ID NUMBER(10) NOT NULL;

ALTER TABLE CT.EC_QUESTIONNAIRE ADD
	REGION_ID NUMBER(10) NOT NULL;

ALTER TABLE CT.EC_QUESTIONNAIRE ADD CONSTRAINT B_R_EC_QUESTIONNAIRE 
    FOREIGN KEY (APP_SID, BREAKDOWN_ID, REGION_ID) REFERENCES CT.BREAKDOWN_REGION (APP_SID,BREAKDOWN_ID,REGION_ID);

-- Add defaults to app_sid columns
ALTER TABLE CT.CUSTOMER_OPTIONS MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.WORKSHEET_COLUMN MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.BREAKDOWN_GROUP MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.EC_OPTIONS MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.BT_OPTIONS MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.UP_OPTIONS MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.PS_OPTIONS MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.BT_PROFILE MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.EC_QUESTIONNAIRE_ANSWERS MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.BREAKDOWN_REGION_GROUP MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');
ALTER TABLE CT.EC_QUESTIONNAIRE MODIFY APP_SID DEFAULT SYS_CONTEXT('SECURITY', 'APP');

grant execute on chain.helper_pkg to CT;
grant execute on chain.upload_pkg to CT;

@..\chain\upload_pkg
@..\chain\upload_body

@..\ct\excel_pkg
@..\ct\excel_body

grant execute on ct.excel_pkg to web_user;

@update_tail
