-- Please update version.sql too -- this keeps clean builds in sync
define version=05
@update_header

alter table sheet_Value add (file_upload_sid number(10,0));

alter table sheet_Value_change add (file_upload_sid number(10,0));



ALTER TABLE SHEET_VALUE ADD CONSTRAINT RefFILE_UPLOAD172 
    FOREIGN KEY (FILE_UPLOAD_SID)
    REFERENCES FILE_UPLOAD(FILE_UPLOAD_SID)
;


ALTER TABLE SHEET_VALUE_CHANGE ADD CONSTRAINT RefFILE_UPLOAD173 
    FOREIGN KEY (FILE_UPLOAD_SID)
    REFERENCES FILE_UPLOAD(FILE_UPLOAD_SID)
;

CREATE TABLE IND_FLAG(
    IND_SID        NUMBER(10, 0)    NOT NULL,
    FLAG           NUMBER(10, 0)    NOT NULL,
    DESCRIPTION    VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK105 PRIMARY KEY (IND_SID, FLAG)
);

ALTER TABLE SHEET_VALUE ADD (
    FLAG                           NUMBER(10, 0));


ALTER TABLE SHEET_VALUE_CHANGE ADD (
    FLAG                           NUMBER(10, 0));


ALTER TABLE IND_FLAG ADD CONSTRAINT RefIND176 
    FOREIGN KEY (IND_SID)
    REFERENCES IND(IND_SID)
;



ALTER TABLE SHEET_VALUE ADD CONSTRAINT RefIND_FLAG177 
    FOREIGN KEY (IND_SID, FLAG)
    REFERENCES IND_FLAG(IND_SID, FLAG)
;


ALTER TABLE SHEET_VALUE_CHANGE ADD CONSTRAINT RefIND_FLAG179 
    FOREIGN KEY (IND_SID, FLAG)
    REFERENCES IND_FLAG(IND_SID, FLAG)
;

@update_tail
