-- Please update version.sql too -- this keeps clean builds in sync
define version=2157
@update_header

INSERT INTO CSR.STD_MEASURE (STD_MEASURE_ID, NAME, DESCRIPTION, SCALE, FORMAT_MASK, REGIONAL_AGGREGATION, CUSTOM_FIELD, PCT_OWNERSHIP_APPLIES, M, KG, S, A, K, MOL, CD) VALUES (36, 'kg.m^2/s^3', 'kg.m^2/s^3', 0, '#,##0', 'sum', NULL, 0, 2, 1, -3, 0, 0, 0, 0);

INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28126, 36, 'W', 1, 1, 0, 1);
INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28127, 36, 'kW', 0.0010, 1, 0, 1);
INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28128, 36, 'MW', 0.0000010, 1, 0, 1);
INSERT INTO CSR.STD_MEASURE_CONVERSION (STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28129, 36, 'GW', 0.0000000010, 1, 0, 1);

@update_tail