-- Please update version.sql too -- this keeps clean builds in sync
define version=422
@update_header

-- SEQUENCE: DELEGATION_IND_COND_ID_SEQ 
--

CREATE SEQUENCE DELEGATION_IND_COND_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

 -- 
-- TABLE: DELEGATION_IND_COND 
--

CREATE TABLE DELEGATION_IND_COND(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEGATION_SID            NUMBER(10, 0)    NOT NULL,
    IND_SID                   NUMBER(10, 0)    NOT NULL,
    DELEGATION_IND_COND_ID    NUMBER(10, 0)    NOT NULL,
    EXPR                      VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK697 PRIMARY KEY (APP_SID, DELEGATION_SID, IND_SID, DELEGATION_IND_COND_ID)
)
;



-- 
-- TABLE: DELEGATION_IND_COND_ACTION 
--

CREATE TABLE DELEGATION_IND_COND_ACTION(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEGATION_SID            NUMBER(10, 0)    NOT NULL,
    IND_SID                   NUMBER(10, 0)    NOT NULL,
    DELEGATION_IND_COND_ID    NUMBER(10, 0)    NOT NULL,
    ACTION                    VARCHAR2(255)    NOT NULL,
    TAG                       VARCHAR2(255)    NOT NULL
)
;



-- 
-- TABLE: DELEGATION_IND_TAG 
--

CREATE TABLE DELEGATION_IND_TAG(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEGATION_SID    NUMBER(10, 0)    NOT NULL,
    IND_SID           NUMBER(10, 0)    NOT NULL,
    TAG               VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK702 PRIMARY KEY (APP_SID, DELEGATION_SID, IND_SID, TAG)
)
;




-- TABLE: DELEGATION_TAG 
--

CREATE TABLE DELEGATION_TAG(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEGATION_SID    NUMBER(10, 0)    NOT NULL,
    TAG               VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK_DELEGATION_TAG PRIMARY KEY (APP_SID, DELEGATION_SID, TAG)
)
;



-- 
-- INDEX: AK_DELEGATION_TAG 
--

-- XXX: back-port this to ER/Studio
CREATE UNIQUE INDEX AK_DELEGATION_TAG ON DELEGATION_TAG(APP_SID, DELEGATION_SID, LOWER(TAG))
;
-- 
-- TABLE: DELEGATION_IND_COND 
--

ALTER TABLE DELEGATION_IND_COND ADD CONSTRAINT RefDELEGATION_IND1472 
    FOREIGN KEY (APP_SID, DELEGATION_SID, IND_SID)
    REFERENCES DELEGATION_IND(APP_SID, DELEGATION_SID, IND_SID)
;


-- 
-- TABLE: DELEGATION_IND_COND_ACTION 
--

ALTER TABLE DELEGATION_IND_COND_ACTION ADD CONSTRAINT RefDELEGATION_IND_COND1473 
    FOREIGN KEY (APP_SID, DELEGATION_SID, IND_SID, DELEGATION_IND_COND_ID)
    REFERENCES DELEGATION_IND_COND(APP_SID, DELEGATION_SID, IND_SID, DELEGATION_IND_COND_ID)
;

ALTER TABLE DELEGATION_IND_COND_ACTION ADD CONSTRAINT RefDELEGATION_TAG1474 
    FOREIGN KEY (APP_SID, DELEGATION_SID, TAG)
    REFERENCES DELEGATION_TAG(APP_SID, DELEGATION_SID, TAG)
;


-- 
-- TABLE: DELEGATION_IND_TAG 
--

ALTER TABLE DELEGATION_IND_TAG ADD CONSTRAINT RefDELEGATION_IND1465 
    FOREIGN KEY (APP_SID, DELEGATION_SID, IND_SID)
    REFERENCES DELEGATION_IND(APP_SID, DELEGATION_SID, IND_SID)
;

-- XXX: back-port this to ER/Studio
ALTER TABLE DELEGATION_IND_TAG ADD CONSTRAINT RefDELEGATION_TAG1475 
    FOREIGN KEY (APP_SID, DELEGATION_SID, TAG)
    REFERENCES DELEGATION_TAG(APP_SID, DELEGATION_SID, TAG)
;


-- 
-- TABLE: DELEGATION_TAG 
--

ALTER TABLE DELEGATION_TAG ADD CONSTRAINT RefDELEGATION1476 
    FOREIGN KEY (APP_SID, DELEGATION_SID)
    REFERENCES DELEGATION(APP_SID, DELEGATION_SID)
;



@../delegation_pkg
@../delegation_body

@../deleg_admin_pkg
@../deleg_admin_body

grant execute on deleg_admin_pkg to web_user;

@update_tail
