define version=1990
@update_header

ALTER TABLE CSR.FLOW_STATE ADD (
    IND_SID					NUMBER(10),
    CONSTRAINT FK_FLOW_STATE_IND_SID FOREIGN KEY (APP_SID, IND_SID) REFERENCES CSR.IND (APP_SID, IND_SID)
);

ALTER TABLE CSR.FLOW ADD (
	AGGREGATE_IND_GROUP_ID	NUMBER(10),
	CONSTRAINT FK_FLOW_AGG_GRP_ID FOREIGN KEY (APP_SID, AGGREGATE_IND_GROUP_ID) REFERENCES CSR.AGGREGATE_IND_GROUP (APP_SID, AGGREGATE_IND_GROUP_ID)
);

ALTER TABLE CSRIMP.FLOW_STATE ADD (
    IND_SID					NUMBER(10)
);

ALTER TABLE CSRIMP.FLOW ADD (
	AGGREGATE_IND_GROUP_ID	NUMBER(10)
);

@..\flow_body
@..\schema_body
@..\csrimp\imp_body

@update_tail
