-- Please update version.sql too -- this keeps clean builds in sync
define version=3143
define minor_version=4
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE SURVEYS.QUESTION_CALC_EXPR_REF
(
	APP_SID						NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	QUESTION_ID					NUMBER(10, 0)	NOT NULL,
	QUESTION_VERSION			NUMBER(10, 0)	NOT NULL,
	QUESTION_DRAFT				NUMBER(1)		NOT NULL,
	REFERENCE_QUESTION_ID		NUMBER(10, 0)	NOT NULL,
	POS							NUMBER(10, 0)	DEFAULT 0 NOT NULL,
	DELETED						NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	CONSTRAINT CHK_QCEQ_DELETED_0_1 CHECK (DELETED IN (0,1)),
	CONSTRAINT PK_QUESTION_CALC_EXPR_REF_REF PRIMARY KEY (APP_SID, QUESTION_ID, QUESTION_VERSION, QUESTION_DRAFT, REFERENCE_QUESTION_ID, POS),
	CONSTRAINT FK_QUESTION_CALC_EXPR_Q_VERS FOREIGN KEY (APP_SID, QUESTION_ID, QUESTION_VERSION, QUESTION_DRAFT)
		REFERENCES SURVEYS.QUESTION_VERSION(APP_SID, QUESTION_ID, QUESTION_VERSION, QUESTION_DRAFT),
	CONSTRAINT FK_QUESTION_CALC_EXPR_REF_Q FOREIGN KEY (APP_SID, REFERENCE_QUESTION_ID)
		REFERENCES SURVEYS.QUESTION(APP_SID, QUESTION_ID)
);

-- Alter tables
ALTER TABLE SURVEYS.QUESTION_VERSION ADD
(
	CALCULATION_EXPRESSION		CLOB
);

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data
BEGIN
	INSERT INTO SURVEYS.QUESTION_TYPE(QUESTION_TYPE, LABEL) VALUES ('calculation', 'Calculation');
END;
/
-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
--@../surveys/question_library_pkg
--@../surveys/question_library_body

@update_tail
