-- Please update version.sql too -- this keeps clean builds in sync
define version=1772
@update_header

DROP TABLE CSR.EST_TRANSACTION_POLL CASCADE CONSTRAINTS;
DROP TABLE CSR.EST_TRANSACTION CASCADE CONSTRAINTS;

ALTER TABLE CSR.EST_BUILDING ADD (
	ADDRESS2			VARCHAR2(256),
	COUNTRY				VARCHAR2(256),
	PRIMARY_FUNCTION	VARCHAR2(1024),
	NOTES				VARCHAR2(4000),
	LAST_POLL_DTM		DATE
);

ALTER TABLE CSR.EST_BUILDING DROP COLUMN LAST_POLL_TRANSACTION_ID;

ALTER TABLE CSR.EST_BUILDING_METRIC_MAPPING DROP CONSTRAINT PK_EST_BUILDING_METRIC_MAPPING;

ALTER TABLE CSR.EST_BUILDING_METRIC_MAPPING ADD (
	UOM					VARCHAR2(256)	DEFAULT '<null>' NOT NULL,
	SIMULATED			NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	CHECK (SIMULATED IN (0,1)),
	CONSTRAINT PK_EST_BUILDING_METRIC_MAPPING PRIMARY KEY (APP_SID, EST_ACCOUNT_SID, METRIC_NAME, UOM)
);

ALTER TABLE CSR.EST_BUILDING_METRIC ADD (
	UOM					VARCHAR2(256)
);

ALTER TABLE CSR.EST_SPACE_ATTR_MAPPING DROP CONSTRAINT PK_EST_SPACE_ATTR_MAPPING;

ALTER TABLE CSR.EST_SPACE_ATTR_MAPPING ADD (
	UOM					VARCHAR2(256)	DEFAULT '<null>' NOT NULL,
	UPDATED				NUMBER(1) 		DEFAULT 0 NOT NULL,
	OLD_MAPPING			NUMBER(1) 		DEFAULT 1 NOT NULL,
	CHECK (UPDATED IN (0,1)),
	CHECK (OLD_MAPPING IN (0,1)),
	CONSTRAINT PK_EST_SPACE_ATTR_MAPPING PRIMARY KEY (APP_SID, EST_ACCOUNT_SID, ATTR_NAME, UOM)
);


ALTER TABLE CSR.EST_SPACE_ATTR DROP CONSTRAINT PK_EST_SPACE_ATTR;

ALTER TABLE CSR.EST_SPACE_ATTR MODIFY (
	EFFECTIVE_DATE		DATE	NOT NULL
);

ALTER TABLE CSR.EST_SPACE_ATTR ADD (
	UOM					VARCHAR2(256),
	CONSTRAINT PK_EST_SPACE_ATTR PRIMARY KEY (APP_SID, EST_ACCOUNT_SID, PM_CUSTOMER_ID, PM_BUILDING_ID, PM_SPACE_ID, ATTR_NAME, EFFECTIVE_DATE)
);


ALTER TABLE CSR.EST_ENERGY_METER ADD (
	LAST_POLL_DTM		DATE
);

ALTER TABLE CSR.EST_ENERGY_METER DROP COLUMN LAST_POLL_TRANSACTION_ID;


ALTER TABLE CSR.EST_ENERGY_CONV_MAPPING DROP CONSTRAINT FK_EST_ENERGYTYP_CONV_MAP;

ALTER TABLE CSR.EST_ENERGY_CONV_MAPPING DROP CONSTRAINT PK_EST_ENERGY_CONV_MAPPING;
ALTER TABLE CSR.EST_ENERGY_CONV_MAPPING ADD(
	OLD_MAPPING		NUMBER(1)	DEFAULT 1 NOT NULL,
	CHECK(OLD_MAPPING IN (0,1)),
    CONSTRAINT PK_EST_ENERGY_CONV_MAPPING PRIMARY KEY (APP_SID, EST_ACCOUNT_SID, ENERGY_TYPE, UOM)
);

ALTER TABLE CSR.EST_ENERGY_TYPE_MAPPING DROP CONSTRAINT PK_EST_ENERGY_TYPE_MAPPING;
ALTER TABLE CSR.EST_ENERGY_TYPE_MAPPING ADD (
	OLD_MAPPING		NUMBER(1)	DEFAULT 1 NOT NULL,
	CHECK(OLD_MAPPING IN (0,1)),
	CONSTRAINT PK_EST_ENERGY_TYPE_MAPPING PRIMARY KEY (APP_SID, EST_ACCOUNT_SID, ENERGY_TYPE)
);

ALTER TABLE CSR.EST_ENERGY_TYPE_MAPPING DROP COLUMN GENERATION_METHOD;
ALTER TABLE CSR.EST_ENERGY_CONV_MAPPING DROP COLUMN GENERATION_METHOD;

ALTER TABLE CSR.EST_ENERGY_CONV_MAPPING ADD CONSTRAINT FK_EST_ENERGYTYP_CONV_MAP 
    FOREIGN KEY (APP_SID, EST_ACCOUNT_SID, ENERGY_TYPE)
    REFERENCES CSR.EST_ENERGY_TYPE_MAPPING(APP_SID, EST_ACCOUNT_SID, ENERGY_TYPE)
;


ALTER TABLE CSR.EST_WATER_METER ADD (
	LAST_POLL_DTM		DATE
);

ALTER TABLE CSR.EST_WATER_METER DROP COLUMN LAST_POLL_TRANSACTION_ID;

ALTER TABLE CSR.EST_WATER_USE_MAPPING ADD(
	OLD_MAPPING		NUMBER(1)	DEFAULT 1 NOT NULL,
	CHECK(OLD_MAPPING IN (0,1))
);

ALTER TABLE CSR.EST_WATER_CONV_MAPPING ADD(
	OLD_MAPPING		NUMBER(1)	DEFAULT 1 NOT NULL,
	CHECK(OLD_MAPPING IN (0,1))
);

ALTER TABLE CSR.EST_CUSTOMER ADD (
	USER_NAME			VARCHAR(256)
);

DROP TYPE CSR.T_EST_ATTR_TABLE;

CREATE OR REPLACE TYPE CSR.T_EST_ATTR_ROW AS
  OBJECT ( 
	NAME		VARCHAR2(256),
	VAL			NUMBER(24, 10),
	STR			VARCHAR2(1024),
	DTM			DATE,
	UOM			VARCHAR2(256),
	POS			NUMBER(10)
  );
/

CREATE OR REPLACE TYPE CSR.T_EST_ATTR_TABLE AS 
  TABLE OF CSR.T_EST_ATTR_ROW;
/

@../energy_star_account_pkg
@../energy_star_pkg

@../energy_star_account_body
@../energy_star_body

@update_tail
