-- Please update version.sql too -- this keeps clean builds in sync
define version=3387
define minor_version=5
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CSR.MODULE_HISTORY(
	APP_SID				NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	MODULE_ID			NUMBER(10, 0)	NOT NULL,
	ENABLED_DTM			DATE,
	LAST_ENABLED_DTM	DATE,
	DISABLED_DTM		DATE,
	CONSTRAINT PK_MODULE_HSTORY_MODULE_ID PRIMARY KEY (APP_SID, MODULE_ID)
)
;

ALTER TABLE CSR.MODULE_HISTORY ADD CONSTRAINT FK_MODULE_HISTORY_ID
	FOREIGN KEY (MODULE_ID)
	REFERENCES CSR.MODULE(MODULE_ID)
;

CREATE INDEX CSR.IX_MODULE_HISTORY_MODULE_ID ON CSR.MODULE_HISTORY (MODULE_ID);

CREATE TABLE CSRIMP.MODULE_HISTORY (
	CSRIMP_SESSION_ID			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MODULE_ID					NUMBER(10, 0)	NOT NULL,
	ENABLED_DTM					DATE,
	LAST_ENABLED_DTM			DATE,
	DISABLED_DTM				DATE,
	CONSTRAINT PK_MODULE_HSTORY_MODULE_ID PRIMARY KEY (CSRIMP_SESSION_ID, MODULE_ID),
	CONSTRAINT FK_MODULE_HISTORY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);



DROP TABLE CSRIMP.CREDENTIAL_MANAGEMENT;
CREATE TABLE CSRIMP.CREDENTIAL_MANAGEMENT (
	CSRIMP_SESSION_ID	NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	CREDENTIAL_ID		NUMBER(10, 0)		NOT NULL,
	LABEL				VARCHAR2(255)		NOT NULL,
	AUTH_TYPE_ID		NUMBER(10, 0)		NOT NULL,
	AUTH_SCOPE_ID		NUMBER(10, 0)		NOT NULL,
	CREATED_DTM			DATE				NOT NULL,
	UPDATED_DTM			DATE				NOT NULL,
	LOGIN_HINT			VARCHAR2(500),
	CONSTRAINT PK_CREDENTIAL_MANAGEMENT PRIMARY KEY (CSRIMP_SESSION_ID, CREDENTIAL_ID),
	CONSTRAINT UK_CREDENTIAL_MANAGEMENT_LABEL UNIQUE (CSRIMP_SESSION_ID, LABEL),
	CONSTRAINT FK_CREDENTIAL_MANAGEMENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

DROP TABLE CSRIMP.INTEGRATION_QUESTION_ANSWER;
CREATE TABLE CSRIMP.INTEGRATION_QUESTION_ANSWER(
	CSRIMP_SESSION_ID	NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PARENT_REF			VARCHAR2(255)	NOT NULL,
	QUESTION_REF		VARCHAR2(255)	NOT NULL,
	INTERNAL_AUDIT_SID	NUMBER(10, 0),
	SECTION_NAME		VARCHAR2(1024),
	SECTION_CODE		VARCHAR2(1024),
	SECTION_SCORE		NUMBER(10, 5),
	SUBSECTION_NAME		VARCHAR2(1024),
	SUBSECTION_CODE		VARCHAR2(1024),
	QUESTION_TEXT		VARCHAR2(4000),
	RATING				VARCHAR2(1024),
	CONCLUSION			CLOB,
	ANSWER				CLOB,
	DATA_POINTS			CLOB,
	LAST_UPDATED		DATE,
	ID					NUMBER(10, 0)	NOT NULL,
	CONSTRAINT PK_INTEGRATION_QUESTION_ANSWER PRIMARY KEY (CSRIMP_SESSION_ID, PARENT_REF, QUESTION_REF),
	CONSTRAINT UK_INTEGRATION_QUESTION_ANSWER_ID UNIQUE (CSRIMP_SESSION_ID, ID),
	CONSTRAINT FK_INTEGRATION_QUESTION_ANSWER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

DROP TABLE CSRIMP.REGION_CERTIFICATE;
CREATE TABLE CSRIMP.REGION_CERTIFICATE (
	CSRIMP_SESSION_ID			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_CERTIFICATE_ID		NUMBER(24,0) NOT NULL,
	REGION_SID					NUMBER(10,0) NOT NULL,
	CERTIFICATION_ID			NUMBER(10,0) NOT NULL,
	CERTIFICATION_LEVEL_ID		NUMBER(10,0),
	CERTIFICATE_NUMBER			NUMBER(10,0),
	FLOOR_AREA					NUMBER(10,2) NOT NULL,
	ISSUED_DTM					DATE,
	EXPIRY_DTM					DATE,
	EXTERNAL_CERTIFICATE_ID		NUMBER(10,0),
	DELETED						NUMBER(1, 0) NOT NULL,
	CONSTRAINT PK_REGION_CERTS PRIMARY KEY (CSRIMP_SESSION_ID, REGION_CERTIFICATE_ID),
	CONSTRAINT UK_REG_CERT_EXT_ID UNIQUE (CSRIMP_SESSION_ID, REGION_SID, CERTIFICATION_ID, CERTIFICATION_LEVEL_ID, EXTERNAL_CERTIFICATE_ID),
	CONSTRAINT CK_REGION_CERT_DELETED CHECK (DELETED in (0,1)),
	CONSTRAINT FK_REGION_CERTIFICATE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

DROP TABLE CSRIMP.REGION_ENERGY_RATING;
CREATE TABLE CSRIMP.REGION_ENERGY_RATING (
	CSRIMP_SESSION_ID			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID					NUMBER(10,0) NOT NULL,
	ENERGY_RATING_ID			NUMBER(10,0) NOT NULL,
	FLOOR_AREA					NUMBER(10,2) NOT NULL,
	ISSUED_DTM					DATE NOT NULL,
	EXPIRY_DTM					DATE,
	CONSTRAINT PK_REGION_ENERGY_RAT PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID),
	CONSTRAINT CHK_REGION_ENERGY_RAT_EXP_AFTER_ISS CHECK ((ISSUED_DTM IS NULL OR EXPIRY_DTM IS NULL) OR (ISSUED_DTM IS NOT NULL AND EXPIRY_DTM IS NOT NULL AND ISSUED_DTM < EXPIRY_DTM)),
	CONSTRAINT FK_REGION_ENERGY_RATING_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);



-- Alter tables


-- *** Grants ***
CREATE OR REPLACE PACKAGE csr.landing_page_pkg AS
    PROCEDURE DUMMY;
END;
/
CREATE OR REPLACE PACKAGE BODY csr.landing_page_pkg AS
    PROCEDURE DUMMY
AS
    BEGIN
        NULL;
    END;
END;
/

grant execute on csr.landing_page_pkg to web_user;

grant select,insert, update on csr.module_history to csrimp;
grant select,insert,update,delete on csrimp.module_history to tool_user;

grant select,insert,update,delete on CSRIMP.CREDENTIAL_MANAGEMENT to tool_user;
grant select,insert,update,delete on CSRIMP.INTEGRATION_QUESTION_ANSWER to tool_user;
grant select,insert,update,delete on CSRIMP.REGION_CERTIFICATE to tool_user;
grant select,insert,update,delete on CSRIMP.REGION_ENERGY_RATING to tool_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data
INSERT INTO csr.module (module_id, module_name, enable_sp, description)
VALUES (122, 'Landing Pages', 'EnableLandingPages', 'Enable Landing Pages');

INSERT INTO CSR.AUDIT_TYPE (AUDIT_TYPE_ID,LABEL,AUDIT_TYPE_GROUP_ID) VALUES (306,'Landing Page',6);

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../csr_data_pkg
@../enable_pkg
@../landing_page_pkg
@../schema_pkg
@../csrimp/imp_pkg

@../csr_app_body
@../enable_body
@../landing_page_body
@../schema_body
@../csrimp/imp_body

@update_tail
