-- Please update version.sql too -- this keeps clean builds in sync
define version=3178
define minor_version=4
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CSR.METER_PROCESSING_JOB (
	APP_SID				NUMBER(10)		DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	CONTAINER_ID		VARCHAR2(256)	NOT NULL,
	JOB_ID				VARCHAR2(256)	NOT NULL,
	JOB_DTM				DATE			DEFAULT SYSDATE NOT NULL,
	FETCH_COUNT			NUMBER(10)		DEFAULT 0 NOT NULL,
	EXPIRED_COUNT		NUMBER(10)		DEFAULT 0 NOT NULL,
	LAST_FETCH_DTM		DATE			NULL,
	HIDE_UNTIL			DATE			NULL,
	LOCAL_STATUS		VARCHAR2(256)	NOT NULL,
	LOCAL_RESULT_PATH	VARCHAR2(2048)	NULL,
	REMOTE_STATUS		VARCHAR2(256)	NULL,
	UPLOAD_URI			VARCHAR2(2048)	NULL,
	RESULT_URI			VARCHAR2(2048)	NULL,
	REMOTE_RESULT_PATH	VARCHAR2(2048)	NULL,
	CONSTRAINT PK_METER_PROCESSING_JOB PRIMARY KEY (APP_SID, CONTAINER_ID, JOB_ID),
	CONSTRAINT FK_CUSTOMER_METER_PROC_JOB
		FOREIGN KEY (APP_SID)
		REFERENCES CSR.CUSTOMER (APP_SID)
);

CREATE INDEX CSR.IX_CUSTOMER_METER_PROC_JOB ON CSR.METER_PROCESSING_JOB (APP_SID);

-- EXTERNAL TABLES
-- FOLDERS NEED TO BE MANAGED SOMEHOW
CREATE OR REPLACE DIRECTORY DIR_SCRIPTS AS '/meterdata';
CREATE OR REPLACE DIRECTORY DIR_EXT_METER_DATA AS '/meterdata';

-- Put the path to search in DIR_EXT_METER_DATA:path.txt and the preprocessor 
-- script will concatenate all *.csv files in that folder and it's sub folders
CREATE TABLE CSR.EXT_METER_DATA (
	CONTAINER_ID	VARCHAR2(1024),
	JOB_ID			VARCHAR2(1024),
	SERIAL_ID		VARCHAR2(1024),
	BUCKET_NAME		VARCHAR2(256),
	START_DTM		DATE,
	VAL				NUMBER(24, 10)
)
ORGANIZATION EXTERNAL 
(
	TYPE ORACLE_LOADER 
	DEFAULT DIRECTORY DIR_EXT_METER_DATA 
	ACCESS PARAMETERS 
	( 
		RECORDS DELIMITED BY NEWLINE
		PREPROCESSOR DIR_SCRIPTS:'concatAllFiles.sh'
		FIELDS TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
		MISSING FIELD VALUES ARE NULL 
		(
			CONTAINER_ID,
			JOB_ID,
			SERIAL_ID,
			BUCKET_NAME,
			START_DTM DATE 'YYYY-MM-DD HH24:MI:SS',
			VAL
		) 
	)
	LOCATION('path.txt') 
)
REJECT LIMIT UNLIMITED;

-- Alter tables
ALTER TABLE CSR.METERING_OPTIONS ADD (
	PROC_USE_SERVICE		NUMBER(1)		DEFAULT 0 NOT NULL,
	PROC_API_BASE_URI		VARCHAR2(1024),
	PROC_LOCAL_PATH			VARCHAR2(1024),
	PROC_KICK_TIMEOUT		NUMBER(10),
	CONSTRAINT CK_PROC_USE_SERVICE CHECK (PROC_USE_SERVICE IN (0, 1)),
	CONSTRAINT CK_PROC_OPRIONS_IN_USE CHECK (
		PROC_USE_SERVICE = 0 OR (
			PROC_API_BASE_URI IS NOT NULL AND 
			PROC_LOCAL_PATH IS NOT NULL AND 
			PROC_KICK_TIMEOUT IS NOT NULL
		)
	)
);

ALTER TABLE CSRIMP.METERING_OPTIONS ADD (
	PROC_USE_SERVICE		NUMBER(1)		NOT NULL,
	PROC_API_BASE_URI		VARCHAR2(1024),
	PROC_LOCAL_PATH			VARCHAR2(1024),
	PROC_KICK_TIMEOUT		NUMBER(10),
	CONSTRAINT CK_PROC_USE_SERVICE CHECK (PROC_USE_SERVICE IN (0, 1)),
	CONSTRAINT CK_PROC_OPRIONS_IN_USE CHECK (
		PROC_USE_SERVICE = 0 OR (
			PROC_API_BASE_URI IS NOT NULL AND 
			PROC_LOCAL_PATH IS NOT NULL AND 
			PROC_KICK_TIMEOUT IS NOT NULL
		)
	)
);

-- *** Grants ***
GRANT READ, EXECUTE ON DIRECTORY DIR_SCRIPTS TO csr;
GRANT READ, EXECUTE ON DIRECTORY DIR_SCRIPTS TO web_user;
GRANT READ, WRITE ON DIRECTORY DIR_EXT_METER_DATA TO csr;
GRANT READ, WRITE ON DIRECTORY DIR_EXT_METER_DATA TO web_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data
BEGIN
	dbms_scheduler.create_job (
		job_name		=> 'CSR.EXPIRE_REMOTE_JOBS',
		job_type		=> 'PLSQL_BLOCK',
		job_action		=> 'csr.customer_pkg.ExpireJobs;',
		job_class		=> 'low_priority_job',
		start_date		=> to_timestamp_tz('2018/01/01 00:00 +00:00','YYYY/MM/DD HH24:MI TZH:TZM'),
		repeat_interval	=> 'FREQ=MINUTELY;INTERVAL=10',
		enabled			=> TRUE,
		auto_drop		=> FALSE,
		comments		=> 'Roll-back or expire meter processing jobs that are no longer locked but in a status that means they were processing'
	);
END;
/

-- ** New package grants **
CREATE OR REPLACE PACKAGE csr.meter_processing_job_pkg
IS
BEGIN
END;
/
GRANT execute ON csr.meter_processing_job_pkg TO web_user;

-- *** Conditional Packages ***

-- *** Packages ***
@../meter_processing_job_pkg
@../meter_pkg

@../meter_processing_job_body
@../meter_body
@../schema_body
@../csrimp/imp_body

@update_tail
