-- Please update version.sql too -- this keeps clean builds in sync
define version=396
@update_header

ALTER TABLE TPL_REPORT ADD (
    INTERVAL          VARCHAR2(1)       DEFAULT 'y' NOT NULL,
    CONSTRAINT CHK_TPL_REPORT_INTERVAL CHECK (INTERVAL IN ('m','q','h','y'))
);

ALTER TABLE TPL_REPORT_TAG_DATAVIEW ADD (
    MONTH_OFFSET      NUMBER(10, 0)    DEFAULT -12 NOT NULL,
    MONTH_DURATION    NUMBER(10, 0)    DEFAULT 12 NOT NULL
);


ALTER TABLE tpl_report_tag_eval DROP COLUMN COND;

ALTER TABLE tpl_report_tag_eval ADD (
	ALL_MUST_BE_TRUE  NUMBER(1) DEFAULT 0 NOT NULL
); 

begin
	for r in (
		select table_name 
		  from user_tables 
		 where table_name in ('TPL_REPORT_TAG_EVAL_COND')
	)
	loop
		execute immediate 'drop table '||r.table_name||' cascade constraints';
	end loop;
end;
/
 
 
CREATE TABLE TPL_REPORT_TAG_EVAL_COND(
    APP_SID           NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    TPL_REPORT_SID    NUMBER(10, 0)     NOT NULL,
    TAG               VARCHAR2(255)     NOT NULL,
    LEFT_IND_SID      NUMBER(10, 0)     NOT NULL,
    OPERATOR          VARCHAR2(2)       NOT NULL,
    RIGHT_VALUE       NUMBER(24, 10),
    RIGHT_IND_SID     NUMBER(10, 0),
    CONSTRAINT CK_RPT_TG_EVL_COND_COMP_NN CHECK ((RIGHT_VALUE IS NOT NULL AND RIGHT_IND_SID IS NULL) OR (RIGHT_VALUE IS NULL AND RIGHT_IND_SID IS NOT NULL)),
    CONSTRAINT CK_RPT_TG_EVL_OP CHECK (OPERATOR IN ('>','<','<=','>=','=','!='))
 )
 ;
 
ALTER TABLE TPL_REPORT_TAG_EVAL_COND ADD CONSTRAINT RefIND1258 
FOREIGN KEY (APP_SID, LEFT_IND_SID)
REFERENCES CSR.IND(APP_SID, IND_SID);

ALTER TABLE TPL_REPORT_TAG_EVAL_COND ADD CONSTRAINT RefIND1259 
FOREIGN KEY (APP_SID, RIGHT_IND_SID)
REFERENCES CSR.IND(APP_SID, IND_SID);

ALTER TABLE TPL_REPORT_TAG_EVAL_COND ADD CONSTRAINT RefTPL_REPORT_TAG_EVAL1260 
FOREIGN KEY (APP_SID, TPL_REPORT_SID, TAG)
REFERENCES TPL_REPORT_TAG_EVAL(APP_SID, TPL_REPORT_SID, TAG);

@..\templated_report_pkg
@..\templated_report_body

 
@update_tail
