-- Please update version.sql too -- this keeps clean builds in sync
define version=3057
define minor_version=8
@update_header

-- *** DDL ***
-- Create tables

/* PRODUCT HEADER */

DROP TABLE CHAIN.PRODUCT_HEADER_PRODUCT_TYPE;
DROP TABLE CHAIN.PRODUCT_HEADER_COMPANY_TYPE;
DROP TABLE CHAIN.PRODUCT_HEADER;

CREATE TABLE CHAIN.PRODUCT_HEADER(
	APP_SID					NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	PRODUCT_HEADER_ID		NUMBER(10, 0) NOT NULL,
	PLUGIN_ID				NUMBER(10, 0) NOT NULL,
	PLUGIN_TYPE_ID			NUMBER(10, 0) NOT NULL,
	POS						NUMBER(10, 0) NOT NULL,
	PRODUCT_COMPANY_TYPE_ID	NUMBER(10, 0) NOT NULL,
	USER_COMPANY_TYPE_ID	NUMBER(10, 0) NOT NULL,
	VIEWING_OWN_PRODUCT		NUMBER(1) NOT NULL,
	VIEWING_AS_SUPPLIER		NUMBER(1) NOT NULL,
	PRODUCT_COL_SID			NUMBER(10, 0),
	USER_COMPANY_COL_SID	NUMBER(10, 0),
	CONSTRAINT CHK_PRD_HEAD_VIEW_OWN_CMP_1_0 CHECK (VIEWING_OWN_PRODUCT IN (1, 0)),
	CONSTRAINT CHK_PRD_HEAD_VIEW_AS_SUPP_1_0 CHECK (VIEWING_AS_SUPPLIER IN (1, 0)),
	CONSTRAINT PRODUCT_HEADER_PK PRIMARY KEY (APP_SID, PRODUCT_HEADER_ID)
);

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PROD_HEADER_PROD_COMP_TYPE
    FOREIGN KEY (APP_SID, PRODUCT_COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PROD_HEADER_USER_COMP_TYPE
    FOREIGN KEY (APP_SID, USER_COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

CREATE TABLE CHAIN.PRODUCT_HEADER_PRODUCT_TYPE (
	APP_SID					NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	PRODUCT_HEADER_ID		NUMBER(10, 0) NOT NULL,
	PRODUCT_TYPE_ID			NUMBER(10, 0) NOT NULL,
	CONSTRAINT PK_PRODUCT_HEADER_PRODUCT_TYPE PRIMARY KEY (APP_SID, PRODUCT_HEADER_ID, PRODUCT_TYPE_ID)
);

ALTER TABLE CHAIN.PRODUCT_HEADER_PRODUCT_TYPE ADD CONSTRAINT FK_PRODUCT_HEADER_PROD_TYPE_PH
    FOREIGN KEY (APP_SID, PRODUCT_HEADER_ID)
    REFERENCES CHAIN.PRODUCT_HEADER(APP_SID, PRODUCT_HEADER_ID)
;

ALTER TABLE CHAIN.PRODUCT_HEADER_PRODUCT_TYPE ADD CONSTRAINT FK_PRODUCT_HEADER_PROD_TYPE_PT
    FOREIGN KEY (APP_SID, PRODUCT_TYPE_ID)
    REFERENCES CHAIN.PRODUCT_TYPE(APP_SID, PRODUCT_TYPE_ID)
;

/* PROUCT TAB */

DROP TABLE CHAIN.PRODUCT_TAB_PRODUCT_TYPE;
DROP TABLE CHAIN.PRODUCT_TAB_COMPANY_TYPE;
DROP TABLE CHAIN.PRODUCT_TAB;

CREATE TABLE CHAIN.PRODUCT_TAB(
	APP_SID					NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	PRODUCT_TAB_ID			NUMBER(10, 0) NOT NULL,
	PLUGIN_ID				NUMBER(10, 0) NOT NULL,
	PLUGIN_TYPE_ID			NUMBER(10, 0) NOT NULL,
	POS						NUMBER(10, 0) NOT NULL,
	LABEL					VARCHAR2(254) NOT NULL,
	PRODUCT_COMPANY_TYPE_ID	NUMBER(10, 0) NOT NULL,
	USER_COMPANY_TYPE_ID	NUMBER(10, 0) NOT NULL,
	VIEWING_OWN_PRODUCT		NUMBER(1) NOT NULL,
	VIEWING_AS_SUPPLIER		NUMBER(1) NOT NULL,
	PRODUCT_COL_SID			NUMBER(10, 0),
	USER_COMPANY_COL_SID	NUMBER(10, 0),
	CONSTRAINT CHK_PRD_TAB_VIEW_OWN_CMP_1_0 CHECK (VIEWING_OWN_PRODUCT IN (1, 0)),
	CONSTRAINT CHK_PRD_TAB_VIEW_AS_SUPP_1_0 CHECK (VIEWING_AS_SUPPLIER IN (1, 0)),
	CONSTRAINT PRODUCT_TAB_PK PRIMARY KEY (APP_SID, PRODUCT_TAB_ID)
);

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PROD_TAB_PROD_COMP_TYPE
    FOREIGN KEY (APP_SID, PRODUCT_COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PROD_TAB_USER_COMP_TYPE
    FOREIGN KEY (APP_SID, USER_COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

CREATE TABLE CHAIN.PRODUCT_TAB_PRODUCT_TYPE (
	APP_SID					NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	PRODUCT_TAB_ID			NUMBER(10, 0) NOT NULL,
	PRODUCT_TYPE_ID			NUMBER(10, 0) NOT NULL,
	CONSTRAINT PK_PRODUCT_TAB_PRODUCT_TYPE PRIMARY KEY (APP_SID, PRODUCT_TAB_ID, PRODUCT_TYPE_ID)
);

ALTER TABLE CHAIN.PRODUCT_TAB_PRODUCT_TYPE ADD CONSTRAINT FK_PRODUCT_TAB_PROD_TYPE_PH
    FOREIGN KEY (APP_SID, PRODUCT_TAB_ID)
    REFERENCES CHAIN.PRODUCT_TAB(APP_SID, PRODUCT_TAB_ID)
;

ALTER TABLE CHAIN.PRODUCT_TAB_PRODUCT_TYPE ADD CONSTRAINT FK_PRODUCT_TAB_PROD_TYPE_PT
    FOREIGN KEY (APP_SID, PRODUCT_TYPE_ID)
    REFERENCES CHAIN.PRODUCT_TYPE(APP_SID, PRODUCT_TYPE_ID)
;

/* PRODUCT SUPPLIER TAB */

DROP TABLE CHAIN.PROD_SUPP_TAB_PRODUCT_TYPE;
DROP TABLE CHAIN.PROD_SUPP_TAB_COMPANY_TYPE;
DROP TABLE CHAIN.PRODUCT_SUPPLIER_TAB;

CREATE TABLE CHAIN.PRODUCT_SUPPLIER_TAB(
	APP_SID					NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	PRODUCT_SUPPLIER_TAB_ID	NUMBER(10, 0) NOT NULL,
	PLUGIN_ID				NUMBER(10, 0) NOT NULL,
	PLUGIN_TYPE_ID			NUMBER(10, 0) NOT NULL,
	POS						NUMBER(10, 0) NOT NULL,
	LABEL					VARCHAR2(254) NOT NULL,
	PRODUCT_COMPANY_TYPE_ID	NUMBER(10, 0) NOT NULL,
	USER_COMPANY_TYPE_ID	NUMBER(10, 0) NOT NULL,
	VIEWING_OWN_PRODUCT		NUMBER(1) NOT NULL,
	VIEWING_AS_SUPPLIER		NUMBER(1) NOT NULL,
	CONSTRAINT CK_PRD_SUP_TAB_VW_OWN_CMP_1_0 CHECK (VIEWING_OWN_PRODUCT IN (1, 0)),
	CONSTRAINT CK_PRD_SUP_TAB_VW_AS_SUPP_1_0 CHECK (VIEWING_AS_SUPPLIER IN (1, 0)),
	CONSTRAINT PRODUCT_SUPPLIER_TAB_PK PRIMARY KEY (APP_SID, PRODUCT_SUPPLIER_TAB_ID)
);

ALTER TABLE CHAIN.PRODUCT_SUPPLIER_TAB ADD CONSTRAINT FK_PROD_SUP_TAB_PROD_COMP_TYPE
    FOREIGN KEY (APP_SID, PRODUCT_COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

ALTER TABLE CHAIN.PRODUCT_SUPPLIER_TAB ADD CONSTRAINT FK_PROD_SUP_TAB_USER_COMP_TYPE
    FOREIGN KEY (APP_SID, USER_COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

CREATE TABLE CHAIN.PROD_SUPP_TAB_PRODUCT_TYPE (
	APP_SID						NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	PRODUCT_SUPPLIER_TAB_ID     NUMBER(10, 0)     NOT NULL,
	PRODUCT_TYPE_ID				NUMBER(10, 0)     NOT NULL,
	CONSTRAINT PK_PROD_SUPP_TAB_PRODUCT_TYPE PRIMARY KEY (APP_SID, PRODUCT_SUPPLIER_TAB_ID, PRODUCT_TYPE_ID)
);

ALTER TABLE CHAIN.PROD_SUPP_TAB_PRODUCT_TYPE ADD CONSTRAINT FK_PROD_SUPP_TAB_PROD_TYPE_PH
    FOREIGN KEY (APP_SID, PRODUCT_SUPPLIER_TAB_ID)
    REFERENCES CHAIN.PRODUCT_SUPPLIER_TAB(APP_SID, PRODUCT_SUPPLIER_TAB_ID)
;

ALTER TABLE CHAIN.PROD_SUPP_TAB_PRODUCT_TYPE ADD CONSTRAINT FK_PROD_SUPP_TAB_PROD_TYPE_PT
    FOREIGN KEY (APP_SID, PRODUCT_TYPE_ID)
    REFERENCES CHAIN.PRODUCT_TYPE(APP_SID, PRODUCT_TYPE_ID)
;

/* FK INDEXES */

create index chain.ix_prod_head_prod_col_sid on chain.product_header (app_sid, product_col_sid);
create index chain.ix_prod_head_user_comp_col_sid on chain.product_header (app_sid, user_company_col_sid);
create index chain.ix_prod_head_prod_comp_type_id on chain.product_header (app_sid, product_company_type_id);
create index chain.ix_prod_head_plugin_id on chain.product_header (plugin_id);
create index chain.ix_prod_head_plugin_type_id on chain.product_header (plugin_type_id);
create index chain.ix_prod_head_user_comp_type_id on chain.product_header (app_sid, user_company_type_id);
create index chain.ix_prod_head_prod_type_id on chain.product_header_product_type (app_sid, product_type_id);
create index chain.ix_prod_supp_plugin_id on chain.product_supplier_tab (plugin_id);
create index chain.ix_prod_supp_prod_comp_type_id on chain.product_supplier_tab (app_sid, product_company_type_id);
create index chain.ix_prod_supp_plugin_type_id on chain.product_supplier_tab (plugin_type_id);
create index chain.ix_prod_supp_user_comp_type_id on chain.product_supplier_tab (app_sid, user_company_type_id);
create index chain.ix_prod_tab_plugin_type_id on chain.product_tab (plugin_type_id);
create index chain.ix_prod_tab_user_comp_col_sid on chain.product_tab (app_sid, user_company_col_sid);
create index chain.ix_prod_tab_user_comp_type_id on chain.product_tab (app_sid, user_company_type_id);
create index chain.ix_prod_tab_prod_comp_type_id on chain.product_tab (app_sid, product_company_type_id);
create index chain.ix_prod_tab_prod_col_sid on chain.product_tab (app_sid, product_col_sid);
create index chain.ix_prod_tab_plugin_id on chain.product_tab (plugin_id);
create index chain.ix_prod_tab_prod_prod_type_ on chain.product_tab_product_type (app_sid, product_type_id);
create index chain.ix_prod_supp_tab_prod_type_id on chain.prod_supp_tab_product_type (app_sid, product_type_id);

/* CSRIMP */

DROP TABLE CSRIMP.CHAIN_PRODUCT_HEADER;
DROP TABLE CSRIMP.CHAIN_PRODUCT_TAB;

CREATE TABLE CSRIMP.MAP_CHAIN_PRODUCT_SUPPLIER_TAB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_PRODUCT_SUPPLIER_TAB_ID NUMBER(10) NOT NULL,
	NEW_PRODUCT_SUPPLIER_TAB_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_PROD_SUPP_TAB PRIMARY KEY (CSRIMP_SESSION_ID, OLD_PRODUCT_SUPPLIER_TAB_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_PROD_SUPP_TAB UNIQUE (CSRIMP_SESSION_ID, NEW_PRODUCT_SUPPLIER_TAB_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_PROD_SUPP_TAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUCT_HEADER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_HEADER_ID NUMBER(10,0) NOT NULL,
	PLUGIN_ID NUMBER(10,0) NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	POS NUMBER(10,0) NOT NULL,
	PRODUCT_COL_SID NUMBER(10,0),
	PRODUCT_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	USER_COMPANY_COL_SID NUMBER(10,0),
	USER_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	VIEWING_AS_SUPPLIER NUMBER(1,0) NOT NULL,
	VIEWING_OWN_PRODUCT NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PRODUCT_HEADER PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_HEADER_ID),
	CONSTRAINT FK_CHAIN_PRODUCT_HEADER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRO_HEAD_PRO_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_HEADER_ID NUMBER(10,0) NOT NULL,
	PRODUCT_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PRO_HEAD_PRO_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_HEADER_ID, PRODUCT_TYPE_ID),
	CONSTRAINT FK_CHAIN_PRO_HEAD_PRO_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUCT_TAB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_TAB_ID NUMBER(10,0) NOT NULL,
	LABEL VARCHAR2(254) NOT NULL,
	PLUGIN_ID NUMBER(10,0) NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	POS NUMBER(10,0) NOT NULL,
	PRODUCT_COL_SID NUMBER(10,0),
	PRODUCT_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	USER_COMPANY_COL_SID NUMBER(10,0),
	USER_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	VIEWING_AS_SUPPLIER NUMBER(1,0) NOT NULL,
	VIEWING_OWN_PRODUCT NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PRODUCT_TAB PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_TAB_ID),
	CONSTRAINT FK_CHAIN_PRODUCT_TAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PROD_TAB_PROD_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_TAB_ID NUMBER(10,0) NOT NULL,
	PRODUCT_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PROD_TAB_PROD_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_TAB_ID, PRODUCT_TYPE_ID),
	CONSTRAINT FK_CHAIN_PROD_TAB_PROD_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUC_SUPPLIE_TAB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_SUPPLIER_TAB_ID NUMBER(10,0) NOT NULL,
	LABEL VARCHAR2(254) NOT NULL,
	PLUGIN_ID NUMBER(10,0) NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	POS NUMBER(10,0) NOT NULL,
	PRODUCT_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	USER_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	VIEWING_AS_SUPPLIER NUMBER(1,0) NOT NULL,
	VIEWING_OWN_PRODUCT NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PRODUC_SUPPLIE_TAB PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_SUPPLIER_TAB_ID),
	CONSTRAINT FK_CHAIN_PRODUC_SUPPLIE_TAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PR_SUP_TAB_PR_TYP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_SUPPLIER_TAB_ID NUMBER(10,0) NOT NULL,
	PRODUCT_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PR_SUP_TAB_PR_TYP PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_SUPPLIER_TAB_ID, PRODUCT_TYPE_ID),
	CONSTRAINT FK_CHAIN_PR_SUP_TAB_PR_TYP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Alter tables

-- *** Grants ***
grant select, insert, update, delete on csrimp.chain_product_header to tool_user;
grant select, insert, update, delete on csrimp.chain_pro_head_pro_type to tool_user;
grant select, insert, update, delete on csrimp.chain_product_tab to tool_user;
grant select, insert, update, delete on csrimp.chain_prod_tab_prod_type to tool_user;
grant select, insert, update, delete on csrimp.chain_produc_supplie_tab to tool_user;
grant select, insert, update, delete on csrimp.chain_pr_sup_tab_pr_typ to tool_user;

grant select, insert, update on chain.product_header to csrimp;
grant select, insert, update on chain.product_header_product_type to csrimp;
grant select, insert, update on chain.product_tab to csrimp;
grant select, insert, update on chain.product_tab_product_type to csrimp;
grant select, insert, update on chain.product_supplier_tab to csrimp;
grant select, insert, update on chain.prod_supp_tab_product_type to csrimp;

grant select on chain.product_supplier_tab_id_seq to csrimp;

grant select, insert, update on chain.product_header to CSR;
grant select, insert, update on chain.product_header_product_type to CSR;
grant select, insert, update on chain.product_tab to CSR;
grant select, insert, update on chain.product_tab_product_type to CSR;
grant select, insert, update on chain.product_supplier_tab to CSR;
grant select, insert, update on chain.prod_supp_tab_product_type to CSR;

-- ** Cross schema constraints ***

/* PROUCT HEADER */

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PR_HD_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID);

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PR_HD_PLUGIN_TYPE_ID_PLGN_T
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID);

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PRODUCT_HDR_PRODUCT_COL
	FOREIGN KEY (APP_SID, PRODUCT_COL_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID);

ALTER TABLE CHAIN.PRODUCT_HEADER ADD CONSTRAINT FK_PRODUCT_HDR_USER_COMP_COL
	FOREIGN KEY (APP_SID, USER_COMPANY_COL_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID);

/* PRODUCT TAB */

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PR_TB_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID);

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PR_TB_PLUGIN_TYPE_ID_PLGN_T
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID);

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PRODUCT_TAB_PRODUCT_COL
	FOREIGN KEY (APP_SID, product_col_sid)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID);

ALTER TABLE CHAIN.PRODUCT_TAB ADD CONSTRAINT FK_PRODUCT_TAB_USER_COMP_COL
	FOREIGN KEY (APP_SID, USER_COMPANY_COL_SID)
	REFERENCES CMS.TAB_COLUMN(APP_SID, COLUMN_SID);

/* PRODUCT SUPPLIER TAB */

ALTER TABLE CHAIN.PRODUCT_SUPPLIER_TAB ADD CONSTRAINT FK_PRSTB_PLUGIN_ID_PLUGIN
    FOREIGN KEY (PLUGIN_ID)
    REFERENCES CSR.PLUGIN(PLUGIN_ID);

ALTER TABLE CHAIN.PRODUCT_SUPPLIER_TAB ADD CONSTRAINT FK_PRSTB_PLUGIN_TYPE_ID_PLGN_T
    FOREIGN KEY (PLUGIN_TYPE_ID)
    REFERENCES CSR.PLUGIN_TYPE(PLUGIN_TYPE_ID);

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../chain/plugin_pkg
@../schema_pkg

@../chain/plugin_body
@../schema_body
@../csrimp/imp_body

@update_tail
