-- Please update version.sql too -- this keeps clean builds in sync
define version=3143
define minor_version=6
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE SURVEYS.SECTION_TEMPLATE(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SECTION_TEMPLATE_ID		NUMBER(10, 0)	NOT NULL,
	CREATED_DTM				TIMESTAMP		DEFAULT SYSTIMESTAMP NOT NULL,
	CREATED_USER_SID		NUMBER(10, 0)	NOT NULL,
	LAST_UPDATED_DTM		TIMESTAMP,
	LAST_UPDATED_USER_SID	NUMBER(10, 0),
	CONSTRAINT PK_SECTION_TEMPLATE PRIMARY KEY (APP_SID, SECTION_TEMPLATE_ID)
)
;
CREATE TABLE SURVEYS.SECTION_TEMPLATE_TR(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SECTION_TEMPLATE_ID		NUMBER(10, 0)	NOT NULL,
	LANGUAGE_CODE			VARCHAR2(50)	NOT NULL,
	NAME					VARCHAR2(4000)	NOT NULL,
	CONSTRAINT PK_SECTION_TEMPLATE_TR PRIMARY KEY (APP_SID, SECTION_TEMPLATE_ID, LANGUAGE_CODE),
	CONSTRAINT FK_SECTION_TEMPLATE_TR_ST FOREIGN KEY (APP_SID, SECTION_TEMPLATE_ID)
		REFERENCES SURVEYS.SECTION_TEMPLATE (APP_SID, SECTION_TEMPLATE_ID)
)
;
CREATE TABLE SURVEYS.SECTION_TEMPLATE_SECTION(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SECTION_TEMPLATE_ID		NUMBER(10, 0)	NOT NULL,
	SECTION_ID				NUMBER(10, 0)	NOT NULL,
	PARENT_ID				NUMBER(10, 0),
	POS						NUMBER(10, 0)	DEFAULT 0 NOT NULL,
	CONSTRAINT PK_SECTION_TEMPLATE_SECTION PRIMARY KEY (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID),
	CONSTRAINT FK_SECTION_TEMPL_SECT_PARENT FOREIGN KEY (APP_SID, SECTION_TEMPLATE_ID, PARENT_ID)
		REFERENCES SURVEYS.SECTION_TEMPLATE_SECTION (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID)
)
;
CREATE TABLE SURVEYS.SECTION_TEMPLATE_SECTION_TR(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SECTION_TEMPLATE_ID		NUMBER(10, 0)	NOT NULL,
	SECTION_ID				NUMBER(10, 0)	NOT NULL,
	LANGUAGE_CODE			VARCHAR2(50)	NOT NULL,
	LABEL					VARCHAR2(1024),
	SIMPLE_INFO_TEXT		VARCHAR2(4000),
	POPUP_TEXT				VARCHAR2(4000),
	CONSTRAINT PK_SECTION_TEMPLATE_SECT_TR PRIMARY KEY (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID, LANGUAGE_CODE),
	CONSTRAINT FK_SECTION_TEMPLATE_SECT_ID FOREIGN KEY (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID)
		REFERENCES SURVEYS.SECTION_TEMPLATE_SECTION (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID)
)
;
CREATE TABLE SURVEYS.SECTION_TEMPLATE_SECTION_TAG(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SECTION_TEMPLATE_ID		NUMBER(10, 0)	NOT NULL,
	SECTION_ID				NUMBER(10, 0)	NOT NULL,
	TAG_ID					NUMBER(10, 0)	NOT NULL,
	CONSTRAINT PK_SECTION_TEMPLATE_SECT_TAG PRIMARY KEY (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID, TAG_ID)
)
;
CREATE TABLE SURVEYS.SECTION_TEMPLATE_QUESTION(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SECTION_TEMPLATE_ID		NUMBER(10, 0)	NOT NULL,
	SECTION_ID				NUMBER(10, 0)	NOT NULL,
	QUESTION_ID				NUMBER(10, 0)	NOT NULL,
	CONSTRAINT PK_SECTION_TEMPLATE_SECT_QUEST PRIMARY KEY (APP_SID, SECTION_TEMPLATE_ID, SECTION_ID, QUESTION_ID),
	CONSTRAINT FK_SECTION_TEMPLATE_SECT_QUEST FOREIGN KEY (APP_SID, QUESTION_ID)
		REFERENCES SURVEYS.QUESTION (APP_SID, QUESTION_ID)
)
;

CREATE SEQUENCE SURVEYS.SECTION_TEMPLATE_SEQ;

-- Alter tables

-- *** Grants ***



-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **
CREATE OR REPLACE PACKAGE surveys.template_pkg AS END;
/

GRANT EXECUTE ON surveys.template_pkg to web_user;


-- *** Conditional Packages ***

-- *** Packages ***
--@../surveys/template_pkg
--@../surveys/template_body

@update_tail
