-- Please update version.sql too -- this keeps clean builds in sync
define version=1408
@update_header

ALTER TABLE CSR.SHEET_VALUE_HIDDEN_CACHE ADD CONSTRAINT FK_SHEET_VALUE_HIDDEN_CACHE_SV
	FOREIGN KEY (APP_SID, SHEET_VALUE_ID)
	REFERENCES CSR.SHEET_VALUE(APP_SID, SHEET_VALUE_ID);

CREATE TABLE CSRIMP.SHEET_VALUE_HIDDEN_CACHE(
	CSRIMP_SESSION_ID			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	SHEET_VALUE_ID				NUMBER(10,0)	NOT NULL,
	VAL_NUMBER					NUMBER(24,10),
	NOTE						CLOB,
	ENTRY_MEASURE_CONVERSION_ID	NUMBER(10, 0),
	ENTRY_VAL_NUMBER			NUMBER(24, 10),
	CONSTRAINT PK_SHEET_VALUE_HIDDEN_CACHE PRIMARY KEY (CSRIMP_SESSION_ID, SHEET_VALUE_ID),
	CONSTRAINT FK_SHEET_VALUE_HIDDEN_CACHE_IS FOREIGN KEY
    	(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
    	ON DELETE CASCADE
)
;

grant insert on csr.sheet_value_hidden_cache to csrimp;
grant insert,select,update,delete on csrimp.sheet_value_hidden_cache to web_user;

@../schema_pkg
@../schema_body
@../csrimp/imp_body

@update_tail
