-- Please update version.sql too -- this keeps clean builds in sync
define version=2540
@update_header

CREATE TABLE CSR.REGION_POSTIT(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SID    NUMBER(10, 0)    NOT NULL,
    POSTIT_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_REGION_POSTIT PRIMARY KEY (APP_SID, REGION_SID, POSTIT_ID)
);


ALTER TABLE CSR.REGION_POSTIT ADD CONSTRAINT FK_REGION_REGION_POSTIT 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID);

ALTER TABLE CSR.REGION_POSTIT ADD CONSTRAINT FK_POSTIT_REGION_POSTIT
    FOREIGN KEY (APP_SID, POSTIT_ID)
    REFERENCES CSR.POSTIT(APP_SID, POSTIT_ID) ON DELETE CASCADE;

@..\property_pkg
@..\property_body

@update_tail
