-- Please update version.sql too -- this keeps clean builds in sync
define version=157
@update_header

-- add RI to "sections" stuff (previously in a separate ER/Studio schema and hadn't been done)

ALTER TABLE ATTACHMENT_HISTORY DROP CONSTRAINT RefSECTION_VERSION8;
ALTER TABLE ATTACHMENT_HISTORY DROP CONSTRAINT RefATTACHMENT13;
ALTER TABLE ROOT_SECTION_USER DROP CONSTRAINT RefSECTION11;
ALTER TABLE SECTION DROP CONSTRAINT RefSECTION1;
ALTER TABLE SECTION DROP CONSTRAINT RefSECTION_VERSION20;
ALTER TABLE SECTION DROP CONSTRAINT RefSECTION_VERSION21;
ALTER TABLE SECTION_APPROVERS DROP CONSTRAINT RefSECTION17;
ALTER TABLE SECTION_COMMENT DROP CONSTRAINT RefSECTION_COMMENT4;
ALTER TABLE SECTION_COMMENT DROP CONSTRAINT RefSECTION9;
ALTER TABLE SECTION_VERSION DROP CONSTRAINT RefSECTION7;

ALTER TABLE SECTION ADD (REF VARCHAR2(64) );

CREATE TABLE SECTION_MODULE(
    MODULE_ROOT_SID    NUMBER(10, 0)    NOT NULL,
    CSR_ROOT_SID       NUMBER(10, 0)    NOT NULL,
    LABEL			   VARCHAR2(1024)	NOT NULL,
    CONSTRAINT PK427 PRIMARY KEY (MODULE_ROOT_SID, CSR_ROOT_SID)
)
;

-- insert a load of module_root_sids
INSERT INTO SECTION_MODULE (MODULE_ROOT_SID, CSR_ROOT_SID, LABEL)
	SELECT module_root_sid, csr_root_sid, name
	  FROM (
		SELECT DISTINCT MODULE_ROOT_SID, CSR_ROOT_SID 
		  FROM SECTION
	  )x, security.securable_object so
	 WHERE x.module_root_Sid = so.sid_Id;
	 
-- update to give it a helper package
update security.securable_object_class set helper_pkg ='csr.section_root_pkg' where class_name='CSRSectionRoot';


-- patch up dodgy user sids
DECLARE
	v_act				security_pkg.T_ACT_ID;
	v_user_sid			security_pkg.T_SID_ID;
BEGIN
	user_pkg.LogonAuthenticatedPath(0, '//csr/users/richard', 10000, v_act);
	user_pkg.GetSID(v_act, v_user_sid);
	update section_version 
	   set changed_by_sid = v_user_sid
	 where changed_by_sid in (
		select distinct changed_by_sid 
		  from section_version 
		 minus 
		select csr_user_sid 
		  from csr_user
	);
	DELETE FROM ROOT_SECTION_USER
	 WHERE CSR_USER_SID IN (
		SELECT DISTINCT csr_user_sid FROM root_section_user 
		  MINUS 
		SELECT csr_user_sid FROM csr_user
	 );
	commit;
END;
/




-- 
-- TABLE: ATTACHMENT 
--

ALTER TABLE ATTACHMENT ADD CONSTRAINT RefDATAVIEW824 
    FOREIGN KEY (DATAVIEW_SID)
    REFERENCES DATAVIEW(DATAVIEW_SID)
;

ALTER TABLE ATTACHMENT ADD CONSTRAINT RefIND825 
    FOREIGN KEY (INDICATOR_SID)
    REFERENCES IND(IND_SID)
;


-- 
-- TABLE: ATTACHMENT_HISTORY 
--

ALTER TABLE ATTACHMENT_HISTORY ADD CONSTRAINT RefATTACHMENT826 
    FOREIGN KEY (ATTACHMENT_ID)
    REFERENCES ATTACHMENT(ATTACHMENT_ID)
;

ALTER TABLE ATTACHMENT_HISTORY ADD CONSTRAINT RefSECTION_VERSION827 
    FOREIGN KEY (SECTION_SID, VERSION_NUMBER)
    REFERENCES SECTION_VERSION(SECTION_SID, VERSION_NUMBER)
;




-- 
-- TABLE: ROOT_SECTION_USER 
--

ALTER TABLE ROOT_SECTION_USER ADD CONSTRAINT RefCSR_USER828 
    FOREIGN KEY (CSR_USER_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE ROOT_SECTION_USER ADD CONSTRAINT RefSECTION829 
    FOREIGN KEY (ROOT_SECTION_SID)
    REFERENCES SECTION(SECTION_SID)
;


-- 
-- TABLE: SECTION 
--

ALTER TABLE SECTION ADD CONSTRAINT RefSECTION_VERSION830 
    FOREIGN KEY (SECTION_SID, CHECKED_OUT_VERSION_NUMBER)
    REFERENCES SECTION_VERSION(SECTION_SID, VERSION_NUMBER)
;

ALTER TABLE SECTION ADD CONSTRAINT RefSECTION_VERSION831 
    FOREIGN KEY (SECTION_SID, VISIBLE_VERSION_NUMBER)
    REFERENCES SECTION_VERSION(SECTION_SID, VERSION_NUMBER)
;

ALTER TABLE SECTION ADD CONSTRAINT RefCSR_USER832 
    FOREIGN KEY (CHECKED_OUT_TO_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE SECTION ADD CONSTRAINT RefSECTION_MODULE833 
    FOREIGN KEY (MODULE_ROOT_SID, CSR_ROOT_SID)
    REFERENCES SECTION_MODULE(MODULE_ROOT_SID, CSR_ROOT_SID)
;

ALTER TABLE SECTION ADD CONSTRAINT RefSECTION834 
    FOREIGN KEY (PARENT_SID)
    REFERENCES SECTION(SECTION_SID)
;


-- 
-- TABLE: SECTION_APPROVERS 
--

ALTER TABLE SECTION_APPROVERS ADD CONSTRAINT RefCSR_USER835 
    FOREIGN KEY (APPROVER_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE SECTION_APPROVERS ADD CONSTRAINT RefSECTION836 
    FOREIGN KEY (SECTION_SID)
    REFERENCES SECTION(SECTION_SID)
;


-- 
-- TABLE: SECTION_COMMENT 
--

ALTER TABLE SECTION_COMMENT ADD CONSTRAINT RefSECTION837 
    FOREIGN KEY (SECTION_SID)
    REFERENCES SECTION(SECTION_SID)
;

ALTER TABLE SECTION_COMMENT ADD CONSTRAINT RefCSR_USER838 
    FOREIGN KEY (ENTERED_BY_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE SECTION_COMMENT ADD CONSTRAINT RefSECTION_COMMENT839 
    FOREIGN KEY (IN_REPLY_TO_ID)
    REFERENCES SECTION_COMMENT(SECTION_COMMENT_ID)
;


-- 
-- TABLE: SECTION_MODULE 
--

ALTER TABLE SECTION_MODULE ADD CONSTRAINT RefCUSTOMER840 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;


-- 
-- TABLE: SECTION_VERSION 
--

ALTER TABLE SECTION_VERSION ADD CONSTRAINT RefCSR_USER841 
    FOREIGN KEY (CHANGED_BY_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE SECTION_VERSION ADD CONSTRAINT RefCSR_USER842 
    FOREIGN KEY (APPROVED_BY_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE SECTION_VERSION ADD CONSTRAINT RefSECTION843 
    FOREIGN KEY (SECTION_SID)
    REFERENCES SECTION(SECTION_SID)
;

@..\text\section_pkg
@..\text\section_body
@..\text\section_root_pkg
@..\text\section_root_body

GRANT EXECUTE ON csr.section_root_pkg TO SECURITY;

@update_tail
