-- Please update version.sql too -- this keeps clean builds in sync
define version=1224
@update_header

ALTER TABLE CT.EIO
ADD (OLD_DESCRIPTION VARCHAR2(1024 BYTE));

UPDATE ct.eio SET old_description = '112A00 - Animal production, except cattle and poultry and eggs' WHERE LOWER(description) = 'animals other than cattle and poultry and eggs';
UPDATE ct.eio SET old_description = '1121A0 - Cattle ranching and farming' WHERE LOWER(description) = 'cattle';
UPDATE ct.eio SET old_description = '111920 - Cotton farming' WHERE LOWER(description) = 'cotton (raw)';
UPDATE ct.eio SET old_description = '1119B0 - All other crop farming' WHERE LOWER(description) = 'crops (miscellaneous)';
UPDATE ct.eio SET old_description = '112120 - Dairy cattle and milk production' WHERE LOWER(description) = 'dairy cattle and milk';
UPDATE ct.eio SET old_description = '114100 - Fishing' WHERE LOWER(description) = 'fish';
UPDATE ct.eio SET old_description = '1113A0 - Fruit farming' WHERE LOWER(description) = 'fruits';
UPDATE ct.eio SET old_description = '1111B0 - Grain farming' WHERE LOWER(description) = 'grains';
UPDATE ct.eio SET old_description = '111400 - Greenhouse, nursery, and floriculture production' WHERE LOWER(description) = 'greenhouse, nursery, and floriculture';
UPDATE ct.eio SET old_description = '1111A0 - Oilseed farming' WHERE LOWER(description) = 'oilseeds';
UPDATE ct.eio SET old_description = '112300 - Poultry and egg production' WHERE LOWER(description) = 'poultry and eggs';
UPDATE ct.eio SET old_description = '1119A0 - Sugarcane and sugar beet farming' WHERE LOWER(description) = 'sugarcane and sugar beet (raw)';
UPDATE ct.eio SET old_description = '111910 - Tobacco farming' WHERE LOWER(description) = 'tobacco (raw)';
UPDATE ct.eio SET old_description = '111335 - Tree nut farming' WHERE LOWER(description) = 'tree nuts';
UPDATE ct.eio SET old_description = '111200 - Vegetable and melon farming' WHERE LOWER(description) = 'vegetables and melons';
UPDATE ct.eio SET old_description = '32711A - Pottery, ceramics, and plumbing fixture manufacturing' WHERE LOWER(description) = 'pottery, ceramics and plumbing fixtures';
UPDATE ct.eio SET old_description = '3259A0 - All other chemical product and preparation manufacturing' WHERE LOWER(description) = 'chemical products';
UPDATE ct.eio SET old_description = '325310 - Fertilizer manufacturing' WHERE LOWER(description) = 'fertilizers';
UPDATE ct.eio SET old_description = '325188 - All other basic inorganic chemical manufacturing' WHERE LOWER(description) = 'inorganic chemicals';
UPDATE ct.eio SET old_description = '324191 - Petroleum lubricating oil and grease manufacturing' WHERE LOWER(description) = 'lubricating oil and grease';
UPDATE ct.eio SET old_description = '325190 - Other basic organic chemical manufacturing' WHERE LOWER(description) = 'organic chemicals';
UPDATE ct.eio SET old_description = '325320 - Pesticide and other agricultural chemical manufacturing' WHERE LOWER(description) = 'pesticides and agricultural chemicals';
UPDATE ct.eio SET old_description = '325110 - Petrochemical manufacturing' WHERE LOWER(description) = 'petrochemicals';
UPDATE ct.eio SET old_description = '324199 - All other petroleum and coal products manufacturing' WHERE LOWER(description) = 'petroleum and coal products';
UPDATE ct.eio SET old_description = '325610 - Soap and cleaning compound manufacturing' WHERE LOWER(description) = 'soap and cleaning compounds';
UPDATE ct.eio SET old_description = '325520 - Adhesive manufacturing' WHERE LOWER(description) = 'adhesives';
UPDATE ct.eio SET old_description = '324121 - Asphalt paving mixture and block manufacturing' WHERE LOWER(description) = 'asphalt paving mixture and blocks';
UPDATE ct.eio SET old_description = '324122 - Asphalt shingle and coating materials manufacturing' WHERE LOWER(description) = 'asphalt shingle and coating materials';
UPDATE ct.eio SET old_description = '32712A - Brick, tile, and other structural clay product manufacturing' WHERE LOWER(description) = 'brick, tile, and other structural clay products';
UPDATE ct.eio SET old_description = '327310 - Cement manufacturing' WHERE LOWER(description) = 'cement';
UPDATE ct.eio SET old_description = '32712B - Clay and nonclay refractory manufacturing' WHERE LOWER(description) = 'clay and nonclay refractory products';
UPDATE ct.eio SET old_description = '327320 - Ready-mix concrete manufacturing' WHERE LOWER(description) = 'concrete (ready-mix)';
UPDATE ct.eio SET old_description = '327330 - Concrete pipe, brick, and block manufacturing' WHERE LOWER(description) = 'concrete pipes, bricks, and blocks';
UPDATE ct.eio SET old_description = '327390 - Other concrete product manufacturing' WHERE LOWER(description) = 'concrete products (miscellaneous)';
UPDATE ct.eio SET old_description = '333120 - Construction machinery manufacturing' WHERE LOWER(description) = 'construction machinery';
UPDATE ct.eio SET old_description = '327991 - Cut stone and stone product manufacturing' WHERE LOWER(description) = 'cut stone and stone products';
UPDATE ct.eio SET old_description = '3274A0 - Lime and gypsum product manufacturing' WHERE LOWER(description) = 'lime and gypsum products';
UPDATE ct.eio SET old_description = '327993 - Mineral wool manufacturing' WHERE LOWER(description) = 'mineral wool';
UPDATE ct.eio SET old_description = '327992 - Ground or treated mineral and earth manufacturing' WHERE LOWER(description) = 'minerals and earth (round or treated)';
UPDATE ct.eio SET old_description = '327999 - Miscellaneous nonmetallic mineral products' WHERE LOWER(description) = 'nonmetallic mineral products (miscellaneous)';
UPDATE ct.eio SET old_description = '212390 - Other nonmetallic mineral mining and quarrying' WHERE LOWER(description) = 'nonmetallic minerals (miscellaneous)';
UPDATE ct.eio SET old_description = '230101 - Nonresidential commercial and health care structures' WHERE LOWER(description) = 'nonresidential commercial and health care structures';
UPDATE ct.eio SET old_description = '230102 - Nonresidential manufacturing structures' WHERE LOWER(description) = 'nonresidential structures';
UPDATE ct.eio SET old_description = '230103 - Other nonresidential structures' WHERE LOWER(description) = 'nonresidential structures (miscellaneous)';
UPDATE ct.eio SET old_description = '230201 - Residential permanent site single- and multi-family structures' WHERE LOWER(description) = 'residential permanent site single- and multi-family structures';
UPDATE ct.eio SET old_description = '230202 - Other residential structures' WHERE LOWER(description) = 'residential structures (miscellaneous)';
UPDATE ct.eio SET old_description = '212320 - Sand, gravel, clay, and ceramic and refractory minerals mining and quarrying' WHERE LOWER(description) = 'sand, gravel, clay and ceramic and refractory minerals';
UPDATE ct.eio SET old_description = '212310 - Stone mining and quarrying' WHERE LOWER(description) = 'stones (mined and quarried)';
UPDATE ct.eio SET old_description = '334300 - Audio and video equipment manufacturing' WHERE LOWER(description) = 'audio and video equipment';
UPDATE ct.eio SET old_description = '334412 - Bare printed circuit board manufacturing' WHERE LOWER(description) = 'bare printed circuit boards';
UPDATE ct.eio SET old_description = '334220 - Broadcast and wireless communications equipment' WHERE LOWER(description) = 'broadcast and wireless communications equipment';
UPDATE ct.eio SET old_description = '33441A - Electronic capacitor, resistor, coil, transformer, and other inductor manufacturing' WHERE LOWER(description) = 'capacitors, resistors, coils, transformers, and other inductors';
UPDATE ct.eio SET old_description = '334290 - Other communications equipment manufacturing' WHERE LOWER(description) = 'communications equipment (miscellaneous)';
UPDATE ct.eio SET old_description = '334112 - Computer storage device manufacturing' WHERE LOWER(description) = 'computer storage devices';
UPDATE ct.eio SET old_description = '33411A - Computer terminals and other computer peripheral equipment manufacturing' WHERE LOWER(description) = 'computer terminals and other computer peripheral equipment';
UPDATE ct.eio SET old_description = '334111 - Electronic computer manufacturing' WHERE LOWER(description) = 'computers';
UPDATE ct.eio SET old_description = '334417 - Electronic connector manufacturing' WHERE LOWER(description) = 'connectors';
UPDATE ct.eio SET old_description = '334510 - Electromedical and electrotherapeutic apparatus manufacturing' WHERE LOWER(description) = 'electromedical and electrotherapeutic apparatus';
UPDATE ct.eio SET old_description = '334419 - Other electronic component manufacturing' WHERE LOWER(description) = 'electronic components (miscellaneous)';
UPDATE ct.eio SET old_description = '334418 - Printed circuit assembly (electronic assembly) manufacturing' WHERE LOWER(description) = 'printed circuit assembly';
UPDATE ct.eio SET old_description = '334413 - Semiconductor and related device manufacturing' WHERE LOWER(description) = 'semiconductor and related devices';
UPDATE ct.eio SET old_description = '333295 - Semiconductor machinery manufacturing' WHERE LOWER(description) = 'semiconductor machinery';
UPDATE ct.eio SET old_description = '334210 - Telephone apparatus manufacturing' WHERE LOWER(description) = 'telephone apparatus';
UPDATE ct.eio SET old_description = '334411 - Electron tube manufacturing' WHERE LOWER(description) = 'tubes (electronic)';
UPDATE ct.eio SET old_description = '312140 - Distilleries' WHERE LOWER(description) = 'alcohol (except beer and wine)';
UPDATE ct.eio SET old_description = '311119 - Other animal food manufacturing' WHERE LOWER(description) = 'animal food (miscellaneous)';
UPDATE ct.eio SET old_description = '31161A - Animal (except poultry) slaughtering, rendering, and processing' WHERE LOWER(description) = 'animals except poultry (slaughtered, rendered, and processed)';
UPDATE ct.eio SET old_description = '312120 - Breweries' WHERE LOWER(description) = 'beer';
UPDATE ct.eio SET old_description = '311313 - Beet sugar manufacturing' WHERE LOWER(description) = 'beet sugar (refined)';
UPDATE ct.eio SET old_description = '311810 - Bread and bakery product manufacturing' WHERE LOWER(description) = 'bread and bakery products';
UPDATE ct.eio SET old_description = '311230 - Breakfast cereal manufacturing' WHERE LOWER(description) = 'breakfast cereal';
UPDATE ct.eio SET old_description = '311513 - Cheese manufacturing' WHERE LOWER(description) = 'cheese';
UPDATE ct.eio SET old_description = '311320 - Chocolate and confectionery manufacturing from cacao beans' WHERE LOWER(description) = 'chocolate and confectionery from cacao beans';
UPDATE ct.eio SET old_description = '311920 - Coffee and tea manufacturing' WHERE LOWER(description) = 'coffee and tea';
UPDATE ct.eio SET old_description = '311340 - Nonchocolate confectionery manufacturing' WHERE LOWER(description) = 'confectionery (nonchocolate)';
UPDATE ct.eio SET old_description = '311330 - Confectionery manufacturing from purchased chocolate' WHERE LOWER(description) = 'confectionery from purchased chocolate';
UPDATE ct.eio SET old_description = '311820 - Cookie, cracker, and pasta manufacturing' WHERE LOWER(description) = 'cookies, crackers, and pasta';
UPDATE ct.eio SET old_description = '311514 - Dry, condensed, and evaporated dairy product manufacturing' WHERE LOWER(description) = 'dairy products (dry, condensed, and evaporated)';
UPDATE ct.eio SET old_description = '311111 - Dog and cat food manufacturing' WHERE LOWER(description) = 'dog and cat food';
UPDATE ct.eio SET old_description = '311225 - Fats and oils refining and blending' WHERE LOWER(description) = 'fats and oils (refined and blended)';
UPDATE ct.eio SET old_description = '311210 - Flour milling and malt manufacturing' WHERE LOWER(description) = 'flour and malt';
UPDATE ct.eio SET old_description = '311990 - All other food manufacturing' WHERE LOWER(description) = 'food (miscellaneous)';
UPDATE ct.eio SET old_description = '311410 - Frozen food manufacturing' WHERE LOWER(description) = 'frozen food';
UPDATE ct.eio SET old_description = '311420 - Fruit and vegetable canning, pickling, and drying' WHERE LOWER(description) = 'fruits and vegetables (canned, pickled, and dried)';
UPDATE ct.eio SET old_description = '311520 - Ice cream and frozen dessert manufacturing' WHERE LOWER(description) = 'ice cream and frozen desserts';
UPDATE ct.eio SET old_description = '31151A - Fluid milk and butter manufacturing' WHERE LOWER(description) = 'milk and butter (fluid)';
UPDATE ct.eio SET old_description = '311615 - Poultry processing' WHERE LOWER(description) = 'poultry (processed)';
UPDATE ct.eio SET old_description = '311700 - Seafood product preparation and packaging' WHERE LOWER(description) = 'seafood products (prepared and packaged)';
UPDATE ct.eio SET old_description = '311940 - Seasoning and dressing manufacturing' WHERE LOWER(description) = 'seasoning and dressing';
UPDATE ct.eio SET old_description = '311910 - Snack food manufacturing' WHERE LOWER(description) = 'snack foods';
UPDATE ct.eio SET old_description = '312110 - Soft drink and ice manufacturing' WHERE LOWER(description) = 'soft drinks and ice';
UPDATE ct.eio SET old_description = '31122A - Soybean and other oilseed processing' WHERE LOWER(description) = 'soybean and other oilseed (processed)';
UPDATE ct.eio SET old_description = '31131A - Sugar cane mills and refining' WHERE LOWER(description) = 'sugar cane (refined)';
UPDATE ct.eio SET old_description = '311930 - Flavoring syrup and concentrate manufacturing' WHERE LOWER(description) = 'syrup and concentrate (flavored)';
UPDATE ct.eio SET old_description = '311830 - Tortilla manufacturing' WHERE LOWER(description) = 'tortilla';
UPDATE ct.eio SET old_description = '311221 - Wet corn milling' WHERE LOWER(description) = 'wet corn';
UPDATE ct.eio SET old_description = '312130 - Wineries' WHERE LOWER(description) = 'wine';
UPDATE ct.eio SET old_description = '327211 - Flat glass manufacturing' WHERE LOWER(description) = 'flat glass';
UPDATE ct.eio SET old_description = '327212 - Other pressed and blown glass and glassware manufacturing' WHERE LOWER(description) = 'glass and glassware (pressed and blown)';
UPDATE ct.eio SET old_description = '327213 - Glass container manufacturing' WHERE LOWER(description) = 'glass containers';
UPDATE ct.eio SET old_description = '327215 - Glass product manufacturing made of purchased glass' WHERE LOWER(description) = 'glass products made of purchased glass';
UPDATE ct.eio SET old_description = '325181 - Alkalies and chlorine manufacturing' WHERE LOWER(description) = 'alkalies and chlorine';
UPDATE ct.eio SET old_description = '325182 - Carbon black manufacturing' WHERE LOWER(description) = 'carbon black';
UPDATE ct.eio SET old_description = '325120 - Industrial gas manufacturing' WHERE LOWER(description) = 'industrial gases';
UPDATE ct.eio SET old_description = '325130 - Synthetic dye and pigment manufacturing' WHERE LOWER(description) = 'synthetic dyes and pigments';
UPDATE ct.eio SET old_description = '316200 - Footwear manufacturing' WHERE LOWER(description) = 'footwear';
UPDATE ct.eio SET old_description = '316900 - Other leather and allied product manufacturing' WHERE LOWER(description) = 'leather and allied products (miscellaneous)';
UPDATE ct.eio SET old_description = '316100 - Leather and hide tanning and finishing' WHERE LOWER(description) = 'leather and hide (tanned and finished)';
UPDATE ct.eio SET old_description = '327910 - Abrasive product manufacturing' WHERE LOWER(description) = 'abrasive products';
UPDATE ct.eio SET old_description = '333912 - Air and gas compressor manufacturing' WHERE LOWER(description) = 'air and gas compressors';
UPDATE ct.eio SET old_description = '333415 - Air conditioning, refrigeration, and warm air heating equipment manufacturing' WHERE LOWER(description) = 'air conditioning, refrigeration, and warm air heating equipment';
UPDATE ct.eio SET old_description = '33341A - Air purification and ventilation equipment manufacturing' WHERE LOWER(description) = 'air purification and ventilation equipment';
UPDATE ct.eio SET old_description = '336412 - Aircraft engine and engine parts manufacturing' WHERE LOWER(description) = 'aircraft engines and engine parts';
UPDATE ct.eio SET old_description = '336413 - Other aircraft parts and auxiliary equipment manufacturing' WHERE LOWER(description) = 'aircraft parts and auxiliary equipment (miscellaneous)';
UPDATE ct.eio SET old_description = '336411 - Aircraft manufacturing' WHERE LOWER(description) = 'aircrafts';
UPDATE ct.eio SET old_description = '33299A - Ammunition manufacturing' WHERE LOWER(description) = 'ammunition';
UPDATE ct.eio SET old_description = '335228 - Other major household appliance manufacturing' WHERE LOWER(description) = 'appliances for households (miscellaneous)';
UPDATE ct.eio SET old_description = '33299B - Arms, ordnance, and accessories manufacturing' WHERE LOWER(description) = 'arms, ordnance, and accessories';
UPDATE ct.eio SET old_description = '336111 - Automobile manufacturing' WHERE LOWER(description) = 'automobiles';
UPDATE ct.eio SET old_description = '335912 - Primary battery manufacturing' WHERE LOWER(description) = 'batteries (primary)';
UPDATE ct.eio SET old_description = '335911 - Storage battery manufacturing' WHERE LOWER(description) = 'batteries (storage)';
UPDATE ct.eio SET old_description = '337920 - Blind and shade manufacturing' WHERE LOWER(description) = 'blinds and shades';
UPDATE ct.eio SET old_description = '336612 - Boat building' WHERE LOWER(description) = 'boats';
UPDATE ct.eio SET old_description = '339994 - Broom, brush, and mop manufacturing' WHERE LOWER(description) = 'brooms, brushes, and mops';
UPDATE ct.eio SET old_description = '335110 - Electric lamp bulb and part manufacturing' WHERE LOWER(description) = 'bulb and parts for electric lamps';
UPDATE ct.eio SET old_description = '335991 - Carbon and graphite product manufacturing' WHERE LOWER(description) = 'carbon and graphite products';
UPDATE ct.eio SET old_description = '333319 - Other commercial and service industry machinery manufacturing' WHERE LOWER(description) = 'commercial and service industry machinery (miscellaneous)';
UPDATE ct.eio SET old_description = '335920 - Communication and energy wire and cable manufacturing' WHERE LOWER(description) = 'communication and energy wires and cables';
UPDATE ct.eio SET old_description = '335221 - Household cooking appliance manufacturing' WHERE LOWER(description) = 'cooking appliances for households';
UPDATE ct.eio SET old_description = '33221A - Cutlery, utensil, pot, and pan manufacturing' WHERE LOWER(description) = 'cutlery, utensils, pots, and pans';
UPDATE ct.eio SET old_description = '333515 - Cutting tool and machine tool accessory manufacturing' WHERE LOWER(description) = 'cutting tools and machine tool accessories';
UPDATE ct.eio SET old_description = '339114 - Dental equipment and supplies manufacturing' WHERE LOWER(description) = 'dental equipment and supplies';
UPDATE ct.eio SET old_description = '339116 - Dental laboratories' WHERE LOWER(description) = 'dental laboratories';
UPDATE ct.eio SET old_description = '339930 - Doll, toy, and game manufacturing' WHERE LOWER(description) = 'dolls, toys, and games';
UPDATE ct.eio SET old_description = '335210 - Small electrical appliance manufacturing' WHERE LOWER(description) = 'electrical appliances (small)';
UPDATE ct.eio SET old_description = '335999 - All other miscellaneous electrical equipment and component manufacturing' WHERE LOWER(description) = 'electrical equipment and components (miscellaneous)';
UPDATE ct.eio SET old_description = '333618 - Other engine equipment manufacturing' WHERE LOWER(description) = 'engine equipment (miscellaneous)';
UPDATE ct.eio SET old_description = '334512 - Automatic environmental control manufacturing' WHERE LOWER(description) = 'environmental control equipment (automated)';
UPDATE ct.eio SET old_description = '333111 - Farm machinery and equipment manufacturing' WHERE LOWER(description) = 'farm machinery and equipment';
UPDATE ct.eio SET old_description = '33399B - Fluid power process machinery' WHERE LOWER(description) = 'fluid power process machinery';
UPDATE ct.eio SET old_description = '113A00 - Forest nurseries, forest products, and timber tracts' WHERE LOWER(description) = 'forest nurseries, forest products, and timber tracts';
UPDATE ct.eio SET old_description = '337127 - Institutional furniture manufacturing' WHERE LOWER(description) = 'furniture (institutional)';
UPDATE ct.eio SET old_description = '33712A - Metal and other household furniture (except wood) manufacturing' WHERE LOWER(description) = 'furniture (metals and other materials except wood)';
UPDATE ct.eio SET old_description = '337122 - Nonupholstered wood household furniture manufacturing' WHERE LOWER(description) = 'furniture for households (nonupholstered wood)';
UPDATE ct.eio SET old_description = '337121 - Upholstered household furniture manufacturing' WHERE LOWER(description) = 'furniture for households (upholstered)';
UPDATE ct.eio SET old_description = '333112 - Lawn and garden equipment manufacturing' WHERE LOWER(description) = 'garden and lawn equipment';
UPDATE ct.eio SET old_description = '339991 - Gasket, packing, and sealing device manufacturing' WHERE LOWER(description) = 'gasket, packing, and sealing devices';
UPDATE ct.eio SET old_description = '33221B - Handtool manufacturing' WHERE LOWER(description) = 'handtools';
UPDATE ct.eio SET old_description = '333991 - Power-driven handtool manufacturing' WHERE LOWER(description) = 'handtools (power driven)';
UPDATE ct.eio SET old_description = '332500 - Hardware manufacturing' WHERE LOWER(description) = 'hardware';
UPDATE ct.eio SET old_description = '333414 - Heating equipment (except warm air furnaces) manufacturing' WHERE LOWER(description) = 'heating equipment (except warm air furnaces)';
UPDATE ct.eio SET old_description = '33329A - Other industrial machinery manufacturing' WHERE LOWER(description) = 'industrial machinery (miscellaneous)';
UPDATE ct.eio SET old_description = '333511 - Industrial mold manufacturing' WHERE LOWER(description) = 'industrial molds';
UPDATE ct.eio SET old_description = '333994 - Industrial process furnace and oven manufacturing' WHERE LOWER(description) = 'industrial process furnace and ovens';
UPDATE ct.eio SET old_description = '334513 - Industrial process variable instruments manufacturing' WHERE LOWER(description) = 'industrial process variable instruments';
UPDATE ct.eio SET old_description = '334511 - Search, detection, and navigation instruments manufacturing' WHERE LOWER(description) = 'instruments for search, detection, and navigation';
UPDATE ct.eio SET old_description = '334517 - Irradiation apparatus manufacturing' WHERE LOWER(description) = 'irradiation apparatus';
UPDATE ct.eio SET old_description = '339910 - Jewelry and silverware manufacturing' WHERE LOWER(description) = 'jewelry and silverware';
UPDATE ct.eio SET old_description = '339111 - Laboratory apparatus and furniture manufacturing' WHERE LOWER(description) = 'laboratory apparatus and furniture';
UPDATE ct.eio SET old_description = '334516 - Analytical laboratory instrument manufacturing' WHERE LOWER(description) = 'laboratory instruments (analytical)';
UPDATE ct.eio SET old_description = '335224 - Household laundry equipment manufacturing' WHERE LOWER(description) = 'laundry equipment for households';
UPDATE ct.eio SET old_description = '335120 - Lighting fixture manufacturing' WHERE LOWER(description) = 'lighting fixtures';
UPDATE ct.eio SET old_description = '332710 - Machine shops' WHERE LOWER(description) = 'machine shops';
UPDATE ct.eio SET old_description = '33399A - Other general purpose machinery manufacturing' WHERE LOWER(description) = 'machinery for general purposes (miscellaneous)';
UPDATE ct.eio SET old_description = '334613 - Magnetic and optical recording media manufacturing' WHERE LOWER(description) = 'magnetic and optical recording media';
UPDATE ct.eio SET old_description = '321991 - Manufactured home (mobile home) manufacturing' WHERE LOWER(description) = 'manufactured homes (mobile homes)';
UPDATE ct.eio SET old_description = '332800 - Coating, engraving, heat treating and allied activities' WHERE LOWER(description) = 'manufactured products involving coating, engraving, heat treating';
UPDATE ct.eio SET old_description = '33999A - All other miscellaneous manufacturing' WHERE LOWER(description) = 'manufactured products (miscellaneous)';
UPDATE ct.eio SET old_description = '333920 - Material handling equipment manufacturing' WHERE LOWER(description) = 'material handling equipment';
UPDATE ct.eio SET old_description = '337910 - Mattress manufacturing' WHERE LOWER(description) = 'mattresses';
UPDATE ct.eio SET old_description = '33351A - Metal cutting and forming machine tool manufacturing' WHERE LOWER(description) = 'metal cutting and forming machine tools';
UPDATE ct.eio SET old_description = '336992 - Military armored vehicle, tank, and tank component manufacturing' WHERE LOWER(description) = 'military armored vehicles, tanks, and tank components';
UPDATE ct.eio SET old_description = '333130 - Mining and oil and gas field machinery manufacturing' WHERE LOWER(description) = 'mining and oil and gas field machinery';
UPDATE ct.eio SET old_description = '336213 - Motor home manufacturing' WHERE LOWER(description) = 'motor homes';
UPDATE ct.eio SET old_description = '336211 - Motor vehicle body manufacturing' WHERE LOWER(description) = 'motor vehicle bodies';
UPDATE ct.eio SET old_description = '336300 - Motor vehicle parts manufacturing' WHERE LOWER(description) = 'motor vehicle parts';
UPDATE ct.eio SET old_description = '336991 - Motorcycle, bicycle, and parts manufacturing' WHERE LOWER(description) = 'motorcycles, bicycles, and parts';
UPDATE ct.eio SET old_description = '335312 - Motor and generator manufacturing' WHERE LOWER(description) = 'motors and generators';
UPDATE ct.eio SET old_description = '339992 - Musical instrument manufacturing' WHERE LOWER(description) = 'musical instruments';
UPDATE ct.eio SET old_description = '337212 - Office furniture and custom architectural woodwork and millwork manufacturing' WHERE LOWER(description) = 'office furniture and custom architectural woodwork and millwork';
UPDATE ct.eio SET old_description = '339940 - Office supplies (except paper) manufacturing' WHERE LOWER(description) = 'office supplies (except paper)';
UPDATE ct.eio SET old_description = '339115 - Ophthalmic goods manufacturing' WHERE LOWER(description) = 'ophthalmic goods';
UPDATE ct.eio SET old_description = '333314 - Optical instrument and lens manufacturing' WHERE LOWER(description) = 'optical instrument and lens';
UPDATE ct.eio SET old_description = '336414 - Guided missile and space vehicle manufacturing' WHERE LOWER(description) = 'space vehicles and guided missiles';
UPDATE ct.eio SET old_description = '333993 - Packaging machinery manufacturing' WHERE LOWER(description) = 'packaging machinery';
UPDATE ct.eio SET old_description = '333315 - Photographic and photocopying equipment manufacturing' WHERE LOWER(description) = 'photographic and photocopying equipment';
UPDATE ct.eio SET old_description = '332996 - Fabricated pipe and pipe fitting manufacturing' WHERE LOWER(description) = 'pipe and pipe fittings (fabricated)';
UPDATE ct.eio SET old_description = '332310 - Plate work and fabricated structural product manufacturing' WHERE LOWER(description) = 'plate work and fabricated structural products';
UPDATE ct.eio SET old_description = '332913 - Plumbing fixture fitting and trim manufacturing' WHERE LOWER(description) = 'plumbing fixture fitting and trims';
UPDATE ct.eio SET old_description = '332410 - Power boiler and heat exchanger manufacturing' WHERE LOWER(description) = 'power boilers and heat exchangers';
UPDATE ct.eio SET old_description = '333613 - Mechanical power transmission equipment manufacturing' WHERE LOWER(description) = 'power transmission equipment (mechanical)';
UPDATE ct.eio SET old_description = '335311 - Power, distribution, and specialty transformer manufacturing' WHERE LOWER(description) = 'power, distribution, and specialty transformers';
UPDATE ct.eio SET old_description = '33641A - Propulsion units and parts for space vehicle and guided missiles' WHERE LOWER(description) = 'propulsion units and parts for space vehicles and guided missiles';
UPDATE ct.eio SET old_description = '333911 - Pump and pumping equipment manufacturing' WHERE LOWER(description) = 'pump and pumping equipment';
UPDATE ct.eio SET old_description = '336500 - Railroad rolling stock manufacturing' WHERE LOWER(description) = 'railroad rolling stocks';
UPDATE ct.eio SET old_description = '335222 - Household refrigerator and home freezer manufacturing' WHERE LOWER(description) = 'refrigerators and home freezers for households';
UPDATE ct.eio SET old_description = '335314 - Relay and industrial control manufacturing' WHERE LOWER(description) = 'relay and industrial control';
UPDATE ct.eio SET old_description = '33351B - Rolling mill and other metalworking machinery manufacturing' WHERE LOWER(description) = 'rolling mills and other metalworking machinery';
UPDATE ct.eio SET old_description = 'S00401 - Scrap' WHERE LOWER(description) = 'scraps';
UPDATE ct.eio SET old_description = '336611 - Ship building and repairing' WHERE LOWER(description) = 'ship';
UPDATE ct.eio SET old_description = '337215 - Showcase, partition, shelving, and locker manufacturing' WHERE LOWER(description) = 'showcases, partitions, shelving, and lockers';
UPDATE ct.eio SET old_description = '339950 - Sign manufacturing' WHERE LOWER(description) = 'signs';
UPDATE ct.eio SET old_description = '333514 - Special tool, die, jig, and fixture manufacturing' WHERE LOWER(description) = 'special tools, die, jigs, and fixtures';
UPDATE ct.eio SET old_description = '333612 - Speed changer, industrial high-speed drive, and gear manufacturing' WHERE LOWER(description) = 'speed changers, industrial high-speed drives, and gears';
UPDATE ct.eio SET old_description = '339920 - Sporting and athletic goods manufacturing' WHERE LOWER(description) = 'sporting and athletic goods';
UPDATE ct.eio SET old_description = '322230 - Stationery product manufacturing' WHERE LOWER(description) = 'stationery products';
UPDATE ct.eio SET old_description = '339112 - Surgical and medical instrument manufacturing' WHERE LOWER(description) = 'surgical and medical instruments';
UPDATE ct.eio SET old_description = '339113 - Surgical appliance and supplies manufacturing' WHERE LOWER(description) = 'surgical appliances and supplies';
UPDATE ct.eio SET old_description = '335313 - Switchgear and switchboard apparatus manufacturing' WHERE LOWER(description) = 'switchgears and switchboard apparatus';
UPDATE ct.eio SET old_description = '334515 - Electricity and signal testing instruments manufacturing' WHERE LOWER(description) = 'testing instruments for electricity and signals';
UPDATE ct.eio SET old_description = '3122A0 - Tobacco product manufacturing' WHERE LOWER(description) = 'tobacco products';
UPDATE ct.eio SET old_description = '325620 - Toilet preparation manufacturing' WHERE LOWER(description) = 'toilet preparation';
UPDATE ct.eio SET old_description = '334514 - Totalizing fluid meters and counting devices manufacturing' WHERE LOWER(description) = 'totalizing fluid meters and counting devices';
UPDATE ct.eio SET old_description = '336214 - Travel trailer and camper manufacturing' WHERE LOWER(description) = 'trailers and campers for travel';
UPDATE ct.eio SET old_description = '336999 - All other transportation equipment manufacturing' WHERE LOWER(description) = 'transportation equipment (miscellaneous)';
UPDATE ct.eio SET old_description = '336212 - Truck trailer manufacturing' WHERE LOWER(description) = 'truck trailers';
UPDATE ct.eio SET old_description = '336120 - Heavy duty truck manufacturing' WHERE LOWER(description) = 'trucks (heavy duty)';
UPDATE ct.eio SET old_description = '336112 - Light truck and utility vehicle manufacturing' WHERE LOWER(description) = 'trucks (light) and utility vehicles';
UPDATE ct.eio SET old_description = '333611 - Turbine and turbine generator set units manufacturing' WHERE LOWER(description) = 'turbine and turbine generator set units';
UPDATE ct.eio SET old_description = 'S00402 - Used and secondhand goods' WHERE LOWER(description) = 'used and secondhand goods';
UPDATE ct.eio SET old_description = '33291A - Valve and fittings other than plumbing' WHERE LOWER(description) = 'valve and fittings other than plumbing';
UPDATE ct.eio SET old_description = '33331A - Vending, commercial, industrial, and office machinery manufacturing' WHERE LOWER(description) = 'vending, commercial, industrial, and office machinery';
UPDATE ct.eio SET old_description = '33451A - Watch, clock, and other measuring and controlling device manufacturing' WHERE LOWER(description) = 'watches, clocks, and other measuring and controlling devices';
UPDATE ct.eio SET old_description = '335930 - Wiring device manufacturing' WHERE LOWER(description) = 'wiring devices';
UPDATE ct.eio SET old_description = '321100 - Sawmills and wood preservation' WHERE LOWER(description) = 'wood (preserved)';
UPDATE ct.eio SET old_description = '32121A - Veneer and plywood manufacturing' WHERE LOWER(description) = 'wood (veneer and plywood)';
UPDATE ct.eio SET old_description = '321992 - Prefabricated wood building manufacturing' WHERE LOWER(description) = 'wood buildings (prefabricated)';
UPDATE ct.eio SET old_description = '33721A - Wood television, radio, and sewing machine cabinet manufacturing' WHERE LOWER(description) = 'wood cabinets for television, radio, sewing machines';
UPDATE ct.eio SET old_description = '321920 - Wood container and pallet manufacturing' WHERE LOWER(description) = 'wood containers and pallets';
UPDATE ct.eio SET old_description = '337110 - Wood kitchen cabinet and countertop manufacturing' WHERE LOWER(description) = 'wood kitchen cabinets and countertops';
UPDATE ct.eio SET old_description = '32121B - Engineered wood member and truss manufacturing' WHERE LOWER(description) = 'wood members and truss (engineered)';
UPDATE ct.eio SET old_description = '321999 - All other miscellaneous wood product manufacturing' WHERE LOWER(description) = 'wood products (miscellaneous)';
UPDATE ct.eio SET old_description = '321219 - Reconstituted wood product manufacturing' WHERE LOWER(description) = 'wood products (reconstituted)';
UPDATE ct.eio SET old_description = '321910 - Wood windows and doors and millwork' WHERE LOWER(description) = 'wood windows and doors and millwork';
UPDATE ct.eio SET old_description = '33131A - Alumina refining and primary aluminum production' WHERE LOWER(description) = 'aluminum (primary, includes refining)';
UPDATE ct.eio SET old_description = '331314 - Secondary smelting and alloying of aluminum' WHERE LOWER(description) = 'aluminum (secondary smelting and alloying)';
UPDATE ct.eio SET old_description = '33131B - Aluminum product manufacturing from purchased aluminum' WHERE LOWER(description) = 'aluminum products from purchased aluminium';
UPDATE ct.eio SET old_description = '332991 - Ball and roller bearing manufacturing' WHERE LOWER(description) = 'ball and roller bearings';
UPDATE ct.eio SET old_description = '331411 - Primary smelting and refining of copper' WHERE LOWER(description) = 'copper (primary, smelted and refined)';
UPDATE ct.eio SET old_description = '331420 - Copper rolling, drawing, extruding and alloying' WHERE LOWER(description) = 'copper (rolled, drawn, extruded and alloyed)';
UPDATE ct.eio SET old_description = '331510 - Ferrous metal foundries' WHERE LOWER(description) = 'ferrous metal castings';
UPDATE ct.eio SET old_description = '331110 - Iron and steel mills and ferroalloy manufacturing' WHERE LOWER(description) = 'iron, steel and ferroalloys';
UPDATE ct.eio SET old_description = '332430 - Metal can, box, and other metal container (light gauge) manufacturing' WHERE LOWER(description) = 'metal cans, boxes, and other metal containers (light gauge)';
UPDATE ct.eio SET old_description = '332320 - Ornamental and architectural metal products manufacturing' WHERE LOWER(description) = 'metal products (ornamental and architectural)';
UPDATE ct.eio SET old_description = '332420 - Metal tank (heavy gauge) manufacturing' WHERE LOWER(description) = 'metal tanks (heavy gauge)';
UPDATE ct.eio SET old_description = '33211A - All other forging, stamping, and sintering' WHERE LOWER(description) = 'metals (forged, stamped, and sintered)';
UPDATE ct.eio SET old_description = '332114 - Custom roll forming' WHERE LOWER(description) = 'metals (rolled forms)';
UPDATE ct.eio SET old_description = '33211B - Crown and closure manufacturing and metal stamping' WHERE LOWER(description) = 'metals (stamped, crown and closure)';
UPDATE ct.eio SET old_description = '331520 - Nonferrous metal foundries' WHERE LOWER(description) = 'nonferrous metal castings';
UPDATE ct.eio SET old_description = '331419 - Primary smelting and refining of nonferrous metal (except copper and aluminum)' WHERE LOWER(description) = 'nonferrous metal except copper and aluminum (includes primary smelting and refining)';
UPDATE ct.eio SET old_description = '331490 - Nonferrous metal (except copper and aluminum) rolling, drawing, extruding and alloying' WHERE LOWER(description) = 'nonferrous metals except copper and aluminum (rolled, drawn, extruded and alloyed)';
UPDATE ct.eio SET old_description = '33299C - Other fabricated metal manufacturing' WHERE LOWER(description) = 'other fabricated metals';
UPDATE ct.eio SET old_description = '332600 - Spring and wire product manufacturing' WHERE LOWER(description) = 'spring and wire products';
UPDATE ct.eio SET old_description = '331200 - Steel product manufacturing from purchased steel' WHERE LOWER(description) = 'steel products from purchased steel';
UPDATE ct.eio SET old_description = '332720 - Turned product and screw, nut, and bolt manufacturing' WHERE LOWER(description) = 'turned products, screws, nuts, and bolts';
UPDATE ct.eio SET old_description = '212100 - Coal mining' WHERE LOWER(description) = 'coal (mined)';
UPDATE ct.eio SET old_description = '212230 - Copper, nickel, lead, and zinc mining' WHERE LOWER(description) = 'copper, nickel, lead, and zinc (mined)';
UPDATE ct.eio SET old_description = '2122A0 - Gold, silver, and other metal ore mining' WHERE LOWER(description) = 'gold, silver, and other metal ore (mined)';
UPDATE ct.eio SET old_description = '212210 - Iron ore mining' WHERE LOWER(description) = 'iron ore (mined)';
UPDATE ct.eio SET old_description = '213111 - Drilling oil and gas wells' WHERE LOWER(description) = 'oil and gas (drilled wells)';
UPDATE ct.eio SET old_description = '211000 - Oil and gas extraction' WHERE LOWER(description) = 'oil and gas (extracted)';
UPDATE ct.eio SET old_description = '325510 - Paint and coating manufacturing' WHERE LOWER(description) = 'paints and coatings';
UPDATE ct.eio SET old_description = '325910 - Printing ink manufacturing' WHERE LOWER(description) = 'printing ink';
UPDATE ct.eio SET old_description = '325414 - Biological product (except diagnostic) manufacturing' WHERE LOWER(description) = 'biological products (except diagnostic)';
UPDATE ct.eio SET old_description = '325413 - In-vitro diagnostic substance manufacturing' WHERE LOWER(description) = 'in-vitro diagnostic substances';
UPDATE ct.eio SET old_description = '325411 - Medicinal and botanical manufacturing' WHERE LOWER(description) = 'medicinal and botanical products';
UPDATE ct.eio SET old_description = '325412 - Pharmaceutical preparation manufacturing' WHERE LOWER(description) = 'pharmaceutical preparations';
UPDATE ct.eio SET old_description = '325220 - Artificial and synthetic fibers and filaments manufacturing' WHERE LOWER(description) = 'fibers and filaments (artificial and synthetic)';
UPDATE ct.eio SET old_description = '333220 - Plastics and rubber industry machinery manufacturing' WHERE LOWER(description) = 'plastics and rubber industry machinery';
UPDATE ct.eio SET old_description = '326160 - Plastics bottle manufacturing' WHERE LOWER(description) = 'plastics bottles';
UPDATE ct.eio SET old_description = '325211 - Plastics material and resin manufacturing' WHERE LOWER(description) = 'plastics material and resin';
UPDATE ct.eio SET old_description = '326110 - Plastics packaging materials and unlaminated film and sheet manufacturing' WHERE LOWER(description) = 'plastics packaging materials and unlaminated films and sheets';
UPDATE ct.eio SET old_description = '326122 - Plastics pipe and pipe fitting manufacturing' WHERE LOWER(description) = 'plastics pipe and pipe fittings';
UPDATE ct.eio SET old_description = '326130 - Laminated plastics plate, sheet (except packaging), and shape manufacturing' WHERE LOWER(description) = 'plastics plates, sheets except packaging, and shapes (laminated)';
UPDATE ct.eio SET old_description = '32619A - Other plastics product manufacturing' WHERE LOWER(description) = 'plastics products (miscellaneous)';
UPDATE ct.eio SET old_description = '326121 - Unlaminated plastics profile shape manufacturing' WHERE LOWER(description) = 'plastics profile shapes (unlaminated)';
UPDATE ct.eio SET old_description = '326140 - Polystyrene foam product manufacturing' WHERE LOWER(description) = 'polystyrene foam products';
UPDATE ct.eio SET old_description = '326150 - Urethane and other foam product (except polystyrene) manufacturing' WHERE LOWER(description) = 'urethane and other foam products (except polystyrene)';
UPDATE ct.eio SET old_description = '322120 - Paper mills' WHERE LOWER(description) = 'paper';
UPDATE ct.eio SET old_description = '322291 - Sanitary paper product manufacturing' WHERE LOWER(description) = 'paper (sanitary)';
UPDATE ct.eio SET old_description = '32222B - All other paper bag and coated and treated paper manufacturing' WHERE LOWER(description) = 'paper bags and coated and treated paper';
UPDATE ct.eio SET old_description = '322299 - All other converted paper product manufacturing' WHERE LOWER(description) = 'paper products (converted)';
UPDATE ct.eio SET old_description = '32222A - Coated and laminated paper, packaging paper and plastics film manufacturing' WHERE LOWER(description) = 'paper, packaging paper and plastics film (coated and laminated)';
UPDATE ct.eio SET old_description = '322130 - Paperboard mills' WHERE LOWER(description) = 'paperboard';
UPDATE ct.eio SET old_description = '322210 - Paperboard container manufacturing' WHERE LOWER(description) = 'paperboard containers';
UPDATE ct.eio SET old_description = '322110 - Pulp mills' WHERE LOWER(description) = 'pulp';
UPDATE ct.eio SET old_description = '113300 - Logging' WHERE LOWER(description) = 'wood (logged)';
UPDATE ct.eio SET old_description = '325212 - Synthetic rubber manufacturing' WHERE LOWER(description) = 'rubber (synthetic)';
UPDATE ct.eio SET old_description = '326220 - Rubber and plastics hoses and belting manufacturing' WHERE LOWER(description) = 'rubber and plastics hoses and beltings';
UPDATE ct.eio SET old_description = '326290 - Other rubber product manufacturing' WHERE LOWER(description) = 'rubber products (miscellaneous)';
UPDATE ct.eio SET old_description = '326210 - Tire manufacturing' WHERE LOWER(description) = 'tires';
UPDATE ct.eio SET old_description = '721A00 - Other accommodations' WHERE LOWER(description) = 'accommodation services';
UPDATE ct.eio SET old_description = '541200 - Accounting, tax preparation, bookkeeping, and payroll services' WHERE LOWER(description) = 'accounting, tax preparation, bookkeeping, and payroll services';
UPDATE ct.eio SET old_description = '541800 - Advertising and related services' WHERE LOWER(description) = 'advertising and related services';
UPDATE ct.eio SET old_description = '115000 - Support activities for agriculture and forestry' WHERE LOWER(description) = 'agriculture and forestry support activities';
UPDATE ct.eio SET old_description = '481000 - Air transportation' WHERE LOWER(description) = 'air transportation services';
UPDATE ct.eio SET old_description = '713B00 - Other amusement and recreation industries' WHERE LOWER(description) = 'amusement and recreation industries';
UPDATE ct.eio SET old_description = '713A00 - Amusement parks, arcades, and gambling industries' WHERE LOWER(description) = 'amusement parks, arcades, and gambling industries';
UPDATE ct.eio SET old_description = '541300 - Architectural, engineering, and related services' WHERE LOWER(description) = 'architectural, engineering, and related services';
UPDATE ct.eio SET old_description = '532100 - Automotive equipment rental and leasing' WHERE LOWER(description) = 'automotive equipment rental and leasing services';
UPDATE ct.eio SET old_description = '8111A0 - Automotive repair and maintenance, except car washes' WHERE LOWER(description) = 'automotive repair and maintenance, except car washes';
UPDATE ct.eio SET old_description = '511130 - Book publishers' WHERE LOWER(description) = 'book publishers';
UPDATE ct.eio SET old_description = '713950 - Bowling centers' WHERE LOWER(description) = 'bowling centers';
UPDATE ct.eio SET old_description = '561700 - Services to buildings and dwellings' WHERE LOWER(description) = 'buildings and dwellings services';
UPDATE ct.eio SET old_description = '561400 - Business support services' WHERE LOWER(description) = 'business support services';
UPDATE ct.eio SET old_description = '515200 - Cable and other subscription programming' WHERE LOWER(description) = 'cable and other subscription programming services';
UPDATE ct.eio SET old_description = '811192 - Car washes' WHERE LOWER(description) = 'car wash services';
UPDATE ct.eio SET old_description = '624400 - Child day care services' WHERE LOWER(description) = 'child day care services';
UPDATE ct.eio SET old_description = '813B00 - Civic, social, professional, and similar organizations' WHERE LOWER(description) = 'civic, social, professional, and similar organizations';
UPDATE ct.eio SET old_description = '532400 - Commercial and industrial machinery and equipment rental and leasing' WHERE LOWER(description) = 'commercial and industrial machinery and equipment rental and leasing services';
UPDATE ct.eio SET old_description = '811300 - Commercial and industrial machinery and equipment repair and maintenance' WHERE LOWER(description) = 'commercial and industrial machinery and equipment repair and maintenance services';
UPDATE ct.eio SET old_description = '624200 - Community food, housing, and other relief services, including rehabilitation services' WHERE LOWER(description) = 'community food, housing, and other relief services, including rehabilitation services';
UPDATE ct.eio SET old_description = '54151A - Other computer related services, including facilities management' WHERE LOWER(description) = 'computer related services, including facilities management';
UPDATE ct.eio SET old_description = '541512 - Computer systems design services' WHERE LOWER(description) = 'computer systems design services';
UPDATE ct.eio SET old_description = '492000 - Couriers and messengers' WHERE LOWER(description) = 'couriers and messengers services';
UPDATE ct.eio SET old_description = '541511 - Custom computer programming services' WHERE LOWER(description) = 'custom computer programming services';
UPDATE ct.eio SET old_description = '518200 - Data processing, hosting, and related services' WHERE LOWER(description) = 'data processing, hosting, and related services';
UPDATE ct.eio SET old_description = '812200 - Death care services' WHERE LOWER(description) = 'death care services';
UPDATE ct.eio SET old_description = '5111A0 - Directory, mailing list, and other publishers' WHERE LOWER(description) = 'directory, mailing list, and other publishers';
UPDATE ct.eio SET old_description = '812300 - Dry-cleaning and laundry services' WHERE LOWER(description) = 'dry-cleaning and laundry services';
UPDATE ct.eio SET old_description = '611B00 - Other educational services' WHERE LOWER(description) = 'educational services';
UPDATE ct.eio SET old_description = '811200 - Electronic and precision equipment repair and maintenance' WHERE LOWER(description) = 'electronic and precision equipment repair and maintenance services';
UPDATE ct.eio SET old_description = '611100 - Elementary and secondary schools' WHERE LOWER(description) = 'elementary and secondary schools';
UPDATE ct.eio SET old_description = '561300 - Employment services' WHERE LOWER(description) = 'employment services';
UPDATE ct.eio SET old_description = '5416A0 - Environmental and other technical consulting services' WHERE LOWER(description) = 'environmental and other technical consulting services';
UPDATE ct.eio SET old_description = '561200 - Facilities support services' WHERE LOWER(description) = 'facilities support services';
UPDATE ct.eio SET old_description = 'S00101 - Federal electric utilities' WHERE LOWER(description) = 'federal government electric utilities';
UPDATE ct.eio SET old_description = '713940 - Fitness and recreational sports centers' WHERE LOWER(description) = 'fitness and recreational sports centers';
UPDATE ct.eio SET old_description = '722000 - Food services and drinking places' WHERE LOWER(description) = 'food services and drinking places';
UPDATE ct.eio SET old_description = '525000 - Funds, trusts, and other financial vehicles' WHERE LOWER(description) = 'funds, trusts, and other financial vehicles';
UPDATE ct.eio SET old_description = '532A00 - General and consumer goods rental except video tapes and discs' WHERE LOWER(description) = 'general and consumer goods rental except video tapes and discs';
UPDATE ct.eio SET old_description = 'S00500 - General Federal defense government services' WHERE LOWER(description) = 'general federal defense government services';
UPDATE ct.eio SET old_description = 'S00600 - General Federal nondefense government services' WHERE LOWER(description) = 'general federal nondefense government services';
UPDATE ct.eio SET old_description = 'S00700 - General state and local government services' WHERE LOWER(description) = 'general state and local government services';
UPDATE ct.eio SET old_description = 'S00102 - Other Federal Government enterprises' WHERE LOWER(description) = 'government enterprises';
UPDATE ct.eio SET old_description = '813A00 - Grantmaking, giving, and social advocacy organizations' WHERE LOWER(description) = 'grantmaking, giving, and social advocacy organizations';
UPDATE ct.eio SET old_description = '621600 - Home health care services' WHERE LOWER(description) = 'home health care services';
UPDATE ct.eio SET old_description = '622000 - Hospitals' WHERE LOWER(description) = 'hospital services';
UPDATE ct.eio SET old_description = '7211A0 - Hotels and motels, including casino hotels' WHERE LOWER(description) = 'hotels and motels, including casino hotels';
UPDATE ct.eio SET old_description = '114200 - Hunting and trapping' WHERE LOWER(description) = 'hunting and trapping activities';
UPDATE ct.eio SET old_description = '711500 - Independent artists, writers, and performers' WHERE LOWER(description) = 'independent artists, writers, and performers';
UPDATE ct.eio SET old_description = '624A00 - Individual and family services' WHERE LOWER(description) = 'individual and family services';
UPDATE ct.eio SET old_description = '519100 - Other information services' WHERE LOWER(description) = 'information services';
UPDATE ct.eio SET old_description = '524200 - Insurance agencies, brokerages, and related activities' WHERE LOWER(description) = 'insurance agencies, brokerages, and related activities';
UPDATE ct.eio SET old_description = '524100 - Insurance carriers' WHERE LOWER(description) = 'insurance carriers';
UPDATE ct.eio SET old_description = '516110 - Internet publishing and broadcasting' WHERE LOWER(description) = 'internet publishing and broadcasting services';
UPDATE ct.eio SET old_description = '518100 - Internet service providers and web search portals' WHERE LOWER(description) = 'internet service providers and web search portals';
UPDATE ct.eio SET old_description = '561600 - Investigation and security services' WHERE LOWER(description) = 'investigation and security services';
UPDATE ct.eio SET old_description = '611A00 - Junior colleges, colleges, universities, and professional schools' WHERE LOWER(description) = 'junior colleges, colleges, universities, and professional schools';
UPDATE ct.eio SET old_description = '541100 - Legal services' WHERE LOWER(description) = 'legal services';
UPDATE ct.eio SET old_description = '533000 - Lessors of nonfinancial intangible assets' WHERE LOWER(description) = 'lessors of nonfinancial intangible assets';
UPDATE ct.eio SET old_description = '550000 - Management of companies and enterprises' WHERE LOWER(description) = 'management of companies and enterprises';
UPDATE ct.eio SET old_description = '541610 - Management, scientific, and technical consulting services' WHERE LOWER(description) = 'management, scientific, and technical consulting services';
UPDATE ct.eio SET old_description = '621B00 - Medical and diagnostic labs and outpatient and other ambulatory care services' WHERE LOWER(description) = 'medical and diagnostic labs and outpatient and other ambulatory care services';
UPDATE ct.eio SET old_description = '21311A - Support activities for other mining' WHERE LOWER(description) = 'mining support activities';
UPDATE ct.eio SET old_description = '52A000 - Monetary authorities and depository credit intermediation' WHERE LOWER(description) = 'monetary authorities and depository credit intermediation';
UPDATE ct.eio SET old_description = '512100 - Motion picture and video industries' WHERE LOWER(description) = 'motion picture and video industries';
UPDATE ct.eio SET old_description = '712000 - Museums, historical sites, zoos, and parks' WHERE LOWER(description) = 'museums, historical sites, zoos, and parks';
UPDATE ct.eio SET old_description = '511110 - Newspaper publishers' WHERE LOWER(description) = 'newspaper publishers';
UPDATE ct.eio SET old_description = '522A00 - Nondepository credit intermediation and related activities' WHERE LOWER(description) = 'nondepository credit intermediation and related activities';
UPDATE ct.eio SET old_description = '230301 - Nonresidential maintenance and repair' WHERE LOWER(description) = 'nonresidential maintenance and repair services';
UPDATE ct.eio SET old_description = '623000 - Nursing and residential care facilities' WHERE LOWER(description) = 'nursing and residential care services';
UPDATE ct.eio SET old_description = '561100 - Office administrative services' WHERE LOWER(description) = 'office administrative services';
UPDATE ct.eio SET old_description = '213112 - Support activities for oil and gas operations' WHERE LOWER(description) = 'oil and gas operations support activities';
UPDATE ct.eio SET old_description = 'S00203 - Other state and local government enterprises' WHERE LOWER(description) = 'other state and local government enterprises';
UPDATE ct.eio SET old_description = '561900 - Other support services' WHERE LOWER(description) = 'other support services';
UPDATE ct.eio SET old_description = 'S00800 - Owner-occupied dwellings' WHERE LOWER(description) = 'owner-occupied dwellings';
UPDATE ct.eio SET old_description = '711100 - Performing arts companies' WHERE LOWER(description) = 'performing arts services';
UPDATE ct.eio SET old_description = '511120 - Periodical publishers' WHERE LOWER(description) = 'periodical publishers';
UPDATE ct.eio SET old_description = '811400 - Personal and household goods repair and maintenance' WHERE LOWER(description) = 'personal and household goods repair and maintenance services';
UPDATE ct.eio SET old_description = '812100 - Personal care services' WHERE LOWER(description) = 'personal care services';
UPDATE ct.eio SET old_description = '812900 - Other personal services' WHERE LOWER(description) = 'personal services';
UPDATE ct.eio SET old_description = '541920 - Photographic services' WHERE LOWER(description) = 'photographic services';
UPDATE ct.eio SET old_description = '621A00 - Offices of physicians, dentists, and other health practitioners' WHERE LOWER(description) = 'physicians, dentists, and other health practitioners';
UPDATE ct.eio SET old_description = '486000 - Pipeline transportation' WHERE LOWER(description) = 'pipeline transportation services';
UPDATE ct.eio SET old_description = '491000 - Postal service' WHERE LOWER(description) = 'postal services';
UPDATE ct.eio SET old_description = '323110 - Printing' WHERE LOWER(description) = 'printing services';
UPDATE ct.eio SET old_description = '323120 - Support activities for printing' WHERE LOWER(description) = 'printing support activities';
UPDATE ct.eio SET old_description = '814000 - Private households' WHERE LOWER(description) = 'private households';
UPDATE ct.eio SET old_description = '5419A0 - All other miscellaneous professional, scientific, and technical services' WHERE LOWER(description) = 'professional, scientific, and technical services (miscellaneous)';
UPDATE ct.eio SET old_description = '711A00 - Promoters of performing arts and sports and agents for public figures' WHERE LOWER(description) = 'promoters of performing arts and sports and agents for public figures';
UPDATE ct.eio SET old_description = '515100 - Radio and television broadcasting' WHERE LOWER(description) = 'radio and television broadcasting services';
UPDATE ct.eio SET old_description = '482000 - Rail transportation' WHERE LOWER(description) = 'rail transportation services';
UPDATE ct.eio SET old_description = '531000 - Real estate' WHERE LOWER(description) = 'real estate services';
UPDATE ct.eio SET old_description = '813100 - Religious organizations' WHERE LOWER(description) = 'religious organizations';
UPDATE ct.eio SET old_description = '230302 - Residential maintenance and repair' WHERE LOWER(description) = 'residential maintenance and repair services';
UPDATE ct.eio SET old_description = '4A0000 - Retail trade' WHERE LOWER(description) = 'retail trade services';
UPDATE ct.eio SET old_description = '48A000 - Scenic and sightseeing transportation and support activities for transportation' WHERE LOWER(description) = 'scenic and sightseeing transportation and support activities';
UPDATE ct.eio SET old_description = '541700 - Scientific research and development services' WHERE LOWER(description) = 'scientific research and development services';
UPDATE ct.eio SET old_description = '523000 - Securities, commodity contracts, investments, and related activities' WHERE LOWER(description) = 'securities, commodity contracts, investments, and related activities';
UPDATE ct.eio SET old_description = '511200 - Software publishers' WHERE LOWER(description) = 'software publishers';
UPDATE ct.eio SET old_description = '33461A - Software, audio, and video media reproducing' WHERE LOWER(description) = 'software, audio, and video media reproduction services';
UPDATE ct.eio SET old_description = '512200 - Sound recording industries' WHERE LOWER(description) = 'sound recording industries';
UPDATE ct.eio SET old_description = '541400 - Specialized design services' WHERE LOWER(description) = 'specialized design services';
UPDATE ct.eio SET old_description = '711200 - Spectator sports' WHERE LOWER(description) = 'spectator sports';
UPDATE ct.eio SET old_description = 'S00202 - State and local government electric utilities' WHERE LOWER(description) = 'state and local government electric utilities';
UPDATE ct.eio SET old_description = 'S00201 - State and local government passenger transit' WHERE LOWER(description) = 'state and local government passenger transit';
UPDATE ct.eio SET old_description = '517000 - Telecommunications' WHERE LOWER(description) = 'telecommunications services';
UPDATE ct.eio SET old_description = '485000 - Transit and ground passenger transportation' WHERE LOWER(description) = 'transit and ground passenger transportation services';
UPDATE ct.eio SET old_description = '561500 - Travel arrangement and reservation services' WHERE LOWER(description) = 'travel arrangement and reservation services';
UPDATE ct.eio SET old_description = '484000 - Truck transportation' WHERE LOWER(description) = 'truck transportation services';
UPDATE ct.eio SET old_description = '541940 - Veterinary services' WHERE LOWER(description) = 'veterinary services';
UPDATE ct.eio SET old_description = '532230 - Video tape and disc rental' WHERE LOWER(description) = 'video tape and disc rental services';
UPDATE ct.eio SET old_description = '493000 - Warehousing and storage' WHERE LOWER(description) = 'warehousing and storage services';
UPDATE ct.eio SET old_description = '562000 - Waste management and remediation services' WHERE LOWER(description) = 'waste management and remediation services';
UPDATE ct.eio SET old_description = '483000 - Water transportation' WHERE LOWER(description) = 'water transportation services';
UPDATE ct.eio SET old_description = '420000 - Wholesale trade' WHERE LOWER(description) = 'wholesale trade services';
UPDATE ct.eio SET old_description = '315210 - Cut and sew apparel contractors' WHERE LOWER(description) = 'apparel (cut and sewn)';
UPDATE ct.eio SET old_description = '315290 - Other cut and sew apparel manufacturing' WHERE LOWER(description) = 'apparel (miscellaneous)';
UPDATE ct.eio SET old_description = '315900 - Apparel accessories and other apparel manufacturing' WHERE LOWER(description) = 'apparel accessories and other apparel';
UPDATE ct.eio SET old_description = '315220 - Mens and boys cut and sew apparel manufacturing' WHERE LOWER(description) = 'apparel for men and boys (cut and sewn)';
UPDATE ct.eio SET old_description = '315230 - Womens and girls cut and sew apparel manufacturing' WHERE LOWER(description) = 'apparel for women and girls (cut and sewn)';
UPDATE ct.eio SET old_description = '313210 - Broadwoven fabric mills' WHERE LOWER(description) = 'broadwoven fabric';
UPDATE ct.eio SET old_description = '314110 - Carpet and rug mills' WHERE LOWER(description) = 'carpet and rugs';
UPDATE ct.eio SET old_description = '314120 - Curtain and linen mills' WHERE LOWER(description) = 'curtains and linen';
UPDATE ct.eio SET old_description = '313230 - Nonwoven fabric mills' WHERE LOWER(description) = 'fabric (nonwoven)';
UPDATE ct.eio SET old_description = '313320 - Fabric coating mills' WHERE LOWER(description) = 'fabric coating';
UPDATE ct.eio SET old_description = '313100 - Fiber, yarn, and thread mills' WHERE LOWER(description) = 'fiber, yarn, and threads';
UPDATE ct.eio SET old_description = '313240 - Knit fabric mills' WHERE LOWER(description) = 'knit fabric';
UPDATE ct.eio SET old_description = '315100 - Apparel knitting mills' WHERE LOWER(description) = 'knitted apparel';
UPDATE ct.eio SET old_description = '313220 - Narrow fabric mills and schiffli machine embroidery' WHERE LOWER(description) = 'narrow fabric and schiffli machine embroidery';
UPDATE ct.eio SET old_description = '314910 - Textile bag and canvas mills' WHERE LOWER(description) = 'textile bags and canvas';
UPDATE ct.eio SET old_description = '314990 - All other textile product mills' WHERE LOWER(description) = 'textile products (miscellaneous)';
UPDATE ct.eio SET old_description = '313310 - Textile and fabric finishing mills' WHERE LOWER(description) = 'textiles (including fabric finishing)';
UPDATE ct.eio SET old_description = '221100 - Electric power generation, transmission, and distribution' WHERE LOWER(description) = 'electric power generation, transmission, and distribution';
UPDATE ct.eio SET old_description = '221200 - Natural gas distribution' WHERE LOWER(description) = 'natural gas distribution';
UPDATE ct.eio SET old_description = '324110 - Petroleum refineries' WHERE LOWER(description) = 'petroleum refineries';
UPDATE ct.eio SET old_description = '221300 - Water, sewage and other systems' WHERE LOWER(description) = 'water, sewage and other systems';
UPDATE ct.eio SET old_description = 'S00900 - Rest of the world adjustment' WHERE LOWER(description) = 'rest of the world adjustment';
UPDATE ct.eio SET old_description = 'S00300 - Noncomparable imports' WHERE LOWER(description) = 'noncomparable imports';

SELECT count(*) FROM ct.eio WHERE old_description is null;

@update_tail
