-- Please update version.sql too -- this keeps clean builds in sync
define version=575
@update_header

DECLARE
	v_version	version.db_version%TYPE;
	v_required	version.db_version%TYPE := 85;
BEGIN
	SELECT db_version INTO v_version FROM actions.version;
	IF v_version < v_required THEN
		RAISE_APPLICATION_ERROR(-20001, '========= UPDATE '||&version||' CANNOT BE APPLIED TO AN ***ACTIONS*** DATABASE OF VERSION '||v_version||' - VERSION '||v_required||' REQUIRED (cvs\csr\actions\changes) =======');
	END IF;
END;
/

-- 
-- TABLE: SELECTED_AXIS_TASK 
--
CREATE TABLE SELECTED_AXIS_TASK(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    AXIS_MEMBER_ID          NUMBER(10, 0)    NOT NULL,
    TASK_SID                NUMBER(10, 0)    NOT NULL,
    ACTION_TAG_ID           NUMBER(10, 0)    NOT NULL,
    REPORTING_PERIOD_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_SELECTED_AXIS_TASK PRIMARY KEY (APP_SID, AXIS_MEMBER_ID, TASK_SID, ACTION_TAG_ID, REPORTING_PERIOD_SID)
)
;

alter table CSR.AXIS_MEMBER add constraint UK_AX_MEM_PRI_ACT_TAG UNIQUE (APP_SID, AXIS_MEMBER_ID, PRIMARY_ACTION_TAG_ID)
using index tablespace indx;

ALTER TABLE SELECTED_AXIS_TASK ADD CONSTRAINT FK_AXIS_MEM_SEL_AX_TASK 
    FOREIGN KEY (APP_SID, AXIS_MEMBER_ID, ACTION_TAG_ID)
    REFERENCES CSR.AXIS_MEMBER(APP_SID, AXIS_MEMBER_ID, PRIMARY_ACTION_TAG_ID)
;

ALTER TABLE SELECTED_AXIS_TASK ADD CONSTRAINT FK_REP_PERIOD_SEL_AX_TASK 
    FOREIGN KEY (APP_SID, REPORTING_PERIOD_SID)
    REFERENCES REPORTING_PERIOD(APP_SID, REPORTING_PERIOD_SID)
;

ALTER TABLE SELECTED_AXIS_TASK ADD CONSTRAINT FK_TASK_TAG_SEL_AX_TASK 
    FOREIGN KEY (APP_SID, TASK_SID, ACTION_TAG_ID)
    REFERENCES ACTIONS.TASK_TAG(APP_SID, TASK_SID, TAG_ID)
;


@update_tail
