-- Please update version.sql too -- this keeps clean builds in sync
define version=1480
@update_header

CREATE TABLE CSR.REGION_METRIC_REGION(
    APP_SID           NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    IND_SID           NUMBER(10, 0)    NOT NULL,
    REGION_SID        NUMBER(10, 0)    NOT NULL,
    SOURCE_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK1538 PRIMARY KEY (APP_SID, IND_SID, REGION_SID)
);

DROP INDEX CSR.IX_REGION_RMETRIC_VAL;
ALTER TABLE CSR.REGION_METRIC_VAL DROP CONSTRAINT FK_REGION_RMETRIC_VAL;

BEGIN
	INSERT INTO csr.region_metric_region (app_sid, ind_sid, region_sid, source_type_id)
		SELECT DISTINCT app_sid, ind_sid, region_sid, 14 /*csr_data_pkg.SOURCE_TYPE_REGION_METRIC*/
		  FROM csr.region_metric_val;
END;
/

ALTER TABLE CSR.REGION_METRIC_VAL ADD CONSTRAINT FK_RMETRICR_RMETRIC_VAL 
    FOREIGN KEY (APP_SID, IND_SID, REGION_SID)
    REFERENCES CSR.REGION_METRIC_REGION(APP_SID, IND_SID, REGION_SID)
;

ALTER TABLE CSR.REGION_METRIC_REGION ADD CONSTRAINT FK_RMETRIC_RMETRICR 
    FOREIGN KEY (APP_SID, IND_SID)
    REFERENCES CSR.REGION_METRIC(APP_SID, IND_SID)
;

ALTER TABLE CSR.REGION_METRIC_REGION ADD CONSTRAINT FK_REGION_RMETRICR 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.REGION_METRIC_REGION ADD CONSTRAINT FK_SOURCE_RMETRIC_VAL 
    FOREIGN KEY (SOURCE_TYPE_ID)
    REFERENCES CSR.SOURCE_TYPE(SOURCE_TYPE_ID)
;

CREATE INDEX CSR.IX_RMETRICR_RMETRIC_VAL ON CSR.REGION_METRIC_VAL (APP_SID, IND_SID, REGION_SID);
CREATE INDEX CSR.IX_RMETRIC_RMETRICR ON CSR.REGION_METRIC_REGION (APP_SID, IND_SID);
CREATE INDEX CSR.IX_REGION_RMETRICR ON CSR.REGION_METRIC_REGION (APP_SID, REGION_SID);
CREATE INDEX CSR.FK_SOURCE_RMETRIC_VAL ON CSR.REGION_METRIC_REGION (SOURCE_TYPE_ID);

BEGIN
	dbms_rls.add_policy(
		object_schema   => 'CSR',
		object_name     => 'REGION_METRIC_REGION',
		policy_name     => 'REGION_METRIC_REGION_POLICY',
		function_schema => 'CSR',
		policy_function => 'appSidCheck',
		statement_types => 'select, insert, update, delete',
		update_check	=> true,
		policy_type     => dbms_rls.context_sensitive );
END;
/

@../region_metric_pkg
@../region_metric_body

@update_tail

