-- Please update version.sql too -- this keeps clean builds in sync
define version=1515
@update_header


INSERT INTO CSR.region_type (region_type, label, class_name) VALUES(9, 'Space', 'CSRTenantRegion');

ALTER TABLE CSR.SPACE_TYPE_REGION_METRIC ADD (REGION_TYPE NUMBER(2) DEFAULT 9 NOT NULL);

ALTER TABLE CSR.SPACE_TYPE_REGION_METRIC ADD CONSTRAINT FK_SP_TYP_RG_MET_RG_TYP_MET
    FOREIGN KEY (APP_SID, REGION_TYPE, IND_SID)
    REFERENCES CSR.REGION_TYPE_METRIC(APP_SID, REGION_TYPE, IND_SID);


-- make these two deferred
ALTER TABLE CSR.REGION_METRIC_REGION DROP CONSTRAINT FK_RMETRIC_RMETRICR;

ALTER TABLE CSR.REGION_METRIC_REGION ADD CONSTRAINT FK_RMETRIC_RMETRICR 
    FOREIGN KEY (APP_SID, IND_SID, MEASURE_SID)
    REFERENCES CSR.REGION_METRIC(APP_SID, IND_SID, MEASURE_SID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE CSR.REGION_METRIC DROP CONSTRAINT FK_INDM_REGION_METRIC;

ALTER TABLE CSR.REGION_METRIC ADD CONSTRAINT FK_INDM_REGION_METRIC 
    FOREIGN KEY (APP_SID, IND_SID, MEASURE_SID)
    REFERENCES CSR.IND(APP_SID, IND_SID, MEASURE_SID)
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE CSR.SPACE DROP CONSTRAINT FK_SPACE_SPACE_TYPE;
 
ALTER TABLE CSR.SPACE ADD (
    PROPERTY_REGION_SID    NUMBER(10, 0),
    PROPERTY_TYPE_ID       NUMBER(10, 0)
);

BEGIN
	FOR r IN (
		SELECT p.region_sid property_region_sid, p.property_type_id, s.region_sid
		  FROM csr.property p
		  	JOIN csr.region r ON p.region_sid = r.parent_sid
		  	JOIN csr.space s ON r.region_sid = s.region_sid
	)
	LOOP
		UPDATE csr.space
		   SET property_region_sid = r.property_region_sid,
		   	property_type_id = r.property_type_id
		 WHERE region_sid = r.region_sid;
	END LOOP;
END;
/

ALTER TABLE CSR.SPACE MODIFY PROPERTY_REGION_SID NOT NULL;
ALTER TABLE CSR.SPACE MODIFY PROPERTY_TYPE_ID NOT NULL;


ALTER TABLE CSR.PROPERTY ADD CONSTRAINT UK_PROPERTY  UNIQUE (APP_SID, REGION_SID, PROPERTY_TYPE_ID);

ALTER TABLE CSR.SPACE ADD CONSTRAINT FK_PROPERTY_SPACE 
    FOREIGN KEY (APP_SID, PROPERTY_REGION_SID, PROPERTY_TYPE_ID)
    REFERENCES CSR.PROPERTY(APP_SID, REGION_SID, PROPERTY_TYPE_ID);
 
ALTER TABLE CSR.SPACE ADD CONSTRAINT FK_PRP_TYP_SPC_TYP_SPC 
    FOREIGN KEY (APP_SID, PROPERTY_TYPE_ID, SPACE_TYPE_ID)
    REFERENCES CSR.PROPERTY_TYPE_SPACE_TYPE(APP_SID, PROPERTY_TYPE_ID, SPACE_TYPE_ID);
 
CREATE OR REPLACE PACKAGE CSR.region_metric_pkg
AS
END;
/

GRANT EXECUTE ON csr.region_metric_pkg TO WEB_USER;

@..\csr_data_pkg
@..\space_pkg
@..\property_pkg
@..\region_metric_pkg

@..\csr_data_body
@..\space_body
@..\property_body
@..\region_metric_body

@update_tail