-- Please update version.sql too -- this keeps clean builds in sync
define version=3168
define minor_version=7
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CSR.ENHESA_ERROR_LOG(
	APP_SID				NUMBER(10, 0) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	ERROR_LOG_ID		NUMBER(10) NOT NULL,
	ERROR_DTM			DATE NOT NULL,
	ERROR_MESSAGE		VARCHAR2(255) NOT NULL,
	STACK_TRACE			CLOB,
	CONSTRAINT PK_ENHESA_ERROR_LOG_ID PRIMARY KEY (APP_SID, ERROR_LOG_ID)
);

CREATE SEQUENCE CSR.ENHESA_ERROR_LOG_ID_SEQ;

CREATE TABLE CSRIMP.MAP_ENHESA_ERROR_LOG (
	CSRIMP_SESSION_ID				NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_ERROR_LOG_ID				NUMBER(10) NOT NULL,
	NEW_ERROR_LOG_ID				NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_ENHESA_ERROR_LOG PRIMARY KEY (CSRIMP_SESSION_ID, OLD_ERROR_LOG_ID),
	CONSTRAINT UK_MAP_ENHESA_ERROR_LOG UNIQUE (CSRIMP_SESSION_ID, NEW_ERROR_LOG_ID),
    CONSTRAINT FK_MAP_ENHESA_ERROR_LOG FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.ENHESA_ERROR_LOG(
	CSRIMP_SESSION_ID	NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ERROR_LOG_ID		NUMBER(10) NOT NULL,
	ERROR_DTM			DATE NOT NULL,
	ERROR_MESSAGE		VARCHAR2(255) NOT NULL,
	STACK_TRACE			CLOB,
	CONSTRAINT PK_ENHESA_ERROR_LOG_ID PRIMARY KEY (CSRIMP_SESSION_ID, ERROR_LOG_ID)
);

-- Alter tables
ALTER TABLE CSR.ENHESA_OPTIONS ADD (
	PACKAGES_IMPORTED	NUMBER(10) DEFAULT 0 NOT NULL,
	PACKAGES_TOTAL		NUMBER(10) DEFAULT 0 NOT NULL,
	ITEMS_IMPORTED		NUMBER(10) DEFAULT 0 NOT NULL,
	ITEMS_TOTAL			NUMBER(10) DEFAULT 0 NOT NULL,
	LINKS_CREATED		NUMBER(10) DEFAULT 0 NOT NULL,
	LINKS_TOTAL			NUMBER(10) DEFAULT 0 NOT NULL
);

ALTER TABLE CSRIMP.ENHESA_OPTIONS ADD (
	PACKAGES_IMPORTED	NUMBER(10) DEFAULT 0 NOT NULL,
	PACKAGES_TOTAL		NUMBER(10) DEFAULT 0 NOT NULL,
	ITEMS_IMPORTED		NUMBER(10) DEFAULT 0 NOT NULL,
	ITEMS_TOTAL			NUMBER(10) DEFAULT 0 NOT NULL,
	LINKS_CREATED		NUMBER(10) DEFAULT 0 NOT NULL,
	LINKS_TOTAL			NUMBER(10) DEFAULT 0 NOT NULL
);

-- *** Grants ***
GRANT SELECT, INSERT, UPDATE ON csr.enhesa_error_log TO csrimp;
GRANT SELECT ON csr.enhesa_error_log_id_seq TO csrimp;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_error_log TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.map_enhesa_error_log TO tool_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../compliance_pkg
@../schema_pkg

@../compliance_body
@../csrimp/imp_body
@../schema_body

@update_tail
