-- Please update version.sql too -- this keeps clean builds in sync
define version=3181
define minor_version=12
@update_header

-- *** DDL ***
-- Create tables

CREATE SEQUENCE CSR.COOKIE_POLICY_CONSENT_ID_SEQ;

CREATE TABLE CSR.COOKIE_POLICY_CONSENT(
	APP_SID						NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	COOKIE_POLICY_CONSENT_ID	NUMBER(10, 0)	NOT NULL,
	CSR_USER_SID				NUMBER(10, 0)	NOT NULL,
	CREATED_DTM 				DATE			DEFAULT SYSDATE NOT NULL,
	ACCEPTED					NUMBER(1),
	CHECK 	(ACCEPTED IN (0, 1)),
	CONSTRAINT PK_COOKIE_POLICY_CONSENT PRIMARY KEY (APP_SID, COOKIE_POLICY_CONSENT_ID)
);

ALTER TABLE CSR.COOKIE_POLICY_CONSENT ADD CONSTRAINT FK_COOKIE_POLICY_CONSENT_USER
    FOREIGN KEY (APP_SID, CSR_USER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

CREATE INDEX CSR.IX_COOKIE_POLICY_CONSENT_USR ON CSR.COOKIE_POLICY_CONSENT(APP_SID, CSR_USER_SID);

--csrimp
CREATE TABLE CSRIMP.COOKIE_POLICY_CONSENT (
	CSRIMP_SESSION_ID			NUMBER(10)      DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    COOKIE_POLICY_CONSENT_ID	NUMBER(10, 0)	NOT NULL,
    CSR_USER_SID				NUMBER(10, 0)	NOT NULL,
    CREATED_DTM 				DATE			NOT NULL,
    ACCEPTED					NUMBER(1),
    CHECK (ACCEPTED IN (0, 1)),
    CONSTRAINT PK_COOKIE_POLICY_CONSENT PRIMARY KEY (CSRIMP_SESSION_ID, COOKIE_POLICY_CONSENT_ID),
    CONSTRAINT FK_COOKIE_POLICY_CONSENT_IS FOREIGN KEY
    	(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
    	ON DELETE CASCADE
);

-- Map tables
CREATE TABLE CSRIMP.MAP_COOKIE_POLICY_CONSEN (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_COOKIE_POLICY_CONSENT_ID NUMBER(10) NOT NULL,
	NEW_COOKIE_POLICY_CONSENT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_COOKIE_POLICY_CONSEN PRIMARY KEY (CSRIMP_SESSION_ID, OLD_COOKIE_POLICY_CONSENT_ID) USING INDEX,
	CONSTRAINT UK_MAP_COOKIE_POLICY_CONSEN UNIQUE (CSRIMP_SESSION_ID, NEW_COOKIE_POLICY_CONSENT_ID) USING INDEX,
	CONSTRAINT FK_MAP_COOKIE_POLICY_CONSEN_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Alter tables
ALTER TABLE CSR.CUSTOMER ADD DISPLAY_COOKIE_POLICY NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE CSR.CUSTOMER ADD CONSTRAINT CK_CUSTOMER_DISP_COOKIE_POLICY CHECK (DISPLAY_COOKIE_POLICY IN (0,1));

--csrimp
ALTER TABLE CSRIMP.CUSTOMER ADD DISPLAY_COOKIE_POLICY NUMBER(1) NOT NULL;
ALTER TABLE CSRIMP.CUSTOMER ADD CONSTRAINT CK_CUSTOMER_DISP_COOKIE_POLICY CHECK (DISPLAY_COOKIE_POLICY IN (0,1));

-- *** Grants ***
grant select, insert, update, delete on csrimp.cookie_policy_consent to tool_user;

-- Object grants

-- grants for csrimp
grant select, insert, update on csr.cookie_policy_consent to csrimp;

grant select on csr.cookie_policy_consent_id_seq to csrimp;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data
BEGIN
	INSERT INTO CSR.UTIL_SCRIPT (UTIL_SCRIPT_ID,UTIL_SCRIPT_NAME,DESCRIPTION,UTIL_SCRIPT_SP,WIKI_ARTICLE) VALUES (54, 'Display cookie policy', 'Show/hide the cookie policy prompt in the website', 'EnableDisplayCookiePolicy', NULL);
	INSERT INTO CSR.UTIL_SCRIPT_PARAM (UTIL_SCRIPT_ID,PARAM_NAME,PARAM_HINT,POS,PARAM_VALUE) VALUES (54, 'Show/hide', 'Show = 1, Hide = 0', 1, NULL);
END;
/

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../csr_user_pkg
@../util_script_pkg
@../csr_user_body
@../customer_body
@../util_script_body
@../schema_pkg
@../schema_body
@../csrimp/imp_body

@update_tail
