-- Please update version.sql too -- this keeps clean builds in sync
define version=1272
@update_header

ALTER TABLE CSR.REGION_SET
 DROP CONSTRAINT PK_REGION_SET;

-- have to drop FK because it references UNIQ_REGION_SET_ID
ALTER TABLE CSR.REGION_SET_REGION DROP CONSTRAINT FK_REGION_SET_R_REGION_S;

ALTER TABLE CSR.REGION_SET
 DROP CONSTRAINT UNIQ_REGION_SET_ID;

DROP INDEX CSR.IDX_REGION_SET_APP_REGION;

ALTER TABLE CSR.REGION_SET
  ADD CONSTRAINT PK_REGION_SET PRIMARY KEY (APP_SID, REGION_SET_ID);

CREATE INDEX CSR.IDX_REGION_SET_APP_OWNER ON CSR.REGION_SET(APP_SID, OWNER_SID);

-- add FK back
ALTER TABLE CSR.REGION_SET_REGION ADD CONSTRAINT FK_REGION_SET_R_REGION_S
    FOREIGN KEY (APP_SID, REGION_SET_ID)
    REFERENCES CSR.REGION_SET(APP_SID, REGION_SET_ID)
;

@update_tail

