-- Please update version.sql too -- this keeps clean builds in sync
define version=2338
@update_header

ALTER TABLE CSR.PROPERTY RENAME TO ALL_PROPERTY;

CREATE OR REPLACE VIEW CSR.PROPERTY
	(APP_SID, REGION_SID, FLOW_ITEM_ID,
	 STREET_ADDR_1, STREET_ADDR_2, CITY, STATE, POSTCODE,
	 COMPANY_SID, PROPERTY_TYPE_ID, PROPERTY_SUB_TYPE_ID,
	 FUND_ID, MGMT_COMPANY_ID, MGMT_COMPANY_OTHER,
	 PM_BUILDING_ID, CURRENT_LEASE_ID, MGMT_COMPANY_CONTACT_ID) AS
  SELECT ALP.APP_SID, ALP.REGION_SID, ALP.FLOW_ITEM_ID,
	 ALP.STREET_ADDR_1, ALP.STREET_ADDR_2, ALP.CITY, ALP.STATE, ALP.POSTCODE,
	 ALP.COMPANY_SID, ALP.PROPERTY_TYPE_ID, ALP.PROPERTY_SUB_TYPE_ID,
	 ALP.FUND_ID, ALP.MGMT_COMPANY_ID, ALP.MGMT_COMPANY_OTHER,
	 ALP.PM_BUILDING_ID, ALP.CURRENT_LEASE_ID, ALP.MGMT_COMPANY_CONTACT_ID
    FROM ALL_PROPERTY ALP JOIN region r ON r.region_sid = alp.region_sid
   WHERE r.region_type = 3;

BEGIN
	FOR r IN (
		select * from dba_tab_privs where grantor = 'CSR' and table_name = 'ALL_PROPERTY'
	) LOOP
		IF r.privilege IN ('INSERT','SELECT','UPDATE','DELETE','REFERENCES') THEN
			EXECUTE IMMEDIATE 'GRANT ' || r.privilege || ' ON CSR.PROPERTY TO ' || r.grantee;
		END IF;
	END LOOP;
END;
/

ALTER TABLE CSR.SPACE RENAME TO ALL_SPACE;

CREATE OR REPLACE VIEW CSR.SPACE
	(APP_SID, REGION_SID, SPACE_TYPE_ID,
	 PROPERTY_REGION_SID, PROPERTY_TYPE_ID, CURRENT_LEASE_ID) AS
  SELECT ALS.APP_SID, ALS.REGION_SID, ALS.SPACE_TYPE_ID,
	 ALS.PROPERTY_REGION_SID, ALS.PROPERTY_TYPE_ID, ALS.CURRENT_LEASE_ID
    FROM ALL_SPACE ALS JOIN region r ON r.region_sid = ALS.region_sid
   WHERE r.region_type = 9;

BEGIN
	FOR r IN (
		select * from dba_tab_privs where grantor = 'CSR' and table_name = 'ALL_SPACE'
	) LOOP
		IF r.privilege IN ('INSERT','SELECT','UPDATE','DELETE','REFERENCES') THEN
			EXECUTE IMMEDIATE 'GRANT ' || r.privilege || ' ON CSR.SPACE TO ' || r.grantee;
		END IF;
	END LOOP;
END;
/

@../property_pkg
@../space_pkg

@../property_body
@../space_body

@update_tail
