-- Please update version.sql too -- this keeps clean builds in sync
define version=1529
@update_header

--no package recompiles are required
CREATE GLOBAL TEMPORARY TABLE CHAIN.TT_OLD_SO_CAPABILITIES
(
	CAPABILITY_ID		NUMBER NOT NULL,
	CAPABILITY_TYPE		NUMBER NOT NULL,
	CAPABILITY_NAME		VARCHAR2(255) NOT NULL,
	SO_ID				NUMBER NOT NULL,
	DACL_ID				NUMBER NOT NULL,
	DACL_SO_ID			NUMBER NOT NULL,
	PERMISSION_SET		NUMBER NOT NULL,
	GROUP_NAME			VARCHAR2(255) NOT NULL
) 
ON COMMIT PRESERVE ROWS; 

CREATE GLOBAL TEMPORARY TABLE CHAIN.TT_NEW_TYPE_CAPABILITIES
(
	CAPABILITY_ID		NUMBER NOT NULL,
	CAPABILITY_NAME		VARCHAR2(255) NOT NULL,
	PERMISSION_SET		NUMBER NOT NULL,
	GROUP_NAME			VARCHAR2(255) NOT NULL
) 
ON COMMIT PRESERVE ROWS; 

@update_tail