-- Please update version.sql too -- this keeps clean builds in sync
define version=2204
@update_header

DROP INDEX UK_SCORE_TYPE_LOOKUP_KEY;
CREATE UNIQUE INDEX CSR.UK_SCORE_TYPE_LOOKUP_KEY ON CSR.SCORE_TYPE (APP_SID, NVL(LOOKUP_KEY, 'NULL_'||SCORE_TYPE_ID));

DROP INDEX IX_SCORE_TYPE_MEASURE;
CREATE INDEX CSR.IX_SCORE_TYPE_MEASURE ON CSR.SCORE_TYPE (APP_SID, MEASURE_SID);

DROP INDEX IX_SCORE_TYPE_SUP_IND;
CREATE INDEX CSR.IX_SCORE_TYPE_SUP_IND ON CSR.SCORE_TYPE (APP_SID, SUPPLIER_SCORE_IND_SID);

@update_tail
