-- Please update version.sql too -- this keeps clean builds in sync
define version=1905
@update_header

CREATE GLOBAL TEMPORARY TABLE CMS.TEMP_REGION_PATH
(
	REGION_SID		NUMBER(10),
	DESCRIPTION		VARCHAR2(1023),
	PATH			VARCHAR2(4000),
	GEO_COUNTRY		VARCHAR2(2)
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE CMS.TEMP_IND_PATH
(
	IND_SID			NUMBER(10),
	DESCRIPTION		VARCHAR2(1023),
	PATH			VARCHAR2(4000)
) ON COMMIT DELETE ROWS;

@update_tail
