-- Please update version.sql too -- this keeps clean builds in sync
define version=56
@update_header


CREATE SEQUENCE DOC_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

CREATE SEQUENCE DOC_TAG_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;


-- 
-- TABLE: CUSTOMER_DOC_TAG 
--

CREATE TABLE CUSTOMER_DOC_TAG(
    DOC_TAG_ID      NUMBER(10, 0)    NOT NULL,
    CSR_ROOT_SID    NUMBER(10, 0)    NOT NULL,
    TAG             VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK264 PRIMARY KEY (DOC_TAG_ID)
)
;



-- 
-- TABLE: DOC 
--

CREATE TABLE DOC(
    DOC_ID          NUMBER(10, 0)    NOT NULL,
    CSR_ROOT_SID    NUMBER(10, 0)    NOT NULL,
    PARENT_SID      NUMBER(10, 0)    NOT NULL,
    DATA            BLOB             NOT NULL,
    MIME_TYPE       VARCHAR2(255)    NOT NULL,
    FILENAME        VARCHAR2(255)    NOT NULL,
    DESCRIPTION     CLOB             NOT NULL,
    CONSTRAINT PK263 PRIMARY KEY (DOC_ID)
)
;



-- 
-- TABLE: DOC_DOWNLOAD 
--

CREATE TABLE DOC_DOWNLOAD(
    DOC_ID            NUMBER(10, 0)    NOT NULL,
    CSR_USER_SID      NUMBER(10, 0)    NOT NULL,
    DOWNLOADED_DTM    DATE              DEFAULT SYSDATE NOT NULL
)
;



-- 
-- TABLE: DOC_HISTORY 
--

CREATE TABLE DOC_HISTORY(
    DOC_ID         NUMBER(10, 0)     NOT NULL,
    VERSION        NUMBER(10, 0)      DEFAULT 1 NOT NULL,
    CHANGED_DTM    DATE               DEFAULT SYSDATE NOT NULL,
    REASON         VARCHAR2(2048)    NOT NULL,
    CONSTRAINT PK266 PRIMARY KEY (DOC_ID, VERSION)
)
;



-- 
-- TABLE: DOC_TAG 
--

CREATE TABLE DOC_TAG(
    DOC_ID        NUMBER(10, 0)    NOT NULL,
    DOC_TAG_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK267 PRIMARY KEY (DOC_ID, DOC_TAG_ID)
)
;



-- 
-- TABLE: CUSTOMER_DOC_TAG 
--

ALTER TABLE CUSTOMER_DOC_TAG ADD CONSTRAINT RefCUSTOMER449 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;


-- 
-- TABLE: DOC 
--

ALTER TABLE DOC ADD CONSTRAINT RefCUSTOMER450 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;


-- 
-- TABLE: DOC_DOWNLOAD 
--

ALTER TABLE DOC_DOWNLOAD ADD CONSTRAINT RefCSR_USER451 
    FOREIGN KEY (CSR_USER_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;

ALTER TABLE DOC_DOWNLOAD ADD CONSTRAINT RefDOC452 
    FOREIGN KEY (DOC_ID)
    REFERENCES DOC(DOC_ID)
;


-- 
-- TABLE: DOC_HISTORY 
--

ALTER TABLE DOC_HISTORY ADD CONSTRAINT RefDOC453 
    FOREIGN KEY (DOC_ID)
    REFERENCES DOC(DOC_ID)
;


-- 
-- TABLE: DOC_TAG 
--

ALTER TABLE DOC_TAG ADD CONSTRAINT RefCUSTOMER_DOC_TAG454 
    FOREIGN KEY (DOC_TAG_ID)
    REFERENCES CUSTOMER_DOC_TAG(DOC_TAG_ID)
;

ALTER TABLE DOC_TAG ADD CONSTRAINT RefDOC455 
    FOREIGN KEY (DOC_ID)
    REFERENCES DOC(DOC_ID)
;

@update_tail
