-- Please update version.sql too -- this keeps clean builds in sync
define version=2507
@update_header

ALTER TABLE CSR.EST_OPTIONS ADD CONSTRAINT FK_CUSTOMER_EST_OPTIONS 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.EST_OPTIONS ADD CONSTRAINT FK_EST_ACCOUNT_OPTIONS 
    FOREIGN KEY (APP_SID, DEFAULT_ACCOUNT_SID)
    REFERENCES CSR.EST_ACCOUNT(APP_SID, EST_ACCOUNT_SID)
;

ALTER TABLE CSR.EST_OPTIONS ADD CONSTRAINT FK_EST_CUSTOMER_OPTIONS 
    FOREIGN KEY (DEFAULT_CUSTOMER_ID)
    REFERENCES CSR.EST_CUSTOMER_GLOBAL(PM_CUSTOMER_ID)
;

CREATE INDEX CSR.IX_EST_ACCOUNT_OPTIONS ON CSR.EST_OPTIONS (APP_SID, DEFAULT_ACCOUNT_SID);
CREATE INDEX CSR.IX_EST_CUSTOMER_OPTIONS ON CSR.EST_OPTIONS (DEFAULT_CUSTOMER_ID);

@update_tail
