-- Please update version.sql too -- this keeps clean builds in sync
define version=1368
@update_header

ALTER TABLE csr.issue_custom_field DROP CONSTRAINT CHK_ISS_CUST_FLD_TYP;
ALTER TABLE csr.issue_custom_field ADD CONSTRAINT CHK_ISS_CUST_FLD_TYP CHECK (FIELD_TYPE IN ('T', 'O', 'M', 'D'));


CREATE TABLE CSR.ISSUE_CUSTOM_FIELD_DATE_VAL(
    APP_SID                  NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    ISSUE_ID                 NUMBER(10, 0)    NOT NULL,
    ISSUE_CUSTOM_FIELD_ID    NUMBER(10, 0)    NOT NULL,
    DATE_VALUE               DATE             NOT NULL,
    CONSTRAINT PK_ISSUE_CUST_FIELD_DATE_VAL PRIMARY KEY (APP_SID, ISSUE_ID, ISSUE_CUSTOM_FIELD_ID)
);

ALTER TABLE CSR.ISSUE_CUSTOM_FIELD_DATE_VAL ADD CONSTRAINT FK_ISS_CUST_FLD_DATE_FLD 
    FOREIGN KEY (APP_SID, ISSUE_CUSTOM_FIELD_ID)
    REFERENCES CSR.ISSUE_CUSTOM_FIELD(APP_SID, ISSUE_CUSTOM_FIELD_ID);

ALTER TABLE CSR.ISSUE_CUSTOM_FIELD_DATE_VAL ADD CONSTRAINT FK_ISSUE_CUST_FLD_DATE_VAL 
    FOREIGN KEY (APP_SID, ISSUE_ID)
    REFERENCES CSR.ISSUE(APP_SID, ISSUE_ID);
	
CREATE INDEX CSR.IX_ISS_CUST_FLD_DTE_VAL_ISS_ID ON CSR.ISSUE_CUSTOM_FIELD_DATE_VAL(APP_SID, ISSUE_ID);
CREATE INDEX CSR.IX_ISS_CUST_FLD_DTE_VAL_FLD ON CSR.ISSUE_CUSTOM_FIELD_DATE_VAL(APP_SID, ISSUE_CUSTOM_FIELD_ID);

ALTER TABLE CSR.ISSUE_CUSTOM_FIELD ADD POS NUMBER(10, 0);

ALTER TABLE CSR.ISSUE_TYPE ADD AUTO_CLOSE_AFTER_RESOLVE_DAYS NUMBER(10, 0);

ALTER TABLE csr.ISSUE_TYPE ADD CONSTRAINT CHK_IT_ACARD_VALID CHECK (AUTO_CLOSE_AFTER_RESOLVE_DAYS >= 1);

CREATE TABLE CSR.USER_DIRECTORY_TYPE(
    USER_DIRECTORY_TYPE_ID   NUMBER(10, 0)  NOT NULL,
    USER_DIRECTORY_CLASS     VARCHAR2(1000) NOT NULL,
	CONSTRAINT PK_USER_DIRECTORY_TYPE PRIMARY KEY (USER_DIRECTORY_TYPE_ID)
);

INSERT INTO CSR.USER_DIRECTORY_TYPE (USER_DIRECTORY_TYPE_ID, USER_DIRECTORY_CLASS) VALUES (1, 'Credit360.UserDirectory.CsrUserDirectory');

ALTER TABLE CSR.CUSTOMER ADD USER_DIRECTORY_TYPE_ID NUMBER(10,0) DEFAULT 1;

ALTER TABLE CSR.CUSTOMER ADD CONSTRAINT FK_CUSTOMER_USER_DIRECTORY_TYP
    FOREIGN KEY (USER_DIRECTORY_TYPE_ID)
    REFERENCES CSR.USER_DIRECTORY_TYPE(USER_DIRECTORY_TYPE_ID);

@..\csr_user_pkg
@..\issue_pkg

@..\csr_user_body
@..\issue_body
@..\csr_app_body
	
@update_tail
