-- Please update version.sql too -- this keeps clean builds in sync
define version=2053
@update_header

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE ADD CAN_BE_OVERDUE NUMBER(1, 0) NULL;

UPDATE CHAIN.QUESTIONNAIRE_TYPE SET CAN_BE_OVERDUE = 1;

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE MODIFY CAN_BE_OVERDUE NUMBER(1, 0) DEFAULT 1 NOT NULL;

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE ADD CHECK (CAN_BE_OVERDUE IN (0, 1))


@../chain/questionnaire_body

@update_tail
