-- Please update version.sql too -- this keeps clean builds in sync
define version=1305
@update_header


ALTER TABLE CT.BT_TRAVEL_MODE DROP CONSTRAINT TRAVEL_MODE_BT_TR_MD;
ALTER TABLE CT.BT_CAR_TRIP DROP CONSTRAINT BT_TR_MD_BT_CAR_TRIP;
ALTER TABLE CT.BT_BUS_TRIP DROP CONSTRAINT BT_TR_MD_BT_BUS_TRIP;
ALTER TABLE CT.BT_TRAIN_TRIP DROP CONSTRAINT BT_TR_MD_BT_TR_TRIP;
ALTER TABLE CT.BT_AIR_TRIP DROP CONSTRAINT BT_TR_MD_BT_AIR_TRIP;
ALTER TABLE CT.BT_CAB_TRIP DROP CONSTRAINT BT_TR_MD_BT_CAB_TRIP;
ALTER TABLE CT.BT_MOTORBIKE_TRIP DROP CONSTRAINT BT_TR_MD_BT_MB_TRIP;

CREATE TABLE CT.BT_TRAVEL_MODE_TYPE (
    BT_TRAVEL_MODE_TYPE_ID NUMBER(10) NOT NULL,
    TRAVEL_MODE_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_BT_TR_MDT PRIMARY KEY (BT_TRAVEL_MODE_TYPE_ID)
);

BEGIN
	DELETE FROM CT.BT_CAR_TRIP;
	DELETE FROM CT.BT_BUS_TRIP;
	DELETE FROM CT.BT_TRAIN_TRIP;
	DELETE FROM CT.BT_AIR_TRIP;
	DELETE FROM CT.BT_CAB_TRIP;
	DELETE FROM CT.BT_MOTORBIKE_TRIP;
	
	INSERT INTO CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID, TRAVEL_MODE_ID, DESCRIPTION) VALUES (1, 1, 'Car');
	INSERT INTO CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID, TRAVEL_MODE_ID, DESCRIPTION) VALUES (2, 1, 'Cab');
	INSERT INTO CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID, TRAVEL_MODE_ID, DESCRIPTION) VALUES (3, 2, 'Bus');
	INSERT INTO CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID, TRAVEL_MODE_ID, DESCRIPTION) VALUES (4, 3, 'Train');
	INSERT INTO CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID, TRAVEL_MODE_ID, DESCRIPTION) VALUES (5, 4, 'Motorbike');
	INSERT INTO CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID, TRAVEL_MODE_ID, DESCRIPTION) VALUES (6, 7, 'Air');
	
	DELETE FROM CT.BT_TRAVEL_MODE WHERE TRAVEL_MODE_ID = 6;
	DELETE FROM CT.BT_TRAVEL_MODE WHERE TRAVEL_MODE_ID = 5;
	
	UPDATE CT.BT_TRAVEL_MODE SET TRAVEL_MODE_ID = 6 WHERE TRAVEL_MODE_ID = 7;
	UPDATE CT.BT_TRAVEL_MODE SET TRAVEL_MODE_ID = 5 WHERE TRAVEL_MODE_ID = 4;
	UPDATE CT.BT_TRAVEL_MODE SET TRAVEL_MODE_ID = 4 WHERE TRAVEL_MODE_ID = 3;
	UPDATE CT.BT_TRAVEL_MODE SET TRAVEL_MODE_ID = 3 WHERE TRAVEL_MODE_ID = 2;
	UPDATE CT.BT_TRAVEL_MODE SET TRAVEL_MODE_ID = 2 WHERE TRAVEL_MODE_ID = 1 AND DESCRIPTION IN ('Regular taxi', 'London cab');
END;
/


ALTER TABLE CT.BT_TRAVEL_MODE RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;
ALTER TABLE CT.BT_CAR_TRIP RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;
ALTER TABLE CT.BT_BUS_TRIP RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;
ALTER TABLE CT.BT_TRAIN_TRIP RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;
ALTER TABLE CT.BT_AIR_TRIP RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;
ALTER TABLE CT.BT_CAB_TRIP RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;
ALTER TABLE CT.BT_MOTORBIKE_TRIP RENAME COLUMN TRAVEL_MODE_ID TO BT_TRAVEL_MODE_TYPE_ID;



ALTER TABLE CT.BT_CAR_TRIP ADD CONSTRAINT CC_BT_CAR_TRIP_BT_TMT 
    CHECK (BT_TRAVEL_MODE_TYPE_ID = 1);

ALTER TABLE CT.BT_BUS_TRIP ADD CONSTRAINT CC_BT_BUS_TRIP_BT_TMT 
    CHECK (BT_TRAVEL_MODE_TYPE_ID = 3);

ALTER TABLE CT.BT_TRAIN_TRIP ADD CONSTRAINT CC_BT_TR_TRIP_BT_TMT 
    CHECK (BT_TRAVEL_MODE_TYPE_ID = 4);
    
ALTER TABLE CT.BT_AIR_TRIP ADD CONSTRAINT CC_BT_AIR_TRIP_BT_TMT 
    CHECK (BT_TRAVEL_MODE_TYPE_ID = 6);    
    
ALTER TABLE CT.BT_CAB_TRIP ADD CONSTRAINT CC_BT_CAB_TRIP_BT_TMT 
    CHECK (BT_TRAVEL_MODE_TYPE_ID = 2);
    
 ALTER TABLE CT.BT_MOTORBIKE_TRIP ADD CONSTRAINT CC_BT_MB_TRIP_BT_TMT 
    CHECK (BT_TRAVEL_MODE_TYPE_ID = 5);   
    

-- hmm, this is from 12775, the version I created my database from
--
-- CREATE TABLE CT.BT_TRAVEL_MODE (
--     TRAVEL_MODE_ID NUMBER(10) NOT NULL,
--     BT_TRAVEL_MODE_ID NUMBER(10) NOT NULL,
--     DESCRIPTION VARCHAR2(100),
--     EF_PER_KM NUMBER(20,10) NOT NULL,
--     EIO_KG_CO2_PER_GBP NUMBER(20,10) NOT NULL,
--     IS_DEFAULT NUMBER(1) DEFAULT 0 CONSTRAINT 0 NOT NULL,
--     CONSTRAINT PK_BT_TR_MD PRIMARY KEY (TRAVEL_MODE_ID, BT_TRAVEL_MODE_ID)
-- );
--
-- however it's been renamed subsequently apparently without a change script.

begin
	for r in (select 1 from all_tab_columns where owner='CT' and table_name='BT_TRAVEL_MODE' and column_name='TRAVEL_MODE_ID') loop
		execute immediate 'alter table CT.BT_TRAVEL_MODE rename column travel_mode_id to bt_travel_mode_id';
	end loop;
end;
/

ALTER TABLE CT.BT_TRAVEL_MODE ADD CONSTRAINT BT_TR_MDT_BT_TR_MD 
    FOREIGN KEY (BT_TRAVEL_MODE_TYPE_ID) REFERENCES CT.BT_TRAVEL_MODE_TYPE (BT_TRAVEL_MODE_TYPE_ID);

ALTER TABLE CT.BT_CAR_TRIP ADD CONSTRAINT BT_TR_MD_BT_CAR_TRIP 
    FOREIGN KEY (BT_TRAVEL_MODE_ID, BT_TRAVEL_MODE_TYPE_ID) REFERENCES CT.BT_TRAVEL_MODE (BT_TRAVEL_MODE_ID,BT_TRAVEL_MODE_TYPE_ID);

ALTER TABLE CT.BT_BUS_TRIP ADD CONSTRAINT BT_TR_MD_BT_BUS_TRIP 
    FOREIGN KEY (BT_TRAVEL_MODE_TYPE_ID, BT_TRAVEL_MODE_ID) REFERENCES CT.BT_TRAVEL_MODE (BT_TRAVEL_MODE_TYPE_ID,BT_TRAVEL_MODE_ID);    
    
ALTER TABLE CT.BT_TRAIN_TRIP ADD CONSTRAINT BT_TR_MD_BT_TR_TRIP 
    FOREIGN KEY (BT_TRAVEL_MODE_TYPE_ID, BT_TRAVEL_MODE_ID) REFERENCES CT.BT_TRAVEL_MODE (BT_TRAVEL_MODE_TYPE_ID,BT_TRAVEL_MODE_ID);

ALTER TABLE CT.BT_AIR_TRIP ADD CONSTRAINT BT_TR_MD_BT_AIR_TRIP 
    FOREIGN KEY (BT_TRAVEL_MODE_TYPE_ID, BT_TRAVEL_MODE_ID) REFERENCES CT.BT_TRAVEL_MODE (BT_TRAVEL_MODE_TYPE_ID,BT_TRAVEL_MODE_ID);

ALTER TABLE CT.BT_CAB_TRIP ADD CONSTRAINT BT_TR_MD_BT_CAB_TRIP 
    FOREIGN KEY (BT_TRAVEL_MODE_TYPE_ID, BT_TRAVEL_MODE_ID) REFERENCES CT.BT_TRAVEL_MODE (BT_TRAVEL_MODE_TYPE_ID,BT_TRAVEL_MODE_ID);

ALTER TABLE CT.BT_MOTORBIKE_TRIP ADD CONSTRAINT BT_TR_MD_BT_MB_TRIP 
    FOREIGN KEY (BT_TRAVEL_MODE_TYPE_ID, BT_TRAVEL_MODE_ID) REFERENCES CT.BT_TRAVEL_MODE (BT_TRAVEL_MODE_TYPE_ID,BT_TRAVEL_MODE_ID);


-- and some missing basedata.

BEGIN
	-- travel modes - COMMON
	BEGIN
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (1, 'Car');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN	
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (2, 'Bus');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN	
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (3, 'Train');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN	
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (4, 'Motorbike');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN	
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (5, 'Bike');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN	
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (6, 'Walk');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN	
		INSERT INTO ct.travel_mode (travel_mode_id, description) VALUES (7, 'Air');
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
END;
/  

ALTER TABLE CT.BT_TRAVEL_MODE_TYPE ADD CONSTRAINT TRAVEL_MODE_BT_TR_MDT 
    FOREIGN KEY (TRAVEL_MODE_ID) REFERENCES CT.TRAVEL_MODE (TRAVEL_MODE_ID);
 
@..\ct\business_travel_pkg
@..\ct\business_travel_body
@..\ct\emp_commute_body
 
@update_tail
