-- Please update version.sql too -- this keeps clean builds in sync
define version=302
@update_header

CREATE SEQUENCE METER_SOURCE_TYPE_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

CREATE TABLE METER_SOURCE_TYPE(
    METER_SOURCE_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    NAME                    VARCHAR2(256)    NOT NULL,
    DESCRIPTION             VARCHAR2(512)    NOT NULL,
    CONSTRAINT PK570 PRIMARY KEY (METER_SOURCE_TYPE_ID)
)
;


ALTER TABLE ALL_METER ADD(
	METER_SOURCE_TYPE_ID	NUMBER(10, 0)	NULL
);

INSERT INTO meter_source_type
  (meter_source_type_id, name, description)
  	VALUES (meter_source_type_id_seq.NEXTVAL, 'point', 'Point in time');
  	
INSERT INTO meter_source_type
  (meter_source_type_id, name, description)
  	VALUES (meter_source_type_id_seq.NEXTVAL, 'period', 'Arbitrary period');
  	
INSERT INTO meter_source_type
  (meter_source_type_id, name, description)
  	VALUES (meter_source_type_id_seq.NEXTVAL, 'amr', 'AMR (CSR form)');

UPDATE all_meter SET meter_source_type_id = 1;

ALTER TABLE ALL_METER MODIFY(
	METER_SOURCE_TYPE_ID	NUMBER(10, 0)	NOT NULL
);



ALTER TABLE ALL_METER ADD CONSTRAINT RefMETER_SOURCE_TYPE1105 
    FOREIGN KEY (METER_SOURCE_TYPE_ID)
    REFERENCES METER_SOURCE_TYPE(METER_SOURCE_TYPE_ID)
;

CREATE OR REPLACE VIEW METER
	(REGION_SID, NOTE, PRIMARY_IND_SID, PRIMARY_MEASURE_CONVERSION_ID, METER_SOURCE_TYPE_ID) AS
  SELECT REGION_SID, NOTE, PRIMARY_IND_SID, PRIMARY_MEASURE_CONVERSION_ID, METER_SOURCE_TYPE_ID
    FROM ALL_METER
   WHERE ACTIVE = 1;
   
CREATE TABLE METER_READING_PERIOD(
    START_ID    NUMBER(10, 0)    NOT NULL,
    END_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK572 PRIMARY KEY (START_ID, END_ID)
)
;

ALTER TABLE METER_READING_PERIOD ADD CONSTRAINT RefMETER_READING1109 
    FOREIGN KEY (END_ID)
    REFERENCES METER_READING(METER_READING_ID)
;

ALTER TABLE METER_READING_PERIOD ADD CONSTRAINT RefMETER_READING1110 
    FOREIGN KEY (START_ID)
    REFERENCES METER_READING(METER_READING_ID)
;

ALTER TABLE METER_READING ADD (
	REFERENCE				VARCHAR2(1024)	NULL,
    COST					NUMBER(24, 10)	NULL,
    METER_DOCUMENT_ID		NUMBER(10, 0) NULL
);

CREATE SEQUENCE METER_DOCUMENT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

CREATE TABLE METER_DOCUMENT(
    APP_SID              NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    METER_DOCUMENT_ID    NUMBER(10, 0)     NOT NULL,
    REGION_SID           NUMBER(10, 0)     NOT NULL,
    MIME_TYPE            VARCHAR2(256)     NOT NULL,
    FILE_NAME            VARCHAR2(1024)    NOT NULL,
    DATA                 BLOB              NOT NULL,
    CONSTRAINT PK574 PRIMARY KEY (APP_SID, METER_DOCUMENT_ID, REGION_SID)
)
;

ALTER TABLE METER_DOCUMENT ADD CONSTRAINT RefALL_METER1114 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES REGION(APP_SID, REGION_SID)
;

ALTER TABLE METER_READING ADD CONSTRAINT RefMETER_DOCUMENT1115 
    FOREIGN KEY (APP_SID, METER_DOCUMENT_ID, REGION_SID)
    REFERENCES METER_DOCUMENT(APP_SID, METER_DOCUMENT_ID, REGION_SID)
;

@update_tail
