define version=781
@update_header


ALTER TABLE CSR.ISSUE_ACTION_LOG ADD RE_ROLE_SID NUMBER(10, 0);

ALTER TABLE CSR.ISSUE_ACTION_LOG ADD CONSTRAINT FK_RE_ROLE_AIL 
    FOREIGN KEY (APP_SID, RE_ROLE_SID)
    REFERENCES CSR.ROLE(APP_SID, ROLE_SID)
;

INSERT INTO CSR.ISSUE_ACTION_TYPE (ISSUE_ACTION_TYPE_ID, DESCRIPTION) VALUES (11, 'Emailed role');

@..\csr_data_pkg
@..\issue_pkg
@..\issue_body

@update_tail