-- Please update version.sql too -- this keeps clean builds in sync
define version=1140
@update_header

ALTER TABLE CT.WORKSHEET_COLUMN_TYPE ADD (CLASS_TYPE VARCHAR2(1000) NOT NULL);
ALTER TABLE CT.WORKSHEET_COLUMN_TYPE ADD (VALUE_GROUP_KEY VARCHAR2(100));

ALTER TABLE CT.WORKSHEET_ROW DROP CONSTRAINT WORKSHEET_WORKSHEET_ROW;
ALTER TABLE CT.WORKSHEET_COLUMN DROP CONSTRAINT WORKSHEET_WS_COLUMN;
ALTER TABLE CT.WORKSHEET_COLUMN DROP CONSTRAINT PK_WS_COLUMN;

ALTER TABLE CT.WORKSHEET MODIFY WORKSHEET_ID NUMBER(10);
ALTER TABLE CT.WORKSHEET_ROW MODIFY WORKSHEET_ID NUMBER(10);
ALTER TABLE CT.WORKSHEET_COLUMN MODIFY WORKSHEET_ID NUMBER(10);
ALTER TABLE CT.WORKSHEET_COLUMN MODIFY COLUMN_INDEX NUMBER(10) NOT NULL;
ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT TUC_WS_COLUMN_2 UNIQUE (APP_SID, WORKSHEET_ID, WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT PK_WS_COLUMN 
	PRIMARY KEY (APP_SID, WORKSHEET_ID, WORKSHEET_COLUMN_TYPE_ID, COLUMN_INDEX);

ALTER TABLE CT.WORKSHEET_ROW ADD CONSTRAINT WORKSHEET_WORKSHEET_ROW 
    FOREIGN KEY (APP_SID, WORKSHEET_ID) REFERENCES CT.WORKSHEET (APP_SID,WORKSHEET_ID);

ALTER TABLE CT.WORKSHEET_COLUMN ADD CONSTRAINT WORKSHEET_WS_COLUMN 
    FOREIGN KEY (APP_SID, WORKSHEET_ID) REFERENCES CT.WORKSHEET (APP_SID,WORKSHEET_ID);

CREATE TABLE CT.VALUE_MAP (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    VALUE_MAP_ID NUMBER(10) NOT NULL,
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    VALUE VARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_VALUE_MAP PRIMARY KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID)
);

ALTER TABLE CT.VALUE_MAP ADD CONSTRAINT CC_VALUE_MAP_VALUE 
    CHECK (VALUE = LOWER(TRIM(VALUE)));

CREATE TABLE CT.VALUE_MAP_CURRENCY (
    APP_SID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
    VALUE_MAP_ID NUMBER(10) NOT NULL,
    CURRENCY_ID NUMBER(10) NOT NULL,
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_VALUE_MAP_CURRENCY PRIMARY KEY (APP_SID, VALUE_MAP_ID, CURRENCY_ID, WORKSHEET_COLUMN_TYPE_ID)
);

CREATE TABLE CT.VALUE_MAP_BREAKDOWN (
    APP_SID NUMBER(10) NOT NULL,
    VALUE_MAP_ID NUMBER(10) NOT NULL,
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    BREAKDOWN_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_VM_BREAKDOWN PRIMARY KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID, BREAKDOWN_ID)
);

CREATE TABLE CT.VALUE_MAP_REGION (
    APP_SID NUMBER(10) NOT NULL,
    VALUE_MAP_ID NUMBER(10) NOT NULL,
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    REGION_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_VALUE_MAP_REGION PRIMARY KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID, REGION_ID)
);


CREATE TABLE CT.WORKSHEET_COLUMN_VALUE_MAP (
    APP_SID NUMBER(10) NOT NULL,
    WORKSHEET_ID NUMBER(10) NOT NULL,
    WORKSHEET_COLUMN_TYPE_ID NUMBER(10) NOT NULL,
    COLUMN_INDEX NUMBER(10) NOT NULL,
    VALUE_MAP_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_WSC_VALUE_MAP PRIMARY KEY (APP_SID, WORKSHEET_ID, WORKSHEET_COLUMN_TYPE_ID, COLUMN_INDEX, VALUE_MAP_ID)
);

ALTER TABLE CT.VALUE_MAP ADD CONSTRAINT WS_COLUMN_TYPE_VALUE_MAP 
    FOREIGN KEY (WORKSHEET_COLUMN_TYPE_ID) REFERENCES CT.WORKSHEET_COLUMN_TYPE (WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.VALUE_MAP ADD CONSTRAINT CUSTOMER_OPTIONS_VALUE_MAP 
    FOREIGN KEY (APP_SID) REFERENCES CT.CUSTOMER_OPTIONS (APP_SID);

ALTER TABLE CT.VALUE_MAP_CURRENCY ADD CONSTRAINT VALUE_MAP_VALUE_MAP_CURRENCY 
    FOREIGN KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID) REFERENCES CT.VALUE_MAP (APP_SID,VALUE_MAP_ID,WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.VALUE_MAP_CURRENCY ADD CONSTRAINT CURRENCY_VALUE_MAP_CURRENCY 
    FOREIGN KEY (CURRENCY_ID) REFERENCES CT.CURRENCY (CURRENCY_ID);

ALTER TABLE CT.WORKSHEET_COLUMN_VALUE_MAP ADD CONSTRAINT WS_COLUMN_WSC_VALUE_MAP 
    FOREIGN KEY (APP_SID, WORKSHEET_ID, WORKSHEET_COLUMN_TYPE_ID, COLUMN_INDEX) REFERENCES CT.WORKSHEET_COLUMN (APP_SID,WORKSHEET_ID,WORKSHEET_COLUMN_TYPE_ID,COLUMN_INDEX);

ALTER TABLE CT.WORKSHEET_COLUMN_VALUE_MAP ADD CONSTRAINT VALUE_MAP_WSC_VALUE_MAP 
    FOREIGN KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID) REFERENCES CT.VALUE_MAP (APP_SID,VALUE_MAP_ID,WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.VALUE_MAP_BREAKDOWN ADD CONSTRAINT VALUE_MAP_VM_BREAKDOWN 
    FOREIGN KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID) REFERENCES CT.VALUE_MAP (APP_SID,VALUE_MAP_ID,WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.VALUE_MAP_BREAKDOWN ADD CONSTRAINT BREAKDOWN_VM_BREAKDOWN 
    FOREIGN KEY (APP_SID, BREAKDOWN_ID) REFERENCES CT.BREAKDOWN (APP_SID,BREAKDOWN_ID);

ALTER TABLE CT.VALUE_MAP_REGION ADD CONSTRAINT VALUE_MAP_VALUE_MAP_REGION 
    FOREIGN KEY (APP_SID, VALUE_MAP_ID, WORKSHEET_COLUMN_TYPE_ID) REFERENCES CT.VALUE_MAP (APP_SID,VALUE_MAP_ID,WORKSHEET_COLUMN_TYPE_ID);

ALTER TABLE CT.VALUE_MAP_REGION ADD CONSTRAINT REGION_VALUE_MAP_REGION 
    FOREIGN KEY (REGION_ID) REFERENCES CT.REGION (REGION_ID);

@..\ct\rls
@..\ct\excel_pkg
@..\ct\excel_body

@update_tail
