-- Please update version.sql too -- this keeps clean builds in sync
define version=1270
@update_header

CREATE SEQUENCE CSR.REGION_SET_ID
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;

CREATE TABLE CSR.REGION_SET(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SET_ID         NUMBER(10, 0)    NOT NULL,
    OWNER_SID             NUMBER(10, 0)    NOT NULL,
    NAME                  VARCHAR2(255)    NOT NULL,
    DISPOSAL_DTM          DATE,
    CONSTRAINT PK_REGION_SET PRIMARY KEY (APP_SID, REGION_SET_ID, OWNER_SID)
)
;

CREATE TABLE CSR.REGION_SET_REGION(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SET_ID         NUMBER(10, 0)    NOT NULL,
    REGION_SID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_REGION_SET_REGION PRIMARY KEY (APP_SID, REGION_SET_ID, REGION_SID)
)
;

CREATE UNIQUE INDEX CSR.IDX_REGION_SET_APP_REGION ON CSR.REGION_SET(APP_SID, REGION_SET_ID)
;

ALTER TABLE CSR.REGION_SET ADD CONSTRAINT FK_REGION_SET_OWNER
    FOREIGN KEY (APP_SID, OWNER_SID)
    REFERENCES CSR.CSR_USER(APP_SID, CSR_USER_SID)
;

ALTER TABLE CSR.REGION_SET ADD CONSTRAINT UNIQ_REGION_SET_ID
    UNIQUE (APP_SID, REGION_SET_ID)
    USING INDEX CSR.IDX_REGION_SET_APP_REGION
;

ALTER TABLE CSR.REGION_SET_REGION ADD CONSTRAINT FK_REGION_SET_R_REGION_S
    FOREIGN KEY (APP_SID, REGION_SET_ID)
    REFERENCES CSR.REGION_SET(APP_SID, REGION_SET_ID)
;

ALTER TABLE CSR.REGION_SET_REGION ADD CONSTRAINT FK_REGION_SET_R_REGION
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

CREATE OR REPLACE PACKAGE CSR.REGION_SET_PKG AS
    PROCEDURE DUMMY;
END;
/
CREATE OR REPLACE PACKAGE BODY CSR.REGION_SET_PKG AS
    PROCEDURE DUMMY
    AS
    BEGIN
        NULL;
    END;
END;
/

GRANT EXECUTE
   ON CSR.REGION_SET_PKG
   TO WEB_USER
;

@../region_pkg
@../region_set_pkg

@../region_body
@../region_set_body

@update_tail
