-- Please update version.sql too -- this keeps clean builds in sync
define version=257
@update_header

/*
begin 
	for r in (select owner, table_name 
				from all_tab_columns 
			   where column_name='APP_SID' and owner in ('SUPPLIER','ACTIONS','DONATIONS')) loop
		dbms_output.put_line('GRANT DELETE ON '||r.owner||'.'||r.table_name||' TO CSR;');
	end loop;
end;
*/

PROMPT Enter connection name (e.g. ASPEN)
connect system/manager@&&1
GRANT DELETE ON ACTIONS.AGGR_TASK_IND_DEPENDENCY TO CSR;
GRANT DELETE ON ACTIONS.AGGR_TASK_PERIOD TO CSR;
GRANT DELETE ON ACTIONS.AGGR_TASK_PERIOD_OVERRIDE TO CSR;
GRANT DELETE ON ACTIONS.AGGR_TASK_TASK_DEPENDENCY TO CSR;
GRANT DELETE ON ACTIONS.ALLOW_TASK_STATUS_CHANGE TO CSR;
GRANT DELETE ON ACTIONS.CUSTOMER_OPTIONS TO CSR;
GRANT DELETE ON ACTIONS.FILE_UPLOAD TO CSR;
GRANT DELETE ON ACTIONS.IND_TEMPLATE TO CSR;
GRANT DELETE ON ACTIONS.INITIATIVE_EXTRA_INFO TO CSR;
GRANT DELETE ON ACTIONS.INITIATIVE_PROJECT_TEAM TO CSR;
GRANT DELETE ON ACTIONS.PROJECT TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_IND_TEMPLATE TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_IND_TEMPLATE_INSTANCE TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_ROLE TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_ROLE_MEMBER TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_TAG_GROUP TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_TASK_PERIOD_STATUS TO CSR;
GRANT DELETE ON ACTIONS.PROJECT_TASK_STATUS TO CSR;
GRANT DELETE ON ACTIONS.ROLE TO CSR;
GRANT DELETE ON ACTIONS.ROOT_IND_TEMPLATE_INSTANCE TO CSR;
GRANT DELETE ON ACTIONS.SCRIPT TO CSR;
GRANT DELETE ON ACTIONS.TAG TO CSR;
GRANT DELETE ON ACTIONS.TAG_GROUP TO CSR;
GRANT DELETE ON ACTIONS.TAG_GROUP_MEMBER TO CSR;
GRANT DELETE ON ACTIONS.TASK TO CSR;
GRANT DELETE ON ACTIONS.TASK_BUDGET_HISTORY TO CSR;
GRANT DELETE ON ACTIONS.TASK_BUDGET_PERIOD TO CSR;
GRANT DELETE ON ACTIONS.TASK_COMMENT TO CSR;
GRANT DELETE ON ACTIONS.TASK_FILE_UPLOAD TO CSR;
GRANT DELETE ON ACTIONS.TASK_INDICATOR TO CSR;
GRANT DELETE ON ACTIONS.TASK_IND_DEPENDENCY TO CSR;
GRANT DELETE ON ACTIONS.TASK_IND_TEMPLATE_INSTANCE TO CSR;
GRANT DELETE ON ACTIONS.TASK_INSTANCE TO CSR;
GRANT DELETE ON ACTIONS.TASK_PERIOD TO CSR;
GRANT DELETE ON ACTIONS.TASK_PERIOD_FILE_UPLOAD TO CSR;
GRANT DELETE ON ACTIONS.TASK_PERIOD_OVERRIDE TO CSR;
GRANT DELETE ON ACTIONS.TASK_PERIOD_STATUS TO CSR;
GRANT DELETE ON ACTIONS.TASK_RECALC_JOB TO CSR;
GRANT DELETE ON ACTIONS.TASK_REGION TO CSR;
GRANT DELETE ON ACTIONS.TASK_ROLE_MEMBER TO CSR;
GRANT DELETE ON ACTIONS.TASK_STATUS TO CSR;
GRANT DELETE ON ACTIONS.TASK_STATUS_HISTORY TO CSR;
GRANT DELETE ON ACTIONS.TASK_TAG TO CSR;
GRANT DELETE ON ACTIONS.TASK_TASK_DEPENDENCY TO CSR;
GRANT DELETE ON DONATIONS.BUDGET TO CSR;
GRANT DELETE ON DONATIONS.BUDGET_CONSTANT TO CSR;
GRANT DELETE ON DONATIONS.CONSTANT TO CSR;
GRANT DELETE ON DONATIONS.CUSTOMER_FILTER_FLAG TO CSR;
GRANT DELETE ON DONATIONS.CUSTOM_FIELD TO CSR;
GRANT DELETE ON DONATIONS.DONATION TO CSR;
GRANT DELETE ON DONATIONS.DONATION_DOC TO CSR;
GRANT DELETE ON DONATIONS.DONATION_STATUS TO CSR;
GRANT DELETE ON DONATIONS.DONATION_TAG TO CSR;
GRANT DELETE ON DONATIONS.FILTER TO CSR;
GRANT DELETE ON DONATIONS.LETTER_BODY_REGION_GROUP TO CSR;
GRANT DELETE ON DONATIONS.LETTER_BODY_TEXT TO CSR;
GRANT DELETE ON DONATIONS.LETTER_TEMPLATE TO CSR;
GRANT DELETE ON DONATIONS.RECIPIENT TO CSR;
GRANT DELETE ON DONATIONS.RECIPIENT_TAG TO CSR;
GRANT DELETE ON DONATIONS.REGION_GROUP TO CSR;
GRANT DELETE ON DONATIONS.REGION_GROUP_MEMBER TO CSR;
GRANT DELETE ON DONATIONS.REGION_GROUP_RECIPIENT TO CSR;
GRANT DELETE ON DONATIONS.SCHEME TO CSR;
GRANT DELETE ON DONATIONS.SCHEME_FIELD TO CSR;
GRANT DELETE ON DONATIONS.SCHEME_TAG_GROUP TO CSR;
GRANT DELETE ON DONATIONS.TAG TO CSR;
GRANT DELETE ON DONATIONS.TAG_GROUP TO CSR;
GRANT DELETE ON DONATIONS.TAG_GROUP_MEMBER TO CSR;
GRANT DELETE ON DONATIONS.TRANSITION TO CSR;
GRANT DELETE ON DONATIONS.USER_FIELDSET TO CSR;
GRANT DELETE ON DONATIONS.USER_FIELDSET_FIELD TO CSR;
GRANT DELETE ON SUPPLIER.ALERT_BATCH TO CSR;
GRANT DELETE ON SUPPLIER.ALL_COMPANY TO CSR;
GRANT DELETE ON SUPPLIER.ALL_PRODUCT TO CSR;
GRANT DELETE ON SUPPLIER.COMPANY TO CSR;
GRANT DELETE ON SUPPLIER.CONTACT_SHORTLIST TO CSR;
GRANT DELETE ON SUPPLIER.CUSTOMER_OPTIONS TO CSR;
GRANT DELETE ON SUPPLIER.CUSTOMER_PERIOD TO CSR;
GRANT DELETE ON SUPPLIER.DOMAIN_BLACKLIST TO CSR;
GRANT DELETE ON SUPPLIER.DOMAIN_LOOKUP TO CSR;
GRANT DELETE ON SUPPLIER.GT_TARGET_SCORES TO CSR;
GRANT DELETE ON SUPPLIER.GT_TARGET_SCORES_LOG TO CSR;
GRANT DELETE ON SUPPLIER.PRODUCT TO CSR;
GRANT DELETE ON SUPPLIER.QUESTIONNAIRE_GROUP TO CSR;
GRANT DELETE ON SUPPLIER.QUESTIONNAIRE_GROUP_SUPPLIER TO CSR;
GRANT DELETE ON SUPPLIER.TAG_GROUP TO CSR;

connect csr/csr@&&1

@..\csr_data_body
    
@update_tail
