-- Please update version.sql too -- this keeps clean builds in sync
define version=1783
@update_header

ALTER TABLE CSR.EST_BUILDING ADD (
	PREV_REGION_SID		NUMBER(10)
);

ALTER TABLE CSR.EST_SPACE ADD (
	PREV_REGION_SID		NUMBER(10)
);

ALTER TABLE CSR.EST_ENERGY_METER ADD (
	PREV_REGION_SID		NUMBER(10)
);

ALTER TABLE CSR.EST_WATER_METER ADD (
	PREV_REGION_SID		NUMBER(10)
);

ALTER TABLE CSR.EST_BUILDING ADD CONSTRAINT FK_EST_BLDNG_PRGN 
    FOREIGN KEY (APP_SID, PREV_REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.EST_SPACE ADD CONSTRAINT FK_EST_SPACE_PRGN 
    FOREIGN KEY (APP_SID, PREV_REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.EST_ENERGY_METER ADD CONSTRAINT FK_EST_METER_PRGN 
    FOREIGN KEY (APP_SID, PREV_REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.EST_WATER_METER ADD CONSTRAINT FK_WMETER_PRGN 
    FOREIGN KEY (APP_SID, PREV_REGION_SID)
    REFERENCES CSR.REGION(APP_SID, REGION_SID)
;


@../energy_star_pkg
@../energy_star_body

@update_tail
