-- Please update version.sql too -- this keeps clean builds in sync
define version=1182
@update_header

-----------------------------------------------------
-- CSR
-----------------------------------------------------
CREATE GLOBAL TEMPORARY TABLE CSR.WORKSHEET_COLUMN_REMAP
(
	COLUMN_TYPE_ID		NUMBER(10) NOT NULL,
	COLUMN_INDEX		NUMBER(10) NOT NULL,
	OLD_COLUMN_INDEX	NUMBER(10)
) ON COMMIT DELETE ROWS;

CREATE SEQUENCE CSR.VALUE_MAP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

ALTER TABLE CSR.WORKSHEET_VALUE_MAPPER DROP CONSTRAINT RefWORKSHEET_VALUE_HELPER3307;
ALTER TABLE CSR.WORKSHEET_VALUE_MAP DROP CONSTRAINT RefWORKSHEET_VALUE_MAPPER3306;
ALTER TABLE CSR.WORKSHEET_ROW DROP CONSTRAINT RefWORKSHEET3304;
ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP DROP CONSTRAINT RefWORKSHEET_COLUMN3303;
ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP DROP CONSTRAINT RefWORKSHEET_VALUE_MAP3302;
ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE DROP CONSTRAINT RefWORKSHEET_VALUE_HELPER3301;
ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE DROP CONSTRAINT RefWORKSHEET_TYPE3300;
ALTER TABLE CSR.WORKSHEET_COLUMN DROP CONSTRAINT RefWORKSHEET3299;
ALTER TABLE CSR.WORKSHEET_COLUMN DROP CONSTRAINT RefWORKSHEET_COLUMN_TYPE3298;
ALTER TABLE CSR.WORKSHEET DROP CONSTRAINT RefWORKSHEET_TYPE3296;


ALTER TABLE CSR.WORKSHEET_COLUMN DROP CONSTRAINT PK_WS_COLUMN;
ALTER TABLE CSR.WORKSHEET_COLUMN ADD CONSTRAINT PK_WS_COLUMN PRIMARY KEY (APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID, VALUE_HELPER_ID);
ALTER TABLE CSR.WORKSHEET_COLUMN ADD CONSTRAINT UC_UNIQUE_COLUMN_INDEX UNIQUE (APP_SID, WORKSHEET_ID, COLUMN_INDEX);

ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP DROP CONSTRAINT PK_WSC_VALUE_MAP;
ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP DROP COLUMN COLUMN_INDEX;
ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP ADD CONSTRAINT PK_WSC_VALUE_MAP PRIMARY KEY (APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID, VALUE_MAP_ID, VALUE_HELPER_ID);

CREATE TABLE CSR.WORKSHEET_VALUE_MAP_VALUE(
    APP_SID            NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    VALUE_MAP_ID       NUMBER(10, 0)     NOT NULL,
    VALUE_HELPER_ID    NUMBER(10, 0)     NOT NULL,
    COLUMN_TYPE_ID     NUMBER(10, 0)     NOT NULL,
    VALUE              VARCHAR2(1000)    NOT NULL,
    CONSTRAINT CC_LOWER_VALUE CHECK (VALUE = LOWER(TRIM(VALUE))),
    CONSTRAINT PK_WS_VMV PRIMARY KEY (APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID, COLUMN_TYPE_ID)
);


ALTER TABLE CSR.WORKSHEET ADD CONSTRAINT FK_WST_WS 
    FOREIGN KEY (WORKSHEET_TYPE_ID)
    REFERENCES CSR.WORKSHEET_TYPE(WORKSHEET_TYPE_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN ADD CONSTRAINT FK_WS_WSC 
    FOREIGN KEY (APP_SID, WORKSHEET_ID)
    REFERENCES CSR.WORKSHEET(APP_SID, WORKSHEET_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN ADD CONSTRAINT FK_WSCT_WSC 
    FOREIGN KEY (COLUMN_TYPE_ID, VALUE_HELPER_ID)
    REFERENCES CSR.WORKSHEET_COLUMN_TYPE(COLUMN_TYPE_ID, VALUE_HELPER_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE ADD CONSTRAINT FK_WCVH_WSCT 
    FOREIGN KEY (VALUE_HELPER_ID)
    REFERENCES CSR.WORKSHEET_VALUE_HELPER(VALUE_HELPER_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE ADD CONSTRAINT FK_WST_WSCT 
    FOREIGN KEY (WORKSHEET_TYPE_ID)
    REFERENCES CSR.WORKSHEET_TYPE(WORKSHEET_TYPE_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP ADD CONSTRAINT FK_WSC_WSCVM 
    FOREIGN KEY (APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID, VALUE_HELPER_ID)
    REFERENCES CSR.WORKSHEET_COLUMN(APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID, VALUE_HELPER_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP ADD CONSTRAINT FK_WSVMV_WSCVM 
    FOREIGN KEY (APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID, COLUMN_TYPE_ID)
    REFERENCES CSR.WORKSHEET_VALUE_MAP_VALUE(APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID, COLUMN_TYPE_ID)
;

ALTER TABLE CSR.WORKSHEET_ROW ADD CONSTRAINT FK_WS_WSR 
    FOREIGN KEY (APP_SID, WORKSHEET_ID)
    REFERENCES CSR.WORKSHEET(APP_SID, WORKSHEET_ID)
;

ALTER TABLE CSR.WORKSHEET_VALUE_MAP ADD CONSTRAINT FK_WSVM_WSVM 
    FOREIGN KEY (VALUE_HELPER_ID)
    REFERENCES CSR.WORKSHEET_VALUE_MAPPER(VALUE_HELPER_ID)
;

ALTER TABLE CSR.WORKSHEET_VALUE_MAPPER ADD CONSTRAINT FK_WSVH_WSVM 
    FOREIGN KEY (VALUE_HELPER_ID)
    REFERENCES CSR.WORKSHEET_VALUE_HELPER(VALUE_HELPER_ID)
;

ALTER TABLE CSR.WORKSHEET_VALUE_MAP_VALUE ADD CONSTRAINT FK_WSCT_WSVMV 
    FOREIGN KEY (COLUMN_TYPE_ID, VALUE_HELPER_ID)
    REFERENCES CSR.WORKSHEET_COLUMN_TYPE(COLUMN_TYPE_ID, VALUE_HELPER_ID)
;

ALTER TABLE CSR.WORKSHEET_VALUE_MAP_VALUE ADD CONSTRAINT FK_WSVM_WSVMV 
    FOREIGN KEY (APP_SID, VALUE_HELPER_ID, VALUE_MAP_ID)
    REFERENCES CSR.WORKSHEET_VALUE_MAP(APP_SID, VALUE_HELPER_ID, VALUE_MAP_ID)
;

GRANT SELECT ON CSR.WORKSHEET_VALUE_MAP_VALUE TO CT;
-----------------------------------------------------
-- CHAIN
-----------------------------------------------------
GRANT EXECUTE ON chain.T_NUMERIC_TABLE TO PUBLIC;


-----------------------------------------------------
-- CT
-----------------------------------------------------
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY DROP CONSTRAINT TCC_WSVM_CURRENCY_1;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY DROP CONSTRAINT CC_WSVM_CURRENCY_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY DROP CONSTRAINT PK_WSVM_CURRENCY;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY DROP COLUMN VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY ADD CONSTRAINT PK_WSVM_CURRENCY PRIMARY KEY (APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY MODIFY (VALUE_HELPER_ID DEFAULT 100);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY ADD CONSTRAINT CC_WSVM_CURRENCY_VHID CHECK (VALUE_HELPER_ID = 100);

ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER DROP CONSTRAINT TCC_WSVM_SUPPLIER_1;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER DROP CONSTRAINT CC_WSVM_SUPPLIER_ID_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER DROP CONSTRAINT CC_WSVM_SUPPLIER_NAME_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER DROP CONSTRAINT PK_WSVM_SUPPLIER;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER DROP COLUMN ID_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER DROP COLUMN NAME_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER ADD CONSTRAINT PK_WSVM_SUPPLIER PRIMARY KEY (APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER MODIFY (VALUE_HELPER_ID DEFAULT 103);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER ADD CONSTRAINT CC_WSVM_SUPPLIER_VHID CHECK (VALUE_HELPER_ID = 103);

ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN DROP CONSTRAINT TCC_WSVM_BREAKDOWN_1;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN DROP CONSTRAINT CC_WSVM_BREAKDOWN_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN DROP CONSTRAINT PK_WSVM_BREAKDOWN;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN DROP COLUMN VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN ADD CONSTRAINT PK_WSVM_BREAKDOWN PRIMARY KEY (APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN MODIFY (VALUE_HELPER_ID DEFAULT 102);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN ADD CONSTRAINT CC_WSVM_BREAKDOWN_VHID CHECK (VALUE_HELPER_ID = 102);

ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION DROP CONSTRAINT TCC_WSVM_REGION_1;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION DROP CONSTRAINT CC_WSVM_REGION_VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION DROP CONSTRAINT PK_WSVM_REGION;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION DROP COLUMN VALUE;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION ADD CONSTRAINT PK_WSVM_REGION PRIMARY KEY (APP_SID, VALUE_MAP_ID, VALUE_HELPER_ID);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION MODIFY (VALUE_HELPER_ID DEFAULT 101);
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION ADD CONSTRAINT CC_WSVM_REGION_VHID CHECK (VALUE_HELPER_ID = 101);

CREATE GLOBAL TEMPORARY TABLE CT.ID_MAPPER_TABLE
(
	POSITION					NUMBER(10),
	VALUE_MAP_ID				NUMBER(10),
	COLUMN_TYPE_ID_1			NUMBER(10),
	VALUE_1						VARCHAR2(4000),
	COLUMN_TYPE_ID_2			NUMBER(10),
	VALUE_2						VARCHAR2(4000),
	ID							NUMBER(10)
) ON COMMIT DELETE ROWS;

@..\excel_pkg
@..\excel_body

@..\ct\excel_pkg
@..\ct\util_pkg

@..\ct\excel_body
@..\ct\util_body

@update_tail
