-- Please update version.sql too -- this keeps clean builds in sync
define version=1189
@update_header

/*****************************************************************
*	CSR
*****************************************************************/

ALTER TABLE CSR.WORKSHEET_COLUMN DROP CONSTRAINT FK_WSCT_WSC;
ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE DROP CONSTRAINT FK_WCVH_WSCT;
ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP DROP CONSTRAINT FK_WSC_WSCVM;
ALTER TABLE CSR.WORKSHEET_VALUE_MAP_VALUE DROP CONSTRAINT FK_WSCT_WSVMV;
ALTER TABLE CSR.WORKSHEET_VALUE_MAPPER DROP CONSTRAINT FK_WSVH_WSVM;

ALTER TABLE CSR.WORKSHEET_VALUE_MAPPER ADD (CLASS_TYPE VARCHAR2(1000));

UPDATE CSR.WORKSHEET_VALUE_MAPPER m
   SET CLASS_TYPE = (
   		SELECT CLASS_TYPE
   		  FROM CSR.WORKSHEET_VALUE_HELPER h
   		 WHERE m.VALUE_HELPER_ID = h.VALUE_HELPER_ID
   );

ALTER TABLE CSR.WORKSHEET_VALUE_MAPPER RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CSR.WORKSHEET_VALUE_MAPPER MODIFY CLASS_TYPE NOT NULL;

ALTER TABLE CSR.WORKSHEET_COLUMN DROP CONSTRAINT PK_WS_COLUMN;
ALTER TABLE CSR.WORKSHEET_COLUMN DROP COLUMN VALUE_HELPER_ID;
ALTER TABLE CSR.WORKSHEET_COLUMN ADD CONSTRAINT PK_WS_COLUMN PRIMARY KEY (APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID);


ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE DROP CONSTRAINT PK_WS_COLUMN_TYPE;
ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE MODIFY VALUE_MAPPER_ID NULL;
ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE ADD CONSTRAINT PK_WS_COLUMN_TYPE PRIMARY KEY (COLUMN_TYPE_ID);

UPDATE CSR.WORKSHEET_COLUMN_TYPE 
   SET VALUE_MAPPER_ID = NULL
 WHERE VALUE_MAPPER_ID NOT IN (SELECT VALUE_MAPPER_ID FROM CSR.WORKSHEET_VALUE_MAPPER);

ALTER TABLE CSR.WORKSHEET_VALUE_MAP RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CSR.WORKSHEET_VALUE_MAP_VALUE RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;


DROP TABLE CSR.WORKSHEET_VALUE_HELPER;

ALTER TABLE CSR.WORKSHEET_COLUMN ADD CONSTRAINT FK_WSCT_WSC 
    FOREIGN KEY (COLUMN_TYPE_ID)
    REFERENCES CSR.WORKSHEET_COLUMN_TYPE(COLUMN_TYPE_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN_TYPE ADD CONSTRAINT FK_WCVM_WSCT 
    FOREIGN KEY (VALUE_MAPPER_ID)
    REFERENCES CSR.WORKSHEET_VALUE_MAPPER(VALUE_MAPPER_ID)
;

ALTER TABLE CSR.WORKSHEET_COLUMN_VALUE_MAP ADD CONSTRAINT FK_WSC_WSCVM 
    FOREIGN KEY (APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID)
    REFERENCES CSR.WORKSHEET_COLUMN(APP_SID, WORKSHEET_ID, COLUMN_TYPE_ID)
;

ALTER TABLE CSR.WORKSHEET_VALUE_MAP_VALUE ADD CONSTRAINT FK_WSCT_WSVMV 
    FOREIGN KEY (COLUMN_TYPE_ID)
    REFERENCES CSR.WORKSHEET_COLUMN_TYPE(COLUMN_TYPE_ID)
;

/*****************************************************************
*	CT
*****************************************************************/
ALTER TABLE CT.WORKSHEET_VALUE_MAP_CURRENCY RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_SUPPLIER RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_BREAKDOWN RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;
ALTER TABLE CT.WORKSHEET_VALUE_MAP_REGION RENAME COLUMN VALUE_HELPER_ID TO VALUE_MAPPER_ID;

BEGIN
	dbms_rls.add_policy(
		object_schema   => 'CSR',
		object_name     => 'WORKSHEET_VALUE_MAP_VALUE',
		policy_name     => SUBSTR('WORKSHEET_VALUE_MAP_VALUE', 1, 23)||'_POLICY',
		function_schema => 'CSR',
		policy_function => 'appSidCheck',
		statement_types => 'select, insert, update, delete',
		update_check	=> true,
		policy_type     => dbms_rls.context_sensitive 
	);
END;
/

@..\excel_pkg
@..\excel_body

@update_tail
