-- Please update version too -- this keeps clean builds in sync
define version=1739
@update_header

DROP PACKAGE CMS.BATCH_IMPORT_PKG;

ALTER TABLE CSR.BATCH_JOB_CMS_IMPORT ADD (
	FAILED_DATA		BLOB NULL,
	JOB_FINISHED	NUMBER(1) DEFAULT 0 NOT NULL
);

ALTER TABLE CSR.BATCH_JOB_CMS_IMPORT ADD CONSTRAINT CHK_JOB_FINISHED CHECK(JOB_FINISHED IN (0,1));

CREATE OR REPLACE PACKAGE CSR.CMS_IMPORT_PKG
AS
PROCEDURE dummy;
END;
/

CREATE OR REPLACE PACKAGE BODY CSR.CMS_IMPORT_PKG
AS
PROCEDURE dummy
AS
BEGIN
	NULL;
END;
END;
/

GRANT EXECUTE ON CSR.CMS_IMPORT_PKG TO web_user;
GRANT EXECUTE ON CSR.CMS_IMPORT_PKG TO cms;

@..\cms_import_pkg
@..\cms_import_body

@update_tail