-- Please update version.sql too -- this keeps clean builds in sync
define version=1165
@update_header

/* Add table "MASS_UNIT" */
CREATE TABLE CT.MASS_UNIT (
    MASS_UNIT_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    SYMBOL VARCHAR2(40) NOT NULL,
    CONVERSION_TO_KG NUMBER(20,10) NOT NULL,
    CONSTRAINT PK_MASS PRIMARY KEY (MASS_UNIT_ID)
);
ALTER TABLE CT.MASS_UNIT ADD
    CHECK (CONVERSION_TO_KG > 0);

/* Add table "POWER_UNIT" */
CREATE TABLE CT.POWER_UNIT (
    POWER_UNIT_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    SYMBOL VARCHAR2(40) NOT NULL,
    CONVERSION_TO_WATT NUMBER(20,10) NOT NULL,
    CONSTRAINT PK_PWR PRIMARY KEY (POWER_UNIT_ID)
);
ALTER TABLE CT.POWER_UNIT ADD CONSTRAINT CC_PWR_CONV_TO_WATT 
    CHECK (CONVERSION_TO_WATT > 0);

/* Add table "HT_CONSUMPTION_TYPE" */
CREATE TABLE CT.HT_CONSUMPTION_TYPE (
    HT_CONSUMPTION_TYPE_ID NUMBER(10) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    CO2_FACTOR NUMBER(30,20) NOT NULL,
    MASS_UNIT_ID NUMBER(10),
    VOLUME_UNIT_ID NUMBER(10),
    POWER_UNIT_ID NUMBER(10),
    CONSTRAINT PK_HT_CONS_TYPE PRIMARY KEY (HT_CONSUMPTION_TYPE_ID),
    CONSTRAINT TCC_MASS_VOL_PWR CHECK ((MASS_UNIT_ID IS NOT NULL AND VOLUME_UNIT_ID IS NULL AND POWER_UNIT_ID IS NULL) OR (MASS_UNIT_ID IS NULL AND VOLUME_UNIT_ID IS NOT NULL AND POWER_UNIT_ID IS NULL) OR (MASS_UNIT_ID IS NULL AND VOLUME_UNIT_ID IS NULL AND POWER_UNIT_ID IS NOT NULL))
);
ALTER TABLE CT.HT_CONSUMPTION_TYPE ADD CONSTRAINT CC_CO2_FACTOR 
    CHECK (CO2_FACTOR>=0 );
	
/* Add table "HT_CONSUMPTION" */
CREATE TABLE CT.HT_CONSUMPTION (
    APP_SID NUMBER(10) NOT NULL,
    COMPANY_SID NUMBER(10) NOT NULL,
    HT_CONSUMPTION_TYPE_ID NUMBER(10) NOT NULL,
    AMOUNT NUMBER(20,10) NOT NULL,
    CONSTRAINT PK_HT_CONS PRIMARY KEY (APP_SID, COMPANY_SID, HT_CONSUMPTION_TYPE_ID)
);
ALTER TABLE CT.HT_CONSUMPTION ADD CONSTRAINT CC_AMOUNT 
    CHECK (AMOUNT > 0);

/* Add table "HT_CONSUMPTION_REGION" */
CREATE TABLE CT.HT_CONSUMPTION_REGION (
    APP_SID NUMBER(10) NOT NULL,
    COMPANY_SID NUMBER(10) NOT NULL,
    HT_CONSUMPTION_TYPE_ID NUMBER(10) NOT NULL,
    REGION_ID NUMBER(10) NOT NULL,
    PCT NUMBER(20,17),
    CONSTRAINT PK_HT_CONS_RG PRIMARY KEY (APP_SID, COMPANY_SID, HT_CONSUMPTION_TYPE_ID, REGION_ID)
);
ALTER TABLE CT.HT_CONSUMPTION_REGION ADD CONSTRAINT CC_PCT 
    CHECK (PCT>=0 AND PCT<=100);

	
--Add constraints
ALTER TABLE CT.HT_CONSUMPTION_TYPE ADD CONSTRAINT MASS_HT_CONS_TYPE 
    FOREIGN KEY (MASS_UNIT_ID) REFERENCES CT.MASS_UNIT (MASS_UNIT_ID);

ALTER TABLE CT.HT_CONSUMPTION_TYPE ADD CONSTRAINT VOLUME_UNIT_HT_CONS_TYPE 
    FOREIGN KEY (VOLUME_UNIT_ID) REFERENCES CT.VOLUME_UNIT (VOLUME_UNIT_ID);

ALTER TABLE CT.HT_CONSUMPTION_TYPE ADD CONSTRAINT PWR_HT_CONS_TYPE 
    FOREIGN KEY (POWER_UNIT_ID) REFERENCES CT.POWER_UNIT (POWER_UNIT_ID);

ALTER TABLE CT.HT_CONSUMPTION_REGION ADD CONSTRAINT HT_CONS_HT_CONS_RG 
    FOREIGN KEY (APP_SID, COMPANY_SID, HT_CONSUMPTION_TYPE_ID) REFERENCES CT.HT_CONSUMPTION (APP_SID,COMPANY_SID,HT_CONSUMPTION_TYPE_ID);

ALTER TABLE CT.HT_CONSUMPTION_REGION ADD CONSTRAINT REGION_HT_CONS_RG 
    FOREIGN KEY (REGION_ID) REFERENCES CT.REGION (REGION_ID);

ALTER TABLE CT.HT_CONSUMPTION ADD CONSTRAINT COMPANY_HT_CONS 
    FOREIGN KEY (APP_SID, COMPANY_SID) REFERENCES CT.COMPANY (APP_SID,COMPANY_SID);

ALTER TABLE CT.HT_CONSUMPTION ADD CONSTRAINT HT_CONS_TYPE_HT_CONS 
    FOREIGN KEY (HT_CONSUMPTION_TYPE_ID) REFERENCES CT.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID);
	
	
--Insert default values	
-- masses -- COMMON 
INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (1, 'Kilogram', 'kg' ,1);
INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (2, 'Pound', 'lb', 0.45359237);
INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (3, 'Metric tonne', 't', 1000);
INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (4, 'UK ton', 'long ton', 1016.047 );
INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (5, 'US ton', 'short ton', 907.18474 );

-- powers -- COMMON 
INSERT INTO ct.power_unit (power_unit_id, description, symbol, conversion_to_watt) VALUES (1, 'Watt', 'W' ,1);
INSERT INTO ct.power_unit (power_unit_id, description, symbol, conversion_to_watt) VALUES (2, 'Kilowatt', 'kW', 1000);
INSERT INTO ct.power_unit (power_unit_id, description, symbol, conversion_to_watt) VALUES (3, 'Megawatt', 'MW', 1000000);

BEGIN
	-- volumes -- COMMON 
	BEGIN
	   INSERT INTO ct.volume_unit (volume_unit_id, description, symbol, conversion_to_litres) VALUES (1, 'Litre', 'l' ,1);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.volume_unit (volume_unit_id, description, symbol, conversion_to_litres) VALUES (2, 'US Gallon', 'Gallon (US)', 0.264172053);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.volume_unit (volume_unit_id, description, symbol, conversion_to_litres) VALUES (3, 'Imperial gallon', 'Gallon (imp)', 0.219969157);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
END;
/

BEGIN
	-- powers -- COMMON 
	BEGIN
	   INSERT INTO ct.power_unit (power_unit_id, description, symbol, conversion_to_watt) VALUES (1, 'Watt', 'W' ,1);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.power_unit (power_unit_id, description, symbol, conversion_to_watt) VALUES (2, 'Kilowatt', 'kW', 1000);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.power_unit (power_unit_id, description, symbol, conversion_to_watt) VALUES (3, 'Megawatt', 'MW', 1000000);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
END;
/

BEGIN
	-- masses -- COMMON 
	BEGIN
	   INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (1, 'Kilogram', 'kg' ,1);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (2, 'Pound', 'lb', 0.45359237);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (3, 'Metric tonne', 't', 1000);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (4, 'UK ton', 'long ton', 1016.047 );
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
	BEGIN
	   INSERT INTO ct.mass_unit (mass_unit_id, description, symbol, conversion_to_kg) VALUES (5, 'US ton', 'short ton', 907.18474 );
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			NULL;
	END;
END;
/

BEGIN
	-- consumption types --HOTSPOT
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (1, 'Electricity', 99, NULL, NULL, 2);
	
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (2, 'Natural gas', 101, NULL, NULL, 2);
	
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (3, 'Coal', 103, 3, NULL, NULL);
	
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (4, 'Oil', 105, NULL, 1, NULL);
	
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (5, 'Petrol', 107, NULL, 1, NULL);
	
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (6, 'Steam', 106, NULL, 1, NULL);
	
	INSERT INTO ct.HT_CONSUMPTION_TYPE (HT_CONSUMPTION_TYPE_ID, DESCRIPTION, CO2_FACTOR, MASS_UNIT_ID, VOLUME_UNIT_ID, POWER_UNIT_ID) 
	VALUES (7, 'Regrigerant', 1522, NULL, 1, NULL);
END;
/

@update_tail
