-- Please update version.sql too -- this keeps clean builds in sync
define version=2313
@update_header

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE ADD IS_RESENDABLE NUMBER(1, 0);

UPDATE CHAIN.QUESTIONNAIRE_TYPE SET IS_RESENDABLE = 1;

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE MODIFY IS_RESENDABLE DEFAULT 1 NOT NULL;

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE ADD CONSTRAINT CHK_IS_RESENDABLE CHECK (IS_RESENDABLE IN (0, 1));

ALTER TABLE CHAIN.QUESTIONNAIRE_TYPE ADD CONSTRAINT CHK_IS_RESENDABLE_ON_EXPIRY 
	CHECK ((IS_RESENDABLE = 0 AND AUTO_RESEND_ON_EXPIRY = 0) OR IS_RESENDABLE = 1);

@../chain/questionnaire_body
@../chain/invitation_body
	
@update_tail