-- Please update version.sql too -- this keeps clean builds in sync
define version=28
@update_header

alter table trash add (so_name varchar2(255));


CREATE or replace VIEW SHEET_WITH_LAST_ACTION AS
SELECT SH.SHEET_ID, SH.DELEGATION_SID, SH.last_sheet_history_id, SH.START_DTM, SH.END_DTM, SH.REMINDER_DTM, SH.SUBMISSION_DTM, SHE.SHEET_ACTION_ID LAST_ACTION_ID, SHE.FROM_USER_SID LAST_ACTION_FROM_USER_SID, SHE.ACTION_DTM LAST_ACTION_DTM, SHE.NOTE LAST_ACTION_NOTE, SHE.TO_DELEGATION_SID LAST_ACTION_TO_DELEGATION_SID,
            CASE WHEN SYSDATE >= submission_dtm AND SHE.SHEET_ACTION_ID IN (0,2) THEN 1 --csr_data_pkg.ACTION_WAITING, csr_data_pkg.ACTION_RETURNED
             	 WHEN SYSDATE >= reminder_dtm AND SHE.SHEET_ACTION_ID IN (0,2) THEN 2 --csr_data_pkg.ACTION_WAITING, csr_data_pkg.ACTION_RETURNED
                 ELSE 3
            END STATUS, SH.LAST_REMINDED_DTM
FROM SHEET_HISTORY SHE, SHEET SH
WHERE SH.LAST_SHEET_HISTORY_ID = SHE.SHEET_HISTORY_ID AND SHE.SHEET_ID = SH.SHEET_ID
 AND SHE.SHEET_ID = SH.SHEET_ID AND SH.LAST_SHEET_HISTORY_ID = SHE.SHEET_HISTORY_ID
;

INSERT INTO ALERT_TYPE ( ALERT_TYPE_ID, DESCRIPTION, GET_DATA_SP ) VALUES ( 5, 'Delegation data reminder', 'alert_pkg.GetAlerts_DelegDataRemind');  



alter table survey rename to old_survey;
alter table survey_response rename to old_survey_response;
alter table survey_response_answer rename to old_survey_response_answer;


ALTER TABLE OLD_SURVEY_RESPONSE rename CONSTRAINT RefSURVEY192 TO RefOLDSURVEY192;

-- 
-- TABLE: SURVEY 
--

CREATE TABLE SURVEY(
    SURVEY_SID      NUMBER(10, 0)    NOT NULL,
    LABEL           VARCHAR2(255)    NOT NULL,
    CSR_ROOT_SID    NUMBER(10, 0)    NOT NULL,
    SURVEY_XML      CLOB,
    CONSTRAINT PK150 PRIMARY KEY (SURVEY_SID)
)
;



-- 
-- TABLE: SURVEY_RESPONSE 
--

CREATE TABLE SURVEY_RESPONSE(
    SURVEY_SID            NUMBER(10, 0)    NOT NULL,
    SURVEY_RESPONSE_ID    NUMBER(10, 0)    NOT NULL,
    USER_SID              NUMBER(10, 0),
    USER_NAME             VARCHAR2(255),
    RESPONSE_XML          CLOB,
    LAST_SAVED_DTM        DATE             NOT NULL,
    STATUS                CHAR(1)          NOT NULL,
    CONSTRAINT PK151 PRIMARY KEY (SURVEY_RESPONSE_ID)
)
;

ALTER TABLE SURVEY ADD CONSTRAINT RefCUSTOMER251 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;




-- 
-- TABLE: SURVEY_RESPONSE 
--

ALTER TABLE SURVEY_RESPONSE ADD CONSTRAINT RefSURVEY192 
    FOREIGN KEY (SURVEY_SID)
    REFERENCES SURVEY(SURVEY_SID)
;

ALTER TABLE SURVEY_RESPONSE ADD CONSTRAINT RefCSR_USER249 
    FOREIGN KEY (USER_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;



@update_tail
