-- Please update version.sql too -- this keeps clean builds in sync
define version=2801
define minor_version=0
define is_combined=1
@update_header

-- *** DDL ***
-- Create tables
DROP TABLE CSR.TEMP_METER_CONSUMPTION;
CREATE GLOBAL TEMPORARY TABLE CSR.TEMP_METER_CONSUMPTION(
	REGION_SID			NUMBER(10)			NOT NULL,
	PRIORITY			NUMBER(10)			NOT NULL,
	START_DTM			DATE				NOT NULL,
	END_DTM				DATE				NOT NULL,
	VAL_NUMBER			NUMBER(24, 10),
	PER_DIEM			NUMBER(24, 10),
	RAW_DATA_ID			NUMBER(10)
) ON COMMIT DELETE ROWS;

DROP TABLE CSR.METER_INSERT_DATA;
CREATE GLOBAL TEMPORARY TABLE CSR.METER_INSERT_DATA 
(
	METER_INPUT_ID		NUMBER(10)					NOT NULL,
	START_DTM   		TIMESTAMP WITH TIME ZONE	NOT NULL,
	END_DTM     		TIMESTAMP WITH TIME ZONE,
	CONSUMPTION 		NUMBER(24,10)
)
ON COMMIT DELETE ROWS;

DROP TABLE CSR.TEMP_METER_CONSUMPTION;
CREATE GLOBAL TEMPORARY TABLE CSR.TEMP_METER_CONSUMPTION(
	REGION_SID			NUMBER(10)			NOT NULL,
	METER_INPUT_ID		NUMBER(10)			NOT NULL,
	PRIORITY			NUMBER(10)			NOT NULL,
	START_DTM			DATE				NOT NULL,
	END_DTM				DATE				NOT NULL,
	VAL_NUMBER			NUMBER(24, 10),
	PER_DIEM			NUMBER(24, 10),
	RAW_DATA_ID			NUMBER(10)
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE CSR.TEMP_METER_GAPS(
	REGION_SID				NUMBER(10)		NOT NULL,
	METER_INPUT_ID			NUMBER(10)		NOT NULL,
	START_DTM				DATE			NOT NULL,
	END_DTM					DATE			NOT NULL
) ON COMMIT DELETE ROWS;


CREATE TABLE CSR.METER_DATA_PRIORITY(
	APP_SID				NUMBER(10, 0)		DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	PRIORITY			NUMBER(10, 0)		NOT NULL,
	LABEL				VARCHAR2(1024)		NOT NULL,
	LOOKUP_KEY			VARCHAR2(256),
	IS_INPUT			NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	IS_OUTPUT			NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	IS_PATCH			NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	IS_AUTO_PATCH		NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	CHECK (IS_INPUT IN(0,1)),
	CHECK (IS_OUTPUT IN(0,1)),
	CHECK (IS_PATCH IN(0,1)),
	CHECK (IS_AUTO_PATCH IN(0,1)),
	CONSTRAINT PK_METER_DATA_PRIORITY PRIMARY KEY (APP_SID, PRIORITY)
);

CREATE TABLE CSR.METER_PATCH_DATA(
	APP_SID				NUMBER(10, 0)		DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	REGION_SID			NUMBER(10, 0)		NOT NULL,
	METER_INPUT_ID		NUMBER(10, 0)		NOT NULL,
	PRIORITY			NUMBER(10, 0)		NOT NULL,
	START_DTM			DATE				NOT NULL,
	END_DTM				DATE				NOT NULL,
	CONSUMPTION			NUMBER(24, 10),
	UPDATED_DTM			DATE				DEFAULT SYSDATE NOT NULL,
	CONSTRAINT PK_METER_PATCH_DATA PRIMARY KEY (APP_SID, REGION_SID, METER_INPUT_ID, PRIORITY, START_DTM)
);

CREATE TABLE CSR.METER_AGGREGATOR(
	AGGREGATOR			VARCHAR2(32)		NOT NULL,
	LABEL				VARCHAR2(256)		NOT NULL,
	AGGR_PROC			VARCHAR2(256)		NOT NULL,
	CONSTRAINT PK_METER_AGGREGATOR PRIMARY KEY (AGGREGATOR)
);

CREATE TABLE CSR.METER_INPUT(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	LABEL					VARCHAR2(1024)	NOT NULL,
	LOOKUP_KEY				VARCHAR2(256)	NOT NULL,
	IS_CONSUMPTION_BASED	NUMBER(1, 0)	DEFAULT 1 NOT NULL,
	PATCH_HELPER			VARCHAR2(256),
	GAP_FINDER				VARCHAR2(256),
	CHECK (IS_CONSUMPTION_BASED IN(0,1)),
	CONSTRAINT PK_METER_INPUT PRIMARY KEY (APP_SID, METER_INPUT_ID)
);
CREATE UNIQUE INDEX CSR.UK_INPUT_LOOKUP_KEY ON CSR.METER_INPUT(APP_SID, LOOKUP_KEY);

CREATE TABLE CSR.METER_INPUT_AGGR_IND(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	REGION_SID				NUMBER(10, 0)	NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	AGGREGATOR				VARCHAR2(32)	NOT NULL,
	IND_SID					NUMBER(10, 0),
	MEASURE_SID				NUMBER(10, 0),
	MEASURE_CONVERSION_ID	NUMBER(10, 0),
	CONSTRAINT PK_METER_INPUT_AGGR_IND PRIMARY KEY (APP_SID, REGION_SID, METER_INPUT_ID, AGGREGATOR)
);

CREATE TABLE CSR.METER_INPUT_AGGREGATOR(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	AGGREGATOR				VARCHAR2(32)	NOT NULL,
	AGGR_PROC				VARCHAR2(256),
	CONSTRAINT PK_METER_INPUT_AGGREGATOR PRIMARY KEY (APP_SID, METER_INPUT_ID, AGGREGATOR)
);


CREATE TABLE CSR.METER_PATCH_JOB(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	REGION_SID				NUMBER(10, 0)	NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	START_DTM				DATE			NOT NULL,
	END_DTM					DATE			NOT NULL,
	CREATED_DTM				DATE			DEFAULT SYSDATE NOT NULL,
	CONSTRAINT PK_METER_PATCH_JOB PRIMARY KEY (APP_SID, REGION_SID, METER_INPUT_ID)
);

CREATE TABLE CSR.METER_PATCH_BATCH_JOB(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	BATCH_JOB_ID			NUMBER(10, 0)	NOT NULL,
	REGION_SID				NUMBER(10, 0)	NOT NULL,
	IS_REMOVE				NUMBER(1, 0)	DEFAULT 0,
	CREATED_DTM				DATE			DEFAULT SYSDATE NOT NULL,
	CHECK(IS_REMOVE IN (0,1)),
	CONSTRAINT PK_METER_PATCH_BATCH_JOB PRIMARY KEY (APP_SID, BATCH_JOB_ID)
);

CREATE TABLE CSR.METER_PATCH_BATCH_DATA(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	BATCH_JOB_ID			NUMBER(10, 0)	NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	PRIORITY				NUMBER(10, 0)	NOT NULL,
	START_DTM				DATE			NOT NULL,
	END_DTM					DATE			NOT NULL,
	PERIOD_TYPE				VARCHAR2(32),
	CONSUMPTION				NUMBER(24, 10),
	CONSTRAINT PK_METER_PATCH_BATCH_DATA PRIMARY KEY (APP_SID, BATCH_JOB_ID, METER_INPUT_ID, PRIORITY, START_DTM)
);

CREATE TABLE CSR.METER_DATA_COVERAGE_IND(
	APP_SID					NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	PRIORITY				NUMBER(10, 0)	NOT NULL,
	IND_SID					NUMBER(10, 0)	NOT NULL,
	CONSTRAINT PK_METER_DATA_COVERAGE_IND PRIMARY KEY (APP_SID, METER_INPUT_ID, PRIORITY)
);

CREATE TABLE CSRIMP.METER_DATA_PRIORITY(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRIORITY				NUMBER(10, 0)		NOT NULL,
	LABEL					VARCHAR2(1024)		NOT NULL,
	LOOKUP_KEY				VARCHAR2(256),
	IS_INPUT				NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	IS_OUTPUT				NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	IS_PATCH				NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	IS_AUTO_PATCH			NUMBER(1, 0)		DEFAULT 0 NOT NULL,
	CHECK (IS_INPUT IN(0,1)),
	CHECK (IS_OUTPUT IN(0,1)),
	CHECK (IS_PATCH IN(0,1)),
	CHECK (IS_AUTO_PATCH IN(0,1)),
	CONSTRAINT PK_METER_DATA_PRIORITY PRIMARY KEY (CSRIMP_SESSION_ID, PRIORITY),
	CONSTRAINT FK_METER_DATA_PRIORITY FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_PATCH_DATA(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID				NUMBER(10, 0)		NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	PRIORITY				NUMBER(10, 0)		NOT NULL,
	START_DTM				DATE				NOT NULL,
	END_DTM					DATE				NOT NULL,
	CONSUMPTION				NUMBER(24, 10),
	UPDATED_DTM				DATE				DEFAULT SYSDATE NOT NULL,
	CONSTRAINT PK_METER_PATCH_DATA PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID, METER_INPUT_ID, PRIORITY, START_DTM),
	CONSTRAINT FK_METER_PATCH_DATA FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_INPUT(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	LABEL					VARCHAR2(1024)		NOT NULL,
	LOOKUP_KEY				VARCHAR2(256)		NOT NULL,
	IS_CONSUMPTION_BASED	NUMBER(1, 0)		DEFAULT 1 NOT NULL,
	PATCH_HELPER			VARCHAR2(256),
	GAP_FINDER				VARCHAR2(256),
	CHECK (IS_CONSUMPTION_BASED IN(0,1)),
	CONSTRAINT PK_METER_INPUT PRIMARY KEY (CSRIMP_SESSION_ID, METER_INPUT_ID),
	CONSTRAINT FK_METER_INPUT FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);
CREATE UNIQUE INDEX CSRIMP.UK_INPUT_LOOKUP_KEY ON CSRIMP.METER_INPUT(CSRIMP_SESSION_ID, LOOKUP_KEY);

CREATE TABLE CSRIMP.METER_INPUT_AGGR_IND(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID				NUMBER(10, 0)		NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	AGGREGATOR				VARCHAR2(32)		NOT NULL,
	IND_SID					NUMBER(10, 0),
	MEASURE_SID				NUMBER(10, 0),
	MEASURE_CONVERSION_ID	NUMBER(10, 0),
	CONSTRAINT PK_METER_INPUT_AGGR_IND PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID, METER_INPUT_ID, AGGREGATOR),
	CONSTRAINT FK_METER_INPUT_AGGR_IND FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_INPUT_AGGREGATOR(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	AGGREGATOR				VARCHAR2(32)		NOT NULL,
	AGGR_PROC				VARCHAR2(256),
	CONSTRAINT PK_METER_INPUT_AGGREGATOR PRIMARY KEY (CSRIMP_SESSION_ID, METER_INPUT_ID, AGGREGATOR),
	CONSTRAINT FK_METER_INPUT_AGGREGATOR FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_PATCH_JOB(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID				NUMBER(10, 0)		NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	START_DTM				DATE				NOT NULL,
	END_DTM					DATE				NOT NULL,
	CREATED_DTM				DATE				DEFAULT SYSDATE NOT NULL,
	CONSTRAINT PK_METER_PATCH_JOB PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID, METER_INPUT_ID),
	CONSTRAINT FK_METER_PATCH_JOB FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_PATCH_BATCH_JOB(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BATCH_JOB_ID			NUMBER(10, 0)		NOT NULL,
	REGION_SID				NUMBER(10, 0)		NOT NULL,
	IS_REMOVE				NUMBER(1, 0)		DEFAULT 0,
	CREATED_DTM				DATE				DEFAULT SYSDATE NOT NULL,
	CHECK(IS_REMOVE IN (0,1)),
	CONSTRAINT PK_METER_PATCH_BATCH_JOB PRIMARY KEY (CSRIMP_SESSION_ID, BATCH_JOB_ID),
	CONSTRAINT FK_METER_PATCH_BATCH_JOB FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_PATCH_BATCH_DATA(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BATCH_JOB_ID			NUMBER(10, 0)		NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	PRIORITY				NUMBER(10, 0)		NOT NULL,
	START_DTM				DATE				NOT NULL,
	END_DTM					DATE				NOT NULL,
	PERIOD_TYPE				VARCHAR2(32),
	CONSUMPTION				NUMBER(24, 10),
	CONSTRAINT PK_METER_PATCH_BATCH_DATA PRIMARY KEY (CSRIMP_SESSION_ID, BATCH_JOB_ID, METER_INPUT_ID, PRIORITY, START_DTM),
	CONSTRAINT FK_METER_PATCH_BATCH_DATA FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_DATA_COVERAGE_IND(
	CSRIMP_SESSION_ID		NUMBER(10)			DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	METER_INPUT_ID			NUMBER(10, 0)		NOT NULL,
	PRIORITY				NUMBER(10, 0)		NOT NULL,
	IND_SID					NUMBER(10, 0)		NOT NULL,
	CONSTRAINT PK_METER_DATA_COVERAGE_IND PRIMARY KEY (CSRIMP_SESSION_ID, METER_INPUT_ID, PRIORITY),
	CONSTRAINT FK_METER_DATA_COVERAGE_IND FOREIGN KEY
		(CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
		ON DELETE CASCADE
);

-- Alter sequence
-- Can't simply rename a sequence
DECLARE
	v_next_seq		NUMBER;
BEGIN
	SELECT csr.live_data_duration_id_seq.NEXTVAL
	  INTO v_next_seq
	  FROM DUAL;
	EXECUTE IMMEDIATE('CREATE SEQUENCE CSR.METER_BUCKET_ID_SEQ START WITH '||v_next_seq||' INCREMENT BY 1 NOMINVALUE NOMAXVALUE CACHE 20 NOORDER');
END;
/
DROP SEQUENCE CSR.LIVE_DATA_DURATION_ID_SEQ;

-- Alter tables
ALTER TABLE CSR.LIVE_DATA_DURATION RENAME TO METER_BUCKET;

DECLARE
	v_cons_name		VARCHAR2(30);
BEGIN
	-- Find the name of the primary key
	SELECT constraint_name
	  INTO v_cons_name
	  FROM all_constraints
	 WHERE owner = 'CSR'
	   AND table_name = 'METER_BUCKET'
	   AND constraint_type = 'P';
	
	-- Drop the primary key
	EXECUTE IMMEDIATE('ALTER TABLE CSR.METER_BUCKET RENAME CONSTRAINT  '||v_cons_name|| ' TO PK_METER_BUCKET');
END;
/

ALTER TABLE CSR.METER_BUCKET RENAME COLUMN IS_SYSTEM_PERIOD TO IS_EXPORT_PERIOD;
ALTER TABLE CSR.METER_BUCKET RENAME COLUMN LIVE_DATA_DURATION_ID TO METER_BUCKET_ID;
ALTER TABLE CSR.METER_LIVE_DATA RENAME COLUMN LIVE_DATA_DURATION_ID TO METER_BUCKET_ID;

BEGIN
	-- Remove existing check constraints
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSR'
		   AND table_name = 'METER_BUCKET'
		   AND constraint_type = 'C'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSR.METER_BUCKET DROP CONSTRAINT  '||r.constraint_name);
	END LOOP;
END;
/

ALTER TABLE CSR.METER_BUCKET ADD(
	PERIOD_SET_ID			NUMBER(10),
	PERIOD_INTERVAL_ID		NUMBER(10),
	HIGH_RESOLUTION_ONLY	NUMBER(1) DEFAULT 0 NOT NULL,
	CHECK (IS_HOURS = 0 OR (IS_HOURS  = 1 AND IS_MINUTES = 0 AND IS_WEEKS = 0 AND IS_MONTHS = 0 AND PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL)),
	CHECK (IS_WEEKS = 0 OR (IS_WEEKS = 1 AND IS_MINUTES = 0 AND IS_HOURS = 0 AND IS_MONTHS = 0 AND PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL)),
	CHECK (IS_MINUTES = 0 OR (IS_MINUTES  = 1 AND IS_HOURS = 0 AND IS_WEEKS = 0 AND IS_MONTHS = 0 AND PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL)),
	CHECK (WEEK_START_DAY IS NULL OR IS_WEEKS = 1),
	CHECK (START_MONTH IS NULL OR IS_MONTHS = 1),
	CHECK ((PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL) OR (PERIOD_SET_ID IS NOT NULL AND PERIOD_INTERVAL_ID IS NOT NULL AND IS_MINUTES = 0 AND IS_HOURS = 0 AND IS_WEEKS = 0)),
	CHECK (HIGH_RESOLUTION_ONLY IN (0,1))
);

BEGIN
	-- All export buckets must have period set and interval
	UPDATE csr.meter_bucket
	   SET period_set_id = 1,
	       period_interval_id = 1
	 WHERE is_export_period = 1
	   AND period_set_id IS NULL;
END;
/

ALTER TABLE CSR.METER_BUCKET ADD(
	CHECK (IS_MONTHS = 0 OR (IS_MONTHS = 1 AND IS_MINUTES = 0 AND IS_HOURS = 0 AND IS_WEEKS = 0 AND (IS_EXPORT_PERIOD = 0 OR (PERIOD_SET_ID = 1 AND PERIOD_INTERVAL_ID = 1)))),
	CHECK (IS_EXPORT_PERIOD IN (0,1) AND (IS_EXPORT_PERIOD = 0 OR (PERIOD_SET_ID IS NOT NULL AND PERIOD_INTERVAL_ID IS NOT NULL)))
);


ALTER TABLE CSR.METER_ALARM_STATISTIC ADD (
	METER_INPUT_ID			NUMBER(10, 0),
	AGGREGATOR				VARCHAR2(32),
	METER_BUCKET_ID			NUMBER(10),
	ALL_METERS				NUMBER(1)		DEFAULT 0 NOT NULL,
	NOT_BEFORE_DTM			DATE,
	LOOKUP_KEY				VARCHAR2(256),
	CHECK(ALL_METERS IN(0,1))
);

CREATE UNIQUE INDEX CSR.UK_LOOKUP_KEY ON CSR.METER_ALARM_STATISTIC(APP_SID, NVL(LOOKUP_KEY, STATISTIC_ID));

DECLARE
	v_bucket_id				csr.meter_bucket.meter_bucket_id%TYPE;
BEGIN
	-- Aggregator types
	INSERT INTO csr.meter_aggregator(aggregator, label, aggr_proc) VALUES ('SUM', 'Sum', 'csr.meter_aggr_pkg.Sum');
	INSERT INTO csr.meter_aggregator(aggregator, label, aggr_proc) VALUES ('AVERAGE', 'Average', 'csr.meter_aggr_pkg.Average');
	
	FOR a IN (
		SELECT app_sid
		  FROM csr.meter_source_type
		UNION
		SELECT app_sid
		  FROM csr.meter_live_data
		UNION
		SELECT app_sid
		  FROM csr.meter_orphan_data
		UNION
		SELECT app_sid
		  FROM csr.meter_patch_data
		UNION
		SELECT app_sid
		  FROM csr.meter_reading_data
		UNION
		SELECT app_sid
		  FROM csr.meter_source_data
	) LOOP
		-- Input types
		INSERT INTO csr.meter_input (app_sid, meter_input_id, label, lookup_key, is_consumption_based) VALUES (a.app_sid, 1, 'Consumption', 'CONSUMPTION', 1);
		INSERT INTO csr.meter_input (app_sid, meter_input_id, label, lookup_key, is_consumption_based) VALUES (a.app_sid, 2, 'Cost','COST', 1);
		
		-- Input -> aggregator type mappings
		INSERT INTO csr.meter_input_aggregator(app_sid, meter_input_id, aggregator) VALUES(a.app_sid, 1, 'SUM');
		INSERT INTO csr.meter_input_aggregator(app_sid, meter_input_id, aggregator) VALUES(a.app_sid, 2, 'SUM');
		
		-- Meter consumption indicators
		INSERT INTO csr.meter_input_aggr_ind (app_sid, region_sid, meter_input_id, aggregator, ind_sid, measure_sid, measure_conversion_id)
			SELECT m.app_sid, m.region_sid, 1, 'SUM', m.primary_ind_sid, i.measure_sid, m.primary_measure_conversion_id
			  FROM csr.all_meter m
			  JOIN csr.ind i ON i.app_sid = m.app_sid AND i.ind_sid = m.primary_ind_sid
			 WHERE m.app_sid = a.app_sid
			  AND m.primary_measure_conversion_id IS NULL
			UNION
			SELECT m.app_sid, m.region_sid, 1, 'SUM', m.primary_ind_sid, i.measure_sid, m.primary_measure_conversion_id
			  FROM csr.all_meter m
			  JOIN csr.ind i ON i.app_sid = m.app_sid AND i.ind_sid = m.primary_ind_sid
			  JOIN csr.measure_conversion mc ON mc.app_sid = i.app_sid AND mc.measure_sid = i.measure_sid AND mc.measure_conversion_id = m.primary_measure_conversion_id
			 WHERE m.app_sid = a.app_sid
		;
			 
		-- Meter cost indicators
		INSERT INTO csr.meter_input_aggr_ind (app_sid, region_sid, meter_input_id, aggregator, ind_sid, measure_sid, measure_conversion_id)
			SELECT m.app_sid, m.region_sid, 2, 'SUM', m.cost_ind_sid, i.measure_sid, m.cost_measure_conversion_id
			  FROM csr.all_meter m
			  JOIN csr.ind i ON i.app_sid = m.app_sid AND i.ind_sid = m.cost_ind_sid
			 WHERE m.app_sid = a.app_sid
			   AND m.cost_measure_conversion_id IS NULL
			UNION
			SELECT m.app_sid, m.region_sid, 2, 'SUM', m.cost_ind_sid, i.measure_sid, m.cost_measure_conversion_id
			  FROM csr.all_meter m
			  JOIN csr.ind i ON i.app_sid = m.app_sid AND i.ind_sid = m.cost_ind_sid
			  JOIN csr.measure_conversion mc ON mc.app_sid = i.app_sid AND mc.measure_sid = i.measure_sid AND mc.measure_conversion_id = m.cost_measure_conversion_id
			 WHERE m.app_sid = a.app_sid
		;

		-- Patch prority
		INSERT INTO csr.meter_data_priority (app_sid, priority, label, lookup_key, is_input, is_output, is_patch, is_auto_patch) VALUES (a.app_sid, 1, 'Auto pathcer', 'AUTO', 1, 0, 0, 1);
		INSERT INTO csr.meter_data_priority (app_sid, priority, label, lookup_key, is_input, is_output, is_patch, is_auto_patch) VALUES (a.app_sid, 2, 'Low resolution', 'LO_RES', 1, 0, 0, 0);
		INSERT INTO csr.meter_data_priority (app_sid, priority, label, lookup_key, is_input, is_output, is_patch, is_auto_patch) VALUES (a.app_sid, 3, 'High resolution', 'HI_RES', 1, 0, 0, 0);
		INSERT INTO csr.meter_data_priority (app_sid, priority, label, lookup_key, is_input, is_output, is_patch, is_auto_patch) VALUES (a.app_sid, 4, 'User patch', 'PATCH_01', 0, 0, 1, 0);
		INSERT INTO csr.meter_data_priority (app_sid, priority, label, lookup_key, is_input, is_output, is_patch, is_auto_patch) VALUES (a.app_sid, 100, 'Patched output', 'OUTPUT', 0, 1, 0, 0);

	END LOOP;

	UPDATE csr.meter_alarm_statistic
	   SET meter_input_id = 1,
	   aggregator = 'SUM';

	-- Stats that use daily buckets
	FOR r IN (
		SELECT DISTINCT app_sid
		  FROM csr.meter_alarm_statistic
	) LOOP
		BEGIN
			SELECT meter_bucket_id
			  INTO v_bucket_id
			  FROM csr.meter_bucket
			 WHERE app_sid = r.app_sid
			   AND is_hours = 1
			   AND duration = 24;
			   
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				INSERT INTO csr.meter_bucket (app_sid, meter_bucket_id, description, duration, is_hours)
				  VALUES (r.app_sid, csr.meter_bucket_id_seq.NEXTVAL, 'Daily', 24, 1)
				  RETURNING meter_bucket_id INTO v_bucket_id;
		END;
		
		-- Set the bucket id
		UPDATE csr.meter_alarm_statistic
		   SET meter_bucket_id = v_bucket_id
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) NOT IN (
			'meter_alarm_stat_pkg.computewkgdaycoreavg',
			'meter_alarm_stat_pkg.computewkgdaycore',
			'meter_alarm_stat_pkg.computewkgdaynoncoreavg',
			'meter_alarm_stat_pkg.computewkgdaynoncore',
			'csr.meter_alarm_stat_pkg.computewkgdaycoreavg',
			'csr.meter_alarm_stat_pkg.computewkgdaycore',
			'csr.meter_alarm_stat_pkg.computewkgdaynoncoreavg',
			'csr.meter_alarm_stat_pkg.computewkgdaynoncore'
		);
	END LOOP;
	
	-- Stats that use hourly buckets
	FOR r IN (
		SELECT DISTINCT app_sid
		  FROM csr.meter_alarm_statistic
	) LOOP
		BEGIN
			-- Most existing stats use a daily bucket
			SELECT meter_bucket_id
			  INTO v_bucket_id
			  FROM csr.meter_bucket
			 WHERE app_sid = r.app_sid
			   AND is_hours = 1
			   AND duration = 1;
			   
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				INSERT INTO csr.meter_bucket (app_sid, meter_bucket_id, description, duration, is_hours)
				  VALUES (r.app_sid, csr.meter_bucket_id_seq.NEXTVAL, 'Hourly', 1, 1)
				  RETURNING meter_bucket_id INTO v_bucket_id;
		END;
		
		-- Set the bucket id
		UPDATE csr.meter_alarm_statistic
		   SET meter_bucket_id = v_bucket_id
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computewkgdaycoreavg',
			'meter_alarm_stat_pkg.computewkgdaycore',
			'meter_alarm_stat_pkg.computewkgdaynoncoreavg',
			'meter_alarm_stat_pkg.computewkgdaynoncore',
			'csr.meter_alarm_stat_pkg.computewkgdaycoreavg',
			'csr.meter_alarm_stat_pkg.computewkgdaycore',
			'csr.meter_alarm_stat_pkg.computewkgdaynoncoreavg',
			'csr.meter_alarm_stat_pkg.computewkgdaynoncore'
		);
		   
		-- Set lookup keys for day averages
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'MONDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgmondayusage',
			'csr.meter_alarm_stat_pkg.computeavgmondayusage'
		 );
		   
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'TUESDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgtuesdayusage',
			'csr.meter_alarm_stat_pkg.computeavgtuesdayusage'
		 );
		
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'WEDNESDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgwednesdayusage',
			'csr.meter_alarm_stat_pkg.computeavgwednesdayusage'
		 );
		   
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'THURSDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgthursdayusage',
			'csr.meter_alarm_stat_pkg.computeavgthursdayusage'
		 );
		   
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'FRIDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgfridayusage',
			'csr.meter_alarm_stat_pkg.computeavgfridayusage'
		 );
		   
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'SATURDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgsaturdayusage',
			'csr.meter_alarm_stat_pkg.computeavgsaturdayusage'
		 );
		   
		UPDATE csr.meter_alarm_statistic
		   SET lookup_key = 'SUNDAY_AVG'
		 WHERE app_sid = r.app_sid
		   AND LOWER(comp_proc) IN (
			'meter_alarm_stat_pkg.computeavgsundayusage',
			'csr.meter_alarm_stat_pkg.computeavgsundayusage'
		 );
	END LOOP;
END;
/

-- UPDATING ALL THE ROWS OF THESE TABLES TAKES FAR TOO LONG DUE TO THE NUMBER OF ROWS OF DATA.
-- IT'S FAR QUICKER TO RECREATE THE TABLES WITH THE NEW COLUMNS ALREADY SET TO THE DEFAULT VALUES

CREATE TABLE CSR.METER_ORPHAN_DATA_NEW
AS
SELECT
	APP_SID,
	SERIAL_ID,
	START_DTM,
	METER_RAW_DATA_ID,
	END_DTM,
	CONSUMPTION,
	RELATED_LOCATION_1,
	RELATED_LOCATION_2,
	UOM,
	CAST (1 AS NUMBER(10)) METER_INPUT_ID,
	CAST (3 AS NUMBER(10)) PRIORITY
  FROM csr.meter_orphan_data
;

ALTER TABLE CSR.METER_ORPHAN_DATA_NEW MODIFY (
	APP_SID				NUMBER(10)	DEFAULT SYS_CONTEXT('SECURITY', 'APP'),
	METER_INPUT_ID		NUMBER(10)	NOT NULL,
	PRIORITY			NUMBER(10)	NOT NULL
);

-- Drop old FKs
BEGIN
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSR'
		   AND table_name = 'METER_ORPHAN_DATA'
		   AND constraint_type = 'R'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSR.METER_ORPHAN_DATA DROP CONSTRAINT '||r.constraint_name);

	END LOOP;
END;
/

-- Swap tables
ALTER TABLE CSR.METER_ORPHAN_DATA RENAME TO METER_ORPHAN_DATA_OLD;
ALTER TABLE CSR.METER_ORPHAN_DATA_NEW RENAME TO METER_ORPHAN_DATA;



CREATE TABLE CSR.METER_READING_DATA_NEW
AS
SELECT
	APP_SID,
	REGION_SID,
	READING_DTM,
	METER_RAW_DATA_ID,
	RAW_UOM,
	RAW_VAL,
	CAST (1 AS NUMBER(10)) METER_INPUT_ID,
	CAST (3 AS NUMBER(10)) PRIORITY,
	CAST (NULL AS NUMBER(24, 10)) VAL
  FROM csr.meter_reading_data
;

ALTER TABLE CSR.METER_READING_DATA_NEW MODIFY (
	APP_SID				NUMBER(10)	DEFAULT SYS_CONTEXT('SECURITY', 'APP'),
	METER_INPUT_ID		NUMBER(10)	NOT NULL,
	PRIORITY			NUMBER(10)	NOT NULL
);

-- Drop FKs
BEGIN
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSR'
		   AND table_name = 'METER_READING_DATA'
		   AND constraint_type = 'R'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSR.METER_READING_DATA DROP CONSTRAINT '||r.constraint_name);

	END LOOP;
END;
/

-- Swap tables
ALTER TABLE CSR.METER_READING_DATA RENAME TO METER_READING_DATA_OLD;
ALTER TABLE CSR.METER_READING_DATA_NEW RENAME TO METER_READING_DATA;


CREATE TABLE CSR.METER_SOURCE_DATA_NEW
AS
SELECT
	APP_SID,
	REGION_SID,
	START_DTM,
	METER_RAW_DATA_ID,
	END_DTM,
	CONSUMPTION,
	RAW_UOM,
	RAW_CONSUMPTION,
	CAST (1 AS NUMBER(10)) METER_INPUT_ID,
	CAST (3 AS NUMBER(10)) PRIORITY
  FROM csr.meter_source_data
;

ALTER TABLE CSR.METER_SOURCE_DATA_NEW MODIFY (
	APP_SID				NUMBER(10)	DEFAULT SYS_CONTEXT('SECURITY', 'APP'),
	METER_INPUT_ID		NUMBER(10)	NOT NULL,
	PRIORITY			NUMBER(10)	NOT NULL
);

-- Drop FKs
BEGIN
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSR'
		   AND table_name = 'METER_SOURCE_DATA'
		   AND constraint_type = 'R'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSR.METER_SOURCE_DATA DROP CONSTRAINT '||r.constraint_name);

	END LOOP;
END;
/

-- Swap tables
ALTER TABLE CSR.METER_SOURCE_DATA RENAME TO METER_SOURCE_DATA_OLD;
ALTER TABLE CSR.METER_SOURCE_DATA_NEW RENAME TO METER_SOURCE_DATA;


CREATE TABLE CSR.METER_LIVE_DATA_NEW
AS
SELECT
	APP_SID,
	REGION_SID,
	METER_BUCKET_ID,
	START_DTM,
	METER_RAW_DATA_ID,
	END_DTM,
	MODIFIED_DTM,
	CONSUMPTION,
	CAST (1 AS NUMBER(10)) METER_INPUT_ID,
	CAST('SUM' AS VARCHAR2(32)) AGGREGATOR,
	CAST (3 AS NUMBER(10)) PRIORITY
  FROM csr.meter_live_data
;

ALTER TABLE CSR.METER_LIVE_DATA_NEW MODIFY (
	APP_SID				NUMBER(10)		DEFAULT SYS_CONTEXT('SECURITY', 'APP'),
	MODIFIED_DTM		DATE			DEFAULT SYSDATE,
	METER_INPUT_ID		NUMBER(10)		NOT NULL,
	AGGREGATOR			VARCHAR2(32)	NOT NULL,
	PRIORITY			NUMBER(10)		NOT NULL,
	CONSTRAINT PK_METER_LIVE_DATA PRIMARY KEY (APP_SID, REGION_SID, METER_BUCKET_ID, METER_INPUT_ID, AGGREGATOR, PRIORITY, START_DTM)
);

-- Drop FKs
BEGIN
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSR'
		   AND table_name = 'METER_LIVE_DATA'
		   AND constraint_type = 'R'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSR.METER_LIVE_DATA DROP CONSTRAINT '||r.constraint_name);

	END LOOP;
END;
/

-- Swap tables
ALTER TABLE CSR.METER_LIVE_DATA RENAME TO METER_LIVE_DATA_OLD;
ALTER TABLE CSR.METER_LIVE_DATA_NEW RENAME TO METER_LIVE_DATA;



ALTER TABLE CSR.METER_ALARM_STATISTIC MODIFY (
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	AGGREGATOR				VARCHAR2(32)	NOT NULL,
	METER_BUCKET_ID			NUMBER(10, 0)	NOT NULL
);

ALTER TABLE CSR.METER_ALARM_STATISTIC_JOB ADD (
	START_DTM				DATE	NULL,
	END_DTM					DATE	NULL
);

DECLARE
	v_start_dtm				DATE;
	v_end_dtm				DATE;
BEGIN
	FOR r IN (
		SELECT j.app_sid, j.region_sid, j.statistic_id, s.meter_bucket_id
		  FROM csr.meter_alarm_statistic_job j
		  JOIN csr.meter_alarm_statistic s ON s.app_sid = j.app_sid AND s.statistic_id = j.statistic_id
			ORDER BY app_sid
	) LOOP
		
		-- Start date (last statistic data point)
		BEGIN
			SELECT MAX(statistic_dtm)
			  INTO v_start_dtm
			  FROM csr.meter_alarm_statistic_period
			 WHERE app_sid = r.app_sid
			   AND region_sid = r.region_sid
			   AND statistic_id = r.statistic_id;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				v_start_dtm := NULL;
		END;
		
		-- End date (last bucketed data point > last statistic data point)
		BEGIN
			SELECT NVL(v_start_dtm, MIN(start_dtm)), MAX(start_dtm)
			  INTO v_start_dtm, v_end_dtm
			  FROM csr.meter_live_data
			 WHERE app_sid = r.app_sid
			   AND region_sid = r.region_sid
			   AND meter_bucket_id = r.meter_bucket_id
			   AND start_dtm >= NVL(v_start_dtm, start_dtm);
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				v_start_dtm := NULL;
				v_end_dtm := NULL;
		END;		
		
		-- If we have valid dates then update the job
		IF v_start_dtm IS NOT NULL AND v_end_dtm IS NOT NULL THEN
			UPDATE csr.meter_alarm_statistic_job
			   SET start_dtm = v_start_dtm,
				   end_dtm = v_end_dtm
			 WHERE app_sid = r.app_sid
			   AND region_sid = r.region_sid
			   AND statistic_id = r.statistic_id;
		ELSE
			-- No valid dates, so no data, just remove the job
			DELETE FROM csr.meter_alarm_statistic_job
			 WHERE app_sid = r.app_sid
			   AND region_sid = r.region_sid
			   AND statistic_id = r.statistic_id;
		END IF;	
	END LOOP;
END;
/

ALTER TABLE CSR.METER_ALARM_STATISTIC_JOB MODIFY (
	START_DTM				DATE	NOT NULL,
	END_DTM					DATE	NOT NULL
);

ALTER TABLE CSR.METER_SOURCE_TYPE ADD (
	AUTO_PATCH				NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	CHECK (AUTO_PATCH IN(0,1))
);

-- FKs
ALTER TABLE CSR.METER_LIVE_DATA ADD CONSTRAINT FK_METBUCK_METLIVDAT 
    FOREIGN KEY (APP_SID, METER_BUCKET_ID)
    REFERENCES CSR.METER_BUCKET(APP_SID, METER_BUCKET_ID)
;

ALTER TABLE CSR.METER_LIVE_DATA ADD CONSTRAINT FK_METRAWDAT_METLIVDAT 
    FOREIGN KEY (APP_SID, METER_RAW_DATA_ID)
    REFERENCES CSR.METER_RAW_DATA(APP_SID, METER_RAW_DATA_ID)
;

ALTER TABLE CSR.METER_LIVE_DATA ADD CONSTRAINT FK_ALLMETER_METLIVDAT 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_SOURCE_DATA ADD CONSTRAINT FK_CUSTOMER_METSRCDAT 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.METER_SOURCE_DATA ADD CONSTRAINT FK_METRAWDAT_METSRCDAT 
    FOREIGN KEY (APP_SID, METER_RAW_DATA_ID)
    REFERENCES CSR.METER_RAW_DATA(APP_SID, METER_RAW_DATA_ID)
;

ALTER TABLE CSR.METER_SOURCE_DATA ADD CONSTRAINT FK_ALLMETER_METSRCDAT 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_READING_DATA ADD CONSTRAINT FK_METER_METER_READING_DATA 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_READING_DATA ADD CONSTRAINT FK_METER_RAW_READING_DATA 
    FOREIGN KEY (APP_SID, METER_RAW_DATA_ID)
    REFERENCES CSR.METER_RAW_DATA(APP_SID, METER_RAW_DATA_ID)
;

ALTER TABLE CSR.METER_ORPHAN_DATA ADD CONSTRAINT FK_CUSTOMER_MORPHAN 
    FOREIGN KEY (APP_SID)
    REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.METER_ORPHAN_DATA ADD CONSTRAINT FK_METRAWDAT_MORPHAN
    FOREIGN KEY (APP_SID, METER_RAW_DATA_ID)
    REFERENCES CSR.METER_RAW_DATA(APP_SID, METER_RAW_DATA_ID)
;

ALTER TABLE CSR.METER_DATA_PRIORITY ADD CONSTRAINT FK_CUSTOMER_MDPRIORITY 
	FOREIGN KEY (APP_SID)
	REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.METER_ORPHAN_DATA ADD CONSTRAINT FK_MDPRIORITY_MORPHAN 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

ALTER TABLE CSR.METER_READING_DATA ADD CONSTRAINT FK_MDPRIORITY_MREADING 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

ALTER TABLE CSR.METER_SOURCE_DATA ADD CONSTRAINT FK_MDPRIORITY_MSOURCE 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

ALTER TABLE CSR.METER_INPUT ADD CONSTRAINT FK_CUSTOMER_METIMP
	FOREIGN KEY (APP_SID)
	REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.METER_INPUT_AGGR_IND ADD CONSTRAINT FK_AMETER_METINPAGGIND
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_INPUT_AGGR_IND ADD CONSTRAINT FK_IND_METERINPAGGRIND 
	FOREIGN KEY (APP_SID, IND_SID, MEASURE_SID)
	REFERENCES CSR.IND(APP_SID, IND_SID, MEASURE_SID)
;

ALTER TABLE CSR.METER_INPUT_AGGR_IND ADD CONSTRAINT FK_MESCONV_METINPAGGRIND 
	FOREIGN KEY (APP_SID, MEASURE_CONVERSION_ID, MEASURE_SID)
	REFERENCES CSR.MEASURE_CONVERSION(APP_SID, MEASURE_CONVERSION_ID, MEASURE_SID)
;

ALTER TABLE CSR.METER_INPUT_AGGR_IND ADD CONSTRAINT FK_METINPAGGR_METINPAGRIND
	FOREIGN KEY (APP_SID, METER_INPUT_ID, AGGREGATOR)
	REFERENCES CSR.METER_INPUT_AGGREGATOR(APP_SID, METER_INPUT_ID, AGGREGATOR)
;

ALTER TABLE CSR.METER_INPUT_AGGREGATOR ADD CONSTRAINT FK_METAGG_METINPAGG
	FOREIGN KEY (AGGREGATOR)
	REFERENCES CSR.METER_AGGREGATOR(AGGREGATOR)
;

ALTER TABLE CSR.METER_INPUT_AGGREGATOR ADD CONSTRAINT FK_METIMP_METIMPAGG
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_LIVE_DATA ADD CONSTRAINT FK_METIMPAGG_METLIVDAT
	FOREIGN KEY (APP_SID, METER_INPUT_ID, AGGREGATOR)
	REFERENCES CSR.METER_INPUT_AGGREGATOR(APP_SID, METER_INPUT_ID, AGGREGATOR)
;

ALTER TABLE CSR.METER_ORPHAN_DATA ADD CONSTRAINT FK_METIMP_METORPDAT
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_PATCH_DATA ADD CONSTRAINT FK_METIMP_METPATDAT
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_READING_DATA ADD CONSTRAINT FK_METIMP_METREDDAT
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_SOURCE_DATA ADD CONSTRAINT FK_METIMP_METSRCDAT
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_ALARM_STATISTIC ADD CONSTRAINT FK_METIMPAGG_METALMSTAT 
	FOREIGN KEY (APP_SID, METER_INPUT_ID, AGGREGATOR)
	REFERENCES CSR.METER_INPUT_AGGREGATOR(APP_SID, METER_INPUT_ID, AGGREGATOR)
;

ALTER TABLE CSR.METER_ALARM_STATISTIC ADD CONSTRAINT FK_METERBUCKET_STATISTIC 
	FOREIGN KEY (APP_SID, METER_BUCKET_ID)
	REFERENCES CSR.METER_BUCKET(APP_SID, METER_BUCKET_ID)
;

ALTER TABLE CSR.METER_LIVE_DATA ADD CONSTRAINT FK_MDPRIORITY_MLIVE 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

ALTER TABLE CSR.METER_PATCH_DATA ADD CONSTRAINT FK_ALLMETER_MPATCH
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_PATCH_DATA ADD CONSTRAINT FK_MDPRIORITY_MPATCH 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

-- Hmm
BEGIN
	FOR r IN (
		SELECT table_name, constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSR'
		   AND table_name IN (
			'METER_ALARM_STATISTIC_JOB',
			'METER_ALARM_STATISTIC_PERIOD'
		   )
		   AND constraint_name IN (
			'REFMETER_METER_ALARM_STATI2143',
			'REFMETER_METER_ALARM_STATI2174'
		  )
	) LOOP
		EXECUTE IMMEDIATE 'ALTER TABLE CSR.'||r.table_name||' DROP CONSTRAINT '||r.constraint_name;
	END LOOP;
END;
/

BEGIN
	FOR r IN (
		SELECT p.table_name, p.constraint_name
		  FROM all_constraints p
		  JOIN all_constraints c
			ON c.constraint_name = p.r_constraint_name
		   AND c.constraint_type = 'P' 
		   AND c.table_name = 'METER_METER_ALARM_STATISTIC'
		 WHERE p.owner = 'CSR'
		   AND p.table_name = 'METER_ALARM_STATISTIC_PERIOD'
		   AND p.constraint_type = 'R'
	) LOOP
		EXECUTE IMMEDIATE 'ALTER TABLE CSR.'||r.table_name||' DROP CONSTRAINT '||r.constraint_name;
	END LOOP;
END;
/


ALTER TABLE CSR.METER_ALARM_STATISTIC_PERIOD ADD CONSTRAINT FK_METALMSTAT_METALMSTATPRD 
	FOREIGN KEY (APP_SID, STATISTIC_ID)
	REFERENCES CSR.METER_ALARM_STATISTIC(APP_SID, STATISTIC_ID)
;

ALTER TABLE CSR.METER_ALARM_STATISTIC_PERIOD ADD CONSTRAINT FK_METER_METALMSTATPERIOD 
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_PATCH_JOB ADD CONSTRAINT FK_AMETER_METERPATCHJOB 
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_PATCH_JOB ADD CONSTRAINT FK_METIMP_METPATJOB 
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_PATCH_BATCH_JOB ADD CONSTRAINT FK_ALLMET_METPATBATJOB 
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.ALL_METER(APP_SID, REGION_SID)
;

ALTER TABLE CSR.METER_PATCH_BATCH_JOB ADD CONSTRAINT FK_CUSTOMER_METPATBATJOB 
	FOREIGN KEY (APP_SID)
	REFERENCES CSR.CUSTOMER(APP_SID)
;

ALTER TABLE CSR.METER_PATCH_BATCH_DATA ADD CONSTRAINT FK_METINP_METPATBATDAT 
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

ALTER TABLE CSR.METER_PATCH_BATCH_DATA ADD CONSTRAINT FK_METDATPRI_METPATBATDAT 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

ALTER TABLE CSR.METER_PATCH_BATCH_DATA ADD CONSTRAINT FK_METPATBATJOB_METPATBADAT
	FOREIGN KEY (APP_SID, BATCH_JOB_ID)
	REFERENCES CSR.METER_PATCH_BATCH_JOB(APP_SID, BATCH_JOB_ID)
;

ALTER TABLE CSR.METER_DATA_COVERAGE_IND ADD CONSTRAINT FK_IND_METDATCOVIND 
	FOREIGN KEY (APP_SID, IND_SID)
	REFERENCES CSR.IND(APP_SID, IND_SID)
;

ALTER TABLE CSR.METER_DATA_COVERAGE_IND ADD CONSTRAINT FK_METDATPRI_METDATCOVIND 
	FOREIGN KEY (APP_SID, PRIORITY)
	REFERENCES CSR.METER_DATA_PRIORITY(APP_SID, PRIORITY)
;

ALTER TABLE CSR.METER_DATA_COVERAGE_IND ADD CONSTRAINT FK_METINP_METDATCOVIND 
	FOREIGN KEY (APP_SID, METER_INPUT_ID)
	REFERENCES CSR.METER_INPUT(APP_SID, METER_INPUT_ID)
;

alter table csr.customer add legacy_period_formatting number(1,0) default 0;

-- Drop indexes to be replaced
DROP INDEX CSR.UK_METER_ORPHAN_DATA;
DROP INDEX CSR.IDX_ORPHAN_SERIAL;
DROP INDEX CSR.IDX_ORPHAN_RAW_DATA_ID;
DROP INDEX CSR.IDX_ORPHAN_DATE_RANGE;
DROP INDEX CSR.IDX_ORPHAN_SOURCE_DATE_RANGE;
DROP INDEX CSR.UK_METER_READING_DATA;
DROP INDEX CSR.IDX_METER_READING_DATA_REGION;
DROP INDEX CSR.UK_METER_SOURCE_DATA;
DROP INDEX CSR.IDX_METER_SOURCE_DATA_REGION;
DROP INDEX CSR.IX_METER_SOURCE__METER_RAW_DAT;
DROP INDEX CSR.IDX_METER_LIVE_DURATION;
DROP INDEX CSR.IDX_METER_LIVE_PERIOD;
DROP INDEX CSR.IDX_METER_LIVE_REGION;
DROP INDEX CSR.IDX_METER_LIVE_RAW;
DROP INDEX CSR.IX_METER_LIVE_DA_LIVE_DATA_DUR;


-- FK indexes
CREATE INDEX CSR.IX_CUSTOMER_MDPRIORITY ON CSR.METER_DATA_PRIORITY(APP_SID);

CREATE INDEX CSR.FK_ALLMETER_MPATCH ON CSR.METER_PATCH_DATA(APP_SID, REGION_SID);
CREATE INDEX CSR.FK_MDPRIORITY_MPATCH ON CSR.METER_PATCH_DATA(APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METIMP_METPATDAT ON CSR.METER_PATCH_DATA(APP_SID, METER_INPUT_ID);

CREATE INDEX CSR.IX_CUSTOMER_METIMP ON CSR.METER_INPUT(APP_SID);

CREATE INDEX CSR.IX_AMETER_METINPAGGIND ON CSR.METER_INPUT_AGGR_IND(APP_SID);
CREATE INDEX CSR.IX_IND_METERINPAGGRIND ON CSR.METER_INPUT_AGGR_IND(APP_SID, IND_SID);
CREATE INDEX CSR.IX_METINPAGGR_METINPAGRIND ON CSR.METER_INPUT_AGGR_IND(APP_SID, METER_INPUT_ID, AGGREGATOR);

CREATE INDEX CSR.IX_METAGG_METINPAGG ON CSR.METER_INPUT_AGGREGATOR(AGGREGATOR);
CREATE INDEX CSR.IX_METIMP_METIMPAGG ON CSR.METER_INPUT_AGGREGATOR(APP_SID, METER_INPUT_ID);

CREATE INDEX CSR.IX_METIMPAGG_METALMSTAT ON CSR.METER_ALARM_STATISTIC (APP_SID, METER_INPUT_ID, AGGREGATOR);
CREATE INDEX CSR.IX_METERBUCKET_STATISTIC ON CSR.METER_ALARM_STATISTIC (APP_SID, METER_BUCKET_ID);

CREATE INDEX IX_METALMSTAT_METALMSTATPRD ON CSR.METER_ALARM_STATISTIC_PERIOD (APP_SID, STATISTIC_ID);
CREATE INDEX IX_METER_METALMSTATPERIOD ON CSR.METER_ALARM_STATISTIC_PERIOD (APP_SID, REGION_SID);

CREATE INDEX CSR.IX_AMETER_METERPATCHJOB ON CSR.METER_PATCH_JOB(APP_SID, REGION_SID);
CREATE INDEX CSR.IX_METIMP_METPATJOB ON CSR.METER_PATCH_JOB(APP_SID, METER_INPUT_ID);

CREATE INDEX CSR.IX_ALLMET_METPATBATJOB ON CSR.METER_PATCH_BATCH_JOB (APP_SID, REGION_SID);
CREATE INDEX CSR.IX_CUSTOMER_METPATBATJOB ON CSR.METER_PATCH_BATCH_JOB (APP_SID);

CREATE INDEX CSR.IX_METINP_METPATBATDAT ON CSR.METER_PATCH_BATCH_DATA (APP_SID, METER_INPUT_ID);
CREATE INDEX CSR.IX_METDATPRI_METPATBATDAT ON CSR.METER_PATCH_BATCH_DATA (APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METPATBATJOB_METPATBADAT ON CSR.METER_PATCH_BATCH_DATA (APP_SID, BATCH_JOB_ID);

CREATE INDEX CSR.IX_IND_METDATCOVIND ON CSR.METER_DATA_COVERAGE_IND(APP_SID, IND_SID);
CREATE INDEX CSR.IX_METDATPRI_METDATCOVIND ON CSR.METER_DATA_COVERAGE_IND(APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METINP_METDATCOVIND ON CSR.METER_DATA_COVERAGE_IND(APP_SID, METER_INPUT_ID);


CREATE INDEX CSR.IX_MDPRIORITY_MORPHAN ON CSR.METER_ORPHAN_DATA(APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METIMP_METORPDAT ON CSR.METER_ORPHAN_DATA(APP_SID, METER_INPUT_ID);

CREATE INDEX CSR.IX_MDPRIORITY_MREADING ON CSR.METER_READING_DATA(APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METIMP_METREDDAT ON CSR.METER_READING_DATA(APP_SID, METER_INPUT_ID);
CREATE INDEX CSR.IX_METER_RAW_READING_DATA ON CSR.METER_READING_DATA(APP_SID, METER_RAW_DATA_ID);

CREATE INDEX CSR.IX_MDPRIORITY_MSOURCE ON CSR.METER_SOURCE_DATA(APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METIMP_METSRCDAT ON CSR.METER_SOURCE_DATA(APP_SID, METER_INPUT_ID);
CREATE INDEX CSR.IX_ALLMETER_METSRCDAT ON CSR.METER_SOURCE_DATA(APP_SID, REGION_SID);
CREATE INDEX CSR.IX_METER_SOURCE__METER_RAW_DAT ON CSR.METER_SOURCE_DATA (APP_SID, METER_RAW_DATA_ID);

CREATE INDEX CSR.IX_MDPRIORITY_MLIVE ON CSR.METER_LIVE_DATA(APP_SID, PRIORITY);
CREATE INDEX CSR.IX_METIMPAGG_METLIVDAT ON CSR.METER_LIVE_DATA(APP_SID, METER_INPUT_ID, AGGREGATOR);
CREATE INDEX CSR.IX_METER_LIVE_DA_LIVE_DATA_DUR ON CSR.METER_LIVE_DATA (APP_SID, METER_BUCKET_ID);

-- Non-FK indexes
CREATE UNIQUE INDEX CSR.UK_METER_ORPHAN_DATA ON CSR.METER_ORPHAN_DATA(APP_SID, SERIAL_ID, METER_INPUT_ID, PRIORITY, START_DTM);
CREATE INDEX CSR.IDX_ORPHAN_SERIAL ON CSR.METER_ORPHAN_DATA(APP_SID, SERIAL_ID);
CREATE INDEX CSR.IDX_ORPHAN_RAW_DATA_ID ON CSR.METER_ORPHAN_DATA(APP_SID, METER_RAW_DATA_ID);
CREATE INDEX CSR.IDX_ORPHAN_DATE_RANGE ON CSR.METER_ORPHAN_DATA(APP_SID, START_DTM, END_DTM);
CREATE INDEX CSR.IDX_ORPHAN_SOURCE_DATE_RANGE ON CSR.METER_ORPHAN_DATA(APP_SID, METER_RAW_DATA_ID, START_DTM, END_DTM);

CREATE UNIQUE INDEX CSR.UK_METER_READING_DATA ON CSR.METER_READING_DATA(APP_SID, REGION_SID, METER_INPUT_ID, PRIORITY, READING_DTM);
CREATE INDEX CSR.IX_METRDNG_RGIN ON CSR.METER_READING_DATA(APP_SID, REGION_SID, METER_INPUT_ID);
CREATE INDEX CSR.IDX_METER_READING_DATA_REGION ON CSR.METER_READING_DATA(APP_SID, REGION_SID);

CREATE UNIQUE INDEX CSR.UK_METER_SOURCE_DATA ON CSR.METER_SOURCE_DATA(APP_SID, REGION_SID, METER_INPUT_ID, PRIORITY, START_DTM);
CREATE INDEX CSR.IX_METSRC_RGIN ON CSR.METER_SOURCE_DATA(APP_SID, REGION_SID, METER_INPUT_ID);
CREATE INDEX CSR.IDX_METER_SOURCE_DATA_REGION ON CSR.METER_SOURCE_DATA(APP_SID, REGION_SID, PRIORITY);

CREATE INDEX CSR.IX_METLD_BUINPR ON CSR.METER_LIVE_DATA(APP_SID, METER_BUCKET_ID, METER_INPUT_ID, PRIORITY);
CREATE INDEX CSR.IX_METLD_BUINPRAG ON CSR.METER_LIVE_DATA(APP_SID, METER_BUCKET_ID, METER_INPUT_ID, PRIORITY, AGGREGATOR);
CREATE INDEX CSR.IX_METLD_RGBUINPR ON CSR.METER_LIVE_DATA(APP_SID, REGION_SID, METER_BUCKET_ID, METER_INPUT_ID, PRIORITY);
CREATE INDEX CSR.IX_METLD_RGBUINAGPR ON CSR.METER_LIVE_DATA(APP_SID, REGION_SID, METER_BUCKET_ID, METER_INPUT_ID, AGGREGATOR, PRIORITY);


----


ALTER TABLE CSRIMP.LIVE_DATA_DURATION RENAME TO METER_BUCKET;
ALTER TABLE CSRIMP.METER_BUCKET RENAME COLUMN IS_SYSTEM_PERIOD TO IS_EXPORT_PERIOD;
ALTER TABLE CSRIMP.METER_BUCKET RENAME COLUMN LIVE_DATA_DURATION_ID TO METER_BUCKET_ID;
ALTER TABLE CSRIMP.METER_LIVE_DATA RENAME COLUMN LIVE_DATA_DURATION_ID TO METER_BUCKET_ID;

DECLARE
	v_cons_name				VARCHAR2(30);
BEGIN
	-- Replace check constraints
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSRIMP'
		   AND table_name = 'METER_BUCKET'
		   AND constraint_type = 'C'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSRIMP.METER_BUCKET DROP CONSTRAINT  '||r.constraint_name);
	END LOOP;
END;
/

ALTER TABLE CSRIMP.METER_BUCKET ADD(
	PERIOD_SET_ID			NUMBER(10),
	PERIOD_INTERVAL_ID		NUMBER(10),
	IS_MINUTES				NUMBER(1),
	HIGH_RESOLUTION_ONLY	NUMBER(1) DEFAULT 0 NOT NULL,
	CHECK (IS_HOURS = 0 OR (IS_HOURS  = 1 AND IS_MINUTES = 0 AND IS_WEEKS = 0 AND IS_MONTHS = 0 AND PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL)),
	CHECK (IS_WEEKS = 0 OR (IS_WEEKS = 1 AND IS_MINUTES = 0 AND IS_HOURS = 0 AND IS_MONTHS = 0 AND PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL)),
	CHECK (IS_MINUTES = 0 OR (IS_MINUTES  = 1 AND IS_HOURS = 0 AND IS_WEEKS = 0 AND IS_MONTHS = 0 AND PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL)),
	CHECK (WEEK_START_DAY IS NULL OR IS_WEEKS = 1),
	CHECK (START_MONTH IS NULL OR IS_MONTHS = 1),
	CHECK ((PERIOD_SET_ID IS NULL AND PERIOD_INTERVAL_ID IS NULL) OR (PERIOD_SET_ID IS NOT NULL AND PERIOD_INTERVAL_ID IS NOT NULL AND IS_MINUTES = 0 AND IS_HOURS = 0 AND IS_WEEKS = 0)),
	CHECK (HIGH_RESOLUTION_ONLY IN (0,1))
);

BEGIN
	-- All export buckets must have period set and interval
	UPDATE csrimp.meter_bucket
	   SET period_set_id = 1,
	       period_interval_id = 1
	 WHERE is_export_period = 1
	   AND period_set_id IS NULL;
END;
/

ALTER TABLE CSRIMP.METER_BUCKET ADD(
	CHECK (IS_MONTHS = 0 OR (IS_MONTHS = 1 AND IS_MINUTES = 0 AND IS_HOURS = 0 AND IS_WEEKS = 0 AND (IS_EXPORT_PERIOD = 0 OR (PERIOD_SET_ID = 1 AND PERIOD_INTERVAL_ID = 1)))),
	CHECK (IS_EXPORT_PERIOD IN (0,1) AND (IS_EXPORT_PERIOD = 0 OR (PERIOD_SET_ID IS NOT NULL AND PERIOD_INTERVAL_ID IS NOT NULL)))
);

ALTER TABLE CSRIMP.MAP_LIVE_DATA_DURATION RENAME TO MAP_METER_BUCKET;
ALTER TABLE CSRIMP.MAP_METER_BUCKET RENAME COLUMN OLD_LIVE_DATA_DURATION_ID TO OLD_METER_BUCKET_ID;
ALTER TABLE CSRIMP.MAP_METER_BUCKET RENAME COLUMN NEW_LIVE_DATA_DURATION_ID TO NEW_METER_BUCKET_ID;

ALTER TABLE CSRIMP.METER_ORPHAN_DATA ADD(
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	PRIORITY				NUMBER(10, 0)	NOT NULL
);
--DROP INDEX CSRIMP.UK_METER_ORPHAN_DATA;
CREATE UNIQUE INDEX CSRIMP.UK_METER_ORPHAN_DATA ON CSRIMP.METER_ORPHAN_DATA(CSRIMP_SESSION_ID, SERIAL_ID, METER_INPUT_ID, PRIORITY, START_DTM);

ALTER TABLE CSRIMP.METER_READING_DATA ADD(
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	PRIORITY				NUMBER(10, 0)	NOT NULL
);
--DROP INDEX CSRIMP.UK_METER_READING_DATA;
CREATE UNIQUE INDEX CSRIMP.UK_METER_READING_DATA ON CSRIMP.METER_READING_DATA(CSRIMP_SESSION_ID, REGION_SID, METER_INPUT_ID, PRIORITY, READING_DTM);


ALTER TABLE CSRIMP.METER_SOURCE_DATA ADD(
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	PRIORITY				NUMBER(10, 0)	NOT NULL
);
--DROP INDEX CSRIMP.UK_METER_SOURCE_DATA;
CREATE UNIQUE INDEX CSRIMP.UK_METER_SOURCE_DATA ON CSRIMP.METER_SOURCE_DATA(CSRIMP_SESSION_ID, REGION_SID, METER_INPUT_ID, PRIORITY, START_DTM);


BEGIN
	-- Remove existing PK
	FOR r IN (
		SELECT constraint_name
		  FROM all_constraints
		 WHERE owner = 'CSRIMP'
		   AND table_name = 'METER_LIVE_DATA'
		   AND constraint_type = 'P'
	) LOOP
		EXECUTE IMMEDIATE('ALTER TABLE CSRIMP.METER_LIVE_DATA DROP CONSTRAINT  '||r.constraint_name||' DROP INDEX');
	END LOOP;
END;
/
--DROP INDEX CSRIMP.PK_METER_LIVE_DATA;
ALTER TABLE CSRIMP.METER_LIVE_DATA ADD(
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	AGGREGATOR				VARCHAR2(32)	NOT NULL,
	PRIORITY				NUMBER(10)		NOT NULL
);
ALTER TABLE CSRIMP.METER_LIVE_DATA ADD(
	CONSTRAINT PK_METER_LIVE_DATA PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID, METER_BUCKET_ID, METER_INPUT_ID, AGGREGATOR, PRIORITY, START_DTM)
);

ALTER TABLE CSRIMP.METER_READING_DATA ADD (
	VAL						NUMBER(24, 10)
);


ALTER TABLE CSRIMP.METER_ALARM_STATISTIC ADD (
	METER_INPUT_ID			NUMBER(10, 0)	NOT NULL,
	AGGREGATOR				VARCHAR2(32)	NOT NULL,
	METER_BUCKET_ID			NUMBER(10, 0)	NOT NULL,
	LOOKUP_KEY				VARCHAR2(256)
);
CREATE UNIQUE INDEX CSRIMP.UK_LOOKUP_KEY ON CSRIMP.METER_ALARM_STATISTIC(CSRIMP_SESSION_ID, NVL(LOOKUP_KEY, STATISTIC_ID));

ALTER TABLE CSRIMP.METER_ALARM_STATISTIC_JOB ADD (
	START_DTM				DATE	NOT NULL,
	END_DTM					DATE	NOT NULL
);

ALTER TABLE CSRIMP.METER_SOURCE_TYPE ADD (
	AUTO_PATCH				NUMBER(1, 0)	DEFAULT 0 NOT NULL,
	CHECK (AUTO_PATCH IN(0,1))
);

ALTER TABLE csr.portal_dashboard DROP CONSTRAINT uk_portal_menu_sid;
CREATE UNIQUE INDEX csr.ux_portal_dashboard_menu_sid ON csr.portal_dashboard (CASE WHEN menu_sid IS NOT NULL THEN app_sid END, menu_sid);

ALTER TABLE csr.plugin ADD (
	portal_sid					NUMBER(10, 0),
	CONSTRAINT fk_plugin_portal FOREIGN KEY (app_sid, portal_sid) REFERENCES csr.portal_dashboard(app_sid, portal_sid)
);

ALTER TABLE csr.plugin DROP CONSTRAINT ck_plugin_refs;
ALTER TABLE csr.plugin ADD CONSTRAINT ck_plugin_refs 
	CHECK (
		(
			tab_sid IS NULL AND form_path IS NULL AND
			group_key IS NULL AND 
			saved_filter_sid IS NULL AND
			control_lookup_keys IS NULL AND
			portal_sid IS NULL
		) OR (
			app_sid IS NOT NULL AND
			(
				(
					tab_sid IS NOT NULL AND form_path IS NOT NULL AND 
					group_key IS NULL AND
					saved_filter_sid IS NULL AND
					portal_sid IS NULL
				) OR (
					tab_sid IS NULL AND form_path IS NULL AND
					group_key IS NOT NULL AND
					saved_filter_sid IS NULL AND
					portal_sid IS NULL
				) OR (
					tab_sid IS NULL AND form_path IS NULL AND
					group_key IS NULL AND
					saved_filter_sid IS NOT NULL AND
					portal_sid IS NULL
				) OR (
					tab_sid IS NULL AND form_path IS NULL AND
					group_key IS NULL AND
					saved_filter_sid IS NULL AND
					portal_sid IS NOT NULL
				)
			)
		)
	);

DROP INDEX csr.plugin_js_class;
CREATE UNIQUE INDEX csr.plugin_js_class ON csr.plugin (app_sid, js_class, form_path, group_key, saved_filter_sid, result_mode, portal_sid);

ALTER TABLE csrimp.plugin ADD (
	portal_sid					NUMBER(10, 0)
);

ALTER TABLE csrimp.flow_state_transition_role ADD group_sid NUMBER(10);
ALTER TABLE csrimp.flow_transition_alert_role ADD group_sid NUMBER(10);
ALTER TABLE csrimp.flow_state_role ADD group_sid NUMBER(10);
ALTER TABLE csrimp.flow_state_role_capability ADD group_sid NUMBER(10);

CREATE INDEX csr.ix_flow_item_gen_proc_dtm_fi ON csr.flow_item_generated_alert (app_sid, processed_dtm, flow_item_id);

-- *** Grants ***
GRANT SELECT ON CSR.METER_BUCKET_ID_SEQ TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_DATA_PRIORITY TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_PATCH_DATA TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_INPUT TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_INPUT_AGGR_IND TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_INPUT_AGGREGATOR TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_PATCH_JOB TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_PATCH_BATCH_JOB TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_DATA_COVERAGE_IND TO CSRIMP;

GRANT SELECT,INSERT,UPDATE ON CSR.METER_ORPHAN_DATA TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_READING_DATA TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_SOURCE_DATA TO CSRIMP;
GRANT SELECT,INSERT,UPDATE ON CSR.METER_LIVE_DATA TO CSRIMP;


GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_DATA_PRIORITY TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_PATCH_DATA TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_INPUT TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_INPUT_AGGR_IND TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_INPUT_AGGREGATOR TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_PATCH_JOB TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_PATCH_BATCH_JOB TO WEB_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON CSRIMP.METER_DATA_COVERAGE_IND TO WEB_USER;

GRANT select ON csr.portal_dashboard TO chain;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please add the path to the create_views file which will contain your view changes.  I will use this version when making the major scripts.

-- /csr/db/create_views.sql
CREATE OR REPLACE VIEW CSR.V$PATCHED_METER_LIVE_DATA AS
	SELECT app_sid, region_sid, meter_input_id, aggregator, meter_bucket_id, priority, start_dtm, end_dtm, meter_raw_data_id, modified_dtm, consumption
	  FROM (
		SELECT app_sid, region_sid, meter_input_id, aggregator, meter_bucket_id, priority, start_dtm, end_dtm, meter_raw_data_id, modified_dtm, consumption,
			ROW_NUMBER() OVER (PARTITION BY app_sid, region_sid, meter_input_id, aggregator, meter_bucket_id, start_dtm ORDER BY priority DESC) rn
		  FROM csr.meter_live_data d
	 )
	 WHERE rn = 1;


-- ** Triggers ** --

-- /csr/db/create_triggers.sql
CREATE OR REPLACE TRIGGER CSR.METER_IND_TRIGGER
AFTER INSERT OR UPDATE
	ON CSR.ALL_METER
	FOR EACH ROW
DECLARE
	v_consumption_input_id	csr.meter_input.meter_input_id%TYPE;
	v_cost_input_id			csr.meter_input.meter_input_id%TYPE;
BEGIN
	SELECT meter_input_id
	  INTO v_consumption_input_id
	  FROM csr.meter_input
	 WHERE app_sid = :NEW.app_sid
	   AND lookup_key = 'CONSUMPTION';
	
	SELECT meter_input_id
	  INTO v_cost_input_id
	  FROM csr.meter_input
	 WHERE app_sid = :NEW.app_sid
	   AND lookup_key = 'COST';
	
	FOR r IN (
		SELECT :NEW.app_sid app_sid, :NEW.region_sid region_sid, 
			pia.aggregator primary_aggregator, :NEW.primary_ind_sid primary_ind_sid, pi.measure_sid primary_measure_sid, :NEW.primary_measure_conversion_id primary_measure_conversion_id,
			cia.aggregator cost_aggregator, :NEW.cost_ind_sid cost_ind_sid, ci.measure_sid cost_measure_sid, :NEW.cost_measure_conversion_id cost_measure_conversion_id
		  FROM csr.ind pi
		  JOIN csr.meter_input_aggregator pia ON pia.app_sid = pi.app_sid AND pia.meter_input_id = v_consumption_input_id
		  LEFT JOIN csr.ind ci ON ci.app_sid = pi.app_sid AND ci.ind_sid = :NEW.cost_ind_sid
		  LEFT JOIN csr.meter_input_aggregator cia ON cia.app_sid = ci.app_sid AND cia.meter_input_id = v_cost_input_id
		 WHERE pi.app_sid = :NEW.app_sid
		   AND pi.ind_sid = :NEW.primary_ind_sid
	) LOOP
		-- Set the consumption indicator/measure/conversion
		BEGIN
			INSERT INTO csr.meter_input_aggr_ind (app_sid, region_sid, meter_input_id, aggregator, ind_sid, measure_sid, measure_conversion_id)
			VALUES (r.app_sid, r.region_sid, v_consumption_input_id, r.primary_aggregator, r.primary_ind_sid, r.primary_measure_sid, r.primary_measure_conversion_id);
		EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
				UPDATE csr.meter_input_aggr_ind
				   SET ind_sid = r.primary_ind_sid,
					   measure_sid = r.primary_measure_sid, 
					   measure_conversion_id = r.primary_measure_conversion_id
				 WHERE app_sid = r.app_sid
				   AND region_sid = r.region_sid
				   AND meter_input_id = v_consumption_input_id
				   AND aggregator = r.primary_aggregator;
		END;
		
		-- Set the cost indicator/measure/conversion
		IF r.cost_ind_sid IS NOT NULL THEN
			BEGIN
				INSERT INTO csr.meter_input_aggr_ind (app_sid, region_sid, meter_input_id, aggregator, ind_sid, measure_sid, measure_conversion_id)
				VALUES (r.app_sid, r.region_sid, v_cost_input_id, r.cost_aggregator, r.cost_ind_sid, r.cost_measure_sid, r.cost_measure_conversion_id);
			EXCEPTION
				WHEN DUP_VAL_ON_INDEX THEN
					UPDATE csr.meter_input_aggr_ind
					   SET ind_sid = r.cost_ind_sid,
						   measure_sid = r.cost_measure_sid, 
						   measure_conversion_id = r.cost_measure_conversion_id
					 WHERE app_sid = r.app_sid
					   AND region_sid = r.region_sid
					   AND meter_input_id = v_cost_input_id
					   AND aggregator = r.cost_aggregator;
			END;
		ELSE
			DELETE FROM csr.meter_input_aggr_ind
			  WHERE app_sid = r.app_sid
			    AND region_sid = r.region_sid
			    AND meter_input_id = v_cost_input_id;
		END IF;
	END LOOP;
END;
/

-- *** Data changes ***
-- RLS
DECLARE
	FEATURE_NOT_ENABLED EXCEPTION;
	PRAGMA EXCEPTION_INIT(FEATURE_NOT_ENABLED, -439);
    POLICY_ALREADY_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(POLICY_ALREADY_EXISTS, -28101);
BEGIN
 	FOR r IN (
		SELECT c.owner, c.table_name, c.nullable, (SUBSTR(c.table_name, 1, 26) || '_POL') policy_name
		  FROM all_tables t
		  JOIN all_tab_columns c ON t.owner = c.owner AND t.table_name = c.table_name
		 WHERE t.owner IN ('CSRIMP') AND (t.dropped = 'NO' OR t.dropped IS NULL) AND c.column_name = 'CSRIMP_SESSION_ID'
		   AND t.table_name IN (
				'METER_INPUT',
				'METER_AGGREGATOR',
				'METER_INPUT_AGGREGATOR',
				'METER_INPUT_AGGR_IND',
				'METER_DATA_PRIORITY',
				'METER_PATCH_DATA',
				'METER_PATCH_JOB',
				'METER_PATCH_BATCH_JOB',
				'METER_PATCH_BATCH_DATA',
				'METER_DATA_COVERAGE_IND'
		   )
 	)
 	LOOP
		dbms_output.put_line('Writing policy '||r.policy_name);
		dbms_rls.add_policy(
			object_schema   => r.owner,
			object_name     => r.table_name,
			policy_name     => r.policy_name, 
			function_schema => 'CSRIMP',
			policy_function => 'SessionIDCheck',
			statement_types => 'select, insert, update, delete',
			update_check	=> true,
			policy_type     => dbms_rls.context_sensitive);
	END LOOP;
EXCEPTION
	WHEN POLICY_ALREADY_EXISTS THEN
		DBMS_OUTPUT.PUT_LINE('Policy exists');
	WHEN FEATURE_NOT_ENABLED THEN
		DBMS_OUTPUT.PUT_LINE('RLS policies not applied as feature not enabled');
END;
/

-- Types
CREATE OR REPLACE TYPE CSR.T_METER_PATCH_DATA_ROW AS
	OBJECT (
		POS					NUMBER(10, 0),
		START_DTM			DATE,
		END_DTM				DATE,
		PERIOD_TYPE			VARCHAR2(32),
		CONSUMPTION			NUMBER(24, 10)
	);
/

CREATE OR REPLACE TYPE CSR.T_METER_PATCH_DATA_TABLE AS
	TABLE OF CSR.T_METER_PATCH_DATA_ROW;
/

-- Data
BEGIN
	INSERT INTO csr.batch_job_type (batch_job_type_id, description, sp, plugin_name, one_at_a_time, file_data_sp)
	VALUES (19, 'Meter patch', 'csr.meter_patch_pkg.ProcessBatchJob', NULL, 0, NULL);
END;
/

BEGIN
	-- Restrict some existing buckets to high resolution data only
	UPDATE csr.meter_bucket
	   SET high_resolution_only = 1
	 WHERE is_minutes = 1
	    OR (is_hours = 1 AND duration < 24);

	-- All metering now needs a system bucket (even non-real-time)
	-- A daily bucket is sometimes used to compute some values with better granularity (so add that too)
	FOR r IN (
		SELECT DISTINCT app_sid
		  FROM csr.meter_source_type st
		 WHERE NOT EXISTS (
		 	SELECT 1
		 	  FROM csr.meter_bucket mb
		 	 WHERE app_sid = st.app_sid
		 )
	) LOOP
		-- System period bucket
		INSERT INTO csr.meter_bucket (app_sid, meter_bucket_id, description, is_export_period, period_set_id, period_interval_id)
		VALUES(r.app_sid, csr.meter_bucket_id_seq.NEXTVAL, 'System', 1, 1, 1);
		-- Daily bucket
		INSERT INTO csr.meter_bucket (app_sid, meter_bucket_id, description, duration, is_hours)
		VALUES(r.app_sid, csr.meter_bucket_id_seq.NEXTVAL, 'Daily', 24, 1);
	END LOOP;
END;
/

DECLARE 
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) 
      INTO v_count
      FROM csr.batch_job_type 
     WHERE batch_job_type_id = 20;

    IF v_count = 0 THEN
        INSERT INTO csr.batch_job_type (batch_job_type_id, description, plugin_name, one_at_a_time)
             VALUES (20, 'Hyatt Forecasting', 'hyatt-forecasting', 1);
    END IF;
END;
/

update csr.customer 
   set legacy_period_formatting = 1 
 where app_sid <> 29144945;

update csr.period_interval
   set single_interval_label = '{1:YYYY}'
 where app_sid = 29144945
   and period_set_id = 1
   and period_interval_id = 4;

-- ** New package grants **
create or replace package csr.meter_patch_pkg as end;
/
grant execute on csr.meter_patch_pkg to web_user;


-- *** Packages ***
@../batch_job_pkg
@../meter_pkg
@../meter_monitor_pkg
@../meter_patch_pkg
@../meter_alarm_stat_pkg
@../meter_aggr_pkg
@../period_pkg
@../schema_pkg
@../plugin_pkg
@..\quick_survey_pkg
@..\chain\company_pkg

@../csrimp/imp_body
@..\enable_body
@..\flow_body
@..\..\..\aspen2\cms\db\tab_body
@..\audit_body
@..\chain\company_body
@../issue_body
@../plugin_body
@../property_body
@../chain/plugin_body
@..\quick_survey_body
@../schema_body
@../csr_app_body
@../meter_body
@../meter_monitor_body
@../meter_alarm_stat_body
@../meter_patch_body
@../meter_aggr_body
@../period_body

@update_tail
