-- Please update version.sql too -- this keeps clean builds in sync
define version=2904
define minor_version=17
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
--drop all enehesa table constraints
BEGIN
for r in (
  select * from all_constraints where lower(r_constraint_name) like '%enhesa%' ) loop
    execute immediate 'alter table '||r.owner||'.'||r.table_name||' drop constraint '||r.constraint_name;
end loop;

for r in (
  select * from all_constraints where owner='CSR' and table_name like 'ENHESA_%' and constraint_name like 'FK_%' ) loop
    execute immediate 'alter table csr.'||r.table_name||' drop constraint '||r.constraint_name;
end loop;

for r in (
  select * from all_constraints where owner='CSR' and table_name like 'ENHESA_%' and constraint_name like 'PK_%' ) loop
    execute immediate 'alter table csr.'||r.table_name||' drop constraint '||r.constraint_name;
end loop;

for r in (
  select * from all_constraints where owner='CSR' and table_name like 'ENHESA_%') loop
    execute immediate 'alter table csr.'||r.table_name||' drop constraint '||r.constraint_name;
end loop;	
END;
/

--drop all the protocol columns
begin
for r in (
  select * from all_tab_columns where owner='CSR' and table_name like 'ENHESA_%' and column_name = 'PROTOCOL' ) loop
    execute immediate 'alter table csr.'||r.table_name||' drop column '||r.column_name;
end loop;
end;
/

--update all the version columns to take two decimals
begin
for r in (
  select * from all_tab_columns where owner='CSR' and table_name like 'ENHESA_%' and column_name = 'VERSION' ) loop
    execute immediate 'alter table csr.'||r.table_name||' modify('||r.column_name||' number(12, 2))';
end loop;
end;
/

--drop protocol table
drop table csr.enhesa_protocol;

--Add a missing column
ALTER TABLE CSR.ENHESA_REG_TEXT ADD VERSION_RESEARCH_DTM DATE;

-- *** Grants ***

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.
--/csr/db/create_views.sql
CREATE OR REPLACE VIEW csr.V$ENHESA_TOPIC AS
    SELECT t.app_sid, t.topic_id, t.country_code, ecn.name country, stn.status_id, stn.name status, 
        t.report_dtm, t.adoption_dtm, t.importance, t.archived, t.version topic_version, t.url, t.region_sid,
        tt.version text_version, tt.version_pub_dtm text_version_pub_dtm, tt.title, tt.abstract, tt.analysis, tt.affected_ops,
        tt.reg_citation, tt.biz_impact, t.flow_item_id, fs.label flow_state_label, fs.state_colour, fs.lookup_key state_lookup_key
      FROM csr.enhesa_topic t
      JOIN csr.enhesa_topic_text tt ON t.topic_id = tt.topic_id AND tt.lang = 'en'
      JOIN csr.enhesa_status_name stn ON t.status_id = stn.status_id AND stn.lang = 'en'
      JOIN csr.enhesa_country_name ecn ON t.country_code = ecn.country_code AND ecn.lang = 'en'
      JOIN csr.flow_item fi ON t.flow_item_id = fi.flow_item_id AND t.app_sid = fi.app_sid
      JOIN csr.flow_state fs ON fi.current_state_id = fs.flow_state_id AND fi.app_sid = fs.app_sid
    ;
--/csr/db/create_views.sql
CREATE OR REPLACE VIEW csr.V$ENHESA_TOPIC_REGION AS  
    SELECT tr.topic_id, tr.country_code, cn.name country, tr.region_code, crn.name region
      FROM csr.enhesa_topic_region tr 
      JOIN csr.enhesa_country_name cn ON tr.country_code = cn.country_code AND cn.lang = 'en'
      JOIN csr.enhesa_country_region_name crn ON tr.country_code = crn.country_code AND tr.region_code = crn.region_code AND crn.lang = 'en'
    ; 
--/csr/db/create_views.sql
CREATE OR REPLACE VIEW csr.V$ENHESA_TOPIC_KEYWORD AS
    SELECT tk.topic_id, tk.keyword_id, kt.main, kt.category
      FROM csr.enhesa_topic_keyword tk 
      JOIN csr.enhesa_keyword_text kt ON tk.keyword_id = kt.keyword_id AND kt.lang = 'en'
    ; 
--/csr/db/create_views.sql
CREATE OR REPLACE VIEW csr.V$ENHESA_TOPIC_REG AS
    SELECT tr.topic_id, tr.reg_id, r.parent_reg_id, r.reg_ref, rt.title, r.ref_dtm, r.link, r.archived, r.version reg_version,
        r.reg_level, rt.version reg_text_version, rt.version_pub_dtm reg_text_version_pub_dtm
      FROM csr.enhesa_topic_reg tr
      JOIN csr.enhesa_reg r ON tr.reg_id = r.reg_id
      JOIN csr.enhesa_reg_text rt ON r.reg_id = rt.reg_id AND rt.lang = 'en'
    ;

-- *** Data changes ***
-- RLS

-- Data
--remove duplicate data from all enhesa tables that used to have a protocol column
DELETE 
  FROM CSR.ENHESA_HEADING
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_HEADING
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, HEADING_CODE ) 
		  FROM CSR.ENHESA_HEADING 
		  ) 
	);

DELETE 
  FROM CSR.ENHESA_HEADING_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_HEADING_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, HEADING_CODE, LANG) 
		  FROM CSR.ENHESA_HEADING_TEXT 
		  ) 
	);	

DELETE 
  FROM CSR.ENHESA_RQMT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_RQMT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, QN_CODE) 
		  FROM CSR.ENHESA_RQMT 
		  ) 
	);	

DELETE 
  FROM CSR.ENHESA_RQMT_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_RQMT_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, QN_CODE, LANG ) 
		  FROM CSR.ENHESA_RQMT_TEXT 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_RQMT_DOMAIN
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_RQMT_DOMAIN
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, QN_CODE, DOMAIN ) 
		  FROM CSR.ENHESA_RQMT_DOMAIN 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_RQMT_REG_CITATION
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_RQMT_REG_CITATION
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, QN_CODE, REG_ID ) 
		  FROM CSR.ENHESA_RQMT_REG_CITATION 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_RQMT_SUP_DOC
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_RQMT_SUP_DOC
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, QN_CODE, ITEM_ID ) 
		  FROM CSR.ENHESA_RQMT_SUP_DOC 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_SUP_DOC
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_SUP_DOC
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, ITEM_ID ) 
		  FROM CSR.ENHESA_SUP_DOC 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_SUP_DOC_ITEM_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_SUP_DOC_ITEM_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, ITEM_ID, LANG ) 
		  FROM CSR.ENHESA_SUP_DOC_ITEM_TEXT 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_INTRO
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_INTRO
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, INTRO_ID ) 
		  FROM CSR.ENHESA_INTRO 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_INTRO_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_INTRO_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, INTRO_ID, LANG ) 
		  FROM CSR.ENHESA_INTRO_TEXT 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_SCRNGQN
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_SCRNGQN
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, SCRNGQN_ID ) 
		  FROM CSR.ENHESA_SCRNGQN 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_SCRNGQN_HEADING
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_SCRNGQN_HEADING
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, SCRNGQN_ID, HEADING_CODE ) 
		  FROM CSR.ENHESA_SCRNGQN_HEADING 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_SCRNGQN_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_SCRNGQN_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, SCRNGQN_ID, LANG ) 
		  FROM CSR.ENHESA_SCRNGQN_TEXT 
		  ) 
	);	
	
DELETE 
  FROM CSR.ENHESA_KEYWORD
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_KEYWORD
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, KEYWORD_ID ) 
		  FROM CSR.ENHESA_KEYWORD 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_KEYWORD_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_KEYWORD_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, KEYWORD_ID, LANG ) 
		  FROM CSR.ENHESA_KEYWORD_TEXT 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_REG
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_REG
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, REG_ID ) 
		  FROM CSR.ENHESA_REG 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_REG_HEADING
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_REG_HEADING
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, REG_ID, HEADING_CODE ) 
		  FROM CSR.ENHESA_REG_HEADING 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_REG_REGION
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_REG_REGION
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, REG_ID, COUNTRY_CODE, REGION_CODE ) 
		  FROM CSR.ENHESA_REG_REGION 
		  ) 
	);

DELETE 
  FROM CSR.ENHESA_REG_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_REG_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, REG_ID, LANG ) 
		  FROM CSR.ENHESA_REG_TEXT 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID ) 
		  FROM CSR.ENHESA_TOPIC 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_REGION
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_REGION
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, COUNTRY_CODE, REGION_CODE ) 
		  FROM CSR.ENHESA_TOPIC_REGION 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_HEADING
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_HEADING
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, HEADING_CODE ) 
		  FROM CSR.ENHESA_TOPIC_HEADING 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_REG
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_REG
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, REG_ID ) 
		  FROM CSR.ENHESA_TOPIC_REG 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_KEYWORD
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_KEYWORD
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, KEYWORD_ID ) 
		  FROM CSR.ENHESA_TOPIC_KEYWORD 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_AUTH
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_AUTH
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, ENHESA_TOPIC_AUTH_ID ) 
		  FROM CSR.ENHESA_TOPIC_AUTH 
		  ) 
	);

DELETE 
  FROM CSR.ENHESA_TOPIC_AUTH_ORG_TITLE
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_AUTH_ORG_TITLE
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, ENHESA_TOPIC_AUTH_ID, LANG ) 
		  FROM CSR.ENHESA_TOPIC_AUTH_ORG_TITLE 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_TEXT
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_TEXT
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, LANG ) 
		  FROM CSR.ENHESA_TOPIC_TEXT 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_ISSUE
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_ISSUE
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, ISSUE_ID ) 
		  FROM CSR.ENHESA_TOPIC_ISSUE 
		  ) 
	);
	
DELETE 
  FROM CSR.ENHESA_TOPIC_SCHED_TASK
 WHERE ROWID NOT IN (
	SELECT ROWID 
	  FROM CSR.ENHESA_TOPIC_SCHED_TASK
	 WHERE ROWID IN ( 
		SELECT MAX(ROWID) over ( PARTITION BY APP_SID, TOPIC_ID, ISSUE_SCHEDULED_TASK_ID ) 
		  FROM CSR.ENHESA_TOPIC_SCHED_TASK 
		  ) 
	);
	
--add constraints again
ALTER TABLE CSR.ENHESA_LANG ADD CONSTRAINT PK_ENHESA_LANG PRIMARY KEY (LANG); 
ALTER TABLE CSR.ENHESA_LANG ADD CONSTRAINT CHK_ENHESA_LANG_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_LANG_NAME ADD CONSTRAINT PK_ENHESA_LANG_NAME PRIMARY KEY (LANG, NAME_LANG);
ALTER TABLE	CSR.ENHESA_LANG_NAME ADD CONSTRAINT FK_ENH_LANG_NAME_LANG_1 FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_LANG_NAME ADD CONSTRAINT CHK_ENHESA_LANG_NAME_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_COUNTRY ADD CONSTRAINT PK_ENHESA_COUNTRY PRIMARY KEY (COUNTRY_CODE);

ALTER TABLE	CSR.ENHESA_COUNTRY_NAME ADD CONSTRAINT PK_ENHESA_COUNTRY_NAME PRIMARY KEY (COUNTRY_CODE);
ALTER TABLE	CSR.ENHESA_COUNTRY_NAME ADD CONSTRAINT FK_ENH_COUNTRY_NM_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_COUNTRY_NAME ADD CONSTRAINT FK_ENH_COUNTRY_NM_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_COUNTRY_NAME ADD CONSTRAINT CHK_ENHESA_COUNTRY_NAME_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_COUNTRY_REGION ADD CONSTRAINT PK_ENHESA_COUNTRY_REGION PRIMARY KEY (COUNTRY_CODE, REGION_CODE);
ALTER TABLE	CSR.ENHESA_COUNTRY_REGION ADD CONSTRAINT FK_ENH_COUNTRY_RG_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_COUNTRY_REGION_NAME ADD CONSTRAINT PK_ENHESA_COUNTRY_REGION_NAME PRIMARY KEY (COUNTRY_CODE, REGION_CODE, LANG);
ALTER TABLE	CSR.ENHESA_COUNTRY_REGION_NAME ADD CONSTRAINT FK_ENH_COU_REG_NM_ENH_COU_REG FOREIGN KEY (COUNTRY_CODE, REGION_CODE) REFERENCES CSR.ENHESA_COUNTRY_REGION (COUNTRY_CODE, REGION_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_COUNTRY_REGION_NAME ADD CONSTRAINT FK_ENH_COU_REG_NM_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_COUNTRY_REGION_NAME ADD CONSTRAINT CHK_ENHESA_CNTRY_REG_NAME_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_STATUS ADD CONSTRAINT PK_ENHESA_STATUS PRIMARY KEY (STATUS_ID);

ALTER TABLE	CSR.ENHESA_STATUS_NAME ADD CONSTRAINT PK_ENHESA_STATUS_NAME PRIMARY KEY (STATUS_ID, LANG);
ALTER TABLE	CSR.ENHESA_STATUS_NAME ADD CONSTRAINT FK_ENHESA_STATUS_NAME_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_STATUS_NAME ADD CONSTRAINT CHK_ENHESA_STATUS_NAME_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_HEADING ADD CONSTRAINT PK_ENHESA_HEADING PRIMARY KEY (APP_SID, HEADING_CODE);

ALTER TABLE	CSR.ENHESA_HEADING_TEXT ADD CONSTRAINT PK_ENHESA_HEADING_TEXT PRIMARY KEY (APP_SID, HEADING_CODE, LANG);
ALTER TABLE	CSR.ENHESA_HEADING_TEXT ADD CONSTRAINT FK_ENHESA_HEAD_TXT_HEADING FOREIGN KEY (APP_SID, HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_HEADING_TEXT ADD CONSTRAINT FK_ENHESA_HEAD_TXT_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_HEADING_TEXT ADD CONSTRAINT CHK_ENHESA_HEADING_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_RQMT ADD CONSTRAINT PK_ENHESA_RQMT PRIMARY KEY (APP_SID, QN_CODE);
ALTER TABLE	CSR.ENHESA_RQMT ADD CONSTRAINT FK_ENHESA_RQMT_HEAD FOREIGN KEY (APP_SID, HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_RQMT ADD CONSTRAINT FK_ENHESA_RQMT_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_RQMT ADD CONSTRAINT FK_ENHESA_RQMT_REGION FOREIGN KEY (COUNTRY_CODE, REGION_CODE) REFERENCES CSR.ENHESA_COUNTRY_REGION (COUNTRY_CODE, REGION_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_RQMT ADD CONSTRAINT CHK_ENHESA_RQMT_ARCHIVED CHECK (ARCHIVED IN (0,1));

ALTER TABLE	CSR.ENHESA_RQMT_TEXT ADD CONSTRAINT PK_ENHESA_RQMT_TEXT PRIMARY KEY (APP_SID, QN_CODE, LANG);
ALTER TABLE	CSR.ENHESA_RQMT_TEXT ADD CONSTRAINT FK_ENHESA_RQMT_TEXT_RQMT FOREIGN KEY (APP_SID, QN_CODE) REFERENCES CSR.ENHESA_RQMT (APP_SID, QN_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_RQMT_TEXT ADD CONSTRAINT FK_ENHESA_RQMT_TEXT_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_RQMT_TEXT ADD CONSTRAINT CHK_ENHESA_RQMT_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_RQMT_DOMAIN ADD CONSTRAINT PK_ENHESA_RQMT_DOMAIN PRIMARY KEY (APP_SID, QN_CODE, DOMAIN);
ALTER TABLE	CSR.ENHESA_RQMT_DOMAIN ADD CONSTRAINT FK_ENHESA_RQMT_DOMAIN_RQMT FOREIGN KEY (APP_SID, QN_CODE) REFERENCES CSR.ENHESA_RQMT (APP_SID, QN_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_RQMT_REG_CITATION ADD CONSTRAINT PK_ENHESA_RQMT_REG_CIT PRIMARY KEY (APP_SID, QN_CODE, REG_ID);
ALTER TABLE	CSR.ENHESA_RQMT_REG_CITATION ADD CONSTRAINT FK_ENHESA_RQMT_REG_CIT_RQMT FOREIGN KEY (APP_SID, QN_CODE) REFERENCES CSR.ENHESA_RQMT (APP_SID, QN_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_RQMT_SUP_DOC ADD CONSTRAINT PK_ENHESA_RQMT_SUP_DOC PRIMARY KEY (APP_SID, QN_CODE, ITEM_ID);
ALTER TABLE	CSR.ENHESA_RQMT_SUP_DOC ADD CONSTRAINT FK_ENHESA_RQMT_SUP_DOC_RQMT FOREIGN KEY (APP_SID, QN_CODE) REFERENCES CSR.ENHESA_RQMT (APP_SID, QN_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_SUP_DOC ADD CONSTRAINT PK_ENHESA_SUP_DOC PRIMARY KEY (APP_SID, ITEM_ID);
ALTER TABLE	CSR.ENHESA_SUP_DOC ADD CONSTRAINT FK_ENHESA_SUP_DOC_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SUP_DOC ADD CONSTRAINT FK_ENHESA_SUP_DOC_REGION FOREIGN KEY (COUNTRY_CODE, REGION_CODE) REFERENCES CSR.ENHESA_COUNTRY_REGION (COUNTRY_CODE, REGION_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SUP_DOC ADD CONSTRAINT CHK_ENHESA_SUP_DOC_ARCHIVED CHECK (ARCHIVED IN (0,1));

ALTER TABLE	CSR.ENHESA_SUP_DOC_ITEM_TEXT ADD CONSTRAINT PK_ENHESA_SUP_DOC_ITM_TEXT PRIMARY KEY (APP_SID, ITEM_ID, LANG);
ALTER TABLE	CSR.ENHESA_SUP_DOC_ITEM_TEXT ADD CONSTRAINT FK_ENHESA_SUP_DOC_ITM_TXT_DOC FOREIGN KEY (APP_SID, ITEM_ID) REFERENCES CSR.ENHESA_SUP_DOC (APP_SID, ITEM_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SUP_DOC_ITEM_TEXT ADD CONSTRAINT FK_ENHESA_SUP_DOC_ITM_TXT_LNG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SUP_DOC_ITEM_TEXT ADD CONSTRAINT CHK_ENHESA_SUP_DOC_ITM_TXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_INTRO ADD CONSTRAINT PK_ENHESA_INTRO PRIMARY KEY (APP_SID, INTRO_ID);
ALTER TABLE	CSR.ENHESA_INTRO ADD CONSTRAINT FK_ENHESA_INTRO_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_INTRO ADD CONSTRAINT FK_ENHESA_INTRO_REGION FOREIGN KEY (COUNTRY_CODE, REGION_CODE) REFERENCES CSR.ENHESA_COUNTRY_REGION (COUNTRY_CODE, REGION_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_INTRO ADD CONSTRAINT FK_ENHESA_INTRO_HEAD FOREIGN KEY (APP_SID, HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_INTRO ADD CONSTRAINT CHK_ENHESA_INTRO_ARCHIVED CHECK (ARCHIVED IN (0,1));

ALTER TABLE	CSR.ENHESA_INTRO_TEXT ADD CONSTRAINT PK_ENHESA_INTRO_TEXT PRIMARY KEY (APP_SID, INTRO_ID, LANG);
ALTER TABLE	CSR.ENHESA_INTRO_TEXT ADD CONSTRAINT FK_ENHESA_INTRO_TEXT_INTRO FOREIGN KEY (APP_SID, INTRO_ID) REFERENCES CSR.ENHESA_INTRO (APP_SID, INTRO_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_INTRO_TEXT ADD CONSTRAINT FK_ENHESA_INTRO_TEXT_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_INTRO_TEXT ADD CONSTRAINT CHK_ENHESA_INTRO_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_SCRNGQN ADD CONSTRAINT PK_ENHESA_SCRNGQN PRIMARY KEY (APP_SID, SCRNGQN_ID);
ALTER TABLE	CSR.ENHESA_SCRNGQN ADD CONSTRAINT FK_ENHESA_SCRNGQN_HEAD FOREIGN KEY (APP_SID, BASE_HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SCRNGQN ADD CONSTRAINT CHK_ENHESA_SCRNGQN_ARCHIVED CHECK (ARCHIVED IN (0,1));

ALTER TABLE	CSR.ENHESA_SCRNGQN_HEADING ADD CONSTRAINT PK_ENHESA_SCRNGQN_HEAD PRIMARY KEY (APP_SID, SCRNGQN_ID, HEADING_CODE);
ALTER TABLE	CSR.ENHESA_SCRNGQN_HEADING ADD CONSTRAINT FK_ENHESA_SCRNGQN_HEAD_SCQN FOREIGN KEY (APP_SID, SCRNGQN_ID) REFERENCES CSR.ENHESA_SCRNGQN (APP_SID, SCRNGQN_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SCRNGQN_HEADING ADD CONSTRAINT FK_ENHESA_SCRNGQN_HEAD_HEAD FOREIGN KEY (APP_SID, HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_SCRNGQN_TEXT ADD CONSTRAINT PK_ENHESA_SCRNGQN_TEXT PRIMARY KEY (APP_SID, SCRNGQN_ID, LANG);
ALTER TABLE	CSR.ENHESA_SCRNGQN_TEXT ADD CONSTRAINT FK_ENHESA_SCRNGQN_TEXT_SCRNGQN FOREIGN KEY (APP_SID, SCRNGQN_ID) REFERENCES CSR.ENHESA_SCRNGQN (APP_SID, SCRNGQN_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SCRNGQN_TEXT ADD CONSTRAINT FK_ENHESA_SCRNGQN_TEXT_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_SCRNGQN_TEXT ADD CONSTRAINT CHK_ENHESA_SCRNGQN_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_KEYWORD ADD CONSTRAINT PK_ENHESA_KEYWORD PRIMARY KEY (APP_SID, KEYWORD_ID);

ALTER TABLE	CSR.ENHESA_KEYWORD_TEXT ADD CONSTRAINT PK_ENHESA_KEYWORD_TEXT PRIMARY KEY (APP_SID, KEYWORD_ID, LANG);
ALTER TABLE	CSR.ENHESA_KEYWORD_TEXT ADD CONSTRAINT FK_ENHESA_KEYWD_TEXT_KEYWD FOREIGN KEY (APP_SID, KEYWORD_ID) REFERENCES CSR.ENHESA_KEYWORD (APP_SID, KEYWORD_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_KEYWORD_TEXT ADD CONSTRAINT FK_ENHESA_KEYWORD_TEXT_LANG FOREIGN KEY (LANG) REFERENCES CSR.ENHESA_LANG (LANG) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_KEYWORD_TEXT ADD CONSTRAINT CHK_ENHESA_KEYWORD_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_REG ADD CONSTRAINT PK_ENHESA_REG PRIMARY KEY (APP_SID, REG_ID);
ALTER TABLE	CSR.ENHESA_REG ADD CONSTRAINT FK_ENHESA_REG_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_REG ADD CONSTRAINT CHK_ENH_REG_ARCHIVED CHECK (ARCHIVED IN (0,1));

ALTER TABLE	CSR.ENHESA_REG_HEADING ADD CONSTRAINT PK_ENHESA_REG_HEADING PRIMARY KEY (APP_SID, REG_ID, HEADING_CODE);
ALTER TABLE	CSR.ENHESA_REG_HEADING ADD CONSTRAINT FK_ENH_REG_HEAD_REG FOREIGN KEY (APP_SID, REG_ID) REFERENCES CSR.ENHESA_REG (APP_SID, REG_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_REG_HEADING ADD CONSTRAINT FK_ENH_REG_HEAD_HEAD FOREIGN KEY (APP_SID, HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_REG_REGION ADD CONSTRAINT PK_ENHESA_REG_REGION PRIMARY KEY (APP_SID, REG_ID, COUNTRY_CODE, REGION_CODE);
ALTER TABLE	CSR.ENHESA_REG_REGION ADD CONSTRAINT FK_ENH_REG_REGION_REG FOREIGN KEY (APP_SID, REG_ID) REFERENCES CSR.ENHESA_REG (APP_SID, REG_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_REG_REGION ADD CONSTRAINT FK_ENH_REG_REGION_REGION FOREIGN KEY (COUNTRY_CODE, REGION_CODE) REFERENCES CSR.ENHESA_COUNTRY_REGION (COUNTRY_CODE, REGION_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_REG_TEXT ADD CONSTRAINT PK_ENHESA_REG_TEXT PRIMARY KEY (APP_SID, REG_ID, LANG);
ALTER TABLE	CSR.ENHESA_REG_TEXT ADD CONSTRAINT FK_ENHESA_REG_TEXT_REG FOREIGN KEY (APP_SID, REG_ID) REFERENCES CSR.ENHESA_REG (APP_SID, REG_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_REG_TEXT ADD CONSTRAINT CHK_ENHESA_REG_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_TOPIC ADD CONSTRAINT PK_ENHESA_TOPIC PRIMARY KEY (APP_SID, TOPIC_ID);
ALTER TABLE	CSR.ENHESA_TOPIC ADD CONSTRAINT UK_ENHESA_TOPIC UNIQUE (APP_SID, TOPIC_ID, COUNTRY_CODE);
ALTER TABLE	CSR.ENHESA_TOPIC ADD CONSTRAINT FK_ENHESA_TOPIC_STATUS FOREIGN KEY (STATUS_ID) REFERENCES CSR.ENHESA_STATUS (STATUS_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC ADD CONSTRAINT FK_ENHESA_TOPIC_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES CSR.ENHESA_COUNTRY (COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC ADD CONSTRAINT CHK_ENH_TOP_ARCHIVED CHECK (ARCHIVED IN (0,1));

ALTER TABLE	CSR.ENHESA_TOPIC_REGION ADD CONSTRAINT PK_ENHESA_TOPIC_REGION PRIMARY KEY (APP_SID, TOPIC_ID, COUNTRY_CODE, REGION_CODE);
ALTER TABLE	CSR.ENHESA_TOPIC_REGION ADD CONSTRAINT FK_ENHESA_TOP_RG_TOP FOREIGN KEY (APP_SID, TOPIC_ID, COUNTRY_CODE) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID, COUNTRY_CODE) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC_REGION ADD CONSTRAINT FK_ENHESA_TOP_RG_COU_RG FOREIGN KEY (COUNTRY_CODE, REGION_CODE) REFERENCES CSR.ENHESA_COUNTRY_REGION (COUNTRY_CODE, REGION_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_TOPIC_HEADING ADD CONSTRAINT PK_ENHESA_TOPIC_HEADING PRIMARY KEY (APP_SID, TOPIC_ID, HEADING_CODE);
ALTER TABLE	CSR.ENHESA_TOPIC_HEADING ADD CONSTRAINT FK_ENHESA_TOP_HEAD_TOP FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC_HEADING ADD CONSTRAINT FK_ENHESA_TOP_HEAD_HEAD FOREIGN KEY (APP_SID, HEADING_CODE) REFERENCES CSR.ENHESA_HEADING (APP_SID, HEADING_CODE) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_TOPIC_REG ADD CONSTRAINT PK_ENHESA_TOPIC_REG PRIMARY KEY (APP_SID, TOPIC_ID, REG_ID);
ALTER TABLE	CSR.ENHESA_TOPIC_REG ADD CONSTRAINT FK_ENHESA_TOP_REG_TOP FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC_REG ADD CONSTRAINT FK_ENHESA_TOP_REG_REG FOREIGN KEY (APP_SID, REG_ID) REFERENCES CSR.ENHESA_REG (APP_SID, REG_ID) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_TOPIC_KEYWORD ADD CONSTRAINT PK_ENHESA_TOPIC_KEYWD PRIMARY KEY (APP_SID, TOPIC_ID, KEYWORD_ID);
ALTER TABLE	CSR.ENHESA_TOPIC_KEYWORD ADD CONSTRAINT FK_ENHESA_TOP_KEYWD_TOP FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC_KEYWORD ADD CONSTRAINT FK_ENHESA_TOP_KEYWD_KEYWD FOREIGN KEY (APP_SID, KEYWORD_ID) REFERENCES CSR.ENHESA_KEYWORD (APP_SID, KEYWORD_ID) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_TOPIC_AUTH ADD CONSTRAINT PK_ENHESA_TOPIC_AUTH PRIMARY KEY (APP_SID, ENHESA_TOPIC_AUTH_ID);
ALTER TABLE	CSR.ENHESA_TOPIC_AUTH ADD CONSTRAINT UK_ENHESA_TOPIC_AUTH UNIQUE (APP_SID, TOPIC_ID);
ALTER TABLE	CSR.ENHESA_TOPIC_AUTH ADD CONSTRAINT FK_ENHESA_TOP_AUTH_TOP FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_TOPIC_AUTH_ORG_TITLE ADD CONSTRAINT PK_ENHESA_TOPIC_AUTH_ORG_TITLE PRIMARY KEY (APP_SID, ENHESA_TOPIC_AUTH_ID, LANG);
ALTER TABLE	CSR.ENHESA_TOPIC_AUTH_ORG_TITLE ADD CONSTRAINT FK_ENH_TOP_AUTH_ORG_TIT_AUTH FOREIGN KEY (APP_SID, ENHESA_TOPIC_AUTH_ID) REFERENCES CSR.ENHESA_TOPIC_AUTH (APP_SID, ENHESA_TOPIC_AUTH_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC_AUTH_ORG_TITLE ADD CONSTRAINT CHK_EN_TP_AUTH_ORG_TITLE_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_TOPIC_TEXT ADD CONSTRAINT PK_ENHESA_TOPIC_TEXT PRIMARY KEY (APP_SID, TOPIC_ID, LANG);
ALTER TABLE	CSR.ENHESA_TOPIC_TEXT ADD CONSTRAINT FK_ENHESA_TOP_TEXT_TOP FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;
ALTER TABLE	CSR.ENHESA_TOPIC_TEXT ADD CONSTRAINT CHK_ENHESA_TOPIC_TEXT_UC CHECK (LANG = UPPER(LANG));

ALTER TABLE	CSR.ENHESA_TOPIC_ISSUE ADD CONSTRAINT PK_ENHESA_TOPIC_ISSUE PRIMARY KEY (APP_SID, TOPIC_ID, ISSUE_ID);
ALTER TABLE	CSR.ENHESA_TOPIC_ISSUE ADD CONSTRAINT FK_ENHESA_TOP_ISS_TOP FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;

ALTER TABLE	CSR.ENHESA_TOPIC_SCHED_TASK ADD CONSTRAINT PK_ENHESA_TOPIC_SCD_TSK PRIMARY KEY (APP_SID, TOPIC_ID, ISSUE_SCHEDULED_TASK_ID);
ALTER TABLE	CSR.ENHESA_TOPIC_SCHED_TASK ADD CONSTRAINT FK_ENHESA_TOPIC_SCD_TSK_T FOREIGN KEY (APP_SID, TOPIC_ID) REFERENCES CSR.ENHESA_TOPIC (APP_SID, TOPIC_ID) ON DELETE CASCADE;


-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***

@../enhesa_pkg
@../enhesa_body

@update_tail




	  



