define version=2077
@update_header

INSERT INTO CSR.STD_MEASURE_CONVERSION(STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28119, 2,'mg',1000000,1,0,1);

@update_tail
