-- Please update version.sql too -- this keeps clean builds in sync
define version=460
@update_header
 

--
-- SEQUENCE: ISSUE_LOG_FILE_ID_SEQ 
--

CREATE SEQUENCE ISSUE_LOG_FILE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: CSR.ISSUE_LOG_FILE 
--

CREATE TABLE CSR.ISSUE_LOG_FILE(
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    ISSUE_LOG_FILE_ID    NUMBER(10, 0)    NOT NULL,
    ISSUE_LOG_ID         NUMBER(10, 0)    NOT NULL,
    FILENAME             VARCHAR2(255)    NOT NULL,
    MIME_TYPE            VARCHAR2(256)    NOT NULL,
    DATA                 BLOB             NOT NULL,
    SHA1                 RAW(20)          NOT NULL,
    CONSTRAINT PK_ISSUE_LOG_FILE PRIMARY KEY (APP_SID, ISSUE_LOG_FILE_ID)
)
;


--
-- TABLE: CSR.ISSUE_LOG_FILE 
--
ALTER TABLE CSR.ISSUE_LOG_FILE ADD CONSTRAINT RefISSUE_LOG1649
    FOREIGN KEY (APP_SID, ISSUE_LOG_ID)
    REFERENCES ISSUE_LOG(APP_SID, ISSUE_LOG_ID)
;

ALTER TABLE CSR.ISSUE_LOG_FILE ADD CONSTRAINT RefCUSTOMER1650
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

@..\issue_pkg
@..\issue_body


@update_tail
