-- Please update version.sql too -- this keeps clean builds in sync
define version=3165
define minor_version=1
@update_header

-- *** DDL ***
-- Create tables

CREATE SEQUENCE CSR.ENHESA_SITE_TYPE_ID_SEQ
;

CREATE TABLE CSR.ENHESA_SITE_TYPE(
    APP_SID             		NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	SITE_TYPE_ID				NUMBER(10, 0),
	LABEL						VARCHAR2(256),
	CONSTRAINT PK_ENHESA_SITE_TYPE PRIMARY KEY (APP_SID, SITE_TYPE_ID)
)
;

CREATE SEQUENCE CSR.ENHESA_SITE_TYP_HEADING_ID_SEQ
;

CREATE TABLE CSR.ENHESA_SITE_TYPE_HEADING(
    APP_SID             		NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    SITE_TYPE_HEADING_ID		NUMBER(10, 0),
	SITE_TYPE_ID				NUMBER(10, 0),
	HEADING_CODE				VARCHAR2(256),
	CONSTRAINT PK_SITE_TYPE_HEADING PRIMARY KEY (APP_SID, SITE_TYPE_HEADING_ID),
	CONSTRAINT UK_SITE_TYPE_HEADING UNIQUE (APP_SID, SITE_TYPE_ID, HEADING_CODE),
	CONSTRAINT FK_SITE_TYP_HEADING_SITE_TYP FOREIGN KEY (APP_SID, SITE_TYPE_ID)
		REFERENCES CSR.ENHESA_SITE_TYPE (APP_SID, SITE_TYPE_ID)
)
;

CREATE INDEX CSR.IX_SITE_TYP_HEADING_SITE_TYP ON CSR.ENHESA_SITE_TYPE_HEADING(APP_SID, SITE_TYPE_ID)
;

CREATE TABLE CSRIMP.ENHESA_SITE_TYPE(
    CSRIMP_SESSION_ID           NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	SITE_TYPE_ID				NUMBER(10),
	LABEL						VARCHAR2(256),
	CONSTRAINT pk_enhesa_site_type PRIMARY KEY (csrimp_session_id),
    CONSTRAINT fk_enhesa_site_type
		FOREIGN KEY (csrimp_session_id)
		REFERENCES csrimp.csrimp_session (csrimp_session_id)
		ON DELETE CASCADE
)
;

CREATE TABLE CSRIMP.ENHESA_SITE_TYPE_HEADING(
    CSRIMP_SESSION_ID           NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    SITE_TYPE_HEADING_ID		NUMBER(10),
	SITE_TYPE_ID				NUMBER(10),
	HEADING_CODE				VARCHAR2(256),
	CONSTRAINT pk_enhesa_site_type_heading PRIMARY KEY (csrimp_session_id),
    CONSTRAINT fk_enhesa_site_type_heading
		FOREIGN KEY (csrimp_session_id)
		REFERENCES csrimp.csrimp_session (csrimp_session_id)
		ON DELETE CASCADE
)
;

-- Alter tables

-- *** Grants ***

GRANT SELECT, INSERT, UPDATE ON csr.enhesa_site_type TO csrimp;
GRANT SELECT, INSERT, UPDATE ON csr.enhesa_site_type_heading TO csrimp;

GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_site_type TO tool_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.enhesa_site_type_heading TO tool_user;

GRANT SELECT ON csr.enhesa_site_type_id_seq TO csrimp;
GRANT SELECT ON csr.enhesa_site_typ_heading_id_seq TO csrimp;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

INSERT INTO CSR.SCHEMA_TABLE
(OWNER, TABLE_NAME, ENABLE_EXPORT, ENABLE_IMPORT, CSRIMP_TABLE_NAME, MODULE_NAME)
VALUES
('CSR', 'ENHESA_SITE_TYPE', 1, 1, 'ENHESA_SITE_TYPE', 'Enhesa')
;

INSERT INTO CSR.SCHEMA_TABLE
(OWNER, TABLE_NAME, ENABLE_EXPORT, ENABLE_IMPORT, CSRIMP_TABLE_NAME, MODULE_NAME)
VALUES
('CSR', 'ENHESA_SITE_TYPE_HEADING', 1, 1, 'ENHESA_SITE_TYPE_HEADING', 'Enhesa')
;

INSERT INTO CSR.SCHEMA_COLUMN
(OWNER, TABLE_NAME, COLUMN_NAME, ENABLE_EXPORT, ENABLE_IMPORT, SEQUENCE_OWNER, SEQUENCE_NAME)
VALUES
('CSR', 'ENHESA_SITE_TYPE', 'SITE_TYPE_ID', 1, 1, 'CSR', 'ENHESA_SITE_TYPE_ID_SEQ')
;

INSERT INTO CSR.SCHEMA_COLUMN
(OWNER, TABLE_NAME, COLUMN_NAME, ENABLE_EXPORT, ENABLE_IMPORT, SEQUENCE_OWNER, SEQUENCE_NAME)
VALUES
('CSR', 'ENHESA_SITE_TYPE_HEADING', 'SITE_TYPE_HEADING_ID', 1, 1, 'CSR', 'ENHESA_SITE_TYP_HEADING_ID_SEQ')
;

INSERT INTO CSR.SCHEMA_COLUMN
(OWNER, TABLE_NAME, COLUMN_NAME, ENABLE_EXPORT, ENABLE_IMPORT, SEQUENCE_OWNER, SEQUENCE_NAME, IS_MAP_SOURCE)
VALUES
('CSR', 'ENHESA_SITE_TYPE_HEADING', 'SITE_TYPE_ID', 1, 1, 'CSR', 'ENHESA_SITE_TYPE_ID_SEQ', 0)
;

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***

@../compliance_pkg

@../compliance_body

@update_tail
