-- Please update version.sql too -- this keeps clean builds in sync
define version=402
@update_header




CREATE TABLE SNAPSHOT_TAG_GROUP(
    APP_SID         NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    NAME            VARCHAR2(255)    NOT NULL,
    TAG_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK674 PRIMARY KEY (APP_SID, NAME, TAG_GROUP_ID)
)
;

ALTER TABLE SNAPSHOT_TAG_GROUP ADD CONSTRAINT RefTAG_GROUP1423 
    FOREIGN KEY (APP_SID, TAG_GROUP_ID)
    REFERENCES TAG_GROUP(APP_SID, TAG_GROUP_ID)
;

ALTER TABLE SNAPSHOT_TAG_GROUP ADD CONSTRAINT RefSNAPSHOT1424 
    FOREIGN KEY (APP_SID, NAME)
    REFERENCES SNAPSHOT(APP_SID, NAME)
;

INSERT INTO SNAPSHOT_TAG_GROUP (app_sid, name, tag_group_id)
	SELECT app_sid, name,tag_group_id 
	  FROM snapshot
	 WHERE tag_group_Id IS NOT NULL;

ALTER TABLE SNAPSHOT DROP CONSTRAINT RefTAG_GROUP868;

ALTER TABLE SNAPSHOT DROP COLUMN TAG_GROUP_ID;

ALTER TABLE SNAPSHOT ADD (
    USE_UNMERGED             NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CONSTRAINT CHK_SNAPSHOT_USE_UNMERGED CHECK (USE_UNMERGED IN (0,1))
);


@../snapshot_pkg
@../snapshot_body


@update_tail
