-- Please update version.sql too -- this keeps clean builds in sync
define version=307
@update_header

ALTER TABLE ALL_METER ADD (
	UTILITY_CONTRACT_ID	NUMBER(10, 0) 	NULL,
	REFERENCE			VARCHAR2(256)	NULL
);


COMMENT ON COLUMN ALL_METER.UTILITY_CONTRACT_ID IS 'desc="Contract ID",auto'
;

CREATE TABLE CONTRACT_DURATION(
    CONTRACT_DURATION_ID    NUMBER(10, 0)    NOT NULL,
    DURATION_MONTHS         NUMBER(10, 0)    NOT NULL,
    LABEL                   VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK582 PRIMARY KEY (CONTRACT_DURATION_ID)
)
;

COMMENT ON TABLE CONTRACT_DURATION IS 'desc="Contract Duration"'
;

CREATE TABLE UTILITY_CONTRACT(
    APP_SID                 NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    UTILITY_CONTRACT_ID     NUMBER(10, 0)    NOT NULL,
    UTILITY_SUPPLIER_ID     NUMBER(10, 0)    NOT NULL,
    ACCOUNT_REF             VARCHAR2(256)    NOT NULL,
    FROM_DTM                DATE             NOT NULL,
    CONTRACT_DURATION_ID    NUMBER(10, 0)    NOT NULL,
    DURATION_OTHER          NUMBER(10, 0)    DEFAULT 0 NOT NULL,
    ALERT_WHEN_DUE          NUMBER(1, 0)     NOT NULL,
    FILE_DATA               BLOB,
    FILE_MIME_TYPE          VARCHAR2(256),
    FILE_NAME               VARCHAR2(256),
    CONSTRAINT PK577 PRIMARY KEY (APP_SID, UTILITY_CONTRACT_ID)
)
;



COMMENT ON TABLE UTILITY_CONTRACT IS 'desc="Utiltiy Contract"'
;
COMMENT ON COLUMN UTILITY_CONTRACT.APP_SID IS 'desc="App SID",app'
;
COMMENT ON COLUMN UTILITY_CONTRACT.UTILITY_CONTRACT_ID IS 'desc="Contract ID",auto'
;
COMMENT ON COLUMN UTILITY_CONTRACT.UTILITY_SUPPLIER_ID IS 'desc="Supplier ID",auto'
;
COMMENT ON COLUMN UTILITY_CONTRACT.ACCOUNT_REF IS 'desc="Account Ref"'
;
COMMENT ON COLUMN UTILITY_CONTRACT.FROM_DTM IS 'desc="From Date"'
;
COMMENT ON COLUMN UTILITY_CONTRACT.CONTRACT_DURATION_ID IS 'desc="Contract Duration",enum,enum_desc_col=label'
;
COMMENT ON COLUMN UTILITY_CONTRACT.DURATION_OTHER IS 'desc="Other Duration"'
;
COMMENT ON COLUMN UTILITY_CONTRACT.ALERT_WHEN_DUE IS 'desc="Alert When Due",bool'
;
COMMENT ON COLUMN UTILITY_CONTRACT.FILE_DATA IS 'desc="Document",file,file_mime=file_mime_type,file_name=file_name'
;


CREATE TABLE UTILITY_INVOICE(
    APP_SID                NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    UTILITY_INVOICE_ID     NUMBER(10, 0)     NOT NULL,
    UTILITY_CONTRACT_ID    NUMBER(10, 0)     NOT NULL,
    REFERENCE              VARCHAR2(256)     NOT NULL,
    INVOICE_DTM            DATE              NOT NULL,
    COST_VALUE             NUMBER(24, 16)    NOT NULL,
    FILE_DATA              BLOB,
    FILE_MIME_TYPE         VARCHAR2(256),
    FILE_NAME              VARCHAR2(256),
    CONSTRAINT PK578 PRIMARY KEY (APP_SID, UTILITY_INVOICE_ID)
)
;



COMMENT ON TABLE UTILITY_INVOICE IS 'desc="Utility Invoice"'
;
COMMENT ON COLUMN UTILITY_INVOICE.APP_SID IS 'desc="App SID",app'
;
COMMENT ON COLUMN UTILITY_INVOICE.UTILITY_INVOICE_ID IS 'desc="Invoice ID",auto'
;
COMMENT ON COLUMN UTILITY_INVOICE.UTILITY_CONTRACT_ID IS 'desc="Contract ID",auto'
;
COMMENT ON COLUMN UTILITY_INVOICE.REFERENCE IS 'desc="Reference"'
;
COMMENT ON COLUMN UTILITY_INVOICE.INVOICE_DTM IS 'desc="Invoice Date"'
;
COMMENT ON COLUMN UTILITY_INVOICE.COST_VALUE IS 'desc="Invlice Value"'
;
COMMENT ON COLUMN UTILITY_INVOICE.FILE_DATA IS 'desc="Invoice Copy",file,file_mime=file_mime_type,file_name=file_name'
;


CREATE TABLE UTILITY_SUPPLIER(
    APP_SID                NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    UTILITY_SUPPLIER_ID    NUMBER(10, 0)     NOT NULL,
    SUPPLIER_NAME          VARCHAR2(1024)    NOT NULL,
    CONTACT_DETAILS        VARCHAR2(4000),
    CONSTRAINT PK576 PRIMARY KEY (APP_SID, UTILITY_SUPPLIER_ID)
)
;



COMMENT ON TABLE UTILITY_SUPPLIER IS 'desc="Utility Supplier"'
;
COMMENT ON COLUMN UTILITY_SUPPLIER.APP_SID IS 'desc="App SID",app'
;
COMMENT ON COLUMN UTILITY_SUPPLIER.UTILITY_SUPPLIER_ID IS 'desc="Supplier ID",auto'
;
COMMENT ON COLUMN UTILITY_SUPPLIER.SUPPLIER_NAME IS 'desc="Supplier Name"'
;
COMMENT ON COLUMN UTILITY_SUPPLIER.CONTACT_DETAILS IS 'desc="Contact Details"'
;


ALTER TABLE ALL_METER ADD CONSTRAINT RefUTILITY_CONTRACT1158 
    FOREIGN KEY (APP_SID, UTILITY_CONTRACT_ID)
    REFERENCES UTILITY_CONTRACT(APP_SID, UTILITY_CONTRACT_ID)
;

ALTER TABLE UTILITY_CONTRACT ADD CONSTRAINT RefCONTRACT_DURATION1159 
    FOREIGN KEY (CONTRACT_DURATION_ID)
    REFERENCES CONTRACT_DURATION(CONTRACT_DURATION_ID)
;

ALTER TABLE UTILITY_CONTRACT ADD CONSTRAINT RefUTILITY_SUPPLIER1160 
    FOREIGN KEY (APP_SID, UTILITY_SUPPLIER_ID)
    REFERENCES UTILITY_SUPPLIER(APP_SID, UTILITY_SUPPLIER_ID)
;

ALTER TABLE UTILITY_CONTRACT ADD CONSTRAINT RefCUSTOMER1161 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

ALTER TABLE UTILITY_INVOICE ADD CONSTRAINT RefCUSTOMER1162 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

ALTER TABLE UTILITY_INVOICE ADD CONSTRAINT RefUTILITY_CONTRACT1163 
    FOREIGN KEY (APP_SID, UTILITY_CONTRACT_ID)
    REFERENCES UTILITY_CONTRACT(APP_SID, UTILITY_CONTRACT_ID)
;

ALTER TABLE UTILITY_SUPPLIER ADD CONSTRAINT RefCUSTOMER1164 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

BEGIN
	INSERT INTO contract_duration (contract_duration_id, duration_months, label) VALUES (1, 1, '1 Month');
	INSERT INTO contract_duration (contract_duration_id, duration_months, label) VALUES (2, 3, '3 Months');
	INSERT INTO contract_duration (contract_duration_id, duration_months, label) VALUES (3, 6, '6 Months');
	INSERT INTO contract_duration (contract_duration_id, duration_months, label) VALUES (4, 12, '1 year');
	INSERT INTO contract_duration (contract_duration_id, duration_months, label) VALUES (5, 0, 'Other');
	COMMIT;
END;
/

-- Add attribute to switch crc type metering on and off
DECLARE
	v_act 			security_pkg.T_ACT_ID;
	v_class_id		security_pkg.T_SID_ID;
	v_attribute_id	security_pkg.T_ATTRIBUTE_ID;
BEGIN
	user_pkg.LogonAuthenticated(security_pkg.SID_BUILTIN_ADMINISTRATOR, NULL, v_act);	
	v_class_id := class_pkg.GetClassId('CSRData');
	attribute_pkg.CreateDefinition(v_act, v_class_id, 'crc-metering-enabled', 0, NULL, v_attribute_id);
	COMMIT;
EXCEPTION
	WHEN security_pkg.DUPLICATE_OBJECT_NAME THEN
		NULL;
END;
/


-----


CREATE TABLE IND_ACTIVITY_TYPE(
    IND_ACTIVITY_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    LABEL                   VARCHAR2(256)    NOT NULL,
    POS                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK588 PRIMARY KEY (IND_ACTIVITY_TYPE_ID)
)
;


ALTER TABLE IND ADD (
	IND_ACTIVITY_TYPE_ID          NUMBER(10, 0),
    CORE                          NUMBER(1, 0)
);

ALTER TABLE IND ADD CONSTRAINT RefIND_ACTIVITY_TYPE1175 
    FOREIGN KEY (IND_ACTIVITY_TYPE_ID)
    REFERENCES IND_ACTIVITY_TYPE(IND_ACTIVITY_TYPE_ID)
;

BEGIN
	INSERT INTO ind_activity_type (ind_activity_type_id, label, pos) VALUES (1, 'n/a', 1);
	INSERT INTO ind_activity_type (ind_activity_type_id, label, pos) VALUES (2, 'Gas', 2);
	INSERT INTO ind_activity_type (ind_activity_type_id, label, pos) VALUES (3, 'Electricity', 3);
	COMMIT;
END;
/

CREATE OR REPLACE VIEW METER
	(REGION_SID, NOTE, PRIMARY_IND_SID, PRIMARY_MEASURE_CONVERSION_ID, METER_SOURCE_TYPE_ID, UTILITY_CONTRACT_ID, REFERENCE) AS
  SELECT REGION_SID, NOTE, PRIMARY_IND_SID, PRIMARY_MEASURE_CONVERSION_ID, METER_SOURCE_TYPE_ID, UTILITY_CONTRACT_ID, REFERENCE
    FROM ALL_METER
   WHERE ACTIVE = 1;

@update_tail
