-- Please update version.sql too -- this keeps clean builds in sync
define version=2418
@update_header

/*
 *  Fully support chain in csrexp/csrimp.
 *  Part 2 - creating csrimp tables, csrimp map tables, adding grants
 */
 
-- creating new csrimp tables
CREATE TABLE CSRIMP.WORKSHEET (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	WORKSHEET_ID NUMBER(10,0) NOT NULL,
	HEADER_ROW_INDEX NUMBER(10,0) NOT NULL,
	LOWER_SHEET_NAME VARCHAR2(1000),
	SHEET_NAME VARCHAR2(1000) NOT NULL,
	WORKSHEET_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_WORKSHEET PRIMARY KEY (CSRIMP_SESSION_ID, WORKSHEET_ID),
	CONSTRAINT FK_WORKSHEET_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.WORKSHEET_COLUMN (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	WORKSHEET_ID NUMBER(10,0) NOT NULL,
	COLUMN_TYPE_ID NUMBER(10,0) NOT NULL,
	COLUMN_INDEX NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_WORKSHEET_COLUMN PRIMARY KEY (CSRIMP_SESSION_ID, WORKSHEET_ID, COLUMN_TYPE_ID),
	CONSTRAINT FK_WORKSHEET_COLUMN_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.WORKSHE_COLUMN_VALUE_MAP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	WORKSHEET_ID NUMBER(10,0) NOT NULL,
	COLUMN_TYPE_ID NUMBER(10,0) NOT NULL,
	VALUE_MAPPER_ID NUMBER(10,0) NOT NULL,
	VALUE_MAP_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_WORKSHE_COLUMN_VALUE_MAP PRIMARY KEY (CSRIMP_SESSION_ID, WORKSHEET_ID, COLUMN_TYPE_ID, VALUE_MAPPER_ID, VALUE_MAP_ID),
	CONSTRAINT FK_WORKSHE_COLUMN_VALUE_MAP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.WORKSHEET_ROW (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	WORKSHEET_ID NUMBER(10,0) NOT NULL,
	ROW_NUMBER NUMBER(10,0) NOT NULL,
	IGNORE NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_WORKSHEET_ROW PRIMARY KEY (CSRIMP_SESSION_ID, WORKSHEET_ID, ROW_NUMBER),
	CONSTRAINT FK_WORKSHEET_ROW_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.WORKSHEET_VALUE_MAP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	VALUE_MAPPER_ID NUMBER(10,0) NOT NULL,
	VALUE_MAP_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_WORKSHEET_VALUE_MAP PRIMARY KEY (CSRIMP_SESSION_ID, VALUE_MAPPER_ID, VALUE_MAP_ID),
	CONSTRAINT FK_WORKSHEET_VALUE_MAP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.WORKSHEE_VALUE_MAP_VALUE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	VALUE_MAP_ID NUMBER(10,0) NOT NULL,
	COLUMN_TYPE_ID NUMBER(10,0) NOT NULL,
	VALUE_MAPPER_ID NUMBER(10,0) NOT NULL,
	VALUE VARCHAR2(1000),
	CONSTRAINT PK_WORKSHEE_VALUE_MAP_VALUE PRIMARY KEY (CSRIMP_SESSION_ID, VALUE_MAP_ID, COLUMN_TYPE_ID, VALUE_MAPPER_ID),
	CONSTRAINT FK_WORKSHEE_VALUE_MAP_VALUE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_ALERT_PARTI_TEMPLA (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_TYPE_ID NUMBER(10,0) NOT NULL,
	PARTIAL_TEMPLATE_TYPE_ID NUMBER(10,0) NOT NULL,
	LANG VARCHAR2(10) NOT NULL,
	PARTIAL_HTML CLOB NOT NULL,
	CONSTRAINT PK_CHAIN_ALERT_PARTI_TEMPLA PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_TYPE_ID, PARTIAL_TEMPLATE_TYPE_ID, LANG),
	CONSTRAINT FK_CHAIN_ALERT_PARTI_TEMPLA_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_ALE_PART_TEMP_PARA (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_TYPE_ID NUMBER(10,0) NOT NULL,
	PARTIAL_TEMPLATE_TYPE_ID NUMBER(10,0) NOT NULL,
	FIELD_NAME VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_CHAIN_ALE_PART_TEMP_PARA PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_TYPE_ID, PARTIAL_TEMPLATE_TYPE_ID, FIELD_NAME),
	CONSTRAINT FK_CHAIN_ALE_PART_TEMP_PARA_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_AMOUNT_UNIT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	AMOUNT_UNIT_ID NUMBER(10,0) NOT NULL,
	CONVERSION_TO_BASE NUMBER(20,10),
	DESCRIPTION VARCHAR2(255) NOT NULL,
	UNIT_TYPE VARCHAR2(32) NOT NULL,
	CONSTRAINT PK_CHAIN_AMOUNT_UNIT PRIMARY KEY (CSRIMP_SESSION_ID, AMOUNT_UNIT_ID),
	CONSTRAINT FK_CHAIN_AMOUNT_UNIT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_AUDIT_REQUEST (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	AUDIT_REQUEST_ID NUMBER(10,0) NOT NULL,
	AUDITEE_COMPANY_SID NUMBER(10,0) NOT NULL,
	AUDITOR_COMPANY_SID NUMBER(10,0) NOT NULL,
	AUDIT_SID NUMBER(10,0),
	NOTES CLOB,
	PROPOSED_DTM DATE,
	REQUESTED_AT_DTM DATE NOT NULL,
	REQUESTED_BY_COMPANY_SID NUMBER(10,0) NOT NULL,
	REQUESTED_BY_USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_AUDIT_REQUEST PRIMARY KEY (CSRIMP_SESSION_ID, AUDIT_REQUEST_ID),
	CONSTRAINT FK_CHAIN_AUDIT_REQUEST_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_AUDIT_REQUES_ALERT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	AUDIT_REQUEST_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	SENT_DTM DATE,
	CONSTRAINT PK_CHAIN_AUDIT_REQUES_ALERT PRIMARY KEY (CSRIMP_SESSION_ID, AUDIT_REQUEST_ID, USER_SID),
	CONSTRAINT FK_CHAIN_AUDIT_REQUES_ALERT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BUSINESS_UNIT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BUSINESS_UNIT_ID NUMBER(10,0) NOT NULL,
	ACTIVE NUMBER(1,0) NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL,
	PARENT_BUSINESS_UNIT_ID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_BUSINESS_UNIT PRIMARY KEY (CSRIMP_SESSION_ID, BUSINESS_UNIT_ID),
	CONSTRAINT FK_CHAIN_BUSINESS_UNIT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BUSINE_UNIT_MEMBER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BUSINESS_UNIT_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	IS_PRIMARY_BU NUMBER(1,0),
	CONSTRAINT PK_CHAIN_BUSINE_UNIT_MEMBER PRIMARY KEY (CSRIMP_SESSION_ID, BUSINESS_UNIT_ID, USER_SID),
	CONSTRAINT FK_CHAIN_BUSINE_UNIT_MEMBER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_BUSINE_UNIT_SUPPLI (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	BUSINESS_UNIT_ID NUMBER(10,0) NOT NULL,
	SUPPLIER_COMPANY_SID NUMBER(10,0) NOT NULL,
	IS_PRIMARY_BU NUMBER(1,0),
	CONSTRAINT PK_CHAIN_BUSINE_UNIT_SUPPLI PRIMARY KEY (CSRIMP_SESSION_ID, BUSINESS_UNIT_ID, SUPPLIER_COMPANY_SID),
	CONSTRAINT FK_CHAIN_BUSINE_UNIT_SUPPLI_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_CH_USE_EMA_ADD_LOG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	EMAIL VARCHAR2(256) NOT NULL,
	LAST_MODIFIED_DTM DATE NOT NULL,
	MODIFIED_BY_SID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT FK_CHAIN_CH_USE_EMA_ADD_LOG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPANY_CC_EMAIL (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	LOWER_EMAIL VARCHAR2(255) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPANY_CC_EMAIL PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_SID, LOWER_EMAIL),
	CONSTRAINT FK_CHAIN_COMPANY_CC_EMAIL_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPANY_HEADER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_HEADER_ID NUMBER(10,0) NOT NULL,
	PAGE_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	PLUGIN_ID NUMBER(10,0) NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	POS NUMBER(10,0) NOT NULL,
	USER_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPANY_HEADER PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_HEADER_ID),
	CONSTRAINT FK_CHAIN_COMPANY_HEADER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPAN_METRIC_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_METRIC_TYPE_ID NUMBER(10,0) NOT NULL,
	CLASS VARCHAR2(64) NOT NULL,
	DESCRIPTION VARCHAR2(200) NOT NULL,
	MAX_VALUE NUMBER(10,3) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPAN_METRIC_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_METRIC_TYPE_ID),
	CONSTRAINT FK_CHAIN_COMPAN_METRIC_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPANY_METRIC (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_METRIC_TYPE_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	METRIC_VALUE NUMBER(10,3),
	NORMALISED_VALUE NUMBER(10,3),
	CONSTRAINT PK_CHAIN_COMPANY_METRIC PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_METRIC_TYPE_ID, COMPANY_SID),
	CONSTRAINT FK_CHAIN_COMPANY_METRIC_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPANY_REFERENCE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	LOOKUP_KEY VARCHAR2(255) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	VALUE VARCHAR2(200),
	CONSTRAINT PK_CHAIN_COMPANY_REFERENCE PRIMARY KEY (CSRIMP_SESSION_ID, LOOKUP_KEY, COMPANY_SID),
	CONSTRAINT FK_CHAIN_COMPANY_REFERENCE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPANY_TAB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_TAB_ID NUMBER(10,0) NOT NULL,
	LABEL VARCHAR2(254) NOT NULL,
	PAGE_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	PLUGIN_ID NUMBER(10,0) NOT NULL,
	PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
	POS NUMBER(10,0) NOT NULL,
	USER_COMPANY_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPANY_TAB PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_TAB_ID),
	CONSTRAINT FK_CHAIN_COMPANY_TAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPANY_TAG_GROUP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	TAG_GROUP_ID NUMBER(10,0) NOT NULL,
	APPLIES_TO_COMPONENT NUMBER(1,0) NOT NULL,
	APPLIES_TO_PURCHASE NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPANY_TAG_GROUP PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_SID, TAG_GROUP_ID),
	CONSTRAINT FK_CHAIN_COMPANY_TAG_GROUP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPONENT_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPONENT_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPONENT_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, COMPONENT_TYPE_ID),
	CONSTRAINT FK_CHAIN_COMPONENT_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPON_TYPE_CONTAI (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	CONTAINER_COMPONENT_TYPE_ID NUMBER(10,0) NOT NULL,
	CHILD_COMPONENT_TYPE_ID NUMBER(10,0) NOT NULL,
	ALLOW_ADD_EXISTING NUMBER(1,0) NOT NULL,
	ALLOW_ADD_NEW NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPON_TYPE_CONTAI PRIMARY KEY (CSRIMP_SESSION_ID, CONTAINER_COMPONENT_TYPE_ID, CHILD_COMPONENT_TYPE_ID),
	CONSTRAINT FK_CHAIN_COMPON_TYPE_CONTAI_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPONENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	AMOUNT_CHILD_PER_PARENT NUMBER(10,3),
	AMOUNT_UNIT_ID NUMBER(10,0),
	COMPANY_SID NUMBER(10,0) NOT NULL,
	COMPONENT_CODE VARCHAR2(4000),
	COMPONENT_NOTES VARCHAR2(4000),
	COMPONENT_TYPE_ID NUMBER(10,0) NOT NULL,
	CREATED_BY_SID NUMBER(10,0) NOT NULL,
	CREATED_DTM DATE NOT NULL,
	DELETED NUMBER(1,0) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
	PARENT_COMPONENT_ID NUMBER(10,0),
	PARENT_COMPONENT_TYPE_ID NUMBER(10,0),
	POSITION NUMBER(10,0),
	CONSTRAINT PK_CHAIN_COMPONENT PRIMARY KEY (CSRIMP_SESSION_ID, COMPONENT_ID),
	CONSTRAINT FK_CHAIN_COMPONENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILE_UPLOAD (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILE_UPLOAD_SID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	DATA BLOB NOT NULL,
	DOWNLOAD_PERMISSION_ID NUMBER(10,0) NOT NULL,
	FILENAME VARCHAR2(255) NOT NULL,
	LANG VARCHAR2(10),
	LAST_MODIFIED_BY_SID NUMBER(10,0),
	LAST_MODIFIED_DTM TIMESTAMP(6) NOT NULL,
	MIME_TYPE VARCHAR2(255) NOT NULL,
	SHA1 RAW(20) NOT NULL,
	CONSTRAINT PK_CHAIN_FILE_UPLOAD PRIMARY KEY (CSRIMP_SESSION_ID, FILE_UPLOAD_SID),
	CONSTRAINT FK_CHAIN_FILE_UPLOAD_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPONENT_DOCUMENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	FILE_UPLOAD_SID NUMBER(10,0) NOT NULL,
	KEY VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPONENT_DOCUMENT PRIMARY KEY (CSRIMP_SESSION_ID, COMPONENT_ID, FILE_UPLOAD_SID),
	CONSTRAINT FK_CHAIN_COMPONENT_DOCUMENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPONENT_SOURCE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	CARD_GROUP_ID NUMBER(10,0),
	CARD_TEXT VARCHAR2(2000) NOT NULL,
	COMPONENT_TYPE_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION_XML VARCHAR2(4000),
	POSITION NUMBER(10,0) NOT NULL,
	PROGRESSION_ACTION VARCHAR2(100) NOT NULL,
	CONSTRAINT FK_CHAIN_COMPONENT_SOURCE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPONENT_TAG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TAG_ID NUMBER(10,0) NOT NULL,
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPONENT_TAG PRIMARY KEY (CSRIMP_SESSION_ID, TAG_ID, COMPONENT_ID),
	CONSTRAINT FK_CHAIN_COMPONENT_TAG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_COMPOUND_FILTER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPOUND_FILTER_ID NUMBER(10,0) NOT NULL,
	ACT_ID CHAR(36),
	CARD_GROUP_ID NUMBER(10,0) NOT NULL,
	CREATED_BY_USER_SID NUMBER(10,0) NOT NULL,
	CREATED_DTM DATE NOT NULL,
	OPERATOR_TYPE VARCHAR2(8) NOT NULL,
	CONSTRAINT PK_CHAIN_COMPOUND_FILTER PRIMARY KEY (CSRIMP_SESSION_ID, COMPOUND_FILTER_ID),
	CONSTRAINT FK_CHAIN_COMPOUND_FILTER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_CUS_ALER_ENTR_TEMP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_ENTRY_TYPE_ID NUMBER(10,0) NOT NULL,
	TEMPLATE_NAME VARCHAR2(100) NOT NULL,
	TEMPLATE VARCHAR2(1000) NOT NULL,
	CONSTRAINT PK_CHAIN_CUS_ALER_ENTR_TEMP PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_ENTRY_TYPE_ID, TEMPLATE_NAME),
	CONSTRAINT FK_CHAIN_CUS_ALER_ENTR_TEMP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_CUS_ALER_ENTR_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_ENTRY_TYPE_ID NUMBER(10,0) NOT NULL,
	COMPANY_SECTION_TEMPLATE VARCHAR2(1000),
	ENABLED NUMBER(1,0),
	FORCE_DISABLE NUMBER(1,0),
	GENERATOR_SP VARCHAR2(255),
	IMPORTANT_SECTION_TEMPLATE VARCHAR2(1000),
	SCHEDULE_XML CLOB,
	USER_SECTION_TEMPLATE VARCHAR2(1000),
	CONSTRAINT PK_CHAIN_CUS_ALER_ENTR_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_ENTRY_TYPE_ID),
	CONSTRAINT FK_CHAIN_CUS_ALER_ENTR_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_DEF_PROD_CODE_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	CODE_LABEL1 VARCHAR2(100) NOT NULL,
	CODE_LABEL2 VARCHAR2(100),
	CODE_LABEL3 VARCHAR2(100),
	CONSTRAINT FK_CHAIN_DEF_PROD_CODE_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_DE_SUP_REL_COD_LAB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	LABEL VARCHAR2(100) NOT NULL,
	MANDATORY NUMBER(1,0) NOT NULL,
	CONSTRAINT FK_CHAIN_DE_SUP_REL_COD_LAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_EMAIL_STUB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	LOWER_STUB VARCHAR2(100) NOT NULL,
	STUB VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_CHAIN_EMAIL_STUB PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_SID, LOWER_STUB),
	CONSTRAINT FK_CHAIN_EMAIL_STUB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILE_GROUP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILE_GROUP_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0),
	DEFAULT_FILE_GROUP_FILE_ID NUMBER(10,0),
	DESCRIPTION VARCHAR2(4000),
	DOWNLOAD_PERMISSION_ID NUMBER(10,0) NOT NULL,
	FILE_GROUP_MODEL_ID NUMBER(10,0) NOT NULL,
	GUID VARCHAR2(38) NOT NULL,
	TITLE VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_CHAIN_FILE_GROUP PRIMARY KEY (CSRIMP_SESSION_ID, FILE_GROUP_ID),
	CONSTRAINT FK_CHAIN_FILE_GROUP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILE_GROUP_FILE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILE_GROUP_FILE_ID NUMBER(10,0) NOT NULL,
	FILE_GROUP_ID NUMBER(10,0) NOT NULL,
	FILE_UPLOAD_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_FILE_GROUP_FILE PRIMARY KEY (CSRIMP_SESSION_ID, FILE_GROUP_FILE_ID),
	CONSTRAINT FK_CHAIN_FILE_GROUP_FILE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILTER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILTER_ID NUMBER(10,0) NOT NULL,
	COMPOUND_FILTER_ID NUMBER(10,0) NOT NULL,
	FILTER_TYPE_ID NUMBER(10,0) NOT NULL,
	OPERATOR_TYPE VARCHAR2(8) NOT NULL,
	CONSTRAINT PK_CHAIN_FILTER PRIMARY KEY (CSRIMP_SESSION_ID, FILTER_ID),
	CONSTRAINT FK_CHAIN_FILTER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILTER_FIELD (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILTER_FIELD_ID NUMBER(10,0) NOT NULL,
	COMPARATOR VARCHAR2(64),
	FILTER_ID NUMBER(10,0) NOT NULL,
	NAME VARCHAR2(255),
	CONSTRAINT PK_CHAIN_FILTER_FIELD PRIMARY KEY (CSRIMP_SESSION_ID, FILTER_FIELD_ID),
	CONSTRAINT FK_CHAIN_FILTER_FIELD_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILTER_VALUE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILTER_VALUE_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION VARCHAR2(255),
	END_DTM_VALUE DATE,
	FILTER_FIELD_ID NUMBER(10,0) NOT NULL,
	MAX_NUM_VAL NUMBER(10,0),
	MIN_NUM_VAL NUMBER(10,0),
	NUM_VALUE NUMBER(10,0),
	REGION_SID NUMBER(10,0),
	START_DTM_VALUE DATE,
	STR_VALUE VARCHAR2(255),
	USER_SID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_FILTER_VALUE PRIMARY KEY (CSRIMP_SESSION_ID, FILTER_VALUE_ID),
	CONSTRAINT FK_CHAIN_FILTER_VALUE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILTERSUPPLIERREPO (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	LABEL NVARCHAR2(500) NOT NULL,
	REPORT_URL NVARCHAR2(2000) NOT NULL,
	CONSTRAINT FK_CHAIN_FILTERSUPPLIERREPO_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FLOW_FILTER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FLOW_SID NUMBER(10,0) NOT NULL,
	SAVED_FILTER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_FLOW_FILTER PRIMARY KEY (CSRIMP_SESSION_ID, FLOW_SID, SAVED_FILTER_SID),
	CONSTRAINT FK_CHAIN_FLOW_FILTER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_INVITATION (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	INVITATION_ID NUMBER(10,0) NOT NULL,
	ACCEPTED_DTM TIMESTAMP(6),
	ACCEPTED_REG_TERMS_VERS NUMBER(10,5),
	BATCH_JOB_ID NUMBER(10,0),
	CANCELLED_BY_USER_SID NUMBER(10,0),
	CANCELLED_DTM TIMESTAMP(6),
	EXPIRATION_DTM TIMESTAMP(6) NOT NULL,
	EXPIRATION_GRACE NUMBER(1,0) NOT NULL,
	FROM_COMPANY_SID NUMBER(10,0),
	FROM_USER_SID NUMBER(10,0),
	GUID VARCHAR2(38) NOT NULL,
	INVITATION_STATUS_ID NUMBER(10,0) NOT NULL,
	INVITATION_TYPE_ID NUMBER(10,0) NOT NULL,
	LANG VARCHAR2(10),
	ON_BEHALF_OF_COMPANY_SID NUMBER(10,0),
	REINVITATION_OF_INVITATION_ID NUMBER(10,0),
	SENT_DTM TIMESTAMP(6),
	TO_COMPANY_SID NUMBER(10,0) NOT NULL,
	TO_USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_INVITATION PRIMARY KEY (CSRIMP_SESSION_ID, INVITATION_ID),
	CONSTRAINT FK_CHAIN_INVITATION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_INVITATIO_USER_TPL (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	LANG VARCHAR2(10) NOT NULL,
	FOOTER VARCHAR2(4000),
	HEADER VARCHAR2(4000),
	CONSTRAINT PK_CHAIN_INVITATIO_USER_TPL PRIMARY KEY (CSRIMP_SESSION_ID, USER_SID, LANG),
	CONSTRAINT FK_CHAIN_INVITATIO_USER_TPL_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_MESSAGE_DEFINITION (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_DEFINITION_ID NUMBER(10,0) NOT NULL,
	COMPLETED_TEMPLATE VARCHAR2(255),
	COMPLETION_TYPE_ID NUMBER(10,0),
	CSS_CLASS VARCHAR2(255),
	HELPER_PKG VARCHAR2(100),
	MESSAGE_PRIORITY_ID NUMBER(10,0),
	MESSAGE_TEMPLATE VARCHAR2(4000),
	CONSTRAINT PK_CHAIN_MESSAGE_DEFINITION PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_DEFINITION_ID),
	CONSTRAINT FK_CHAIN_MESSAGE_DEFINITION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_MESSAGE_PARAM (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_DEFINITION_ID NUMBER(10,0) NOT NULL,
	PARAM_NAME VARCHAR2(255) NOT NULL,
	CSS_CLASS VARCHAR2(255),
	HREF VARCHAR2(1000),
	VALUE VARCHAR2(1000),
	CONSTRAINT PK_CHAIN_MESSAGE_PARAM PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_DEFINITION_ID, PARAM_NAME),
	CONSTRAINT FK_CHAIN_MESSAGE_PARAM_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTIONNAIR_GROUP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	GROUP_NAME VARCHAR2(30) NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTIONNAIR_GROUP PRIMARY KEY (CSRIMP_SESSION_ID, GROUP_NAME),
	CONSTRAINT FK_CHAIN_QUESTIONNAIR_GROUP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTIONNAIRE_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	ACTIVE NUMBER(1,0) NOT NULL,
	AUTO_RESEND_ON_EXPIRY NUMBER(10,0) NOT NULL,
	CAN_BE_OVERDUE NUMBER(1,0) NOT NULL,
	CLASS VARCHAR2(255) NOT NULL,
	DB_CLASS VARCHAR2(200),
	DEFAULT_OVERDUE_DAYS NUMBER(10,0),
	EDIT_URL VARCHAR2(4000),
	ENABLE_OVERDUE_ALERT NUMBER(1,0) NOT NULL,
	ENABLE_REMINDER_ALERT NUMBER(1,0) NOT NULL,
	EXPIRE_AFTER_MONTHS NUMBER(10,0),
	GROUP_NAME VARCHAR2(30),
	IS_RESENDABLE NUMBER(1,0) NOT NULL,
	NAME VARCHAR2(255) NOT NULL,
	OWNER_CAN_REVIEW NUMBER(1,0) NOT NULL,
	POSITION NUMBER(10,0),
	PROCURER_CAN_REVIEW NUMBER(1,0),
	REMINDER_OFFSET_DAYS NUMBER(10,0),
	REQUIRES_REVIEW NUMBER(1,0) NOT NULL,
	SECURITY_SCHEME_ID NUMBER(10,0),
	VIEW_URL VARCHAR2(4000),
	CONSTRAINT PK_CHAIN_QUESTIONNAIRE_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_TYPE_ID),
	CONSTRAINT FK_CHAIN_QUESTIONNAIRE_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FLOW_QUESTION_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FLOW_SID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_FLOW_QUESTION_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, FLOW_SID),
	CONSTRAINT FK_CHAIN_FLOW_QUESTION_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_INVI_QNR_TYPE_COMP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	INVITATION_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_INVI_QNR_TYPE_COMP PRIMARY KEY (CSRIMP_SESSION_ID, INVITATION_ID, QUESTIONNAIRE_TYPE_ID, COMPONENT_ID),
	CONSTRAINT FK_CHAIN_INVI_QNR_TYPE_COMP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_MESSAGE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_ID NUMBER(10,0) NOT NULL,
	ACTION_ID NUMBER(10,0),
	COMPLETED_BY_USER_SID NUMBER(10,0),
	COMPLETED_DTM TIMESTAMP(6),
	DUE_DTM TIMESTAMP(6),
	EVENT_ID NUMBER(10,0),
	MESSAGE_DEFINITION_ID NUMBER(10,0) NOT NULL,
	RE_AUDIT_REQUEST_ID NUMBER(10,0),
	RE_COMPANY_SID NUMBER(10,0),
	RE_COMPONENT_ID NUMBER(10,0),
	RE_INVITATION_ID NUMBER(10,0),
	RE_QUESTIONNAIRE_TYPE_ID NUMBER(10,0),
	RE_SECONDARY_COMPANY_SID NUMBER(10,0),
	RE_USER_SID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_MESSAGE PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_ID),
	CONSTRAINT FK_CHAIN_MESSAGE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_ALERT_ENTRY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_ENTRY_ID NUMBER(10,0) NOT NULL,
	ALERT_ENTRY_TYPE_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0),
	MESSAGE_ID NUMBER(10,0),
	OCCURRED_DTM TIMESTAMP(6) NOT NULL,
	OWNER_SCHEDULED_ALERT_ID NUMBER(10,0),
	PRIORITY NUMBER(10,0),
	TEMPLATE_NAME VARCHAR2(100) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_ALERT_ENTRY PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_ENTRY_ID),
	CONSTRAINT FK_CHAIN_ALERT_ENTRY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_ALERT_ENTRY_PARAM (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_ENTRY_ID NUMBER(10,0) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	VALUE VARCHAR2(1000) NOT NULL,
	CONSTRAINT PK_CHAIN_ALERT_ENTRY_PARAM PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_ENTRY_ID, NAME),
	CONSTRAINT FK_CHAIN_ALERT_ENTRY_PARAM_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_INVITATIO_QNR_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	INVITATION_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	ADDED_BY_USER_SID NUMBER(10,0) NOT NULL,
	REQUESTED_DUE_DTM DATE,
	CONSTRAINT PK_CHAIN_INVITATIO_QNR_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, INVITATION_ID, QUESTIONNAIRE_TYPE_ID),
	CONSTRAINT FK_CHAIN_INVITATIO_QNR_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_MESSAGE_RECIPIENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_ID NUMBER(10,0) NOT NULL,
	RECIPIENT_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_MESSAGE_RECIPIENT PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_ID, RECIPIENT_ID),
	CONSTRAINT FK_CHAIN_MESSAGE_RECIPIENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_MESSAG_REFRESH_LOG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_ID NUMBER(10,0) NOT NULL,
	REFRESH_INDEX NUMBER(10,0) NOT NULL,
	REFRESH_DTM TIMESTAMP(6) NOT NULL,
	REFRESH_USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_MESSAG_REFRESH_LOG PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_ID, REFRESH_INDEX),
	CONSTRAINT FK_CHAIN_MESSAG_REFRESH_LOG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_NEWSFLASH (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	NEWSFLASH_ID NUMBER(10,0) NOT NULL,
	CONTENT CLOB,
	CREATED_DTM DATE NOT NULL,
	EXPIRED_DTM DATE,
	RELEASED_DTM DATE,
	CONSTRAINT PK_CHAIN_NEWSFLASH PRIMARY KEY (CSRIMP_SESSION_ID, NEWSFLASH_ID),
	CONSTRAINT FK_CHAIN_NEWSFLASH_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_NEWSFLASH_COMPANY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	NEWSFLASH_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	FOR_SUPPLIERS NUMBER(1,0) NOT NULL,
	FOR_USERS NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_NEWSFLASH_COMPANY PRIMARY KEY (CSRIMP_SESSION_ID, NEWSFLASH_ID),
	CONSTRAINT FK_CHAIN_NEWSFLASH_COMPANY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_NEWSFL_USER_SETTIN (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	NEWSFLASH_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	HIDDEN NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_NEWSFL_USER_SETTIN PRIMARY KEY (CSRIMP_SESSION_ID, NEWSFLASH_ID, USER_SID),
	CONSTRAINT FK_CHAIN_NEWSFL_USER_SETTIN_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUCT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PRODUCT PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_ID),
	CONSTRAINT FK_CHAIN_PRODUCT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUCT_CODE_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	CODE2_MANDATORY NUMBER(1,0) NOT NULL,
	CODE3_MANDATORY NUMBER(1,0) NOT NULL,
	CODE_LABEL1 VARCHAR2(100) NOT NULL,
	CODE_LABEL2 VARCHAR2(100),
	CODE_LABEL3 VARCHAR2(100),
	MAPPING_APPROVAL_REQUIRED NUMBER(1,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PRODUCT_CODE_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_SID),
	CONSTRAINT FK_CHAIN_PRODUCT_CODE_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUC_METRIC_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_METRIC_TYPE_ID NUMBER(10,0) NOT NULL,
	CLASS VARCHAR2(64),
	DESCRIPTION VARCHAR2(200) NOT NULL,
	MAX_SCORE NUMBER(10,3),
	CONSTRAINT PK_CHAIN_PRODUC_METRIC_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_METRIC_TYPE_ID),
	CONSTRAINT FK_CHAIN_PRODUC_METRIC_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PRODUCT_REVISION (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	REVISION_NUM NUMBER(10,0) NOT NULL,
	ACTIVE NUMBER(1,0) NOT NULL,
	CODE2 VARCHAR2(100),
	CODE3 VARCHAR2(100),
	LAST_PUBLISHED_BY_USER_SID NUMBER(10,0),
	LAST_PUBLISHED_DTM TIMESTAMP(0),
	NEED_REVIEW NUMBER(1,0) NOT NULL,
	NOTES VARCHAR2(255),
	PREVIOUS_END_DTM DATE,
	PREVIOUS_REV_NUMBER NUMBER(10,0),
	PSEUDO_ROOT_COMPONENT_ID NUMBER(10,0) NOT NULL,
	PUBLISHED NUMBER(1,0) NOT NULL,
	REVISION_CREATED_BY_SID NUMBER(10,0) NOT NULL,
	REVISION_END_DTM DATE,
	REVISION_START_DTM DATE NOT NULL,
	VALIDATED_ROOT_COMPONENT_ID NUMBER(10,0),
	VALIDATION_STATUS VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_CHAIN_PRODUCT_REVISION PRIMARY KEY (CSRIMP_SESSION_ID, PRODUCT_ID, REVISION_NUM),
	CONSTRAINT FK_CHAIN_PRODUCT_REVISION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);
CREATE TABLE CSRIMP.CHAIN_PURCHASE_CHANNEL (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	PURCHASE_CHANNEL_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL,
	REGION_SID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_PURCHASE_CHANNEL PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_SID, PURCHASE_CHANNEL_ID),
	CONSTRAINT FK_CHAIN_PURCHASE_CHANNEL_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PURCHASE_COMPONENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	ACCEPTANCE_STATUS_ID NUMBER(10,0),
	COMPANY_SID NUMBER(10,0) NOT NULL,
	COMPONENT_SUPPLIER_TYPE_ID NUMBER(10,0),
	COMPONENT_TYPE_ID NUMBER(10,0) NOT NULL,
	MAPPED_BY_USER_SID NUMBER(10,0),
	MAPPED_DTM DATE,
	PREVIOUS_PURCH_COMPONENT_ID NUMBER(10,0),
	PURCHASES_LOCKED NUMBER(1,0) NOT NULL,
	SUPPLIER_COMPANY_SID NUMBER(10,0),
	SUPPLIER_PRODUCT_ID NUMBER(10,0),
	UNINVITED_SUPPLIER_SID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_PURCHASE_COMPONENT PRIMARY KEY (CSRIMP_SESSION_ID, COMPONENT_ID),
	CONSTRAINT FK_CHAIN_PURCHASE_COMPONENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PURCHASE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PURCHASE_ID NUMBER(10,0) NOT NULL,
	AMOUNT NUMBER(10,3) NOT NULL,
	AMOUNT_UNIT_ID NUMBER(10,0) NOT NULL,
	END_DATE DATE,
	INVOICE_NUMBER VARCHAR2(50),
	NOTE VARCHAR2(255),
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	PURCHASER_COMPANY_SID NUMBER(10,0) NOT NULL,
	PURCHASE_CHANNEL_ID NUMBER(10,0),
	PURCHASE_ORDER VARCHAR2(50),
	START_DATE DATE NOT NULL,
	CONSTRAINT PK_CHAIN_PURCHASE PRIMARY KEY (CSRIMP_SESSION_ID, PURCHASE_ID),
	CONSTRAINT FK_CHAIN_PURCHASE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PURCHASE_TAG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TAG_ID NUMBER(10,0) NOT NULL,
	PURCHASE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PURCHASE_TAG PRIMARY KEY (CSRIMP_SESSION_ID, TAG_ID, PURCHASE_ID),
	CONSTRAINT FK_CHAIN_PURCHASE_TAG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_PURCHASER_FOLLOWER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PURCHASER_COMPANY_SID NUMBER(10,0) NOT NULL,
	SUPPLIER_COMPANY_SID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_PURCHASER_FOLLOWER PRIMARY KEY (CSRIMP_SESSION_ID, PURCHASER_COMPANY_SID, SUPPLIER_COMPANY_SID, USER_SID),
	CONSTRAINT FK_CHAIN_PURCHASER_FOLLOWER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QNNA_SHAR_ALER_LOG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_SHARE_ID NUMBER(10,0) NOT NULL,
	ALERT_SENT_DTM DATE NOT NULL,
	STD_ALERT_TYPE_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QNNA_SHAR_ALER_LOG PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_SHARE_ID, ALERT_SENT_DTM, STD_ALERT_TYPE_ID, USER_SID),
	CONSTRAINT FK_CHAIN_QNNA_SHAR_ALER_LOG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QNR_ACTI_SECU_MASK (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	COMPANY_FUNCTION_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_ACTION_ID NUMBER(10,0) NOT NULL,
	ACTION_SECURITY_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QNR_ACTI_SECU_MASK PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_TYPE_ID, COMPANY_FUNCTION_ID, QUESTIONNAIRE_ACTION_ID),
	CONSTRAINT FK_CHAIN_QNR_ACTI_SECU_MASK_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTIONNAIRE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	COMPONENT_ID NUMBER(10,0),
	CREATED_DTM DATE,
	DESCRIPTION VARCHAR2(255),
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTIONNAIRE PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_ID),
	CONSTRAINT FK_CHAIN_QUESTIONNAIRE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QNR_SHAR_LOG_ENTRY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_SHARE_ID NUMBER(10,0) NOT NULL,
	SHARE_LOG_ENTRY_INDEX NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	ENTRY_DTM TIMESTAMP(6) NOT NULL,
	SHARE_STATUS_ID NUMBER(10,0) NOT NULL,
	USER_NOTES VARCHAR2(4000),
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QNR_SHAR_LOG_ENTRY PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_SHARE_ID, SHARE_LOG_ENTRY_INDEX),
	CONSTRAINT FK_CHAIN_QNR_SHAR_LOG_ENTRY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QNR_STAT_LOG_ENTRY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	STATUS_LOG_ENTRY_INDEX NUMBER(10,0) NOT NULL,
	ENTRY_DTM TIMESTAMP(6) NOT NULL,
	QUESTIONNAIRE_STATUS_ID NUMBER(10,0) NOT NULL,
	USER_NOTES VARCHAR2(4000),
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QNR_STAT_LOG_ENTRY PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_ID, STATUS_LOG_ENTRY_INDEX),
	CONSTRAINT FK_CHAIN_QNR_STAT_LOG_ENTRY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUEST_EXPIRY_ALERT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_SHARE_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QUEST_EXPIRY_ALERT PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_SHARE_ID, USER_SID),
	CONSTRAINT FK_CHAIN_QUEST_EXPIRY_ALERT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTION_INVITATIO (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	INVITATION_ID NUMBER(10,0) NOT NULL,
	ADDED_DTM TIMESTAMP(6) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTION_INVITATIO PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_ID, INVITATION_ID),
	CONSTRAINT FK_CHAIN_QUESTION_INVITATIO_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTI_METRIC_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_METRIC_TYPE_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
	MAX_VALUE NUMBER(10,0),
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTI_METRIC_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_METRIC_TYPE_ID),
	CONSTRAINT FK_CHAIN_QUESTI_METRIC_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTIONNAI_METRIC (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_METRIC_TYPE_ID NUMBER(10,0) NOT NULL,
	METRIC_VALUE NUMBER(10,0) NOT NULL,
	NORMALISED_VALUE NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTIONNAI_METRIC PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_ID, QUESTIONNAIRE_METRIC_TYPE_ID),
	CONSTRAINT FK_CHAIN_QUESTIONNAI_METRIC_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTIONNAIR_SHARE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_SHARE_ID NUMBER(10,0) NOT NULL,
	DUE_BY_DTM DATE NOT NULL,
	EXPIRY_DTM DATE,
	EXPIRY_SENT_DTM DATE,
	OVERDUE_EVENTS_SENT NUMBER(1,0) NOT NULL,
	OVERDUE_SENT_DTM DATE,
	QNR_OWNER_COMPANY_SID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	REMINDER_SENT_DTM DATE,
	SHARE_WITH_COMPANY_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTIONNAIR_SHARE PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_SHARE_ID),
	CONSTRAINT FK_CHAIN_QUESTIONNAIR_SHARE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTIONNAIRE_USER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	COMPANY_FUNCTION_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	ADDED_DTM TIMESTAMP(6) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTIONNAIRE_USER PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_ID, USER_SID, COMPANY_FUNCTION_ID, COMPANY_SID),
	CONSTRAINT FK_CHAIN_QUESTIONNAIRE_USER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_QUESTI_USER_ACTION (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	COMPANY_FUNCTION_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_ACTION_ID NUMBER(10,0) NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_QUESTI_USER_ACTION PRIMARY KEY (CSRIMP_SESSION_ID, QUESTIONNAIRE_ID, USER_SID, COMPANY_FUNCTION_ID, QUESTIONNAIRE_ACTION_ID, COMPANY_SID),
	CONSTRAINT FK_CHAIN_QUESTI_USER_ACTION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_RECIPIENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	RECIPIENT_ID NUMBER(10,0) NOT NULL,
	TO_COMPANY_SID NUMBER(10,0),
	TO_USER_SID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_RECIPIENT PRIMARY KEY (CSRIMP_SESSION_ID, RECIPIENT_ID),
	CONSTRAINT FK_CHAIN_RECIPIENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_REFERENCE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	LOOKUP_KEY VARCHAR2(255) NOT NULL,
	DEPRICATED_REFERENCE_NUMBER NUMBER(10,0),
	FOR_COMPANY_TYPE_ID NUMBER(10,0),
	LABEL VARCHAR2(255) NOT NULL,
	MANDATORY NUMBER(1,0) NOT NULL,
	PURCHASER_REF_ACCESS_LEVEL_ID NUMBER(10,0) NOT NULL,
	REFERENCE_FILTER_TYPE_ID NUMBER(10,0) NOT NULL,
	REFERENCE_LOCATION_ID NUMBER(10,0) NOT NULL,
	REFERENCE_UNIQUENESS_ID NUMBER(10,0) NOT NULL,
	SUPPLIER_REF_ACCESS_LEVEL_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_REFERENCE PRIMARY KEY (CSRIMP_SESSION_ID, LOOKUP_KEY),
	CONSTRAINT FK_CHAIN_REFERENCE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_REVIEW_ALERT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REVIEW_ALERT_ID NUMBER(10,0) NOT NULL,
	FROM_COMPANY_SID NUMBER(10,0) NOT NULL,
	FROM_USER_SID NUMBER(10,0) NOT NULL,
	SENT_DTM TIMESTAMP(6),
	TO_COMPANY_SID NUMBER(10,0) NOT NULL,
	TO_USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_REVIEW_ALERT PRIMARY KEY (CSRIMP_SESSION_ID, REVIEW_ALERT_ID),
	CONSTRAINT FK_CHAIN_REVIEW_ALERT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_SAVED_FILTER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	SAVED_FILTER_SID NUMBER(10,0) NOT NULL,
	CARD_GROUP_ID NUMBER(10,0) NOT NULL,
	COMPOUND_FILTER_ID NUMBER(10,0) NOT NULL,
	NAME VARCHAR2(255) NOT NULL,
	PARENT_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_SAVED_FILTER PRIMARY KEY (CSRIMP_SESSION_ID, SAVED_FILTER_SID),
	CONSTRAINT FK_CHAIN_SAVED_FILTER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_SCHEDULED_ALERT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	SCHEDULED_ALERT_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	ALERT_ENTRY_TYPE_ID NUMBER(10,0) NOT NULL,
	SENT_DTM TIMESTAMP(6),
	CONSTRAINT PK_CHAIN_SCHEDULED_ALERT PRIMARY KEY (CSRIMP_SESSION_ID, SCHEDULED_ALERT_ID, USER_SID, ALERT_ENTRY_TYPE_ID),
	CONSTRAINT FK_CHAIN_SCHEDULED_ALERT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_SUPPLIER_AUDIT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	AUDIT_SID NUMBER(10,0) NOT NULL,
	AUDITOR_COMPANY_SID NUMBER(10,0) NOT NULL,
	CREATED_BY_COMPANY_SID NUMBER(10,0) NOT NULL,
	SUPPLIER_COMPANY_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_SUPPLIER_AUDIT PRIMARY KEY (CSRIMP_SESSION_ID, AUDIT_SID),
	CONSTRAINT FK_CHAIN_SUPPLIER_AUDIT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_ID NUMBER(10,0) NOT NULL,
	CHANGE_GROUP_ID NUMBER(10,0),
	DUE_DATE DATE,
	LAST_TASK_STATUS_ID NUMBER(10,0),
	LAST_UPDATED_BY_SID NUMBER(10,0),
	LAST_UPDATED_DTM DATE,
	NEXT_REVIEW_DATE DATE,
	OWNER_COMPANY_SID NUMBER(10,0) NOT NULL,
	SKIPPED NUMBER(1,0) NOT NULL,
	SUPPLIER_COMPANY_SID NUMBER(10,0) NOT NULL,
	TASK_STATUS_ID NUMBER(10,0) NOT NULL,
	TASK_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_TASK PRIMARY KEY (CSRIMP_SESSION_ID, TASK_ID),
	CONSTRAINT FK_CHAIN_TASK_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_ACTION_TRIGGE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ON_TASK_ACTION_ID NUMBER(10,0) NOT NULL,
	POSITION NUMBER(10,0) NOT NULL,
	TASK_TYPE_ID NUMBER(10,0) NOT NULL,
	TRIGGER_TASK_ACTION_ID NUMBER(10,0) NOT NULL,
	TRIGGER_TASK_NAME VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_CHAIN_TASK_ACTION_TRIGGE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_ENTRY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_ENTRY_ID NUMBER(10,0) NOT NULL,
	LAST_MODIFIED_BY_SID NUMBER(10,0) NOT NULL,
	LAST_MODIFIED_DTM TIMESTAMP(6) NOT NULL,
	NAME VARCHAR2(30),
	TASK_ENTRY_TYPE_ID NUMBER(10,0) NOT NULL,
	TASK_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_TASK_ENTRY PRIMARY KEY (CSRIMP_SESSION_ID, TASK_ENTRY_ID),
	CONSTRAINT FK_CHAIN_TASK_ENTRY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_ENTRY_DATE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_ENTRY_ID NUMBER(10,0) NOT NULL,
	DTM TIMESTAMP(6),
	CONSTRAINT PK_CHAIN_TASK_ENTRY_DATE PRIMARY KEY (CSRIMP_SESSION_ID, TASK_ENTRY_ID),
	CONSTRAINT FK_CHAIN_TASK_ENTRY_DATE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_ENTRY_FILE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_ENTRY_ID NUMBER(10,0) NOT NULL,
	FILE_UPLOAD_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_TASK_ENTRY_FILE PRIMARY KEY (CSRIMP_SESSION_ID, TASK_ENTRY_ID, FILE_UPLOAD_SID),
	CONSTRAINT FK_CHAIN_TASK_ENTRY_FILE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_ENTRY_NOTE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_ENTRY_ID NUMBER(10,0) NOT NULL,
	TEXT VARCHAR2(4000),
	CONSTRAINT PK_CHAIN_TASK_ENTRY_NOTE PRIMARY KEY (CSRIMP_SESSION_ID, TASK_ENTRY_ID),
	CONSTRAINT FK_CHAIN_TASK_ENTRY_NOTE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_SCHEME (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_SCHEME_ID NUMBER(10,0) NOT NULL,
	DB_CLASS VARCHAR2(64),
	DESCRIPTION VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_CHAIN_TASK_SCHEME PRIMARY KEY (CSRIMP_SESSION_ID, TASK_SCHEME_ID),
	CONSTRAINT FK_CHAIN_TASK_SCHEME_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_TYPE_ID NUMBER(10,0) NOT NULL,
	CARD_ID NUMBER(10,0),
	DB_CLASS VARCHAR2(64),
	DEFAULT_TASK_STATUS_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL,
	DUE_DATE_EDITABLE NUMBER(1,0) NOT NULL,
	DUE_IN_DAYS NUMBER(10,0),
	MANDATORY NUMBER(1,0) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	PARENT_TASK_TYPE_ID NUMBER(10,0),
	POSITION NUMBER(10,0) NOT NULL,
	REVIEW_EVERY_N_DAYS NUMBER(10,0),
	TASK_SCHEME_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_TASK_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, TASK_TYPE_ID),
	CONSTRAINT FK_CHAIN_TASK_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_TASK_INVI_QNR_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TASK_ID NUMBER(10,0) NOT NULL,
	INVITATION_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_TASK_INVI_QNR_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, TASK_ID),
	CONSTRAINT FK_CHAIN_TASK_INVI_QNR_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_UCD_LOGON (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	UCD_ACT_ID CHAR(36) NOT NULL,
	PREVIOUS_ACT_ID CHAR(36) NOT NULL,
	PREVIOUS_COMPANY_SID NUMBER(10,0),
	PREVIOUS_USER_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_UCD_LOGON PRIMARY KEY (CSRIMP_SESSION_ID, UCD_ACT_ID),
	CONSTRAINT FK_CHAIN_UCD_LOGON_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_UNINVITED_SUPPLIER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_SID NUMBER(10,0) NOT NULL,
	UNINVITED_SUPPLIER_SID NUMBER(10,0) NOT NULL,
	COUNTRY_CODE VARCHAR2(2) NOT NULL,
	CREATED_AS_COMPANY_SID NUMBER(10,0),
	NAME VARCHAR2(1000) NOT NULL,
	SUPP_REL_CODE VARCHAR2(100),
	CONSTRAINT PK_CHAIN_UNINVITED_SUPPLIER PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_SID, UNINVITED_SUPPLIER_SID),
	CONSTRAINT FK_CHAIN_UNINVITED_SUPPLIER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_URL_OVERRIDES (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	HOST VARCHAR2(1000) NOT NULL,
	KEY VARCHAR2(100) NOT NULL,
	SITE_NAME VARCHAR2(200),
	SUPPORT_EMAIL VARCHAR2(255),
	CONSTRAINT FK_CHAIN_URL_OVERRIDES_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_USE_ALER_ENTR_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ALERT_ENTRY_TYPE_ID NUMBER(10,0) NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	ENABLED NUMBER(1,0),
	SCHEDULE_XML CLOB,
	CONSTRAINT PK_CHAIN_USE_ALER_ENTR_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, ALERT_ENTRY_TYPE_ID, USER_SID),
	CONSTRAINT FK_CHAIN_USE_ALER_ENTR_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_USER_MESSAGE_LOG (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	USER_SID NUMBER(10,0) NOT NULL,
	MESSAGE_ID NUMBER(10,0) NOT NULL,
	VIEWED_DTM TIMESTAMP(6),
	CONSTRAINT PK_CHAIN_USER_MESSAGE_LOG PRIMARY KEY (CSRIMP_SESSION_ID, USER_SID, MESSAGE_ID),
	CONSTRAINT FK_CHAIN_USER_MESSAGE_LOG_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_VALID_PURCH_COMPON (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPONENT_ID NUMBER(10,0) NOT NULL,
	MAPPED_PURCHASED_COMPONENT_ID NUMBER(10,0),
	CONSTRAINT PK_CHAIN_VALID_PURCH_COMPON PRIMARY KEY (CSRIMP_SESSION_ID, COMPONENT_ID),
	CONSTRAINT FK_CHAIN_VALID_PURCH_COMPON_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_WORKSH_FILE_UPLOAD (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	WORKSHEET_ID NUMBER(10,0) NOT NULL,
	FILE_UPLOAD_SID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_WORKSH_FILE_UPLOAD PRIMARY KEY (CSRIMP_SESSION_ID, WORKSHEET_ID, FILE_UPLOAD_SID),
	CONSTRAINT FK_CHAIN_WORKSH_FILE_UPLOAD_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_DEFAU_MESSA_DEFINI (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_DEFINITION_ID NUMBER(10,0) NOT NULL,
	ADDRESSING_TYPE_ID NUMBER(10,0) NOT NULL,
	COMPLETED_TEMPLATE VARCHAR2(255),
	COMPLETION_TYPE_ID NUMBER(10,0) NOT NULL,
	CSS_CLASS VARCHAR2(255),
	HELPER_PKG VARCHAR2(100),
	MESSAGE_PRIORITY_ID NUMBER(10,0) NOT NULL,
	MESSAGE_TEMPLATE VARCHAR2(4000) NOT NULL,
	REPEAT_TYPE_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_DEFAU_MESSA_DEFINI PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_DEFINITION_ID),
	CONSTRAINT FK_CHAIN_DEFAU_MESSA_DEFINI_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_MESSA_DEFIN_LOOKUP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	MESSAGE_DEFINITION_ID NUMBER(10,0) NOT NULL,
	PRIMARY_LOOKUP_ID NUMBER(10,0) NOT NULL,
	SECONDARY_LOOKUP_ID NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_MESSA_DEFIN_LOOKUP PRIMARY KEY (CSRIMP_SESSION_ID, MESSAGE_DEFINITION_ID),
	CONSTRAINT FK_CHAIN_MESSA_DEFIN_LOOKUP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_FILTER_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	FILTER_TYPE_ID NUMBER(10,0) NOT NULL,
	CARD_ID NUMBER(10,0) NOT NULL,
	DESCRIPTION VARCHAR2(255),
	HELPER_PKG VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_CHAIN_FILTER_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, FILTER_TYPE_ID),
	CONSTRAINT FK_CHAIN_FILTER_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_GROUP_CAPABILITY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	GROUP_CAPABILITY_ID NUMBER(10,0) NOT NULL,
	CAPABILITY_ID NUMBER(10,0) NOT NULL,
	COMPANY_GROUP_TYPE_ID NUMBER(10,0) NOT NULL,
	PERMISSION_SET NUMBER(10,0) NOT NULL,
	CONSTRAINT PK_CHAIN_GROUP_CAPABILITY PRIMARY KEY (CSRIMP_SESSION_ID, GROUP_CAPABILITY_ID),
	CONSTRAINT FK_CHAIN_GROUP_CAPABILITY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CHAIN_CARD_PROGRE_ACTION (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	CARD_ID NUMBER(10,0) NOT NULL,
	ACTION VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_CHAIN_CARD_PROGRE_ACTION PRIMARY KEY (CSRIMP_SESSION_ID, CARD_ID, ACTION),
	CONSTRAINT FK_CHAIN_CARD_PROGRE_ACTION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);



-- creating new csrimp map tables

CREATE TABLE CSRIMP.MAP_WORKSHEET (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_WORKSHEET_ID NUMBER(10) NOT NULL,
	NEW_WORKSHEET_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_WORKSHEET PRIMARY KEY (OLD_WORKSHEET_ID) USING INDEX,
	CONSTRAINT UK_MAP_WORKSHEET UNIQUE (NEW_WORKSHEET_ID) USING INDEX,
	CONSTRAINT FK_MAP_WORKSHEET_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_VALUE_MAP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_VALUE_MAP_ID NUMBER(10) NOT NULL,
	NEW_VALUE_MAP_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_VALUE_MAP PRIMARY KEY (OLD_VALUE_MAP_ID) USING INDEX,
	CONSTRAINT UK_MAP_VALUE_MAP UNIQUE (NEW_VALUE_MAP_ID) USING INDEX,
	CONSTRAINT FK_MAP_VALUE_MAP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_ALERT_ENTRY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_ALERT_ENTRY_ID NUMBER(10) NOT NULL,
	NEW_ALERT_ENTRY_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_ALERT_ENTRY PRIMARY KEY (OLD_ALERT_ENTRY_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_ALERT_ENTRY UNIQUE (NEW_ALERT_ENTRY_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_ALERT_ENTRY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_MESSAGE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_MESSAGE_ID NUMBER(10) NOT NULL,
	NEW_MESSAGE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_MESSAGE PRIMARY KEY (OLD_MESSAGE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_MESSAGE UNIQUE (NEW_MESSAGE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_MESSAGE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_SCHEDULE_ALERT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_SCHEDULED_ALERT_ID NUMBER(10) NOT NULL,
	NEW_SCHEDULED_ALERT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_SCHEDULE_ALERT PRIMARY KEY (OLD_SCHEDULED_ALERT_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_SCHEDULE_ALERT UNIQUE (NEW_SCHEDULED_ALERT_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_SCHEDULE_ALERT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_AUDIT_REQUEST (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_AUDIT_REQUEST_ID NUMBER(10) NOT NULL,
	NEW_AUDIT_REQUEST_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_AUDIT_REQUEST PRIMARY KEY (OLD_AUDIT_REQUEST_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_AUDIT_REQUEST UNIQUE (NEW_AUDIT_REQUEST_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_AUDIT_REQUEST_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_COMPANY_HEADER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_COMPANY_HEADER_ID NUMBER(10) NOT NULL,
	NEW_COMPANY_HEADER_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_COMPANY_HEADER PRIMARY KEY (OLD_COMPANY_HEADER_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_COMPANY_HEADER UNIQUE (NEW_COMPANY_HEADER_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_COMPANY_HEADER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_COMPANY_TAB (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_COMPANY_TAB_ID NUMBER(10) NOT NULL,
	NEW_COMPANY_TAB_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_COMPANY_TAB PRIMARY KEY (OLD_COMPANY_TAB_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_COMPANY_TAB UNIQUE (NEW_COMPANY_TAB_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_COMPANY_TAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_COMPONENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_COMPONENT_ID NUMBER(10) NOT NULL,
	NEW_COMPONENT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_COMPONENT PRIMARY KEY (OLD_COMPONENT_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_COMPONENT UNIQUE (NEW_COMPONENT_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_COMPONENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_COMPOUN_FILTER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_COMPOUND_FILTER_ID NUMBER(10) NOT NULL,
	NEW_COMPOUND_FILTER_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_COMPOUN_FILTER PRIMARY KEY (OLD_COMPOUND_FILTER_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_COMPOUN_FILTER UNIQUE (NEW_COMPOUND_FILTER_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_COMPOUN_FILTER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_FILE_GROUP (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_FILE_GROUP_ID NUMBER(10) NOT NULL,
	NEW_FILE_GROUP_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_FILE_GROUP PRIMARY KEY (OLD_FILE_GROUP_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_FILE_GROUP UNIQUE (NEW_FILE_GROUP_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_FILE_GROUP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_FILE_GROU_FILE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_FILE_GROUP_FILE_ID NUMBER(10) NOT NULL,
	NEW_FILE_GROUP_FILE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_FILE_GROU_FILE PRIMARY KEY (OLD_FILE_GROUP_FILE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_FILE_GROU_FILE UNIQUE (NEW_FILE_GROUP_FILE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_FILE_GROU_FILE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_FILTER (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_FILTER_ID NUMBER(10) NOT NULL,
	NEW_FILTER_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_FILTER PRIMARY KEY (OLD_FILTER_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_FILTER UNIQUE (NEW_FILTER_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_FILTER_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_FILTER_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_FILTER_TYPE_ID NUMBER(10) NOT NULL,
	NEW_FILTER_TYPE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_FILTER_TYPE PRIMARY KEY (OLD_FILTER_TYPE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_FILTER_TYPE UNIQUE (NEW_FILTER_TYPE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_FILTER_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_FILTER_FIELD (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_FILTER_FIELD_ID NUMBER(10) NOT NULL,
	NEW_FILTER_FIELD_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_FILTER_FIELD PRIMARY KEY (OLD_FILTER_FIELD_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_FILTER_FIELD UNIQUE (NEW_FILTER_FIELD_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_FILTER_FIELD_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_FILTER_VALUE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_FILTER_VALUE_ID NUMBER(10) NOT NULL,
	NEW_FILTER_VALUE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_FILTER_VALUE PRIMARY KEY (OLD_FILTER_VALUE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_FILTER_VALUE UNIQUE (NEW_FILTER_VALUE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_FILTER_VALUE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_QUESTIONN_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_QUESTIONNAIRE_TYPE_ID NUMBER(10) NOT NULL,
	NEW_QUESTIONNAIRE_TYPE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_QUESTIONN_TYPE PRIMARY KEY (OLD_QUESTIONNAIRE_TYPE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_QUESTIONN_TYPE UNIQUE (NEW_QUESTIONNAIRE_TYPE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_QUESTIONN_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_INVITATION (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_INVITATION_ID NUMBER(10) NOT NULL,
	NEW_INVITATION_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_INVITATION PRIMARY KEY (OLD_INVITATION_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_INVITATION UNIQUE (NEW_INVITATION_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_INVITATION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_MESSAG_DEFINIT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_MESSAGE_DEFINITION_ID NUMBER(10) NOT NULL,
	NEW_MESSAGE_DEFINITION_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_MESSAG_DEFINIT PRIMARY KEY (OLD_MESSAGE_DEFINITION_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_MESSAG_DEFINIT UNIQUE (NEW_MESSAGE_DEFINITION_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_MESSAG_DEFINIT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_QUESTIONNAIRE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_QUESTIONNAIRE_ID NUMBER(10) NOT NULL,
	NEW_QUESTIONNAIRE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_QUESTIONNAIRE PRIMARY KEY (OLD_QUESTIONNAIRE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_QUESTIONNAIRE UNIQUE (NEW_QUESTIONNAIRE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_QUESTIONNAIRE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_RECIPIENT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_RECIPIENT_ID NUMBER(10) NOT NULL,
	NEW_RECIPIENT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_RECIPIENT PRIMARY KEY (OLD_RECIPIENT_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_RECIPIENT UNIQUE (NEW_RECIPIENT_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_RECIPIENT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_NEWSFLASH (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_NEWSFLASH_ID NUMBER(10) NOT NULL,
	NEW_NEWSFLASH_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_NEWSFLASH PRIMARY KEY (OLD_NEWSFLASH_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_NEWSFLASH UNIQUE (NEW_NEWSFLASH_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_NEWSFLASH_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_PRODUCT (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_PRODUCT_ID NUMBER(10) NOT NULL,
	NEW_PRODUCT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_PRODUCT PRIMARY KEY (OLD_PRODUCT_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_PRODUCT UNIQUE (NEW_PRODUCT_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_PRODUCT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_PURCHASE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_PURCHASE_ID NUMBER(10) NOT NULL,
	NEW_PURCHASE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_PURCHASE PRIMARY KEY (OLD_PURCHASE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_PURCHASE UNIQUE (NEW_PURCHASE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_PURCHASE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_QUESTION_SHARE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_QUESTIONNAIRE_SHARE_ID NUMBER(10) NOT NULL,
	NEW_QUESTIONNAIRE_SHARE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_QUESTION_SHARE PRIMARY KEY (OLD_QUESTIONNAIRE_SHARE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_QUESTION_SHARE UNIQUE (NEW_QUESTIONNAIRE_SHARE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_QUESTION_SHARE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_TASK (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_TASK_ID NUMBER(10) NOT NULL,
	NEW_TASK_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_TASK PRIMARY KEY (OLD_TASK_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_TASK UNIQUE (NEW_TASK_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_TASK_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_TASK_TYPE (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_TASK_TYPE_ID NUMBER(10) NOT NULL,
	NEW_TASK_TYPE_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_TASK_TYPE PRIMARY KEY (OLD_TASK_TYPE_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_TASK_TYPE UNIQUE (NEW_TASK_TYPE_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_TASK_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MAP_CHAIN_TASK_ENTRY (
	CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	OLD_TASK_ENTRY_ID NUMBER(10) NOT NULL,
	NEW_TASK_ENTRY_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_MAP_CHAIN_TASK_ENTRY PRIMARY KEY (OLD_TASK_ENTRY_ID) USING INDEX,
	CONSTRAINT UK_MAP_CHAIN_TASK_ENTRY UNIQUE (NEW_TASK_ENTRY_ID) USING INDEX,
	CONSTRAINT FK_MAP_CHAIN_TASK_ENTRY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- grants (from package_grants.sql)
grant select, insert, update, delete on csrimp.chain_alert_parti_templa to web_user;
grant select, insert, update, delete on csrimp.chain_ale_part_temp_para to web_user;
grant select, insert, update, delete on csrimp.chain_amount_unit to web_user;
grant select, insert, update, delete on csrimp.chain_audit_request to web_user;
grant select, insert, update, delete on csrimp.chain_audit_reques_alert to web_user;
grant select, insert, update, delete on csrimp.chain_business_unit to web_user;
grant select, insert, update, delete on csrimp.chain_busine_unit_member to web_user;
grant select, insert, update, delete on csrimp.chain_busine_unit_suppli to web_user;
grant select, insert, update, delete on csrimp.chain_ch_use_ema_add_log to web_user;
grant select, insert, update, delete on csrimp.chain_company_cc_email to web_user;
grant select, insert, update, delete on csrimp.chain_company_header to web_user;
grant select, insert, update, delete on csrimp.chain_compan_metric_type to web_user;
grant select, insert, update, delete on csrimp.chain_company_metric to web_user;
grant select, insert, update, delete on csrimp.chain_company_reference to web_user;
grant select, insert, update, delete on csrimp.chain_company_tab to web_user;
grant select, insert, update, delete on csrimp.chain_company_tag_group to web_user;
grant select, insert, update, delete on csrimp.chain_component_type to web_user;
grant select, insert, update, delete on csrimp.chain_compon_type_contai to web_user;
grant select, insert, update, delete on csrimp.chain_component to web_user;
grant select, insert, update, delete on csrimp.chain_file_upload to web_user;
grant select, insert, update, delete on csrimp.chain_component_document to web_user;
grant select, insert, update, delete on csrimp.chain_component_source to web_user;
grant select, insert, update, delete on csrimp.chain_component_tag to web_user;
grant select, insert, update, delete on csrimp.chain_compound_filter to web_user;
grant select, insert, update, delete on csrimp.chain_cus_aler_entr_temp to web_user;
grant select, insert, update, delete on csrimp.chain_cus_aler_entr_type to web_user;
grant select, insert, update, delete on csrimp.chain_def_prod_code_type to web_user;
grant select, insert, update, delete on csrimp.chain_de_sup_rel_cod_lab to web_user;
grant select, insert, update, delete on csrimp.chain_email_stub to web_user;
grant select, insert, update, delete on csrimp.chain_file_group to web_user;
grant select, insert, update, delete on csrimp.chain_file_group_file to web_user;
grant select, insert, update, delete on csrimp.chain_filter to web_user;
grant select, insert, update, delete on csrimp.chain_filter_field to web_user;
grant select, insert, update, delete on csrimp.chain_filter_value to web_user;
grant select, insert, update, delete on csrimp.chain_filtersupplierrepo to web_user;
grant select, insert, update, delete on csrimp.chain_flow_filter to web_user;
grant select, insert, update, delete on csrimp.chain_invitation to web_user;
grant select, insert, update, delete on csrimp.chain_invitatio_user_tpl to web_user;
grant select, insert, update, delete on csrimp.chain_message_definition to web_user;
grant select, insert, update, delete on csrimp.chain_message_param to web_user;
grant select, insert, update, delete on csrimp.chain_questionnair_group to web_user;
grant select, insert, update, delete on csrimp.chain_questionnaire_type to web_user;
grant select, insert, update, delete on csrimp.chain_flow_question_type to web_user;
grant select, insert, update, delete on csrimp.chain_invi_qnr_type_comp to web_user;
grant select, insert, update, delete on csrimp.chain_message to web_user;
grant select, insert, update, delete on csrimp.chain_alert_entry to web_user;
grant select, insert, update, delete on csrimp.chain_alert_entry_param to web_user;
grant select, insert, update, delete on csrimp.chain_invitatio_qnr_type to web_user;
grant select, insert, update, delete on csrimp.chain_message_recipient to web_user;
grant select, insert, update, delete on csrimp.chain_messag_refresh_log to web_user;
grant select, insert, update, delete on csrimp.chain_newsflash to web_user;
grant select, insert, update, delete on csrimp.chain_newsflash_company to web_user;
grant select, insert, update, delete on csrimp.chain_newsfl_user_settin to web_user;
grant select, insert, update, delete on csrimp.chain_product to web_user;
grant select, insert, update, delete on csrimp.chain_product_code_type to web_user;
grant select, insert, update, delete on csrimp.chain_produc_metric_type to web_user;
grant select, insert, update, delete on csrimp.chain_product_revision to web_user;
grant select, insert, update, delete on csrimp.chain_purchase_channel to web_user;
grant select, insert, update, delete on csrimp.chain_purchase_component to web_user;
grant select, insert, update, delete on csrimp.chain_purchase to web_user;
grant select, insert, update, delete on csrimp.chain_purchase_tag to web_user;
grant select, insert, update, delete on csrimp.chain_purchaser_follower to web_user;
grant select, insert, update, delete on csrimp.chain_qnna_shar_aler_log to web_user;
grant select, insert, update, delete on csrimp.chain_qnr_acti_secu_mask to web_user;
grant select, insert, update, delete on csrimp.chain_questionnaire to web_user;
grant select, insert, update, delete on csrimp.chain_qnr_shar_log_entry to web_user;
grant select, insert, update, delete on csrimp.chain_qnr_stat_log_entry to web_user;
grant select, insert, update, delete on csrimp.chain_quest_expiry_alert to web_user;
grant select, insert, update, delete on csrimp.chain_question_invitatio to web_user;
grant select, insert, update, delete on csrimp.chain_questi_metric_type to web_user;
grant select, insert, update, delete on csrimp.chain_questionnai_metric to web_user;
grant select, insert, update, delete on csrimp.chain_questionnair_share to web_user;
grant select, insert, update, delete on csrimp.chain_questionnaire_user to web_user;
grant select, insert, update, delete on csrimp.chain_questi_user_action to web_user;
grant select, insert, update, delete on csrimp.chain_recipient to web_user;
grant select, insert, update, delete on csrimp.chain_reference to web_user;
grant select, insert, update, delete on csrimp.chain_review_alert to web_user;
grant select, insert, update, delete on csrimp.chain_saved_filter to web_user;
grant select, insert, update, delete on csrimp.chain_scheduled_alert to web_user;
grant select, insert, update, delete on csrimp.chain_supplier_audit to web_user;
grant select, insert, update, delete on csrimp.chain_task to web_user;
grant select, insert, update, delete on csrimp.chain_task_action_trigge to web_user;
grant select, insert, update, delete on csrimp.chain_task_entry to web_user;
grant select, insert, update, delete on csrimp.chain_task_entry_date to web_user;
grant select, insert, update, delete on csrimp.chain_task_entry_file to web_user;
grant select, insert, update, delete on csrimp.chain_task_entry_note to web_user;
grant select, insert, update, delete on csrimp.chain_task_scheme to web_user;
grant select, insert, update, delete on csrimp.chain_task_type to web_user;
grant select, insert, update, delete on csrimp.chain_task_invi_qnr_type to web_user;
grant select, insert, update, delete on csrimp.chain_ucd_logon to web_user;
grant select, insert, update, delete on csrimp.chain_uninvited_supplier to web_user;
grant select, insert, update, delete on csrimp.chain_url_overrides to web_user;
grant select, insert, update, delete on csrimp.chain_use_aler_entr_type to web_user;
grant select, insert, update, delete on csrimp.chain_user_message_log to web_user;
grant select, insert, update, delete on csrimp.chain_valid_purch_compon to web_user;
grant select, insert, update, delete on csrimp.chain_worksh_file_upload to web_user;
grant select, insert, update, delete on csrimp.chain_defau_messa_defini to web_user;
grant select, insert, update, delete on csrimp.chain_messa_defin_lookup to web_user;
grant select, insert, update, delete on csrimp.chain_filter_type to web_user;
grant select, insert, update, delete on csrimp.chain_group_capability to web_user;
grant select, insert, update, delete on csrimp.chain_card_progre_action to web_user;

grant select, insert, update, delete on csrimp.worksheet to web_user;
grant select, insert, update, delete on csrimp.worksheet_column to web_user;
grant select, insert, update, delete on csrimp.workshe_column_value_map to web_user;
grant select, insert, update, delete on csrimp.worksheet_row to web_user;
grant select, insert, update, delete on csrimp.worksheet_value_map to web_user;
grant select, insert, update, delete on csrimp.workshee_value_map_value to web_user;


@../schema_pkg
@../schema_body
@../csrimp/imp_pkg
@../csrimp/imp_body

@update_tail