-- Please update version.sql too -- this keeps clean builds in sync
define version=2109
@update_header

  INSERT INTO CSR.STD_MEASURE_CONVERSION(STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28120, 26, 'l/kWh', 3600000000, 0, 0, 1);
  INSERT INTO CSR.STD_MEASURE_CONVERSION(STD_MEASURE_CONVERSION_ID, STD_MEASURE_ID, DESCRIPTION, A, B, C, DIVISIBLE) VALUES (28121, 17, 'kWh/kgCO2', 3600000, 0, 0, 1);

@update_tail