-- Please update version.sql too -- this keeps clean builds in sync
define version=463
@update_header
 
 
-- 
-- TABLE: CUSTOMER_MAP 
--

CREATE TABLE CUSTOMER_MAP(
    APP_SID        NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    MAP_ID         NUMBER(10, 0)     NOT NULL,
    MAP_CONTEXT    NUMBER(10, 0)     DEFAULT 0,
    EXTENT_N       NUMBER(14, 10)    DEFAULT 80,
    EXTENT_S       NUMBER(14, 10)    DEFAULT -80,
    EXTENT_W       NUMBER(14, 10)    DEFAULT -160,
    EXTENT_E       NUMBER(14, 10)    DEFAULT 160,
    CONSTRAINT PK1_2 PRIMARY KEY (APP_SID, MAP_ID)
)
;



-- TABLE: MAP_SHPFILE 
--

CREATE TABLE MAP_SHPFILE(
    APP_SID        NUMBER(10, 0)     DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    MAP_ID         NUMBER(10, 0)     NOT NULL,
    SHPFILE        VARCHAR2(1024)    NOT NULL,
    GEO_FIELD      VARCHAR2(256),
    GEO_COUNTRY    VARCHAR2(2),
    Z_ORDER        NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (APP_SID, MAP_ID, SHPFILE)
)
;


-- TABLE: CUSTOMER_MAP 
--

ALTER TABLE CUSTOMER_MAP ADD CONSTRAINT RefCUSTOMER1674 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;


-- 
-- TABLE: MAP_SHPFILE 
--

ALTER TABLE MAP_SHPFILE ADD CONSTRAINT RefCOUNTRY1675 
    FOREIGN KEY (GEO_COUNTRY)
    REFERENCES POSTCODE.COUNTRY(COUNTRY)
;

ALTER TABLE MAP_SHPFILE ADD CONSTRAINT RefCUSTOMER_MAP1676 
    FOREIGN KEY (APP_SID, MAP_ID)
    REFERENCES CUSTOMER_MAP(APP_SID, MAP_ID)
;




CREATE SEQUENCE MAP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 5
    NOORDER
;


	
ALTER TABLE ISSUE_LOG_FILE ADD (
	UPLOADED_DTM	DATE	DEFAULT SYSDATE NOT NULL
);


@..\map_pkg
@..\map_body

GRANT EXECUTE ON map_pkg TO WEB_USER;

@..\issue_pkg
@..\issue_body

@update_tail
