define version=2040
@update_header

DROP TABLE CSR.TEMP_SECTION_SEARCH_RESULT;

CREATE GLOBAL TEMPORARY TABLE CSR.TEMP_SECTION_SEARCH_RESULT (
	SEARCH_ROOT			NUMBER(1),
	SECTION_SID			NUMBER(10,0),
	DOC_ID				NUMBER(10,0),
	DOC_DATA_ID			NUMBER(10,0),
	ATTACHMENT_ID		NUMBER(10,0),
	VERSION_NUMBER		NUMBER(10,0),
	TITLE				VARCHAR2(1024),
	USE_SNIPPET			NUMBER(1),
	PATH				VARCHAR2(1024),
	CHANGED_BY_SID		NUMBER(10,0),
	CHANGED_BY_NAME		VARCHAR2(256),
	CHANGED_DTM			DATE,
	RESULT_TYPE			NUMBER(1,0),
	RESULT_SCORE		NUMBER(10,0),
	MIME_TYPE			VARCHAR2(128)
) ON COMMIT DELETE ROWS;

@../section_pkg
@../section_body

@update_tail
