-- Please update version.sql too -- this keeps clean builds in sync
define version=1117
@update_header

-- NOTE THAT THIS BLCOK HAS BEEN RUN ON LIVE AS 1116 IS BLOCKING DUE TO RELEASE FREEZE
-- COMMENT THIS OUT TO RUN ON LIVE
begin
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Admin Employee Commuting', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Admin Business Travel', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Admin Products Services', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Admin Use Phase', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Edit Employee Commuting', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Edit Business Travel', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Edit Products Services', 0);
INSERT INTO CSR.CAPABILITY (NAME, ALLOW_BY_DEFAULT) VALUES ('Edit Use Phase', 0);
end;
/

@update_tail
