-- Please update version.sql too -- this keeps clean builds in sync
define version=2972
define minor_version=13
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
ALTER TABLE CSR.DATAVIEW ADD (HIGHLIGHT_CHANGED_SINCE NUMBER(1, 0) DEFAULT 0 NOT NULL);
ALTER TABLE CSR.DATAVIEW ADD (HIGHLIGHT_CHANGED_SINCE_DTM DATE);

ALTER TABLE CSR.DATAVIEW_HISTORY ADD (HIGHLIGHT_CHANGED_SINCE NUMBER(1, 0) DEFAULT 0 NOT NULL);
ALTER TABLE CSR.DATAVIEW_HISTORY ADD (HIGHLIGHT_CHANGED_SINCE_DTM DATE);


ALTER TABLE CSRIMP.DATAVIEW ADD (HIGHLIGHT_CHANGED_SINCE NUMBER(1, 0) NOT NULL);
ALTER TABLE CSRIMP.DATAVIEW ADD (HIGHLIGHT_CHANGED_SINCE_DTM DATE);

ALTER TABLE CSRIMP.DATAVIEW_HISTORY ADD (HIGHLIGHT_CHANGED_SINCE NUMBER(1, 0) NOT NULL);
ALTER TABLE CSRIMP.DATAVIEW_HISTORY ADD (HIGHLIGHT_CHANGED_SINCE_DTM DATE);

-- *** Grants ***

-- ** Cross schema constraints ***
ALTER TABLE CSR.DATAVIEW ADD CONSTRAINT CK_DATAVIEW_HGHLGHT_CHGD_SNCE CHECK (HIGHLIGHT_CHANGED_SINCE IN (0,1));
ALTER TABLE CSR.DATAVIEW_HISTORY ADD CONSTRAINT CK_DV_HIST_HIGHLIGHT_CHGD_SNCE CHECK (HIGHLIGHT_CHANGED_SINCE IN (0,1));

ALTER TABLE CSRIMP.DATAVIEW ADD CONSTRAINT CK_DATAVIEW_HGHLGHT_CHGD_SNCE CHECK (HIGHLIGHT_CHANGED_SINCE IN (0,1));
ALTER TABLE CSRIMP.DATAVIEW_HISTORY ADD CONSTRAINT CK_DV_HIST_HIGHLIGHT_CHGD_SNCE CHECK (HIGHLIGHT_CHANGED_SINCE IN (0,1));

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../dataview_pkg
@../dataview_body
@../schema_body
@../csrimp/imp_body

@update_tail
