-- Please update version.sql too -- this keeps clean builds in sync
define version=2031
@update_header

CREATE SEQUENCE CSR.PROPERTY_SUB_TYPE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER;
	
/************ CSRIMP *****************/
CREATE TABLE CSRIMP.TENANT (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    TENANT_ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_TENANT PRIMARY KEY (CSRIMP_SESSION_ID, TENANT_ID),
    CONSTRAINT FK_TENANT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.SPACE_TYPE_REGION_METRIC (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    SPACE_TYPE_ID NUMBER(10,0) NOT NULL,
    IND_SID NUMBER(10,0) NOT NULL,
    REGION_TYPE NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_SPACE_TYPE_REGION_METRIC PRIMARY KEY (CSRIMP_SESSION_ID, SPACE_TYPE_ID, IND_SID),
    CONSTRAINT FK_SPACE_TYPE_REGION_METRIC_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.SPACE_TYPE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    SPACE_TYPE_ID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255) NOT NULL,
    IS_TENANTABLE NUMBER(1,0) NOT NULL,
    CONSTRAINT PK_SPACE_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, SPACE_TYPE_ID),
    CONSTRAINT FK_SPACE_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_SPACE_TYPE_IS_TENANT CHECK (IS_TENANTABLE IN (0,1))
);

CREATE TABLE CSRIMP.SPACE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    REGION_SID NUMBER(10,0) NOT NULL,
    SPACE_TYPE_ID NUMBER(10,0) NOT NULL,
    PROPERTY_REGION_SID NUMBER(10,0) NOT NULL,
    PROPERTY_TYPE_ID NUMBER(10,0) NOT NULL,
    CURRENT_LEASE_ID NUMBER(10,0),
    CONSTRAINT PK_SPACE PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID),
    CONSTRAINT FK_SPACE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.REGION_TYPE_TAG_GROUP (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    REGION_TYPE NUMBER(10,0) NOT NULL,
    TAG_GROUP_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_REGION_TYPE_TAG_GROUP PRIMARY KEY (CSRIMP_SESSION_ID, REGION_TYPE, TAG_GROUP_ID),
    CONSTRAINT FK_REGION_TYPE_TAG_GROUP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.REGION_TYPE_METRIC (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    REGION_TYPE NUMBER(2,0) NOT NULL,
    IND_SID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_REGION_TYPE_METRIC PRIMARY KEY (CSRIMP_SESSION_ID, REGION_TYPE, IND_SID),
    CONSTRAINT FK_REGION_TYPE_METRIC_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.REGION_METRIC (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    MEASURE_SID NUMBER(10,0) NOT NULL,
    LOOKUP_KEY VARCHAR2(256),
    IND_SID NUMBER(10,0) NOT NULL,
    IS_MANDATORY NUMBER(1,0) NOT NULL,
    CONSTRAINT PK_REGION_METRIC PRIMARY KEY (CSRIMP_SESSION_ID, IND_SID),
    CONSTRAINT FK_REGION_METRIC_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_REG_METRIC_MAND CHECK (IS_MANDATORY IN (0,1))
);

CREATE TABLE CSRIMP.REGION_METRIC_REGION (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    IND_SID NUMBER(10,0) NOT NULL,
    REGION_SID NUMBER(10,0) NOT NULL,
    MEASURE_SID NUMBER(10,0) NOT NULL,
    MEASURE_CONVERSION_ID NUMBER(10,0),
    SOURCE_TYPE_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_REGION_METRIC_REGION PRIMARY KEY (CSRIMP_SESSION_ID, IND_SID, REGION_SID),
    CONSTRAINT FK_REGION_METRIC_REGION_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.REGION_METRIC_VAL (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    IND_SID NUMBER(10,0) NOT NULL,
    REGION_SID NUMBER(10,0) NOT NULL,
    EFFECTIVE_DTM DATE NOT NULL,
    ENTERED_BY_SID NUMBER(10,0) NOT NULL,
    ENTERED_DTM DATE NOT NULL,
    VAL NUMBER(24,10),
    NOTE VARCHAR2(4000),
    REGION_METRIC_VAL_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_REGION_METRIC_VAL PRIMARY KEY (CSRIMP_SESSION_ID, REGION_METRIC_VAL_ID),
    CONSTRAINT FK_REGION_METRIC_VAL_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_TYPE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PROPERTY_TYPE_ID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_PROPERTY_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PROPERTY_TYPE_ID),
    CONSTRAINT FK_PROPERTY_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_TAB (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PLUGIN_ID NUMBER(10,0) NOT NULL,
    PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
    POS NUMBER(10,0) NOT NULL,
    TAB_LABEL VARCHAR2(50),
    CONSTRAINT PK_PROPERTY_TAB PRIMARY KEY (CSRIMP_SESSION_ID, PLUGIN_ID),
    CONSTRAINT FK_PROPERTY_TAB_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_TAB_GROUP (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PLUGIN_ID NUMBER(10,0) NOT NULL,
    GROUP_SID NUMBER(10,0),
    ROLE_SID  NUMBER(10,0),
    CONSTRAINT PK_PROPERTY_TAB_GROUP PRIMARY KEY (CSRIMP_SESSION_ID, PLUGIN_ID, GROUP_SID),
	CONSTRAINT FK_PROPERTY_TAB_GRP_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_SUB_TYPE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PROPERTY_SUB_TYPE_ID NUMBER(10,0) NOT NULL,
    PROPERTY_TYPE_ID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_PROPERTY_SUB_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, PROPERTY_SUB_TYPE_ID),
    CONSTRAINT FK_PROPERTY_SUB_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_OPTIONS (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PROPERTY_HELPER_PKG VARCHAR2(255),
    CONSTRAINT PK_PROPERTY_OPTIONS PRIMARY KEY (CSRIMP_SESSION_ID),
    CONSTRAINT FK_PROPERTY_OPTIONS_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_ELEMENT_LAYOUT (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	ELEMENT_NAME VARCHAR2(255) NOT NULL,
    POS NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_PROPERTY_ELEMENT_LAYOUT PRIMARY KEY (CSRIMP_SESSION_ID, ELEMENT_NAME),
	CONSTRAINT FK_PROPERTY_EL_LAYOUT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_ADDRESS_OPTIONS (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    ELEMENT_NAME VARCHAR2(255) NOT NULL,
    MANDATORY NUMBER(1,0) NOT NULL,
    CONSTRAINT PK_PROPERTY_ADDRESS_OPTIONS PRIMARY KEY (CSRIMP_SESSION_ID, ELEMENT_NAME),
	CONSTRAINT FK_PROPERTY_ADDR_OPTIONS_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    REGION_SID NUMBER(10,0) NOT NULL,
    STREET_ADDR_1 VARCHAR2(200),
    CITY VARCHAR2(200),
    STATE VARCHAR2(200),
    POSTCODE VARCHAR2(200),
    FLOW_ITEM_ID NUMBER(10,0),
    STREET_ADDR_2 VARCHAR2(200),
    PROPERTY_TYPE_ID NUMBER(10,0),
    COMPANY_SID NUMBER(10,0),
    PROPERTY_SUB_TYPE_ID NUMBER(10,0),
    FUND_ID NUMBER(10,0),
    MGMT_COMPANY_ID NUMBER(10,0),
    MGMT_COMPANY_OTHER VARCHAR2(255),
    PM_BUILDING_ID VARCHAR2(256),
    CURRENT_LEASE_ID NUMBER(10,0),
    MGMT_COMPANY_CONTACT_ID NUMBER(10,0),
    CONSTRAINT PK_PROPERTY PRIMARY KEY (CSRIMP_SESSION_ID, REGION_SID),
    CONSTRAINT FK_PROPERTY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PROPERTY_PHOTO (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	PROPERTY_PHOTO_ID NUMBER(10,0) NOT NULL,
    PROPERTY_REGION_SID NUMBER(10,0) NOT NULL,
    SPACE_REGION_SID NUMBER(10,0),
    FILENAME VARCHAR2(256 BYTE) NOT NULL,
    MIME_TYPE VARCHAR2(255 BYTE) NOT NULL,
    DATA BLOB NOT NULL,
    CONSTRAINT PK_PROPERTY_PHOTO PRIMARY KEY (CSRIMP_SESSION_ID, PROPERTY_PHOTO_ID),
	CONSTRAINT FK_PROPERTY_PHOTO_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.PLUGIN (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PLUGIN_ID NUMBER(10,0) NOT NULL,
    PLUGIN_TYPE_ID NUMBER(10,0) NOT NULL,
    DESCRIPTION VARCHAR2(50) NOT NULL,
    JS_INCLUDE VARCHAR2(255) NOT NULL,
    JS_CLASS VARCHAR2(255) NOT NULL,
    CS_CLASS VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_PLUGIN PRIMARY KEY (CSRIMP_SESSION_ID, PLUGIN_ID),
    CONSTRAINT FK_PLUGIN_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MGMT_COMPANY_FUND_CONTACT (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    FUND_ID NUMBER(10,0) NOT NULL,
    MGMT_COMPANY_CONTACT_ID NUMBER(10,0) NOT NULL,
    MGMT_COMPANY_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_MGMT_COMP_FUND_CONT PRIMARY KEY (CSRIMP_SESSION_ID, FUND_ID, MGMT_COMPANY_CONTACT_ID, MGMT_COMPANY_ID),
    CONSTRAINT FK_MGMT_COMP_FUND_CONT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MGMT_COMPANY_CONTACT (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    MGMT_COMPANY_CONTACT_ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    PHONE VARCHAR2(255),
    MGMT_COMPANY_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_MGMT_COMPANY_CONTACT PRIMARY KEY (CSRIMP_SESSION_ID, MGMT_COMPANY_CONTACT_ID),
    CONSTRAINT FK_MGMT_COMPANY_CONTACT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.MGMT_COMPANY (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    MGMT_COMPANY_ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    COMPANY_SID NUMBER(10,0),
    CONSTRAINT PK_MGMT_COMPANY PRIMARY KEY (CSRIMP_SESSION_ID, MGMT_COMPANY_ID),
    CONSTRAINT FK_MGMT_COMPANY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.METER_IND (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    METER_IND_ID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255) NOT NULL,
    CONSUMPTION_IND_SID NUMBER(10,0) NOT NULL,
    COST_IND_SID NUMBER(10,0),
    GROUP_KEY VARCHAR2(255),
    DAYS_IND_SID NUMBER(10,0),
    COSTDAYS_IND_SID NUMBER(10,0),
    DEMAND_IND_SID NUMBER(10,0),
    CONSTRAINT PK_METER_IND PRIMARY KEY (CSRIMP_SESSION_ID, METER_IND_ID),
    CONSTRAINT FK_METER_IND_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.LEASE_TYPE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    LEASE_TYPE_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_LEASE_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, LEASE_TYPE_ID),
    CONSTRAINT FK_LEASE_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.LEASE_SPACE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    LEASE_ID NUMBER(10,0) NOT NULL,
    SPACE_REGION_SID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_LEASE_SPACE PRIMARY KEY (CSRIMP_SESSION_ID, LEASE_ID, SPACE_REGION_SID),
    CONSTRAINT FK_LEASE_SPACE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.LEASE_PROPERTY (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    LEASE_ID NUMBER(10,0) NOT NULL,
    PROPERTY_REGION_SID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_LEASE_PROPERTY PRIMARY KEY (CSRIMP_SESSION_ID, LEASE_ID, PROPERTY_REGION_SID),
    CONSTRAINT FK_LEASE_PROPERTY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.LEASE_POSTIT (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    LEASE_ID NUMBER(10,0) NOT NULL,
    POSTIT_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_LEASE_POSTIT PRIMARY KEY (CSRIMP_SESSION_ID, LEASE_ID, POSTIT_ID),
    CONSTRAINT FK_LEASE_POSTIT_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.LEASE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    LEASE_ID NUMBER(10,0) NOT NULL,
    START_DTM DATE NOT NULL,
    END_DTM DATE,
    NEXT_BREAK_DTM DATE,
    CURRENT_RENT NUMBER(16,2),
    NORMALISED_RENT NUMBER(16,2),
    NEXT_RENT_REVIEW DATE,
    TENANT_ID NUMBER(10,0) NOT NULL,
    CURRENCY_CODE VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_LEASE PRIMARY KEY (CSRIMP_SESSION_ID, LEASE_ID),
    CONSTRAINT FK_LEASE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.FUND_TYPE (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    FUND_TYPE_ID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255),
    CONSTRAINT PK_FUND_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, FUND_TYPE_ID),
    CONSTRAINT FK_FUND_TYPE_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.FUND_FORM_PLUGIN (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    PLUGIN_ID NUMBER(10,0) NOT NULL,
    POS NUMBER(10,0) NOT NULL,
    XML_PATH VARCHAR2(255) NOT NULL,
    KEY_NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_FUND_FORM_PLUGIN PRIMARY KEY (CSRIMP_SESSION_ID, PLUGIN_ID, POS),
    CONSTRAINT FK_FUND_FORM_PLUGIN_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.FUND (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    FUND_ID NUMBER(10,0) NOT NULL,
    COMPANY_SID NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY','CHAIN_COMPANY') NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    YEAR_OF_INCEPTION NUMBER(10,0),
    FUND_TYPE_ID NUMBER(10,0),
    DEFAULT_MGMT_COMPANY_ID NUMBER(10,0),
    MGR_CONTACT_NAME VARCHAR2(255),
    MGR_CONTACT_EMAIL VARCHAR2(255),
    MGR_CONTACT_PHONE VARCHAR2(255),
    CONSTRAINT PK_FUND PRIMARY KEY (CSRIMP_SESSION_ID, FUND_ID),
    CONSTRAINT FK_FUND_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE CSRIMP.CURRENCY (
    CSRIMP_SESSION_ID NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    CURRENCY_CODE VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CURRENCY PRIMARY KEY (CSRIMP_SESSION_ID, CURRENCY_CODE),
    CONSTRAINT FK_CURRENCY_IS FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

/*******************************************/
CREATE TABLE csrimp.map_tenant (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_tenant_id   NUMBER(10) NOT NULL,
    new_tenant_id   NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_tenant_id PRIMARY KEY (old_tenant_id) USING INDEX,
    CONSTRAINT uk_map_tenant_id UNIQUE (new_tenant_id) USING INDEX,
    CONSTRAINT fk_map_tenant_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_space_type (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_space_type_id   NUMBER(10) NOT NULL,
    new_space_type_id   NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_space_type_id PRIMARY KEY (old_space_type_id) USING INDEX,
    CONSTRAINT uk_map_space_type_id UNIQUE (new_space_type_id) USING INDEX,
    CONSTRAINT fk_map_space_type_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_property_type (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_property_type_id    NUMBER(10) NOT NULL,
    new_property_type_id    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_property_type_id PRIMARY KEY (old_property_type_id) USING INDEX,
    CONSTRAINT uk_map_property_type_id UNIQUE (new_property_type_id) USING INDEX,
    CONSTRAINT fk_map_property_type_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_sub_property_type (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_sub_property_type_id    NUMBER(10) NOT NULL,
    new_sub_property_type_id    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_sub_property_type_id PRIMARY KEY (old_sub_property_type_id) USING INDEX,
    CONSTRAINT uk_map_sub_property_type_id UNIQUE (new_sub_property_type_id) USING INDEX,
    CONSTRAINT fk_map_sub_prop_type_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_property_photo (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_property_photo_id    NUMBER(10) NOT NULL,
    new_property_photo_id    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_property_photo_id PRIMARY KEY (old_property_photo_id) USING INDEX,
    CONSTRAINT uk_map_property_photo_id UNIQUE (new_property_photo_id) USING INDEX,
    CONSTRAINT fk_map_property_photo_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_lease (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_lease_id    NUMBER(10) NOT NULL,
    new_lease_id    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_lease_id PRIMARY KEY (old_lease_id) USING INDEX,
    CONSTRAINT uk_map_lease_id UNIQUE (new_lease_id) USING INDEX,
    CONSTRAINT fk_map_lease_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_plugin (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_plugin_id   NUMBER(10) NOT NULL,
    new_plugin_id   NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_plugin_id PRIMARY KEY (old_plugin_id) USING INDEX,
    CONSTRAINT uk_map_plugin_id UNIQUE (new_plugin_id) USING INDEX,
    CONSTRAINT fk_map_plugin_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_plugin_type (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_plugin_type_id  NUMBER(10) NOT NULL,
    new_plugin_type_id  NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_plugin_type_id PRIMARY KEY (old_plugin_type_id) USING INDEX,
    CONSTRAINT uk_map_plugin_type_id UNIQUE (new_plugin_type_id) USING INDEX,
    CONSTRAINT fk_map_plugin_type_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_mgmt_company (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_mgmt_company_id				NUMBER(10) NOT NULL,
    new_mgmt_company_id				NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_mgmt_company_id PRIMARY KEY (old_mgmt_company_id) USING INDEX,
    CONSTRAINT uk_map_mgmt_company_id UNIQUE (new_mgmt_company_id) USING INDEX,
    CONSTRAINT fk_map_mgmt_company_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_fund (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_fund_id NUMBER(10) NOT NULL,
    new_fund_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_fund_id PRIMARY KEY (old_fund_id) USING INDEX,
    CONSTRAINT uk_map_fund_id UNIQUE (new_fund_id) USING INDEX,
    CONSTRAINT fk_map_fund_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_mgmt_company_contact (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_mgmt_company_contact_id NUMBER(10) NOT NULL,
    new_mgmt_company_contact_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_mgmt_company_contact_id PRIMARY KEY (old_mgmt_company_contact_id) USING INDEX,
    CONSTRAINT uk_map_mgmt_company_contact_id UNIQUE (new_mgmt_company_contact_id) USING INDEX,
    CONSTRAINT fk_map_mgmt_co_cont_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_meter_ind (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_meter_ind_id    NUMBER(10) NOT NULL,
    new_meter_ind_id    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_meter_ind_id PRIMARY KEY (old_meter_ind_id) USING INDEX,
    CONSTRAINT uk_map_meter_ind_id UNIQUE (new_meter_ind_id) USING INDEX,
    CONSTRAINT fk_map_meter_ind_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_lease_type (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_lease_type_id   NUMBER(10) NOT NULL,
    new_lease_type_id   NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_lease_type_id PRIMARY KEY (old_lease_type_id) USING INDEX,
    CONSTRAINT uk_map_lease_type_id UNIQUE (new_lease_type_id) USING INDEX,
    CONSTRAINT fk_map_lease_type_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_fund_type (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_fund_type_id    NUMBER(10) NOT NULL,
    new_fund_type_id    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_fund_type_id PRIMARY KEY (old_fund_type_id) USING INDEX,
    CONSTRAINT uk_map_fund_type_id UNIQUE (new_fund_type_id) USING INDEX,
    CONSTRAINT fk_map_fund_type_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE csrimp.map_region_metric_val (
    CSRIMP_SESSION_ID               NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
    old_region_metric_val_id	    NUMBER(10) NOT NULL,
    new_region_metric_val_id	    NUMBER(10) NOT NULL,
    CONSTRAINT pk_map_region_metric_val_id PRIMARY KEY (old_region_metric_val_id) USING INDEX,
    CONSTRAINT uk_map_region_metric_val_id UNIQUE (new_region_metric_val_id) USING INDEX,
    CONSTRAINT fk_map_region_metric_val_id_is FOREIGN KEY
        (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID)
        ON DELETE CASCADE
);

/* object_grants */

-- csr tables
grant select,insert,update on csr.CURRENCY to csrimp;
grant select,insert,update on csr.FUND to csrimp;
grant select,insert,update on csr.FUND_FORM_PLUGIN to csrimp;
grant select,insert,update on csr.FUND_TYPE to csrimp;
grant select,insert,update on csr.LEASE to csrimp;
grant select,insert,update on csr.LEASE_POSTIT to csrimp;
grant select,insert,update on csr.LEASE_PROPERTY to csrimp;
grant select,insert,update on csr.LEASE_SPACE to csrimp;
grant select,insert,update on csr.LEASE_TYPE to csrimp;
grant select,insert,update on csr.METER_IND to csrimp;
grant select,insert,update on csr.MGMT_COMPANY to csrimp;
grant select,insert,update on csr.MGMT_COMPANY_CONTACT to csrimp;
grant select,insert,update on csr.MGMT_COMPANY_FUND_CONTACT to csrimp;
grant select,insert,update on csr.PLUGIN to csrimp;
grant select,insert,update on csr.PROPERTY to csrimp;
grant select,insert,update on csr.PROPERTY_ADDRESS_OPTIONS to csrimp;
grant select,insert,update on csr.PROPERTY_ELEMENT_LAYOUT to csrimp;
grant select,insert,update on csr.PROPERTY_OPTIONS to csrimp;
grant select,insert,update on csr.PROPERTY_PHOTO to csrimp;
grant select,insert,update on csr.PROPERTY_SUB_TYPE to csrimp;
grant select,insert,update on csr.PROPERTY_TAB to csrimp;
grant select,insert,update on csr.PROPERTY_TAB_GROUP to csrimp;
grant select,insert,update on csr.PROPERTY_TYPE to csrimp;
grant select,insert,update on csr.REGION_METRIC to csrimp;
grant select,insert,update on csr.REGION_METRIC_REGION to csrimp;
grant select,insert,update on csr.REGION_METRIC_VAL to csrimp;
grant select,insert,update on csr.REGION_TYPE_METRIC to csrimp;
grant select,insert,update on csr.REGION_TYPE_TAG_GROUP to csrimp;
grant select,insert,update on csr.SPACE to csrimp;
grant select,insert,update on csr.SPACE_TYPE to csrimp;
grant select,insert,update on csr.SPACE_TYPE_REGION_METRIC to csrimp;
grant select,insert,update on csr.TENANT to csrimp;

grant select on csr.tenant_id_seq to csrimp;
grant select on csr.space_type_id_seq to csrimp;
grant select on csr.property_photo_id_seq to csrimp;
grant select on csr.property_type_id_seq to csrimp;
grant select on csr.property_sub_type_id_seq to csrimp;
grant select on csr.lease_id_seq to csrimp;
grant select on csr.plugin_Id_seq to csrimp;
grant select on csr.mgmt_company_id_seq to csrimp;
grant select on csr.fund_id_seq to csrimp;
grant select on csr.mgmt_company_contact_id_seq to csrimp;
grant select on csr.meter_ind_Id_seq to csrimp;
grant select on csr.lease_type_id_seq to csrimp;
grant select on csr.fund_type_id_seq to csrimp;
grant select on csr.region_metric_val_id_seq to csrimp;

/* package_grants */
grant select,insert,update,delete on CSRIMP.CURRENCY to web_user;
grant select,insert,update,delete on CSRIMP.FUND to web_user;
grant select,insert,update,delete on CSRIMP.FUND_FORM_PLUGIN to web_user;
grant select,insert,update,delete on CSRIMP.FUND_TYPE to web_user;
grant select,insert,update,delete on CSRIMP.LEASE to web_user;
grant select,insert,update,delete on CSRIMP.LEASE_POSTIT to web_user;
grant select,insert,update,delete on CSRIMP.LEASE_PROPERTY to web_user;
grant select,insert,update,delete on CSRIMP.LEASE_SPACE to web_user;
grant select,insert,update,delete on CSRIMP.LEASE_TYPE to web_user;
grant select,insert,update,delete on CSRIMP.METER_IND to web_user;
grant select,insert,update,delete on CSRIMP.MGMT_COMPANY to web_user;
grant select,insert,update,delete on CSRIMP.MGMT_COMPANY_CONTACT to web_user;
grant select,insert,update,delete on CSRIMP.MGMT_COMPANY_FUND_CONTACT to web_user;
grant select,insert,update,delete on CSRIMP.PLUGIN to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_ADDRESS_OPTIONS to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_ELEMENT_LAYOUT to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_OPTIONS to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_PHOTO to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_SUB_TYPE to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_TAB to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_TAB_GROUP to web_user;
grant select,insert,update,delete on CSRIMP.PROPERTY_TYPE to web_user;
grant select,insert,update,delete on CSRIMP.REGION_METRIC to web_user;
grant select,insert,update,delete on CSRIMP.REGION_METRIC_REGION to web_user;
grant select,insert,update,delete on CSRIMP.REGION_METRIC_VAL to web_user;
grant select,insert,update,delete on CSRIMP.REGION_TYPE_METRIC to web_user;
grant select,insert,update,delete on CSRIMP.REGION_TYPE_TAG_GROUP to web_user;
grant select,insert,update,delete on CSRIMP.SPACE to web_user;
grant select,insert,update,delete on CSRIMP.SPACE_TYPE to web_user;
grant select,insert,update,delete on CSRIMP.SPACE_TYPE_REGION_METRIC to web_user;
grant select,insert,update,delete on CSRIMP.TENANT to web_user;
/*********************************************/

@@../csrimp/rls

@@../schema_pkg
@@../schema_body

@update_tail
