-- Please update version.sql too -- this keeps clean builds in sync
define version=3384
define minor_version=4
@update_header

-- *** DDL ***
-- Create tables

-- Alter tables
DROP TABLE csr.region_certificates;
DROP TABLE csrimp.region_certificates;
DROP TABLE csr.region_energy_ratings;
DROP TABLE csrimp.region_energy_ratings;

CREATE SEQUENCE CSR.REGION_CERTIFICATE_ID_SEQ;
CREATE TABLE CSR.REGION_CERTIFICATE (
	APP_SID						NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	REGION_CERTIFICATE_ID		NUMBER(24,0) NOT NULL,
	REGION_SID					NUMBER(10,0) NOT NULL,
	CERTIFICATION_ID			NUMBER(10,0) NOT NULL,
	CERTIFICATION_LEVEL_ID		NUMBER(10,0),
	CERTIFICATE_NUMBER			NUMBER(10,0),
	FLOOR_AREA					NUMBER(10,2) NOT NULL,
	ISSUED_DTM					DATE,
	EXPIRY_DTM					DATE,
	EXTERNAL_CERTIFICATE_ID		NUMBER(10,0),
	DELETED						NUMBER(1, 0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_REGION_CERTS PRIMARY KEY (APP_SID, REGION_CERTIFICATE_ID),
	CONSTRAINT UK_REG_CERT_EXT_ID UNIQUE (APP_SID, REGION_SID, CERTIFICATION_ID, CERTIFICATION_LEVEL_ID, EXTERNAL_CERTIFICATE_ID),
	CONSTRAINT CHK_REGION_CERT_EXP_AFTER_ISS CHECK ((ISSUED_DTM IS NULL OR EXPIRY_DTM IS NULL) OR (ISSUED_DTM IS NOT NULL AND EXPIRY_DTM IS NOT NULL AND ISSUED_DTM < EXPIRY_DTM)),
	CONSTRAINT CK_REGION_CERT_DELETED CHECK (DELETED in (0,1))
)
;

ALTER TABLE CSR.REGION_CERTIFICATE ADD CONSTRAINT FK_REG_CERT_REGION
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.REGION_CERTIFICATE ADD CONSTRAINT FK_REG_CERT_CERT_ID
	FOREIGN KEY (CERTIFICATION_ID)
	REFERENCES CSR.CERTIFICATION(CERTIFICATION_ID)
;

ALTER TABLE CSR.REGION_CERTIFICATE ADD CONSTRAINT FK_REG_CERT_CERT_LVL
	FOREIGN KEY (CERTIFICATION_LEVEL_ID, CERTIFICATION_ID)
	REFERENCES CSR.CERTIFICATION_LEVEL(CERTIFICATION_LEVEL_ID, CERTIFICATION_ID)
;


CREATE TABLE CSRIMP.REGION_CERTIFICATE (
	CSRIMP_SESSION_ID			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID					NUMBER(10,0) NOT NULL,
	CERTIFICATION_ID			NUMBER(10,0) NOT NULL,
	CERTIFICATION_LEVEL_ID		NUMBER(10,0),
	CERTIFICATE_NUMBER			NUMBER(10,0),
	FLOOR_AREA					NUMBER(10,2) NOT NULL,
	ISSUED_DTM					DATE,
	EXPIRY_DTM					DATE,
	EXTERNAL_CERTIFICATE_ID		NUMBER(10,0),
	DELETED						NUMBER(1, 0) NOT NULL,
	CONSTRAINT CK_REGION_CERT_DELETED CHECK (DELETED in (0,1))
);


CREATE TABLE CSR.REGION_ENERGY_RATING (
	APP_SID						NUMBER(10,0) DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	REGION_SID					NUMBER(10,0) NOT NULL,
	ENERGY_RATING_ID			NUMBER(10,0) NOT NULL,
	FLOOR_AREA					NUMBER(10,2) NOT NULL,
	ISSUED_DTM					DATE,
	EXPIRY_DTM					DATE,
	CONSTRAINT PK_REGION_ENERGY_RAT PRIMARY KEY (APP_SID, REGION_SID),
	CONSTRAINT CHK_REGION_ENERGY_RAT_EXP_AFTER_ISS CHECK ((ISSUED_DTM IS NULL OR EXPIRY_DTM IS NULL) OR (ISSUED_DTM IS NOT NULL AND EXPIRY_DTM IS NOT NULL AND ISSUED_DTM < EXPIRY_DTM))
)
;

ALTER TABLE CSR.REGION_ENERGY_RATING ADD CONSTRAINT FK_REG_ENE_RAT_REGION
	FOREIGN KEY (APP_SID, REGION_SID)
	REFERENCES CSR.REGION(APP_SID, REGION_SID)
;

ALTER TABLE CSR.REGION_ENERGY_RATING ADD CONSTRAINT FK_REG_ENE_RAT_ID
	FOREIGN KEY (ENERGY_RATING_ID)
	REFERENCES CSR.ENERGY_RATING(ENERGY_RATING_ID)
;

CREATE TABLE CSRIMP.REGION_ENERGY_RATING (
	CSRIMP_SESSION_ID			NUMBER(10) DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	REGION_SID					NUMBER(10,0) NOT NULL,
	ENERGY_RATING_ID			NUMBER(10,0) NOT NULL,
	FLOOR_AREA					NUMBER(10,2) NOT NULL,
	ISSUED_DTM					DATE,
	EXPIRY_DTM					DATE
);


CREATE INDEX CSR.IX_REGION_CERTIF_CERTIFICATION ON CSR.REGION_CERTIFICATE (CERTIFICATION_ID);
CREATE INDEX CSR.IX_REGION_CERTIF_CERTIF_LEVEL ON CSR.REGION_CERTIFICATE (CERTIFICATION_LEVEL_ID, CERTIFICATION_ID);
CREATE INDEX CSR.IX_REGION_ENERGY_ENERGY_RATING ON CSR.REGION_ENERGY_RATING (ENERGY_RATING_ID);

-- *** Grants ***
grant select on csr.region_certificate_id_seq to csrimp;
grant select,insert, update on csr.region_certificate to csrimp;
grant select,insert,update,delete on csrimp.region_certificate to tool_user;
grant select,insert, update on csr.region_energy_rating to csrimp;
grant select,insert,update,delete on csrimp.region_energy_rating to tool_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../region_certificate_pkg
@../schema_pkg

@../csr_app_body
@../region_certificate_body
@../schema_body
@../csrimp/imp_body

@update_tail
