-- Please update version.sql too -- this keeps clean builds in sync
define version=742
@update_header

CREATE TABLE csr.LOGISTICS_CHANGED(
    APP_SID             NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    LOCATION_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_LOGISTICS_CHANGED PRIMARY KEY (APP_SID, LOCATION_TYPE_ID)
)
;

ALTER TABLE csr.LOGISTICS_CHANGED ADD CONSTRAINT FK_CUSTOMER_LOGI_CHANGED 
    FOREIGN KEY (APP_SID)
    REFERENCES csr.CUSTOMER(APP_SID)
;

ALTER TABLE csr.LOGISTICS_CHANGED ADD CONSTRAINT FK_LOC_TYPE_LOGI_CHANGED 
    FOREIGN KEY (LOCATION_TYPE_ID)
    REFERENCES csr.LOCATION_TYPE(LOCATION_TYPE_ID)
;

@update_tail
