-- Please update version.sql too -- this keeps clean builds in sync
define version=2197
@update_header

ALTER TABLE CHAIN.COMPANY_TYPE_CAPABILITY ADD PRIMARY_COMPANY_TYPE_ROLE_SID	NUMBER(10, 0) NULL;

ALTER TABLE CHAIN.COMPANY_TYPE_CAPABILITY MODIFY PRIMARY_COMPANY_GROUP_TYPE_ID NULL;

ALTER TABLE CHAIN.COMPANY_TYPE_CAPABILITY ADD CONSTRAINT FK_CTC_COMPANY_TYPE_ROLE
	FOREIGN KEY (APP_SID, PRIMARY_COMPANY_TYPE_ID, PRIMARY_COMPANY_TYPE_ROLE_SID)
	REFERENCES CHAIN.COMPANY_TYPE_ROLE(APP_SID, COMPANY_TYPE_ID, ROLE_SID)
;

DROP INDEX CHAIN.UK_CTC_UNIQUE_PERMISSION_SET;

CREATE UNIQUE INDEX CHAIN.UK_CTC_UNIQUE_PERMISSION_SET 
	ON CHAIN.COMPANY_TYPE_CAPABILITY(APP_SID, PRIMARY_COMPANY_TYPE_ID, NVL2(PRIMARY_COMPANY_GROUP_TYPE_ID, PRIMARY_COMPANY_GROUP_TYPE_ID || 'GR', PRIMARY_COMPANY_TYPE_ROLE_SID || 'RL'), CAPABILITY_ID, 
		NVL2(SECONDARY_COMPANY_TYPE_ID, 
			NVL2(TERTIARY_COMPANY_TYPE_ID, 'T' || TERTIARY_COMPANY_TYPE_ID || 'R' || SECONDARY_COMPANY_TYPE_ID, 'R' || SECONDARY_COMPANY_TYPE_ID), 
			'C' || PRIMARY_COMPANY_TYPE_ID))
;

ALTER TABLE CHAIN.COMPANY_TYPE_CAPABILITY ADD CONSTRAINT CHK_GROUP_ROLE_XOR CHECK
	((PRIMARY_COMPANY_GROUP_TYPE_ID IS NOT NULL AND PRIMARY_COMPANY_TYPE_ROLE_SID IS NULL) OR (PRIMARY_COMPANY_GROUP_TYPE_ID IS NULL AND PRIMARY_COMPANY_TYPE_ROLE_SID IS NOT NULL))
;

CREATE INDEX CHAIN.IX_PRIMARY_CT_ROLE_SID ON CHAIN.COMPANY_TYPE_CAPABILITY(APP_SID, PRIMARY_COMPANY_TYPE_ID, PRIMARY_COMPANY_TYPE_ROLE_SID);

@../chain/type_capability_pkg
@../chain/type_capability_body

@update_tail
