-- Please update version.sql too -- this keeps clean builds in sync
define version=310
@update_header
	
ALTER TABLE METER_DOCUMENT DROP COLUMN REGION_SID CASCADE CONSTRAINTS;

ALTER TABLE METER_DOCUMENT ADD CONSTRAINT RefCUSTOMER1144 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID)
;

CREATE TABLE REGION_PROC_DOC(
    APP_SID       NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SID    NUMBER(10, 0)    NOT NULL,
    DOC_ID        NUMBER(10, 0)    NOT NULL,
    INHERITED     NUMBER(1, 0)     NOT NULL
                  CHECK (INHERITED IN (0,1)),
    CONSTRAINT PK586 PRIMARY KEY (APP_SID, REGION_SID, DOC_ID)
)
;

CREATE TABLE REGION_PROC_FILE(
    APP_SID              NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    REGION_SID           NUMBER(10, 0)    NOT NULL,
    METER_DOCUMENT_ID    NUMBER(10, 0)    NOT NULL,
    INHERITED            NUMBER(1, 0)     NOT NULL
                         CHECK (INHERITED IN (0,1)),
    CONSTRAINT PK587 PRIMARY KEY (APP_SID, REGION_SID, METER_DOCUMENT_ID)
)
;

ALTER TABLE REGION_PROC_DOC ADD CONSTRAINT RefDOC1139 
    FOREIGN KEY (APP_SID, DOC_ID)
    REFERENCES DOC(APP_SID, DOC_ID)
;

ALTER TABLE REGION_PROC_DOC ADD CONSTRAINT RefREGION1140 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES REGION(APP_SID, REGION_SID)
;

ALTER TABLE REGION_PROC_FILE ADD CONSTRAINT RefREGION1142 
    FOREIGN KEY (APP_SID, REGION_SID)
    REFERENCES REGION(APP_SID, REGION_SID)
;


@update_tail
