-- Please update version.sql too -- this keeps clean builds in sync
define version=3200
define minor_version=4
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CSR.TPL_REPORT_VARIANT_TAG (
	APP_SID				NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
	TPL_REPORT_SID		NUMBER(10, 0)	NOT NULL,
	LANGUAGE_CODE		VARCHAR2(10)	NOT NULL,
	TAG					VARCHAR2(256)	NOT NULL,
	CONSTRAINT PK_TPL_REPORT_VARIANT_TAG PRIMARY KEY (APP_SID, TPL_REPORT_SID, LANGUAGE_CODE, TAG)
);

CREATE TABLE CSRIMP.TPL_REPORT_VARIANT_TAG (
	CSRIMP_SESSION_ID	NUMBER(10) 		DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	TPL_REPORT_SID		NUMBER(10, 0)	NOT NULL,
	LANGUAGE_CODE		VARCHAR2(10)	NOT NULL,
	TAG					VARCHAR2(256)	NOT NULL,
	CONSTRAINT PK_TPL_REPORT_VARIANT_TAG PRIMARY KEY (CSRIMP_SESSION_ID, TPL_REPORT_SID, LANGUAGE_CODE),
	CONSTRAINT FK_TPL_REPORT_VARIANT_TAG_IS FOREIGN KEY (CSRIMP_SESSION_ID)
		REFERENCES CSRIMP.CSRIMP_SESSION(CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Alter tables

ALTER TABLE CSR.TPL_REPORT_VARIANT_TAG ADD CONSTRAINT FK_TPL_REPORT_VARIANT 
	FOREIGN KEY (APP_SID, TPL_REPORT_SID, LANGUAGE_CODE) 
	REFERENCES CSR.TPL_REPORT_VARIANT(APP_SID, MASTER_TEMPLATE_SID, LANGUAGE_CODE)
	ON DELETE CASCADE;

ALTER TABLE CSR.TPL_REPORT_VARIANT ADD (
	MIME_TYPE			VARCHAR2(255)
);

ALTER TABLE CSRIMP.TPL_REPORT_VARIANT ADD (
	MIME_TYPE			VARCHAR2(255)
);

-- *** Grants ***

GRANT INSERT ON csr.tpl_report_variant_tag TO csrimp;
GRANT SELECT, INSERT, UPDATE, DELETE ON csrimp.tpl_report_variant_tag TO tool_user;

-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@..\schema_pkg
@..\templated_report_pkg

@..\csr_app_body
@..\schema_body
@..\templated_report_body
@..\csrimp\imp_body

@update_tail
