-- Please update version.sql too -- this keeps clean builds in sync
define version=2051
@update_header

BEGIN
	FOR r IN (
		SELECT index_name
		  FROM user_indexes
		 WHERE index_name = 'IX_FLOW_STATE_RL_CAP_ROLE'
	) LOOP
		EXECUTE IMMEDIATE 'DROP INDEX IX_FLOW_STATE_RL_CAP_ROLE';
		EXECUTE IMMEDIATE 'CREATE INDEX csr.IX_FLOW_STATE_RL_CAP_ROLE ON csr.FLOW_STATE_ROLE_CAPABILITY (APP_SID, FLOW_STATE_ID, ROLE_SID)';
	END LOOP;
	
	FOR r IN (
		SELECT index_name
		  FROM user_indexes
		 WHERE index_name = 'IX_FLOW_STATE_RL_CAP_INV'
	) LOOP
		EXECUTE IMMEDIATE 'DROP INDEX IX_FLOW_STATE_RL_CAP_INV';
		EXECUTE IMMEDIATE 'CREATE INDEX csr.IX_FLOW_STATE_RL_CAP_INV ON csr.FLOW_STATE_ROLE_CAPABILITY (APP_SID, FLOW_STATE_ID, FLOW_INVOLVEMENT_TYPE_ID)';
	END LOOP;
END;
/

@update_tail
