-- Please update version.sql too -- this keeps clean builds in sync
define version=674
@update_header


ALTER TABLE csr.INTERNAL_AUDIT ADD (
    INTERNAL_AUDIT_TYPE_ID    NUMBER(10, 0) 
);
 
CREATE TABLE csr.INTERNAL_AUDIT_POSTIT(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    INTERNAL_AUDIT_SID    NUMBER(10, 0)    NOT NULL,
    POSTIT_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK_INTERNAL_AUDIT_POSTIT PRIMARY KEY (APP_SID, INTERNAL_AUDIT_SID, POSTIT_ID)
);


CREATE TABLE csr.INTERNAL_AUDIT_TYPE(
    APP_SID                   NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    INTERNAL_AUDIT_TYPE_ID    NUMBER(10, 0)    NOT NULL,
    LABEL                     VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK_INTERNAL_AUDIT_TYPE_ID PRIMARY KEY (APP_SID, INTERNAL_AUDIT_TYPE_ID)
);


ALTER TABLE csr.INTERNAL_AUDIT ADD CONSTRAINT FK_IA_IA_TYPE 
    FOREIGN KEY (APP_SID, INTERNAL_AUDIT_TYPE_ID)
    REFERENCES csr.INTERNAL_AUDIT_TYPE(APP_SID, INTERNAL_AUDIT_TYPE_ID);
 

ALTER TABLE csr.INTERNAL_AUDIT_POSTIT ADD CONSTRAINT FK_IA_IA_POSTIT 
    FOREIGN KEY (APP_SID, INTERNAL_AUDIT_SID)
    REFERENCES csr.INTERNAL_AUDIT(APP_SID, INTERNAL_AUDIT_SID);

ALTER TABLE csr.INTERNAL_AUDIT_POSTIT ADD CONSTRAINT FK_IA_POSTIT 
    FOREIGN KEY (APP_SID, POSTIT_ID)
    REFERENCES csr.POSTIT(APP_SID, POSTIT_ID) ON DELETE CASCADE;


ALTER TABLE csr.INTERNAL_AUDIT_TYPE ADD CONSTRAINT FK_CUSTOMER_IA_TYPE 
    FOREIGN KEY (APP_SID)
    REFERENCES csr.CUSTOMER(APP_SID);

/*
ALTER TABLE csr.INTERNAL_AUDIT MODIFY INTERNAL_AUDIT_TYPE_ID NOT NULL;
*/

@..\audit_pkg
@..\audit_body

update security.web_resource 
    set rewrite_path = replace(lower(rewrite_path), 'quicksurvey/survey.acds', 'quicksurvey/public/view.acds') 
  where rewrite_path like '%quicksurvey%';
  
@..\quick_survey_body

@update_tail
