-- Please update version.sql too -- this keeps clean builds in sync
define version=471
@update_header

-- SEQUENCE: DELEGATION_GRID_ID_SEQ 
CREATE SEQUENCE DELEGATION_GRID_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER;

 
-- TABLE: DELEGATION_GRID 
CREATE TABLE DELEGATION_GRID(
    APP_SID               NUMBER(10, 0)    DEFAULT SYS_CONTEXT('SECURITY','APP') NOT NULL,
    DELEGATION_GRID_ID    NUMBER(10, 0)    NOT NULL,
    PATH                  VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK_DELEGATION_GRID PRIMARY KEY (APP_SID, DELEGATION_GRID_ID)
);


ALTER TABLE DELEGATION_IND ADD (
    DELEGATION_GRID_ID    NUMBER(10, 0)
);


ALTER TABLE DELEGATION_IND ADD CONSTRAINT RefDELEGATION_GRID1705 
    FOREIGN KEY (APP_SID, DELEGATION_GRID_ID)
    REFERENCES DELEGATION_GRID(APP_SID, DELEGATION_GRID_ID)
;


ALTER TABLE DELEGATION_GRID ADD CONSTRAINT RefCUSTOMER1707 
    FOREIGN KEY (APP_SID)
    REFERENCES CUSTOMER(APP_SID);

@..\delegation_body
@..\sheet_body

@update_tail
