define version=1983
@update_header

CREATE GLOBAL TEMPORARY TABLE CSR.TEMP_INITIATIVE_METRIC_IDS
(
	INITIATIVE_METRIC_ID 		NUMBER(10)	NOT NULL,
	MEASURE_CONVERSION_ID		NUMBER(10)	NULL
)
ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE CSR.TEMP_INITIATIVE_AGGR_VAL
(
	INITIATIVE_SID			NUMBER(10)		NOT NULL,
  	INITIATIVE_METRIC_ID	NUMBER(10)		NOT NULL,
	REGION_SID				NUMBER(10)		NOT NULL,
	START_DTM				DATE			NOT NULL,
	END_DTM					DATE			NOT NULL,
	VAL_NUMBER				NUMBER(24, 10)	NULL
)
ON COMMIT DELETE ROWS;

ALTER TABLE CSR.INITIATIVE_METRIC ADD (
	DIVISIBILITY			NUMBER(10)	NULL
);

BEGIN
	-- XXX: Only Barclays using this atm
	-- and all the metrics are divisible 
	UPDATE csr.initiative_metric
	   SET divisibility = csr.csr_data_pkg.DIVISIBILITY_DIVISIBLE;
END;
/

ALTER TABLE CSR.INITIATIVE_METRIC MODIFY (
	DIVISIBILITY			NUMBER(10)	NOT NULL
);


@../initiative_aggr_pkg
@../initiative_aggr_body

@update_tail
