-- Please update version.sql too -- this keeps clean builds in sync
define version=3040
define minor_version=38
@update_header

-- *** DDL ***
-- Create tables
CREATE TABLE CHAIN.COMPANY_TAB_RELATED_CO_TYPE(
	APP_SID							NUMBER(10, 0)	DEFAULT SYS_CONTEXT('SECURITY', 'APP') NOT NULL,
	COMPANY_TAB_ID					NUMBER(10, 0)	NOT NULL,
	COMPANY_TYPE_ID					NUMBER(10, 0)	NOT NULL,
	CONSTRAINT COMPANY_TAB_REL_CO_TYPE_PK PRIMARY KEY (APP_SID, COMPANY_TAB_ID, COMPANY_TYPE_ID)
);

ALTER TABLE CHAIN.COMPANY_TAB_RELATED_CO_TYPE ADD CONSTRAINT REF_RCT_COMPANY_TAB 
    FOREIGN KEY (APP_SID, COMPANY_TAB_ID)
    REFERENCES CHAIN.COMPANY_TAB(APP_SID, COMPANY_TAB_ID)
;

ALTER TABLE CHAIN.COMPANY_TAB_RELATED_CO_TYPE ADD CONSTRAINT REF_RCT_COMPANY_TYPE 
    FOREIGN KEY (APP_SID, COMPANY_TYPE_ID)
    REFERENCES CHAIN.COMPANY_TYPE(APP_SID, COMPANY_TYPE_ID)
;

CREATE TABLE CSRIMP.CHAIN_CO_TAB_RELATED_CO_TYPE (
	CSRIMP_SESSION_ID				NUMBER(10)		DEFAULT SYS_CONTEXT('SECURITY', 'CSRIMP_SESSION_ID') NOT NULL,
	COMPANY_TAB_ID					NUMBER(10, 0)	NOT NULL,
	COMPANY_TYPE_ID					NUMBER(10, 0)	NOT NULL,
	CONSTRAINT PK_CO_TAB_REL_CO_TYPE PRIMARY KEY (CSRIMP_SESSION_ID, COMPANY_TAB_ID, COMPANY_TYPE_ID),
	CONSTRAINT FK_CO_TAB_REL_CO_TYPE FOREIGN KEY (CSRIMP_SESSION_ID) REFERENCES CSRIMP.CSRIMP_SESSION (CSRIMP_SESSION_ID) ON DELETE CASCADE
);

-- Alter tables

ALTER TABLE CHAIN.COMPANY_TAB ADD 
	DEFAULT_SAVED_FILTER_SID NUMBER(10) NULL
;

ALTER TABLE CHAIN.COMPANY_TAB ADD CONSTRAINT REF_CO_TAB_DEF_SAVED_FILTER
    FOREIGN KEY (APP_SID, DEFAULT_SAVED_FILTER_SID)
    REFERENCES CHAIN.SAVED_FILTER(APP_SID, SAVED_FILTER_SID)
;

ALTER TABLE CSRIMP.CHAIN_COMPANY_TAB ADD 
	DEFAULT_SAVED_FILTER_SID NUMBER(10) NULL
;


-- *** Grants ***
GRANT SELECT, INSERT, UPDATE ON chain.company_tab_related_co_type TO csr;
GRANT SELECT, INSERT, UPDATE ON chain.company_tab_related_co_type TO csrimp;
-- ** Cross schema constraints ***

-- *** Views ***
-- Please paste the content of the view and add a comment referencing the path of the create_views file which will contain your view changes.

-- *** Data changes ***
-- RLS

-- Data

-- ** New package grants **

-- *** Conditional Packages ***

-- *** Packages ***
@../chain/company_filter_pkg
@../schema_pkg

@../chain/company_filter_body
@../schema_body
@../csrimp/imp_body

@update_tail
