-- Please update version.sql too -- this keeps clean builds in sync
define version=151
@update_header


-- 
-- SEQUENCE: PORTLET_ID_SEQ 
--

CREATE SEQUENCE PORTLET_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
-- 
-- SEQUENCE: TAB_ID_SEQ 
--

CREATE SEQUENCE TAB_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: TAB_PORTLET_ID_SEQ 
--

CREATE SEQUENCE TAB_PORTLET_ID_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


-- 
-- TABLE: CUSTOMER_PORTLET 
--

CREATE TABLE CUSTOMER_PORTLET(
    PORTLET_ID       NUMBER(10, 0)    NOT NULL,
    CSR_ROOT_SID     NUMBER(10, 0)    NOT NULL,
    DEFAULT_STATE    CLOB,
    CONSTRAINT PK412 PRIMARY KEY (PORTLET_ID, CSR_ROOT_SID)
)
;


-- 
-- TABLE: PORTLET 
--

CREATE TABLE PORTLET(
    PORTLET_ID       NUMBER(10, 0)    NOT NULL,
    NAME             VARCHAR2(255)    NOT NULL,
    TYPE             VARCHAR2(255)    NOT NULL,
    DEFAULT_STATE    CLOB,
    SCRIPT_PATH      VARCHAR2(255),
    CONSTRAINT PK411 PRIMARY KEY (PORTLET_ID)
)
;



-- 
-- TABLE: TAB 
--

CREATE TABLE TAB(
    USER_SID    NUMBER(10, 0)    NOT NULL,
    TAB_ID      NUMBER(10, 0)    NOT NULL,
    POS         NUMBER(10, 0)     DEFAULT 0 NOT NULL,
    LAYOUT      NUMBER(10, 0)    NOT NULL,
    NAME        VARCHAR2(255)    NOT NULL,
    CSR_ROOT_SID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK410 PRIMARY KEY (TAB_ID)
)
;



-- 
-- TABLE: TAB_PORTLET 
--

CREATE TABLE TAB_PORTLET(
    TAB_PORTLET_ID    NUMBER(10, 0)    NOT NULL,
    TAB_ID            NUMBER(10, 0)    NOT NULL,
    PORTLET_ID        NUMBER(10, 0)    NOT NULL,
    COLUMN_NUM        NUMBER(10, 0)     DEFAULT 1 NOT NULL,
    POS               NUMBER(10, 0)    NOT NULL,
    STATE             CLOB,
    CONSTRAINT PK413 PRIMARY KEY (TAB_PORTLET_ID)
)
;



-- 
-- TABLE: CUSTOMER_PORTLET 
--

ALTER TABLE CUSTOMER_PORTLET ADD CONSTRAINT RefCUSTOMER795 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;

ALTER TABLE CUSTOMER_PORTLET ADD CONSTRAINT RefPORTLET796 
    FOREIGN KEY (PORTLET_ID)
    REFERENCES PORTLET(PORTLET_ID)
;


-- 
-- TABLE: TAB 
--

ALTER TABLE TAB ADD CONSTRAINT RefCSR_USER797 
    FOREIGN KEY (USER_SID)
    REFERENCES CSR_USER(CSR_USER_SID)
;


ALTER TABLE TAB ADD CONSTRAINT RefCUSTOMER801 
    FOREIGN KEY (CSR_ROOT_SID)
    REFERENCES CUSTOMER(CSR_ROOT_SID)
;

-- 
-- TABLE: TAB_PORTLET 
--

ALTER TABLE TAB_PORTLET ADD CONSTRAINT RefTAB798 
    FOREIGN KEY (TAB_ID)
    REFERENCES TAB(TAB_ID)
;

ALTER TABLE TAB_PORTLET ADD CONSTRAINT RefPORTLET799 
    FOREIGN KEY (PORTLET_ID)
    REFERENCES PORTLET(PORTLET_ID)
;



@update_tail
