-- Please update version.sql too -- this keeps clean builds in sync
define version=843
@update_header

ALTER TABLE ACTIONS.IND_TEMPLATE DROP CONSTRAINT CHK_IS_NPV;
ALTER TABLE ACTIONS.IND_TEMPLATE DROP COLUMN IS_NPV_COST;
ALTER TABLE ACTIONS.IND_TEMPLATE DROP COLUMN IS_NPV_SAVING;

ALTER TABLE ACTIONS.IND_TEMPLATE ADD (
	NPV_NET_NAME           VARCHAR2(256),
    NPV_NET_KEY            VARCHAR2(256),
    NPV_RATE_NAME          VARCHAR2(256),
    NPV_RATE_KEY           VARCHAR2(256),
    CONSTRAINT CHK_NPV_INPUT CHECK (IS_NPV = 0 OR (
	(NPV_NET_NAME IS NOT NULL OR NPV_NET_KEY IS NOT NULL) AND
	(NPV_RATE_NAME IS NOT NULL OR NPV_RATE_KEY IS NOT NULL)
)));

@../actions/initiative_body
@../actions/ind_template_body

@update_tail
