-- Please update version.sql too -- this keeps clean builds in sync
define version=146
@update_header

ALTER TABLE METER RENAME COLUMN PRIMAY_MEASURE_CONVERSION_ID TO PRIMARY_MEASURE_CONVERSION_ID;

ALTER TABLE METER RENAME TO ALL_METER;

ALTER TABLE ALL_METER ADD(
	ACTIVE	NUMBER(1)	NULL
);

UPDATE ALL_METER SET ACTIVE = 1;
COMMIT;

ALTER TABLE ALL_METER MODIFY (
	ACTIVE	NUMBER(1)	NOT NULL
);

CREATE OR REPLACE VIEW METER
	(REGION_SID, NOTE, PRIMARY_IND_SID, PRIMARY_MEASURE_CONVERSION_ID, 
		PRO_RATA_IND_SID, PRO_RATA_MEASURE_CONVERSION_ID) AS
  SELECT REGION_SID, NOTE, PRIMARY_IND_SID, PRIMARY_MEASURE_CONVERSION_ID, 
		PRO_RATA_IND_SID, PRO_RATA_MEASURE_CONVERSION_ID
    FROM ALL_METER
   WHERE ACTIVE = 1;
   
@update_tail