define version=3496
define minor_version=0
define is_combined=1
@update_header

-- clean out junk in csrimp
BEGIN
	FOR r IN (
		SELECT table_name
		  FROM all_tables
		 WHERE owner='CSRIMP' AND table_name!='CSRIMP_SESSION'
		)
	LOOP
		EXECUTE IMMEDIATE 'TRUNCATE TABLE csrimp.'||r.table_name;
	END LOOP;
	DELETE FROM csrimp.csrimp_session;
	commit;
END;
/

-- clean out debug log
TRUNCATE TABLE security.debug_log;



UPDATE csr.ind
   SET tolerance_number_of_periods = NULL, tolerance_number_of_standard_deviations_from_average = NULL
 WHERE tolerance_number_of_periods IS NOT NULL OR tolerance_number_of_standard_deviations_from_average IS NOT NULL;
ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_TYPE CHECK (TOLERANCE_TYPE IN (0,1,2,3,4));
ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_NUMBER_OF_PERIODS CHECK (
    TOLERANCE_NUMBER_OF_PERIODS >= 3 AND TOLERANCE_NUMBER_OF_PERIODS <= 99
);
ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE CHECK (
    TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE >= 0 AND TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE <= 5
);
ALTER TABLE csr.ind DROP CONSTRAINT IND_TOLERANCE;
ALTER TABLE CSR.REGION_TREE
ADD IS_SYSTEM_MANAGED NUMBER(1, 0) DEFAULT 0 NOT NULL;
ALTER TABLE csr.ind DROP CONSTRAINT CHK_TOLERANCE_NUMBER_OF_PERIODS;
ALTER TABLE csr.ind DROP CONSTRAINT CHK_TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE;
UPDATE csr.ind
   SET TOLERANCE_NUMBER_OF_PERIODS = 3, TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE = 0.5
 WHERE TOLERANCE_TYPE IN (3, 4) AND 
 	(TOLERANCE_NUMBER_OF_PERIODS IS NULL OR TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE IS NULL)
;
  
ALTER TABLE csr.ind ADD CONSTRAINT CHK_IND_TOLERANCE CHECK (
	TOLERANCE_TYPE = 0
	OR (TOLERANCE_TYPE IN (1, 2) AND PCT_UPPER_TOLERANCE IS NOT NULL AND PCT_LOWER_TOLERANCE IS NOT NULL)
	OR (TOLERANCE_TYPE IN (3, 4) AND TOLERANCE_NUMBER_OF_PERIODS IS NOT NULL AND TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE IS NOT NULL)	
);
ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_NUMBER_OF_PERIODS CHECK (
    TOLERANCE_TYPE = 0
	OR (TOLERANCE_TYPE = 1 AND TOLERANCE_NUMBER_OF_PERIODS >= 1 AND TOLERANCE_NUMBER_OF_PERIODS <= 99)
	OR (TOLERANCE_TYPE = 2 AND TOLERANCE_NUMBER_OF_PERIODS >= 1 AND TOLERANCE_NUMBER_OF_PERIODS <= 8)
	OR (TOLERANCE_TYPE = 3 AND TOLERANCE_NUMBER_OF_PERIODS >= 3 AND TOLERANCE_NUMBER_OF_PERIODS <= 99)
	OR (TOLERANCE_TYPE = 4 AND TOLERANCE_NUMBER_OF_PERIODS >= 3 AND TOLERANCE_NUMBER_OF_PERIODS <= 8)
);
ALTER TABLE csr.ind ADD CONSTRAINT CHK_TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE CHECK (
	TOLERANCE_TYPE < 3
	OR (TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE >= 0 AND TOLERANCE_NUMBER_OF_STANDARD_DEVIATIONS_FROM_AVERAGE <= 5)
);


grant select,delete on csr.user_profile to chain;








UPDATE csr.region_tree
SET is_system_managed = 1
WHERE is_fund = 1 OR region_tree_root_sid in (SELECT region_sid FROM csr.secondary_region_tree_ctrl);






@..\issue_pkg
@..\indicator_pkg
@..\unit_test_pkg
@..\customer_pkg
@..\region_tree_pkg
@..\core_access_pkg


@..\issue_body
@..\indicator_body
@..\csrimp\imp_body
@..\csr_user_body
@..\unit_test_body
@..\customer_body
@..\region_tree_body
@..\region_body
@..\core_access_body



@update_tail
