--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      TEST
-- Project :      newSchema.dm1
-- Author :       TEST
--
-- Date Created : Sunday, September 06, 2009 15:25:11
-- Target DBMS : Oracle 10g
--

DROP TABLE SUPPLIER.NP_COMPONENT_DESCRIPTION CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_EVIDENCE_CLASS CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_EVIDENCE_TYPE CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_KINGDOM CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_PART_DESCRIPTION CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_PART_EVIDENCE CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_PP_GROUP_MEMBER CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_PRODUCT_ANSWERS CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_PRODUCTION_PROCESS CASCADE CONSTRAINTS
;
DROP TABLE SUPPLIER.NP_PRODUCTION_PROCESS_GROUP CASCADE CONSTRAINTS
;
DROP SEQUENCE SUPPLIER.NP_PPROC_GROUP_ID_SEQ;


-- 
-- SEQUENCE: NP_PPROC_GROUP_ID_SEQ 
--

CREATE SEQUENCE NP_PPROC_GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: SUPPLIER.NP_COMPONENT_DESCRIPTION 
--

CREATE TABLE SUPPLIER.NP_COMPONENT_DESCRIPTION(
    PRODUCT_PART_ID                   NUMBER(10, 0)     NOT NULL,
    COMMON_NAME                       VARCHAR2(1024),
    SPECIES                           VARCHAR2(255),
    GENUS                             VARCHAR2(255),
    DESCRIPTION                       VARCHAR2(1024)    NOT NULL,
    COUNTRY_OF_ORIGIN                 VARCHAR2(8)       NOT NULL,
    REGION                            VARCHAR2(255),
    NP_KINGDOM_ID                     NUMBER(10, 0)     NOT NULL,
    NATURAL_CLAIM                     NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    COMPONENT_CODE                    VARCHAR2(255),
    COLLECTION_DESC                   CLOB              NOT NULL,
    NP_PRODUCTION_PROCESS_GROUP_ID    NUMBER(10, 0),
    ENV_PROCESS_SAFEGUARD_DESC        CLOB,
    ENV_HARVEST_SAFEGUARD_DESC        CLOB              NOT NULL,
    CONSTRAINT PK119 PRIMARY KEY (PRODUCT_PART_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_EVIDENCE_CLASS 
--

CREATE TABLE SUPPLIER.NP_EVIDENCE_CLASS(
    NP_EVIDENCE_CLASS_ID    NUMBER(10, 0)     NOT NULL,
    NAME                    VARCHAR2(255)     NOT NULL,
    DESCRIPTION             VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK114 PRIMARY KEY (NP_EVIDENCE_CLASS_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_EVIDENCE_TYPE 
--

CREATE TABLE SUPPLIER.NP_EVIDENCE_TYPE(
    NP_EVIDENCE_TYPE_ID    NUMBER(10, 0)     NOT NULL,
    NAME                   VARCHAR2(255)     NOT NULL,
    DESCRIPTION            VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK118 PRIMARY KEY (NP_EVIDENCE_TYPE_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_KINGDOM 
--

CREATE TABLE SUPPLIER.NP_KINGDOM(
    NP_KINGDOM_ID    NUMBER(10, 0)     NOT NULL,
    NAME             VARCHAR2(255)     NOT NULL,
    DESCRIPTION      VARCHAR2(1024)    NOT NULL,
    CONSTRAINT PK120 PRIMARY KEY (NP_KINGDOM_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_PART_DESCRIPTION 
--

CREATE TABLE SUPPLIER.NP_PART_DESCRIPTION(
    PRODUCT_PART_ID    NUMBER(10, 0)     NOT NULL,
    DESCRIPTION        VARCHAR2(1024)    NOT NULL,
    PART_CODE          VARCHAR2(255),
    NATURAL_CLAIM      NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK30_1 PRIMARY KEY (PRODUCT_PART_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_PART_EVIDENCE 
--

CREATE TABLE SUPPLIER.NP_PART_EVIDENCE(
    PRODUCT_PART_ID         NUMBER(10, 0)    NOT NULL,
    DETAILS                 CLOB             NOT NULL,
    DOCUMENT_GROUP_ID       NUMBER(10, 0),
    NP_EVIDENCE_CLASS_ID    NUMBER(10, 0)    NOT NULL,
    NP_EVIDENCE_TYPE_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK116 PRIMARY KEY (PRODUCT_PART_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_PP_GROUP_MEMBER 
--

CREATE TABLE SUPPLIER.NP_PP_GROUP_MEMBER(
    NP_PRODUCTION_PROCESS_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    NP_PRODUCTION_PROCESS_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK125 PRIMARY KEY (NP_PRODUCTION_PROCESS_GROUP_ID, NP_PRODUCTION_PROCESS_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_PRODUCT_ANSWERS 
--

CREATE TABLE SUPPLIER.NP_PRODUCT_ANSWERS(
    PRODUCT_ID    NUMBER(10, 0)    NOT NULL,
    NOTE          CLOB,
    CONSTRAINT PK56_1 PRIMARY KEY (PRODUCT_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_PRODUCTION_PROCESS 
--

CREATE TABLE SUPPLIER.NP_PRODUCTION_PROCESS(
    NP_PRODUCTION_PROCESS_ID    NUMBER(10, 0)     NOT NULL,
    NAME                        VARCHAR2(255)     NOT NULL,
    DESCRIPTION                 VARCHAR2(1024),
    CONSTRAINT PK117 PRIMARY KEY (NP_PRODUCTION_PROCESS_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_PRODUCTION_PROCESS_GROUP 
--

CREATE TABLE SUPPLIER.NP_PRODUCTION_PROCESS_GROUP(
    NP_PRODUCTION_PROCESS_GROUP_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK117_1 PRIMARY KEY (NP_PRODUCTION_PROCESS_GROUP_ID)
)
;



-- 
-- TABLE: SUPPLIER.NP_COMPONENT_DESCRIPTION 
--

ALTER TABLE SUPPLIER.NP_COMPONENT_DESCRIPTION ADD CONSTRAINT REFNP_KINGDOM194 
    FOREIGN KEY (NP_KINGDOM_ID)
    REFERENCES SUPPLIER.NP_KINGDOM(NP_KINGDOM_ID)
;

ALTER TABLE SUPPLIER.NP_COMPONENT_DESCRIPTION ADD CONSTRAINT REFNP_PRODUCTION_PROCESS_GR195 
    FOREIGN KEY (NP_PRODUCTION_PROCESS_GROUP_ID)
    REFERENCES SUPPLIER.NP_PRODUCTION_PROCESS_GROUP(NP_PRODUCTION_PROCESS_GROUP_ID)
;

-- 
-- TABLE: SUPPLIER.NP_PART_EVIDENCE 
--

ALTER TABLE SUPPLIER.NP_PART_EVIDENCE ADD CONSTRAINT REFNP_EVIDENCE_CLASS199 
    FOREIGN KEY (NP_EVIDENCE_CLASS_ID)
    REFERENCES SUPPLIER.NP_EVIDENCE_CLASS(NP_EVIDENCE_CLASS_ID)
;

ALTER TABLE SUPPLIER.NP_PART_EVIDENCE ADD CONSTRAINT REFNP_EVIDENCE_TYPE200 
    FOREIGN KEY (NP_EVIDENCE_TYPE_ID)
    REFERENCES SUPPLIER.NP_EVIDENCE_TYPE(NP_EVIDENCE_TYPE_ID)
;

-- 
-- TABLE: SUPPLIER.NP_PP_GROUP_MEMBER 
--

ALTER TABLE SUPPLIER.NP_PP_GROUP_MEMBER ADD CONSTRAINT REFNP_PRODUCTION_PROCESS202 
    FOREIGN KEY (NP_PRODUCTION_PROCESS_ID)
    REFERENCES SUPPLIER.NP_PRODUCTION_PROCESS(NP_PRODUCTION_PROCESS_ID)
;

ALTER TABLE SUPPLIER.NP_PP_GROUP_MEMBER ADD CONSTRAINT REFNP_PRODUCTION_PROCESS_GR203 
    FOREIGN KEY (NP_PRODUCTION_PROCESS_GROUP_ID)
    REFERENCES SUPPLIER.NP_PRODUCTION_PROCESS_GROUP(NP_PRODUCTION_PROCESS_GROUP_ID)
;


