REM INSERTING into CT.EIO_GROUP
SET DEFINE OFF;
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100001,'Agricultural goods',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100002,'Ceramic goods',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100003,'Chemicals',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100004,'Construction materials and products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100005,'Electronics',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100006,'Food and Drink products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100007,'Glass and glass products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100008,'Industrial gases and dyes',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100009,'Leather products and footwear',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100010,'Manufactured products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100011,'Metals and metal products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100012,'Mining and extraction',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100013,'Paints, varnishes and printing ink',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100014,'Pharmaceuticals',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100015,'Plastics products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100016,'Pulp and paper',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100017,'Rubber products',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100018,'Services',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100019,'Textiles',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100020,'Utilities',0);
Insert into CT.EIO_GROUP (EIO_GROUP_ID,DESCRIPTION,HIDE) values (100021,'System',1);
